<?php
if (!function_exists('hr_t')) {
  function hr_t($key, $fallback = '') { return lang_text($key, $fallback); }
}
if (!function_exists('hr_h')) {
  function hr_h($key, $fallback = '') { return htmlspecialchars((string) hr_t($key, $fallback), ENT_QUOTES, 'UTF-8'); }
}
if (!function_exists('hr_js')) {
  function hr_js($key, $fallback = '') { return json_encode(hr_t($key, $fallback), JSON_HEX_TAG | JSON_HEX_APOS | JSON_HEX_AMP | JSON_HEX_QUOT); }
}
if (session_status() === PHP_SESSION_NONE) session_start();
include "../../inc/config.php";
session_check_json();
function kt_json($s,$m='',$x=array()){header('Content-Type: application/json; charset=utf-8');$p=array('status'=>$s);if($m!=='')$p[$s==='good'?'message':'error_message']=$m;foreach($x as $k=>$v)$p[$k]=$v;echo json_encode($p);exit;}
function kt_h($v){return htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');}
function kt_p($k,$d=''){return isset($_POST[$k])?$_POST[$k]:$d;}
function kt_user(){return isset($_SESSION['username'])&&$_SESSION['username']!==''?$_SESSION['username']:'admin';}
function kt_select2($rows,$id,$cb){$out=array();foreach($rows as $r)$out[]=array('id'=>$r->$id,'text'=>$cb($r));header('Content-Type: application/json; charset=utf-8');echo json_encode(array('results'=>$out));exit;}
function kt_no(){global $db;$prefix='KPI-TPL-'.date('Ym');$r=$db->fetch("SELECT template_no FROM erp_kpi_template WHERE template_no LIKE ? ORDER BY template_no DESC LIMIT 1",array($prefix.'%'));$n=$r?((int)substr($r->template_no,-4)+1):1;return $prefix.sprintf('%04d',$n);}
function kt_filters($src){return array('as_of'=>isset($src['as_of_date'])&&$src['as_of_date']!==''?$src['as_of_date']:date('Y-m-d'),'template_type'=>isset($src['template_type'])?trim($src['template_type']):'','cycle_type'=>isset($src['cycle_type'])?trim($src['cycle_type']):'','department_code'=>isset($src['department_code'])?trim($src['department_code']):'','job_title_id'=>isset($src['job_title_id'])?trim($src['job_title_id']):'','employee_group'=>isset($src['employee_group'])?trim($src['employee_group']):'','status'=>isset($src['status'])?trim($src['status']):'','weight_status'=>isset($src['weight_status'])?trim($src['weight_status']):'','keyword'=>isset($src['keyword'])?trim($src['keyword']):'');}
function kt_where($f,&$p){$w=" WHERE t.effective_from<=? AND t.effective_to>=? ";array_push($p,$f['as_of'],$f['as_of']);foreach(array('template_type','cycle_type','department_code','employee_group','status') as $k){if($f[$k]!==''){$w.=" AND t.$k=? ";$p[]=$f[$k];}}if($f['job_title_id']!==''){$w.=" AND t.job_title_id=? ";$p[]=(int)$f['job_title_id'];}if($f['weight_status']==='COMPLETE')$w.=" AND ROUND(t.total_weight,2)=100.00 ";elseif($f['weight_status']==='INCOMPLETE')$w.=" AND ROUND(t.total_weight,2)<>100.00 ";if($f['keyword']!==''){$kw='%'.$f['keyword'].'%';$w.=" AND (t.template_no LIKE ? OR t.template_name LIKE ? OR d.nm_dept LIKE ? OR jt.job_title_name LIKE ? OR t.sap_reference LIKE ?) ";for($i=0;$i<5;$i++)$p[]=$kw;}return $w;}
function kt_row($id){global $db;return $db->fetch("SELECT t.*,d.nm_dept,jt.job_title_code,jt.job_title_name,o.employee_no owner_no,o.full_name owner_name FROM erp_kpi_template t LEFT JOIN dept d ON d.kd_dept=t.department_code LEFT JOIN erp_job_title jt ON jt.id=t.job_title_id LEFT JOIN erp_employee_master o ON o.id=t.owner_employee_id WHERE t.id=? LIMIT 1",array((int)$id));}
$act=isset($_GET['act'])?$_GET['act']:'';
switch($act){
case 'department_search':$t=trim(kt_p('term'));$like='%'.$t.'%';$rows=$db->query("SELECT kd_dept,nm_dept FROM dept WHERE (?='' OR kd_dept LIKE ? OR nm_dept LIKE ?) ORDER BY kd_dept LIMIT 50",array($t,$like,$like));kt_select2($rows,'kd_dept',function($r){return $r->kd_dept.' - '.$r->nm_dept;});
case 'job_title_search':$t=trim(kt_p('term'));$dept=trim(kt_p('department_code'));$like='%'.$t.'%';$sql="SELECT id,job_title_code,job_title_name,job_level FROM erp_job_title WHERE (?='' OR job_title_code LIKE ? OR job_title_name LIKE ?) ";$p=array($t,$like,$like);if($dept!==''){$sql.=" AND department_code=? ";$p[]=$dept;}$rows=$db->query($sql." ORDER BY job_level DESC,job_title_code LIMIT 50",$p);kt_select2($rows,'id',function($r){return $r->job_title_code.' - '.$r->job_title_name.' ['.$r->job_level.']';});
case 'employee_search':$t=trim(kt_p('term'));$like='%'.$t.'%';$rows=$db->query("SELECT id,employee_no,full_name,department_code FROM erp_employee_master WHERE (?='' OR employee_no LIKE ? OR full_name LIKE ? OR department_code LIKE ?) ORDER BY employee_no LIMIT 50",array($t,$like,$like,$like));kt_select2($rows,'id',function($r){return $r->employee_no.' - '.$r->full_name.' ['.$r->department_code.']';});
case 'get':
  $r=kt_row((int)kt_p('id'));if(!$r)kt_json('error','KPI Template tidak ditemukan.');
  $data=(array)$r;$data['department_text']=$r->department_code?($r->department_code.' - '.$r->nm_dept):'';$data['job_title_text']=$r->job_title_id?($r->job_title_code.' - '.$r->job_title_name):'';$data['owner_text']=$r->owner_employee_id?($r->owner_no.' - '.$r->owner_name):'';
  $rows=$db->query("SELECT * FROM erp_kpi_template_detail WHERE kpi_template_id=? ORDER BY line_no,id",array((int)$r->id));
  $lines=array();
  foreach($rows as $line)$lines[]=(array)$line;
  kt_json('good','',array('data'=>$data,'lines'=>$lines));
case 'save':
  $id=(int)kt_p('id');$user=kt_user();$no=trim(kt_p('template_no'))!==''?strtoupper(trim(kt_p('template_no'))):kt_no();
  $name=trim(kt_p('template_name'));if($name==='')kt_json('error','Template Name wajib diisi.');
  $dup=$db->fetch("SELECT id FROM erp_kpi_template WHERE template_no=? AND id<>? LIMIT 1",array($no,$id));if($dup)kt_json('error','Template No sudah digunakan.');
  $codes=isset($_POST['kpi_code'])?$_POST['kpi_code']:array();$names=isset($_POST['kpi_name'])?$_POST['kpi_name']:array();$weights=isset($_POST['weight'])?$_POST['weight']:array();
  $lineData=array();$total=0;$line=1;for($i=0;$i<count($codes);$i++){if(trim($codes[$i])===''&&trim($names[$i])==='')continue;if(trim($codes[$i])===''||trim($names[$i])==='')kt_json('error','KPI Code dan KPI Name wajib diisi pada semua detail.');$w=(float)$weights[$i];if($w<=0)kt_json('error','Weight detail KPI harus lebih dari 0.');$total+=$w;$lineData[]=array('line_no'=>$line++,'kpi_code'=>strtoupper(trim($codes[$i])),'kpi_name'=>trim($names[$i]),'kpi_perspective'=>$_POST['kpi_perspective'][$i],'measure_type'=>$_POST['measure_type'][$i],'target_value'=>$_POST['target_value'][$i]!==''?(float)$_POST['target_value'][$i]:null,'target_text'=>trim($_POST['target_text'][$i]),'unit_of_measure'=>trim($_POST['unit_of_measure'][$i]),'weight'=>$w,'scoring_direction'=>$_POST['scoring_direction'][$i],'minimum_score'=>$_POST['minimum_score'][$i]!==''?(float)$_POST['minimum_score'][$i]:0,'maximum_score'=>$_POST['maximum_score'][$i]!==''?(float)$_POST['maximum_score'][$i]:100,'data_source'=>trim($_POST['data_source'][$i]),'review_frequency'=>$_POST['review_frequency'][$i],'mandatory'=>$_POST['mandatory'][$i],'remarks'=>trim($_POST['detail_remarks'][$i]));}
  if(!count($lineData))kt_json('error','Minimal satu detail KPI wajib diisi.');
  $data=array('template_no'=>$no,'template_name'=>$name,'template_type'=>kt_p('template_type','JOB_TITLE'),'cycle_type'=>kt_p('cycle_type','ANNUAL'),'appraisal_period'=>kt_p('appraisal_period','ANNUAL'),'department_code'=>kt_p('department_code')!==''?kt_p('department_code'):null,'job_title_id'=>kt_p('job_title_id')!==''?(int)kt_p('job_title_id'):null,'employee_group'=>kt_p('employee_group','ALL'),'effective_from'=>kt_p('effective_from',date('Y-m-d')),'effective_to'=>kt_p('effective_to','9999-12-31'),'total_weight'=>$total,'status'=>kt_p('status','DRAFT'),'approval_required'=>kt_p('approval_required','Y'),'calibration_required'=>kt_p('calibration_required','Y'),'owner_employee_id'=>kt_p('owner_employee_id')!==''?(int)kt_p('owner_employee_id'):null,'sap_reference'=>trim(kt_p('sap_reference')),'remarks'=>trim(kt_p('remarks')),'updated_by'=>$user,'updated_at'=>date('Y-m-d H:i:s'));
  if(abs($total-100)>0.01&&$data['status']==='ACTIVE')kt_json('error','Template ACTIVE harus memiliki total weight 100%.');
  if($id>0){$ok=$db->update('erp_kpi_template',$data,'id',$id);}else{$data['created_by']=$user;$ok=$db->insert('erp_kpi_template',$data);$id=(int)$db->last_insert_id();}
  if(!$ok)kt_json('error',$db->getErrorMessage()?:hr_t('hr_kpi_template_save_failed', 'KPI Template failed to save.'));
  $db->delete('erp_kpi_template_detail','kpi_template_id',$id);
  foreach($lineData as $l){$l['kpi_template_id']=$id;$db->insert('erp_kpi_template_detail',$l);}
  if(function_exists('simpan_log'))simpan_log('User '.$user.' menyimpan KPI Template '.$no.' dengan total weight '.$total.' pada '.date('Y-m-d H:i:s'),$user);
  kt_json('good','KPI Template berhasil disimpan.',array('id'=>$id,'total_weight'=>$total));
case 'delete':
  $id=(int)kt_p('id');$r=kt_row($id);if(!$r)kt_json('error','KPI Template tidak ditemukan.');$db->delete('erp_kpi_template_detail','kpi_template_id',$id);$db->delete('erp_kpi_template','id',$id);if($db->getErrorMessage())kt_json('error',$db->getErrorMessage());kt_json('good','KPI Template berhasil dihapus.');
case 'detail':
  $r=kt_row((int)kt_p('id'));if(!$r){echo '<div class="alert alert-warning">KPI Template tidak ditemukan.</div>';break;}$lines=$db->query("SELECT * FROM erp_kpi_template_detail WHERE kpi_template_id=? ORDER BY line_no,id",array((int)$r->id));
  echo '<div class="kt-detail"><h3 style="margin-top:0">'.kt_h($r->template_no).' <small>'.kt_h($r->template_name).'</small></h3><span class="label label-primary">'.kt_h($r->template_type).'</span> <span class="label label-success">'.kt_h($r->status).'</span><hr><div class="row"><div class="col-sm-3"><b>'.hr_h('hr_department', 'Department').'</b><br>'.kt_h($r->department_code?($r->department_code.' - '.$r->nm_dept):'-').'</div><div class="col-sm-3"><b>'.hr_h('hr_job_title', 'Job Title').'</b><br>'.kt_h($r->job_title_code?($r->job_title_code.' - '.$r->job_title_name):'-').'</div><div class="col-sm-3"><b>Cycle</b><br>'.kt_h($r->cycle_type.' / '.$r->appraisal_period).'</div><div class="col-sm-3"><b>Total Weight</b><br><b>'.number_format((float)$r->total_weight,2).'%</b></div></div><hr><table class="table table-bordered table-condensed"><thead><tr><th>'.hr_h('common_no', 'No').'</th><th>KPI</th><th>Perspective</th><th>Target</th><th>Weight</th><th>Direction</th><th>Source</th><th>Frequency</th></tr></thead><tbody>';
  foreach($lines as $l){echo '<tr><td>'.(int)$l->line_no.'</td><td><b>'.kt_h($l->kpi_code).'</b><br><small>'.kt_h($l->kpi_name).'</small></td><td>'.kt_h($l->kpi_perspective).'<br><small>'.kt_h($l->measure_type).'</small></td><td>'.kt_h(($l->target_text?:$l->target_value).' '.($l->unit_of_measure?:'')).'</td><td class="text-right">'.number_format((float)$l->weight,2).'%</td><td>'.kt_h($l->scoring_direction).'</td><td>'.kt_h($l->data_source?:'-').'</td><td>'.kt_h($l->review_frequency).'</td></tr>';}
  echo '</tbody></table><p><b>SAP Ref:</b> '.kt_h($r->sap_reference?:'-').'<br><b>Remarks:</b> '.kt_h($r->remarks?:'-').'</p></div>';break;
case 'export':
  $initial=ob_get_level();ob_start();error_reporting(E_ALL & ~E_NOTICE & ~E_WARNING & ~E_DEPRECATED & ~E_USER_DEPRECATED);require_once "../../inc/lib/PHPExcel.php";require_once "../../inc/excel_style_helper.php";PHPExcel_Shared_File::setUseUploadTempDirectory(true);
  $f=kt_filters($_GET);$p=array();$w=kt_where($f,$p);$rows=$db->query("SELECT t.*,d.nm_dept,jt.job_title_code,jt.job_title_name,det.line_no,det.kpi_code,det.kpi_name,det.kpi_perspective,det.measure_type,det.target_value,det.target_text,det.unit_of_measure,det.weight,det.scoring_direction,det.data_source,det.review_frequency,det.mandatory FROM erp_kpi_template t LEFT JOIN dept d ON d.kd_dept=t.department_code LEFT JOIN erp_job_title jt ON jt.id=t.job_title_id LEFT JOIN erp_kpi_template_detail det ON det.kpi_template_id=t.id $w ORDER BY t.template_no,det.line_no",$p);
  $excel=new PHPExcel();$sheet=$excel->setActiveSheetIndex(0);$sheet->setTitle(erp_export_sheet_title('KPI Template'));$heads=array(erp_export_label("No"),erp_export_label("Template No"),erp_export_label("Template Name"),erp_export_label("Type"),erp_export_label("Cycle"),erp_export_label("Period"),erp_export_label("Department"),erp_export_label("Job Title"),erp_export_label("Employee Group"),erp_export_label("Valid From"),erp_export_label("Valid To"),erp_export_label("Total Weight"),erp_export_label("Status"),erp_export_label("Line"),erp_export_label("KPI Code"),erp_export_label("KPI Name"),erp_export_label("Perspective"),erp_export_label("Measure"),erp_export_label("Target Value"),erp_export_label("Target Text"),erp_export_label("UoM"),erp_export_label("Weight"),erp_export_label("Direction"),erp_export_label("Data Source"),erp_export_label("Frequency"),erp_export_label("Mandatory"),erp_export_label("SAP Ref"),erp_export_label("Updated By"));foreach($heads as $i=>$h)$sheet->setCellValue(PHPExcel_Cell::stringFromColumnIndex($i).'4',$h);
  $rn=5;$n=1;foreach($rows as $r){$vals=array($n++,$r->template_no,$r->template_name,$r->template_type,$r->cycle_type,$r->appraisal_period,$r->department_code.' - '.$r->nm_dept,$r->job_title_code.' - '.$r->job_title_name,$r->employee_group,$r->effective_from,$r->effective_to,$r->total_weight,$r->status,$r->line_no,$r->kpi_code,$r->kpi_name,$r->kpi_perspective,$r->measure_type,$r->target_value,$r->target_text,$r->unit_of_measure,$r->weight,$r->scoring_direction,$r->data_source,$r->review_frequency,$r->mandatory,$r->sap_reference,$r->updated_by?:$r->created_by);foreach($vals as $i=>$v)$sheet->setCellValue(PHPExcel_Cell::stringFromColumnIndex($i).$rn,$v);$rn++;}
  erpkb_excel_apply_standard_style($excel,array('sheet'=>$sheet,'title'=>erp_export_title('KPI TEMPLATE REPORT'),'header_row'=>4,'first_data_row'=>5,'last_data_row'=>max(5,$rn-1),'column_count'=>count($heads),'numeric_columns'=>array('L','N','S','V'),'filters'=>array('As Of'=>$f['as_of'],'Type'=>$f['template_type']?:erp_export_all_text(),'Status'=>$f['status']?:erp_export_all_text(),'Weight'=>$f['weight_status']?:erp_export_all_text()),'widths'=>array('B'=>18,'C'=>28,'G'=>26,'H'=>28,'O'=>18,'P'=>30,'T'=>28,'X'=>24,'AA'=>24,'AB'=>18)));
  $tmp=erpkb_excel_temp_file('kpi_template_');PHPExcel_IOFactory::createWriter($excel,'Excel2007')->save($tmp);$size=@filesize($tmp);$sig=@file_get_contents($tmp,false,null,0,2);if(!$size||$sig!=='PK'){@unlink($tmp);while(ob_get_level()>$initial)ob_end_clean();echo erp_t('export_excel_invalid_file','File Excel gagal dibuat dengan benar.');exit;}while(ob_get_level()>$initial)ob_end_clean();header('Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');header('Content-Disposition: attachment; filename="kpi_template_'.date('Ymd_His').'.xlsx"');header('Content-Length: '.$size);header('Cache-Control: max-age=0');header('Pragma: public');readfile($tmp);@unlink($tmp);exit;
default:kt_json('error','Action tidak dikenal.');
}
?>
