<?php
if (!function_exists('hr_t')) {
  function hr_t($key, $fallback = '') { return lang_text($key, $fallback); }
}
if (!function_exists('hr_h')) {
  function hr_h($key, $fallback = '') { return htmlspecialchars((string) hr_t($key, $fallback), ENT_QUOTES, 'UTF-8'); }
}
if (!function_exists('hr_js')) {
  function hr_js($key, $fallback = '') { return json_encode(hr_t($key, $fallback), JSON_HEX_TAG | JSON_HEX_APOS | JSON_HEX_AMP | JSON_HEX_QUOT); }
}
$defaultAsOf=date('Y-m-d');$canInsert=isset($role_act['insert_act'])&&$role_act['insert_act']==='Y';$canUpdate=isset($role_act['update_act'])&&$role_act['update_act']==='Y';$canDelete=isset($role_act['delete_act'])&&$role_act['delete_act']==='Y'; ?>
<style>
.kt-hero{background:linear-gradient(135deg,#1e3a8a,#0f766e);color:#fff;border-radius:14px;padding:22px;margin-bottom:16px;box-shadow:0 10px 24px rgba(30,58,138,.18)}.kt-hero h1{margin:0 0 6px;font-size:27px;font-weight:700}.kt-hero p{margin:0;color:#dbeafe}.kt-card{border-radius:12px;background:#fff;border:1px solid #e5edf5;box-shadow:0 5px 16px rgba(15,23,42,.05);margin-bottom:14px}.kt-kpi{padding:14px;border-radius:12px;background:#f8fafc;border:1px solid #dbeafe;min-height:76px}.kt-kpi span{display:block;color:#64748b;font-size:12px}.kt-kpi b{font-size:21px;color:#0f172a}.kt-kpi.good{background:#ecfdf5;border-color:#bbf7d0}.kt-kpi.warn{background:#fff7ed;border-color:#fed7aa}#dtb_kpi_template th,#dtb_kpi_template td{font-size:12px;vertical-align:middle}.select2-container{width:100%!important}.kt-action{white-space:nowrap}.required-label:after{content:' *';color:#dd4b39}.kt-detail{background:#fff;border:1px solid #e5e7eb;border-radius:12px;padding:18px}#modal_kt .modal-body,#modal_kt_detail .modal-body{max-height:calc(100vh - 180px);overflow-y:auto}.kt-line-table th,.kt-line-table td{font-size:12px;vertical-align:middle}.kt-line-table input,.kt-line-table select{min-width:110px}.kt-line-table .wide{min-width:180px}.kt-total-ok{color:#16a34a;font-weight:700}.kt-total-bad{color:#dc2626;font-weight:700}
</style>
<section class="content-header"><h1><?=hr_h('hr_kpi_template', 'KPI Template');?> <small>SAP HCM Performance Management</small></h1><ol class="breadcrumb"><li><a href="<?=base_index();?>"><i class="fa fa-dashboard"></i> <?=hr_h('common_home', 'Home');?></a></li><li>Human Resource</li><li>Performance Management</li><li class="active"><?=hr_h('hr_kpi_template', 'KPI Template');?></li></ol></section>
<section class="content">
<div class="kt-hero"><div class="row"><div class="col-md-8"><h1>KPI Template Workbench</h1><p>Master template KPI per department, job title, employee group, cycle appraisal, lengkap dengan bobot, target, sumber data, dan frekuensi review.</p></div><div class="col-md-4 text-right"><?php if($canInsert){ ?><button id="btn_open_kt" class="btn btn-warning"><i class="fa fa-plus"></i> Create KPI Template</button><?php } ?> <button id="btn_export_kt" class="btn btn-success"><i class="fa fa-file-excel-o"></i> <?=hr_h('common_export_excel', 'Export Excel');?></button></div></div></div>
<div class="row"><div class="col-sm-2"><div class="kt-kpi"><span>Total Template</span><b id="kpi_total">0</b></div></div><div class="col-sm-2"><div class="kt-kpi good"><span><?=hr_h('hr_active', 'Active');?></span><b id="kpi_active">0</b></div></div><div class="col-sm-2"><div class="kt-kpi good"><span>Weight 100%</span><b id="kpi_complete">0</b></div></div><div class="col-sm-2"><div class="kt-kpi warn"><span>Weight Issue</span><b id="kpi_incomplete">0</b></div></div><div class="col-sm-2"><div class="kt-kpi"><span>Departments</span><b id="kpi_dept">0</b></div></div><div class="col-sm-2"><div class="kt-kpi"><span>Standard</span><b>SAP KPI</b></div></div></div>
<div class="box kt-card"><div class="box-header"><h3 class="box-title"><i class="fa fa-filter"></i> Filter KPI Template</h3></div><div class="box-body"><form class="form-horizontal" onsubmit="return false;">
  <div class="form-group"><label class="control-label col-lg-2">As Of Date</label><div class="col-lg-2"><div class="input-group date kt-date"><input id="filter_as_of_date" class="form-control" value="<?=$defaultAsOf;?>"><span class="input-group-addon"><span class="glyphicon glyphicon-calendar"></span></span></div></div><label class="control-label col-lg-1">Type</label><div class="col-lg-2"><select id="filter_template_type" class="form-control"><option value="">All</option><option>CORPORATE</option><option>DEPARTMENT</option><option>JOB_TITLE</option><option>INDIVIDUAL</option><option>PROJECT</option></select></div><label class="control-label col-lg-1">Cycle</label><div class="col-lg-2"><select id="filter_cycle_type" class="form-control"><option value="">All</option><option>MONTHLY</option><option>QUARTERLY</option><option>HALF_YEAR</option><option>ANNUAL</option><option>PROBATION</option><option>PROJECT</option></select></div><label class="control-label col-lg-1"><?=hr_h('common_status', 'Status');?></label><div class="col-lg-1"><select id="filter_status" class="form-control"><option value="">All</option><option>DRAFT</option><option>ACTIVE</option><option>INACTIVE</option><option>ARCHIVED</option></select></div></div>
  <div class="form-group"><label class="control-label col-lg-2"><?=hr_h('hr_department', 'Department');?></label><div class="col-lg-3"><select id="filter_department_code" class="form-control"></select></div><label class="control-label col-lg-1"><?=hr_h('hr_job_title', 'Job Title');?></label><div class="col-lg-3"><select id="filter_job_title_id" class="form-control"></select></div><label class="control-label col-lg-1">Group</label><div class="col-lg-2"><select id="filter_employee_group" class="form-control"><option value="">All</option><option>ALL</option><option>DIRECTOR</option><option>MANAGER</option><option>STAFF</option><option>NON_STAFF</option><option>OPERATOR</option><option>CONTRACT</option><option>DAILY_WORKER</option><option>TRAINEE</option></select></div></div>
  <div class="form-group"><label class="control-label col-lg-2">Weight</label><div class="col-lg-2"><select id="filter_weight_status" class="form-control"><option value="">All</option><option value="COMPLETE">Complete 100%</option><option value="INCOMPLETE">Not 100%</option></select></div><label class="control-label col-lg-1">Keyword</label><div class="col-lg-5"><input id="filter_keyword" class="form-control" placeholder="Template no, name, department, job title, SAP ref"></div><div class="col-lg-2"><button id="btn_filter_kt" class="btn btn-primary"><i class="fa fa-filter"></i> <?=hr_h('common_filter', 'Filter');?></button> <button id="btn_reset_kt" class="btn btn-default"><i class="fa fa-refresh"></i></button></div></div>
</form></div></div>
<div class="box kt-card"><div class="box-body"><div class="alert alert-warning error_data_delete" style="display:none"><button type="button" class="close hide_alert_notif">&times;</button><span class="isi_warning_delete"></span></div><div class="table-responsive"><table id="dtb_kpi_template" class="table table-bordered table-striped" style="width:100%"><thead><tr><th><?=hr_h('common_no', 'No');?></th><th><?=hr_h('common_action', 'Action');?></th><th>Template No</th><th>Template Name</th><th>Type</th><th><?=hr_h('hr_department', 'Department');?></th><th><?=hr_h('hr_job_title', 'Job Title');?></th><th>Cycle</th><th>Weight</th><th>Items</th><th><?=hr_h('common_status', 'Status');?></th><th>Updated</th></tr></thead><tbody></tbody></table></div></div></div>
<div id="modal_kt" class="modal fade"><div class="modal-dialog modal-lg" style="width:96%"><div class="modal-content"><form id="form_kt"><input type="hidden" name="id" id="kt_id"><div class="modal-header"><button type="button" class="close" data-dismiss="modal">&times;</button><h4 class="modal-title">Create KPI Template</h4></div><div class="modal-body">
  <div class="alert alert-info"><strong>SAP hint:</strong> Template KPI yang aktif sebaiknya memiliki total bobot 100%. Gunakan scope Department/Job Title agar appraisal employee otomatis memakai template yang tepat.</div>
  <div class="row"><div class="col-md-2 form-group"><label>Template No</label><input name="template_no" id="template_no" class="form-control" placeholder="Auto"></div><div class="col-md-4 form-group"><label class="required-label">Template Name</label><input name="template_name" id="template_name" class="form-control" required></div><div class="col-md-2 form-group"><label>Template Type</label><select name="template_type" id="template_type" class="form-control"><option>JOB_TITLE</option><option>DEPARTMENT</option><option>CORPORATE</option><option>INDIVIDUAL</option><option>PROJECT</option></select></div><div class="col-md-2 form-group"><label>Cycle</label><select name="cycle_type" id="cycle_type" class="form-control"><option>ANNUAL</option><option>MONTHLY</option><option>QUARTERLY</option><option>HALF_YEAR</option><option>PROBATION</option><option>PROJECT</option></select></div><div class="col-md-2 form-group"><label><?=hr_h('hr_period', 'Period');?></label><select name="appraisal_period" id="appraisal_period" class="form-control"><option>ANNUAL</option><option>H1</option><option>H2</option><option>Q1</option><option>Q2</option><option>Q3</option><option>Q4</option><option>PROBATION</option><option>SPECIAL</option></select></div></div>
  <div class="row"><div class="col-md-3 form-group"><label><?=hr_h('hr_department', 'Department');?></label><select name="department_code" id="department_code" class="form-control"></select></div><div class="col-md-3 form-group"><label><?=hr_h('hr_job_title', 'Job Title');?></label><select name="job_title_id" id="job_title_id" class="form-control"></select></div><div class="col-md-2 form-group"><label>Employee Group</label><select name="employee_group" id="employee_group" class="form-control"><option>ALL</option><option>DIRECTOR</option><option>MANAGER</option><option>STAFF</option><option>NON_STAFF</option><option>OPERATOR</option><option>CONTRACT</option><option>DAILY_WORKER</option><option>TRAINEE</option></select></div><div class="col-md-2 form-group"><label>Effective From</label><input name="effective_from" id="effective_from" class="form-control kt-date-field" value="<?=date('Y-m-d');?>"></div><div class="col-md-2 form-group"><label>Effective To</label><input name="effective_to" id="effective_to" class="form-control kt-date-field" value="9999-12-31"></div></div>
  <div class="row"><div class="col-md-2 form-group"><label><?=hr_h('common_status', 'Status');?></label><select name="status" id="status" class="form-control"><option>DRAFT</option><option>ACTIVE</option><option>INACTIVE</option><option>ARCHIVED</option></select></div><div class="col-md-2 form-group"><label>Approval Required</label><select name="approval_required" id="approval_required" class="form-control"><option>Y</option><option>N</option></select></div><div class="col-md-2 form-group"><label>Calibration</label><select name="calibration_required" id="calibration_required" class="form-control"><option>Y</option><option>N</option></select></div><div class="col-md-3 form-group"><label>Owner</label><select name="owner_employee_id" id="owner_employee_id" class="form-control"></select></div><div class="col-md-3 form-group"><label>SAP Reference</label><input name="sap_reference" id="sap_reference" class="form-control"></div></div>
  <div class="row"><div class="col-md-12 form-group"><label><?=hr_h('common_remarks', 'Remarks');?></label><textarea name="remarks" id="remarks" class="form-control" rows="2"></textarea></div></div>
  <h4>KPI Items <small>Total Weight: <span id="kt_total_weight" class="kt-total-bad">0.00%</span></small> <button type="button" id="btn_add_line" class="btn btn-xs btn-success pull-right"><i class="fa fa-plus"></i> Add KPI Item</button></h4>
  <div class="table-responsive"><table class="table table-bordered kt-line-table"><thead><tr><th><?=hr_h('common_no', 'No');?></th><th>KPI Code</th><th>KPI Name</th><th>Perspective</th><th>Measure</th><th>Target</th><th>Text</th><th>UoM</th><th>Weight</th><th>Direction</th><th>Source</th><th>Freq</th><th>Mandatory</th><th><?=hr_h('common_remarks', 'Remarks');?></th><th></th></tr></thead><tbody id="kt_lines"></tbody></table></div>
</div><div class="modal-footer"><button type="button" class="btn btn-default" data-dismiss="modal"><?=hr_h('common_cancel', 'Cancel');?></button><button type="submit" class="btn btn-primary"><i class="fa fa-save"></i> Save KPI Template</button></div></form></div></div></div>
<div id="modal_kt_detail" class="modal fade"><div class="modal-dialog modal-lg" style="width:94%"><div class="modal-content"><div class="modal-header"><button class="close" data-dismiss="modal">&times;</button><h4 class="modal-title">KPI Template Detail</h4></div><div class="modal-body" id="kt_detail_body"></div><div class="modal-footer"><button class="btn btn-default" data-dismiss="modal"><?=hr_h('common_close', 'Close');?></button></div></div></div></div>
</section>
<script src="<?=base_admin();?>assets/plugins/select2/select2.min.js"></script><script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
<script>
var ktCanUpdate='<?=$canUpdate?'Y':'N';?>',ktCanDelete='<?=$canDelete?'Y':'N';?>';
function ktError(m){$('.isi_warning_delete').text(m||<?=hr_js('hr_kpi_template_process_failed', 'KPI Template failed to process.');?>);$('.error_data_delete').fadeIn();}
function ktFilters(){return{as_of_date:$('#filter_as_of_date').val(),template_type:$('#filter_template_type').val(),cycle_type:$('#filter_cycle_type').val(),department_code:$('#filter_department_code').val(),job_title_id:$('#filter_job_title_id').val(),employee_group:$('#filter_employee_group').val(),status:$('#filter_status').val(),weight_status:$('#filter_weight_status').val(),keyword:$('#filter_keyword').val()};}
function ktAjax(s,act,p,parent){$(s).select2({width:'100%',allowClear:true,placeholder:p,dropdownParent:parent||$(document.body),ajax:{url:'<?=base_admin();?>modul/kpi_template/kpi_template_action.php?act='+act,type:'POST',dataType:'json',delay:250,data:function(q){return{term:q.term||'',department_code:$('#department_code').val()||$('#filter_department_code').val()||''};},processResults:function(d){return{results:d.results||[]};}}});}
function ktSet(sel,val,text){var e=$(sel);if(!val){e.val(null).trigger('change');return;}if(!e.find('option[value="'+val+'"]').length)e.append(new Option(text||val,val,true,true));e.val(val).trigger('change');}
function ktLine(l){l=l||{};var n=$('#kt_lines tr').length+1;var opts=function(arr,v){return arr.map(function(x){return '<option '+(x==(v||'')?'selected':'')+'>'+x+'</option>';}).join('');};return '<tr><td class="line-no">'+n+'</td><td><input name="kpi_code[]" class="form-control" value="'+(l.kpi_code||'')+'"></td><td><input name="kpi_name[]" class="form-control wide" value="'+(l.kpi_name||'')+'"></td><td><select name="kpi_perspective[]" class="form-control">'+opts(['FINANCIAL','CUSTOMER','PROCESS','PEOPLE','QUALITY','SAFETY','COMPLIANCE','INNOVATION'],l.kpi_perspective||'PROCESS')+'</select></td><td><select name="measure_type[]" class="form-control">'+opts(['QUANTITATIVE','QUALITATIVE','MILESTONE'],l.measure_type||'QUANTITATIVE')+'</select></td><td><input name="target_value[]" type="number" step="0.0001" class="form-control" value="'+(l.target_value||'')+'"></td><td><input name="target_text[]" class="form-control wide" value="'+(l.target_text||'')+'"></td><td><input name="unit_of_measure[]" class="form-control" value="'+(l.unit_of_measure||'')+'"></td><td><input name="weight[]" type="number" step="0.01" class="form-control kt-weight" value="'+(l.weight||'0')+'"></td><td><select name="scoring_direction[]" class="form-control">'+opts(['HIGHER_BETTER','LOWER_BETTER','TARGET_BETTER','MILESTONE'],l.scoring_direction||'HIGHER_BETTER')+'</select><input name="minimum_score[]" type="hidden" value="'+(l.minimum_score||'0')+'"><input name="maximum_score[]" type="hidden" value="'+(l.maximum_score||'100')+'"></td><td><input name="data_source[]" class="form-control wide" value="'+(l.data_source||'')+'"></td><td><select name="review_frequency[]" class="form-control">'+opts(['DAILY','WEEKLY','MONTHLY','QUARTERLY','HALF_YEAR','ANNUAL','ON_DEMAND'],l.review_frequency||'MONTHLY')+'</select></td><td><select name="mandatory[]" class="form-control">'+opts(['Y','N'],l.mandatory||'Y')+'</select></td><td><input name="detail_remarks[]" class="form-control wide" value="'+(l.remarks||'')+'"></td><td><button type="button" class="btn btn-danger btn-xs btn-remove-line"><i class="fa fa-trash"></i></button></td></tr>';}
function ktRenumber(){var total=0;$('#kt_lines tr').each(function(i){$(this).find('.line-no').text(i+1);total+=parseFloat($(this).find('.kt-weight').val()||0)||0;});$('#kt_total_weight').text(total.toFixed(2)+'%').toggleClass('kt-total-ok',Math.abs(total-100)<.01).toggleClass('kt-total-bad',Math.abs(total-100)>=.01);}
function ktReset(){var f=$('#form_kt')[0];f.reset();$('#kt_id').val('');$('#template_no').val('');$('#status').val('DRAFT').trigger('change');$('#template_type').val('JOB_TITLE').trigger('change');$('#cycle_type').val('ANNUAL').trigger('change');$('#appraisal_period').val('ANNUAL').trigger('change');$('#employee_group').val('ALL').trigger('change');$('#approval_required,#calibration_required').val('Y').trigger('change');$('#department_code,#job_title_id,#owner_employee_id').val(null).trigger('change');$('#effective_from').val('<?=date('Y-m-d');?>');$('#effective_to').val('9999-12-31');$('#kt_lines').empty().append(ktLine({weight:100,kpi_code:'KPI-',kpi_perspective:'PROCESS'}));ktRenumber();$('#modal_kt .modal-title').text('Create KPI Template');}
$(function(){
 if($.fn.datepicker){$('.kt-date,.kt-date-field').datepicker({format:'yyyy-mm-dd',autoclose:true,todayHighlight:true});}
 if($.fn.select2){$('#filter_template_type,#filter_cycle_type,#filter_employee_group,#filter_status,#filter_weight_status,#template_type,#cycle_type,#appraisal_period,#employee_group,#status,#approval_required,#calibration_required').select2({width:'100%',allowClear:true});ktAjax('#filter_department_code','department_search','Semua Department');ktAjax('#filter_job_title_id','job_title_search','Semua Job Title');ktAjax('#department_code','department_search','Pilih Department',$('#modal_kt'));ktAjax('#job_title_id','job_title_search','Pilih Job Title',$('#modal_kt'));ktAjax('#owner_employee_id','employee_search','Pilih Owner',$('#modal_kt'));}
 var dt=$('#dtb_kpi_template').DataTable({bProcessing:true,bServerSide:true,pageLength:25,dom:"<'row'<'col-sm-12'B>>"+"<'row'<'col-sm-6'l><'col-sm-6'f>>"+"<'row'<'col-sm-12'tr>>"+"<'row'<'col-sm-5'i><'col-sm-7'p>>",buttons:[{extend:'collection',text:<?=hr_js('common_export_data', 'Export Data');?>,buttons:['copyHtml5','excelHtml5','csvHtml5']}],columnDefs:[{targets:[0,1],orderable:false,searchable:false},{width:'42px',targets:0},{width:'115px',targets:1}],ajax:{url:'<?=base_admin();?>modul/kpi_template/kpi_template_data.php',type:'post',data:function(d){$.extend(d,ktFilters());},dataSrc:function(j){var k=j.kpi||{};$('#kpi_total').text(k.total||0);$('#kpi_active').text(k.active||0);$('#kpi_complete').text(k.complete||0);$('#kpi_incomplete').text(k.incomplete||0);$('#kpi_dept').text(k.departments||0);return j.data||[];},error:function(x){console.log(x.responseText);ktError(<?=hr_js('hr_kpi_template_load_failed', 'KPI Template data failed to load.');?>);}}});
 $('#btn_open_kt').click(function(){ktReset();$('#modal_kt').modal({backdrop:'static',keyboard:false});});$('#btn_filter_kt').click(function(){dt.draw();});$('#filter_keyword').keyup(function(e){if(e.keyCode===13)dt.draw();});$('#btn_reset_kt').click(function(){$('#filter_as_of_date').val('<?=$defaultAsOf;?>');$('#filter_template_type,#filter_cycle_type,#filter_department_code,#filter_job_title_id,#filter_employee_group,#filter_status,#filter_weight_status').val(null).trigger('change');$('#filter_keyword').val('');dt.draw();});$('#btn_export_kt').click(function(){window.location='<?=base_admin();?>modul/kpi_template/kpi_template_action.php?act=export&'+$.param(ktFilters());});$('.hide_alert_notif').click(function(){$('.error_data_delete').hide();});
 $('#btn_add_line').click(function(){$('#kt_lines').append(ktLine());ktRenumber();});$(document).on('click','.btn-remove-line',function(){$(this).closest('tr').remove();ktRenumber();});$(document).on('keyup change','.kt-weight',ktRenumber);
 $('#form_kt').submit(function(e){e.preventDefault();var btn=$(this).find('button[type=submit]');btn.prop('disabled',true).html('<i class="fa fa-spinner fa-spin"></i> <?=hr_h('common_saving', 'Saving...');?>');$.post('<?=base_admin();?>modul/kpi_template/kpi_template_action.php?act=save',$(this).serialize(),function(r){btn.prop('disabled',false).html('<i class="fa fa-save"></i> Save KPI Template');if(r.status==='good'){$('#modal_kt').modal('hide');dt.draw(false);Swal.fire('Saved','KPI Template tersimpan. Total weight '+r.total_weight+'%','success');}else ktError(r.error_message);},'json').fail(function(x){btn.prop('disabled',false).html('<i class="fa fa-save"></i> Save KPI Template');ktError(x.responseText);});});
 $(document).on('click','.btn-kt-detail',function(){$.post('<?=base_admin();?>modul/kpi_template/kpi_template_action.php?act=detail',{id:$(this).data('id')},function(h){$('#kt_detail_body').html(h);$('#modal_kt_detail').modal('show');});});
 $(document).on('click','.btn-kt-edit',function(){if(ktCanUpdate!=='Y')return;ktReset();$.post('<?=base_admin();?>modul/kpi_template/kpi_template_action.php?act=get',{id:$(this).data('id')},function(r){if(r.status!=='good'){ktError(r.error_message);return;}var d=r.data;Object.keys(d).forEach(function(k){var e=$('#'+k);if(e.length&&!['department_code','job_title_id','owner_employee_id'].includes(k))e.val(d[k]);});$('#kt_id').val(d.id);ktSet('#department_code',d.department_code,d.department_text);ktSet('#job_title_id',d.job_title_id,d.job_title_text);ktSet('#owner_employee_id',d.owner_employee_id,d.owner_text);$('#template_type,#cycle_type,#appraisal_period,#employee_group,#status,#approval_required,#calibration_required').trigger('change');$('#kt_lines').empty();(r.lines||[]).forEach(function(l){$('#kt_lines').append(ktLine(l));});ktRenumber();$('#modal_kt .modal-title').text('Edit KPI Template');$('#modal_kt').modal({backdrop:'static',keyboard:false});},'json');});
 $(document).on('click','.btn-kt-delete',function(){if(ktCanDelete!=='Y')return;var id=$(this).data('id'),no=$(this).data('no');Swal.fire({title:erpLang('confirm_delete_title','Delete Confirmation'),text:no,icon:'warning',showCancelButton:true,confirmButtonText:erpLang('common_delete','Delete'),cancelButtonText:erpLang('common_cancel','Cancel')}).then(function(x){if(!x.isConfirmed)return;$.post('<?=base_admin();?>modul/kpi_template/kpi_template_action.php?act=delete',{id:id},function(r){if(r.status==='good'){dt.draw(false);Swal.fire(erpLang('common_deleted','Deleted'),erpLang('common_deleted_message','Data deleted successfully.'),'success');}else ktError(r.error_message);},'json');});});
});
</script>
