<?php
if (session_status() === PHP_SESSION_NONE) session_start();
include "../../inc/config.php";
function mbm_action_h($value) { return htmlspecialchars((string)$value, ENT_QUOTES, 'UTF-8'); }
function mbm_action_num($value, $dec = 2) { return number_format((float)$value, $dec, ',', '.'); }
function mbm_action_input($key, $default = '') { return isset($_REQUEST[$key]) ? trim((string)$_REQUEST[$key]) : $default; }

function mbm_action_rows($db) {
  $tglAwal=mbm_action_input('tgl_awal',date('Y-m-01')); $tglAkhir=mbm_action_input('tgl_akhir',date('Y-m-d'));
  $material=mbm_action_input('material_code'); $plantId=mbm_action_input('plant_id'); $slocId=mbm_action_input('storage_location_id'); $binId=mbm_action_input('storage_bin_id'); $stockType=mbm_action_input('stock_type'); $keyword=mbm_action_input('keyword');
  $where=" WHERE b.kd_kategori='K03' "; $fp=array();
  if($material!==''){$where.=" AND b.kd_barang=? ";$fp[]=$material;} if($plantId!==''){$where.=" AND COALESCE(dt.plant_id,sl.plant_id)=? ";$fp[]=$plantId;} if($slocId!==''){$where.=" AND COALESCE(dt.storage_location_id,dt.destination_storage_location_id,sl.storage_location_id)=? ";$fp[]=$slocId;} if($binId!==''){$where.=" AND COALESCE(dt.storage_bin_id,dt.destination_storage_bin_id,sl.storage_bin_id)=? ";$fp[]=$binId;} if($stockType!==''){$where.=" AND COALESCE(dt.stock_type,dt.destination_stock_type,sl.stock_type,'UNRESTRICTED')=? ";$fp[]=$stockType;}
  if($keyword!==''){$where.=" AND (b.kd_barang LIKE ? OR b.nm_barang LIKE ? OR dt.no_ref LIKE ? OR dt.no_bpb LIKE ? OR dt.no_aju LIKE ? OR dt.no_dokpab LIKE ? OR dt.remark LIKE ?) ";$kw='%'.$keyword.'%';for($i=0;$i<7;$i++)$fp[]=$kw;}
  $movementExpr="CASE WHEN dt.id_detail IS NULL THEN 'IN' WHEN dt.direction='OUT' OR COALESCE(dt.qty,0)<0 OR dt.move_code IN ('102','122','201','221','261','262','532','551','601','602','702','712') THEN 'OUT' ELSE 'IN' END";
  $adjustExpr="CASE WHEN dt.move_code IN ('701','702','711','712') OR COALESCE(dt.ref_type,'') LIKE '%DIFF%' OR COALESCE(dt.ref_type,'') LIKE '%OPNAME%' OR COALESCE(dt.ref_type,'') LIKE '%ADJUST%' THEN 1 ELSE 0 END";
  $signedQtyExpr="CASE WHEN ($movementExpr)='OUT' THEN -ABS(COALESCE(dt.qty,0)) ELSE ABS(COALESCE(dt.qty,0)) END";
  $sql="SELECT b.id,b.kd_barang,b.nm_barang,b.satuan,ep.plant_code,es.storage_code,eb.bin_code,COALESCE(dt.stock_type,dt.destination_stock_type,sl.stock_type,'UNRESTRICTED') stock_type,
    COALESCE(SUM(CASE WHEN dt.document_date < ? THEN $signedQtyExpr ELSE 0 END),0) saldo_awal,
    COALESCE(SUM(CASE WHEN dt.document_date BETWEEN ? AND ? AND ($adjustExpr)=0 AND ($movementExpr)='IN' THEN ABS(COALESCE(dt.qty,0)) ELSE 0 END),0) pemasukan,
    COALESCE(SUM(CASE WHEN dt.document_date BETWEEN ? AND ? AND ($adjustExpr)=0 AND ($movementExpr)='OUT' THEN ABS(COALESCE(dt.qty,0)) ELSE 0 END),0) pengeluaran,
    COALESCE(SUM(CASE WHEN dt.document_date BETWEEN ? AND ? AND ($adjustExpr)=1 THEN $signedQtyExpr ELSE 0 END),0) penyesuaian,
    COALESCE(SUM(CASE WHEN dt.document_date <= ? THEN $signedQtyExpr ELSE 0 END),0) saldo_akhir,
    COALESCE(SUM(CASE WHEN dt.document_date BETWEEN ? AND ? THEN 1 ELSE 0 END),0) movement_lines
    FROM barang b
    LEFT JOIN detail_transaksi dt ON dt.kd_barang=b.kd_barang AND dt.document_date<=? AND (dt.posisi='GUDANG' OR dt.lokasi LIKE '%GUDANG%' OR dt.lokasi LIKE '%WAREHOUSE%' OR dt.posisi IS NULL) AND COALESCE(dt.is_reversal,0)=0
    LEFT JOIN stock_layer sl ON sl.id=dt.ref_id AND sl.kode=b.kd_barang
    LEFT JOIN erp_plant ep ON ep.id=COALESCE(dt.plant_id,sl.plant_id)
    LEFT JOIN erp_storage_location es ON es.id=COALESCE(dt.storage_location_id,dt.destination_storage_location_id,sl.storage_location_id)
    LEFT JOIN erp_storage_bin eb ON eb.id=COALESCE(dt.storage_bin_id,dt.destination_storage_bin_id,sl.storage_bin_id)
    $where GROUP BY b.id,b.kd_barang,b.nm_barang,b.satuan,ep.plant_code,es.storage_code,eb.bin_code,stock_type
    HAVING saldo_awal<>0 OR pemasukan<>0 OR pengeluaran<>0 OR penyesuaian<>0 OR saldo_akhir<>0 ORDER BY b.kd_barang ASC";
  $p=array($tglAwal.' 00:00:00',$tglAwal.' 00:00:00',$tglAkhir.' 23:59:59',$tglAwal.' 00:00:00',$tglAkhir.' 23:59:59',$tglAwal.' 00:00:00',$tglAkhir.' 23:59:59',$tglAkhir.' 23:59:59',$tglAwal.' 00:00:00',$tglAkhir.' 23:59:59',$tglAkhir.' 23:59:59');
  return $db->query($sql,array_merge($p,$fp));
}

$act=isset($_GET['act'])?$_GET['act']:'';
switch($act){
  case 'buat_view':
    header('Content-Type: application/json; charset=utf-8'); echo json_encode(array('status'=>'good','message'=>customs_t('capital_goods_mutation_source_message','Mutasi barang modal dibaca langsung dari detail_transaksi.'))); break;
  case 'show_detail':
    $tglAwal=mbm_action_input('tgl_awal',date('Y-m-01')); $tglAkhir=mbm_action_input('tgl_akhir',date('Y-m-d')); $kd=mbm_action_input('kd_barang'); $type=strtoupper(mbm_action_input('type','IN'));
    $movementExpr="CASE WHEN dt.direction='OUT' OR COALESCE(dt.qty,0)<0 OR dt.move_code IN ('102','122','201','221','261','262','532','551','601','602','702','712') THEN 'OUT' ELSE 'IN' END";
    $adjustExpr="CASE WHEN dt.move_code IN ('701','702','711','712') OR COALESCE(dt.ref_type,'') LIKE '%DIFF%' OR COALESCE(dt.ref_type,'') LIKE '%OPNAME%' OR COALESCE(dt.ref_type,'') LIKE '%ADJUST%' THEN 1 ELSE 0 END";
    $where=" WHERE dt.document_date BETWEEN ? AND ? AND dt.kd_barang=? AND (dt.posisi='GUDANG' OR dt.lokasi LIKE '%GUDANG%' OR dt.lokasi LIKE '%WAREHOUSE%' OR dt.posisi IS NULL) AND COALESCE(dt.is_reversal,0)=0 "; $p=array($tglAwal.' 00:00:00',$tglAkhir.' 23:59:59',$kd);
    if($type==='ADJ'){$where.=" AND ($adjustExpr)=1 ";$title='Detail Penyesuaian';}elseif($type==='OUT'){$where.=" AND ($adjustExpr)=0 AND ($movementExpr)='OUT' ";$title='Detail Pengeluaran';}else{$where.=" AND ($adjustExpr)=0 AND ($movementExpr)='IN' ";$title='Detail Pemasukan';}
    $q=$db->query("SELECT dt.*,b.nm_barang,b.satuan,ep.plant_code,es.storage_code,eb.bin_code,p.jenis_dokpab header_jenis_dokpab,p.tgl_dokpab FROM detail_transaksi dt LEFT JOIN barang b ON b.kd_barang=dt.kd_barang LEFT JOIN erp_plant ep ON ep.id=dt.plant_id LEFT JOIN erp_storage_location es ON es.id=COALESCE(dt.storage_location_id,dt.destination_storage_location_id) LEFT JOIN erp_storage_bin eb ON eb.id=COALESCE(dt.storage_bin_id,dt.destination_storage_bin_id) LEFT JOIN pemasukan p ON p.no_bpb=COALESCE(NULLIF(dt.no_bpb,''),NULLIF(dt.no_ref,''),NULLIF(dt.ref_pengganti,'')) OR p.no_aju=dt.no_aju $where ORDER BY dt.posting_date ASC,dt.id_detail ASC",$p);
    ?>
    <style>.mbm-detail-table th,.mbm-detail-table td{font-size:12px;vertical-align:middle!important}.mbm-detail-table th{background:#f8fafc}.mbm-detail-head{background:#f8fafc;border:1px solid #e5e7eb;border-radius:12px;padding:12px;margin-bottom:12px}.mbm-muted{color:#64748b;font-size:11px}</style>
    <div class="mbm-detail-head"><h4 style="margin:0"><?=mbm_action_h($title);?> Barang Modal - <?=mbm_action_h($kd);?></h4><small>Periode <?=mbm_action_h($tglAwal);?> s/d <?=mbm_action_h($tglAkhir);?></small></div>
    <div class="table-responsive"><table class="table table-bordered table-condensed mbm-detail-table"><thead><tr><th><?=customs_h('no','No');?></th><th>Material Document</th><th>Posting Date</th><th>Movement</th><th><?=customs_h('material','Material');?></th><th>Location</th><th><?=customs_h('customs_document','Dokumen Pabean');?></th><th>No BPB/Ref</th><th class="text-right">Qty</th><th>UOM</th><th><?=customs_h('remarks','Keterangan');?></th></tr></thead><tbody>
    <?php $no=1;$total=0;foreach($q as $k){$mv=($k->direction==='OUT'||(float)$k->qty<0||in_array($k->move_code,array('102','122','201','221','261','262','532','551','601','602','702','712')))?'OUT':'IN';$qty=abs((float)$k->qty);$total+=$qty;$loc=trim((string)$k->plant_code.' / '.(string)$k->storage_code.' / '.(string)$k->bin_code,' /');$customs=trim((string)($k->header_jenis_dokpab?:'').' '.(string)$k->no_dokpab.' / '.(string)$k->no_aju,' /'); ?>
      <tr><td><?=intval($no++);?></td><td><strong><?=mbm_action_h($k->no_ref ?: $k->no_bpb);?></strong><br><small class="mbm-muted">#<?=intval($k->id_detail);?></small></td><td><?=mbm_action_h($k->posting_date ?: $k->document_date);?></td><td><span class="label label-<?=$mv==='OUT'?'danger':'success';?>"><?=mbm_action_h($mv);?></span><br><small class="mbm-muted"><?=mbm_action_h($k->move_code.' '.$k->ref_type);?></small></td><td><strong><?=mbm_action_h($k->kd_barang);?></strong><br><small class="mbm-muted"><?=mbm_action_h($k->nm_barang);?></small></td><td><?=mbm_action_h($loc ?: ($k->lokasi ?: '-'));?><br><small class="mbm-muted"><?=mbm_action_h($k->stock_type ?: 'UNRESTRICTED');?></small></td><td><?=mbm_action_h($customs ?: '-');?><br><small class="mbm-muted"><?=mbm_action_h($k->tgl_dokpab ?: '');?></small></td><td><?=mbm_action_h($k->no_bpb ?: $k->ref_pengganti ?: '-');?></td><td class="text-right"><?=mbm_action_num($qty);?></td><td><?=mbm_action_h($k->uom ?: $k->satuan);?></td><td><?=mbm_action_h(trim((string)$k->remark.' '.(string)$k->reason));?></td></tr>
    <?php } if($no===1){ ?><tr><td colspan="11" class="text-center text-muted">Tidak ada detail transaksi.</td></tr><?php } ?>
    </tbody><tfoot><tr><th colspan="8" class="text-right">Total</th><th class="text-right"><?=mbm_action_num($total);?></th><th colspan="2"></th></tr></tfoot></table></div>
    <?php break;
  case 'excel':
    $initialOutputBufferLevel=ob_get_level(); ob_start(); ini_set('display_errors','0'); error_reporting(E_ALL & ~E_NOTICE & ~E_WARNING & ~E_DEPRECATED & ~E_USER_DEPRECATED);
    require "../../inc/lib/PHPExcel.php"; require_once "../../inc/excel_style_helper.php"; PHPExcel_Shared_File::setUseUploadTempDirectory(true);
    $tglAwal=mbm_action_input('tgl_awal',date('Y-m-01')); $tglAkhir=mbm_action_input('tgl_akhir',date('Y-m-d')); $companyName=defined('namaPT')?namaPT:(defined('shortTittle')?shortTittle:'NAMA_PT'); $rows=mbm_action_rows($db);
    $excel=new PHPExcel(); $sheet=$excel->setActiveSheetIndex(0); $sheet->setTitle(erp_export_sheet_title('Mutasi Modal')); $headerStart=6; $headerEnd=7; $firstDataRow=8; $lastCol='L';
    foreach(array(1=>'LAPORAN PERTANGGUNGJAWABAN MUTASI BARANG',2=>'LAPORAN PERTANGGUNGJAWABAN MUTASI BARANG MODAL',3=>'KAWASAN BERIKAT '.$companyName,4=>'PERIODE: '.$tglAwal.' SD '.$tglAkhir) as $row=>$text){$sheet->mergeCells('A'.$row.':L'.$row);$sheet->setCellValue('A'.$row,$text);}
    $headers=array(erp_export_label("No"),erp_export_label("KODE\\nBARANG"),erp_export_label("NAMA\\nBARANG"),erp_export_label("SAT"),erp_export_label("SALDO\\nAWAL\\n....(7)...."),erp_export_label("PEMASUKAN"),erp_export_label("PENGELUARAN"),erp_export_label("PENYESUAIAN\\n(ADJUSTMENT)"),erp_export_label("SALDO\\nAKHIR\\n....(12)...."),erp_export_label("STOCK\\nOPNAME\\n....(14)...."),erp_export_label("SELISIH"),erp_export_label("KETERANGAN")); $numbers=array('(3)','(4)','(5)','(6)','(8)','(9)','(10)','(11)','(13)','(15)','(16)','(17)');
    foreach($headers as $c=>$h)$sheet->setCellValueByColumnAndRow($c,$headerStart,$h); foreach($numbers as $c=>$h)$sheet->setCellValueByColumnAndRow($c,$headerEnd,$h);
    $r=$firstDataRow;$n=1;$tot=array_fill_keys(array('saldo_awal','pemasukan','pengeluaran','penyesuaian','saldo_akhir','stock_opname','selisih'),0);
    foreach($rows as $row){$saldo=(float)$row->saldo_akhir;$op=$saldo;$sel=$op-$saldo;$ket=array();if((int)$row->movement_lines>0)$ket[]=(int)$row->movement_lines.' line transaksi';if($row->plant_code||$row->storage_code||$row->bin_code)$ket[]=trim((string)$row->plant_code.' / '.(string)$row->storage_code.' / '.(string)$row->bin_code,' /');if($row->stock_type)$ket[]=$row->stock_type;$vals=array($n++,$row->kd_barang,$row->nm_barang,$row->satuan,(float)$row->saldo_awal,(float)$row->pemasukan,(float)$row->pengeluaran,(float)$row->penyesuaian,$saldo,$op,$sel,implode(' | ',$ket));foreach($vals as $c=>$v)$sheet->setCellValueByColumnAndRow($c,$r,$v);foreach(array('saldo_awal','pemasukan','pengeluaran','penyesuaian') as $k)$tot[$k]+=(float)$row->$k;$tot['saldo_akhir']+=$saldo;$tot['stock_opname']+=$op;$tot['selisih']+=$sel;$r++;}
    $lastDataRow=max($firstDataRow,$r-1);$summaryRow=$r+1;$sheet->mergeCells('A'.$summaryRow.':D'.$summaryRow);$sheet->setCellValue('A'.$summaryRow, erp_export_label('TOTAL'));$sheet->setCellValue('E'.$summaryRow,$tot['saldo_awal']);$sheet->setCellValue('F'.$summaryRow,$tot['pemasukan']);$sheet->setCellValue('G'.$summaryRow,$tot['pengeluaran']);$sheet->setCellValue('H'.$summaryRow,$tot['penyesuaian']);$sheet->setCellValue('I'.$summaryRow,$tot['saldo_akhir']);$sheet->setCellValue('J'.$summaryRow,$tot['stock_opname']);$sheet->setCellValue('K'.$summaryRow,$tot['selisih']);
    $sheet->getStyle('A1:L4')->getFont()->setBold(true)->setSize(12);$sheet->getStyle('A1:L4')->getAlignment()->setHorizontal(PHPExcel_Style_Alignment::HORIZONTAL_CENTER);$sheet->getStyle('A'.$headerStart.':L'.$headerEnd)->getFont()->setBold(true);$sheet->getStyle('A'.$headerStart.':L'.$headerEnd)->getAlignment()->setHorizontal(PHPExcel_Style_Alignment::HORIZONTAL_CENTER)->setVertical(PHPExcel_Style_Alignment::VERTICAL_CENTER)->setWrapText(true);$sheet->getStyle('A'.$headerStart.':L'.$headerStart)->getFill()->setFillType(PHPExcel_Style_Fill::FILL_SOLID)->getStartColor()->setRGB('EFF6FF');$sheet->getStyle('A'.$headerEnd.':L'.$headerEnd)->getFill()->setFillType(PHPExcel_Style_Fill::FILL_SOLID)->getStartColor()->setRGB('FFFFFF');$sheet->getStyle('A'.$headerStart.':L'.$lastDataRow)->getBorders()->getAllBorders()->setBorderStyle(PHPExcel_Style_Border::BORDER_THIN)->getColor()->setRGB('CBD5E1');$sheet->getStyle('A'.$firstDataRow.':L'.$lastDataRow)->getAlignment()->setVertical(PHPExcel_Style_Alignment::VERTICAL_TOP)->setWrapText(true);$sheet->getStyle('A'.$firstDataRow.':A'.$lastDataRow)->getAlignment()->setHorizontal(PHPExcel_Style_Alignment::HORIZONTAL_CENTER);$sheet->getStyle('E'.$firstDataRow.':K'.$summaryRow)->getNumberFormat()->setFormatCode('#,##0.00');$sheet->getStyle('E'.$firstDataRow.':K'.$summaryRow)->getAlignment()->setHorizontal(PHPExcel_Style_Alignment::HORIZONTAL_RIGHT);$sheet->getStyle('A'.$summaryRow.':L'.$summaryRow)->getFont()->setBold(true);$sheet->getStyle('A'.$summaryRow.':L'.$summaryRow)->getFill()->setFillType(PHPExcel_Style_Fill::FILL_SOLID)->getStartColor()->setRGB('ECFDF5');$sheet->getStyle('A'.$summaryRow.':L'.$summaryRow)->getBorders()->getAllBorders()->setBorderStyle(PHPExcel_Style_Border::BORDER_THIN)->getColor()->setRGB('CBD5E1');
    foreach(array('A'=>6,'B'=>14,'C'=>30,'D'=>8,'E'=>13,'F'=>14,'G'=>15,'H'=>18,'I'=>13,'J'=>14,'K'=>12,'L'=>34) as $col=>$w)$sheet->getColumnDimension($col)->setWidth($w);$sheet->getRowDimension($headerStart)->setRowHeight(42);$sheet->getRowDimension($headerEnd)->setRowHeight(22);$sheet->freezePane('A'.$firstDataRow);$sheet->setAutoFilter('A'.$headerEnd.':L'.$lastDataRow);$sheet->getPageSetup()->setOrientation(PHPExcel_Worksheet_PageSetup::ORIENTATION_LANDSCAPE);$sheet->getPageSetup()->setFitToWidth(1);$sheet->getPageSetup()->setFitToHeight(0);
    $tmp=erpkb_excel_temp_file('mutasi_barang_modal_');PHPExcel_IOFactory::createWriter($excel,'Excel2007')->save($tmp);$size=@filesize($tmp);$sig=@file_get_contents($tmp,false,null,0,2);if(!$size||$sig!=='PK'){@unlink($tmp);while(ob_get_level()>$initialOutputBufferLevel)ob_end_clean();header('Content-Type:text/plain; charset=utf-8');echo erp_t('export_excel_invalid_file','File Excel gagal dibuat dengan benar.');exit;}while(ob_get_level()>$initialOutputBufferLevel)ob_end_clean();header('Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');header('Content-Disposition: attachment; filename="laporan_mutasi_barang_modal_'.$tglAwal.'_sd_'.$tglAkhir.'.xlsx"');header('Content-Length: '.$size);header('Cache-Control: max-age=0');header('Pragma: public');readfile($tmp);@unlink($tmp);exit;
  default:
    header('Content-Type: application/json; charset=utf-8'); echo json_encode(array('status'=>'error','error_message'=>'Action tidak dikenal.'));
}
?>
