<?php
include_once "capa_lib.php";
$defaultFrom = date('Y-m-01');
$defaultTo = date('Y-m-d');
$kpi = capa_kpi($db);
$users = capa_users($db);
$nextNo = capa_next_number(date('Y-m-d'));
?>
<style>
.capa-hero{background:linear-gradient(135deg,#111827,#be123c);color:#fff;border-radius:14px;padding:21px 22px;margin-bottom:18px;box-shadow:0 10px 24px rgba(15,23,42,.18)}
.capa-hero h1{margin:0 0 6px;font-size:26px;font-weight:700}.capa-hero p{margin:0;opacity:.92}
.capa-kpi{border-radius:12px;background:#fff;border:1px solid #e5edf5;padding:15px;margin-bottom:14px;box-shadow:0 4px 14px rgba(15,23,42,.05)}
.capa-kpi span{display:block;color:#64748b;font-size:12px;text-transform:uppercase;letter-spacing:.04em}.capa-kpi strong{display:block;font-size:23px;margin-top:6px;color:#111827}.capa-kpi i{float:right;font-size:26px;color:#be123c;opacity:.55}
.capa-card{border-radius:12px;border:1px solid #e5edf5;box-shadow:0 5px 16px rgba(15,23,42,.05)}.capa-filter .form-group{margin-bottom:12px}
#dtb_capa th,#dtb_capa td{font-size:12px;vertical-align:middle}.select2-container{width:100%!important}.capa-modal .modal-body{max-height:72vh;overflow:auto}
.capa-help{color:#64748b;margin-top:6px}.capa-section-title{font-weight:700;margin:8px 0 12px;color:#0f172a}
</style>
<section class="content-header">
  <h1>CAPA <small>SAP QM Corrective and Preventive Action</small></h1>
  <ol class="breadcrumb"><li><a href="<?=base_index();?>"><i class="fa fa-dashboard"></i> Home</a></li><li><a href="<?=base_index();?>quality-dashboard">Quality Management</a></li><li class="active">CAPA</li></ol>
</section>
<section class="content">
  <div class="capa-hero"><div class="row"><div class="col-md-8"><h1>CAPA Workbench</h1><p>Kelola corrective dan preventive action dari NCR, audit, customer complaint, supplier defect, atau deviation sampai efektivitasnya terverifikasi.</p></div><div class="col-md-4 text-right"><button id="btn_add_capa_top" class="btn btn-info"><i class="fa fa-plus"></i> Create CAPA</button> <button id="btn_excel_capa_top" class="btn btn-success"><i class="fa fa-file-excel-o"></i> Export</button></div></div></div>
  <div class="row">
    <div class="col-sm-3"><div class="capa-kpi"><i class="fa fa-list"></i><span>Total CAPA</span><strong><?=capa_num($kpi->total);?></strong></div></div>
    <div class="col-sm-3"><div class="capa-kpi"><i class="fa fa-folder-open"></i><span>Open / Progress</span><strong><?=capa_num($kpi->open_count);?></strong></div></div>
    <div class="col-sm-3"><div class="capa-kpi"><i class="fa fa-check-square-o"></i><span>Need Verification</span><strong><?=capa_num($kpi->verification_count);?></strong></div></div>
    <div class="col-sm-3"><div class="capa-kpi"><i class="fa fa-clock-o"></i><span>Overdue</span><strong><?=capa_num($kpi->overdue_count);?></strong></div></div>
  </div>
  <div class="box capa-card"><div class="box-header with-border"><h3 class="box-title"><i class="fa fa-filter"></i> Filter CAPA</h3></div><div class="box-body">
    <form class="form-horizontal capa-filter" onsubmit="return false;">
      <div class="form-group"><label class="control-label col-lg-2">Created Date</label><div class="col-lg-2"><div class="input-group date capa-date"><input id="filter_tgl_awal" class="form-control" value="<?=$defaultFrom;?>" autocomplete="off"><span class="input-group-addon"><span class="glyphicon glyphicon-calendar"></span></span></div></div><div class="col-lg-2"><div class="input-group date capa-date"><input id="filter_tgl_akhir" class="form-control" value="<?=$defaultTo;?>" autocomplete="off"><span class="input-group-addon"><span class="glyphicon glyphicon-calendar"></span></span></div></div><label class="control-label col-lg-1">Status</label><div class="col-lg-2"><select id="filter_status" class="form-control"><option value="">Semua</option><option>DRAFT</option><option>OPEN</option><option>IN_PROGRESS</option><option>WAITING_VERIFICATION</option><option>EFFECTIVE</option><option>INEFFECTIVE</option><option>CLOSED</option><option>CANCELLED</option></select></div><label class="control-label col-lg-1">Risk</label><div class="col-lg-2"><select id="filter_risk_level" class="form-control"><option value="">Semua</option><option>LOW</option><option>MEDIUM</option><option>HIGH</option><option>CRITICAL</option></select></div></div>
      <div class="form-group"><label class="control-label col-lg-2">Owner</label><div class="col-lg-3"><select id="filter_owner_user" class="form-control"><option value="">Semua</option><?php foreach($users as $u){ ?><option value="<?=capa_h($u->username);?>"><?=capa_h($u->username);?></option><?php } ?></select></div><label class="control-label col-lg-1">Source</label><div class="col-lg-3"><select id="filter_source_type" class="form-control"><option value="">Semua</option><option>QUALITY_NOTIFICATION</option><option>AUDIT</option><option>CUSTOMER_COMPLAINT</option><option>SUPPLIER_DEFECT</option><option>PROCESS_DEVIATION</option><option>MANUAL</option></select></div><label class="control-label col-lg-1">Search</label><div class="col-lg-2"><input id="filter_keyword" class="form-control" placeholder="CAPA, NCR, material, action"></div></div>
      <div class="form-group"><div class="col-lg-offset-2 col-lg-10"><button type="button" id="btn_filter_capa" class="btn btn-primary"><i class="fa fa-filter"></i> Filter</button> <button type="button" id="btn_reset_capa" class="btn btn-default"><i class="fa fa-refresh"></i></button> <button type="button" id="btn_add_capa" class="btn btn-info"><i class="fa fa-plus"></i> Create CAPA</button> <button type="button" id="btn_excel_capa" class="btn btn-success"><i class="fa fa-file-excel-o"></i> Export Excel</button></div></div>
    </form>
  </div></div>
  <div class="box capa-card"><div class="box-body"><div class="alert alert-warning error_data_delete" style="display:none"><button type="button" class="close hide_alert_notif">&times;</button><i class="icon fa fa-warning"></i> <span class="isi_warning_delete"></span></div><div class="table-responsive"><table id="dtb_capa" class="table table-bordered table-striped table-condensed" style="width:100%"><thead><tr><th>No</th><th>Action</th><th>CAPA</th><th>Source</th><th>Material</th><th>Risk</th><th>Status</th><th>Problem</th><th>Owner / Due</th><th>Log</th><th>Created</th></tr></thead><tbody></tbody></table></div></div></div>

  <div id="modal_capa_form" class="modal fade capa-modal"><div class="modal-dialog modal-lg" style="width:96%"><div class="modal-content"><div class="modal-header"><button class="close" data-dismiss="modal">&times;</button><h4 class="modal-title">CAPA</h4></div><div class="modal-body">
    <form id="form_capa" class="form-horizontal">
      <input type="hidden" name="id" id="capa_id"><input type="hidden" name="notification_id" id="notification_id"><input type="hidden" name="notification_no" id="notification_no"><input type="hidden" name="material_name" id="material_name">
      <div class="alert alert-info"><strong>SAP QM hint:</strong> CAPA idealnya dibuat dari NCR yang sudah membutuhkan tindakan korektif/preventif. Untuk audit atau improvement internal, gunakan source manual.</div>
      <div class="form-group"><label class="control-label col-sm-2">NCR Source</label><div class="col-sm-6"><select id="qn_candidate" class="form-control"></select><div class="capa-help">Pilih NCR untuk auto-fill problem, material, root cause, dan action awal.</div></div><label class="control-label col-sm-2">CAPA No</label><div class="col-sm-2"><input name="capa_no" id="capa_no" class="form-control" value="<?=capa_h($nextNo);?>"></div></div>
      <div class="form-group"><label class="control-label col-sm-2">Type</label><div class="col-sm-2"><select name="capa_type" id="capa_type" class="form-control"><option>CORRECTIVE</option><option>PREVENTIVE</option><option selected>BOTH</option></select></div><label class="control-label col-sm-2">Source</label><div class="col-sm-2"><select name="source_type" id="source_type" class="form-control"><option>MANUAL</option><option>QUALITY_NOTIFICATION</option><option>AUDIT</option><option>CUSTOMER_COMPLAINT</option><option>SUPPLIER_DEFECT</option><option>PROCESS_DEVIATION</option></select></div><label class="control-label col-sm-2">Material</label><div class="col-sm-2"><input name="material_code" id="material_code" class="form-control" placeholder="Material"></div></div>
      <div class="form-group"><label class="control-label col-sm-2">Risk</label><div class="col-sm-2"><select name="risk_level" id="risk_level" class="form-control"><option>LOW</option><option selected>MEDIUM</option><option>HIGH</option><option>CRITICAL</option></select></div><label class="control-label col-sm-2">Priority</label><div class="col-sm-2"><select name="priority" id="priority" class="form-control"><option>LOW</option><option selected>NORMAL</option><option>HIGH</option><option>URGENT</option></select></div><label class="control-label col-sm-2">Status</label><div class="col-sm-2"><select name="status" id="status" class="form-control"><option>DRAFT</option><option selected>OPEN</option><option>IN_PROGRESS</option><option>WAITING_VERIFICATION</option><option>EFFECTIVE</option><option>INEFFECTIVE</option><option>CLOSED</option><option>CANCELLED</option></select></div></div>
      <div class="form-group"><label class="control-label col-sm-2">Owner</label><div class="col-sm-2"><select name="owner_user" id="owner_user" class="form-control"><option value="">-</option><?php foreach($users as $u){ ?><option value="<?=capa_h($u->username);?>"><?=capa_h($u->username);?></option><?php } ?></select></div><label class="control-label col-sm-2">Approver</label><div class="col-sm-2"><select name="approver_user" id="approver_user" class="form-control"><option value="">-</option><?php foreach($users as $u){ ?><option value="<?=capa_h($u->username);?>"><?=capa_h($u->username);?></option><?php } ?></select></div><label class="control-label col-sm-2">Start / Due</label><div class="col-sm-1"><input name="start_date" id="start_date" class="form-control capa-date-input" value="<?=date('Y-m-d');?>"></div><div class="col-sm-1"><input name="due_date" id="due_date" class="form-control capa-date-input"></div></div>
      <div class="form-group"><label class="control-label col-sm-2">Category</label><div class="col-sm-3"><input name="defect_category" id="defect_category" class="form-control" placeholder="Process / Material / Document"></div><label class="control-label col-sm-2">Defect Code</label><div class="col-sm-2"><input name="defect_code" id="defect_code" class="form-control"></div><label class="control-label col-sm-1">Verify</label><div class="col-sm-2"><input name="verification_date" id="verification_date" class="form-control capa-date-input"></div></div>
      <div class="capa-section-title">1. Problem & Root Cause</div>
      <div class="form-group"><label class="control-label col-sm-2">Problem *</label><div class="col-sm-4"><textarea name="problem_statement" id="problem_statement" class="form-control" rows="3" required></textarea></div><label class="control-label col-sm-2">Root Cause</label><div class="col-sm-4"><textarea name="root_cause" id="root_cause" class="form-control" rows="3" placeholder="5 Why / Fishbone result"></textarea></div></div>
      <div class="capa-section-title">2. Action Plan</div>
      <div class="form-group"><label class="control-label col-sm-2">Correction</label><div class="col-sm-4"><textarea name="correction_action" id="correction_action" class="form-control" rows="3" placeholder="Immediate correction / containment"></textarea></div><label class="control-label col-sm-2">Corrective</label><div class="col-sm-4"><textarea name="corrective_action" id="corrective_action" class="form-control" rows="3" placeholder="Action to remove root cause"></textarea></div></div>
      <div class="form-group"><label class="control-label col-sm-2">Preventive</label><div class="col-sm-4"><textarea name="preventive_action" id="preventive_action" class="form-control" rows="3" placeholder="Action to prevent recurrence"></textarea></div><label class="control-label col-sm-2">Verification Plan</label><div class="col-sm-4"><textarea name="verification_plan" id="verification_plan" class="form-control" rows="3" placeholder="How to verify effectiveness"></textarea></div></div>
      <div class="form-group"><label class="control-label col-sm-2">Effectiveness Result</label><div class="col-sm-10"><textarea name="effectiveness_result" id="effectiveness_result" class="form-control" rows="2"></textarea></div></div>
    </form>
  </div><div class="modal-footer"><button class="btn btn-default" data-dismiss="modal">Close</button><button id="btn_save_capa" class="btn btn-primary"><i class="fa fa-save"></i> Save CAPA</button></div></div></div></div>
  <div id="modal_capa_detail" class="modal fade capa-modal"><div class="modal-dialog modal-lg" style="width:96%"><div class="modal-content"><div class="modal-header"><button class="close" data-dismiss="modal">&times;</button><h4 class="modal-title">CAPA Detail</h4></div><div class="modal-body" id="capa_detail_body"></div><div class="modal-footer"><button class="btn btn-default" data-dismiss="modal">Close</button></div></div></div></div>
  <div id="modal_capa_action" class="modal fade capa-modal"><div class="modal-dialog modal-lg"><div class="modal-content"><div class="modal-header"><button class="close" data-dismiss="modal">&times;</button><h4 class="modal-title">CAPA Action</h4></div><div class="modal-body" id="capa_action_body"></div><div class="modal-footer"><button class="btn btn-default" data-dismiss="modal">Close</button><button id="btn_save_capa_action" class="btn btn-warning"><i class="fa fa-tasks"></i> Save Action</button></div></div></div></div>
</section>
<script src="<?=base_admin();?>assets/plugins/select2/select2.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
<script>
function capaError(m){$('.isi_warning_delete').text(m||'CAPA gagal diproses.');$('.error_data_delete').fadeIn();}
function capaFilters(){return{tgl_awal:$('#filter_tgl_awal').val(),tgl_akhir:$('#filter_tgl_akhir').val(),status:$('#filter_status').val(),risk_level:$('#filter_risk_level').val(),owner_user:$('#filter_owner_user').val(),source_type:$('#filter_source_type').val(),keyword:$('#filter_keyword').val()};}
function capaExcelUrl(){return '<?=base_admin();?>modul/capa/capa_action.php?act=excel&'+$.param(capaFilters());}
function capaInitSelect(){if(!$.fn.select2)return;$('#filter_status,#filter_risk_level,#filter_owner_user,#filter_source_type,#capa_type,#source_type,#risk_level,#priority,#status,#owner_user,#approver_user,#capa_action_status').select2({width:'100%',allowClear:true});$('#qn_candidate').select2({width:'100%',dropdownParent:$('#modal_capa_form'),placeholder:'Cari NCR...',minimumInputLength:0,ajax:{url:'<?=base_admin();?>modul/capa/capa_action.php?act=qn_candidate',type:'POST',dataType:'json',delay:250,data:function(p){return{term:p.term||''};},processResults:function(d){return{results:d.results||[]};}}}).on('select2:select',function(e){fillFromQn(e.params.data);});}
function resetCapaForm(){$('#form_capa')[0].reset();$('#capa_id,#notification_id,#notification_no,#material_name').val('');$('#capa_no').val('<?=capa_h($nextNo);?>');$('#qn_candidate').val(null).trigger('change');$('#source_type').val('MANUAL').trigger('change');$('#capa_type').val('BOTH').trigger('change');$('#risk_level').val('MEDIUM').trigger('change');$('#priority').val('NORMAL').trigger('change');$('#status').val('OPEN').trigger('change');$('#owner_user,#approver_user').val('').trigger('change');$('#start_date').val('<?=date('Y-m-d');?>');}
function fillFromQn(d){$('#source_type').val('QUALITY_NOTIFICATION').trigger('change');$('#notification_id').val(d.id);$('#notification_no').val(d.notification_no||'');$('#material_code').val(d.material_code||'');$('#material_name').val(d.material_name||'');$('#defect_category').val(d.defect_category||'');$('#defect_code').val(d.defect_code||'');$('#problem_statement').val(d.problem_statement||'');$('#root_cause').val(d.root_cause||'');$('#correction_action').val(d.correction_action||'');$('#corrective_action').val(d.corrective_action||'');$('#preventive_action').val(d.preventive_action||'');$('#owner_user').val(d.owner_user||'').trigger('change');$('#risk_level').val(d.risk_level||'MEDIUM').trigger('change');$('#priority').val(d.priority||'NORMAL').trigger('change');}
function fillCapaForm(d){$('#capa_id').val(d.id);$('#capa_no').val(d.capa_no);$('#capa_type').val(d.capa_type).trigger('change');$('#source_type').val(d.source_type).trigger('change');$('#notification_id').val(d.notification_id);$('#notification_no').val(d.notification_no);$('#material_code').val(d.material_code);$('#material_name').val(d.material_name);$('#risk_level').val(d.risk_level).trigger('change');$('#priority').val(d.priority).trigger('change');$('#status').val(d.status).trigger('change');$('#owner_user').val(d.owner_user).trigger('change');$('#approver_user').val(d.approver_user).trigger('change');$('#start_date').val(d.start_date);$('#due_date').val(d.due_date);$('#verification_date').val(d.verification_date);$('#defect_category').val(d.defect_category);$('#defect_code').val(d.defect_code);$('#problem_statement').val(d.problem_statement);$('#root_cause').val(d.root_cause);$('#correction_action').val(d.correction_action);$('#corrective_action').val(d.corrective_action);$('#preventive_action').val(d.preventive_action);$('#verification_plan').val(d.verification_plan);$('#effectiveness_result').val(d.effectiveness_result);if(d.notification_no){var opt=new Option(d.notification_no+' | '+(d.material_code||'')+' - '+(d.material_name||''),d.notification_id,true,true);$('#qn_candidate').append(opt).trigger('change');}}
$(function(){
  if($.fn.datepicker){$('.capa-date').datepicker({format:'yyyy-mm-dd',autoclose:true,todayHighlight:true});$('.capa-date-input').datepicker({format:'yyyy-mm-dd',autoclose:true,todayHighlight:true});}
  capaInitSelect();
  var dt=$('#dtb_capa').DataTable({bProcessing:true,bServerSide:true,pageLength:25,ordering:false,dom:"<'row'<'col-sm-12'B>>"+"<'row'<'col-sm-6'l><'col-sm-6'f>>"+"<'row'<'col-sm-12'tr>>"+"<'row'<'col-sm-5'i><'col-sm-7'p>>",buttons:[{extend:'collection',text:'Export Data',buttons:['copyHtml5','excelHtml5','csvHtml5','pdfHtml5']}],columnDefs:[{targets:[0,1],orderable:false,searchable:false},{targets:[9],className:'text-right'},{width:'42px',targets:0},{width:'125px',targets:1}],ajax:{url:'<?=base_admin();?>modul/capa/capa_data.php',type:'post',data:function(d){$.extend(d,capaFilters());},error:function(xhr){console.log(xhr.responseText);capaError('Data CAPA gagal dimuat.');}}});
  $('#btn_filter_capa').click(function(){dt.draw();});$('#filter_keyword').keyup(function(e){if(e.keyCode===13)dt.draw();});$('#btn_excel_capa,#btn_excel_capa_top').click(function(){window.location=capaExcelUrl();});
  $('#btn_reset_capa').click(function(){$('#filter_tgl_awal').val('<?=$defaultFrom;?>');$('#filter_tgl_akhir').val('<?=$defaultTo;?>');$('#filter_keyword').val('');$('#filter_status,#filter_risk_level,#filter_owner_user,#filter_source_type').val('').trigger('change');dt.draw();});
  $('#btn_add_capa,#btn_add_capa_top').click(function(){resetCapaForm();$('#modal_capa_form').modal('show');});
  $('#btn_save_capa').click(function(){var btn=$(this);btn.prop('disabled',true).html('<i class="fa fa-spinner fa-spin"></i> Saving...');$.ajax({url:'<?=base_admin();?>modul/capa/capa_action.php?act=save',type:'POST',data:$('#form_capa').serialize(),dataType:'json',success:function(res){btn.prop('disabled',false).html('<i class="fa fa-save"></i> Save CAPA');if(res.status==='good'){$('#modal_capa_form').modal('hide');dt.draw(false);Swal.fire('Success','CAPA '+res.capa_no+' tersimpan.','success');}else capaError(res.error_message);},error:function(xhr){btn.prop('disabled',false).html('<i class="fa fa-save"></i> Save CAPA');capaError(xhr.responseText);}});});
  $(document).on('click','.btn-capa-detail',function(){$.post('<?=base_admin();?>modul/capa/capa_action.php?act=detail',{id:$(this).data('id')},function(html){$('#capa_detail_body').html(html);$('#modal_capa_detail').modal('show');}).fail(function(){capaError('Detail CAPA gagal dibuka.');});});
  $(document).on('click','.btn-capa-action',function(){$.post('<?=base_admin();?>modul/capa/capa_action.php?act=action_form',{id:$(this).data('id')},function(html){$('#capa_action_body').html(html);capaInitSelect();$('#modal_capa_action').modal('show');}).fail(function(){capaError('Form action gagal dibuka.');});});
  $(document).on('click','.btn-capa-edit',function(){resetCapaForm();$.post('<?=base_admin();?>modul/capa/capa_action.php?act=get',{id:$(this).data('id')},function(res){if(res.status!=='good'){capaError(res.error_message);return;}fillCapaForm(res.data);$('#modal_capa_form').modal('show');},'json').fail(function(xhr){capaError(xhr.responseText);});});
  $(document).on('click','.btn-capa-cancel',function(){var id=$(this).data('id');Swal.fire({title:'Cancel CAPA?',text:'Status CAPA akan menjadi CANCELLED.',icon:'warning',showCancelButton:true,confirmButtonText:'Ya, cancel'}).then(function(r){if(!r.isConfirmed)return;$.post('<?=base_admin();?>modul/capa/capa_action.php?act=cancel',{id:id},function(res){if(res.status==='good'){dt.draw(false);Swal.fire('Done','CAPA dibatalkan.','success');}else capaError(res.error_message);},'json').fail(function(xhr){capaError(xhr.responseText);});});});
  $('#btn_save_capa_action').click(function(){var btn=$(this);btn.prop('disabled',true).html('<i class="fa fa-spinner fa-spin"></i> Saving...');$.ajax({url:'<?=base_admin();?>modul/capa/capa_action.php?act=post_action',type:'POST',data:$('#form_capa_action').serialize(),dataType:'json',success:function(res){btn.prop('disabled',false).html('<i class="fa fa-tasks"></i> Save Action');if(res.status==='good'){$('#modal_capa_action').modal('hide');dt.draw(false);Swal.fire('Success','Action CAPA tersimpan.','success');}else capaError(res.error_message);},error:function(xhr){btn.prop('disabled',false).html('<i class="fa fa-tasks"></i> Save Action');capaError(xhr.responseText);}});});
  $('.hide_alert_notif').click(function(){$('.error_data_delete').hide();});
});
</script>
