<?php
if (!function_exists('prod_t')) {
  function prod_t($key, $fallback = '') { return lang_text($key, $fallback); }
}
if (!function_exists('prod_h')) {
  function prod_h($key, $fallback = '') { return htmlspecialchars((string) prod_t($key, $fallback), ENT_QUOTES, 'UTF-8'); }
}
if (!function_exists('prod_js')) {
  function prod_js($key, $fallback = '') { return json_encode(prod_t($key, $fallback), JSON_HEX_TAG | JSON_HEX_APOS | JSON_HEX_AMP | JSON_HEX_QUOT); }
}
$defaultFrom=date('Y-m-01');$defaultTo=date('Y-m-t');$plants=$db->query("SELECT id,plant_code,plant_name FROM erp_plant WHERE status='Aktif' ORDER BY plant_code"); ?>
<style>
.dm-hero{background:linear-gradient(135deg,#1d4ed8,#7c3aed);color:#fff;border-radius:14px;padding:20px;margin-bottom:18px;box-shadow:0 10px 24px rgba(15,23,42,.16)}.dm-hero h1{margin:0 0 6px;font-size:26px;font-weight:700}.dm-hero p{margin:0;opacity:.92}.dm-card{border-radius:12px;background:#fff;border:1px solid #e5edf5;box-shadow:0 5px 16px rgba(15,23,42,.05);margin-bottom:14px}.dm-items th,.dm-items td,#dtb_demand th,#dtb_demand td{font-size:12px;vertical-align:middle}.select2-container{width:100%!important}.required-label:after{content:' *';color:#dd4b39}.dm-action{white-space:nowrap}.dm-source-box{background:#f8fafc;border:1px solid #e2e8f0;border-radius:10px;padding:10px;margin-bottom:10px}
</style>
<section class="content-header"><h1><?=prod_h('production_demand_management', 'Demand Management');?> <small>SAP PP Demand Program</small></h1><ol class="breadcrumb"><li><a href="<?=base_index();?>"><i class="fa fa-dashboard"></i> <?=prod_h('common_home', 'Home');?></a></li><li class="active"><?=prod_h('production_demand_management', 'Demand Management');?></li></ol></section>
<section class="content">
  <div class="dm-hero"><div class="row"><div class="col-md-8"><h1>Demand Management Workbench</h1><p>Konsolidasikan forecast dan sales order menjadi demand plan untuk MRP dan production planning.</p></div><div class="col-md-4 text-right"><button id="btn_open_dm" class="btn btn-warning"><i class="fa fa-plus"></i> Create Demand Plan</button></div></div></div>
  <div class="box dm-card"><div class="box-header"><h3 class="box-title"><i class="fa fa-filter"></i> Filter Demand</h3></div><div class="box-body"><form class="form-horizontal" onsubmit="return false;"><div class="form-group"><label class="control-label col-lg-2"><?=prod_h('production_period', 'Period');?></label><div class="col-lg-2"><div class="input-group date dm-date"><input id="filter_tgl_awal" class="form-control" value="<?=$defaultFrom;?>"><span class="input-group-addon"><span class="glyphicon glyphicon-calendar"></span></span></div></div><div class="col-lg-2"><div class="input-group date dm-date"><input id="filter_tgl_akhir" class="form-control" value="<?=$defaultTo;?>"><span class="input-group-addon"><span class="glyphicon glyphicon-calendar"></span></span></div></div><label class="control-label col-lg-1"><?=prod_h('production_plant', 'Plant');?></label><div class="col-lg-2"><select id="filter_plant" class="form-control"><option value=""><?=prod_h('common_all', 'All');?></option><?php foreach($plants as $p){ ?><option value="<?=htmlspecialchars($p->plant_code,ENT_QUOTES,'UTF-8');?>"><?=htmlspecialchars($p->plant_code.' - '.$p->plant_name,ENT_QUOTES,'UTF-8');?></option><?php } ?></select></div><label class="control-label col-lg-1"><?=prod_h('common_status', 'Status');?></label><div class="col-lg-2"><select id="filter_status" class="form-control"><option value=""><?=prod_h('common_all', 'All');?></option><option>DRAFT</option><option>RELEASED</option><option>CLOSED</option><option>CANCELLED</option></select></div></div><div class="form-group"><label class="control-label col-lg-2"><?=prod_h('common_search', 'Search');?></label><div class="col-lg-5"><input id="filter_keyword" class="form-control" placeholder="Demand no / material / customer / source ref"></div><div class="col-lg-5"><button id="btn_filter_dm" class="btn btn-primary"><i class="fa fa-filter"></i> <?=prod_h('common_filter', 'Filter');?></button> <button id="btn_reset_dm" class="btn btn-default"><i class="fa fa-refresh"></i> <?=prod_h('common_reset', 'Reset');?></button> <button id="btn_export_dm" class="btn btn-success"><i class="fa fa-file-excel-o"></i> <?=prod_h('common_export_excel', 'Export Excel');?></button></div></div></form></div></div>
  <div class="box dm-card"><div class="box-body"><div class="alert alert-warning error_data_delete" style="display:none"><button type="button" class="close hide_alert_notif">&times;</button><span class="isi_warning_delete"></span></div><div class="table-responsive"><table id="dtb_demand" class="table table-bordered table-striped" style="width:100%"><thead><tr><th><?=prod_h('common_no', 'No');?></th><th><?=prod_h('common_action', 'Action');?></th><th>Demand Plan</th><th><?=prod_h('production_period', 'Period');?></th><th><?=prod_h('production_plant', 'Plant');?></th><th><?=prod_h('production_items', 'Items');?></th><th><?=prod_h('production_total_qty', 'Total Qty');?></th><th>Open Qty</th><th><?=prod_h('common_status', 'Status');?></th><th><?=prod_h('common_created_by', 'Created By');?></th></tr></thead><tbody></tbody></table></div></div></div>
  <div id="modal_dm" class="modal fade"><div class="modal-dialog modal-lg" style="width:96%"><div class="modal-content"><form id="form_dm"><div class="modal-header"><button class="close" data-dismiss="modal">&times;</button><h4 class="modal-title">Create Demand Plan</h4></div><div class="modal-body">
    <div class="alert alert-info">Demand Management mengubah forecast atau sales order menjadi demand plan. Status <strong>RELEASED</strong> menjadi input MRP.</div>
    <div class="row"><div class="col-md-2 form-group"><label>Demand Type</label><select name="demand_type" id="demand_type" class="form-control"><option value="PIR">PIR / Forecast</option><option value="SALES_ORDER">Sales Order</option><option value="CUSTOMER_REQUIREMENT">Customer Requirement</option><option value="SAFETY_STOCK">Safety Stock</option><option value="MANUAL">Manual</option></select></div><div class="col-md-2 form-group"><label><?=prod_h('production_version_label', 'Version');?></label><input name="demand_version" class="form-control" value="BASE"></div><div class="col-md-2 form-group"><label class="required-label">From</label><input name="period_from" id="period_from" class="form-control date-field" value="<?=$defaultFrom;?>" required></div><div class="col-md-2 form-group"><label class="required-label">To</label><input name="period_to" id="period_to" class="form-control date-field" value="<?=$defaultTo;?>" required></div><div class="col-md-2 form-group"><label><?=prod_h('production_plant', 'Plant');?></label><select id="plant_id" name="plant_id" class="form-control"><option value="">All Plant</option><?php foreach($db->query("SELECT id,plant_code,plant_name FROM erp_plant WHERE status='Aktif' ORDER BY plant_code") as $p){ ?><option value="<?=intval($p->id);?>" data-code="<?=htmlspecialchars($p->plant_code,ENT_QUOTES,'UTF-8');?>"><?=htmlspecialchars($p->plant_code.' - '.$p->plant_name,ENT_QUOTES,'UTF-8');?></option><?php } ?></select><input type="hidden" name="plant_code" id="plant_code"></div><div class="col-md-2 form-group"><label>Release After Save</label><select name="auto_release" class="form-control"><option value="N"><?=prod_h('common_no', 'No');?></option><option value="Y">Yes</option></select></div></div>
    <div class="dm-source-box"><div class="row"><div class="col-md-5"><select id="forecast_id" class="form-control"></select></div><div class="col-md-7"><button type="button" id="btn_load_forecast" class="btn btn-info"><i class="fa fa-download"></i> Load Released Forecast</button> <button type="button" id="btn_load_sales_order" class="btn btn-primary"><i class="fa fa-shopping-cart"></i> Load Open Sales Orders</button> <button type="button" id="btn_add_line" class="btn btn-default"><i class="fa fa-plus"></i> Add Manual Line</button></div></div></div>
    <div class="form-group"><label><?=prod_h('common_remarks', 'Remarks');?></label><input name="remarks" class="form-control" placeholder="Scenario demand / asumsi planning"></div>
    <div class="table-responsive"><table class="table table-bordered table-condensed dm-items"><thead><tr><th style="width:44px">#</th><th style="width:180px"><?=prod_h('production_material', 'Material');?></th><th>Description</th><th style="width:110px"><?=prod_h('production_period', 'Period');?></th><th style="width:120px"><?=prod_h('production_qty', 'Qty');?></th><th style="width:70px"><?=prod_h('production_uom', 'UOM');?></th><th style="width:95px">Req Type</th><th style="width:110px"><?=prod_h('production_source', 'Source');?></th><th>Source Ref / Customer</th><th><?=prod_h('common_remarks', 'Remarks');?></th></tr></thead><tbody id="dm_lines"></tbody></table></div>
  </div><div class="modal-footer"><button type="button" class="btn btn-default" data-dismiss="modal"><?=prod_h('common_cancel', 'Cancel');?></button><button type="submit" class="btn btn-primary"><i class="fa fa-save"></i> <?=prod_h('production_save_demand_plan', 'Save Demand Plan');?></button></div></form></div></div></div>
  <div id="modal_dm_detail" class="modal fade"><div class="modal-dialog modal-lg" style="width:94%"><div class="modal-content"><div class="modal-header"><button class="close" data-dismiss="modal">&times;</button><h4 class="modal-title">Demand Detail</h4></div><div class="modal-body" id="dm_detail_body"></div><div class="modal-footer"><button class="btn btn-default" data-dismiss="modal"><?=prod_h('common_close', 'Close');?></button></div></div></div></div>
</section>
<script src="<?=base_admin();?>assets/plugins/select2/select2.min.js"></script><script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
<script>
function dmError(m){$('.isi_warning_delete').text(m||<?=prod_js('production_demand_process_failed', 'Demand failed to process.');?>);$('.error_data_delete').fadeIn();}
var lineNo=0;function htmlEsc(s){return String(s||'').replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c];});}
function initDmMaterial(el){if(!$.fn.select2){return;}el.select2({width:'100%',dropdownParent:$('#modal_dm'),placeholder:'Cari material...',minimumInputLength:1,ajax:{url:'<?=base_admin();?>modul/demand_management/demand_management_action.php?act=material_search',type:'POST',dataType:'json',delay:250,data:function(p){return{term:p.term||''};},processResults:function(d){return{results:d.results||[]};}}}).on('select2:select',function(e){var d=e.params.data,tr=$(this).closest('tr');tr.find('input[name="material_name[]"]').val(d.material_name||'');tr.find('input[name="uom[]"]').val(d.uom||'');});}
function appendLine(x){lineNo++;x=x||{};var rowId='dm_line_'+lineNo;var matOpt=x.material_code?'<option value="'+htmlEsc(x.material_code)+'" selected>'+htmlEsc(x.material_code+' - '+(x.material_name||''))+'</option>':'';var row='<tr id="'+rowId+'"><td class="text-center"><button type="button" class="btn btn-xs btn-danger btn-dm-remove-line"><i class="fa fa-trash"></i></button></td><td><select name="material_code[]" class="form-control demand-material" required>'+matOpt+'</select></td><td><input name="material_name[]" class="form-control" value="'+htmlEsc(x.material_name||'')+'" readonly></td><td><input name="period_date[]" class="form-control date-field" value="'+htmlEsc(x.period_date||$('#period_from').val())+'" required></td><td><input type="number" step="0.00001" min="0.00001" name="demand_qty[]" class="form-control text-right" value="'+htmlEsc(x.demand_qty||'')+'" required></td><td><input name="uom[]" class="form-control" value="'+htmlEsc(x.uom||'')+'" readonly></td><td><select name="requirement_type[]" class="form-control"><option '+(x.requirement_type==='VSF'?'selected':'')+'>VSF</option><option '+(x.requirement_type==='KE'?'selected':'')+'>KE</option><option '+(x.requirement_type==='LSF'?'selected':'')+'>LSF</option><option '+(x.requirement_type==='MANUAL'?'selected':'')+'>MANUAL</option></select></td><td><input name="source_type[]" class="form-control" value="'+htmlEsc(x.source_type||'MANUAL')+'" readonly></td><td><input type="hidden" name="source_ref[]" value="'+htmlEsc(x.source_ref||'')+'"><input type="hidden" name="id_sales_order[]" value="'+htmlEsc(x.id_sales_order||'')+'"><input type="hidden" name="id_sales_order_detail[]" value="'+htmlEsc(x.id_sales_order_detail||'')+'"><input type="hidden" name="customer_code[]" value="'+htmlEsc(x.customer_code||'')+'"><input name="customer_name[]" class="form-control" value="'+htmlEsc((x.source_ref||'')+(x.customer_name?' / '+x.customer_name:''))+'" readonly></td><td><input name="line_remarks[]" class="form-control" value="'+htmlEsc(x.remarks||'')+'"></td></tr>';$('#dm_lines').append(row);initDmMaterial($('#'+rowId+' .demand-material'));if($.fn.datepicker)$('#'+rowId+' .date-field').datepicker({format:'yyyy-mm-dd',autoclose:true,todayHighlight:true});}
function filters(){return{tgl_awal:$('#filter_tgl_awal').val(),tgl_akhir:$('#filter_tgl_akhir').val(),status:$('#filter_status').val(),plant:$('#filter_plant').val(),keyword:$('#filter_keyword').val()};}
$(function(){if($.fn.datepicker){$('.dm-date,.date-field').datepicker({format:'yyyy-mm-dd',autoclose:true,todayHighlight:true});}if($.fn.select2){$('#filter_plant,#filter_status,#plant_id,#demand_type').select2({width:'100%'});$('#forecast_id').select2({width:'100%',placeholder:'Cari released forecast...',allowClear:true,dropdownParent:$('#modal_dm'),ajax:{url:'<?=base_admin();?>modul/demand_management/demand_management_action.php?act=forecast_search',type:'POST',dataType:'json',delay:250,data:function(p){return{term:p.term||''};},processResults:function(d){return{results:d.results||[]};}}});}
var dt=null;function reloadDemandTable(resetPaging){if(dt&&dt.draw){dt.draw(resetPaging===false?false:undefined);}}
try{if($.fn.DataTable){dt=$('#dtb_demand').DataTable({bProcessing:true,bServerSide:true,pageLength:25,dom:"<'row'<'col-sm-12'B>>"+"<'row'<'col-sm-6'l><'col-sm-6'f>>"+"<'row'<'col-sm-12'tr>>"+"<'row'<'col-sm-5'i><'col-sm-7'p>>",buttons:[{extend:'collection',text:<?=prod_js('common_export_data', 'Export Data');?>,buttons:['copyHtml5','excelHtml5','csvHtml5','pdfHtml5']}],columnDefs:[{targets:[0,1],orderable:false,searchable:false},{targets:[6,7],className:'text-right'},{width:'42px',targets:0},{width:'110px',targets:1}],ajax:{url:'<?=base_admin();?>modul/demand_management/demand_management_data.php',type:'post',data:function(d){$.extend(d,filters());},error:function(xhr){console.log(xhr.responseText);dmError(<?=prod_js('production_demand_load_failed', 'Demand data failed to load.');?>);}}});}}catch(e){console.error(e);dmError(<?=prod_js('production_demand_load_failed_create_available', 'Demand data failed to load. Create button remains available.');?>);}
$('#btn_open_dm').click(function(){lineNo=0;$('#form_dm')[0].reset();$('#dm_lines').html('');$('#forecast_id').val(null).trigger('change');$('#plant_id').val('').trigger('change');appendLine();$('#modal_dm').modal({backdrop:'static',keyboard:false});});$('#plant_id').change(function(){$('#plant_code').val($('#plant_id option:selected').data('code')||'');});$('#btn_add_line').click(function(){appendLine();});
$(document).on('click','.btn-dm-remove-line',function(){$(this).closest('tr').remove();});
$('#btn_load_forecast').click(function(){var id=$('#forecast_id').val();if(!id){dmError('Pilih released forecast dulu.');return;}$.post('<?=base_admin();?>modul/demand_management/demand_management_action.php?act=forecast_lines',{id:id},function(r){if(r.status==='good'){$('#dm_lines').html('');lineNo=0;(r.lines||[]).forEach(appendLine);$('#period_from').val(r.period_from);$('#period_to').val(r.period_to);$('#plant_code').val(r.plant_code||'');}else dmError(r.error_message);},'json');});
$('#btn_load_sales_order').click(function(){$.post('<?=base_admin();?>modul/demand_management/demand_management_action.php?act=sales_order_lines',{period_from:$('#period_from').val(),period_to:$('#period_to').val()},function(r){if(r.status==='good'){$('#dm_lines').html('');lineNo=0;(r.lines||[]).forEach(appendLine);if(!(r.lines||[]).length)dmError('Tidak ada sales order open pada periode ini.');}else dmError(r.error_message);},'json');});
$('#btn_filter_dm').click(function(){reloadDemandTable();});$('#filter_keyword').keyup(function(e){if(e.keyCode===13)reloadDemandTable();});$('#btn_reset_dm').click(function(){$('#filter_tgl_awal').val('<?=$defaultFrom;?>');$('#filter_tgl_akhir').val('<?=$defaultTo;?>');$('#filter_status,#filter_plant').val('').trigger('change');$('#filter_keyword').val('');reloadDemandTable();});$('#btn_export_dm').click(function(){window.location='<?=base_admin();?>modul/demand_management/demand_management_action.php?act=excel&'+$.param(filters());});
$('#form_dm').submit(function(e){e.preventDefault();var btn=$(this).find('button[type=submit]');btn.prop('disabled',true).html('<i class="fa fa-spinner fa-spin"></i> <?=prod_h('common_saving', 'Saving...');?>');$.post('<?=base_admin();?>modul/demand_management/demand_management_action.php?act=save',$(this).serialize(),function(r){if(r.status==='good'){$('#modal_dm').modal('hide');reloadDemandTable(false);}else dmError(r.error_message);btn.prop('disabled',false).html('<i class="fa fa-save"></i> <?=prod_h('production_save_demand_plan', 'Save Demand Plan');?>');},'json').fail(function(xhr){dmError(xhr.responseText);btn.prop('disabled',false).html('<i class="fa fa-save"></i> <?=prod_h('production_save_demand_plan', 'Save Demand Plan');?>');});});
$(document).on('click','.btn-dm-detail',function(){$.post('<?=base_admin();?>modul/demand_management/demand_management_action.php?act=detail',{id:$(this).data('id')},function(html){$('#dm_detail_body').html(html);$('#modal_dm_detail').modal('show');});});$(document).on('click','.btn-dm-release',function(){var id=$(this).data('id'),no=$(this).data('no');Swal.fire({title:'Release Demand?',text:no+' akan tersedia untuk MRP.',icon:'question',showCancelButton:true,confirmButtonText:<?=prod_js('production_release', 'Release');?>}).then(function(x){if(!x.isConfirmed)return;$.post('<?=base_admin();?>modul/demand_management/demand_management_action.php?act=release',{id:id},function(r){if(r.status==='good')reloadDemandTable(false);else dmError(r.error_message);},'json');});});$(document).on('click','.btn-dm-cancel',function(){var id=$(this).data('id'),no=$(this).data('no');Swal.fire({title:'Cancel Demand?',input:'text',inputLabel:'Reason '+no,showCancelButton:true,confirmButtonText:'Cancel',inputValidator:function(v){return !v?<?=prod_js('production_reason_required', 'Reason is required');?>:undefined;}}).then(function(x){if(!x.isConfirmed)return;$.post('<?=base_admin();?>modul/demand_management/demand_management_action.php?act=cancel',{id:id,reason:x.value},function(r){if(r.status==='good')reloadDemandTable(false);else dmError(r.error_message);},'json');});});$('.hide_alert_notif').click(function(){$('.error_data_delete').hide();});
});
</script>
