<?php
if (!function_exists('sd_t')) {
  function sd_t($key, $fallback = '') { return lang_text($key, $fallback); }
}
if (!function_exists('sd_h')) {
  function sd_h($key, $fallback = '') { return htmlspecialchars((string) sd_t($key, $fallback), ENT_QUOTES, 'UTF-8'); }
}
if (!function_exists('sd_js')) {
  function sd_js($key, $fallback = '') { return json_encode(sd_t($key, $fallback), JSON_HEX_TAG | JSON_HEX_APOS | JSON_HEX_AMP | JSON_HEX_QUOT); }
}
include_once "billing_report_lib.php";
$defaultFrom=date('Y-m-01');$defaultTo=date('Y-m-d');
$customers=$db->query("SELECT kode_penerima,nama FROM penerima ORDER BY nama");
$currencies=$db->query("SELECT DISTINCT valuta FROM sales_invoice WHERE COALESCE(valuta,'')<>'' ORDER BY valuta");
$salesUsers=$db->query("SELECT DISTINCT so.sales_id FROM sales_invoice si JOIN sales_order so ON so.no_sales_order=si.no_sales_order WHERE COALESCE(so.sales_id,'')<>'' ORDER BY so.sales_id");
$sum=br_summary($db,array('tgl_awal'=>$defaultFrom,'tgl_akhir'=>$defaultTo,'customer'=>'','currency'=>'','tax_status'=>'','due_status'=>'','sales_person'=>'','keyword'=>''));
?>
<style>
.br-hero{background:linear-gradient(135deg,#064e3b,#2563eb);color:#fff;border-radius:14px;padding:20px 22px;margin-bottom:18px;box-shadow:0 10px 24px rgba(15,23,42,.18)}.br-hero h1{margin:0 0 6px;font-size:26px;font-weight:700}.br-card{border-radius:12px;background:#fff;border:1px solid #e5edf5;box-shadow:0 5px 16px rgba(15,23,42,.05);margin-bottom:14px}.br-kpi{border-radius:12px;background:#fff;border:1px solid #edf2f7;padding:15px;margin-bottom:14px}.br-kpi span{display:block;color:#64748b;font-size:12px;text-transform:uppercase}.br-kpi strong{display:block;font-size:22px;margin-top:6px}.br-kpi i{float:right;font-size:26px;color:#2563eb;opacity:.55}.br-help{background:#f8fafc;border:1px dashed #cbd5e1;border-radius:10px;padding:12px;margin-bottom:14px;color:#475569}#dtb_billing_report th,#dtb_billing_report td{font-size:12px;vertical-align:middle}.select2-container{width:100%!important}
</style>
<section class="content-header"><h1><?=sd_h('sales_billing_report', 'Billing Report');?> <small>SAP SD Billing Analytics</small></h1><ol class="breadcrumb"><li><a href="<?=base_index();?>"><i class="fa fa-dashboard"></i> <?=sd_h('common_home', 'Home');?></a></li><li class="active"><?=sd_h('sales_billing_report', 'Billing Report');?></li></ol></section>
<section class="content">
  <div class="br-hero"><div class="row"><div class="col-md-8"><h1>Billing Report Cockpit</h1><p>Analitik dokumen billing/invoice: nilai DPP, PPN, grand total, due date, overdue, dan document flow ke SO serta Surat Jalan.</p></div><div class="col-md-4 text-right"><a class="btn btn-warning btn-lg" href="<?=base_index();?>sales-invoice"><i class="fa fa-file-text"></i> <?=sd_h('sales_invoice', 'Sales Invoice');?></a></div></div></div>
  <div class="row"><div class="col-sm-3"><div class="br-kpi"><i class="fa fa-file-text-o"></i><span>Invoices</span><strong><?=number_format((float)$sum->invoice_count,0,',','.');?></strong></div></div><div class="col-sm-3"><div class="br-kpi"><i class="fa fa-calculator"></i><span>DPP</span><strong><?=number_format((float)$sum->subtotal,2,',','.');?></strong></div></div><div class="col-sm-3"><div class="br-kpi"><i class="fa fa-percent"></i><span>PPN</span><strong><?=number_format((float)$sum->tax_amount,2,',','.');?></strong></div></div><div class="col-sm-3"><div class="br-kpi"><i class="fa fa-warning"></i><span>Overdue</span><strong><?=number_format((float)$sum->overdue_count,0,',','.');?></strong></div></div></div>
  <div class="br-help"><strong>Standar SAP SD:</strong> Billing Report dipakai untuk menganalisa dokumen billing yang sudah dibuat, bukan untuk input invoice. Fokusnya audit nilai, pajak, due date, customer, SO, delivery reference, dan export.</div>
  <div class="box br-card"><div class="box-header"><h3 class="box-title"><i class="fa fa-filter"></i> Filter Billing Report</h3></div><div class="box-body"><form class="form-horizontal" onsubmit="return false;"><div class="form-group"><label class="control-label col-lg-2">Invoice Date</label><div class="col-lg-2"><div class="input-group date br-date"><input id="filter_tgl_awal" class="form-control" value="<?=$defaultFrom;?>"><span class="input-group-addon"><span class="glyphicon glyphicon-calendar"></span></span></div></div><div class="col-lg-2"><div class="input-group date br-date"><input id="filter_tgl_akhir" class="form-control" value="<?=$defaultTo;?>"><span class="input-group-addon"><span class="glyphicon glyphicon-calendar"></span></span></div></div><label class="control-label col-lg-1"><?=sd_h('sales_customer', 'Customer');?></label><div class="col-lg-3"><select id="filter_customer" class="form-control"><option value=""><?=sd_h('common_all', 'All');?></option><?php foreach($customers as $c){ ?><option value="<?=br_h($c->kode_penerima);?>"><?=br_h($c->nama);?></option><?php } ?></select></div><div class="col-lg-2"><select id="filter_currency" class="form-control"><option value=""><?=sd_h('sales_currency', 'Currency');?></option><?php foreach($currencies as $c){ ?><option value="<?=br_h($c->valuta);?>"><?=br_h($c->valuta);?></option><?php } ?></select></div></div><div class="form-group"><label class="control-label col-lg-2"><?=sd_h('sales_tax', 'Tax');?></label><div class="col-lg-2"><select id="filter_tax_status" class="form-control"><option value=""><?=sd_h('common_all', 'All');?></option><option value="TAXED">Taxed</option><option value="NO_TAX">No Tax</option></select></div><label class="control-label col-lg-1">Due</label><div class="col-lg-2"><select id="filter_due_status" class="form-control"><option value=""><?=sd_h('common_all', 'All');?></option><option value="OVERDUE">Overdue</option><option value="NOT_DUE">Not Due</option></select></div><label class="control-label col-lg-1">Sales</label><div class="col-lg-2"><select id="filter_sales_person" class="form-control"><option value=""><?=sd_h('common_all', 'All');?></option><?php foreach($salesUsers as $s){ ?><option value="<?=br_h($s->sales_id);?>"><?=br_h($s->sales_id);?></option><?php } ?></select></div><div class="col-lg-2"><input id="filter_keyword" class="form-control" placeholder="Invoice, SO, SJ, PO"></div></div><div class="form-group"><div class="col-lg-offset-2 col-lg-10"><button id="btn_filter_br" class="btn btn-primary"><i class="fa fa-filter"></i> <?=sd_h('common_filter', 'Filter');?></button> <button id="btn_reset_br" class="btn btn-default"><i class="fa fa-refresh"></i> <?=sd_h('common_reset', 'Reset');?></button> <button id="btn_excel_br" class="btn btn-success"><i class="fa fa-file-excel-o"></i> <?=sd_h('common_export_excel', 'Export Excel');?></button></div></div></form></div></div>
  <div class="box br-card"><div class="box-body"><div class="alert alert-warning error_data_delete" style="display:none"><button type="button" class="close hide_alert_notif">&times;</button><span class="isi_warning_delete"></span></div><div class="table-responsive"><table id="dtb_billing_report" class="table table-bordered table-striped table-condensed" style="width:100%"><thead><tr><th><?=sd_h('common_no', 'No');?></th><th><?=sd_h('common_action', 'Action');?></th><th>Invoice</th><th><?=sd_h('sales_customer', 'Customer');?></th><th><?=sd_h('sales_reference', 'Reference');?></th><th><?=sd_h('sales_items', 'Items');?></th><th><?=sd_h('sales_amount', 'Amount');?></th><th><?=sd_h('sales_tax', 'Tax');?></th><th><?=sd_h('sales_due_date', 'Due Date');?></th><th>Due Status</th><th>Sales</th><th>Notes</th></tr></thead><tbody></tbody></table></div></div></div>
  <div id="modal_detail_br" class="modal fade"><div class="modal-dialog modal-lg" style="width:94%"><div class="modal-content"><div class="modal-header"><button class="close" data-dismiss="modal">&times;</button><h4 class="modal-title">Billing Report Detail</h4></div><div class="modal-body" id="br_detail_body"></div><div class="modal-footer"><a class="btn btn-warning" href="<?=base_index();?>sales-invoice"><i class="fa fa-file-text"></i> <?=sd_h('sales_invoice', 'Sales Invoice');?></a><button class="btn btn-default" data-dismiss="modal"><?=sd_h('common_close', 'Close');?></button></div></div></div></div>
</section>
<script src="<?=base_admin();?>assets/plugins/select2/select2.min.js"></script>
<script>
function brError(m){$('.isi_warning_delete').text(m||<?=sd_js('sales_billing_report_process_failed', 'Billing Report failed to process.');?>);$('.error_data_delete').fadeIn();}
function brFilters(){return{tgl_awal:$('#filter_tgl_awal').val(),tgl_akhir:$('#filter_tgl_akhir').val(),customer:$('#filter_customer').val(),currency:$('#filter_currency').val(),tax_status:$('#filter_tax_status').val(),due_status:$('#filter_due_status').val(),sales_person:$('#filter_sales_person').val(),keyword:$('#filter_keyword').val()};}
$(function(){if($.fn.datepicker){$('.br-date').datepicker({format:'yyyy-mm-dd',autoclose:true,todayHighlight:true});}if($.fn.select2){$('#filter_customer,#filter_currency,#filter_tax_status,#filter_due_status,#filter_sales_person').select2({width:'100%',allowClear:true});}
var dt=$('#dtb_billing_report').DataTable({bProcessing:true,bServerSide:true,pageLength:25,ordering:false,scrollX:true,dom:"<'row'<'col-sm-12'B>>"+"<'row'<'col-sm-6'l><'col-sm-6'f>>"+"<'row'<'col-sm-12'tr>>"+"<'row'<'col-sm-5'i><'col-sm-7'p>>",buttons:[{extend:'collection',text:<?=sd_js('common_export_data', 'Export Data');?>,buttons:['copyHtml5','excelHtml5','csvHtml5','pdfHtml5']}],columnDefs:[{targets:[0,1],orderable:false,searchable:false},{targets:[5,6],className:'text-right'},{width:'38px',targets:0},{width:'78px',targets:1}],ajax:{url:'<?=base_admin();?>modul/billing_report/billing_report_data.php',type:'post',data:function(d){$.extend(d,brFilters());},error:function(xhr){console.log(xhr.responseText);brError(<?=sd_js('sales_billing_report_load_failed', 'Billing Report data failed to load.');?>);}}});
$('#btn_filter_br').click(function(){dt.draw();});$('#filter_keyword').keyup(function(e){if(e.keyCode===13)dt.draw();});$('#btn_reset_br').click(function(){$('#filter_tgl_awal').val('<?=$defaultFrom;?>');$('#filter_tgl_akhir').val('<?=$defaultTo;?>');$('#filter_customer,#filter_currency,#filter_tax_status,#filter_due_status,#filter_sales_person').val('').trigger('change');$('#filter_keyword').val('');dt.draw();});$('#btn_excel_br').click(function(){window.location='<?=base_admin();?>modul/billing_report/billing_report_action.php?act=excel&'+$.param(brFilters());});
$(document).on('click','.btn-br-detail',function(){$.post('<?=base_admin();?>modul/billing_report/billing_report_action.php?act=detail',{id:$(this).data('id')},function(html){$('#br_detail_body').html(html);$('#modal_detail_br').modal('show');}).fail(function(xhr){console.log(xhr.responseText);brError('Detail gagal dibuka.');});});$('.hide_alert_notif').click(function(){$('.error_data_delete').hide();});
});
</script>
