<?php
if (!function_exists('prod_t')) {
  function prod_t($key, $fallback = '') { return lang_text($key, $fallback); }
}
if (!function_exists('prod_h')) {
  function prod_h($key, $fallback = '') { return htmlspecialchars((string) prod_t($key, $fallback), ENT_QUOTES, 'UTF-8'); }
}
if (!function_exists('prod_js')) {
  function prod_js($key, $fallback = '') { return json_encode(prod_t($key, $fallback), JSON_HEX_TAG | JSON_HEX_APOS | JSON_HEX_AMP | JSON_HEX_QUOT); }
}
$defaultFrom=date('Y-m-01');$defaultTo=date('Y-m-d');
$plants=$db->query("SELECT id,plant_code,plant_name FROM erp_plant WHERE status='Aktif' ORDER BY plant_code");
$kpi=$db->fetch("SELECT COUNT(*) created_doc,COALESCE(SUM(priority='URGENT'),0) urgent_doc FROM production_order WHERE status='CREATED'");
?>
<style>
.por-hero{background:linear-gradient(135deg,#6d28d9,#0f766e);color:#fff;border-radius:14px;padding:20px;margin-bottom:18px;box-shadow:0 10px 24px rgba(15,23,42,.16)}.por-hero h1{margin:0 0 6px;font-size:26px;font-weight:700}.por-hero p{margin:0;opacity:.92}.por-card{border-radius:12px;background:#fff;border:1px solid #e5edf5;box-shadow:0 5px 16px rgba(15,23,42,.05);margin-bottom:14px}.por-kpi{border-radius:12px;background:#fff;border:1px solid #edf2f7;padding:15px;margin-bottom:14px}.por-kpi span{color:#64748b;font-size:12px;text-transform:uppercase}.por-kpi strong{display:block;font-size:25px;margin-top:6px}#dtb_po_release th,#dtb_po_release td{font-size:12px;vertical-align:middle}.por-action{white-space:nowrap}.select2-container{width:100%!important}
</style>
<section class="content-header"><h1>Production Order Release <small>SAP PP Release Cockpit</small></h1><ol class="breadcrumb"><li><a href="<?=base_index();?>"><i class="fa fa-dashboard"></i> <?=prod_h('common_home', 'Home');?></a></li><li class="active">Production Order Release</li></ol></section>
<section class="content">
  <div class="por-hero"><div class="row"><div class="col-md-8"><h1>Release Cockpit</h1><p>Validasi kesiapan Production Order sebelum dilepas ke shop floor: material requirement, stock availability, routing operation, production version, dan factory calendar.</p></div><div class="col-md-4 text-right"><button id="btn_export_por_top" class="btn btn-success"><i class="fa fa-file-excel-o"></i> Export Readiness</button></div></div></div>
  <div class="row"><div class="col-sm-3"><div class="por-kpi"><span>Created Waiting Release</span><strong><?=number_format((float)$kpi->created_doc,0,',','.');?></strong></div></div><div class="col-sm-3"><div class="por-kpi"><span>Urgent Orders</span><strong><?=number_format((float)$kpi->urgent_doc,0,',','.');?></strong></div></div></div>
  <div class="box por-card"><div class="box-header"><h3 class="box-title"><i class="fa fa-filter"></i> Filter Release Queue</h3></div><div class="box-body"><form class="form-horizontal" onsubmit="return false;"><div class="form-group"><label class="control-label col-lg-2"><?=prod_h('production_start_date', 'Start Date');?></label><div class="col-lg-2"><div class="input-group date por-date"><input id="filter_tgl_awal" class="form-control" value="<?=$defaultFrom;?>"><span class="input-group-addon"><span class="glyphicon glyphicon-calendar"></span></span></div></div><div class="col-lg-2"><div class="input-group date por-date"><input id="filter_tgl_akhir" class="form-control" value="<?=$defaultTo;?>"><span class="input-group-addon"><span class="glyphicon glyphicon-calendar"></span></span></div></div><label class="control-label col-lg-1"><?=prod_h('production_plant', 'Plant');?></label><div class="col-lg-2"><select id="filter_plant" class="form-control"><option value=""><?=prod_h('common_all', 'All');?></option><?php foreach($plants as $p){ ?><option value="<?=htmlspecialchars($p->plant_code,ENT_QUOTES,'UTF-8');?>"><?=htmlspecialchars($p->plant_code.' - '.$p->plant_name,ENT_QUOTES,'UTF-8');?></option><?php } ?></select></div><label class="control-label col-lg-1">Ready</label><div class="col-lg-2"><select id="filter_ready" class="form-control"><option value=""><?=prod_h('common_all', 'All');?></option><option value="Y">No Error Only</option></select></div></div><div class="form-group"><label class="control-label col-lg-2"><?=prod_h('common_search', 'Search');?></label><div class="col-lg-7"><input id="filter_keyword" class="form-control" placeholder="PO / material / PV / BOM / routing"></div><div class="col-lg-3"><button id="btn_filter_por" class="btn btn-primary"><i class="fa fa-filter"></i> <?=prod_h('common_filter', 'Filter');?></button> <button id="btn_reset_por" class="btn btn-default"><i class="fa fa-refresh"></i> <?=prod_h('common_reset', 'Reset');?></button> <button id="btn_export_por" class="btn btn-success"><i class="fa fa-file-excel-o"></i> <?=prod_h('common_export_excel', 'Export Excel');?></button></div></div></form></div></div>
  <div class="box por-card"><div class="box-body"><div class="alert alert-warning error_data_delete" style="display:none"><button type="button" class="close hide_alert_notif">&times;</button><span class="isi_warning_delete"></span></div><div class="table-responsive"><table id="dtb_po_release" class="table table-bordered table-striped" style="width:100%"><thead><tr><th><?=prod_h('common_no', 'No');?></th><th><?=prod_h('common_action', 'Action');?></th><th><?=prod_h('production_order', 'Production Order');?></th><th><?=prod_h('production_material', 'Material');?></th><th><?=prod_h('production_qty', 'Qty');?></th><th>Plant/SLoc</th><th>Schedule</th><th>PV/BOM/Routing</th><th>Structure</th><th>Readiness</th><th><?=prod_h('common_status', 'Status');?></th></tr></thead><tbody></tbody></table></div></div></div>
  <div id="modal_por_detail" class="modal fade"><div class="modal-dialog modal-lg" style="width:96%"><div class="modal-content"><div class="modal-header"><button class="close" data-dismiss="modal">&times;</button><h4 class="modal-title">Production Order Release Readiness</h4></div><div class="modal-body" id="por_detail_body"></div><div class="modal-footer"><button class="btn btn-default" data-dismiss="modal"><?=prod_h('common_close', 'Close');?></button></div></div></div></div>
</section>
<script src="<?=base_admin();?>assets/plugins/select2/select2.min.js"></script><script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
<script>
function porError(m){$('.isi_warning_delete').text(m||<?=prod_js('production_order_release_process_failed', 'Production Order Release failed to process.');?>);$('.error_data_delete').fadeIn();}
function porFilters(){return{tgl_awal:$('#filter_tgl_awal').val(),tgl_akhir:$('#filter_tgl_akhir').val(),plant:$('#filter_plant').val(),keyword:$('#filter_keyword').val(),only_ready:$('#filter_ready').val()};}
$(function(){if($.fn.datepicker){$('.por-date').datepicker({format:'yyyy-mm-dd',autoclose:true,todayHighlight:true});}if($.fn.select2){$('#filter_plant,#filter_ready').select2({width:'100%'});}
var dt=$('#dtb_po_release').DataTable({bProcessing:true,bServerSide:true,pageLength:25,dom:"<'row'<'col-sm-12'B>>"+"<'row'<'col-sm-6'l><'col-sm-6'f>>"+"<'row'<'col-sm-12'tr>>"+"<'row'<'col-sm-5'i><'col-sm-7'p>>",buttons:[{extend:'collection',text:<?=prod_js('common_export_data', 'Export Data');?>,buttons:['copyHtml5','excelHtml5','csvHtml5','pdfHtml5']}],columnDefs:[{targets:[0,1],orderable:false,searchable:false},{targets:[4],className:'text-right'},{width:'42px',targets:0},{width:'135px',targets:1}],ajax:{url:'<?=base_admin();?>modul/production_order_release/production_order_release_data.php',type:'post',data:function(d){$.extend(d,porFilters());},error:function(xhr){console.log(xhr.responseText);porError(<?=prod_js('production_release_queue_load_failed', 'Release queue data failed to load.');?>);}}});
function reload(){dt.draw(false);}function exportUrl(){return '<?=base_admin();?>modul/production_order_release/production_order_release_action.php?act=excel&'+$.param(porFilters());}
$('#btn_filter_por').click(function(){reload();});$('#filter_keyword').keyup(function(e){if(e.keyCode===13)reload();});$('#btn_reset_por').click(function(){$('#filter_tgl_awal').val('<?=$defaultFrom;?>');$('#filter_tgl_akhir').val('<?=$defaultTo;?>');$('#filter_plant,#filter_ready').val('').trigger('change');$('#filter_keyword').val('');reload();});$('#btn_export_por,#btn_export_por_top').click(function(){window.location=exportUrl();});$('.hide_alert_notif').click(function(){$('.error_data_delete').hide();});
$(document).on('click','.btn-por-detail,.btn-por-check',function(){$.post('<?=base_admin();?>modul/production_order_release/production_order_release_action.php?act=detail',{id:$(this).data('id')},function(html){$('#por_detail_body').html(html);$('#modal_por_detail').modal('show');}).fail(function(){porError('Detail readiness gagal dibuka.');});});
$(document).on('click','.btn-por-release',function(){var id=$(this).data('id'),no=$(this).data('no');Swal.fire({title:<?=prod_js('production_release_order_confirm', 'Release Production Order?');?>,text:no+' akan dilepas ke shop floor. Warning stock tetap dicatat di log release.',input:'text',inputLabel:'Remarks release (opsional)',icon:'question',showCancelButton:true,confirmButtonText:<?=prod_js('production_release', 'Release');?>}).then(function(r){if(!r.isConfirmed)return;$.post('<?=base_admin();?>modul/production_order_release/production_order_release_action.php?act=release',{id:id,remarks:r.value||''},function(res){if(res.status==='good'){Swal.fire('Released',no+' berhasil release.','success');reload();}else porError(res.error_message);},'json').fail(function(xhr){porError(xhr.responseText);});});});
});
</script>
