<?php
if (!function_exists('hr_t')) {
  function hr_t($key, $fallback = '') { return lang_text($key, $fallback); }
}
if (!function_exists('hr_h')) {
  function hr_h($key, $fallback = '') { return htmlspecialchars((string) hr_t($key, $fallback), ENT_QUOTES, 'UTF-8'); }
}
if (!function_exists('hr_js')) {
  function hr_js($key, $fallback = '') { return json_encode(hr_t($key, $fallback), JSON_HEX_TAG | JSON_HEX_APOS | JSON_HEX_AMP | JSON_HEX_QUOT); }
}
if (session_status() === PHP_SESSION_NONE) session_start();
include "../../inc/config.php";
session_check_json();
function isd_h($v){return htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');}
function isd_label($s){$m=array('DRAFT'=>'default','SCHEDULED'=>'info','CONFIRMED'=>'primary','COMPLETED'=>'success','RESCHEDULED'=>'warning','CANCELLED'=>'danger','NO_SHOW'=>'danger');$c=isset($m[$s])?$m[$s]:'default';return '<span class="label label-'.$c.'">'.isd_h($s).'</span>';}
function isd_filters(){return array('from'=>isset($_POST['tgl_awal'])&&$_POST['tgl_awal']!==''?$_POST['tgl_awal']:date('Y-m-01'),'to'=>isset($_POST['tgl_akhir'])&&$_POST['tgl_akhir']!==''?$_POST['tgl_akhir']:date('Y-m-t'),'status'=>isset($_POST['interview_status'])?trim($_POST['interview_status']):'','type'=>isset($_POST['interview_type'])?trim($_POST['interview_type']):'','method'=>isset($_POST['interview_method'])?trim($_POST['interview_method']):'','interviewer'=>isset($_POST['interviewer_employee_id'])?trim($_POST['interviewer_employee_id']):'','keyword'=>isset($_POST['keyword'])?trim($_POST['keyword']):'');}
function isd_where($f,&$p){$w=" WHERE i.schedule_date BETWEEN ? AND ? ";array_push($p,$f['from'],$f['to']);if($f['status']!==''){$w.=" AND i.interview_status=? ";$p[]=$f['status'];}if($f['type']!==''){$w.=" AND i.interview_type=? ";$p[]=$f['type'];}if($f['method']!==''){$w.=" AND i.interview_method=? ";$p[]=$f['method'];}if($f['interviewer']!==''){$w.=" AND (i.primary_interviewer_employee_id=? OR i.hr_interviewer_employee_id=? OR i.technical_interviewer_employee_id=? OR i.hiring_manager_employee_id=? OR EXISTS(SELECT 1 FROM erp_interview_schedule_panel p2 WHERE p2.interview_id=i.id AND p2.interviewer_employee_id=?)) ";for($x=0;$x<5;$x++)$p[]=(int)$f['interviewer'];}if($f['keyword']!==''){$kw='%'.$f['keyword'].'%';$w.=" AND (i.interview_no LIKE ? OR a.applicant_no LIKE ? OR a.applicant_name LIKE ? OR v.vacancy_no LIKE ? OR v.vacancy_title LIKE ?) ";array_push($p,$kw,$kw,$kw,$kw,$kw);}return $w;}
$draw=isset($_POST['draw'])?(int)$_POST['draw']:1;$start=isset($_POST['start'])?max(0,(int)$_POST['start']):0;$length=isset($_POST['length'])?(int)$_POST['length']:25;if($length<=0||$length>500)$length=25;
$f=isd_filters();$p=array();$w=isd_where($f,$p);
$base=" FROM erp_interview_schedule i LEFT JOIN erp_applicant_data a ON a.id=i.applicant_id LEFT JOIN erp_job_vacancy v ON v.id=i.vacancy_id LEFT JOIN erp_employee_master rec ON rec.id=i.recruiter_employee_id LEFT JOIN erp_employee_master pri ON pri.id=i.primary_interviewer_employee_id ";
$kpi=$db->fetch("SELECT COUNT(*) total,SUM(i.interview_status='SCHEDULED') scheduled,SUM(i.interview_status='CONFIRMED') confirmed,SUM(i.interview_status='COMPLETED') completed,SUM(i.interview_status='CANCELLED') cancelled,AVG(NULLIF(i.overall_score,0)) avg_score $base $w",$p);
$cnt=$db->fetch("SELECT COUNT(*) jml $base $w",$p);$total=$cnt?(int)$cnt->jml:0;
$orderMap=array(2=>'i.interview_no',3=>'a.applicant_name',4=>'v.vacancy_no',5=>'i.interview_type',6=>'i.schedule_date',7=>'pri.employee_no',8=>'i.overall_score',9=>'i.interview_status',10=>'i.updated_at');$orderBy='i.schedule_date DESC,i.start_time DESC';
if(isset($_POST['order'][0]['column'])){$col=(int)$_POST['order'][0]['column'];$dir=(isset($_POST['order'][0]['dir'])&&strtolower($_POST['order'][0]['dir'])==='desc')?'DESC':'ASC';if(isset($orderMap[$col]))$orderBy=$orderMap[$col].' '.$dir;}
$rows=$db->query("SELECT i.*,a.applicant_no,a.applicant_name,a.applicant_status,v.vacancy_no,v.vacancy_title,rec.employee_no recruiter_no,rec.full_name recruiter_name,pri.employee_no primary_no,pri.full_name primary_name $base $w ORDER BY $orderBy LIMIT $start,$length",$p);
$data=array();$no=$start+1;foreach($rows as $r){$canDelete=in_array($r->interview_status,array('DRAFT','CANCELLED'),true);$act='<div class="is-action"><button class="btn btn-info btn-xs btn-is-detail" data-id="'.(int)$r->id.'"><i class="fa fa-eye"></i></button> <button class="btn btn-primary btn-xs btn-is-edit" data-id="'.(int)$r->id.'"><i class="fa fa-pencil"></i></button> <button class="btn btn-success btn-xs btn-is-status" data-id="'.(int)$r->id.'" data-status="COMPLETED"><i class="fa fa-check"></i></button> <button class="btn btn-warning btn-xs btn-is-status" data-id="'.(int)$r->id.'" data-status="CONFIRMED"><i class="fa fa-calendar-check-o"></i></button> <button class="btn btn-danger btn-xs btn-is-delete" data-id="'.(int)$r->id.'" data-no="'.isd_h($r->interview_no).'"'.($canDelete?'':' disabled').'><i class="fa fa-trash"></i></button></div>';
  $data[]=array($no++,$act,'<strong>'.isd_h($r->interview_no).'</strong><br><small>'.isd_h($r->sap_reference?:'-').'</small>','<strong>'.isd_h($r->applicant_no.' - '.$r->applicant_name).'</strong><br><small>'.isd_h($r->applicant_status).'</small>','<strong>'.isd_h($r->vacancy_no?:'-').'</strong><br><small>'.isd_h($r->vacancy_title?:'-').'</small>','<span class="label label-info">'.isd_h($r->interview_type).'</span><br><small>'.isd_h($r->interview_method.' / Round '.$r->interview_round).'</small>','<strong>'.isd_h($r->schedule_date).'</strong><br><small>'.isd_h(substr($r->start_time,0,5).' - '.substr($r->end_time,0,5)).'</small>','<strong>'.isd_h($r->primary_no?:'-').'</strong><br><small>'.isd_h($r->primary_name?:'-').'</small>','<strong>'.number_format((float)$r->overall_score,2).'</strong><br><small>'.isd_h($r->recommendation).'</small>',isd_label($r->interview_status),isd_h($r->updated_by?:$r->created_by?:'-').'<br><small>'.isd_h($r->updated_at?:$r->created_at).'</small>');}
header('Content-Type: application/json; charset=utf-8');echo json_encode(array('draw'=>$draw,'recordsTotal'=>$total,'recordsFiltered'=>$total,'data'=>$data,'kpi'=>array('total'=>$kpi?(int)$kpi->total:0,'scheduled'=>$kpi?(int)$kpi->scheduled:0,'confirmed'=>$kpi?(int)$kpi->confirmed:0,'completed'=>$kpi?(int)$kpi->completed:0,'cancelled'=>$kpi?(int)$kpi->cancelled:0,'avg_score'=>$kpi?number_format((float)$kpi->avg_score,2):'0.00')));
?>
