<?php
if (!function_exists('hr_t')) {
  function hr_t($key, $fallback = '') { return lang_text($key, $fallback); }
}
if (!function_exists('hr_h')) {
  function hr_h($key, $fallback = '') { return htmlspecialchars((string) hr_t($key, $fallback), ENT_QUOTES, 'UTF-8'); }
}
if (!function_exists('hr_js')) {
  function hr_js($key, $fallback = '') { return json_encode(hr_t($key, $fallback), JSON_HEX_TAG | JSON_HEX_APOS | JSON_HEX_AMP | JSON_HEX_QUOT); }
}
$defaultFrom=date('Y-m-01');$defaultTo=date('Y-m-t');$canInsert=isset($role_act['insert_act'])&&$role_act['insert_act']==='Y'; ?>
<style>
.is-hero{background:linear-gradient(135deg,#2563eb,#9333ea);color:#fff;border-radius:14px;padding:22px;margin-bottom:14px;box-shadow:0 8px 24px rgba(37,99,235,.18)}.is-hero h1{margin:0 0 6px;font-weight:700}.is-hero p{margin:0;color:#eef2ff}.is-card{border-radius:12px;border:1px solid #e5edf5;box-shadow:0 4px 14px rgba(15,23,42,.05)}.is-kpi{background:#fff;border:1px solid #e5edf5;border-radius:12px;padding:13px;margin-bottom:14px}.is-kpi span{font-size:12px;color:#64748b}.is-kpi b{display:block;font-size:21px;color:#0f172a}#dtb_interview_schedule th,#dtb_interview_schedule td,#panel_table th,#panel_table td{font-size:12px;vertical-align:middle}.is-action{white-space:nowrap}.select2-container{width:100%!important}.required-label:after{content:' *';color:#dd4b39}#modal_is .modal-body{max-height:calc(100vh - 180px);overflow-y:auto}.is-section{font-weight:700;color:#334155;border-bottom:1px solid #e5e7eb;padding-bottom:7px;margin:8px 0 12px}.panel-box{background:#f8fafc;border:1px solid #e2e8f0;border-radius:10px;padding:12px;margin-bottom:12px}
</style>
<section class="content-header"><h1><?=hr_h('hr_interview_schedule', 'Interview Schedule');?> <small>SAP HCM Recruitment</small></h1><ol class="breadcrumb"><li><a href="<?=base_index();?>"><i class="fa fa-dashboard"></i> <?=hr_h('common_home', 'Home');?></a></li><li>Human Resource</li><li>Recruitment</li><li class="active"><?=hr_h('hr_interview_schedule', 'Interview Schedule');?></li></ol></section>
<section class="content">
<div class="is-hero"><div class="row"><div class="col-md-8"><h1>Interview Schedule Cockpit</h1><p>Atur jadwal interview, panel interviewer, konfirmasi kandidat, scoring, rekomendasi, dan hasil interview dalam satu flow recruitment.</p></div><div class="col-md-4 text-right"><?php if($canInsert){ ?><button id="btn_open_is" class="btn btn-warning"><i class="fa fa-plus"></i> Create Interview</button><?php } ?> <button id="btn_export_is" class="btn btn-success"><i class="fa fa-file-excel-o"></i> <?=hr_h('common_export_excel', 'Export Excel');?></button></div></div></div>
<div class="row"><div class="col-sm-2"><div class="is-kpi"><span>Total</span><b id="kpi_total">0</b></div></div><div class="col-sm-2"><div class="is-kpi"><span>Scheduled</span><b id="kpi_scheduled">0</b></div></div><div class="col-sm-2"><div class="is-kpi"><span>Confirmed</span><b id="kpi_confirmed">0</b></div></div><div class="col-sm-2"><div class="is-kpi"><span>Completed</span><b id="kpi_completed">0</b></div></div><div class="col-sm-2"><div class="is-kpi"><span>Cancelled</span><b id="kpi_cancelled">0</b></div></div><div class="col-sm-2"><div class="is-kpi"><span>Avg Score</span><b id="kpi_avg_score">0</b></div></div></div>
<div class="box is-card"><div class="box-header"><h3 class="box-title"><i class="fa fa-filter"></i> Filter Interview</h3></div><div class="box-body"><form class="form-horizontal" onsubmit="return false;"><div class="form-group"><label class="control-label col-lg-2">Schedule Date</label><div class="col-lg-2"><div class="input-group date is-date"><input id="filter_tgl_awal" class="form-control" value="<?=$defaultFrom;?>"><span class="input-group-addon"><span class="glyphicon glyphicon-calendar"></span></span></div></div><div class="col-lg-2"><div class="input-group date is-date"><input id="filter_tgl_akhir" class="form-control" value="<?=$defaultTo;?>"><span class="input-group-addon"><span class="glyphicon glyphicon-calendar"></span></span></div></div><label class="control-label col-lg-1">Type</label><div class="col-lg-2"><select id="filter_interview_type" class="form-control"><option value=""><?=hr_h('common_all', 'All');?></option><option>HR</option><option>TECHNICAL</option><option>USER</option><option>PANEL</option><option>FINAL</option><option>ONLINE</option></select></div><label class="control-label col-lg-1"><?=hr_h('common_status', 'Status');?></label><div class="col-lg-2"><select id="filter_interview_status" class="form-control"><option value=""><?=hr_h('common_all', 'All');?></option><option>DRAFT</option><option>SCHEDULED</option><option>CONFIRMED</option><option>COMPLETED</option><option>RESCHEDULED</option><option>CANCELLED</option><option>NO_SHOW</option></select></div></div><div class="form-group"><label class="control-label col-lg-2">Method</label><div class="col-lg-2"><select id="filter_interview_method" class="form-control"><option value=""><?=hr_h('common_all', 'All');?></option><option>ONSITE</option><option>ONLINE</option><option>PHONE</option></select></div><label class="control-label col-lg-1">Interviewer</label><div class="col-lg-3"><select id="filter_interviewer_employee_id" class="form-control"></select></div><div class="col-lg-3"><input id="filter_keyword" class="form-control" placeholder="Interview no, applicant, vacancy"></div><div class="col-lg-1"><button id="btn_filter_is" class="btn btn-primary"><i class="fa fa-filter"></i></button> <button id="btn_reset_is" class="btn btn-default"><i class="fa fa-refresh"></i></button></div></div></form></div></div>
<div class="box is-card"><div class="box-body"><div class="alert alert-warning error_data_delete" style="display:none"><button type="button" class="close hide_alert_notif">&times;</button><span class="isi_warning_delete"></span></div><div class="table-responsive"><table id="dtb_interview_schedule" class="table table-bordered table-striped" style="width:100%"><thead><tr><th><?=hr_h('common_no', 'No');?></th><th><?=hr_h('common_action', 'Action');?></th><th>Interview No</th><th><?=hr_h('hr_applicant', 'Applicant');?></th><th>Vacancy</th><th>Type</th><th>Schedule</th><th>Primary Interviewer</th><th><?=hr_h('hr_score', 'Score');?></th><th><?=hr_h('common_status', 'Status');?></th><th>Updated</th></tr></thead><tbody></tbody></table></div></div></div>
<div id="modal_is" class="modal fade"><div class="modal-dialog modal-lg" style="width:96%"><div class="modal-content"><form id="form_is"><input type="hidden" name="id" id="is_id"><input type="hidden" name="panels_json" id="panels_json"><div class="modal-header"><button type="button" class="close" data-dismiss="modal">&times;</button><h4 class="modal-title">Create Interview Schedule</h4></div><div class="modal-body">
<div class="alert alert-info"><strong>SAP hint:</strong> Pilih applicant terlebih dahulu, vacancy/recruiter/hiring manager akan ikut terisi dari recruitment pipeline.</div>
<div class="is-section">Schedule Header</div><div class="row"><div class="col-md-2 form-group"><label class="required-label">Interview No</label><div class="input-group"><input name="interview_no" id="interview_no" class="form-control" readonly><span class="input-group-btn"><button type="button" id="btn_next_is" class="btn btn-default"><i class="fa fa-refresh"></i></button></span></div></div><div class="col-md-4 form-group"><label class="required-label"><?=hr_h('hr_applicant', 'Applicant');?></label><select name="applicant_id" id="applicant_id" class="form-control"></select></div><div class="col-md-3 form-group"><label>Vacancy</label><select name="vacancy_id" id="vacancy_id" class="form-control"></select></div><div class="col-md-1 form-group"><label>Round</label><input name="interview_round" id="interview_round" type="number" min="1" class="form-control" value="1"></div><div class="col-md-2 form-group"><label><?=hr_h('common_status', 'Status');?></label><select name="interview_status" id="interview_status" class="form-control"><option>DRAFT</option><option>SCHEDULED</option><option>CONFIRMED</option><option>COMPLETED</option><option>RESCHEDULED</option><option>CANCELLED</option><option>NO_SHOW</option></select></div></div>
<div class="row"><div class="col-md-2 form-group"><label>Type</label><select name="interview_type" id="interview_type" class="form-control"><option>HR</option><option>TECHNICAL</option><option>USER</option><option>PANEL</option><option>FINAL</option><option>ONLINE</option></select></div><div class="col-md-2 form-group"><label>Method</label><select name="interview_method" id="interview_method" class="form-control"><option>ONSITE</option><option>ONLINE</option><option>PHONE</option></select></div><div class="col-md-2 form-group"><label class="required-label"><?=hr_h('hr_date', 'Date');?></label><input name="schedule_date" id="schedule_date" class="form-control date-field" value="<?=date('Y-m-d');?>"></div><div class="col-md-2 form-group"><label>Start</label><input name="start_time" id="start_time" class="form-control" placeholder="09:00"></div><div class="col-md-2 form-group"><label>End</label><input name="end_time" id="end_time" class="form-control" placeholder="10:00"></div><div class="col-md-2 form-group"><label>Timezone</label><input name="timezone" id="timezone" class="form-control" value="Asia/Jakarta"></div></div>
<div class="row"><div class="col-md-3 form-group"><label>Location</label><input name="location" id="location" class="form-control"></div><div class="col-md-5 form-group"><label>Meeting Link</label><input name="meeting_link" id="meeting_link" class="form-control"></div><div class="col-md-2 form-group"><label>Confirmation Sent</label><select name="confirmation_sent" id="confirmation_sent" class="form-control"><option>N</option><option>Y</option></select></div><div class="col-md-2 form-group"><label>Applicant Confirmed</label><select name="applicant_confirmed" id="applicant_confirmed" class="form-control"><option>N</option><option>Y</option></select></div></div>
<div class="is-section">Interviewer Assignment</div><div class="row"><div class="col-md-3 form-group"><label>Recruiter</label><select name="recruiter_employee_id" id="recruiter_employee_id" class="form-control"></select></div><div class="col-md-3 form-group"><label>Primary Interviewer</label><select name="primary_interviewer_employee_id" id="primary_interviewer_employee_id" class="form-control"></select></div><div class="col-md-3 form-group"><label>HR Interviewer</label><select name="hr_interviewer_employee_id" id="hr_interviewer_employee_id" class="form-control"></select></div><div class="col-md-3 form-group"><label>Technical Interviewer</label><select name="technical_interviewer_employee_id" id="technical_interviewer_employee_id" class="form-control"></select></div></div><div class="row"><div class="col-md-3 form-group"><label>Hiring Manager</label><select name="hiring_manager_employee_id" id="hiring_manager_employee_id" class="form-control"></select></div><div class="col-md-2 form-group"><label>Overall Score</label><input name="overall_score" id="overall_score" type="number" step="0.01" min="0" max="100" class="form-control" value="0"></div><div class="col-md-2 form-group"><label>Recommendation</label><select name="recommendation" id="recommendation" class="form-control"><option>PENDING</option><option>PASS</option><option>HOLD</option><option>FAIL</option><option>REINTERVIEW</option></select></div><div class="col-md-5 form-group"><label>Cancellation Reason</label><input name="cancellation_reason" id="cancellation_reason" class="form-control"></div></div>
<div class="is-section">Panel Detail</div><div class="panel-box"><div class="row"><div class="col-md-4 form-group"><label>Interviewer</label><select id="panel_employee_id" class="form-control"></select></div><div class="col-md-2 form-group"><label>Role</label><select id="panel_role" class="form-control"><option>USER</option><option>HR</option><option>TECHNICAL</option><option>HIRING_MANAGER</option><option>OBSERVER</option></select></div><div class="col-md-2 form-group"><label><?=hr_h('hr_attendance', 'Attendance');?></label><select id="panel_attendance" class="form-control"><option>INVITED</option><option>CONFIRMED</option><option>ATTENDED</option><option>ABSENT</option></select></div><div class="col-md-1 form-group"><label><?=hr_h('hr_score', 'Score');?></label><input id="panel_score" type="number" min="0" max="100" step="0.01" class="form-control" value="0"></div><div class="col-md-2 form-group"><label>Feedback</label><input id="panel_feedback" class="form-control"></div><div class="col-md-1 form-group"><label>&nbsp;</label><button type="button" id="btn_add_panel" class="btn btn-primary btn-block"><i class="fa fa-plus"></i></button></div></div></div><div class="table-responsive"><table id="panel_table" class="table table-bordered table-condensed"><thead><tr><th><?=hr_h('common_no', 'No');?></th><th>Interviewer</th><th>Role</th><th><?=hr_h('hr_attendance', 'Attendance');?></th><th><?=hr_h('hr_score', 'Score');?></th><th>Feedback</th><th></th></tr></thead><tbody></tbody></table></div>
<div class="is-section">Notes</div><div class="row"><div class="col-md-4 form-group"><label>Agenda</label><textarea name="agenda" id="agenda" rows="3" class="form-control"></textarea></div><div class="col-md-4 form-group"><label>Preparation Notes</label><textarea name="preparation_notes" id="preparation_notes" rows="3" class="form-control"></textarea></div><div class="col-md-4 form-group"><label>Result Notes</label><textarea name="result_notes" id="result_notes" rows="3" class="form-control"></textarea></div></div><div class="row"><div class="col-md-3 form-group"><label>SAP Reference</label><input name="sap_reference" id="sap_reference" class="form-control"></div><div class="col-md-9 form-group"><label><?=hr_h('common_remarks', 'Remarks');?></label><input name="remarks" id="remarks" class="form-control"></div></div>
</div><div class="modal-footer"><button type="button" class="btn btn-default" data-dismiss="modal"><?=hr_h('common_cancel', 'Cancel');?></button><button type="submit" class="btn btn-primary"><i class="fa fa-save"></i> Save Interview</button></div></form></div></div></div>
<div id="modal_is_detail" class="modal fade"><div class="modal-dialog modal-lg" style="width:94%"><div class="modal-content"><div class="modal-header"><button class="close" data-dismiss="modal">&times;</button><h4 class="modal-title">Interview Detail</h4></div><div class="modal-body" id="is_detail_body"></div><div class="modal-footer"><button class="btn btn-default" data-dismiss="modal"><?=hr_h('common_close', 'Close');?></button></div></div></div></div>
</section>
<script src="<?=base_admin();?>assets/plugins/select2/select2.min.js"></script><script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
<script>
var panels=[];function isError(m){$('.isi_warning_delete').text(m||'Interview gagal diproses.');$('.error_data_delete').fadeIn();}function isFilters(){return{tgl_awal:$('#filter_tgl_awal').val(),tgl_akhir:$('#filter_tgl_akhir').val(),interview_type:$('#filter_interview_type').val(),interview_status:$('#filter_interview_status').val(),interview_method:$('#filter_interview_method').val(),interviewer_employee_id:$('#filter_interviewer_employee_id').val(),keyword:$('#filter_keyword').val()};}
function isSet(s,v,t){var e=$(s);if(!v){e.val(null).trigger('change');return;}if(!e.find('option[value="'+v+'"]').length)e.append(new Option(t||v,v,true,true));e.val(v).trigger('change');}
function ajaxSel(s,act,ph,parent){$(s).select2({width:'100%',allowClear:true,placeholder:ph,dropdownParent:parent||$(document.body),ajax:{url:'<?=base_admin();?>modul/interview_schedule/interview_schedule_action.php?act='+act,type:'POST',dataType:'json',delay:250,data:function(q){return{term:q.term||''};},processResults:function(d){return{results:d.results||[]};}}});}
function nextNo(){ $.post('<?=base_admin();?>modul/interview_schedule/interview_schedule_action.php?act=next_no',{year:($('#schedule_date').val()||'<?=date('Y');?>').substr(0,4)},function(r){if(r.status==='good')$('#interview_no').val(r.interview_no);},'json');}
function resetForm(t){$('#form_is')[0].reset();$('#is_id').val('');$('#schedule_date').val('<?=date('Y-m-d');?>');$('#start_time').val('09:00');$('#end_time').val('10:00');$('#timezone').val('Asia/Jakarta');$('#interview_status').val('DRAFT').trigger('change');$('#interview_type').val('HR').trigger('change');$('#interview_method').val('ONSITE').trigger('change');$('#recommendation').val('PENDING').trigger('change');$('#confirmation_sent,#applicant_confirmed').val('N').trigger('change');$('#applicant_id,#vacancy_id,#recruiter_employee_id,#primary_interviewer_employee_id,#hr_interviewer_employee_id,#technical_interviewer_employee_id,#hiring_manager_employee_id,#panel_employee_id').val(null).trigger('change');panels=[];renderPanels();$('#modal_is .modal-title').text(t||'Create Interview Schedule');nextNo();}
function renderPanels(){var h='';panels.forEach(function(p,i){h+='<tr><td>'+(i+1)+'</td><td>'+($('<div>').text(p.interviewer_text||'').html())+'</td><td>'+p.interviewer_role+'</td><td>'+p.attendance_status+'</td><td class="text-right">'+Number(p.score||0).toFixed(2)+'</td><td>'+($('<div>').text(p.feedback||'').html())+'</td><td><button type="button" class="btn btn-danger btn-xs panel-del" data-i="'+i+'"><i class="fa fa-trash"></i></button></td></tr>';});if(!h)h='<tr><td colspan="7" class="text-center text-muted">Belum ada panel interviewer.</td></tr>';$('#panel_table tbody').html(h);$('#panels_json').val(JSON.stringify(panels));}
$(function(){if($.fn.datepicker){$('.is-date,.date-field').datepicker({format:'yyyy-mm-dd',autoclose:true,todayHighlight:true});}if($.fn.select2){$('#filter_interview_type,#filter_interview_status,#filter_interview_method,#interview_status,#interview_type,#interview_method,#confirmation_sent,#applicant_confirmed,#recommendation,#panel_role,#panel_attendance').select2({width:'100%',allowClear:true});ajaxSel('#filter_interviewer_employee_id','employee_search','Semua Interviewer');ajaxSel('#applicant_id','applicant_search','Pilih Applicant',$('#modal_is'));ajaxSel('#vacancy_id','applicant_search','Auto dari Applicant',$('#modal_is'));ajaxSel('#recruiter_employee_id','employee_search','Pilih Recruiter',$('#modal_is'));ajaxSel('#primary_interviewer_employee_id','employee_search','Pilih Primary',$('#modal_is'));ajaxSel('#hr_interviewer_employee_id','employee_search','Pilih HR',$('#modal_is'));ajaxSel('#technical_interviewer_employee_id','employee_search','Pilih Technical',$('#modal_is'));ajaxSel('#hiring_manager_employee_id','employee_search','Pilih Hiring Manager',$('#modal_is'));ajaxSel('#panel_employee_id','employee_search','Pilih Interviewer',$('#modal_is'));}
var dt=$('#dtb_interview_schedule').DataTable({bProcessing:true,bServerSide:true,pageLength:25,dom:"<'row'<'col-sm-12'B>>"+"<'row'<'col-sm-6'l><'col-sm-6'f>>"+"<'row'<'col-sm-12'tr>>"+"<'row'<'col-sm-5'i><'col-sm-7'p>>",buttons:[{extend:'collection',text:<?=hr_js('common_export_data', 'Export Data');?>,buttons:['copyHtml5','excelHtml5','csvHtml5','pdfHtml5']}],columnDefs:[{targets:[0,1],orderable:false,searchable:false},{targets:[8],className:'text-right'},{width:'42px',targets:0},{width:'150px',targets:1}],ajax:{url:'<?=base_admin();?>modul/interview_schedule/interview_schedule_data.php',type:'post',data:function(d){$.extend(d,isFilters());},dataSrc:function(j){var k=j.kpi||{};$('#kpi_total').text(k.total||0);$('#kpi_scheduled').text(k.scheduled||0);$('#kpi_confirmed').text(k.confirmed||0);$('#kpi_completed').text(k.completed||0);$('#kpi_cancelled').text(k.cancelled||0);$('#kpi_avg_score').text(k.avg_score||0);return j.data||[];},error:function(xhr){console.log(xhr.responseText);isError('Data interview gagal dimuat.');}}});
$('#btn_open_is').click(function(){resetForm('Create Interview Schedule');$('#modal_is').modal({backdrop:'static',keyboard:false});});$('#btn_next_is,#schedule_date').on('click change',nextNo);$('#btn_filter_is').click(function(){dt.draw();});$('#filter_keyword').keyup(function(e){if(e.keyCode===13)dt.draw();});$('#btn_reset_is').click(function(){$('#filter_tgl_awal').val('<?=$defaultFrom;?>');$('#filter_tgl_akhir').val('<?=$defaultTo;?>');$('#filter_interview_type,#filter_interview_status,#filter_interview_method,#filter_interviewer_employee_id').val(null).trigger('change');$('#filter_keyword').val('');dt.draw();});$('#btn_export_is').click(function(){window.location='<?=base_admin();?>modul/interview_schedule/interview_schedule_action.php?act=export&'+$.param(isFilters());});$('.hide_alert_notif').click(function(){$('.error_data_delete').hide();});
$('#applicant_id').on('select2:select',function(e){$.post('<?=base_admin();?>modul/interview_schedule/interview_schedule_action.php?act=applicant_info',{id:e.params.data.id},function(r){if(r.status!=='good')return;var d=r.data||{};isSet('#vacancy_id',d.vacancy_id,d.vacancy_text);isSet('#recruiter_employee_id',d.recruiter_employee_id,d.recruiter_text);isSet('#hr_interviewer_employee_id',d.recruiter_employee_id,d.recruiter_text);isSet('#hiring_manager_employee_id',d.hiring_manager_employee_id,d.manager_text);},'json');});
$('#btn_add_panel').click(function(){var id=$('#panel_employee_id').val();if(!id){isError('Interviewer panel wajib dipilih.');return;}panels.push({interviewer_employee_id:id,interviewer_text:$('#panel_employee_id option:selected').text(),interviewer_role:$('#panel_role').val(),attendance_status:$('#panel_attendance').val(),score:$('#panel_score').val(),feedback:$('#panel_feedback').val()});renderPanels();$('#panel_employee_id').val(null).trigger('change');$('#panel_score').val(0);$('#panel_feedback').val('');});$(document).on('click','.panel-del',function(){panels.splice(parseInt($(this).data('i'),10),1);renderPanels();});
$('#form_is').submit(function(e){e.preventDefault();renderPanels();var b=$(this).find('button[type=submit]');b.prop('disabled',true).html('<i class="fa fa-spinner fa-spin"></i> <?=hr_h('common_saving', 'Saving...');?>');$.post('<?=base_admin();?>modul/interview_schedule/interview_schedule_action.php?act=save',$(this).serialize(),function(r){b.prop('disabled',false).html('<i class="fa fa-save"></i> Save Interview');if(r.status==='good'){$('#modal_is').modal('hide');dt.draw(false);Swal.fire('Saved','Interview Schedule berhasil disimpan.','success');}else isError(r.error_message);},'json').fail(function(xhr){b.prop('disabled',false).html('<i class="fa fa-save"></i> Save Interview');isError(xhr.responseText);});});
$(document).on('click','.btn-is-detail',function(){$.post('<?=base_admin();?>modul/interview_schedule/interview_schedule_action.php?act=detail',{id:$(this).data('id')},function(h){$('#is_detail_body').html(h);$('#modal_is_detail').modal('show');});});
$(document).on('click','.btn-is-edit',function(){var id=$(this).data('id');$.post('<?=base_admin();?>modul/interview_schedule/interview_schedule_action.php?act=get',{id:id},function(r){if(r.status!=='good'){isError(r.error_message);return;}resetForm('Edit Interview Schedule');var h=r.data||{};Object.keys(h).forEach(function(k){var el=$('#'+k);if(el.length&&!['applicant_id','vacancy_id','recruiter_employee_id','primary_interviewer_employee_id','hr_interviewer_employee_id','technical_interviewer_employee_id','hiring_manager_employee_id'].includes(k))el.val(h[k]);});$('#is_id').val(h.id);isSet('#applicant_id',h.applicant_id,h.applicant_text);isSet('#vacancy_id',h.vacancy_id,h.vacancy_text);isSet('#recruiter_employee_id',h.recruiter_employee_id,h.recruiter_text);isSet('#primary_interviewer_employee_id',h.primary_interviewer_employee_id,h.primary_text);isSet('#hr_interviewer_employee_id',h.hr_interviewer_employee_id,h.hr_text);isSet('#technical_interviewer_employee_id',h.technical_interviewer_employee_id,h.technical_text);isSet('#hiring_manager_employee_id',h.hiring_manager_employee_id,h.manager_text);$('#interview_status,#interview_type,#interview_method,#confirmation_sent,#applicant_confirmed,#recommendation').trigger('change');panels=h.panels||[];renderPanels();$('#modal_is').modal({backdrop:'static',keyboard:false});},'json');});
$(document).on('click','.btn-is-status',function(){var id=$(this).data('id'),status=$(this).data('status');$.post('<?=base_admin();?>modul/interview_schedule/interview_schedule_action.php?act=status',{id:id,status:status},function(r){if(r.status==='good'){dt.draw(false);Swal.fire('Updated','Status berhasil diubah.','success');}else isError(r.error_message);},'json');});
$(document).on('click','.btn-is-delete',function(){var id=$(this).data('id'),no=$(this).data('no');Swal.fire({title:erpLang('confirm_delete_title','Delete Confirmation'),text:no,icon:'warning',showCancelButton:true,confirmButtonText:erpLang('common_delete','Delete'),cancelButtonText:erpLang('common_cancel','Cancel')}).then(function(x){if(!x.isConfirmed)return;$.post('<?=base_admin();?>modul/interview_schedule/interview_schedule_action.php?act=delete',{id:id},function(r){if(r.status==='good'){dt.draw(false);Swal.fire(erpLang('common_deleted','Deleted'),erpLang('common_deleted_message','Data deleted successfully.'),'success');}else isError(r.error_message);},'json');});});
});
</script>
