<?php
if (!function_exists('hr_t')) {
  function hr_t($key, $fallback = '') { return lang_text($key, $fallback); }
}
if (!function_exists('hr_h')) {
  function hr_h($key, $fallback = '') { return htmlspecialchars((string) hr_t($key, $fallback), ENT_QUOTES, 'UTF-8'); }
}
if (!function_exists('hr_js')) {
  function hr_js($key, $fallback = '') { return json_encode(hr_t($key, $fallback), JSON_HEX_TAG | JSON_HEX_APOS | JSON_HEX_AMP | JSON_HEX_QUOT); }
}
if (session_status() === PHP_SESSION_NONE) session_start();
include "../../inc/config.php";
session_check_json();
function is_json($s,$m='',$x=array()){header('Content-Type: application/json; charset=utf-8');$p=array('status'=>$s);if($m!=='')$p[$s==='good'?'message':'error_message']=$m;foreach($x as $k=>$v)$p[$k]=$v;echo json_encode($p);exit;}
function is_h($v){return htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');}
function is_p($k,$d=''){return isset($_POST[$k])?$_POST[$k]:$d;} function is_g($k,$d=''){return isset($_GET[$k])?$_GET[$k]:$d;} function is_c($v){return strtoupper(trim((string)$v));} function is_user(){return isset($_SESSION['username'])&&$_SESSION['username']!==''?$_SESSION['username']:'system';}
function is_select2($rows,$id,$cb){$out=array();foreach($rows as $r)$out[]=array('id'=>$r->$id,'text'=>$cb($r));header('Content-Type: application/json; charset=utf-8');echo json_encode(array('results'=>$out));exit;}
function is_next_no($year){global $db;$year=(int)$year>0?(int)$year:(int)date('Y');$r=$db->fetch("SELECT interview_no FROM erp_interview_schedule WHERE interview_no LIKE ? ORDER BY interview_no DESC LIMIT 1",array('INT-'.$year.'-%'));$n=1;if($r&&preg_match('/-(\d+)$/',$r->interview_no,$m))$n=(int)$m[1]+1;return 'INT-'.$year.'-'.str_pad($n,3,'0',STR_PAD_LEFT);}
function is_row($id){global $db;return $db->fetch("SELECT i.*,a.applicant_no,a.applicant_name,a.applicant_status,v.vacancy_no,v.vacancy_title,rec.employee_no recruiter_no,rec.full_name recruiter_name,pri.employee_no primary_no,pri.full_name primary_name,hr.employee_no hr_no,hr.full_name hr_name,tech.employee_no tech_no,tech.full_name tech_name,hm.employee_no manager_no,hm.full_name manager_name FROM erp_interview_schedule i LEFT JOIN erp_applicant_data a ON a.id=i.applicant_id LEFT JOIN erp_job_vacancy v ON v.id=i.vacancy_id LEFT JOIN erp_employee_master rec ON rec.id=i.recruiter_employee_id LEFT JOIN erp_employee_master pri ON pri.id=i.primary_interviewer_employee_id LEFT JOIN erp_employee_master hr ON hr.id=i.hr_interviewer_employee_id LEFT JOIN erp_employee_master tech ON tech.id=i.technical_interviewer_employee_id LEFT JOIN erp_employee_master hm ON hm.id=i.hiring_manager_employee_id WHERE i.id=? LIMIT 1",array((int)$id));}
function is_sync_applicant($applicantId){global $db;if((int)$applicantId<=0)return;$cnt=$db->fetch("SELECT COUNT(*) jml FROM erp_interview_schedule WHERE applicant_id=? AND interview_status<>'CANCELLED'",array((int)$applicantId));if(!$cnt||(int)$cnt->jml===0)return;$r=$db->fetch("SELECT MAX(overall_score) score FROM erp_interview_schedule WHERE applicant_id=? AND interview_status='COMPLETED'",array((int)$applicantId));$score=$r?(float)$r->score:0;$data=array('applicant_status'=>'INTERVIEW','updated_by'=>'admin','updated_at'=>date('Y-m-d H:i:s'));if($score>0){$a=$db->fetch("SELECT screening_score FROM erp_applicant_data WHERE id=? LIMIT 1",array((int)$applicantId));$screen=$a?(float)$a->screening_score:0;$data['interview_score']=$score;$data['final_score']=$screen>0?round(($screen+$score)/2,2):$score;}$db->update('erp_applicant_data',$data,'id',(int)$applicantId);}
function is_payload($r){global $db;$d=(array)$r;$d['applicant_text']=$r->applicant_id?($r->applicant_no.' - '.$r->applicant_name):'';$d['vacancy_text']=$r->vacancy_id?($r->vacancy_no.' - '.$r->vacancy_title):'';$d['recruiter_text']=$r->recruiter_employee_id?($r->recruiter_no.' - '.$r->recruiter_name):'';$d['primary_text']=$r->primary_interviewer_employee_id?($r->primary_no.' - '.$r->primary_name):'';$d['hr_text']=$r->hr_interviewer_employee_id?($r->hr_no.' - '.$r->hr_name):'';$d['technical_text']=$r->technical_interviewer_employee_id?($r->tech_no.' - '.$r->tech_name):'';$d['manager_text']=$r->hiring_manager_employee_id?($r->manager_no.' - '.$r->manager_name):'';$panels=$db->query("SELECT p.*,e.employee_no,e.full_name FROM erp_interview_schedule_panel p LEFT JOIN erp_employee_master e ON e.id=p.interviewer_employee_id WHERE p.interview_id=? ORDER BY p.line_no,p.id",array((int)$r->id));$d['panels']=array();foreach($panels as $p){$a=(array)$p;$a['interviewer_text']=$p->employee_no.' - '.$p->full_name;$d['panels'][]=$a;}return $d;}
function is_export_rows($from,$to,$status,$type,$method,$kw){global $db;$p=array($from,$to);$w=" WHERE i.schedule_date BETWEEN ? AND ? ";if($status!==''){$w.=" AND i.interview_status=? ";$p[]=$status;}if($type!==''){$w.=" AND i.interview_type=? ";$p[]=$type;}if($method!==''){$w.=" AND i.interview_method=? ";$p[]=$method;}if($kw!==''){$like='%'.$kw.'%';$w.=" AND (i.interview_no LIKE ? OR a.applicant_name LIKE ? OR v.vacancy_title LIKE ?) ";array_push($p,$like,$like,$like);}return $db->query("SELECT i.*,a.applicant_no,a.applicant_name,v.vacancy_no,v.vacancy_title,pri.employee_no primary_no,pri.full_name primary_name FROM erp_interview_schedule i LEFT JOIN erp_applicant_data a ON a.id=i.applicant_id LEFT JOIN erp_job_vacancy v ON v.id=i.vacancy_id LEFT JOIN erp_employee_master pri ON pri.id=i.primary_interviewer_employee_id $w ORDER BY i.schedule_date DESC,i.start_time DESC",$p);}
$act=isset($_GET['act'])?$_GET['act']:'';$username=is_user();$statuses=array('DRAFT','SCHEDULED','CONFIRMED','COMPLETED','RESCHEDULED','CANCELLED','NO_SHOW');$types=array('HR','TECHNICAL','USER','PANEL','FINAL','ONLINE');$methods=array('ONSITE','ONLINE','PHONE');$recs=array('PENDING','PASS','HOLD','FAIL','REINTERVIEW');
switch($act){
case 'next_no':is_json('good','',array('interview_no'=>is_next_no((int)is_p('year',date('Y')))));
case 'applicant_search':$t=trim(is_p('term'));$like='%'.$t.'%';$rows=$db->query("SELECT a.id,a.applicant_no,a.applicant_name,a.applicant_status,v.vacancy_no,v.vacancy_title FROM erp_applicant_data a LEFT JOIN erp_job_vacancy v ON v.id=a.vacancy_id WHERE a.applicant_status IN ('SCREENING','SHORTLISTED','INTERVIEW','OFFER','NEW') AND (?='' OR a.applicant_no LIKE ? OR a.applicant_name LIKE ? OR v.vacancy_no LIKE ? OR v.vacancy_title LIKE ?) ORDER BY a.application_date DESC LIMIT 50",array($t,$like,$like,$like,$like));is_select2($rows,'id',function($r){return $r->applicant_no.' - '.$r->applicant_name.' ['.$r->vacancy_no.' / '.$r->applicant_status.']';});
case 'employee_search':$t=trim(is_p('term'));$like='%'.$t.'%';$rows=$db->query("SELECT id,employee_no,full_name,employment_status FROM erp_employee_master WHERE employment_status IN ('ACTIVE','PROBATION','CONTRACT') AND (?='' OR employee_no LIKE ? OR full_name LIKE ?) ORDER BY employee_no LIMIT 40",array($t,$like,$like));is_select2($rows,'id',function($r){return $r->employee_no.' - '.$r->full_name.' ['.$r->employment_status.']';});
case 'applicant_info':$r=$db->fetch("SELECT a.*,v.vacancy_no,v.vacancy_title,v.recruiter_employee_id,v.hiring_manager_employee_id,rec.employee_no rec_no,rec.full_name rec_name,hm.employee_no hm_no,hm.full_name hm_name FROM erp_applicant_data a LEFT JOIN erp_job_vacancy v ON v.id=a.vacancy_id LEFT JOIN erp_employee_master rec ON rec.id=v.recruiter_employee_id LEFT JOIN erp_employee_master hm ON hm.id=v.hiring_manager_employee_id WHERE a.id=? LIMIT 1",array((int)is_p('id')));if(!$r)is_json('error','Applicant tidak ditemukan.');is_json('good','',array('data'=>array('vacancy_id'=>$r->vacancy_id,'vacancy_text'=>$r->vacancy_no.' - '.$r->vacancy_title,'recruiter_employee_id'=>$r->recruiter_employee_id,'recruiter_text'=>$r->rec_no.' - '.$r->rec_name,'hiring_manager_employee_id'=>$r->hiring_manager_employee_id,'manager_text'=>$r->hm_no.' - '.$r->hm_name)));
case 'get':$r=is_row((int)is_p('id'));if(!$r)is_json('error','Interview tidak ditemukan.');is_json('good','',array('data'=>is_payload($r)));
case 'save':
  $id=(int)is_p('id');$no=is_c(is_p('interview_no'));$date=trim(is_p('schedule_date'));if($no===''||$no==='AUTO')$no=is_next_no($date!==''?(int)substr($date,0,4):date('Y'));$app=(int)is_p('applicant_id');$status=is_c(is_p('interview_status','DRAFT'));$type=is_c(is_p('interview_type','HR'));$method=is_c(is_p('interview_method','ONSITE'));$rec=is_c(is_p('recommendation','PENDING'));
  if(!$app)is_json('error','Applicant wajib dipilih.');if($date===''||is_p('start_time')===''||is_p('end_time')==='')is_json('error','Tanggal dan jam interview wajib diisi.');if(!in_array($status,$statuses,true))is_json('error','Status tidak valid.');if(!in_array($type,$types,true))is_json('error','Type tidak valid.');if(!in_array($method,$methods,true))is_json('error','Method tidak valid.');if(!in_array($rec,$recs,true))$rec='PENDING';if($db->fetch("SELECT id FROM erp_interview_schedule WHERE interview_no=? AND id<>? LIMIT 1",array($no,$id)))is_json('error','Interview No sudah digunakan.');
  $vac=is_p('vacancy_id')!==''?(int)is_p('vacancy_id'):null;if(!$vac){$a=$db->fetch("SELECT vacancy_id FROM erp_applicant_data WHERE id=? LIMIT 1",array($app));$vac=$a?(int)$a->vacancy_id:null;}
  $data=array('interview_no'=>$no,'applicant_id'=>$app,'vacancy_id'=>$vac,'interview_round'=>max(1,(int)is_p('interview_round',1)),'interview_type'=>$type,'interview_method'=>$method,'interview_status'=>$status,'schedule_date'=>$date,'start_time'=>is_p('start_time'),'end_time'=>is_p('end_time'),'timezone'=>trim(is_p('timezone','Asia/Jakarta')),'location'=>trim(is_p('location')),'meeting_link'=>trim(is_p('meeting_link')),'recruiter_employee_id'=>is_p('recruiter_employee_id')!==''?(int)is_p('recruiter_employee_id'):null,'primary_interviewer_employee_id'=>is_p('primary_interviewer_employee_id')!==''?(int)is_p('primary_interviewer_employee_id'):null,'hr_interviewer_employee_id'=>is_p('hr_interviewer_employee_id')!==''?(int)is_p('hr_interviewer_employee_id'):null,'technical_interviewer_employee_id'=>is_p('technical_interviewer_employee_id')!==''?(int)is_p('technical_interviewer_employee_id'):null,'hiring_manager_employee_id'=>is_p('hiring_manager_employee_id')!==''?(int)is_p('hiring_manager_employee_id'):null,'confirmation_sent'=>is_c(is_p('confirmation_sent','N'))==='Y'?'Y':'N','confirmation_sent_at'=>trim(is_p('confirmation_sent_at'))?:null,'applicant_confirmed'=>is_c(is_p('applicant_confirmed','N'))==='Y'?'Y':'N','applicant_confirmed_at'=>trim(is_p('applicant_confirmed_at'))?:null,'overall_score'=>(float)is_p('overall_score',0),'recommendation'=>$rec,'result_notes'=>trim(is_p('result_notes')),'agenda'=>trim(is_p('agenda')),'preparation_notes'=>trim(is_p('preparation_notes')),'cancellation_reason'=>trim(is_p('cancellation_reason')),'sap_reference'=>trim(is_p('sap_reference')),'remarks'=>trim(is_p('remarks')),'updated_by'=>$username,'updated_at'=>date('Y-m-d H:i:s'));
  if($id>0){$old=is_row($id);if(!$old)is_json('error','Interview tidak ditemukan.');$ok=$db->update('erp_interview_schedule',$data,'id',$id);}else{$data['created_by']=$username;$ok=$db->insert('erp_interview_schedule',$data);$id=(int)$db->last_insert_id();}
  if(!$ok)is_json('error',$db->getErrorMessage()?:'Interview gagal disimpan.');
  $db->delete('erp_interview_schedule_panel','interview_id',$id);$panels=json_decode(is_p('panels_json','[]'),true);if(is_array($panels)){ $ln=1;foreach($panels as $pnl){$emp=isset($pnl['interviewer_employee_id'])?(int)$pnl['interviewer_employee_id']:0;if(!$emp)continue;$db->insert('erp_interview_schedule_panel',array('interview_id'=>$id,'line_no'=>$ln++,'interviewer_employee_id'=>$emp,'interviewer_role'=>is_c($pnl['interviewer_role']??'USER'),'attendance_status'=>is_c($pnl['attendance_status']??'INVITED'),'score'=>(float)($pnl['score']??0),'feedback'=>trim($pnl['feedback']??'')));}}
  is_sync_applicant($app);if(function_exists('simpan_log'))simpan_log('User '.$username.' menyimpan Interview Schedule '.$no.' pada '.date('Y-m-d H:i:s'),$username);is_json('good','Interview Schedule berhasil disimpan.',array('id'=>$id,'interview_no'=>$no));
case 'status':$id=(int)is_p('id');$status=is_c(is_p('status'));if(!in_array($status,$statuses,true))is_json('error','Status tidak valid.');$r=is_row($id);if(!$r)is_json('error','Interview tidak ditemukan.');$db->update('erp_interview_schedule',array('interview_status'=>$status,'updated_by'=>$username,'updated_at'=>date('Y-m-d H:i:s')),'id',$id);is_sync_applicant((int)$r->applicant_id);is_json('good','Status berhasil diubah.');
case 'delete':$id=(int)is_p('id');$r=is_row($id);if(!$r)is_json('error','Interview tidak ditemukan.');if(!in_array($r->interview_status,array('DRAFT','CANCELLED'),true))is_json('error','Hanya DRAFT/CANCELLED yang boleh dihapus.');$app=(int)$r->applicant_id;$db->delete('erp_interview_schedule','id',$id);if($db->getErrorMessage())is_json('error',$db->getErrorMessage());is_sync_applicant($app);is_json('good','Interview berhasil dihapus.');
case 'detail':$r=is_row((int)is_p('id'));if(!$r){echo '<div class="alert alert-warning">Interview tidak ditemukan.</div>';break;}$pan=$db->query("SELECT p.*,e.employee_no,e.full_name FROM erp_interview_schedule_panel p LEFT JOIN erp_employee_master e ON e.id=p.interviewer_employee_id WHERE p.interview_id=? ORDER BY p.line_no",array((int)$r->id));echo '<h3 style="margin-top:0">'.is_h($r->interview_no).' <small>'.is_h($r->applicant_no.' - '.$r->applicant_name).'</small></h3><span class="label label-info">'.is_h($r->interview_type).'</span> <span class="label label-primary">'.is_h($r->interview_status).'</span><hr><div class="row"><div class="col-sm-3"><b>Schedule</b><br>'.is_h($r->schedule_date.' '.substr($r->start_time,0,5).' - '.substr($r->end_time,0,5)).'</div><div class="col-sm-3"><b>Vacancy</b><br>'.is_h($r->vacancy_no.' - '.$r->vacancy_title).'</div><div class="col-sm-3"><b>Primary Interviewer</b><br>'.is_h($r->primary_no?($r->primary_no.' - '.$r->primary_name):'-').'</div><div class="col-sm-3"><b>Score / Recommendation</b><br>'.number_format((float)$r->overall_score,2).' / '.is_h($r->recommendation).'</div></div><hr><h4>Interview Panel</h4><table class="table table-bordered table-condensed"><thead><tr><th>'.hr_h('common_no', 'No').'</th><th>Interviewer</th><th>Role</th><th>'.hr_h('hr_attendance', 'Attendance').'</th><th>'.hr_h('hr_score', 'Score').'</th><th>Feedback</th></tr></thead><tbody>';foreach($pan as $p){echo '<tr><td>'.(int)$p->line_no.'</td><td>'.is_h($p->employee_no.' - '.$p->full_name).'</td><td>'.is_h($p->interviewer_role).'</td><td>'.is_h($p->attendance_status).'</td><td class="text-right">'.number_format((float)$p->score,2).'</td><td>'.is_h($p->feedback).'</td></tr>';}echo '</tbody></table><hr><p><b>Agenda:</b> '.nl2br(is_h($r->agenda?:'-')).'<br><b>Result:</b> '.nl2br(is_h($r->result_notes?:'-')).'</p>';break;
case 'export':$initial=ob_get_level();ob_start();error_reporting(E_ALL & ~E_NOTICE & ~E_WARNING & ~E_DEPRECATED & ~E_USER_DEPRECATED);require_once "../../inc/lib/PHPExcel.php";require_once "../../inc/excel_style_helper.php";PHPExcel_Shared_File::setUseUploadTempDirectory(true);$from=is_g('tgl_awal',date('Y-m-01'));$to=is_g('tgl_akhir',date('Y-m-t'));$rows=is_export_rows($from,$to,is_g('interview_status',''),is_g('interview_type',''),is_g('interview_method',''),is_g('keyword',''));$excel=new PHPExcel();$sheet=$excel->setActiveSheetIndex(0);$sheet->setTitle(erp_export_sheet_title('Interview Schedule'));$heads=array(erp_export_label("No"),erp_export_label("Interview No"),erp_export_label("Applicant"),erp_export_label("Vacancy"),erp_export_label("Round"),erp_export_label("Type"),erp_export_label("Method"),erp_export_label("Status"),erp_export_label("Date"),erp_export_label("Start"),erp_export_label("End"),erp_export_label("Location"),erp_export_label("Primary Interviewer"),erp_export_label("Score"),erp_export_label("Recommendation"),erp_export_label("SAP Ref"),erp_export_label("Updated By"));foreach($heads as $i=>$h)$sheet->setCellValue(PHPExcel_Cell::stringFromColumnIndex($i).'4',$h);$rn=5;$n=1;foreach($rows as $r){$vals=array($n++,$r->interview_no,$r->applicant_no.' - '.$r->applicant_name,$r->vacancy_no.' - '.$r->vacancy_title,$r->interview_round,$r->interview_type,$r->interview_method,$r->interview_status,$r->schedule_date,$r->start_time,$r->end_time,$r->location,$r->primary_no.' - '.$r->primary_name,$r->overall_score,$r->recommendation,$r->sap_reference,$r->updated_by?:$r->created_by);foreach($vals as $i=>$v)$sheet->setCellValue(PHPExcel_Cell::stringFromColumnIndex($i).$rn,$v);$rn++;}erpkb_excel_apply_standard_style($excel,array('sheet'=>$sheet,'title'=>erp_export_title('INTERVIEW SCHEDULE REPORT'),'header_row'=>4,'first_data_row'=>5,'last_data_row'=>max(5,$rn-1),'column_count'=>count($heads),'decimal_columns'=>array('N'),'filters'=>array('Schedule'=>$from.' s/d '.$to),'widths'=>array('B'=>18,'C'=>30,'D'=>30,'I'=>14,'L'=>25,'M'=>30,'P'=>20)));$tmp=erpkb_excel_temp_file('interview_schedule_');PHPExcel_IOFactory::createWriter($excel,'Excel2007')->save($tmp);$size=@filesize($tmp);$sig=@file_get_contents($tmp,false,null,0,2);if(!$size||$sig!=='PK'){@unlink($tmp);while(ob_get_level()>$initial)ob_end_clean();echo erp_t('export_excel_invalid_file','File Excel gagal dibuat dengan benar.');exit;}while(ob_get_level()>$initial)ob_end_clean();header('Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');header('Content-Disposition: attachment; filename="interview_schedule_'.date('Ymd_His').'.xlsx"');header('Content-Length: '.$size);header('Cache-Control: max-age=0');header('Pragma: public');readfile($tmp);@unlink($tmp);exit;
default:is_json('error','Action tidak dikenal.');
}
?>
