<?php
if (session_status() === PHP_SESSION_NONE) session_start();
include "../../inc/config.php";
function mbj_action_h($value) { return htmlspecialchars((string)$value, ENT_QUOTES, 'UTF-8'); }
function mbj_action_num($value, $dec = 2) { return number_format((float)$value, $dec, ',', '.'); }
function mbj_action_input($key, $default = '') { return isset($_REQUEST[$key]) ? trim((string)$_REQUEST[$key]) : $default; }
function mbj_action_rows($db) {
  $tglAwal=mbj_action_input('tgl_awal',date('Y-m-01')); $tglAkhir=mbj_action_input('tgl_akhir',date('Y-m-d'));
  $material=mbj_action_input('material_code'); $plantId=mbj_action_input('plant_id'); $slocId=mbj_action_input('storage_location_id'); $binId=mbj_action_input('storage_bin_id'); $stockType=mbj_action_input('stock_type'); $keyword=mbj_action_input('keyword');
  $where=" WHERE b.kd_kategori IN ('K02','K03') "; $fp=array();
  if($material!==''){$where.=" AND b.kd_barang=? ";$fp[]=$material;} if($plantId!==''){$where.=" AND COALESCE(dt.plant_id,sl.plant_id)=? ";$fp[]=$plantId;} if($slocId!==''){$where.=" AND COALESCE(dt.storage_location_id,dt.destination_storage_location_id,sl.storage_location_id)=? ";$fp[]=$slocId;} if($binId!==''){$where.=" AND COALESCE(dt.storage_bin_id,dt.destination_storage_bin_id,sl.storage_bin_id)=? ";$fp[]=$binId;} if($stockType!==''){$where.=" AND COALESCE(dt.stock_type,dt.destination_stock_type,sl.stock_type,'UNRESTRICTED')=? ";$fp[]=$stockType;}
  if($keyword!==''){$where.=" AND (b.kd_barang LIKE ? OR b.nm_barang LIKE ? OR dt.no_ref LIKE ? OR dt.no_bpb LIKE ? OR dt.no_aju LIKE ? OR dt.no_dokpab LIKE ? OR dt.remark LIKE ?) ";$kw='%'.$keyword.'%';for($i=0;$i<7;$i++)$fp[]=$kw;}
  $movementExpr="CASE WHEN dt.id_detail IS NULL THEN 'IN' WHEN dt.direction='OUT' OR COALESCE(dt.qty,0)<0 OR dt.move_code IN ('102','122','201','221','261','262','551','601','602') THEN 'OUT' ELSE 'IN' END";
  $adjustExpr="CASE WHEN dt.move_code IN ('701','702','711','712') OR COALESCE(dt.ref_type,'') LIKE '%DIFF%' OR COALESCE(dt.ref_type,'') LIKE '%OPNAME%' OR COALESCE(dt.ref_type,'') LIKE '%ADJUST%' THEN 1 ELSE 0 END";
  $giDeliveryExpr="(dt.ref_type='GI_DELIVERY' OR dt.move_code='601')";
  $signedQtyExpr="CASE WHEN ($movementExpr)='OUT' THEN -ABS(COALESCE(dt.qty,0)) ELSE ABS(COALESCE(dt.qty,0)) END";
  $sql="SELECT b.id,b.kd_barang,b.nm_barang,b.satuan,ep.plant_code,es.storage_code,eb.bin_code,COALESCE(dt.stock_type,dt.destination_stock_type,sl.stock_type,'UNRESTRICTED') stock_type,
    COALESCE(SUM(CASE WHEN dt.document_date < ? THEN $signedQtyExpr ELSE 0 END),0) saldo_awal,
    COALESCE(SUM(CASE WHEN dt.document_date BETWEEN ? AND ? AND ($adjustExpr)=0 AND ($movementExpr)='IN' THEN ABS(COALESCE(dt.qty,0)) ELSE 0 END),0) pemasukan,
    COALESCE(SUM(CASE WHEN dt.document_date BETWEEN ? AND ? AND ($adjustExpr)=0 AND ($movementExpr)='OUT' AND $giDeliveryExpr THEN ABS(COALESCE(dt.qty,0)) ELSE 0 END),0) pengeluaran,
    COALESCE(SUM(CASE WHEN dt.document_date BETWEEN ? AND ? AND ($adjustExpr)=1 THEN $signedQtyExpr ELSE 0 END),0) penyesuaian,
    COALESCE(SUM(CASE WHEN dt.document_date <= ? THEN $signedQtyExpr ELSE 0 END),0) saldo_akhir,
    COALESCE(SUM(CASE WHEN dt.document_date BETWEEN ? AND ? THEN 1 ELSE 0 END),0) movement_lines
    FROM barang b
    LEFT JOIN detail_transaksi dt ON dt.kd_barang=b.kd_barang AND dt.document_date<=? AND (dt.posisi='GUDANG' OR dt.lokasi LIKE '%GUDANG%' OR dt.lokasi LIKE '%WAREHOUSE%' OR dt.posisi IS NULL) AND COALESCE(dt.is_reversal,0)=0
    LEFT JOIN stock_layer sl ON sl.id=dt.ref_id AND sl.kode=b.kd_barang
    LEFT JOIN erp_plant ep ON ep.id=COALESCE(dt.plant_id,sl.plant_id)
    LEFT JOIN erp_storage_location es ON es.id=COALESCE(dt.storage_location_id,dt.destination_storage_location_id,sl.storage_location_id)
    LEFT JOIN erp_storage_bin eb ON eb.id=COALESCE(dt.storage_bin_id,dt.destination_storage_bin_id,sl.storage_bin_id)
    $where GROUP BY b.id,b.kd_barang,b.nm_barang,b.satuan,ep.plant_code,es.storage_code,eb.bin_code,stock_type
    HAVING saldo_awal<>0 OR pemasukan<>0 OR pengeluaran<>0 OR penyesuaian<>0 OR saldo_akhir<>0 ORDER BY b.kd_barang ASC";
  $p=array($tglAwal.' 00:00:00',$tglAwal.' 00:00:00',$tglAkhir.' 23:59:59',$tglAwal.' 00:00:00',$tglAkhir.' 23:59:59',$tglAwal.' 00:00:00',$tglAkhir.' 23:59:59',$tglAkhir.' 23:59:59',$tglAwal.' 00:00:00',$tglAkhir.' 23:59:59',$tglAkhir.' 23:59:59');
  return $db->query($sql,array_merge($p,$fp));
}
$act=isset($_GET['act'])?$_GET['act']:'';
switch($act){
  case 'buat_view':
    header('Content-Type: application/json; charset=utf-8'); echo json_encode(array('status'=>'good','message'=>customs_t('finished_goods_mutation_source_message','Mutasi barang jadi dibaca langsung dari detail_transaksi.'))); break;
  case 'show_detail_pemasukan':
    $tglAwal=mbj_action_input('tgl_awal',date('Y-m-01')); $tglAkhir=mbj_action_input('tgl_akhir',date('Y-m-d')); $kd=mbj_action_input('kd_barang'); $type=strtoupper(mbj_action_input('type','IN'));
    if($type==='OUT'){
      $q=$db->query("SELECT gi.gi_no,gi.posting_date,gi.document_date,gi.delivery_no,gi.reference_surat_jalan,gi.customer_code,gi.customer_name,gi.outbound_bc_type,gi.outbound_bc_purpose_code,gi.outbound_bc_purpose,gi.outbound_no_aju,gi.outbound_tgl_aju,gi.outbound_no_daftar,gi.outbound_tgl_daftar,gi.outbound_customs_office,gi.outbound_destination_country,gi.outbound_customs_remarks,d.id detail_id,d.line_no,d.material_code,d.material_name,d.qty,d.uom,d.price,d.amount,d.stock_type,d.remarks,t.stock_layer_id,t.no_bpb,t.no_aju source_no_aju,t.no_dokpab source_no_dokpab,t.jenis_dokpab source_jenis_dokpab,t.lot_no,t.qty trace_qty,t.amount trace_amount,ep.plant_code,es.storage_code,eb.bin_code FROM erp_goods_issue_delivery gi JOIN erp_goods_issue_delivery_detail d ON d.gi_id=gi.id LEFT JOIN erp_goods_issue_delivery_trace t ON t.gi_detail_id=d.id LEFT JOIN erp_plant ep ON ep.id=t.plant_id LEFT JOIN erp_storage_location es ON es.id=t.storage_location_id LEFT JOIN erp_storage_bin eb ON eb.id=t.storage_bin_id WHERE gi.status='POSTED' AND gi.posting_date BETWEEN ? AND ? AND d.material_code=? ORDER BY gi.posting_date ASC,gi.gi_no ASC,d.line_no ASC,t.id ASC",array($tglAwal,$tglAkhir,$kd));
      ?>
      <style>.mbj-detail-table th,.mbj-detail-table td{font-size:12px;vertical-align:middle!important}.mbj-detail-table th{background:#f8fafc}.mbj-detail-head{background:#f8fafc;border:1px solid #e5e7eb;border-radius:12px;padding:12px;margin-bottom:12px}.mbj-detail-muted{color:#64748b;font-size:11px}.mbj-qty-link{font-weight:700;text-decoration:underline;cursor:pointer}.mbj-customs-expanded{display:none;background:#f8fafc}.mbj-customs-box{border:1px solid #e5e7eb;border-radius:10px;background:#fff;padding:10px;margin:4px 0}.mbj-customs-box h5{font-size:12px;font-weight:700;margin:0 0 8px;color:#334155}.mbj-customs-line{display:flex;border-bottom:1px dashed #e5e7eb;padding:4px 0}.mbj-customs-line:last-child{border-bottom:0}.mbj-customs-label{width:145px;color:#64748b;flex:0 0 145px}.mbj-customs-value{font-weight:600;color:#0f172a;word-break:break-word}</style>
      <div class="mbj-detail-head"><h4 style="margin:0"><?=customs_h('gi_delivery_outgoing_detail','Detail Pengeluaran GI for Delivery');?> - <?=mbj_action_h($kd);?></h4><small>Periode <?=mbj_action_h($tglAwal);?> s/d <?=mbj_action_h($tglAkhir);?>. <?=customs_h('gi_delivery_trace_desc','Detail ini mengambil data dari Goods Issue for Delivery dan trace layer/dokumen BC asal.');?></small></div>
      <div class="table-responsive"><table class="table table-bordered table-condensed mbj-detail-table"><thead><tr><th><?=customs_h('no','No');?></th><th><?=customs_h('gi_date','GI / Tanggal');?></th><th><?=customs_h('customer','Customer');?></th><th><?=customs_h('delivery_delivery_note','Delivery / Surat Jalan');?></th><th><?=customs_h('outbound_customs_document','Dokumen Pabean Keluar');?></th><th><?=customs_h('purpose','Tujuan');?></th><th><?=customs_h('material','Material');?></th><th class="text-right"><?=customs_h('qty','Qty');?></th><th class="text-right"><?=customs_h('amount','Nilai');?></th><th><?=customs_h('origin_trace','Trace Asal');?></th><th><?=customs_h('location','Lokasi');?></th><th><?=customs_h('remarks','Keterangan');?></th></tr></thead><tbody>
      <?php $no=1;$totalQty=0;$totalAmount=0;foreach($q as $k){$rowNo=$no++;$qty=(float)($k->trace_qty!==null?$k->trace_qty:$k->qty);$amount=(float)($k->trace_amount!==null?$k->trace_amount:$k->amount);$totalQty+=$qty;$totalAmount+=$amount;$bcKeluar=trim((string)$k->outbound_bc_type.' / AJU '.(string)$k->outbound_no_aju.' / Daftar '.(string)$k->outbound_no_daftar,' /');$bcTanggal=array();if($k->outbound_tgl_aju)$bcTanggal[]='Tgl AJU '.$k->outbound_tgl_aju;if($k->outbound_tgl_daftar)$bcTanggal[]='Tgl Daftar '.$k->outbound_tgl_daftar;$trace=trim((string)$k->source_jenis_dokpab.' / '.(string)$k->source_no_dokpab.' / '.(string)$k->source_no_aju,' /');$loc=trim((string)$k->plant_code.' / '.(string)$k->storage_code.' / '.(string)$k->bin_code,' /');$tujuan=trim((string)$k->outbound_bc_purpose_code.' - '.(string)$k->outbound_bc_purpose,' -'); ?>
        <tr><td><?=intval($rowNo);?></td><td><strong><?=mbj_action_h($k->gi_no);?></strong><br><small class="mbj-detail-muted"><?=mbj_action_h($k->posting_date ?: $k->document_date);?></small></td><td><strong><?=mbj_action_h($k->customer_name ?: $k->customer_code);?></strong><br><small class="mbj-detail-muted"><?=mbj_action_h($k->customer_code);?></small></td><td><?=mbj_action_h($k->delivery_no ?: '-');?><br><small class="mbj-detail-muted"><?=mbj_action_h($k->reference_surat_jalan ?: 'Surat jalan belum terisi');?></small></td><td><strong><?=mbj_action_h($bcKeluar ?: '-');?></strong><br><small class="mbj-detail-muted"><?=mbj_action_h(implode(' | ',$bcTanggal));?></small></td><td><?=mbj_action_h($tujuan ?: '-');?><br><small class="mbj-detail-muted"><?=mbj_action_h($k->outbound_customs_office ?: $k->outbound_destination_country);?></small></td><td><strong><?=mbj_action_h($k->material_code);?></strong><br><small class="mbj-detail-muted"><?=mbj_action_h($k->material_name);?></small></td><td class="text-right"><a href="javascript:void(0)" class="mbj-qty-link" onclick="$(this).closest('tr').next('.mbj-customs-expanded').toggle();return false;"><?=mbj_action_num($qty);?></a><br><small class="mbj-detail-muted"><?=mbj_action_h($k->uom);?> | klik detail</small></td><td class="text-right"><?=mbj_action_num($amount);?><br><small class="mbj-detail-muted">@<?=mbj_action_num($k->price);?></small></td><td><?=mbj_action_h($trace ?: '-');?><br><small class="mbj-detail-muted">Layer #<?=mbj_action_h($k->stock_layer_id ?: '-');?><?=($k->lot_no?' | Lot '.$k->lot_no:'');?></small></td><td><?=mbj_action_h($loc ?: '-');?><br><small class="mbj-detail-muted"><?=mbj_action_h($k->stock_type ?: 'UNRESTRICTED');?></small></td><td><?=mbj_action_h(trim((string)$k->remarks.' '.(string)$k->outbound_customs_remarks));?></td></tr>
        <tr class="mbj-customs-expanded"><td colspan="12">
          <div class="mbj-customs-box">
            <h5><?=customs_h('finished_goods_raw_detail','Detail Bahan Baku Asal Barang Jadi');?></h5>
            <div class="mbj-detail-muted" style="margin-bottom:8px"><?=customs_h('finished_goods_raw_trace_desc','Barang jadi keluar dari layer');?> #<?=mbj_action_h($k->stock_layer_id ?: '-');?>. <?=customs_h('finished_goods_raw_trace_qty_desc','Qty bahan baku dihitung proporsional terhadap Qty barang jadi yang dikeluarkan.');?></div>
            <div class="table-responsive"><table class="table table-bordered table-condensed" style="margin-bottom:0"><thead><tr class="bg-gray"><th><?=customs_h('no','No');?></th><th><?=customs_h('source_raw_material','Bahan Baku Asal');?></th><th class="text-right"><?=customs_h('qty','Jumlah');?></th><th>UOM</th><th><?=customs_h('inbound_bc_document','Dokumen BC Masuk');?></th><th><?=customs_h('aju_no_short','No AJU');?></th><th><?=customs_h('bpb_no','No BPB');?></th><th><?=customs_h('lot_batch','Lot/Batch');?></th><th><?=customs_h('hs_code','HS Code');?></th><th><?=customs_h('trace','Trace');?></th></tr></thead><tbody>
            <?php
              $rawRows=$db->query("SELECT gt.*,sl.qty_masuk AS output_layer_qty FROM erp_gr_production_trace gt LEFT JOIN stock_layer sl ON sl.id=gt.output_stock_layer_id WHERE gt.output_stock_layer_id=? ORDER BY gt.raw_material_code,gt.no_aju,gt.no_dokpab,gt.id",array($k->stock_layer_id));
              $rawNo=1;$rawTotal=0;$hasRaw=false;
              if($rawRows) foreach($rawRows as $raw){$hasRaw=true;$ratio=((float)$raw->output_layer_qty>0)?($qty/(float)$raw->output_layer_qty):1;$rawQty=(float)$raw->qty*$ratio;$rawTotal+=$rawQty;$rawTrace=$raw->trace_source==='INHERITED'?'INHERITED':'DIRECT';
            ?>
              <tr><td><?=intval($rawNo++);?></td><td><strong><?=mbj_action_h($raw->raw_material_code ?: $raw->source_material_code);?></strong><br><small class="mbj-detail-muted"><?=mbj_action_h($raw->raw_material_name ?: $raw->source_material_name);?></small></td><td class="text-right"><?=mbj_action_num($rawQty,5);?></td><td><?=mbj_action_h($raw->uom ?: '-');?></td><td><?=mbj_action_h(trim((string)$raw->jenis_dokpab.' '.(string)$raw->no_dokpab) ?: '-');?></td><td><?=mbj_action_h($raw->no_aju ?: '-');?></td><td><?=mbj_action_h($raw->no_bpb ?: '-');?></td><td><?=mbj_action_h($raw->lot_no ?: '-');?></td><td><?=mbj_action_h($raw->hs_code ?: '-');?></td><td><span class="label label-<?=($rawTrace==='INHERITED'?'primary':'info');?>"><?=mbj_action_h($rawTrace);?></span><br><small class="mbj-detail-muted">Source layer #<?=mbj_action_h($raw->source_stock_layer_id ?: '-');?></small></td></tr>
            <?php } if(!$hasRaw){ ?>
              <tr><td colspan="10" class="text-center text-muted"><?=customs_h('raw_trace_not_available_fg_layer','Trace bahan baku belum tersedia untuk stock layer barang jadi ini.');?></td></tr>
            <?php } ?>
            </tbody><?php if($hasRaw){ ?><tfoot><tr><th colspan="2" class="text-right">Total bahan baku proporsional</th><th class="text-right"><?=mbj_action_num($rawTotal,5);?></th><th colspan="7"></th></tr></tfoot><?php } ?></table></div>
          </div>
        </td></tr>
      <?php } if($no===1){ ?><tr><td colspan="12" class="text-center text-muted">Tidak ada Goods Issue for Delivery untuk material dan periode ini.</td></tr><?php } ?>
      </tbody><tfoot><tr><th colspan="7" class="text-right">Total</th><th class="text-right"><?=mbj_action_num($totalQty);?></th><th class="text-right"><?=mbj_action_num($totalAmount);?></th><th colspan="3"></th></tr></tfoot></table></div>
      <?php
      break;
    }
    $movementExpr="CASE WHEN dt.direction='OUT' OR COALESCE(dt.qty,0)<0 OR dt.move_code IN ('102','122','201','221','261','262','551','601','602') THEN 'OUT' ELSE 'IN' END";
    $adjustExpr="CASE WHEN dt.move_code IN ('701','702','711','712') OR COALESCE(dt.ref_type,'') LIKE '%DIFF%' OR COALESCE(dt.ref_type,'') LIKE '%OPNAME%' OR COALESCE(dt.ref_type,'') LIKE '%ADJUST%' THEN 1 ELSE 0 END";
    $where=" WHERE dt.document_date BETWEEN ? AND ? AND dt.kd_barang=? AND (dt.posisi='GUDANG' OR dt.lokasi LIKE '%GUDANG%' OR dt.lokasi LIKE '%WAREHOUSE%' OR dt.posisi IS NULL) AND COALESCE(dt.is_reversal,0)=0 "; $p=array($tglAwal.' 00:00:00',$tglAkhir.' 23:59:59',$kd);
    if($type==='ADJ'){$where.=" AND ($adjustExpr)=1 ";$title='Detail Penyesuaian';}elseif($type==='OUT'){$where.=" AND ($adjustExpr)=0 AND ($movementExpr)='OUT' ";$title='Detail Pengeluaran';}else{$where.=" AND ($adjustExpr)=0 AND ($movementExpr)='IN' ";$title='Detail Pemasukan';}
    $q=$db->query("SELECT dt.*,b.nm_barang,b.satuan,ep.plant_code,es.storage_code,eb.bin_code,p.jenis_dokpab header_jenis_dokpab,p.tgl_dokpab,gd.stock_layer_id output_stock_layer_id,gd.qty output_layer_qty,sl.no_bpb layer_no_bpb,sl.jenis_dokpab layer_jenis_dokpab,sl.no_aju layer_no_aju,sl.no_dokpab layer_no_dokpab,sl.qty_masuk layer_qty_masuk,sl.qty_sisa layer_qty_sisa FROM detail_transaksi dt LEFT JOIN barang b ON b.kd_barang=dt.kd_barang LEFT JOIN erp_plant ep ON ep.id=dt.plant_id LEFT JOIN erp_storage_location es ON es.id=COALESCE(dt.storage_location_id,dt.destination_storage_location_id) LEFT JOIN erp_storage_bin eb ON eb.id=COALESCE(dt.storage_bin_id,dt.destination_storage_bin_id) LEFT JOIN erp_gr_production_detail gd ON gd.material_doc_id=dt.id_detail LEFT JOIN stock_layer sl ON sl.id=gd.stock_layer_id LEFT JOIN pemasukan p ON p.no_bpb=COALESCE(NULLIF(dt.no_bpb,''),NULLIF(dt.no_ref,''),NULLIF(dt.ref_pengganti,'')) OR p.no_aju=dt.no_aju $where ORDER BY dt.posting_date ASC,dt.id_detail ASC",$p);
    ?>
    <style>.mbj-detail-table th,.mbj-detail-table td{font-size:12px;vertical-align:middle!important}.mbj-detail-table th{background:#f8fafc}.mbj-detail-head{background:#f8fafc;border:1px solid #e5e7eb;border-radius:12px;padding:12px;margin-bottom:12px}.mbj-detail-muted{color:#64748b;font-size:11px}.mbj-qty-link{font-weight:700;text-decoration:underline;cursor:pointer}.mbj-customs-expanded{display:none;background:#f8fafc}.mbj-trace-box{border:1px solid #e5e7eb;background:#fff;border-radius:10px;padding:10px;margin:4px 0}.mbj-trace-box h5{font-size:12px;font-weight:700;margin:0 0 8px;color:#334155}</style>
    <div class="mbj-detail-head"><h4 style="margin:0"><?=mbj_action_h($title);?> - <?=mbj_action_h($kd);?></h4><small>Periode <?=mbj_action_h($tglAwal);?> s/d <?=mbj_action_h($tglAkhir);?></small></div>
    <div class="table-responsive"><table class="table table-bordered table-condensed mbj-detail-table"><thead><tr><th><?=customs_h('no','No');?></th><th>Material Document</th><th>Posting Date</th><th>Movement</th><th><?=customs_h('material','Material');?></th><th>Location</th><th>Customs</th><th class="text-right"><?=customs_h('qty','Qty');?></th><th>UOM</th><th><?=customs_h('remarks','Keterangan');?></th></tr></thead><tbody>
    <?php $no=1;$total=0;foreach($q as $k){$mv=($k->direction==='OUT'||(float)$k->qty<0||in_array($k->move_code,array('102','122','201','221','261','262','551','601','602')))?'OUT':'IN';$qty=abs((float)$k->qty);$total+=$qty;$loc=trim((string)$k->plant_code.' / '.(string)$k->storage_code.' / '.(string)$k->bin_code,' /');$customs=trim((string)($k->header_jenis_dokpab?:'').' '.(string)$k->no_dokpab.' / '.(string)$k->no_aju,' /'); ?>
      <tr><td><?=intval($no++);?></td><td><strong><?=mbj_action_h($k->no_ref ?: $k->no_bpb);?></strong><br><small>#<?=intval($k->id_detail);?><?=($k->output_stock_layer_id?' | Layer #'.intval($k->output_stock_layer_id):'');?></small></td><td><?=mbj_action_h($k->posting_date ?: $k->document_date);?></td><td><span class="label label-<?=$mv==='OUT'?'danger':'success';?>"><?=mbj_action_h($mv);?></span><br><small><?=mbj_action_h($k->move_code.' '.$k->ref_type);?></small></td><td><strong><?=mbj_action_h($k->kd_barang);?></strong><br><small><?=mbj_action_h($k->nm_barang);?></small></td><td><?=mbj_action_h($loc ?: ($k->lokasi ?: '-'));?><br><small><?=mbj_action_h($k->stock_type ?: 'UNRESTRICTED');?></small></td><td><?=mbj_action_h($customs ?: trim((string)$k->layer_jenis_dokpab.' '.(string)$k->layer_no_dokpab.' / '.(string)$k->layer_no_aju,' /') ?: '-');?><br><small><?=mbj_action_h($k->no_bpb ?: $k->layer_no_bpb ?: '');?></small></td><td class="text-right"><a href="javascript:void(0)" class="mbj-qty-link" onclick="$(this).closest('tr').next('.mbj-customs-expanded').toggle();return false;"><?=mbj_action_num($qty);?></a><br><small class="mbj-detail-muted">klik detail BC</small></td><td><?=mbj_action_h($k->uom ?: $k->satuan);?></td><td><?=mbj_action_h(trim((string)$k->remark.' '.(string)$k->reason));?></td></tr>
      <tr class="mbj-customs-expanded"><td colspan="10">
        <div class="mbj-trace-box">
          <h5><?=customs_h('raw_bc_detail_fg_layer','Detail Dokumen BC Asal Bahan Baku / Layer Barang Jadi');?></h5>
          <div class="mbj-detail-muted" style="margin-bottom:8px"><?=customs_h('finished_goods_inherit_trace_desc','Pemasukan barang jadi ini membentuk layer');?> #<?=mbj_action_h($k->output_stock_layer_id ?: '-');?>. <?=customs_h('finished_goods_inherit_trace_detail_desc','Jika hasil produksi, tabel di bawah menampilkan bahan baku asal dan dokumen BC masuk yang diwariskan ke barang jadi.');?></div>
          <div class="table-responsive"><table class="table table-bordered table-condensed" style="margin-bottom:0"><thead><tr class="bg-gray"><th><?=customs_h('no','No');?></th><th><?=customs_h('source_raw_material','Bahan Baku Asal');?></th><th class="text-right"><?=customs_h('qty','Jumlah');?></th><th>UOM</th><th><?=customs_h('inbound_bc_document','Dokumen BC Masuk');?></th><th><?=customs_h('aju_no_short','No AJU');?></th><th><?=customs_h('bpb_no','No BPB');?></th><th><?=customs_h('lot_batch','Lot/Batch');?></th><th><?=customs_h('hs_code','HS Code');?></th><th><?=customs_h('trace','Trace');?></th></tr></thead><tbody>
          <?php
            $rawNo=1;$rawTotal=0;$hasRaw=false;
            if($k->output_stock_layer_id){
              $rawRows=$db->query("SELECT * FROM erp_gr_production_trace WHERE output_stock_layer_id=? ORDER BY raw_material_code,no_aju,no_dokpab,id",array($k->output_stock_layer_id));
              if($rawRows) foreach($rawRows as $raw){$hasRaw=true;$rawQty=(float)$raw->qty;$rawTotal+=$rawQty;$rawTrace=$raw->trace_source==='INHERITED'?'INHERITED':'DIRECT';
          ?>
            <tr><td><?=intval($rawNo++);?></td><td><strong><?=mbj_action_h($raw->raw_material_code ?: $raw->source_material_code);?></strong><br><small class="mbj-detail-muted"><?=mbj_action_h($raw->raw_material_name ?: $raw->source_material_name);?></small></td><td class="text-right"><?=mbj_action_num($rawQty,5);?></td><td><?=mbj_action_h($raw->uom ?: '-');?></td><td><?=mbj_action_h(trim((string)$raw->jenis_dokpab.' '.(string)$raw->no_dokpab) ?: '-');?></td><td><?=mbj_action_h($raw->no_aju ?: '-');?></td><td><?=mbj_action_h($raw->no_bpb ?: '-');?></td><td><?=mbj_action_h($raw->lot_no ?: '-');?></td><td><?=mbj_action_h($raw->hs_code ?: '-');?></td><td><span class="label label-<?=($rawTrace==='INHERITED'?'primary':'info');?>"><?=mbj_action_h($rawTrace);?></span><br><small class="mbj-detail-muted">Source layer #<?=mbj_action_h($raw->source_stock_layer_id ?: '-');?></small></td></tr>
          <?php }} if(!$hasRaw){ ?>
            <tr><td colspan="10" class="text-center text-muted"><?=customs_h('bc_trace_not_available_transaction','Detail trace dokumen BC belum tersedia untuk transaksi ini. Untuk transaksi non-produksi, referensi dokumen ada di baris utama.');?></td></tr>
          <?php } ?>
          </tbody><?php if($hasRaw){ ?><tfoot><tr><th colspan="2" class="text-right">Total bahan baku trace</th><th class="text-right"><?=mbj_action_num($rawTotal,5);?></th><th colspan="7"></th></tr></tfoot><?php } ?></table></div>
        </div>
      </td></tr>
    <?php } if($no===1){ ?><tr><td colspan="10" class="text-center text-muted">Tidak ada detail transaksi.</td></tr><?php } ?>
    </tbody><tfoot><tr><th colspan="7" class="text-right">Total</th><th class="text-right"><?=mbj_action_num($total);?></th><th colspan="2"></th></tr></tfoot></table></div>
    <?php break;
  case 'excel':
    $initialOutputBufferLevel=ob_get_level(); ob_start(); ini_set('display_errors','0'); error_reporting(E_ALL & ~E_NOTICE & ~E_WARNING & ~E_DEPRECATED & ~E_USER_DEPRECATED);
    require "../../inc/lib/PHPExcel.php"; require_once "../../inc/excel_style_helper.php"; PHPExcel_Shared_File::setUseUploadTempDirectory(true);
    $tglAwal=mbj_action_input('tgl_awal',date('Y-m-01')); $tglAkhir=mbj_action_input('tgl_akhir',date('Y-m-d')); $companyName=defined('namaPT')?namaPT:(defined('shortTittle')?shortTittle:'NAMA_PT'); $rows=mbj_action_rows($db);
    $excel=new PHPExcel(); $sheet=$excel->setActiveSheetIndex(0); $sheet->setTitle(erp_export_sheet_title('Mutasi BJ')); $headerStart=6; $headerEnd=7; $firstDataRow=8; $lastCol='L';
    foreach(array(1=>'LAPORAN PERTANGGUNGJAWABAN MUTASI BARANG',2=>'LAPORAN PERTANGGUNGJAWABAN MUTASI BARANG JADI',3=>'KAWASAN BERIKAT '.$companyName,4=>'PERIODE: '.$tglAwal.' SD '.$tglAkhir) as $row=>$text){$sheet->mergeCells('A'.$row.':L'.$row);$sheet->setCellValue('A'.$row,$text);}
    $headers=array(erp_export_label("No"),erp_export_label("KODE\\nBARANG"),erp_export_label("NAMA\\nBARANG"),erp_export_label("SAT"),erp_export_label("SALDO\\nAWAL\\n....(7)...."),erp_export_label("PEMASUKAN"),erp_export_label("PENGELUARAN"),erp_export_label("PENYESUAIAN\\n(ADJUSTMENT)"),erp_export_label("SALDO\\nAKHIR\\n....(12)...."),erp_export_label("STOCK\\nOPNAME\\n....(14)...."),erp_export_label("SELISIH"),erp_export_label("KETERANGAN")); $numbers=array('(3)','(4)','(5)','(6)','(8)','(9)','(10)','(11)','(13)','(15)','(16)','(17)');
    foreach($headers as $c=>$h)$sheet->setCellValueByColumnAndRow($c,$headerStart,$h); foreach($numbers as $c=>$h)$sheet->setCellValueByColumnAndRow($c,$headerEnd,$h);
    $r=$firstDataRow;$n=1;$tot=array_fill_keys(array('saldo_awal','pemasukan','pengeluaran','penyesuaian','saldo_akhir','stock_opname','selisih'),0);
    foreach($rows as $row){$saldo=(float)$row->saldo_akhir;$op=$saldo;$sel=$op-$saldo;$ket=array();if((int)$row->movement_lines>0)$ket[]=(int)$row->movement_lines.' line transaksi';if($row->plant_code||$row->storage_code||$row->bin_code)$ket[]=trim((string)$row->plant_code.' / '.(string)$row->storage_code.' / '.(string)$row->bin_code,' /');if($row->stock_type)$ket[]=$row->stock_type;$vals=array($n++,$row->kd_barang,$row->nm_barang,$row->satuan,(float)$row->saldo_awal,(float)$row->pemasukan,(float)$row->pengeluaran,(float)$row->penyesuaian,$saldo,$op,$sel,implode(' | ',$ket));foreach($vals as $c=>$v)$sheet->setCellValueByColumnAndRow($c,$r,$v);$tot['saldo_awal']+=(float)$row->saldo_awal;$tot['pemasukan']+=(float)$row->pemasukan;$tot['pengeluaran']+=(float)$row->pengeluaran;$tot['penyesuaian']+=(float)$row->penyesuaian;$tot['saldo_akhir']+=$saldo;$tot['stock_opname']+=$op;$tot['selisih']+=$sel;$r++;}
    $lastDataRow=max($firstDataRow,$r-1);$summaryRow=$r+1;$sheet->mergeCells('A'.$summaryRow.':D'.$summaryRow);$sheet->setCellValue('A'.$summaryRow, erp_export_label('TOTAL'));$sheet->setCellValue('E'.$summaryRow,$tot['saldo_awal']);$sheet->setCellValue('F'.$summaryRow,$tot['pemasukan']);$sheet->setCellValue('G'.$summaryRow,$tot['pengeluaran']);$sheet->setCellValue('H'.$summaryRow,$tot['penyesuaian']);$sheet->setCellValue('I'.$summaryRow,$tot['saldo_akhir']);$sheet->setCellValue('J'.$summaryRow,$tot['stock_opname']);$sheet->setCellValue('K'.$summaryRow,$tot['selisih']);
    $sheet->getStyle('A1:L4')->getFont()->setBold(true)->setSize(12);$sheet->getStyle('A1:L4')->getAlignment()->setHorizontal(PHPExcel_Style_Alignment::HORIZONTAL_CENTER);$sheet->getStyle('A'.$headerStart.':L'.$headerEnd)->getFont()->setBold(true);$sheet->getStyle('A'.$headerStart.':L'.$headerEnd)->getAlignment()->setHorizontal(PHPExcel_Style_Alignment::HORIZONTAL_CENTER)->setVertical(PHPExcel_Style_Alignment::VERTICAL_CENTER)->setWrapText(true);$sheet->getStyle('A'.$headerStart.':L'.$headerStart)->getFill()->setFillType(PHPExcel_Style_Fill::FILL_SOLID)->getStartColor()->setRGB('FFF7ED');$sheet->getStyle('A'.$headerEnd.':L'.$headerEnd)->getFill()->setFillType(PHPExcel_Style_Fill::FILL_SOLID)->getStartColor()->setRGB('FFFFFF');$sheet->getStyle('A'.$headerStart.':L'.$lastDataRow)->getBorders()->getAllBorders()->setBorderStyle(PHPExcel_Style_Border::BORDER_THIN)->getColor()->setRGB('CBD5E1');$sheet->getStyle('A'.$firstDataRow.':L'.$lastDataRow)->getAlignment()->setVertical(PHPExcel_Style_Alignment::VERTICAL_TOP)->setWrapText(true);$sheet->getStyle('A'.$firstDataRow.':A'.$lastDataRow)->getAlignment()->setHorizontal(PHPExcel_Style_Alignment::HORIZONTAL_CENTER);$sheet->getStyle('E'.$firstDataRow.':K'.$summaryRow)->getNumberFormat()->setFormatCode('#,##0.00');$sheet->getStyle('E'.$firstDataRow.':K'.$summaryRow)->getAlignment()->setHorizontal(PHPExcel_Style_Alignment::HORIZONTAL_RIGHT);$sheet->getStyle('A'.$summaryRow.':L'.$summaryRow)->getFont()->setBold(true);$sheet->getStyle('A'.$summaryRow.':L'.$summaryRow)->getFill()->setFillType(PHPExcel_Style_Fill::FILL_SOLID)->getStartColor()->setRGB('ECFDF5');$sheet->getStyle('A'.$summaryRow.':L'.$summaryRow)->getBorders()->getAllBorders()->setBorderStyle(PHPExcel_Style_Border::BORDER_THIN)->getColor()->setRGB('CBD5E1');
    foreach(array('A'=>6,'B'=>14,'C'=>30,'D'=>8,'E'=>13,'F'=>14,'G'=>15,'H'=>18,'I'=>13,'J'=>14,'K'=>12,'L'=>34) as $col=>$w)$sheet->getColumnDimension($col)->setWidth($w);$sheet->getRowDimension($headerStart)->setRowHeight(42);$sheet->getRowDimension($headerEnd)->setRowHeight(22);$sheet->freezePane('A'.$firstDataRow);$sheet->setAutoFilter('A'.$headerEnd.':L'.$lastDataRow);$sheet->getPageSetup()->setOrientation(PHPExcel_Worksheet_PageSetup::ORIENTATION_LANDSCAPE);$sheet->getPageSetup()->setFitToWidth(1);$sheet->getPageSetup()->setFitToHeight(0);
    $tmp=erpkb_excel_temp_file('mutasi_barang_jadi_');PHPExcel_IOFactory::createWriter($excel,'Excel2007')->save($tmp);$size=@filesize($tmp);$sig=@file_get_contents($tmp,false,null,0,2);if(!$size||$sig!=='PK'){@unlink($tmp);while(ob_get_level()>$initialOutputBufferLevel)ob_end_clean();header('Content-Type:text/plain; charset=utf-8');echo erp_t('export_excel_invalid_file','File Excel gagal dibuat dengan benar.');exit;}while(ob_get_level()>$initialOutputBufferLevel)ob_end_clean();header('Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');header('Content-Disposition: attachment; filename="laporan_mutasi_barang_jadi_'.$tglAwal.'_sd_'.$tglAkhir.'.xlsx"');header('Content-Length: '.$size);header('Cache-Control: max-age=0');header('Pragma: public');readfile($tmp);@unlink($tmp);exit;
  default:
    header('Content-Type: application/json; charset=utf-8'); echo json_encode(array('status'=>'error','error_message'=>'Action tidak dikenal.'));
}
?>
