<?php
$defaultFrom = isset($tgl_awal) && $tgl_awal ? $tgl_awal : date('Y-m-01');
$defaultTo = isset($tgl_akhir) && $tgl_akhir ? $tgl_akhir : date('Y-m-d');
$materials = iterator_to_array($db->query("SELECT kd_barang,nm_barang,satuan FROM barang WHERE kd_kategori IN ('K02','K03') AND COALESCE(status,1)=1 ORDER BY kd_barang LIMIT 500"));
$plants = iterator_to_array($db->query("SELECT id,plant_code,plant_name FROM erp_plant WHERE status='Aktif' ORDER BY plant_code"));
$storageLocations = iterator_to_array($db->query("SELECT s.id,s.plant_id,s.storage_code,s.storage_name,p.plant_code FROM erp_storage_location s LEFT JOIN erp_plant p ON p.id=s.plant_id WHERE s.status='Aktif' ORDER BY p.plant_code,s.storage_code"));
$storageBins = iterator_to_array($db->query("SELECT b.id,b.storage_location_id,b.bin_code,b.bin_name,s.storage_code FROM erp_storage_bin b LEFT JOIN erp_storage_location s ON s.id=b.storage_location_id WHERE b.status='Aktif' ORDER BY s.storage_code,b.bin_code"));
$summary = $db->fetch("SELECT
  (SELECT COUNT(*) FROM barang WHERE kd_kategori IN ('K02','K03')) material_count,
  (SELECT COALESCE(SUM(sl.qty_sisa),0) FROM stock_layer sl JOIN barang b ON b.kd_barang=sl.kode WHERE b.kd_kategori IN ('K02','K03') AND sl.qty_sisa>0) current_stock,
  (SELECT COUNT(DISTINCT dt.no_ref) FROM detail_transaksi dt JOIN barang b ON b.kd_barang=dt.kd_barang WHERE b.kd_kategori IN ('K02','K03') AND dt.document_date BETWEEN ? AND ?) movement_docs,
  (SELECT COALESCE(SUM(ABS(dt.qty)),0) FROM detail_transaksi dt JOIN barang b ON b.kd_barang=dt.kd_barang WHERE b.kd_kategori IN ('K02','K03') AND dt.document_date BETWEEN ? AND ? AND (dt.direction='OUT' OR dt.qty<0 OR dt.move_code IN ('102','122','201','221','261','262','551','601','602'))) qty_out", array($defaultFrom.' 00:00:00',$defaultTo.' 23:59:59',$defaultFrom.' 00:00:00',$defaultTo.' 23:59:59'));
function mbj_view_h($value) { return htmlspecialchars((string)$value, ENT_QUOTES, 'UTF-8'); }
?>
<style>
.mbj-hero{background:linear-gradient(135deg,#0f766e,#334155);color:#fff;border-radius:14px;padding:20px 22px;margin-bottom:18px;box-shadow:0 10px 24px rgba(15,23,42,.18)}
.mbj-hero h1{margin:0 0 6px;font-size:26px;font-weight:700}.mbj-hero p{margin:0;opacity:.92}
.mbj-kpi{border-radius:12px;background:#fff;border:1px solid #e5edf5;padding:15px;margin-bottom:14px;box-shadow:0 4px 14px rgba(15,23,42,.05)}
.mbj-kpi span{display:block;color:#64748b;font-size:12px;text-transform:uppercase;letter-spacing:.04em}.mbj-kpi strong{display:block;font-size:23px;margin-top:6px;color:#111827}
.mbj-kpi i{float:right;font-size:26px;color:#0f766e;opacity:.55}.mbj-filter .form-group{margin-bottom:12px}.select2-container{width:100%!important}
#dtb_mutasi_barang_jadi th,#dtb_mutasi_barang_jadi td{font-size:12px;vertical-align:middle!important}
#dtb_mutasi_barang_jadi thead th{background:#f8fafc;color:#1f2937;text-align:center;border-color:#d8e2ec!important}
#dtb_mutasi_barang_jadi thead tr:first-child th{background:#fff7ed!important;font-weight:700}
#dtb_mutasi_barang_jadi thead tr:nth-child(2) th{background:#fff!important;color:#475569;font-weight:600}
.mbj-official-title{text-align:center;margin:10px 0 55px;color:#111827;font-family:"Times New Roman",serif;line-height:1.25}
.mbj-official-title h3{margin:0;font-size:16px;font-weight:800;text-transform:uppercase}.mbj-official-title .subtitle{font-size:16px;font-weight:800;text-transform:uppercase}
.mbj-table-wrap{border:1px solid #d8e2ec;border-radius:10px;overflow:hidden;background:#fff}
.mbj-number{text-align:right}.mbj-center{text-align:center}.mbj-detail-link{font-weight:700;text-decoration:underline;color:#0f766e}.mbj-help{font-size:12px;color:#64748b;margin-top:5px}
</style>
<section class="content-header">
  <h1><?=customs_h('mutation_finished_goods','Mutasi Barang Jadi');?> <small><?=customs_h('stock_movement','Customs Stock Movement');?></small></h1>
  <ol class="breadcrumb"><li><a href="<?=base_index();?>"><i class="fa fa-dashboard"></i> <?=customs_h('home','Home');?></a></li><li><a href="<?=base_index();?>mutasi-barang-jadi"><?=customs_h('report','Customs Report');?></a></li><li class="active"><?=customs_h('mutation_finished_goods','Mutasi Barang Jadi');?></li></ol>
</section>
<section class="content">
  <div class="mbj-hero"><div class="row"><div class="col-md-8"><h1><?=customs_h('mutation_finished_goods','Mutasi Barang Jadi');?></h1><p>Ringkasan saldo awal, pemasukan, pengeluaran, penyesuaian, dan saldo akhir barang jadi berdasarkan material document, stock layer, plant, storage location, bin, dan stock type.</p></div><div class="col-md-4 text-right"><span class="label label-primary"><?=customs_h('read_only_report','Read Only Customs Report');?></span></div></div></div>
  <div class="row">
    <div class="col-sm-3"><div class="mbj-kpi"><i class="fa fa-cubes"></i><span>Material BJ</span><strong><?=number_format((float)$summary->material_count,0,',','.');?></strong></div></div>
    <div class="col-sm-3"><div class="mbj-kpi"><i class="fa fa-archive"></i><span><?=customs_h('current_stock','Stock Saat Ini');?></span><strong><?=number_format((float)$summary->current_stock,2,',','.');?></strong></div></div>
    <div class="col-sm-3"><div class="mbj-kpi"><i class="fa fa-file-text-o"></i><span><?=customs_h('movement_documents','Dokumen Mutasi');?></span><strong><?=number_format((float)$summary->movement_docs,0,',','.');?></strong></div></div>
    <div class="col-sm-3"><div class="mbj-kpi"><i class="fa fa-arrow-up"></i><span><?=customs_h('period_outgoing_qty','Qty Keluar Periode');?></span><strong><?=number_format((float)$summary->qty_out,2,',','.');?></strong></div></div>
  </div>
  <div class="box"><div class="box-header with-border"><h3 class="box-title"><i class="fa fa-filter"></i> <?=customs_h('filter_finished_goods_mutation','Filter Mutasi Barang Jadi');?></h3></div><div class="box-body"><form class="form-horizontal mbj-filter" onsubmit="return false;">
    <div class="form-group"><label class="control-label col-lg-2"><?=customs_h('period','Periode');?></label><div class="col-lg-2"><div class="input-group date mbj-date"><input type="text" class="form-control" id="tgl_awal" value="<?=mbj_view_h($defaultFrom);?>" autocomplete="off"><span class="input-group-addon"><span class="glyphicon glyphicon-calendar"></span></span></div></div><div class="col-lg-2"><div class="input-group date mbj-date"><input type="text" class="form-control" id="tgl_akhir" value="<?=mbj_view_h($defaultTo);?>" autocomplete="off"><span class="input-group-addon"><span class="glyphicon glyphicon-calendar"></span></span></div></div><label class="control-label col-lg-1"><?=customs_h('material','Material');?></label><div class="col-lg-5"><select id="filter_material" class="form-control"><option value="">Semua Barang Jadi</option><?php foreach($materials as $m){ ?><option value="<?=mbj_view_h($m->kd_barang);?>"><?=mbj_view_h($m->kd_barang.' - '.$m->nm_barang.' | '.$m->satuan);?></option><?php } ?></select><div class="mbj-help">Kosongkan untuk semua barang jadi.</div></div></div>
    <div class="form-group"><label class="control-label col-lg-2"><?=customs_h('plant','Plant');?></label><div class="col-lg-2"><select id="filter_plant" class="form-control"><option value="">Semua Plant</option><?php foreach($plants as $p){ ?><option value="<?=intval($p->id);?>"><?=mbj_view_h($p->plant_code.' - '.$p->plant_name);?></option><?php } ?></select></div><label class="control-label col-lg-2"><?=customs_h('storage_location','Storage Location');?></label><div class="col-lg-2"><select id="filter_storage_location" class="form-control"><option value="">Semua SLoc</option><?php foreach($storageLocations as $s){ ?><option value="<?=intval($s->id);?>" data-plant-id="<?=intval($s->plant_id);?>"><?=mbj_view_h($s->plant_code.' / '.$s->storage_code.' - '.$s->storage_name);?></option><?php } ?></select></div><label class="control-label col-lg-1"><?=customs_h('storage_bin','Storage Bin');?></label><div class="col-lg-3"><select id="filter_storage_bin" class="form-control"><option value="">Semua Bin</option><?php foreach($storageBins as $b){ ?><option value="<?=intval($b->id);?>" data-storage-location-id="<?=intval($b->storage_location_id);?>"><?=mbj_view_h($b->storage_code.' / '.$b->bin_code.' - '.$b->bin_name);?></option><?php } ?></select></div></div>
    <div class="form-group"><label class="control-label col-lg-2"><?=customs_h('stock_type','Stock Type');?></label><div class="col-lg-2"><select id="filter_stock_type" class="form-control"><option value="">Semua</option><option value="UNRESTRICTED">Unrestricted</option><option value="QUALITY">Quality Inspection</option><option value="BLOCKED">Blocked</option></select></div><label class="control-label col-lg-2"><?=customs_h('search','Search');?></label><div class="col-lg-4"><input type="text" id="filter_keyword" class="form-control" placeholder="<?=customs_h('search_material_doc','Kode/nama material, dokumen, AJU, BPB, remark');?>"></div><div class="col-lg-2"><button type="button" class="btn btn-primary" id="btn_filter_mbj"><i class="fa fa-filter"></i> <?=customs_h('filter','Filter');?></button> <button type="button" class="btn btn-success" id="btn_excel_mbj"><i class="fa fa-file-excel-o"></i> <?=customs_h('excel','Excel');?></button> <button type="button" class="btn btn-default" id="btn_reset_mbj"><i class="fa fa-refresh"></i></button></div></div>
  </form></div></div>
  <div class="box"><div class="box-header with-border"><h3 class="box-title"><i class="fa fa-list"></i> <?=customs_h('mutation_finished_goods','Mutasi Barang Jadi');?></h3></div><div class="box-body"><div class="alert alert-warning fade in error_data_delete" style="display:none"><button type="button" class="close hide_alert_notif">&times;</button><i class="icon fa fa-warning"></i> <span class="isi_warning_delete"></span></div>
    <div class="mbj-official-title"><div class="subtitle">LAPORAN PERTANGGUNGJAWABAN MUTASI BARANG JADI</div><div class="subtitle">KAWASAN BERIKAT <?=mbj_view_h(defined('namaPT') ? namaPT : (defined('shortTittle') ? shortTittle : 'NAMA_PT'));?></div><div class="subtitle">PERIODE: <span id="mbj_period_from"><?=mbj_view_h($defaultFrom);?></span> SD <span id="mbj_period_to"><?=mbj_view_h($defaultTo);?></span></div></div>
    <div class="table-responsive mbj-table-wrap"><table id="dtb_mutasi_barang_jadi" class="table table-bordered table-striped table-condensed" style="width:100%"><thead><tr><th><?=customs_h('no','No');?></th><th><?=customs_h('material_code','KODE BARANG');?></th><th><?=customs_h('material_name','NAMA BARANG');?></th><th><?=customs_h('uom','SAT');?></th><th>SALDO<br>AWAL<br></th><th><?=customs_h('incoming','PEMASUKAN');?></th><th><?=customs_h('outgoing','PENGELUARAN');?></th><th><?=customs_h('adjustment','PENYESUAIAN');?><br>(ADJUSTMENT)</th><th>SALDO<br>AKHIR</th><th>STOCK<br>OPNAME.</th><th><?=customs_h('difference','SELISIH');?></th><th><?=customs_h('remarks','KETERANGAN');?></th></tr><tr><th>(1)</th><th>(2)</th><th>(3)</th><th>(4)</th><th>(5)</th><th>(6)</th><th>(7)</th><th>(8)</th><th>(9)</th><th>(10)</th><th>(11)</th><th>(12)</th></tr></thead><tbody></tbody></table></div>
  </div></div>
  <div id="modal_detail_mbj" class="modal fade"><div class="modal-dialog modal-lg" style="width:96%"><div class="modal-content"><div class="modal-header"><button type="button" class="close" data-dismiss="modal">&times;</button><h4 class="modal-title"><?=customs_h('detail_finished_goods_mutation','Detail Mutasi Barang Jadi');?></h4></div><div class="modal-body" id="isi_detail_mbj"></div><div class="modal-footer"><button type="button" class="btn btn-default" data-dismiss="modal"><?=customs_h('close','Close');?></button></div></div></div></div>
</section>
<script src="<?=base_admin();?>assets/plugins/select2/select2.min.js"></script>
<script>
function mbjFilters(){return{tgl_awal:$('#tgl_awal').val(),tgl_akhir:$('#tgl_akhir').val(),material_code:$('#filter_material').val(),plant_id:$('#filter_plant').val(),storage_location_id:$('#filter_storage_location').val(),storage_bin_id:$('#filter_storage_bin').val(),stock_type:$('#filter_stock_type').val(),keyword:$('#filter_keyword').val()};}
function showMbjError(msg){$('.isi_warning_delete').text(msg||'Data mutasi barang jadi gagal dimuat.');$('.error_data_delete').fadeIn();}
$(function(){if($.fn.datepicker){$('.mbj-date').datepicker({format:'yyyy-mm-dd',autoclose:true,todayHighlight:true});}if($.fn.select2){$('#filter_material,#filter_plant,#filter_storage_location,#filter_storage_bin,#filter_stock_type').select2({width:'100%',allowClear:true});}
$('#filter_plant').on('change',function(){var plant=$(this).val();$('#filter_storage_location option').each(function(){var op=$(this),p=op.data('plant-id');op.toggle(!p||!plant||String(p)===String(plant));});if(plant&&$('#filter_storage_location option:selected').data('plant-id')&&String($('#filter_storage_location option:selected').data('plant-id'))!==String(plant))$('#filter_storage_location').val('').trigger('change.select2');});
$('#filter_storage_location').on('change',function(){var loc=$(this).val();$('#filter_storage_bin option').each(function(){var op=$(this),l=op.data('storage-location-id');op.toggle(!l||!loc||String(l)===String(loc));});if(loc&&$('#filter_storage_bin option:selected').data('storage-location-id')&&String($('#filter_storage_bin option:selected').data('storage-location-id'))!==String(loc))$('#filter_storage_bin').val('').trigger('change.select2');});
var dt=$('#dtb_mutasi_barang_jadi').DataTable({bProcessing:true,bServerSide:true,pageLength:25,dom:"<'row'<'col-sm-12'B>>"+"<'row'<'col-sm-6'l><'col-sm-6'f>>"+"<'row'<'col-sm-12'tr>>"+"<'row'<'col-sm-5'i><'col-sm-7'p>>",buttons:[{extend:'collection',text:'<?=customs_h('export_data','Export Data');?>',buttons:['copyHtml5','excelHtml5','csvHtml5','pdfHtml5']}],columnDefs:[{targets:0,width:'48px',orderable:false,searchable:false,className:'mbj-center'},{targets:[4,5,6,7,8,9,10],className:'mbj-number'}],ajax:{url:'<?=base_admin();?>modul/mutasi_barang_jadi/mutasi_barang_jadi_data.php',type:'post',data:function(d){$.extend(d,mbjFilters());},error:function(xhr){console.log(xhr);showMbjError(<?=customs_js('finished_goods_mutation_load_failed','Data mutasi barang jadi gagal dimuat.');?>);}}});
$('#btn_filter_mbj').on('click',function(){$('#mbj_period_from').text($('#tgl_awal').val()||'-');$('#mbj_period_to').text($('#tgl_akhir').val()||'-');dt.draw();});$('#filter_keyword').on('keyup',function(e){if(e.keyCode===13)dt.draw();});$('#btn_excel_mbj').on('click',function(){window.location='<?=base_admin();?>modul/mutasi_barang_jadi/mutasi_barang_jadi_action.php?act=excel&'+$.param(mbjFilters());});
$('#btn_reset_mbj').on('click',function(){$('#tgl_awal').val('<?=$defaultFrom;?>');$('#tgl_akhir').val('<?=$defaultTo;?>');$('#mbj_period_from').text('<?=$defaultFrom;?>');$('#mbj_period_to').text('<?=$defaultTo;?>');$('#filter_keyword').val('');$('#filter_material,#filter_plant,#filter_storage_location,#filter_storage_bin,#filter_stock_type').val('').trigger('change');dt.draw();});
$(document).on('click','.mbj-detail-link',function(){var el=$(this);$('#isi_detail_mbj').html('<div class="text-center text-muted" style="padding:25px"><i class="fa fa-spinner fa-spin"></i> <?=customs_h('loading_detail','Memuat detail...');?></div>');$('#modal_detail_mbj').modal('show');$.post('<?=base_admin();?>modul/mutasi_barang_jadi/mutasi_barang_jadi_action.php?act=show_detail_pemasukan',{kd_barang:el.data('material'),type:el.data('type'),tgl_awal:$('#tgl_awal').val(),tgl_akhir:$('#tgl_akhir').val()},function(html){$('#isi_detail_mbj').html(html);}).fail(function(xhr){$('#isi_detail_mbj').html('<div class="alert alert-danger"><?=customs_h('detail_load_failed','Detail gagal dimuat.');?><br>'+xhr.responseText+'</div>');});});$(document).on('click','.hide_alert_notif',function(){$('.error_data_delete').hide();});});
</script>
