<?php
if (!function_exists('hr_t')) {
  function hr_t($key, $fallback = '') { return lang_text($key, $fallback); }
}
if (!function_exists('hr_h')) {
  function hr_h($key, $fallback = '') { return htmlspecialchars((string) hr_t($key, $fallback), ENT_QUOTES, 'UTF-8'); }
}
if (!function_exists('hr_js')) {
  function hr_js($key, $fallback = '') { return json_encode(hr_t($key, $fallback), JSON_HEX_TAG | JSON_HEX_APOS | JSON_HEX_AMP | JSON_HEX_QUOT); }
}
if (session_status() === PHP_SESSION_NONE) session_start();
include "../../inc/config.php";
session_check_json();
function pa_json($s,$m='',$x=array()){header('Content-Type: application/json; charset=utf-8');$p=array('status'=>$s);if($m!=='')$p[$s==='good'?'message':'error_message']=$m;foreach($x as $k=>$v)$p[$k]=$v;echo json_encode($p);exit;}
function pa_h($v){return htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');}
function pa_p($k,$d=''){return isset($_POST[$k])?$_POST[$k]:$d;}
function pa_user(){return isset($_SESSION['username'])&&$_SESSION['username']!==''?$_SESSION['username']:'admin';}
function pa_select2($rows,$id,$cb){$out=array();foreach($rows as $r)$out[]=array('id'=>$r->$id,'text'=>$cb($r));header('Content-Type: application/json; charset=utf-8');echo json_encode(array('results'=>$out));exit;}
function pa_no(){global $db;$prefix='PAPP'.date('Ym');$r=$db->fetch("SELECT appraisal_no FROM erp_performance_appraisal WHERE appraisal_no LIKE ? ORDER BY appraisal_no DESC LIMIT 1",array($prefix.'%'));$n=$r?((int)substr($r->appraisal_no,-4)+1):1;return $prefix.sprintf('%04d',$n);}
function pa_rating($score){if($score>=90)return 'A';if($score>=80)return 'B';if($score>=70)return 'C';if($score>=60)return 'D';return 'E';}
function pa_filters($src){return array('from'=>isset($src['tgl_awal'])&&$src['tgl_awal']!==''?$src['tgl_awal']:date('Y-01-01'),'to'=>isset($src['tgl_akhir'])&&$src['tgl_akhir']!==''?$src['tgl_akhir']:date('Y-m-d'),'cycle_year'=>isset($src['cycle_year'])?trim($src['cycle_year']):'','appraisal_period'=>isset($src['appraisal_period'])?trim($src['appraisal_period']):'','employee_id'=>isset($src['employee_id'])?trim($src['employee_id']):'','department_code'=>isset($src['department_code'])?trim($src['department_code']):'','job_title_id'=>isset($src['job_title_id'])?trim($src['job_title_id']):'','appraisal_status'=>isset($src['appraisal_status'])?trim($src['appraisal_status']):'','approval_status'=>isset($src['approval_status'])?trim($src['approval_status']):'','final_rating'=>isset($src['final_rating'])?trim($src['final_rating']):'','keyword'=>isset($src['keyword'])?trim($src['keyword']):'');}
function pa_where($f,&$p){$w=" WHERE pa.appraisal_date BETWEEN ? AND ? ";array_push($p,$f['from'],$f['to']);foreach(array('cycle_year','appraisal_period','department_code','appraisal_status','approval_status','final_rating') as $k){if($f[$k]!==''){$w.=" AND pa.$k=? ";$p[]=$f[$k];}}foreach(array('employee_id','job_title_id') as $k){if($f[$k]!==''){$w.=" AND pa.$k=? ";$p[]=(int)$f[$k];}}if($f['keyword']!==''){$kw='%'.$f['keyword'].'%';$w.=" AND (pa.appraisal_no LIKE ? OR e.employee_no LIKE ? OR e.full_name LIKE ? OR d.nm_dept LIKE ? OR jt.job_title_name LIKE ? OR ek.employee_kpi_no LIKE ?) ";for($i=0;$i<6;$i++)$p[]=$kw;}return $w;}
function pa_row($id){global $db;return $db->fetch("SELECT pa.*,e.employee_no,e.full_name,e.employee_group,d.nm_dept,jt.job_title_code,jt.job_title_name,ek.employee_kpi_no,ap.employee_no appraiser_no,ap.full_name appraiser_name,hr.employee_no hr_no,hr.full_name hr_name FROM erp_performance_appraisal pa JOIN erp_employee_master e ON e.id=pa.employee_id LEFT JOIN dept d ON d.kd_dept=pa.department_code LEFT JOIN erp_job_title jt ON jt.id=pa.job_title_id LEFT JOIN erp_employee_kpi ek ON ek.id=pa.employee_kpi_id LEFT JOIN erp_employee_master ap ON ap.id=pa.appraiser_employee_id LEFT JOIN erp_employee_master hr ON hr.id=pa.hr_reviewer_employee_id WHERE pa.id=? LIMIT 1",array((int)$id));}
$act=isset($_GET['act'])?$_GET['act']:'';
switch($act){
case 'employee_search':$t=trim(pa_p('term'));$like='%'.$t.'%';$rows=$db->query("SELECT id,employee_no,full_name,department_code,employee_group FROM erp_employee_master WHERE (?='' OR employee_no LIKE ? OR full_name LIKE ? OR department_code LIKE ?) ORDER BY employee_no LIMIT 50",array($t,$like,$like,$like));pa_select2($rows,'id',function($r){return $r->employee_no.' - '.$r->full_name.' ['.$r->department_code.' / '.$r->employee_group.']';});
case 'department_search':$t=trim(pa_p('term'));$like='%'.$t.'%';$rows=$db->query("SELECT kd_dept,nm_dept FROM dept WHERE (?='' OR kd_dept LIKE ? OR nm_dept LIKE ?) ORDER BY kd_dept LIMIT 50",array($t,$like,$like));pa_select2($rows,'kd_dept',function($r){return $r->kd_dept.' - '.$r->nm_dept;});
case 'job_title_search':$t=trim(pa_p('term'));$dept=trim(pa_p('department_code'));$like='%'.$t.'%';$sql="SELECT id,job_title_code,job_title_name,job_level FROM erp_job_title WHERE (?='' OR job_title_code LIKE ? OR job_title_name LIKE ?) ";$p=array($t,$like,$like);if($dept!==''){$sql.=" AND department_code=? ";$p[]=$dept;}$rows=$db->query($sql." ORDER BY job_level DESC,job_title_code LIMIT 50",$p);pa_select2($rows,'id',function($r){return $r->job_title_code.' - '.$r->job_title_name.' ['.$r->job_level.']';});
case 'employee_kpi_search':$t=trim(pa_p('term'));$like='%'.$t.'%';$rows=$db->query("SELECT ek.id,ek.employee_kpi_no,e.employee_no,e.full_name,ek.cycle_year,ek.appraisal_period FROM erp_employee_kpi ek JOIN erp_employee_master e ON e.id=ek.employee_id WHERE ek.target_status IN ('ASSIGNED','ACKNOWLEDGED','IN_REVIEW','COMPLETED') AND (?='' OR ek.employee_kpi_no LIKE ? OR e.employee_no LIKE ? OR e.full_name LIKE ?) ORDER BY ek.cycle_year DESC,ek.employee_kpi_no LIMIT 50",array($t,$like,$like,$like));pa_select2($rows,'id',function($r){return $r->employee_kpi_no.' - '.$r->employee_no.' '.$r->full_name.' ['.$r->cycle_year.' '.$r->appraisal_period.']';});
case 'kpi_lines':
  $id=(int)pa_p('employee_kpi_id');$r=$db->fetch("SELECT ek.*,e.employee_no,e.full_name,d.nm_dept,jt.job_title_code,jt.job_title_name,ap.employee_no appraiser_no,ap.full_name appraiser_name,hr.employee_no hr_no,hr.full_name hr_name FROM erp_employee_kpi ek JOIN erp_employee_master e ON e.id=ek.employee_id LEFT JOIN dept d ON d.kd_dept=ek.department_code LEFT JOIN erp_job_title jt ON jt.id=ek.job_title_id LEFT JOIN erp_employee_master ap ON ap.id=ek.appraiser_employee_id LEFT JOIN erp_employee_master hr ON hr.id=ek.hr_reviewer_employee_id WHERE ek.id=? LIMIT 1",array($id));if(!$r)pa_json('error','Employee KPI tidak ditemukan.');$rows=$db->query("SELECT * FROM erp_employee_kpi_detail WHERE employee_kpi_id=? ORDER BY line_no,id",array($id));$lines=array();foreach($rows as $x)$lines[]=(array)$x;$data=(array)$r;$data['employee_text']=$r->employee_no.' - '.$r->full_name;$data['department_text']=$r->department_code.' - '.$r->nm_dept;$data['job_title_text']=$r->job_title_code.' - '.$r->job_title_name;$data['appraiser_text']=$r->appraiser_no?($r->appraiser_no.' - '.$r->appraiser_name):'';$data['hr_text']=$r->hr_no?($r->hr_no.' - '.$r->hr_name):'';pa_json('good','',array('data'=>$data,'lines'=>$lines));
case 'get':
  $r=pa_row((int)pa_p('id'));if(!$r)pa_json('error','Performance Appraisal tidak ditemukan.');$data=(array)$r;$data['employee_kpi_text']=$r->employee_kpi_no.' - '.$r->employee_no.' '.$r->full_name;$data['employee_text']=$r->employee_no.' - '.$r->full_name;$data['department_text']=$r->department_code.' - '.$r->nm_dept;$data['job_title_text']=$r->job_title_code.' - '.$r->job_title_name;$data['appraiser_text']=$r->appraiser_no?($r->appraiser_no.' - '.$r->appraiser_name):'';$data['hr_text']=$r->hr_no?($r->hr_no.' - '.$r->hr_name):'';$rows=$db->query("SELECT * FROM erp_performance_appraisal_detail WHERE performance_appraisal_id=? ORDER BY line_no,id",array((int)$r->id));$lines=array();foreach($rows as $x)$lines[]=(array)$x;pa_json('good','',array('data'=>$data,'lines'=>$lines));
case 'save':
  $id=(int)pa_p('id');$user=pa_user();$ek=(int)pa_p('employee_kpi_id');if(!$ek)pa_json('error','Employee KPI wajib dipilih.');$no=trim(pa_p('appraisal_no'))!==''?strtoupper(trim(pa_p('appraisal_no'))):pa_no();$dup=$db->fetch("SELECT id FROM erp_performance_appraisal WHERE appraisal_no=? AND id<>? LIMIT 1",array($no,$id));if($dup)pa_json('error','Appraisal No sudah digunakan.');
  $codes=isset($_POST['kpi_code'])?$_POST['kpi_code']:array();$lines=array();$totalWeighted=0;$totalWeight=0;$n=1;for($i=0;$i<count($codes);$i++){if(trim($codes[$i])==='')continue;$w=(float)$_POST['weight'][$i];$mgr=$_POST['manager_score'][$i]!==''?(float)$_POST['manager_score'][$i]:0;$self=$_POST['self_score'][$i]!==''?(float)$_POST['self_score'][$i]:null;$final=$mgr;$weighted=round(($final*$w)/100,2);$totalWeight+=$w;$totalWeighted+=$weighted;$lines[]=array('employee_kpi_detail_id'=>$_POST['employee_kpi_detail_id'][$i]!==''?(int)$_POST['employee_kpi_detail_id'][$i]:null,'line_no'=>$n++,'kpi_code'=>strtoupper(trim($codes[$i])),'kpi_name'=>trim($_POST['kpi_name'][$i]),'kpi_perspective'=>$_POST['kpi_perspective'][$i],'target_text'=>trim($_POST['target_text'][$i]),'unit_of_measure'=>trim($_POST['unit_of_measure'][$i]),'weight'=>$w,'scoring_direction'=>$_POST['scoring_direction'][$i],'actual_value'=>$_POST['actual_value'][$i]!==''?(float)$_POST['actual_value'][$i]:null,'actual_text'=>trim($_POST['actual_text'][$i]),'self_score'=>$self,'manager_score'=>$mgr,'final_score'=>$final,'weighted_score'=>$weighted,'evidence_ref'=>trim($_POST['evidence_ref'][$i]),'appraiser_comment'=>trim($_POST['appraiser_comment'][$i]),'remarks'=>trim($_POST['detail_remarks'][$i]));}
  if(!count($lines))pa_json('error','Minimal satu detail KPI wajib diisi.');$comp=(float)pa_p('competency_score',0);$beh=(float)pa_p('behavior_score',0);$kpiScore=round($totalWeighted,2);$final=round(($kpiScore*0.60)+($comp*0.25)+($beh*0.15),2);$rating=pa_rating($final);$status=pa_p('appraisal_status','DRAFT');$approval=$status==='SUBMITTED'?'PENDING':pa_p('approval_status','NOT_SUBMITTED');
  $data=array('appraisal_no'=>$no,'employee_kpi_id'=>$ek,'employee_id'=>(int)pa_p('employee_id'),'cycle_year'=>(int)pa_p('cycle_year',date('Y')),'appraisal_period'=>pa_p('appraisal_period','ANNUAL'),'appraisal_type'=>pa_p('appraisal_type','ANNUAL'),'department_code'=>pa_p('department_code')!==''?pa_p('department_code'):null,'job_title_id'=>pa_p('job_title_id')!==''?(int)pa_p('job_title_id'):null,'appraiser_employee_id'=>pa_p('appraiser_employee_id')!==''?(int)pa_p('appraiser_employee_id'):null,'hr_reviewer_employee_id'=>pa_p('hr_reviewer_employee_id')!==''?(int)pa_p('hr_reviewer_employee_id'):null,'appraisal_date'=>pa_p('appraisal_date',date('Y-m-d')),'self_assessment_score'=>(float)pa_p('self_assessment_score',0),'manager_kpi_score'=>$kpiScore,'competency_score'=>$comp,'behavior_score'=>$beh,'final_score'=>$final,'final_rating'=>$rating,'appraisal_status'=>$status,'approval_status'=>$approval,'submitted_at'=>$status==='SUBMITTED'?date('Y-m-d H:i:s'):null,'employee_comment'=>trim(pa_p('employee_comment')),'manager_comment'=>trim(pa_p('manager_comment')),'hr_comment'=>trim(pa_p('hr_comment')),'development_plan'=>trim(pa_p('development_plan')),'reward_recommendation'=>trim(pa_p('reward_recommendation')),'improvement_required'=>pa_p('improvement_required','N'),'sap_reference'=>trim(pa_p('sap_reference')),'remarks'=>trim(pa_p('remarks')),'updated_by'=>$user,'updated_at'=>date('Y-m-d H:i:s'));
  if(!$data['employee_id'])pa_json('error','Employee wajib terisi dari Employee KPI.');if($id>0){$ok=$db->update('erp_performance_appraisal',$data,'id',$id);}else{$data['created_by']=$user;$ok=$db->insert('erp_performance_appraisal',$data);$id=(int)$db->last_insert_id();}if(!$ok)pa_json('error',$db->getErrorMessage()?:'Performance Appraisal gagal disimpan.');
  $db->delete('erp_performance_appraisal_detail','performance_appraisal_id',$id);foreach($lines as $l){$l['performance_appraisal_id']=$id;$db->insert('erp_performance_appraisal_detail',$l);}
  if(function_exists('simpan_log'))simpan_log('User '.$user.' menyimpan Performance Appraisal '.$no.' score '.$final.' pada '.date('Y-m-d H:i:s'),$user);pa_json('good','Performance Appraisal berhasil disimpan.',array('id'=>$id,'kpi_score'=>$kpiScore,'final_score'=>$final,'final_rating'=>$rating,'total_weight'=>$totalWeight));
case 'delete':$id=(int)pa_p('id');$r=pa_row($id);if(!$r)pa_json('error','Performance Appraisal tidak ditemukan.');$db->delete('erp_performance_appraisal_detail','performance_appraisal_id',$id);$db->delete('erp_performance_appraisal','id',$id);if($db->getErrorMessage())pa_json('error',$db->getErrorMessage());pa_json('good','Performance Appraisal berhasil dihapus.');
case 'detail':
  $r=pa_row((int)pa_p('id'));if(!$r){echo '<div class="alert alert-warning">Performance Appraisal tidak ditemukan.</div>';break;}$lines=$db->query("SELECT * FROM erp_performance_appraisal_detail WHERE performance_appraisal_id=? ORDER BY line_no,id",array((int)$r->id));echo '<div class="pa-detail"><h3 style="margin-top:0">'.pa_h($r->appraisal_no).' <small>'.pa_h($r->employee_no.' - '.$r->full_name).'</small></h3><span class="label label-primary">'.pa_h($r->appraisal_status).'</span> <span class="label label-success">Rating '.pa_h($r->final_rating).'</span><hr><div class="row"><div class="col-sm-3"><b>'.hr_h('hr_employee_kpi', 'Employee KPI').'</b><br>'.pa_h($r->employee_kpi_no).'</div><div class="col-sm-3"><b>Cycle</b><br>'.pa_h($r->cycle_year.' / '.$r->appraisal_period).'</div><div class="col-sm-3"><b>KPI Score</b><br>'.number_format((float)$r->manager_kpi_score,2).'</div><div class="col-sm-3"><b>Final Score</b><br><b>'.number_format((float)$r->final_score,2).'</b></div></div><hr><table class="table table-bordered table-condensed"><thead><tr><th>'.hr_h('common_no', 'No').'</th><th>KPI</th><th>Target</th><th>Weight</th><th>Actual</th><th>Self</th><th>'.hr_h('hr_manager', 'Manager').'</th><th>Weighted</th></tr></thead><tbody>';foreach($lines as $l){echo '<tr><td>'.(int)$l->line_no.'</td><td><b>'.pa_h($l->kpi_code).'</b><br><small>'.pa_h($l->kpi_name).'</small></td><td>'.pa_h(($l->target_text?:'-').' '.($l->unit_of_measure?:'')).'</td><td class="text-right">'.number_format((float)$l->weight,2).'%</td><td>'.pa_h($l->actual_text?:$l->actual_value?:'-').'</td><td class="text-right">'.($l->self_score!==null?number_format((float)$l->self_score,2):'-').'</td><td class="text-right">'.number_format((float)$l->manager_score,2).'</td><td class="text-right">'.number_format((float)$l->weighted_score,2).'</td></tr>';}echo '</tbody></table><p><b>Development Plan:</b> '.pa_h($r->development_plan?:'-').'<br><b>Remarks:</b> '.pa_h($r->remarks?:'-').'</p></div>';break;
case 'export':
  $initial=ob_get_level();ob_start();error_reporting(E_ALL & ~E_NOTICE & ~E_WARNING & ~E_DEPRECATED & ~E_USER_DEPRECATED);require_once "../../inc/lib/PHPExcel.php";require_once "../../inc/excel_style_helper.php";PHPExcel_Shared_File::setUseUploadTempDirectory(true);$f=pa_filters($_GET);$p=array();$w=pa_where($f,$p);$rows=$db->query("SELECT pa.*,e.employee_no,e.full_name,d.nm_dept,jt.job_title_code,jt.job_title_name,det.line_no,det.kpi_code,det.kpi_name,det.weight,det.actual_text,det.self_score,det.manager_score,det.weighted_score FROM erp_performance_appraisal pa JOIN erp_employee_master e ON e.id=pa.employee_id LEFT JOIN dept d ON d.kd_dept=pa.department_code LEFT JOIN erp_job_title jt ON jt.id=pa.job_title_id LEFT JOIN erp_employee_kpi ek ON ek.id=pa.employee_kpi_id LEFT JOIN erp_performance_appraisal_detail det ON det.performance_appraisal_id=pa.id $w ORDER BY pa.appraisal_no,det.line_no",$p);
  $excel=new PHPExcel();$sheet=$excel->setActiveSheetIndex(0);$sheet->setTitle(erp_export_sheet_title('Performance Appraisal'));$heads=array(erp_export_label("No"),erp_export_label("Appraisal No"),erp_export_label("Employee"),erp_export_label("Department"),erp_export_label("Job Title"),erp_export_label("Year"),erp_export_label("Period"),erp_export_label("Date"),erp_export_label("KPI Score"),erp_export_label("Competency"),erp_export_label("Behavior"),erp_export_label("Final Score"),erp_export_label("Rating"),erp_export_label("Status"),erp_export_label("Approval"),erp_export_label("Line"),erp_export_label("KPI Code"),erp_export_label("KPI Name"),erp_export_label("Weight"),erp_export_label("Actual"),erp_export_label("Self Score"),erp_export_label("Manager Score"),erp_export_label("Weighted"),erp_export_label("Development Plan"),erp_export_label("Updated By"));foreach($heads as $i=>$h)$sheet->setCellValue(PHPExcel_Cell::stringFromColumnIndex($i).'4',$h);$rn=5;$n=1;foreach($rows as $r){$vals=array($n++,$r->appraisal_no,$r->employee_no.' - '.$r->full_name,$r->department_code.' - '.$r->nm_dept,$r->job_title_code.' - '.$r->job_title_name,$r->cycle_year,$r->appraisal_period,$r->appraisal_date,$r->manager_kpi_score,$r->competency_score,$r->behavior_score,$r->final_score,$r->final_rating,$r->appraisal_status,$r->approval_status,$r->line_no,$r->kpi_code,$r->kpi_name,$r->weight,$r->actual_text,$r->self_score,$r->manager_score,$r->weighted_score,$r->development_plan,$r->updated_by?:$r->created_by);foreach($vals as $i=>$v)$sheet->setCellValue(PHPExcel_Cell::stringFromColumnIndex($i).$rn,$v);$rn++;}
  erpkb_excel_apply_standard_style($excel,array('sheet'=>$sheet,'title'=>erp_export_title('PERFORMANCE APPRAISAL REPORT'),'header_row'=>4,'first_data_row'=>5,'last_data_row'=>max(5,$rn-1),'column_count'=>count($heads),'numeric_columns'=>array('I','J','K','L','P','S','U','V','W'),'filters'=>array('Tanggal'=>$f['from'].' s/d '.$f['to'],'Year'=>$f['cycle_year']?:erp_export_all_text(),'Status'=>$f['appraisal_status']?:erp_export_all_text()),'widths'=>array('B'=>20,'C'=>28,'D'=>26,'E'=>28,'Q'=>18,'R'=>30,'X'=>34,'Y'=>18)));
  $tmp=erpkb_excel_temp_file('performance_appraisal_');PHPExcel_IOFactory::createWriter($excel,'Excel2007')->save($tmp);$size=@filesize($tmp);$sig=@file_get_contents($tmp,false,null,0,2);if(!$size||$sig!=='PK'){@unlink($tmp);while(ob_get_level()>$initial)ob_end_clean();echo erp_t('export_excel_invalid_file','File Excel gagal dibuat dengan benar.');exit;}while(ob_get_level()>$initial)ob_end_clean();header('Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');header('Content-Disposition: attachment; filename="performance_appraisal_'.date('Ymd_His').'.xlsx"');header('Content-Length: '.$size);header('Cache-Control: max-age=0');header('Pragma: public');readfile($tmp);@unlink($tmp);exit;
default:pa_json('error','Action tidak dikenal.');
}
?>
