<?php
if (!function_exists('hr_t')) {
  function hr_t($key, $fallback = '') { return lang_text($key, $fallback); }
}
if (!function_exists('hr_h')) {
  function hr_h($key, $fallback = '') { return htmlspecialchars((string) hr_t($key, $fallback), ENT_QUOTES, 'UTF-8'); }
}
if (!function_exists('hr_js')) {
  function hr_js($key, $fallback = '') { return json_encode(hr_t($key, $fallback), JSON_HEX_TAG | JSON_HEX_APOS | JSON_HEX_AMP | JSON_HEX_QUOT); }
}
$defaultFrom=date('Y-01-01');$defaultTo=date('Y-m-d');$yearNow=(int)date('Y');$canInsert=isset($role_act['insert_act'])&&$role_act['insert_act']==='Y';$canUpdate=isset($role_act['update_act'])&&$role_act['update_act']==='Y';$canDelete=isset($role_act['delete_act'])&&$role_act['delete_act']==='Y'; ?>
<style>
.pa-hero{background:linear-gradient(135deg,#0f766e,#7c2d12);color:#fff;border-radius:14px;padding:22px;margin-bottom:16px;box-shadow:0 10px 24px rgba(15,118,110,.18)}.pa-hero h1{margin:0 0 6px;font-size:27px;font-weight:700}.pa-hero p{margin:0;color:#ccfbf1}.pa-card{border-radius:12px;background:#fff;border:1px solid #e5edf5;box-shadow:0 5px 16px rgba(15,23,42,.05);margin-bottom:14px}.pa-kpi{padding:14px;border-radius:12px;background:#f8fafc;border:1px solid #dbeafe;min-height:76px}.pa-kpi span{display:block;color:#64748b;font-size:12px}.pa-kpi b{font-size:21px;color:#0f172a}.pa-kpi.good{background:#ecfdf5;border-color:#bbf7d0}.pa-kpi.warn{background:#fff7ed;border-color:#fed7aa}#dtb_performance_appraisal th,#dtb_performance_appraisal td{font-size:12px;vertical-align:middle}.select2-container{width:100%!important}.pa-action{white-space:nowrap}.pa-detail{background:#fff;border:1px solid #e5e7eb;border-radius:12px;padding:18px}#modal_pa .modal-body,#modal_pa_detail .modal-body{max-height:calc(100vh - 180px);overflow-y:auto}.pa-line-table th,.pa-line-table td{font-size:12px;vertical-align:middle}.pa-line-table input{min-width:100px}.pa-line-table .wide{min-width:180px}.pa-score-ok{font-weight:700;color:#16a34a}
</style>
<section class="content-header"><h1><?=hr_h('hr_performance_appraisal', 'Performance Appraisal');?> <small>SAP HCM Performance Review</small></h1><ol class="breadcrumb"><li><a href="<?=base_index();?>"><i class="fa fa-dashboard"></i> <?=hr_h('common_home', 'Home');?></a></li><li>Human Resource</li><li>Performance Management</li><li class="active"><?=hr_h('hr_performance_appraisal', 'Performance Appraisal');?></li></ol></section>
<section class="content">
<div class="pa-hero"><div class="row"><div class="col-md-8"><h1>Performance Appraisal Workbench</h1><p>Review KPI employee, isi actual result, self score, manager score, competency, behavior, final rating, dan submit ke approval.</p></div><div class="col-md-4 text-right"><?php if($canInsert){ ?><button id="btn_open_pa" class="btn btn-warning"><i class="fa fa-plus"></i> Create Appraisal</button><?php } ?> <button id="btn_export_pa" class="btn btn-success"><i class="fa fa-file-excel-o"></i> <?=hr_h('common_export_excel', 'Export Excel');?></button></div></div></div>
<div class="row"><div class="col-sm-2"><div class="pa-kpi"><span>Total</span><b id="kpi_total">0</b></div></div><div class="col-sm-2"><div class="pa-kpi"><span>Employees</span><b id="kpi_employees">0</b></div></div><div class="col-sm-2"><div class="pa-kpi good"><span>Avg Score</span><b id="kpi_avg">0</b></div></div><div class="col-sm-2"><div class="pa-kpi warn"><span>Submitted</span><b id="kpi_submitted">0</b></div></div><div class="col-sm-2"><div class="pa-kpi good"><span><?=hr_h('hr_approved', 'Approved');?></span><b id="kpi_approved">0</b></div></div><div class="col-sm-2"><div class="pa-kpi warn"><span>PIP</span><b id="kpi_pip">0</b></div></div></div>
<div class="box pa-card"><div class="box-header"><h3 class="box-title"><i class="fa fa-filter"></i> Filter Performance Appraisal</h3></div><div class="box-body"><form class="form-horizontal" onsubmit="return false;">
<div class="form-group"><label class="control-label col-lg-2">Appraisal Date</label><div class="col-lg-2"><div class="input-group date pa-date"><input id="filter_tgl_awal" class="form-control" value="<?=$defaultFrom;?>"><span class="input-group-addon"><span class="glyphicon glyphicon-calendar"></span></span></div></div><div class="col-lg-2"><div class="input-group date pa-date"><input id="filter_tgl_akhir" class="form-control" value="<?=$defaultTo;?>"><span class="input-group-addon"><span class="glyphicon glyphicon-calendar"></span></span></div></div><label class="control-label col-lg-1">Year</label><div class="col-lg-1"><select id="filter_cycle_year" class="form-control"><option value="">All</option><?php for($y=$yearNow-2;$y<=$yearNow+1;$y++){ ?><option value="<?=$y;?>" <?=$y===$yearNow?'selected':'';?>><?=$y;?></option><?php } ?></select></div><label class="control-label col-lg-1"><?=hr_h('hr_period', 'Period');?></label><div class="col-lg-3"><select id="filter_appraisal_period" class="form-control"><option value="">All</option><option>Q1</option><option>Q2</option><option>Q3</option><option>Q4</option><option>H1</option><option>H2</option><option>ANNUAL</option><option>PROBATION</option><option>SPECIAL</option></select></div></div>
<div class="form-group"><label class="control-label col-lg-2"><?=hr_h('hr_employee', 'Employee');?></label><div class="col-lg-3"><select id="filter_employee_id" class="form-control"></select></div><label class="control-label col-lg-1"><?=hr_h('hr_department', 'Department');?></label><div class="col-lg-3"><select id="filter_department_code" class="form-control"></select></div><label class="control-label col-lg-1">Job</label><div class="col-lg-2"><select id="filter_job_title_id" class="form-control"></select></div></div>
<div class="form-group"><label class="control-label col-lg-2"><?=hr_h('common_status', 'Status');?></label><div class="col-lg-2"><select id="filter_appraisal_status" class="form-control"><option value="">All</option><option>DRAFT</option><option>SELF_ASSESSED</option><option>MANAGER_REVIEW</option><option>SUBMITTED</option><option>APPROVED</option><option>REJECTED</option><option>RETURNED</option><option>CANCELLED</option></select></div><label class="control-label col-lg-1">Approval</label><div class="col-lg-2"><select id="filter_approval_status" class="form-control"><option value="">All</option><option>NOT_SUBMITTED</option><option>PENDING</option><option>APPROVED</option><option>REJECTED</option><option>RETURNED</option></select></div><label class="control-label col-lg-1"><?=hr_h('hr_rating', 'Rating');?></label><div class="col-lg-2"><select id="filter_final_rating" class="form-control"><option value="">All</option><option>A</option><option>B</option><option>C</option><option>D</option><option>E</option></select></div><div class="col-lg-2"><input id="filter_keyword" class="form-control" placeholder="<?=hr_h('common_search', 'Search');?>"></div></div>
<div class="form-group"><div class="col-lg-10 col-lg-offset-2"><button id="btn_filter_pa" class="btn btn-primary"><i class="fa fa-filter"></i> <?=hr_h('common_filter', 'Filter');?></button> <button id="btn_reset_pa" class="btn btn-default"><i class="fa fa-refresh"></i> <?=hr_h('common_reset', 'Reset');?></button></div></div>
</form></div></div>
<div class="box pa-card"><div class="box-body"><div class="alert alert-warning error_data_delete" style="display:none"><button type="button" class="close hide_alert_notif">&times;</button><span class="isi_warning_delete"></span></div><div class="table-responsive"><table id="dtb_performance_appraisal" class="table table-bordered table-striped" style="width:100%"><thead><tr><th><?=hr_h('common_no', 'No');?></th><th><?=hr_h('common_action', 'Action');?></th><th>Appraisal</th><th><?=hr_h('hr_employee', 'Employee');?></th><th>Organization</th><th><?=hr_h('hr_employee_kpi', 'Employee KPI');?></th><th>Cycle</th><th>Score Detail</th><th>Final</th><th><?=hr_h('hr_rating', 'Rating');?></th><th><?=hr_h('common_status', 'Status');?></th><th>Updated</th></tr></thead><tbody></tbody></table></div></div></div>
<div id="modal_pa" class="modal fade"><div class="modal-dialog modal-lg" style="width:96%"><div class="modal-content"><form id="form_pa"><input type="hidden" name="id" id="pa_id"><input type="hidden" name="employee_id" id="employee_id"><div class="modal-header"><button class="close" data-dismiss="modal">&times;</button><h4 class="modal-title">Create Performance Appraisal</h4></div><div class="modal-body">
<div class="alert alert-info"><strong>SAP hint:</strong> Pilih Employee KPI lalu Generate KPI Review. Final score = KPI score 60%, Competency 25%, Behavior 15%.</div>
<div class="row"><div class="col-md-2 form-group"><label>Appraisal No</label><input name="appraisal_no" id="appraisal_no" class="form-control" placeholder="Auto"></div><div class="col-md-4 form-group"><label><?=hr_h('hr_employee_kpi', 'Employee KPI');?></label><select name="employee_kpi_id" id="employee_kpi_id" class="form-control"></select></div><div class="col-md-2 form-group"><label>Year</label><input name="cycle_year" id="cycle_year" class="form-control" value="<?=$yearNow;?>"></div><div class="col-md-2 form-group"><label><?=hr_h('hr_period', 'Period');?></label><select name="appraisal_period" id="appraisal_period" class="form-control"><option>ANNUAL</option><option>H1</option><option>H2</option><option>Q1</option><option>Q2</option><option>Q3</option><option>Q4</option><option>PROBATION</option><option>SPECIAL</option></select></div><div class="col-md-2 form-group"><label><?=hr_h('hr_date', 'Date');?></label><input name="appraisal_date" id="appraisal_date" class="form-control pa-date-field" value="<?=date('Y-m-d');?>"></div></div>
<div class="row"><div class="col-md-3 form-group"><label><?=hr_h('hr_employee', 'Employee');?></label><input id="employee_text" class="form-control" readonly></div><div class="col-md-3 form-group"><label><?=hr_h('hr_department', 'Department');?></label><select name="department_code" id="department_code" class="form-control"></select></div><div class="col-md-3 form-group"><label><?=hr_h('hr_job_title', 'Job Title');?></label><select name="job_title_id" id="job_title_id" class="form-control"></select></div><div class="col-md-3 form-group"><label><br></label><button type="button" id="btn_generate_pa" class="btn btn-success btn-block"><i class="fa fa-magic"></i> Generate KPI Review</button></div></div>
<div class="row"><div class="col-md-3 form-group"><label>Appraiser</label><select name="appraiser_employee_id" id="appraiser_employee_id" class="form-control"></select></div><div class="col-md-3 form-group"><label>HR Reviewer</label><select name="hr_reviewer_employee_id" id="hr_reviewer_employee_id" class="form-control"></select></div><div class="col-md-2 form-group"><label><?=hr_h('common_status', 'Status');?></label><select name="appraisal_status" id="appraisal_status" class="form-control"><option>DRAFT</option><option>SELF_ASSESSED</option><option>MANAGER_REVIEW</option><option>SUBMITTED</option><option>APPROVED</option><option>REJECTED</option><option>RETURNED</option><option>CANCELLED</option></select></div><div class="col-md-2 form-group"><label>Competency</label><input name="competency_score" id="competency_score" type="number" step="0.01" class="form-control pa-score" value="0"></div><div class="col-md-2 form-group"><label>Behavior</label><input name="behavior_score" id="behavior_score" type="number" step="0.01" class="form-control pa-score" value="0"></div></div>
<div class="row"><div class="col-md-2 form-group"><label>Self Avg</label><input name="self_assessment_score" id="self_assessment_score" class="form-control" readonly value="0"></div><div class="col-md-2 form-group"><label>KPI Score</label><input id="manager_kpi_score_preview" class="form-control" readonly value="0"></div><div class="col-md-2 form-group"><label>Final Score</label><input id="final_score_preview" class="form-control pa-score-ok" readonly value="0"></div><div class="col-md-2 form-group"><label><?=hr_h('hr_rating', 'Rating');?></label><input id="final_rating_preview" class="form-control pa-score-ok" readonly value="C"></div><div class="col-md-2 form-group"><label>Improvement</label><select name="improvement_required" id="improvement_required" class="form-control"><option>N</option><option>Y</option></select></div><div class="col-md-2 form-group"><label>Type</label><select name="appraisal_type" id="appraisal_type" class="form-control"><option>ANNUAL</option><option>MID_YEAR</option><option>PROBATION</option><option>PROJECT</option><option>SPECIAL</option></select></div></div>
<h4>KPI Review Items</h4><div class="table-responsive"><table class="table table-bordered pa-line-table"><thead><tr><th><?=hr_h('common_no', 'No');?></th><th>KPI</th><th>Target</th><th>Weight</th><th>Actual</th><th>Self</th><th><?=hr_h('hr_manager', 'Manager');?></th><th>Evidence</th><th>Comment</th></tr></thead><tbody id="pa_lines"></tbody></table></div>
<div class="row"><div class="col-md-4 form-group"><label>Employee Comment</label><textarea name="employee_comment" id="employee_comment" class="form-control" rows="3"></textarea></div><div class="col-md-4 form-group"><label>Manager Comment</label><textarea name="manager_comment" id="manager_comment" class="form-control" rows="3"></textarea></div><div class="col-md-4 form-group"><label>HR Comment</label><textarea name="hr_comment" id="hr_comment" class="form-control" rows="3"></textarea></div></div>
<div class="row"><div class="col-md-5 form-group"><label>Development Plan</label><textarea name="development_plan" id="development_plan" class="form-control" rows="2"></textarea></div><div class="col-md-3 form-group"><label>Reward Recommendation</label><input name="reward_recommendation" id="reward_recommendation" class="form-control"></div><div class="col-md-2 form-group"><label>SAP Ref</label><input name="sap_reference" id="sap_reference" class="form-control"></div><div class="col-md-2 form-group"><label><?=hr_h('common_remarks', 'Remarks');?></label><input name="remarks" id="remarks" class="form-control"></div></div>
</div><div class="modal-footer"><button type="button" class="btn btn-default" data-dismiss="modal"><?=hr_h('common_cancel', 'Cancel');?></button><button type="submit" class="btn btn-primary"><i class="fa fa-save"></i> Save Appraisal</button></div></form></div></div></div>
<div id="modal_pa_detail" class="modal fade"><div class="modal-dialog modal-lg" style="width:94%"><div class="modal-content"><div class="modal-header"><button class="close" data-dismiss="modal">&times;</button><h4 class="modal-title">Performance Appraisal Detail</h4></div><div class="modal-body" id="pa_detail_body"></div><div class="modal-footer"><button class="btn btn-default" data-dismiss="modal"><?=hr_h('common_close', 'Close');?></button></div></div></div></div>
</section>
<script src="<?=base_admin();?>assets/plugins/select2/select2.min.js"></script><script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
<script>
var paCanUpdate='<?=$canUpdate?'Y':'N';?>',paCanDelete='<?=$canDelete?'Y':'N';?>';
function paError(m){$('.isi_warning_delete').text(m||'Performance Appraisal gagal diproses.');$('.error_data_delete').fadeIn();}
function paFilters(){return{tgl_awal:$('#filter_tgl_awal').val(),tgl_akhir:$('#filter_tgl_akhir').val(),cycle_year:$('#filter_cycle_year').val(),appraisal_period:$('#filter_appraisal_period').val(),employee_id:$('#filter_employee_id').val(),department_code:$('#filter_department_code').val(),job_title_id:$('#filter_job_title_id').val(),appraisal_status:$('#filter_appraisal_status').val(),approval_status:$('#filter_approval_status').val(),final_rating:$('#filter_final_rating').val(),keyword:$('#filter_keyword').val()};}
function paAjax(s,act,p,parent){$(s).select2({width:'100%',allowClear:true,placeholder:p,dropdownParent:parent||$(document.body),ajax:{url:'<?=base_admin();?>modul/performance_appraisal/performance_appraisal_action.php?act='+act,type:'POST',dataType:'json',delay:250,data:function(q){return{term:q.term||'',department_code:$('#department_code').val()||$('#filter_department_code').val()||''};},processResults:function(d){return{results:d.results||[]};}}});}
function paSet(sel,val,text){var e=$(sel);if(!val){e.val(null).trigger('change');return;}if(!e.find('option[value="'+val+'"]').length)e.append(new Option(text||val,val,true,true));e.val(val).trigger('change');}
function paRating(s){s=parseFloat(s||0);if(s>=90)return'A';if(s>=80)return'B';if(s>=70)return'C';if(s>=60)return'D';return'E';}
function paLine(l){l=l||{};var n=$('#pa_lines tr').length+1;return '<tr><td class="line-no">'+n+'</td><td><input name="employee_kpi_detail_id[]" type="hidden" value="'+(l.employee_kpi_detail_id||l.id||'')+'"><input name="kpi_code[]" class="form-control" value="'+(l.kpi_code||'')+'"><input name="kpi_name[]" class="form-control wide" value="'+(l.kpi_name||'')+'"><input name="kpi_perspective[]" type="hidden" value="'+(l.kpi_perspective||'PROCESS')+'"><input name="scoring_direction[]" type="hidden" value="'+(l.scoring_direction||'HIGHER_BETTER')+'"></td><td><input name="target_text[]" class="form-control wide" value="'+(l.target_text||'')+'"><input name="unit_of_measure[]" type="hidden" value="'+(l.unit_of_measure||'')+'"></td><td><input name="weight[]" type="number" step="0.01" class="form-control pa-weight" value="'+(l.weight||'0')+'"></td><td><input name="actual_value[]" type="number" step="0.0001" class="form-control" value="'+(l.actual_value||'')+'"><input name="actual_text[]" class="form-control" value="'+(l.actual_text||'')+'" placeholder="Text"></td><td><input name="self_score[]" type="number" step="0.01" class="form-control pa-self" value="'+(l.self_score||'')+'"></td><td><input name="manager_score[]" type="number" step="0.01" class="form-control pa-manager" value="'+(l.manager_score||l.score||'')+'"></td><td><input name="evidence_ref[]" class="form-control wide" value="'+(l.evidence_ref||'')+'"></td><td><input name="appraiser_comment[]" class="form-control wide" value="'+(l.appraiser_comment||'')+'"><input name="detail_remarks[]" type="hidden" value="'+(l.remarks||'')+'"></td></tr>';}
function paCalc(){var wsum=0,ks=0,self=0,sc=0;$('#pa_lines tr').each(function(){var w=parseFloat($(this).find('.pa-weight').val()||0)||0,m=parseFloat($(this).find('.pa-manager').val()||0)||0,s=parseFloat($(this).find('.pa-self').val()||0);wsum+=w;ks+=(m*w/100);if(!isNaN(s)){self+=s;sc++;}});var comp=parseFloat($('#competency_score').val()||0)||0,beh=parseFloat($('#behavior_score').val()||0)||0,fin=(ks*.60)+(comp*.25)+(beh*.15);$('#manager_kpi_score_preview').val(ks.toFixed(2));$('#final_score_preview').val(fin.toFixed(2));$('#final_rating_preview').val(paRating(fin));$('#self_assessment_score').val(sc?(self/sc).toFixed(2):'0.00');}
function paReset(){$('#form_pa')[0].reset();$('#pa_id,#appraisal_no,#employee_id').val('');$('#cycle_year').val('<?=$yearNow;?>');$('#appraisal_date').val('<?=date('Y-m-d');?>');$('#employee_kpi_id,#department_code,#job_title_id,#appraiser_employee_id,#hr_reviewer_employee_id').val(null).trigger('change');$('#appraisal_period').val('ANNUAL').trigger('change');$('#appraisal_type').val('ANNUAL').trigger('change');$('#appraisal_status').val('DRAFT').trigger('change');$('#improvement_required').val('N').trigger('change');$('#pa_lines').empty();paCalc();$('#modal_pa .modal-title').text('Create Performance Appraisal');}
$(function(){
 if($.fn.datepicker){$('.pa-date,.pa-date-field').datepicker({format:'yyyy-mm-dd',autoclose:true,todayHighlight:true});}
 if($.fn.select2){$('#filter_cycle_year,#filter_appraisal_period,#filter_appraisal_status,#filter_approval_status,#filter_final_rating,#appraisal_period,#appraisal_type,#appraisal_status,#improvement_required').select2({width:'100%',allowClear:true});paAjax('#filter_employee_id','employee_search','Semua Employee');paAjax('#filter_department_code','department_search','Semua Department');paAjax('#filter_job_title_id','job_title_search','Semua Job Title');paAjax('#employee_kpi_id','employee_kpi_search','Pilih Employee KPI',$('#modal_pa'));paAjax('#department_code','department_search','Pilih Department',$('#modal_pa'));paAjax('#job_title_id','job_title_search','Pilih Job Title',$('#modal_pa'));paAjax('#appraiser_employee_id','employee_search','Pilih Appraiser',$('#modal_pa'));paAjax('#hr_reviewer_employee_id','employee_search','Pilih HR Reviewer',$('#modal_pa'));}
 var dt=$('#dtb_performance_appraisal').DataTable({bProcessing:true,bServerSide:true,pageLength:25,dom:"<'row'<'col-sm-12'B>>"+"<'row'<'col-sm-6'l><'col-sm-6'f>>"+"<'row'<'col-sm-12'tr>>"+"<'row'<'col-sm-5'i><'col-sm-7'p>>",buttons:[{extend:'collection',text:<?=hr_js('common_export_data', 'Export Data');?>,buttons:['copyHtml5','excelHtml5','csvHtml5']}],columnDefs:[{targets:[0,1],orderable:false,searchable:false},{width:'42px',targets:0},{width:'115px',targets:1}],ajax:{url:'<?=base_admin();?>modul/performance_appraisal/performance_appraisal_data.php',type:'post',data:function(d){$.extend(d,paFilters());},dataSrc:function(j){var k=j.kpi||{};$('#kpi_total').text(k.total||0);$('#kpi_employees').text(k.employees||0);$('#kpi_avg').text(k.avg_score||0);$('#kpi_submitted').text(k.submitted||0);$('#kpi_approved').text(k.approved||0);$('#kpi_pip').text(k.pip||0);return j.data||[];},error:function(x){console.log(x.responseText);paError('Data Performance Appraisal gagal dimuat.');}}});
 $('#btn_open_pa').click(function(){paReset();$('#modal_pa').modal({backdrop:'static',keyboard:false});});$('#btn_filter_pa').click(function(){dt.draw();});$('#filter_keyword').keyup(function(e){if(e.keyCode===13)dt.draw();});$('#btn_reset_pa').click(function(){$('#filter_tgl_awal').val('<?=$defaultFrom;?>');$('#filter_tgl_akhir').val('<?=$defaultTo;?>');$('#filter_cycle_year').val('<?=$yearNow;?>').trigger('change');$('#filter_appraisal_period,#filter_employee_id,#filter_department_code,#filter_job_title_id,#filter_appraisal_status,#filter_approval_status,#filter_final_rating').val(null).trigger('change');$('#filter_keyword').val('');dt.draw();});$('#btn_export_pa').click(function(){window.location='<?=base_admin();?>modul/performance_appraisal/performance_appraisal_action.php?act=export&'+$.param(paFilters());});$('.hide_alert_notif').click(function(){$('.error_data_delete').hide();});
 $('#btn_generate_pa').click(function(){var id=$('#employee_kpi_id').val();if(!id){paError('Employee KPI wajib dipilih.');return;}$.post('<?=base_admin();?>modul/performance_appraisal/performance_appraisal_action.php?act=kpi_lines',{employee_kpi_id:id},function(r){if(r.status!=='good'){paError(r.error_message);return;}var d=r.data;$('#employee_id').val(d.employee_id);$('#employee_text').val(d.employee_text);$('#cycle_year').val(d.cycle_year);$('#appraisal_period').val(d.appraisal_period).trigger('change');paSet('#department_code',d.department_code,d.department_text);paSet('#job_title_id',d.job_title_id,d.job_title_text);paSet('#appraiser_employee_id',d.appraiser_employee_id,d.appraiser_text);paSet('#hr_reviewer_employee_id',d.hr_reviewer_employee_id,d.hr_text);$('#pa_lines').empty();(r.lines||[]).forEach(function(l){$('#pa_lines').append(paLine(l));});paCalc();},'json');});
 $(document).on('keyup change','.pa-weight,.pa-self,.pa-manager,#competency_score,#behavior_score',paCalc);
 $('#form_pa').submit(function(e){e.preventDefault();var btn=$(this).find('button[type=submit]');btn.prop('disabled',true).html('<i class="fa fa-spinner fa-spin"></i> <?=hr_h('common_saving', 'Saving...');?>');$.post('<?=base_admin();?>modul/performance_appraisal/performance_appraisal_action.php?act=save',$(this).serialize(),function(r){btn.prop('disabled',false).html('<i class="fa fa-save"></i> Save Appraisal');if(r.status==='good'){$('#modal_pa').modal('hide');dt.draw(false);Swal.fire('Saved','Final score '+r.final_score+' rating '+r.final_rating,'success');}else paError(r.error_message);},'json').fail(function(x){btn.prop('disabled',false).html('<i class="fa fa-save"></i> Save Appraisal');paError(x.responseText);});});
 $(document).on('click','.btn-pa-detail',function(){$.post('<?=base_admin();?>modul/performance_appraisal/performance_appraisal_action.php?act=detail',{id:$(this).data('id')},function(h){$('#pa_detail_body').html(h);$('#modal_pa_detail').modal('show');});});
 $(document).on('click','.btn-pa-edit',function(){if(paCanUpdate!=='Y')return;paReset();$.post('<?=base_admin();?>modul/performance_appraisal/performance_appraisal_action.php?act=get',{id:$(this).data('id')},function(r){if(r.status!=='good'){paError(r.error_message);return;}var d=r.data;Object.keys(d).forEach(function(k){var e=$('#'+k);if(e.length&&!['employee_kpi_id','department_code','job_title_id','appraiser_employee_id','hr_reviewer_employee_id'].includes(k))e.val(d[k]);});$('#pa_id').val(d.id);$('#employee_text').val(d.employee_text);paSet('#employee_kpi_id',d.employee_kpi_id,d.employee_kpi_text);paSet('#department_code',d.department_code,d.department_text);paSet('#job_title_id',d.job_title_id,d.job_title_text);paSet('#appraiser_employee_id',d.appraiser_employee_id,d.appraiser_text);paSet('#hr_reviewer_employee_id',d.hr_reviewer_employee_id,d.hr_text);$('#appraisal_period,#appraisal_type,#appraisal_status,#improvement_required').trigger('change');$('#pa_lines').empty();(r.lines||[]).forEach(function(l){$('#pa_lines').append(paLine(l));});paCalc();$('#modal_pa .modal-title').text('Edit Performance Appraisal');$('#modal_pa').modal({backdrop:'static',keyboard:false});},'json');});
 $(document).on('click','.btn-pa-delete',function(){if(paCanDelete!=='Y')return;var id=$(this).data('id'),no=$(this).data('no');Swal.fire({title:erpLang('confirm_delete_title','Delete Confirmation'),text:no,icon:'warning',showCancelButton:true,confirmButtonText:erpLang('common_delete','Delete'),cancelButtonText:erpLang('common_cancel','Cancel')}).then(function(x){if(!x.isConfirmed)return;$.post('<?=base_admin();?>modul/performance_appraisal/performance_appraisal_action.php?act=delete',{id:id},function(r){if(r.status==='good'){dt.draw(false);Swal.fire(erpLang('common_deleted','Deleted'),erpLang('common_deleted_message','Data deleted successfully.'),'success');}else paError(r.error_message);},'json');});});
});
</script>
