<?php
if (!function_exists('hr_t')) {
  function hr_t($key, $fallback = '') { return lang_text($key, $fallback); }
}
if (!function_exists('hr_h')) {
  function hr_h($key, $fallback = '') { return htmlspecialchars((string) hr_t($key, $fallback), ENT_QUOTES, 'UTF-8'); }
}
if (!function_exists('hr_js')) {
  function hr_js($key, $fallback = '') { return json_encode(hr_t($key, $fallback), JSON_HEX_TAG | JSON_HEX_APOS | JSON_HEX_AMP | JSON_HEX_QUOT); }
}
if (session_status() === PHP_SESSION_NONE) session_start();
include "../../inc/config.php";
session_check_json();
function pad_h($v){return htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');}
function pad_label($s){$m=array('DRAFT'=>'default','SELF_ASSESSED'=>'info','MANAGER_REVIEW'=>'warning','SUBMITTED'=>'primary','APPROVED'=>'success','REJECTED'=>'danger','RETURNED'=>'warning','CANCELLED'=>'default','NOT_SUBMITTED'=>'default','PENDING'=>'warning');$c=isset($m[$s])?$m[$s]:'default';return '<span class="label label-'.$c.'">'.pad_h($s?:'-').'</span>';}
function pad_rating($r){$m=array('A'=>'success','B'=>'primary','C'=>'info','D'=>'warning','E'=>'danger');$c=isset($m[$r])?$m[$r]:'default';return '<span class="label label-'.$c.'" style="font-size:13px">'.pad_h($r?:'-').'</span>';}
function pad_filters(){return array('from'=>isset($_POST['tgl_awal'])&&$_POST['tgl_awal']!==''?$_POST['tgl_awal']:date('Y-01-01'),'to'=>isset($_POST['tgl_akhir'])&&$_POST['tgl_akhir']!==''?$_POST['tgl_akhir']:date('Y-m-d'),'cycle_year'=>isset($_POST['cycle_year'])?trim($_POST['cycle_year']):'','appraisal_period'=>isset($_POST['appraisal_period'])?trim($_POST['appraisal_period']):'','employee_id'=>isset($_POST['employee_id'])?trim($_POST['employee_id']):'','department_code'=>isset($_POST['department_code'])?trim($_POST['department_code']):'','job_title_id'=>isset($_POST['job_title_id'])?trim($_POST['job_title_id']):'','appraisal_status'=>isset($_POST['appraisal_status'])?trim($_POST['appraisal_status']):'','approval_status'=>isset($_POST['approval_status'])?trim($_POST['approval_status']):'','final_rating'=>isset($_POST['final_rating'])?trim($_POST['final_rating']):'','keyword'=>isset($_POST['keyword'])?trim($_POST['keyword']):'');}
function pad_where($f,&$p){$w=" WHERE pa.appraisal_date BETWEEN ? AND ? ";array_push($p,$f['from'],$f['to']);foreach(array('cycle_year','appraisal_period','department_code','appraisal_status','approval_status','final_rating') as $k){if($f[$k]!==''){$w.=" AND pa.$k=? ";$p[]=$f[$k];}}foreach(array('employee_id','job_title_id') as $k){if($f[$k]!==''){$w.=" AND pa.$k=? ";$p[]=(int)$f[$k];}}if($f['keyword']!==''){$kw='%'.$f['keyword'].'%';$w.=" AND (pa.appraisal_no LIKE ? OR e.employee_no LIKE ? OR e.full_name LIKE ? OR d.nm_dept LIKE ? OR jt.job_title_name LIKE ? OR ek.employee_kpi_no LIKE ?) ";for($i=0;$i<6;$i++)$p[]=$kw;}return $w;}
$draw=isset($_POST['draw'])?(int)$_POST['draw']:1;$start=isset($_POST['start'])?max(0,(int)$_POST['start']):0;$length=isset($_POST['length'])?(int)$_POST['length']:25;if($length<=0||$length>500)$length=25;
$f=pad_filters();$p=array();$w=pad_where($f,$p);
$base=" FROM erp_performance_appraisal pa JOIN erp_employee_master e ON e.id=pa.employee_id LEFT JOIN dept d ON d.kd_dept=pa.department_code LEFT JOIN erp_job_title jt ON jt.id=pa.job_title_id LEFT JOIN erp_employee_kpi ek ON ek.id=pa.employee_kpi_id LEFT JOIN erp_employee_master ap ON ap.id=pa.appraiser_employee_id ";
$kpi=$db->fetch("SELECT COUNT(*) total,COUNT(DISTINCT pa.employee_id) employees,ROUND(AVG(pa.final_score),2) avg_score,SUM(pa.appraisal_status='SUBMITTED') submitted,SUM(pa.appraisal_status='APPROVED') approved,SUM(pa.improvement_required='Y') pip $base $w",$p);
$cnt=$db->fetch("SELECT COUNT(*) jml $base $w",$p);$total=$cnt?(int)$cnt->jml:0;
$orderMap=array(2=>'pa.appraisal_no',3=>'e.employee_no',4=>'d.kd_dept',5=>'ek.employee_kpi_no',6=>'pa.cycle_year',7=>'pa.manager_kpi_score',8=>'pa.final_score',9=>'pa.final_rating',10=>'pa.appraisal_status',11=>'pa.updated_at');$orderBy='pa.appraisal_date DESC,pa.id DESC';
if(isset($_POST['order'][0]['column'])){$col=(int)$_POST['order'][0]['column'];$dir=(isset($_POST['order'][0]['dir'])&&strtolower($_POST['order'][0]['dir'])==='desc')?'DESC':'ASC';if(isset($orderMap[$col]))$orderBy=$orderMap[$col].' '.$dir;}
$rows=$db->query("SELECT pa.*,e.employee_no,e.full_name,e.employee_group,d.nm_dept,jt.job_title_code,jt.job_title_name,ek.employee_kpi_no,ap.employee_no appraiser_no,ap.full_name appraiser_name,(SELECT COUNT(*) FROM erp_performance_appraisal_detail x WHERE x.performance_appraisal_id=pa.id) line_count $base $w ORDER BY $orderBy LIMIT $start,$length",$p);
$data=array();$no=$start+1;foreach($rows as $r){$act='<div class="pa-action"><button class="btn btn-info btn-xs btn-pa-detail" data-id="'.(int)$r->id.'"><i class="fa fa-eye"></i></button> <button class="btn btn-primary btn-xs btn-pa-edit" data-id="'.(int)$r->id.'"><i class="fa fa-pencil"></i></button> <button class="btn btn-danger btn-xs btn-pa-delete" data-id="'.(int)$r->id.'" data-no="'.pad_h($r->appraisal_no).'"><i class="fa fa-trash"></i></button></div>';
  $data[]=array($no++,$act,'<strong>'.pad_h($r->appraisal_no).'</strong><br><small>'.pad_h($r->sap_reference?:'-').'</small>','<strong>'.pad_h($r->employee_no).'</strong><br><small>'.pad_h($r->full_name).' / '.pad_h($r->employee_group).'</small>','<strong>'.pad_h($r->department_code?:'-').'</strong><br><small>'.pad_h($r->nm_dept?:'-').'</small><br><small>'.pad_h($r->job_title_code?:'-').' '.pad_h($r->job_title_name?:'').'</small>',pad_h($r->employee_kpi_no?:'-').'<br><small>Items '.(int)$r->line_count.'</small>',pad_h($r->cycle_year.' / '.$r->appraisal_period).'<br><small>'.pad_h($r->appraisal_type).' / '.pad_h($r->appraisal_date).'</small>','KPI '.number_format((float)$r->manager_kpi_score,2).'<br><small>Comp '.number_format((float)$r->competency_score,2).' | Beh '.number_format((float)$r->behavior_score,2).'</small>','<strong>'.number_format((float)$r->final_score,2).'</strong>',pad_rating($r->final_rating),pad_label($r->appraisal_status).'<br><small>'.pad_h($r->approval_status).'</small>',pad_h($r->updated_by?:$r->created_by?:'-').'<br><small>'.pad_h($r->updated_at?:$r->created_at).'</small>');
}
header('Content-Type: application/json; charset=utf-8');echo json_encode(array('draw'=>$draw,'recordsTotal'=>$total,'recordsFiltered'=>$total,'data'=>$data,'kpi'=>array('total'=>$kpi?(int)$kpi->total:0,'employees'=>$kpi?(int)$kpi->employees:0,'avg_score'=>$kpi&&$kpi->avg_score!==null?$kpi->avg_score:0,'submitted'=>$kpi?(int)$kpi->submitted:0,'approved'=>$kpi?(int)$kpi->approved:0,'pip'=>$kpi?(int)$kpi->pip:0)));
?>
