<?php
if (!function_exists('hr_t')) {
  function hr_t($key, $fallback = '') { return lang_text($key, $fallback); }
}
if (!function_exists('hr_h')) {
  function hr_h($key, $fallback = '') { return htmlspecialchars((string) hr_t($key, $fallback), ENT_QUOTES, 'UTF-8'); }
}
if (!function_exists('hr_js')) {
  function hr_js($key, $fallback = '') { return json_encode(hr_t($key, $fallback), JSON_HEX_TAG | JSON_HEX_APOS | JSON_HEX_AMP | JSON_HEX_QUOT); }
}
if (session_status() === PHP_SESSION_NONE) session_start();
include "../../inc/config.php";
session_check_json();
function ar_h($v){return htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');}
function ar_label($s){$m=array('DRAFT'=>'warning','RECORDED'=>'info','APPROVED'=>'success','POSTED'=>'primary','REJECTED'=>'danger','CANCELLED'=>'default');$c=isset($m[$s])?$m[$s]:'default';return '<span class="label label-'.$c.'">'.ar_h($s).'</span>';}
function ar_filters(){return array('from'=>isset($_POST['tgl_awal'])&&$_POST['tgl_awal']!==''?$_POST['tgl_awal']:date('Y-m-01'),'to'=>isset($_POST['tgl_akhir'])&&$_POST['tgl_akhir']!==''?$_POST['tgl_akhir']:date('Y-m-t'),'employee_id'=>isset($_POST['employee_id'])?trim($_POST['employee_id']):'','department_code'=>isset($_POST['department_code'])?trim($_POST['department_code']):'','shift_id'=>isset($_POST['shift_id'])?trim($_POST['shift_id']):'','work_location_id'=>isset($_POST['work_location_id'])?trim($_POST['work_location_id']):'','attendance_type'=>isset($_POST['attendance_type'])?trim($_POST['attendance_type']):'','attendance_status'=>isset($_POST['attendance_status'])?trim($_POST['attendance_status']):'','attendance_source'=>isset($_POST['attendance_source'])?trim($_POST['attendance_source']):'','exception_type'=>isset($_POST['exception_type'])?trim($_POST['exception_type']):'','keyword'=>isset($_POST['keyword'])?trim($_POST['keyword']):'');}
function ar_where($f,&$p){$w=" WHERE a.attendance_date BETWEEN ? AND ? ";array_push($p,$f['from'],$f['to']);foreach(array('employee_id','shift_id','work_location_id') as $k){if($f[$k]!==''){$w.=" AND a.$k=? ";$p[]=(int)$f[$k];}}foreach(array('department_code','attendance_type','attendance_status','attendance_source') as $k){if($f[$k]!==''){$w.=" AND a.$k=? ";$p[]=$f[$k];}}if($f['exception_type']==='LATE')$w.=" AND a.late_minutes>0 ";elseif($f['exception_type']==='EARLY_LEAVE')$w.=" AND a.early_leave_minutes>0 ";elseif($f['exception_type']==='OVERTIME')$w.=" AND a.overtime_hours>0 ";elseif($f['exception_type']==='ABSENCE')$w.=" AND a.attendance_type IN ('ABSENT','SICK','LEAVE') ";elseif($f['exception_type']==='NO_CLOCK_OUT')$w.=" AND a.actual_clock_in IS NOT NULL AND a.actual_clock_out IS NULL ";if($f['keyword']!==''){$kw='%'.$f['keyword'].'%';$w.=" AND (a.attendance_no LIKE ? OR a.employee_no LIKE ? OR e.full_name LIKE ? OR a.sap_reference LIKE ? OR a.remarks LIKE ? OR d.nm_dept LIKE ?) ";for($i=0;$i<6;$i++)$p[]=$kw;}return $w;}
$draw=isset($_POST['draw'])?(int)$_POST['draw']:1;$start=isset($_POST['start'])?max(0,(int)$_POST['start']):0;$length=isset($_POST['length'])?(int)$_POST['length']:25;if($length<=0||$length>500)$length=25;
$f=ar_filters();$p=array();$w=ar_where($f,$p);
$base=" FROM erp_attendance a JOIN erp_employee_master e ON e.id=a.employee_id LEFT JOIN dept d ON d.kd_dept=a.department_code LEFT JOIN erp_shift s ON s.id=a.shift_id LEFT JOIN erp_work_location wl ON wl.id=a.work_location_id ";
$kpi=$db->fetch("SELECT COUNT(*) total,SUM(a.attendance_status='POSTED') posted_count,SUM(a.late_minutes>0) late_count,SUM(a.early_leave_minutes>0) early_count,SUM(a.attendance_type IN ('ABSENT','SICK','LEAVE')) absence_count,ROUND(SUM(a.overtime_hours),2) overtime_hours,ROUND(SUM(a.actual_hours),2) actual_hours,ROUND(SUM(a.planned_hours),2) planned_hours $base $w",$p);
$cnt=$db->fetch("SELECT COUNT(*) jml $base $w",$p);$total=$cnt?(int)$cnt->jml:0;
$orderMap=array(2=>'a.attendance_no',3=>'a.attendance_date',4=>'e.employee_no',5=>'d.kd_dept',6=>'a.shift_code',7=>'wl.location_code',8=>'a.actual_clock_in',9=>'a.actual_hours',10=>'a.attendance_type',11=>'a.attendance_status',12=>'a.updated_at');$orderBy='a.attendance_date DESC,a.attendance_no DESC';
if(isset($_POST['order'][0]['column'])){$col=(int)$_POST['order'][0]['column'];$dir=(isset($_POST['order'][0]['dir'])&&strtolower($_POST['order'][0]['dir'])==='desc')?'DESC':'ASC';if(isset($orderMap[$col]))$orderBy=$orderMap[$col].' '.$dir;}
$rows=$db->query("SELECT a.*,e.full_name,e.employee_group,d.nm_dept,s.nama_shift,wl.location_code,wl.location_name $base $w ORDER BY $orderBy LIMIT $start,$length",$p);
$data=array();$no=$start+1;foreach($rows as $r){$exception=array();if((int)$r->late_minutes>0)$exception[]='Late '.$r->late_minutes.'m';if((int)$r->early_leave_minutes>0)$exception[]='Early '.$r->early_leave_minutes.'m';if((float)$r->overtime_hours>0)$exception[]='OT '.$r->overtime_hours.'h';if(in_array($r->attendance_type,array('ABSENT','SICK','LEAVE'),true))$exception[]=$r->attendance_type;$data[]=array($no++,'<button class="btn btn-info btn-xs btn-ar-detail" data-id="'.(int)$r->id.'"><i class="fa fa-eye"></i></button>','<strong>'.ar_h($r->attendance_no).'</strong><br><small>'.ar_h($r->sap_reference?:'-').'</small>',ar_h($r->attendance_date),'<strong>'.ar_h($r->employee_no).'</strong><br><small>'.ar_h($r->full_name).' / '.ar_h($r->employee_group).'</small>','<strong>'.ar_h($r->department_code?:'-').'</strong><br><small>'.ar_h($r->nm_dept?:'-').'</small>','<strong>'.ar_h(($r->shift_code?:'-').' '.$r->nama_shift).'</strong><br><small>'.ar_h($r->assignment_no?:'-').'</small>',ar_h(($r->location_code?:'-').' - '.($r->location_name?:'-')),'Plan '.ar_h($r->planned_start?substr($r->planned_start,11,5):'-').' - '.ar_h($r->planned_end?substr($r->planned_end,11,5):'-').'<br><small>Actual '.ar_h($r->actual_clock_in?substr($r->actual_clock_in,11,5):'-').' - '.ar_h($r->actual_clock_out?substr($r->actual_clock_out,11,5):'-').'</small>','<strong>'.ar_h($r->actual_hours).'</strong> / '.ar_h($r->planned_hours).'<br><small>'.ar_h(implode(' | ',$exception)?:'On schedule').'</small>','<strong>'.ar_h($r->attendance_type).'</strong><br><small>'.ar_h($r->attendance_source).'</small>',ar_label($r->attendance_status),ar_h($r->updated_by?:$r->created_by?:'-').'<br><small>'.ar_h($r->updated_at?:$r->created_at).'</small>');}
$rate=($kpi&&$kpi->total>0)?round((($kpi->total-$kpi->late_count-$kpi->early_count-$kpi->absence_count)/$kpi->total)*100,2):0;
header('Content-Type: application/json; charset=utf-8');echo json_encode(array('draw'=>$draw,'recordsTotal'=>$total,'recordsFiltered'=>$total,'data'=>$data,'kpi'=>array('total'=>$kpi?(int)$kpi->total:0,'posted'=>$kpi?(int)$kpi->posted_count:0,'late'=>$kpi?(int)$kpi->late_count:0,'early'=>$kpi?(int)$kpi->early_count:0,'absence'=>$kpi?(int)$kpi->absence_count:0,'overtime'=>$kpi?$kpi->overtime_hours:0,'actual_hours'=>$kpi?$kpi->actual_hours:0,'compliance'=>$rate)));
?>
