<?php
include_once "inspection_lot_lib.php";
$defaultFrom = date('Y-m-01');
$defaultTo = date('Y-m-d');
$plants = ilot_plants($db);
$storageLocations = ilot_storage_locations($db);
$storageBins = ilot_storage_bins($db);
$kpi = ilot_kpi($db);
$nextNo = ilot_next_number(date('Y-m-d'));
?>
<style>
.ilot-hero{background:linear-gradient(135deg,#0f172a,#0369a1);color:#fff;border-radius:14px;padding:21px 22px;margin-bottom:18px;box-shadow:0 10px 24px rgba(15,23,42,.18)}
.ilot-hero h1{margin:0 0 6px;font-size:26px;font-weight:700}.ilot-hero p{margin:0;opacity:.92}
.ilot-kpi{border-radius:12px;background:#fff;border:1px solid #e5edf5;padding:15px;margin-bottom:14px;box-shadow:0 4px 14px rgba(15,23,42,.05)}
.ilot-kpi span{display:block;color:#64748b;font-size:12px;text-transform:uppercase;letter-spacing:.04em}.ilot-kpi strong{display:block;font-size:23px;margin-top:6px;color:#111827}
.ilot-kpi i{float:right;font-size:26px;color:#0369a1;opacity:.55}.ilot-card{border-radius:12px;border:1px solid #e5edf5;box-shadow:0 5px 16px rgba(15,23,42,.05)}
.ilot-filter .form-group{margin-bottom:12px}#dtb_inspection_lot th,#dtb_inspection_lot td{font-size:12px;vertical-align:middle}.select2-container{width:100%!important}
.ilot-help{color:#64748b;margin-top:6px}.ilot-detail-table th{width:190px;background:#f8fafc}.ilot-modal .modal-body{max-height:72vh;overflow:auto}
#tbl_ilot_result th,#tbl_ilot_result td{font-size:12px;vertical-align:middle}
</style>
<section class="content-header">
  <h1>Inspection Lot <small>SAP QM Workbench</small></h1>
  <ol class="breadcrumb"><li><a href="<?=base_index();?>"><i class="fa fa-dashboard"></i> Home</a></li><li><a href="<?=base_index();?>quality-dashboard">Quality Management</a></li><li class="active">Inspection Lot</li></ol>
</section>
<section class="content">
  <div class="ilot-hero"><div class="row"><div class="col-md-8"><h1>Inspection Lot Workbench</h1><p>Buat, monitor, record result, dan finalisasi usage decision inspection lot dengan trace material, lokasi, stock layer, dan dokumen BC.</p></div><div class="col-md-4 text-right"><button id="btn_generate_source" class="btn btn-info"><i class="fa fa-magic"></i> Generate from QI Stock</button> <button id="btn_add_ilot_top" class="btn btn-success"><i class="fa fa-plus"></i> Add Lot</button></div></div></div>
  <div class="row">
    <div class="col-sm-3"><div class="ilot-kpi"><i class="fa fa-clipboard"></i><span>Total Lots</span><strong><?=number_format((float)$kpi->total_lot,0,',','.');?></strong></div></div>
    <div class="col-sm-3"><div class="ilot-kpi"><i class="fa fa-hourglass-half"></i><span>Open Lots</span><strong><?=number_format((float)$kpi->open_lot,0,',','.');?></strong></div></div>
    <div class="col-sm-3"><div class="ilot-kpi"><i class="fa fa-check"></i><span>Accepted Lots</span><strong><?=number_format((float)$kpi->accepted_lot,0,',','.');?></strong></div></div>
    <div class="col-sm-3"><div class="ilot-kpi"><i class="fa fa-warning"></i><span>Exception Lots</span><strong><?=number_format((float)$kpi->exception_lot,0,',','.');?></strong></div></div>
  </div>
  <div class="box ilot-card"><div class="box-header with-border"><h3 class="box-title"><i class="fa fa-filter"></i> Filter Inspection Lot</h3></div><div class="box-body">
    <form class="form-horizontal ilot-filter" onsubmit="return false;">
      <div class="form-group"><label class="control-label col-lg-2">Created Date</label><div class="col-lg-2"><div class="input-group date ilot-date"><input id="filter_tgl_awal" class="form-control" value="<?=$defaultFrom;?>" autocomplete="off"><span class="input-group-addon"><span class="glyphicon glyphicon-calendar"></span></span></div></div><div class="col-lg-2"><div class="input-group date ilot-date"><input id="filter_tgl_akhir" class="form-control" value="<?=$defaultTo;?>" autocomplete="off"><span class="input-group-addon"><span class="glyphicon glyphicon-calendar"></span></span></div></div><label class="control-label col-lg-1">Material</label><div class="col-lg-5"><select id="filter_material" class="form-control"></select></div></div>
      <div class="form-group"><label class="control-label col-lg-2">Plant</label><div class="col-lg-2"><select id="filter_plant" class="form-control"><option value="">Semua Plant</option><?php foreach($plants as $p){ ?><option value="<?=intval($p->id);?>"><?=ilot_h($p->plant_code.' - '.$p->plant_name);?></option><?php } ?></select></div><label class="control-label col-lg-2">Storage Location</label><div class="col-lg-2"><select id="filter_storage_location" class="form-control"><option value="">Semua SLoc</option><?php foreach($storageLocations as $s){ ?><option value="<?=intval($s->id);?>" data-plant-id="<?=intval($s->plant_id);?>"><?=ilot_h($s->plant_code.' / '.$s->storage_code.' - '.$s->storage_name);?></option><?php } ?></select></div><label class="control-label col-lg-1">Storage Bin</label><div class="col-lg-3"><select id="filter_storage_bin" class="form-control"><option value="">Semua Bin</option><?php foreach($storageBins as $b){ ?><option value="<?=intval($b->id);?>" data-storage-location-id="<?=intval($b->storage_location_id);?>"><?=ilot_h($b->storage_code.' / '.$b->bin_code.' - '.$b->bin_name);?></option><?php } ?></select></div></div>
      <div class="form-group"><label class="control-label col-lg-2">Status</label><div class="col-lg-2"><select id="filter_lot_status" class="form-control"><option value="">Semua Status</option><option>CREATED</option><option>IN_INSPECTION</option><option>RESULT_RECORDED</option><option>UD_ACCEPTED</option><option>UD_REJECTED</option><option>UD_PARTIAL</option><option>CANCELLED</option></select></div><label class="control-label col-lg-2">Origin</label><div class="col-lg-2"><select id="filter_inspection_origin" class="form-control"><option value="">Semua Origin</option><option value="GOODS_RECEIPT">Goods Receipt</option><option value="PRODUCTION">Production</option><option value="MANUAL">Manual</option><option value="TRANSFER">Transfer</option><option value="RETURN">Return</option></select></div><label class="control-label col-lg-1">Search</label><div class="col-lg-3"><input id="filter_keyword" class="form-control" placeholder="Lot, material, source, No Aju, BC"></div></div>
      <div class="form-group"><div class="col-lg-offset-2 col-lg-10"><button id="btn_filter_ilot" class="btn btn-primary"><i class="fa fa-filter"></i> Filter</button> <button id="btn_reset_ilot" class="btn btn-default"><i class="fa fa-refresh"></i> Reset</button> <button id="btn_excel_ilot" class="btn btn-success"><i class="fa fa-file-excel-o"></i> Export Excel</button> <button id="btn_add_ilot" class="btn btn-info"><i class="fa fa-plus"></i> Add Manual Lot</button></div></div>
    </form>
  </div></div>
  <div class="box ilot-card"><div class="box-body"><div class="alert alert-warning error_data_delete" style="display:none"><button type="button" class="close hide_alert_notif">&times;</button><i class="icon fa fa-warning"></i> <span class="isi_warning_delete"></span></div><div class="table-responsive"><table id="dtb_inspection_lot" class="table table-bordered table-striped table-condensed" style="width:100%"><thead><tr><th>No</th><th>Action</th><th>Inspection Lot</th><th>Material</th><th>Lot Qty</th><th>Sample</th><th>Location</th><th>Status</th><th>Source / Customs</th><th>Created</th></tr></thead><tbody></tbody></table></div></div></div>

  <div id="modal_ilot_form" class="modal fade ilot-modal"><div class="modal-dialog modal-lg" style="width:96%"><div class="modal-content"><div class="modal-header"><button class="close" data-dismiss="modal">&times;</button><h4 class="modal-title">Inspection Lot</h4></div><div class="modal-body">
    <form id="form_ilot" class="form-horizontal">
      <input type="hidden" name="id" id="ilot_id"><input type="hidden" name="material_name" id="material_name"><input type="hidden" name="source_ref_type" id="source_ref_type"><input type="hidden" name="source_ref_id" id="source_ref_id"><input type="hidden" name="source_ref_no" id="source_ref_no"><input type="hidden" name="stock_layer_id" id="stock_layer_id"><input type="hidden" name="no_aju" id="no_aju"><input type="hidden" name="jenis_dokpab" id="jenis_dokpab"><input type="hidden" name="no_dokpab" id="no_dokpab"><input type="hidden" name="no_bpb" id="no_bpb">
      <div class="alert alert-info"><strong>SAP QM hint:</strong> Inspection lot idealnya dibuat dari GR/production receipt dengan stock type Quality Inspection. Manual lot dipakai untuk kasus khusus.</div>
      <div class="form-group"><label class="control-label col-sm-2">Source QI Stock</label><div class="col-sm-10"><select id="source_layer_select" class="form-control"></select><div class="ilot-help">Pilih layer stock QUALITY/BLOCKED untuk auto-fill material, qty, lokasi, dan dokumen BC.</div></div></div>
      <div class="form-group"><label class="control-label col-sm-2">Lot No</label><div class="col-sm-2"><input name="lot_no" id="lot_no" class="form-control" value="<?=ilot_h($nextNo);?>"></div><label class="control-label col-sm-2">Origin</label><div class="col-sm-2"><select name="inspection_origin" id="inspection_origin" class="form-control"><option value="GOODS_RECEIPT">Goods Receipt</option><option value="PRODUCTION">Production</option><option value="MANUAL">Manual</option><option value="TRANSFER">Transfer</option><option value="RETURN">Return</option></select></div><label class="control-label col-sm-2">Inspection Type</label><div class="col-sm-2"><input name="inspection_type" id="inspection_type" class="form-control" value="01"></div></div>
      <div class="form-group"><label class="control-label col-sm-2">Material</label><div class="col-sm-5"><select name="material_code" id="material_code" class="form-control"></select></div><label class="control-label col-sm-1">UOM</label><div class="col-sm-1"><input name="uom" id="uom" class="form-control"></div><label class="control-label col-sm-1">Stock</label><div class="col-sm-2"><select name="stock_type" id="stock_type" class="form-control"><option value="QUALITY">QUALITY</option><option value="BLOCKED">BLOCKED</option><option value="UNRESTRICTED">UNRESTRICTED</option></select></div></div>
      <div class="form-group"><label class="control-label col-sm-2">Lot Qty</label><div class="col-sm-2"><input name="lot_qty" id="lot_qty" class="form-control text-right"></div><label class="control-label col-sm-2">Sample Qty</label><div class="col-sm-2"><input name="sample_qty" id="sample_qty" class="form-control text-right"></div><label class="control-label col-sm-2">Batch / Lot</label><div class="col-sm-2"><input name="batch_no" id="batch_no" class="form-control"></div></div>
      <div class="form-group"><label class="control-label col-sm-2">Plant</label><div class="col-sm-2"><select name="plant_id" id="plant_id" class="form-control"><option value="">-</option><?php foreach($plants as $p){ ?><option value="<?=intval($p->id);?>"><?=ilot_h($p->plant_code.' - '.$p->plant_name);?></option><?php } ?></select></div><label class="control-label col-sm-2">Storage Location</label><div class="col-sm-2"><select name="storage_location_id" id="storage_location_id" class="form-control"><option value="">-</option><?php foreach($storageLocations as $s){ ?><option value="<?=intval($s->id);?>" data-plant-id="<?=intval($s->plant_id);?>"><?=ilot_h($s->plant_code.' / '.$s->storage_code.' - '.$s->storage_name);?></option><?php } ?></select></div><label class="control-label col-sm-1">Bin</label><div class="col-sm-3"><select name="storage_bin_id" id="storage_bin_id" class="form-control"><option value="">-</option><?php foreach($storageBins as $b){ ?><option value="<?=intval($b->id);?>" data-storage-location-id="<?=intval($b->storage_location_id);?>"><?=ilot_h($b->storage_code.' / '.$b->bin_code.' - '.$b->bin_name);?></option><?php } ?></select></div></div>
      <div class="form-group"><label class="control-label col-sm-2">Inspection Plan</label><div class="col-sm-4"><input name="inspection_plan" id="inspection_plan" class="form-control" placeholder="Optional: plan/group counter"></div><label class="control-label col-sm-2">Notes</label><div class="col-sm-4"><textarea name="notes" id="notes" class="form-control" rows="2"></textarea></div></div>
    </form>
  </div><div class="modal-footer"><button class="btn btn-default" data-dismiss="modal">Close</button><button id="btn_save_ilot" class="btn btn-primary"><i class="fa fa-save"></i> Save Lot</button></div></div></div></div>

  <div id="modal_ilot_detail" class="modal fade ilot-modal"><div class="modal-dialog modal-lg" style="width:96%"><div class="modal-content"><div class="modal-header"><button class="close" data-dismiss="modal">&times;</button><h4 class="modal-title">Inspection Lot Detail</h4></div><div class="modal-body" id="ilot_detail_body"></div><div class="modal-footer"><button class="btn btn-default" data-dismiss="modal">Close</button></div></div></div></div>
  <div id="modal_ilot_result" class="modal fade ilot-modal"><div class="modal-dialog modal-lg" style="width:96%"><div class="modal-content"><div class="modal-header"><button class="close" data-dismiss="modal">&times;</button><h4 class="modal-title">Record Inspection Result</h4></div><div class="modal-body" id="ilot_result_body"></div><div class="modal-footer"><button class="btn btn-default" data-dismiss="modal">Close</button><button id="btn_save_result" class="btn btn-success"><i class="fa fa-check-square-o"></i> Save Result</button></div></div></div></div>
  <div id="modal_ilot_ud" class="modal fade ilot-modal"><div class="modal-dialog modal-lg"><div class="modal-content"><div class="modal-header"><button class="close" data-dismiss="modal">&times;</button><h4 class="modal-title">Usage Decision</h4></div><div class="modal-body" id="ilot_ud_body"></div><div class="modal-footer"><button class="btn btn-default" data-dismiss="modal">Close</button><button id="btn_save_ud" class="btn btn-warning"><i class="fa fa-gavel"></i> Post Usage Decision</button></div></div></div></div>
</section>
<script src="<?=base_admin();?>assets/plugins/select2/select2.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
<script>
function ilotError(m){$('.isi_warning_delete').text(m||'Inspection Lot gagal diproses.');$('.error_data_delete').fadeIn();}
function ilotFilters(){return{tgl_awal:$('#filter_tgl_awal').val(),tgl_akhir:$('#filter_tgl_akhir').val(),material_code:$('#filter_material').val(),plant_id:$('#filter_plant').val(),storage_location_id:$('#filter_storage_location').val(),storage_bin_id:$('#filter_storage_bin').val(),lot_status:$('#filter_lot_status').val(),inspection_origin:$('#filter_inspection_origin').val(),keyword:$('#filter_keyword').val()};}
function ilotExcelUrl(){return '<?=base_admin();?>modul/inspection_lot/inspection_lot_action.php?act=excel&'+$.param(ilotFilters());}
function initISelect(){
  if(!$.fn.select2)return;
  $('#filter_plant,#filter_storage_location,#filter_storage_bin,#filter_lot_status,#filter_inspection_origin,#plant_id,#storage_location_id,#storage_bin_id,#inspection_origin,#stock_type,#ud_code').select2({width:'100%',allowClear:true});
  $('#filter_material').select2({width:'100%',allowClear:true,placeholder:'Cari material...',minimumInputLength:1,ajax:{url:'<?=base_admin();?>modul/inspection_lot/inspection_lot_action.php?act=material_search',type:'POST',dataType:'json',delay:250,data:function(p){return{term:p.term||''};},processResults:function(d){return{results:d.results||[]};}}});
  $('#material_code').select2({width:'100%',dropdownParent:$('#modal_ilot_form'),placeholder:'Cari material...',minimumInputLength:1,ajax:{url:'<?=base_admin();?>modul/inspection_lot/inspection_lot_action.php?act=material_search',type:'POST',dataType:'json',delay:250,data:function(p){return{term:p.term||''};},processResults:function(d){return{results:d.results||[]};}}}).on('select2:select',function(e){$('#material_name').val(e.params.data.name||'');$('#uom').val(e.params.data.uom||'');});
  $('#source_layer_select').select2({width:'100%',dropdownParent:$('#modal_ilot_form'),allowClear:true,placeholder:'Cari stock QUALITY/BLOCKED...',minimumInputLength:0,ajax:{url:'<?=base_admin();?>modul/inspection_lot/inspection_lot_action.php?act=source_search',type:'POST',dataType:'json',delay:250,data:function(p){return{term:p.term||''};},processResults:function(d){return{results:d.results||[]};}}}).on('select2:select',function(e){var d=e.params.data;$('#stock_layer_id').val(d.id);$('#material_name').val(d.material_name);$('#lot_qty').val(d.qty);$('#sample_qty').val(d.qty);$('#uom').val(d.uom);$('#plant_id').val(d.plant_id).trigger('change');$('#storage_location_id').val(d.storage_location_id).trigger('change');$('#storage_bin_id').val(d.storage_bin_id).trigger('change');$('#stock_type').val(d.stock_type).trigger('change');$('#source_ref_type').val(d.source_ref_type);$('#source_ref_id').val(d.source_ref_id);$('#source_ref_no').val(d.source_ref_no);$('#no_aju').val(d.no_aju);$('#jenis_dokpab').val(d.jenis_dokpab);$('#no_dokpab').val(d.no_dokpab);$('#no_bpb').val(d.no_bpb);var opt=new Option(d.material_code+' - '+d.material_name,d.material_code,true,true);$('#material_code').append(opt).trigger('change');});
}
function resetForm(){
  $('#form_ilot')[0].reset();$('#ilot_id,#stock_layer_id,#source_ref_type,#source_ref_id,#source_ref_no,#material_name,#no_aju,#jenis_dokpab,#no_dokpab,#no_bpb').val('');
  $('#lot_no').val('<?=ilot_h($nextNo);?>');$('#source_layer_select,#material_code').val(null).trigger('change');$('#inspection_origin').val('GOODS_RECEIPT').trigger('change');$('#stock_type').val('QUALITY').trigger('change');$('#plant_id,#storage_location_id,#storage_bin_id').val('').trigger('change');
}
function resultRow(){return '<tr><td><input name="characteristic_no[]" class="form-control input-sm"></td><td><input name="characteristic_name[]" class="form-control input-sm"></td><td><input name="specification[]" class="form-control input-sm"></td><td><input name="sample_qty_result[]" class="form-control input-sm text-right" value="0"></td><td><input name="result_value[]" class="form-control input-sm"></td><td><select name="result_status[]" class="form-control input-sm"><option value="PASS">PASS</option><option value="FAIL">FAIL</option><option value="INFO">INFO</option></select></td><td><input name="defect_code[]" class="form-control input-sm"></td><td><input name="defect_qty[]" class="form-control input-sm text-right" value="0"></td><td><input name="remarks_result[]" class="form-control input-sm"></td><td><button type="button" class="btn btn-danger btn-xs btn-remove-result"><i class="fa fa-trash"></i></button></td></tr>';}
$(function(){
  if($.fn.datepicker){$('.ilot-date').datepicker({format:'yyyy-mm-dd',autoclose:true,todayHighlight:true});}
  initISelect();
  var dt=$('#dtb_inspection_lot').DataTable({bProcessing:true,bServerSide:true,pageLength:25,ordering:false,dom:"<'row'<'col-sm-12'B>>"+"<'row'<'col-sm-6'l><'col-sm-6'f>>"+"<'row'<'col-sm-12'tr>>"+"<'row'<'col-sm-5'i><'col-sm-7'p>>",buttons:[{extend:'collection',text:'Export Data',buttons:['copyHtml5','excelHtml5','csvHtml5','pdfHtml5']}],columnDefs:[{targets:[0,1],orderable:false,searchable:false},{targets:[4,5],className:'text-right'},{width:'42px',targets:0},{width:'150px',targets:1}],ajax:{url:'<?=base_admin();?>modul/inspection_lot/inspection_lot_data.php',type:'post',data:function(d){$.extend(d,ilotFilters());},error:function(xhr){console.log(xhr.responseText);ilotError('Data Inspection Lot gagal dimuat.');}}});
  $('#btn_filter_ilot').click(function(){dt.draw();});$('#filter_keyword').keyup(function(e){if(e.keyCode===13)dt.draw();});$('#btn_excel_ilot').click(function(){window.location=ilotExcelUrl();});
  $('#btn_reset_ilot').click(function(){$('#filter_tgl_awal').val('<?=$defaultFrom;?>');$('#filter_tgl_akhir').val('<?=$defaultTo;?>');$('#filter_keyword').val('');$('#filter_material').val(null).trigger('change');$('#filter_plant,#filter_storage_location,#filter_storage_bin,#filter_lot_status,#filter_inspection_origin').val('').trigger('change');dt.draw();});
  $('#btn_add_ilot,#btn_add_ilot_top,#btn_generate_source').click(function(){resetForm();$('#modal_ilot_form').modal('show');});
  $('#btn_save_ilot').click(function(){var btn=$(this);btn.prop('disabled',true).html('<i class="fa fa-spinner fa-spin"></i> Saving...');$.ajax({url:'<?=base_admin();?>modul/inspection_lot/inspection_lot_action.php?act=save',type:'POST',data:$('#form_ilot').serialize(),dataType:'json',success:function(res){btn.prop('disabled',false).html('<i class="fa fa-save"></i> Save Lot');if(res.status==='good'){$('#modal_ilot_form').modal('hide');dt.draw(false);Swal.fire('Success','Inspection lot '+res.lot_no+' tersimpan.','success');}else ilotError(res.error_message);},error:function(xhr){btn.prop('disabled',false).html('<i class="fa fa-save"></i> Save Lot');ilotError(xhr.responseText);}});});
  $(document).on('click','.btn-ilot-detail',function(){$.post('<?=base_admin();?>modul/inspection_lot/inspection_lot_action.php?act=detail',{id:$(this).data('id')},function(html){$('#ilot_detail_body').html(html);$('#modal_ilot_detail').modal('show');}).fail(function(){ilotError('Detail gagal dibuka.');});});
  $(document).on('click','.btn-ilot-edit',function(){var id=$(this).data('id');resetForm();$.post('<?=base_admin();?>modul/inspection_lot/inspection_lot_action.php?act=get',{id:id},function(res){if(res.status!=='good'){ilotError(res.error_message);return;}var d=res.data;$('#ilot_id').val(d.id);$('#lot_no').val(d.lot_no);$('#inspection_origin').val(d.inspection_origin).trigger('change');$('#inspection_type').val(d.inspection_type);$('#material_name').val(d.material_name);var opt=new Option(d.material_code+' - '+d.material_name,d.material_code,true,true);$('#material_code').append(opt).trigger('change');$('#uom').val(d.uom);$('#stock_type').val(d.stock_type).trigger('change');$('#lot_qty').val(d.lot_qty);$('#sample_qty').val(d.sample_qty);$('#batch_no').val(d.batch_no);$('#plant_id').val(d.plant_id).trigger('change');$('#storage_location_id').val(d.storage_location_id).trigger('change');$('#storage_bin_id').val(d.storage_bin_id).trigger('change');$('#inspection_plan').val(d.inspection_plan);$('#notes').val(d.notes);$('#source_ref_type').val(d.source_ref_type);$('#source_ref_id').val(d.source_ref_id);$('#source_ref_no').val(d.source_ref_no);$('#stock_layer_id').val(d.stock_layer_id);$('#no_aju').val(d.no_aju);$('#jenis_dokpab').val(d.jenis_dokpab);$('#no_dokpab').val(d.no_dokpab);$('#no_bpb').val(d.no_bpb);$('#modal_ilot_form').modal('show');},'json').fail(function(xhr){ilotError(xhr.responseText);});});
  $(document).on('click','.btn-ilot-result',function(){var id=$(this).data('id');$.post('<?=base_admin();?>modul/inspection_lot/inspection_lot_action.php?act=result_form',{id:id},function(html){$('#ilot_result_body').html(html);$('#modal_ilot_result').modal('show');}).fail(function(){ilotError('Form result gagal dibuka.');});});
  $(document).on('click','.btn-ilot-start',function(){var id=$(this).data('id'),no=$(this).data('no');Swal.fire({title:'Start inspection?',text:no+' akan berubah menjadi IN_INSPECTION.',icon:'question',showCancelButton:true,confirmButtonText:'Start'}).then(function(r){if(!r.isConfirmed)return;$.post('<?=base_admin();?>modul/inspection_lot/inspection_lot_action.php?act=start',{id:id},function(res){if(res.status==='good'){dt.draw(false);Swal.fire('Success','Inspection dimulai.','success');}else ilotError(res.error_message);},'json').fail(function(xhr){ilotError(xhr.responseText);});});});
  $(document).on('click','#btn_add_result_row',function(){$('#tbl_ilot_result tbody').append(resultRow());});$(document).on('click','.btn-remove-result',function(){$(this).closest('tr').remove();});
  $('#btn_save_result').click(function(){var btn=$(this);btn.prop('disabled',true).html('<i class="fa fa-spinner fa-spin"></i> Saving...');$.ajax({url:'<?=base_admin();?>modul/inspection_lot/inspection_lot_action.php?act=record_result',type:'POST',data:$('#form_ilot_result').serialize(),dataType:'json',success:function(res){btn.prop('disabled',false).html('<i class="fa fa-check-square-o"></i> Save Result');if(res.status==='good'){$('#modal_ilot_result').modal('hide');dt.draw(false);Swal.fire('Success','Inspection result tersimpan.','success');}else ilotError(res.error_message);},error:function(xhr){btn.prop('disabled',false).html('<i class="fa fa-check-square-o"></i> Save Result');ilotError(xhr.responseText);}});});
  $(document).on('click','.btn-ilot-ud',function(){var id=$(this).data('id');$.post('<?=base_admin();?>modul/inspection_lot/inspection_lot_action.php?act=ud_form',{id:id},function(html){$('#ilot_ud_body').html(html);initISelect();$('#modal_ilot_ud').modal('show');}).fail(function(){ilotError('Form UD gagal dibuka.');});});
  $('#btn_save_ud').click(function(){Swal.fire({title:'Post Usage Decision?',text:'UD akan memfinalisasi inspection lot.',icon:'question',showCancelButton:true,confirmButtonText:'Post UD'}).then(function(r){if(!r.isConfirmed)return;$.ajax({url:'<?=base_admin();?>modul/inspection_lot/inspection_lot_action.php?act=usage_decision',type:'POST',data:$('#form_ilot_ud').serialize(),dataType:'json',success:function(res){if(res.status==='good'){$('#modal_ilot_ud').modal('hide');dt.draw(false);Swal.fire('Success','Usage decision berhasil diposting.','success');}else ilotError(res.error_message);},error:function(xhr){ilotError(xhr.responseText);}});});});
  $(document).on('click','.btn-ilot-cancel',function(){var id=$(this).data('id'),no=$(this).data('no');Swal.fire({title:'Cancel '+no+'?',input:'text',inputLabel:'Reason cancel',showCancelButton:true,confirmButtonText:'Cancel Lot',inputValidator:function(v){return !v?'Reason wajib diisi':undefined;}}).then(function(r){if(!r.isConfirmed)return;$.post('<?=base_admin();?>modul/inspection_lot/inspection_lot_action.php?act=cancel',{id:id,reason:r.value},function(res){if(res.status==='good'){dt.draw(false);Swal.fire('Success','Inspection lot dibatalkan.','success');}else ilotError(res.error_message);},'json').fail(function(xhr){ilotError(xhr.responseText);});});});
  $(document).on('click','.hide_alert_notif',function(){$('.error_data_delete').hide();});
});
</script>
