<?php
if (!function_exists('prod_t')) {
  function prod_t($key, $fallback = '') { return lang_text($key, $fallback); }
}
if (!function_exists('prod_h')) {
  function prod_h($key, $fallback = '') { return htmlspecialchars((string) prod_t($key, $fallback), ENT_QUOTES, 'UTF-8'); }
}
if (!function_exists('prod_js')) {
  function prod_js($key, $fallback = '') { return json_encode(prod_t($key, $fallback), JSON_HEX_TAG | JSON_HEX_APOS | JSON_HEX_AMP | JSON_HEX_QUOT); }
}
$defaultFrom=date('Y-m-01');$defaultTo=date('Y-m-t');$today=date('Y-m-d');
$plants=$db->query("SELECT id,plant_code,plant_name FROM erp_plant WHERE status='Aktif' ORDER BY plant_code");
?>
<style>
.mrq-hero{background:linear-gradient(135deg,#1d4ed8,#0f766e);color:#fff;border-radius:14px;padding:20px;margin-bottom:18px;box-shadow:0 10px 24px rgba(15,23,42,.16)}.mrq-hero h1{margin:0 0 6px;font-size:26px;font-weight:700}.mrq-hero p{margin:0;opacity:.92}.mrq-card{border-radius:12px;background:#fff;border:1px solid #e5edf5;box-shadow:0 5px 16px rgba(15,23,42,.05);margin-bottom:14px}.mrq-items th,.mrq-items td,#dtb_material_requirement th,#dtb_material_requirement td{font-size:12px;vertical-align:middle}.select2-container{width:100%!important}.required-label:after{content:' *';color:#dd4b39}.mrq-action{white-space:nowrap}.mrq-source-box{background:#f8fafc;border:1px solid #e2e8f0;border-radius:10px;padding:10px;margin-bottom:10px}.mrq-pill{display:inline-block;border-radius:999px;background:#e0f2fe;color:#075985;padding:3px 9px;font-size:12px;margin-left:6px}
#modal_mrq .modal-dialog{margin-top:12px;margin-bottom:12px}
#modal_mrq .modal-body{max-height:calc(100vh - 185px);overflow-y:auto;overflow-x:hidden}
#modal_mrq .table-responsive{overflow-x:auto!important;overflow-y:visible!important}
#modal_mrq .mrq-items{min-width:1550px;margin-bottom:0}
</style>
<section class="content-header"><h1>Material Requirement <small>SAP PP Requirement Workbench</small></h1><ol class="breadcrumb"><li><a href="<?=base_index();?>"><i class="fa fa-dashboard"></i> <?=prod_h('common_home', 'Home');?></a></li><li class="active">Material Requirement</li></ol></section>
<section class="content">
  <div class="mrq-hero"><div class="row"><div class="col-md-8"><h1>Material Requirement Workbench</h1><p>Konversi shortage MRP atau kebutuhan Production Order menjadi dokumen requirement untuk staging, PR/PO, dan issue produksi.</p></div><div class="col-md-4 text-right"><button id="btn_open_mrq" class="btn btn-warning"><i class="fa fa-plus"></i> Create Requirement</button></div></div></div>
  <div class="box mrq-card"><div class="box-header"><h3 class="box-title"><i class="fa fa-filter"></i> Filter Requirement</h3></div><div class="box-body"><form class="form-horizontal" onsubmit="return false;"><div class="form-group"><label class="control-label col-lg-2"><?=prod_h('production_period', 'Period');?></label><div class="col-lg-2"><div class="input-group date mrq-date"><input id="filter_tgl_awal" class="form-control" value="<?=$defaultFrom;?>"><span class="input-group-addon"><span class="glyphicon glyphicon-calendar"></span></span></div></div><div class="col-lg-2"><div class="input-group date mrq-date"><input id="filter_tgl_akhir" class="form-control" value="<?=$defaultTo;?>"><span class="input-group-addon"><span class="glyphicon glyphicon-calendar"></span></span></div></div><label class="control-label col-lg-1"><?=prod_h('production_plant', 'Plant');?></label><div class="col-lg-2"><select id="filter_plant" class="form-control"><option value=""><?=prod_h('common_all', 'All');?></option><?php foreach($plants as $p){ ?><option value="<?=htmlspecialchars($p->plant_code,ENT_QUOTES,'UTF-8');?>"><?=htmlspecialchars($p->plant_code.' - '.$p->plant_name,ENT_QUOTES,'UTF-8');?></option><?php } ?></select></div><label class="control-label col-lg-1"><?=prod_h('common_status', 'Status');?></label><div class="col-lg-2"><select id="filter_status" class="form-control"><option value=""><?=prod_h('common_all', 'All');?></option><option>DRAFT</option><option>SUBMITTED</option><option>APPROVED</option><option>STAGED</option><option>ISSUED</option><option>CLOSED</option><option>CANCELLED</option></select></div></div><div class="form-group"><label class="control-label col-lg-2"><?=prod_h('production_type', 'Type');?></label><div class="col-lg-2"><select id="filter_type" class="form-control"><option value=""><?=prod_h('common_all', 'All');?></option><option><?=prod_h('production_mrp', 'MRP');?></option><option>PRODUCTION_ORDER</option><option>MANUAL</option><option>SALES_ORDER</option><option>DEMAND_PLAN</option></select></div><label class="control-label col-lg-1"><?=prod_h('common_search', 'Search');?></label><div class="col-lg-4"><input id="filter_keyword" class="form-control" placeholder="Requirement / MRP / Production Order / material"></div><div class="col-lg-3"><button id="btn_filter_mrq" class="btn btn-primary"><i class="fa fa-filter"></i> <?=prod_h('common_filter', 'Filter');?></button> <button id="btn_reset_mrq" class="btn btn-default"><i class="fa fa-refresh"></i> <?=prod_h('common_reset', 'Reset');?></button> <button id="btn_export_mrq" class="btn btn-success"><i class="fa fa-file-excel-o"></i> <?=prod_h('common_export_excel', 'Export Excel');?></button></div></div></form></div></div>
  <div class="box mrq-card"><div class="box-body"><div class="alert alert-warning error_data_delete" style="display:none"><button type="button" class="close hide_alert_notif">&times;</button><span class="isi_warning_delete"></span></div><div class="table-responsive"><table id="dtb_material_requirement" class="table table-bordered table-striped" style="width:100%"><thead><tr><th><?=prod_h('common_no', 'No');?></th><th><?=prod_h('common_action', 'Action');?></th><th>Requirement</th><th><?=prod_h('production_date', 'Date');?></th><th><?=prod_h('production_plant', 'Plant');?></th><th><?=prod_h('production_source', 'Source');?></th><th><?=prod_h('production_items', 'Items');?></th><th>Required Qty</th><th>Open Qty</th><th><?=prod_h('common_status', 'Status');?></th><th>Requestor</th></tr></thead><tbody></tbody></table></div></div></div>
  <div id="modal_mrq" class="modal fade"><div class="modal-dialog modal-lg" style="width:97%"><div class="modal-content"><form id="form_mrq"><input type="hidden" name="id" id="mrq_id"><input type="hidden" name="source_mrp_no" id="source_mrp_no"><input type="hidden" name="source_production_order_no" id="source_production_order_no"><div class="modal-header"><button class="close" data-dismiss="modal">&times;</button><h4 class="modal-title">Create Material Requirement</h4></div><div class="modal-body">
    <div class="alert alert-info">Gunakan <strong>Load from MRP</strong> untuk shortage planning normal. Gunakan <strong>Load from Production Order</strong> untuk kebutuhan order produksi. Manual wajib mengisi reason.</div>
    <div class="row"><div class="col-md-2 form-group"><label><?=prod_h('production_type', 'Type');?></label><select name="requirement_type" id="requirement_type" class="form-control"><option value="MRP"><?=prod_h('production_mrp', 'MRP');?></option><option value="PRODUCTION_ORDER"><?=prod_h('production_order', 'Production Order');?></option><option value="MANUAL">Manual</option><option value="SALES_ORDER">Sales Order</option><option value="DEMAND_PLAN">Demand Plan</option></select></div><div class="col-md-2 form-group"><label class="required-label">Req Date</label><input name="requirement_date" id="requirement_date" class="form-control date-field" value="<?=$today;?>" required></div><div class="col-md-2 form-group"><label>Required From</label><input name="required_from" id="required_from" class="form-control date-field" value="<?=$today;?>"></div><div class="col-md-2 form-group"><label>Required To</label><input name="required_to" id="required_to" class="form-control date-field" value="<?=$defaultTo;?>"></div><div class="col-md-2 form-group"><label><?=prod_h('production_plant', 'Plant');?></label><select id="plant_id" name="plant_id" class="form-control"><option value="">All Plant</option><?php foreach($db->query("SELECT id,plant_code,plant_name FROM erp_plant WHERE status='Aktif' ORDER BY plant_code") as $p){ ?><option value="<?=intval($p->id);?>" data-code="<?=htmlspecialchars($p->plant_code,ENT_QUOTES,'UTF-8');?>"><?=htmlspecialchars($p->plant_code.' - '.$p->plant_name,ENT_QUOTES,'UTF-8');?></option><?php } ?></select><input type="hidden" name="plant_code" id="plant_code"></div><div class="col-md-2 form-group"><label>Priority</label><select name="priority" id="priority" class="form-control"><option>NORMAL</option><option>LOW</option><option>HIGH</option><option>URGENT</option></select></div></div>
    <div class="row"><div class="col-md-3 form-group"><label>MRP Run</label><select id="source_mrp_id" name="source_mrp_id" class="form-control"></select></div><div class="col-md-3 form-group"><label><?=prod_h('production_order', 'Production Order');?></label><select id="source_production_order_id" name="source_production_order_id" class="form-control"></select></div><div class="col-md-2 form-group"><label>Requestor</label><input name="requestor" id="requestor" class="form-control" value="<?=htmlspecialchars(isset($_SESSION['username'])?$_SESSION['username']:'',ENT_QUOTES,'UTF-8');?>"></div><div class="col-md-2 form-group"><label>Department</label><input name="department" id="department" class="form-control" placeholder="PPIC / Produksi"></div><div class="col-md-2 form-group"><label>Source Ref</label><input name="source_ref" id="source_ref" class="form-control"></div></div>
    <div class="mrq-source-box"><button type="button" id="btn_load_mrp" class="btn btn-info"><i class="fa fa-download"></i> Load from MRP</button> <button type="button" id="btn_load_po" class="btn btn-primary"><i class="fa fa-industry"></i> Load from Production Order</button> <button type="button" id="btn_add_line" class="btn btn-default"><i class="fa fa-plus"></i> Add Manual Line</button> <span class="mrq-pill">Approved requirement menjadi dasar staging / issue / PR</span></div>
    <div class="row"><div class="col-md-5 form-group"><label>Reason <span class="text-danger manual-reason-note" style="display:none">*</span></label><input name="reason" id="reason" class="form-control" placeholder="Wajib untuk manual requirement"></div><div class="col-md-7 form-group"><label><?=prod_h('common_remarks', 'Remarks');?></label><input name="remarks" id="remarks" class="form-control" placeholder="Catatan planning / produksi"></div></div>
    <div class="table-responsive"><table class="table table-bordered table-condensed mrq-items"><thead><tr><th style="width:44px">#</th><th style="width:230px"><?=prod_h('production_material', 'Material');?></th><th>Description</th><th style="width:110px">Req Date</th><th style="width:120px">Required Qty</th><th style="width:110px">Stock</th><th style="width:70px"><?=prod_h('production_uom', 'UOM');?></th><th style="width:115px">Proc.</th><th style="width:130px"><?=prod_h('production_source', 'Source');?></th><th>Source Ref / Parent</th><th>Storage Loc</th><th><?=prod_h('common_remarks', 'Remarks');?></th></tr></thead><tbody id="mrq_lines"></tbody></table></div>
  </div><div class="modal-footer"><button type="button" class="btn btn-default" data-dismiss="modal"><?=prod_h('common_cancel', 'Cancel');?></button><button type="submit" class="btn btn-primary"><i class="fa fa-save"></i> <?=prod_h('production_save_requirement', 'Save Requirement');?></button></div></form></div></div></div>
  <div id="modal_mrq_detail" class="modal fade"><div class="modal-dialog modal-lg" style="width:96%"><div class="modal-content"><div class="modal-header"><button class="close" data-dismiss="modal">&times;</button><h4 class="modal-title">Requirement Detail</h4></div><div class="modal-body" id="mrq_detail_body"></div><div class="modal-footer"><button class="btn btn-default" data-dismiss="modal"><?=prod_h('common_close', 'Close');?></button></div></div></div></div>
</section>
<script src="<?=base_admin();?>assets/plugins/select2/select2.min.js"></script><script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
<script>
function mrqError(m){$('.isi_warning_delete').text(m||<?=prod_js('production_material_requirement_process_failed', 'Material Requirement failed to process.');?>);$('.error_data_delete').fadeIn();}
function esc(s){return String(s||'').replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c];});}
function nval(v){var x=parseFloat(String(v||0).replace(',','.'));return isNaN(x)?0:x;}
var lineNo=0;
function initMaterialSelect(el){if(!$.fn.select2)return;el.select2({width:'100%',dropdownParent:$('#modal_mrq'),placeholder:'Cari material...',minimumInputLength:1,ajax:{url:'<?=base_admin();?>modul/material_requirement/material_requirement_action.php?act=material_search',type:'POST',dataType:'json',delay:250,data:function(p){return{term:p.term||''};},processResults:function(d){return{results:d.results||[]};}}}).on('select2:select',function(e){var d=e.params.data,tr=$(this).closest('tr');tr.find('input[name="material_name[]"]').val(d.material_name||'');tr.find('input[name="material_type[]"]').val(d.material_type||'');tr.find('input[name="uom[]"]').val(d.uom||'');});}
function appendLine(x){lineNo++;x=x||{};var rowId='mrq_line_'+lineNo,matOpt=x.material_code?'<option value="'+esc(x.material_code)+'" selected>'+esc(x.material_code+' - '+(x.material_name||''))+'</option>':'';var row='<tr id="'+rowId+'"><td class="text-center"><button type="button" class="btn btn-xs btn-danger btn-mrq-remove-line"><i class="fa fa-trash"></i></button></td><td><select name="material_code[]" class="form-control mrq-material" required>'+matOpt+'</select><input type="hidden" name="material_type[]" value="'+esc(x.material_type||'')+'"></td><td><input name="material_name[]" class="form-control" value="'+esc(x.material_name||'')+'" readonly></td><td><input name="required_date[]" class="form-control date-field" value="'+esc(x.required_date||$('#required_from').val()||$('#requirement_date').val())+'" required></td><td><input type="number" step="0.00001" min="0.00001" name="required_qty[]" class="form-control text-right" value="'+esc(x.required_qty||'')+'" required></td><td><input type="number" step="0.00001" name="available_stock[]" class="form-control text-right" value="'+esc(x.available_stock||0)+'" readonly></td><td><input name="uom[]" class="form-control" value="'+esc(x.uom||'')+'" readonly></td><td><select name="procurement_type[]" class="form-control"><option value="EXTERNAL" '+(x.procurement_type==='EXTERNAL'?'selected':'')+'>External</option><option value="IN_HOUSE" '+(x.procurement_type==='IN_HOUSE'?'selected':'')+'>In-house</option><option value="BOTH" '+(x.procurement_type==='BOTH'?'selected':'')+'>Both</option></select></td><td><input name="source_type[]" class="form-control" value="'+esc(x.source_type||$('#requirement_type').val()||'MANUAL')+'" readonly><input type="hidden" name="source_line_id[]" value="'+esc(x.source_line_id||'')+'"></td><td><input name="source_ref_line[]" class="form-control" value="'+esc(x.source_ref||'')+'" placeholder="Source Ref"><input name="parent_material_code[]" class="form-control" value="'+esc(x.parent_material_code||'')+'" placeholder="Parent Material"></td><td><input name="storage_location[]" class="form-control" value="'+esc(x.storage_location||'')+'"></td><td><input name="line_remarks[]" class="form-control" value="'+esc(x.remarks||'')+'"></td></tr>';$('#mrq_lines').append(row);initMaterialSelect($('#'+rowId+' .mrq-material'));if($.fn.datepicker)$('#'+rowId+' .date-field').datepicker({format:'yyyy-mm-dd',autoclose:true,todayHighlight:true});}
function filters(){return{tgl_awal:$('#filter_tgl_awal').val(),tgl_akhir:$('#filter_tgl_akhir').val(),status:$('#filter_status').val(),type:$('#filter_type').val(),plant:$('#filter_plant').val(),keyword:$('#filter_keyword').val()};}
function openForm(title){lineNo=0;$('#form_mrq')[0].reset();$('#mrq_id,#source_mrp_no,#source_production_order_no').val('');$('#mrq_lines').html('');$('#source_mrp_id,#source_production_order_id').val(null).trigger('change');$('#plant_id').val('').trigger('change');$('#modal_mrq .modal-title').text(title||'Create Material Requirement');appendLine();toggleReason();$('#modal_mrq').modal({backdrop:'static',keyboard:false});}
function toggleReason(){var isManual=$('#requirement_type').val()==='MANUAL';$('.manual-reason-note').toggle(isManual);$('#reason').prop('required',isManual);}
$(function(){if($.fn.datepicker){$('.mrq-date,.date-field').datepicker({format:'yyyy-mm-dd',autoclose:true,todayHighlight:true});}if($.fn.select2){$('#filter_plant,#filter_status,#filter_type,#plant_id,#requirement_type,#priority').select2({width:'100%'});$('#source_mrp_id').select2({width:'100%',placeholder:'Cari released MRP...',allowClear:true,dropdownParent:$('#modal_mrq'),ajax:{url:'<?=base_admin();?>modul/material_requirement/material_requirement_action.php?act=mrp_search',type:'POST',dataType:'json',delay:250,data:function(p){return{term:p.term||''};},processResults:function(d){return{results:d.results||[]};}}}).on('select2:select',function(e){var d=e.params.data;$('#source_mrp_no').val(d.mrp_no||'');$('#required_from').val(d.period_from||$('#required_from').val());$('#required_to').val(d.period_to||$('#required_to').val());$('#requirement_type').val('MRP').trigger('change');});$('#source_production_order_id').select2({width:'100%',placeholder:'Cari production order...',allowClear:true,dropdownParent:$('#modal_mrq'),ajax:{url:'<?=base_admin();?>modul/material_requirement/material_requirement_action.php?act=production_order_search',type:'POST',dataType:'json',delay:250,data:function(p){return{term:p.term||''};},processResults:function(d){return{results:d.results||[]};}}}).on('select2:select',function(e){var d=e.params.data;$('#source_production_order_no').val(d.no_production_order||'');$('#plant_code').val(d.plant_code||'');$('#requirement_type').val('PRODUCTION_ORDER').trigger('change');});}
var dt=null;function reloadTable(resetPaging){if(dt&&dt.draw)dt.draw(resetPaging===false?false:undefined);}
try{if($.fn.DataTable){dt=$('#dtb_material_requirement').DataTable({bProcessing:true,bServerSide:true,pageLength:25,dom:"<'row'<'col-sm-12'B>>"+"<'row'<'col-sm-6'l><'col-sm-6'f>>"+"<'row'<'col-sm-12'tr>>"+"<'row'<'col-sm-5'i><'col-sm-7'p>>",buttons:[{extend:'collection',text:<?=prod_js('common_export_data', 'Export Data');?>,buttons:['copyHtml5','excelHtml5','csvHtml5','pdfHtml5']}],columnDefs:[{targets:[0,1],orderable:false,searchable:false},{targets:[7,8],className:'text-right'},{width:'42px',targets:0},{width:'160px',targets:1}],ajax:{url:'<?=base_admin();?>modul/material_requirement/material_requirement_data.php',type:'post',data:function(d){$.extend(d,filters());},error:function(xhr){console.log(xhr.responseText);mrqError(<?=prod_js('production_material_requirement_load_failed', 'Material Requirement data failed to load.');?>);}}});}}catch(e){console.error(e);mrqError(<?=prod_js('production_material_requirement_load_failed_create_available', 'Material Requirement data failed to load. Create button remains available.');?>);}
$('#btn_open_mrq').click(function(){openForm('Create Material Requirement');});$('#requirement_type').change(toggleReason);$('#plant_id').change(function(){$('#plant_code').val($('#plant_id option:selected').data('code')||'');});$('#btn_add_line').click(function(){appendLine({source_type:'MANUAL'});});$(document).on('click','.btn-mrq-remove-line',function(){$(this).closest('tr').remove();});
$('#btn_load_mrp').click(function(){var id=$('#source_mrp_id').val();if(!id){mrqError('Pilih MRP RELEASED dulu.');return;}$.post('<?=base_admin();?>modul/material_requirement/material_requirement_action.php?act=mrp_lines',{mrp_id:id},function(r){if(r.status==='good'){$('#mrq_lines').html('');lineNo=0;$('#source_mrp_no').val(r.source_mrp_no||'');$('#required_from').val(r.period_from||$('#required_from').val());$('#required_to').val(r.period_to||$('#required_to').val());$('#plant_code').val(r.plant_code||'');(r.lines||[]).forEach(appendLine);if(!(r.lines||[]).length)mrqError('MRP tidak punya shortage open.');}else mrqError(r.error_message);},'json').fail(function(xhr){mrqError(xhr.responseText);});});
$('#btn_load_po').click(function(){var id=$('#source_production_order_id').val();if(!id){mrqError('Pilih Production Order dulu.');return;}$.post('<?=base_admin();?>modul/material_requirement/material_requirement_action.php?act=production_order_lines',{production_order_id:id},function(r){if(r.status==='good'){$('#mrq_lines').html('');lineNo=0;$('#source_production_order_no').val(r.source_production_order_no||'');$('#required_from').val(r.period_from||$('#required_from').val());$('#required_to').val(r.period_to||$('#required_to').val());$('#plant_code').val(r.plant_code||'');(r.lines||[]).forEach(appendLine);if(!(r.lines||[]).length)mrqError('Production Order tidak punya material open.');}else mrqError(r.error_message);},'json').fail(function(xhr){mrqError(xhr.responseText);});});
$('#btn_filter_mrq').click(function(){reloadTable();});$('#filter_keyword').keyup(function(e){if(e.keyCode===13)reloadTable();});$('#btn_reset_mrq').click(function(){$('#filter_tgl_awal').val('<?=$defaultFrom;?>');$('#filter_tgl_akhir').val('<?=$defaultTo;?>');$('#filter_status,#filter_type,#filter_plant').val('').trigger('change');$('#filter_keyword').val('');reloadTable();});$('#btn_export_mrq').click(function(){window.location='<?=base_admin();?>modul/material_requirement/material_requirement_action.php?act=excel&'+$.param(filters());});
$('#form_mrq').submit(function(e){e.preventDefault();var btn=$(this).find('button[type=submit]');btn.prop('disabled',true).html('<i class="fa fa-spinner fa-spin"></i> <?=prod_h('common_saving', 'Saving...');?>');$.post('<?=base_admin();?>modul/material_requirement/material_requirement_action.php?act=save',$(this).serialize(),function(r){if(r.status==='good'){$('#modal_mrq').modal('hide');reloadTable(false);}else mrqError(r.error_message);btn.prop('disabled',false).html('<i class="fa fa-save"></i> <?=prod_h('production_save_requirement', 'Save Requirement');?>');},'json').fail(function(xhr){mrqError(xhr.responseText);btn.prop('disabled',false).html('<i class="fa fa-save"></i> <?=prod_h('production_save_requirement', 'Save Requirement');?>');});});
$(document).on('click','.btn-mrq-detail',function(){$.post('<?=base_admin();?>modul/material_requirement/material_requirement_action.php?act=detail',{id:$(this).data('id')},function(html){$('#mrq_detail_body').html(html);$('#modal_mrq_detail').modal('show');});});
$(document).on('click','.btn-mrq-edit',function(){var id=$(this).data('id');$.post('<?=base_admin();?>modul/material_requirement/material_requirement_action.php?act=get',{id:id},function(r){if(r.status!=='good'){mrqError(r.error_message);return;}openForm('Edit Material Requirement');var h=r.header||{};$('#mrq_id').val(h.id);$('#requirement_type').val(h.requirement_type).trigger('change');$('#requirement_date').val(h.requirement_date);$('#required_from').val(h.required_from);$('#required_to').val(h.required_to);$('#plant_id').val(h.plant_id||'').trigger('change');$('#plant_code').val(h.plant_code||'');$('#source_mrp_no').val(h.source_mrp_no||'');$('#source_production_order_no').val(h.source_production_order_no||'');$('#source_ref').val(h.source_ref||'');$('#requestor').val(h.requestor||'');$('#department').val(h.department||'');$('#priority').val(h.priority||'NORMAL').trigger('change');$('#reason').val(h.reason||'');$('#remarks').val(h.remarks||'');$('#mrq_lines').html('');lineNo=0;(r.lines||[]).forEach(appendLine);},'json');});
function statusAction(act,id,no,title,input){var cfg={title:title,text:no,icon:'question',showCancelButton:true,confirmButtonText:title};if(input){cfg.input='text';cfg.inputLabel='Reason '+no;cfg.inputValidator=function(v){return !v?<?=prod_js('production_reason_required', 'Reason is required');?>:undefined;};}Swal.fire(cfg).then(function(x){if(!x.isConfirmed)return;var data={id:id};if(input)data.reason=x.value;$.post('<?=base_admin();?>modul/material_requirement/material_requirement_action.php?act='+act,data,function(r){if(r.status==='good')reloadTable(false);else mrqError(r.error_message);},'json');});}
$(document).on('click','.btn-mrq-submit',function(){statusAction('submit',$(this).data('id'),$(this).data('no'),'Submit');});$(document).on('click','.btn-mrq-approve',function(){statusAction('approve',$(this).data('id'),$(this).data('no'),'Approve');});$(document).on('click','.btn-mrq-cancel',function(){statusAction('cancel',$(this).data('id'),$(this).data('no'),'Cancel',true);});$(document).on('click','.btn-mrq-delete',function(){statusAction('delete',$(this).data('id'),$(this).data('no'),'Delete');});$('.hide_alert_notif').click(function(){$('.error_data_delete').hide();});
});
</script>
