<?php
include_once "quality_notification_lib.php";
$defaultFrom = date('Y-m-01');
$defaultTo = date('Y-m-d');
$kpi = qn_kpi($db);
$users = qn_responsible_users($db);
$nextNo = qn_next_number(date('Y-m-d'));
?>
<style>
.qn-hero{background:linear-gradient(135deg,#0f172a,#b91c1c);color:#fff;border-radius:14px;padding:21px 22px;margin-bottom:18px;box-shadow:0 10px 24px rgba(15,23,42,.18)}
.qn-hero h1{margin:0 0 6px;font-size:26px;font-weight:700}.qn-hero p{margin:0;opacity:.92}
.qn-kpi{border-radius:12px;background:#fff;border:1px solid #e5edf5;padding:15px;margin-bottom:14px;box-shadow:0 4px 14px rgba(15,23,42,.05)}
.qn-kpi span{display:block;color:#64748b;font-size:12px;text-transform:uppercase;letter-spacing:.04em}.qn-kpi strong{display:block;font-size:23px;margin-top:6px;color:#111827}.qn-kpi i{float:right;font-size:26px;color:#b91c1c;opacity:.55}
.qn-card{border-radius:12px;border:1px solid #e5edf5;box-shadow:0 5px 16px rgba(15,23,42,.05)}.qn-filter .form-group{margin-bottom:12px}
#dtb_quality_notification th,#dtb_quality_notification td{font-size:12px;vertical-align:middle}.select2-container{width:100%!important}.qn-modal .modal-body{max-height:72vh;overflow:auto}
.qn-help{color:#64748b;margin-top:6px}
</style>
<section class="content-header">
  <h1>Quality Notification / NCR <small>SAP QM Nonconformance</small></h1>
  <ol class="breadcrumb"><li><a href="<?=base_index();?>"><i class="fa fa-dashboard"></i> Home</a></li><li><a href="<?=base_index();?>quality-dashboard">Quality Management</a></li><li class="active">Quality Notification / NCR</li></ol>
</section>
<section class="content">
  <div class="qn-hero"><div class="row"><div class="col-md-8"><h1>Quality Notification / NCR Workbench</h1><p>Catat nonconformance dari failed inspection, data NG, supplier/customer/internal defect, lalu kelola containment, root cause, corrective dan preventive action.</p></div><div class="col-md-4 text-right"><button id="btn_add_qn_top" class="btn btn-info"><i class="fa fa-plus"></i> Create NCR</button> <button id="btn_excel_qn_top" class="btn btn-success"><i class="fa fa-file-excel-o"></i> Export</button></div></div></div>
  <div class="row">
    <div class="col-sm-3"><div class="qn-kpi"><i class="fa fa-list"></i><span>Total NCR</span><strong><?=number_format((float)$kpi->total,0,',','.');?></strong></div></div>
    <div class="col-sm-3"><div class="qn-kpi"><i class="fa fa-folder-open"></i><span>Open NCR</span><strong><?=number_format((float)$kpi->open_count,0,',','.');?></strong></div></div>
    <div class="col-sm-3"><div class="qn-kpi"><i class="fa fa-warning"></i><span>Critical</span><strong><?=number_format((float)$kpi->critical_count,0,',','.');?></strong></div></div>
    <div class="col-sm-3"><div class="qn-kpi"><i class="fa fa-clock-o"></i><span>Overdue</span><strong><?=number_format((float)$kpi->overdue_count,0,',','.');?></strong></div></div>
  </div>
  <div class="box qn-card"><div class="box-header with-border"><h3 class="box-title"><i class="fa fa-filter"></i> Filter NCR</h3></div><div class="box-body">
    <form class="form-horizontal qn-filter" onsubmit="return false;">
      <div class="form-group"><label class="control-label col-lg-2">Created Date</label><div class="col-lg-2"><div class="input-group date qn-date"><input id="filter_tgl_awal" class="form-control" value="<?=$defaultFrom;?>" autocomplete="off"><span class="input-group-addon"><span class="glyphicon glyphicon-calendar"></span></span></div></div><div class="col-lg-2"><div class="input-group date qn-date"><input id="filter_tgl_akhir" class="form-control" value="<?=$defaultTo;?>" autocomplete="off"><span class="input-group-addon"><span class="glyphicon glyphicon-calendar"></span></span></div></div><label class="control-label col-lg-1">Material</label><div class="col-lg-5"><select id="filter_material" class="form-control"></select></div></div>
      <div class="form-group"><label class="control-label col-lg-2">Status</label><div class="col-lg-2"><select id="filter_status" class="form-control"><option value="">Semua</option><option>OPEN</option><option>IN_REVIEW</option><option>CONTAINED</option><option>CAPA_REQUIRED</option><option>CAPA_IN_PROGRESS</option><option>CLOSED</option><option>CANCELLED</option></select></div><label class="control-label col-lg-2">Severity</label><div class="col-lg-2"><select id="filter_severity" class="form-control"><option value="">Semua</option><option>LOW</option><option>MEDIUM</option><option>HIGH</option><option>CRITICAL</option></select></div><label class="control-label col-lg-1">Source</label><div class="col-lg-3"><select id="filter_source_type" class="form-control"><option value="">Semua</option><option>INSPECTION_LOT</option><option>NG</option><option>MANUAL</option><option>CUSTOMER</option><option>SUPPLIER</option><option>AUDIT</option></select></div></div>
      <div class="form-group"><label class="control-label col-lg-2">Responsible</label><div class="col-lg-3"><select id="filter_responsible_user" class="form-control"><option value="">Semua</option><?php foreach($users as $u){ ?><option value="<?=ilot_h($u->username);?>"><?=ilot_h($u->username);?></option><?php } ?></select></div><label class="control-label col-lg-1">Search</label><div class="col-lg-4"><input id="filter_keyword" class="form-control" placeholder="NCR, material, source, problem, BC"></div><div class="col-lg-2"><button id="btn_filter_qn" class="btn btn-primary"><i class="fa fa-filter"></i> Filter</button> <button id="btn_reset_qn" class="btn btn-default"><i class="fa fa-refresh"></i></button></div></div>
      <div class="form-group"><div class="col-lg-offset-2 col-lg-10"><button id="btn_add_qn" class="btn btn-info"><i class="fa fa-plus"></i> Create NCR</button> <button id="btn_excel_qn" class="btn btn-success"><i class="fa fa-file-excel-o"></i> Export Excel</button></div></div>
    </form>
  </div></div>
  <div class="box qn-card"><div class="box-body"><div class="alert alert-warning error_data_delete" style="display:none"><button type="button" class="close hide_alert_notif">&times;</button><i class="icon fa fa-warning"></i> <span class="isi_warning_delete"></span></div><div class="table-responsive"><table id="dtb_quality_notification" class="table table-bordered table-striped table-condensed" style="width:100%"><thead><tr><th>No</th><th>Action</th><th>NCR</th><th>Material</th><th>Defect Qty</th><th>Severity</th><th>Status</th><th>Defect</th><th>Source / Location</th><th>Responsible</th><th>Created</th></tr></thead><tbody></tbody></table></div></div></div>
  <div id="modal_qn_form" class="modal fade qn-modal"><div class="modal-dialog modal-lg" style="width:96%"><div class="modal-content"><div class="modal-header"><button class="close" data-dismiss="modal">&times;</button><h4 class="modal-title">Quality Notification / NCR</h4></div><div class="modal-body">
    <form id="form_qn" class="form-horizontal">
      <input type="hidden" name="id" id="qn_id"><input type="hidden" name="material_name" id="material_name"><input type="hidden" name="source_ref_id" id="source_ref_id"><input type="hidden" name="source_ref_no" id="source_ref_no"><input type="hidden" name="inspection_lot_id" id="inspection_lot_id"><input type="hidden" name="plant_id" id="plant_id"><input type="hidden" name="storage_location_id" id="storage_location_id"><input type="hidden" name="storage_bin_id" id="storage_bin_id"><input type="hidden" name="no_aju" id="no_aju"><input type="hidden" name="jenis_dokpab" id="jenis_dokpab"><input type="hidden" name="no_dokpab" id="no_dokpab"><input type="hidden" name="no_bpb" id="no_bpb">
      <div class="alert alert-info"><strong>SAP QM hint:</strong> NCR dapat dibuat dari failed inspection characteristic, data NG lama, atau manual untuk kasus customer/supplier/internal/audit.</div>
      <div class="form-group"><label class="control-label col-sm-2">Failed Inspection</label><div class="col-sm-4"><select id="inspection_candidate" class="form-control"></select><div class="qn-help">Pilih jika NCR berasal dari inspection lot gagal.</div></div><label class="control-label col-sm-2">Legacy NG</label><div class="col-sm-4"><select id="ng_candidate" class="form-control"></select></div></div>
      <div class="form-group"><label class="control-label col-sm-2">NCR No</label><div class="col-sm-2"><input name="notification_no" id="notification_no" class="form-control" value="<?=ilot_h($nextNo);?>"></div><label class="control-label col-sm-2">Type</label><div class="col-sm-2"><select name="notification_type" id="notification_type" class="form-control"><option>NCR</option><option>CUSTOMER_COMPLAINT</option><option>SUPPLIER_DEFECT</option><option>INTERNAL_DEFECT</option><option>AUDIT_FINDING</option></select></div><label class="control-label col-sm-2">Source</label><div class="col-sm-2"><select name="source_type" id="source_type" class="form-control"><option>MANUAL</option><option>INSPECTION_LOT</option><option>NG</option><option>CUSTOMER</option><option>SUPPLIER</option><option>AUDIT</option></select></div></div>
      <div class="form-group"><label class="control-label col-sm-2">Material</label><div class="col-sm-5"><select name="material_code" id="material_code" class="form-control"></select></div><label class="control-label col-sm-1">Qty</label><div class="col-sm-2"><input name="defect_qty" id="defect_qty" class="form-control text-right" value="0"></div><div class="col-sm-2"><input name="uom" id="uom" class="form-control" placeholder="UOM"></div></div>
      <div class="form-group"><label class="control-label col-sm-2">Severity</label><div class="col-sm-2"><select name="severity" id="severity" class="form-control"><option>LOW</option><option selected>MEDIUM</option><option>HIGH</option><option>CRITICAL</option></select></div><label class="control-label col-sm-2">Priority</label><div class="col-sm-2"><select name="priority" id="priority" class="form-control"><option>LOW</option><option selected>NORMAL</option><option>HIGH</option><option>URGENT</option></select></div><label class="control-label col-sm-2">Status</label><div class="col-sm-2"><select name="status" id="status" class="form-control"><option>OPEN</option><option>IN_REVIEW</option><option>CONTAINED</option><option>CAPA_REQUIRED</option><option>CAPA_IN_PROGRESS</option><option>CLOSED</option><option>CANCELLED</option></select></div></div>
      <div class="form-group"><label class="control-label col-sm-2">Category</label><div class="col-sm-3"><input name="defect_category" id="defect_category" class="form-control" placeholder="Visual / Dimensi / Dokumen / Proses"></div><label class="control-label col-sm-2">Defect Code</label><div class="col-sm-2"><input name="defect_code" id="defect_code" class="form-control"></div><label class="control-label col-sm-1">Due</label><div class="col-sm-2"><div class="input-group date qn-date"><input name="due_date" id="due_date" class="form-control" autocomplete="off"><span class="input-group-addon"><span class="glyphicon glyphicon-calendar"></span></span></div></div></div>
      <div class="form-group"><label class="control-label col-sm-2">Responsible</label><div class="col-sm-4"><select name="responsible_user" id="responsible_user" class="form-control"><option value="">-</option><?php foreach($users as $u){ ?><option value="<?=ilot_h($u->username);?>"><?=ilot_h($u->username);?></option><?php } ?></select></div><label class="control-label col-sm-2">Problem</label><div class="col-sm-4"><textarea name="defect_description" id="defect_description" class="form-control" rows="2"></textarea></div></div>
      <div class="form-group"><label class="control-label col-sm-2">Containment</label><div class="col-sm-4"><textarea name="containment_action" id="containment_action" class="form-control" rows="2"></textarea></div><label class="control-label col-sm-2">Root Cause</label><div class="col-sm-4"><textarea name="root_cause" id="root_cause" class="form-control" rows="2"></textarea></div></div>
      <div class="form-group"><label class="control-label col-sm-2">Corrective</label><div class="col-sm-4"><textarea name="corrective_action" id="corrective_action" class="form-control" rows="2"></textarea></div><label class="control-label col-sm-2">Preventive</label><div class="col-sm-4"><textarea name="preventive_action" id="preventive_action" class="form-control" rows="2"></textarea></div></div>
    </form>
  </div><div class="modal-footer"><button class="btn btn-default" data-dismiss="modal">Close</button><button id="btn_save_qn" class="btn btn-primary"><i class="fa fa-save"></i> Save NCR</button></div></div></div></div>
  <div id="modal_qn_detail" class="modal fade qn-modal"><div class="modal-dialog modal-lg" style="width:96%"><div class="modal-content"><div class="modal-header"><button class="close" data-dismiss="modal">&times;</button><h4 class="modal-title">NCR Detail</h4></div><div class="modal-body" id="qn_detail_body"></div><div class="modal-footer"><button class="btn btn-default" data-dismiss="modal">Close</button></div></div></div></div>
  <div id="modal_qn_action" class="modal fade qn-modal"><div class="modal-dialog modal-lg"><div class="modal-content"><div class="modal-header"><button class="close" data-dismiss="modal">&times;</button><h4 class="modal-title">NCR Action</h4></div><div class="modal-body" id="qn_action_body"></div><div class="modal-footer"><button class="btn btn-default" data-dismiss="modal">Close</button><button id="btn_save_qn_action" class="btn btn-warning"><i class="fa fa-tasks"></i> Save Action</button></div></div></div></div>
</section>
<script src="<?=base_admin();?>assets/plugins/select2/select2.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
<script>
function qnError(m){$('.isi_warning_delete').text(m||'Quality Notification gagal diproses.');$('.error_data_delete').fadeIn();}
function qnFilters(){return{tgl_awal:$('#filter_tgl_awal').val(),tgl_akhir:$('#filter_tgl_akhir').val(),material_code:$('#filter_material').val(),status:$('#filter_status').val(),severity:$('#filter_severity').val(),source_type:$('#filter_source_type').val(),responsible_user:$('#filter_responsible_user').val(),keyword:$('#filter_keyword').val()};}
function qnExcelUrl(){return '<?=base_admin();?>modul/quality_notification/quality_notification_action.php?act=excel&'+$.param(qnFilters());}
function qnInitSelect(){if(!$.fn.select2)return;$('#filter_status,#filter_severity,#filter_source_type,#filter_responsible_user,#notification_type,#source_type,#severity,#priority,#status,#responsible_user,#qn_action_status').select2({width:'100%',allowClear:true});$('#filter_material').select2({width:'100%',allowClear:true,placeholder:'Cari material...',minimumInputLength:1,ajax:{url:'<?=base_admin();?>modul/quality_notification/quality_notification_action.php?act=material_search',type:'POST',dataType:'json',delay:250,data:function(p){return{term:p.term||''};},processResults:function(d){return{results:d.results||[]};}}});$('#material_code').select2({width:'100%',dropdownParent:$('#modal_qn_form'),placeholder:'Cari material...',minimumInputLength:1,ajax:{url:'<?=base_admin();?>modul/quality_notification/quality_notification_action.php?act=material_search',type:'POST',dataType:'json',delay:250,data:function(p){return{term:p.term||''};},processResults:function(d){return{results:d.results||[]};}}}).on('select2:select',function(e){$('#material_name').val(e.params.data.name||'');$('#uom').val(e.params.data.uom||'');});$('#inspection_candidate').select2({width:'100%',dropdownParent:$('#modal_qn_form'),placeholder:'Cari failed inspection...',minimumInputLength:0,ajax:{url:'<?=base_admin();?>modul/quality_notification/quality_notification_action.php?act=inspection_candidate',type:'POST',dataType:'json',delay:250,data:function(p){return{term:p.term||''};},processResults:function(d){return{results:d.results||[]};}}}).on('select2:select',function(e){fillFromCandidate(e.params.data,'INSPECTION_LOT');});$('#ng_candidate').select2({width:'100%',dropdownParent:$('#modal_qn_form'),placeholder:'Cari data NG...',minimumInputLength:0,ajax:{url:'<?=base_admin();?>modul/quality_notification/quality_notification_action.php?act=ng_candidate',type:'POST',dataType:'json',delay:250,data:function(p){return{term:p.term||''};},processResults:function(d){return{results:d.results||[]};}}}).on('select2:select',function(e){fillFromCandidate(e.params.data,'NG');});}
function resetQnForm(){$('#form_qn')[0].reset();$('#qn_id,#material_name,#source_ref_id,#source_ref_no,#inspection_lot_id,#plant_id,#storage_location_id,#storage_bin_id,#no_aju,#jenis_dokpab,#no_dokpab,#no_bpb').val('');$('#notification_no').val('<?=ilot_h($nextNo);?>');$('#material_code,#inspection_candidate,#ng_candidate').val(null).trigger('change');$('#notification_type').val('NCR').trigger('change');$('#source_type').val('MANUAL').trigger('change');$('#severity').val('MEDIUM').trigger('change');$('#priority').val('NORMAL').trigger('change');$('#status').val('OPEN').trigger('change');}
function fillFromCandidate(d,source){$('#source_type').val(source).trigger('change');$('#source_ref_id').val(d.id);$('#source_ref_no').val(d.source_ref_no||'');$('#inspection_lot_id').val(d.inspection_lot_id||'');$('#material_name').val(d.material_name||'');$('#defect_qty').val(d.defect_qty||0);$('#uom').val(d.uom||'');$('#defect_code').val(d.defect_code||'');$('#defect_description').val(d.defect_description||'');$('#plant_id').val(d.plant_id||'');$('#storage_location_id').val(d.storage_location_id||'');$('#storage_bin_id').val(d.storage_bin_id||'');$('#no_aju').val(d.no_aju||'');$('#jenis_dokpab').val(d.jenis_dokpab||'');$('#no_dokpab').val(d.no_dokpab||'');$('#no_bpb').val(d.no_bpb||'');var opt=new Option((d.material_code||'')+' - '+(d.material_name||''),d.material_code,true,true);$('#material_code').append(opt).trigger('change');}
$(function(){
  if($.fn.datepicker){$('.qn-date').datepicker({format:'yyyy-mm-dd',autoclose:true,todayHighlight:true});}
  qnInitSelect();
  var dt=$('#dtb_quality_notification').DataTable({bProcessing:true,bServerSide:true,pageLength:25,ordering:false,dom:"<'row'<'col-sm-12'B>>"+"<'row'<'col-sm-6'l><'col-sm-6'f>>"+"<'row'<'col-sm-12'tr>>"+"<'row'<'col-sm-5'i><'col-sm-7'p>>",buttons:[{extend:'collection',text:'Export Data',buttons:['copyHtml5','excelHtml5','csvHtml5','pdfHtml5']}],columnDefs:[{targets:[0,1],orderable:false,searchable:false},{targets:[4],className:'text-right'},{width:'42px',targets:0},{width:'105px',targets:1}],ajax:{url:'<?=base_admin();?>modul/quality_notification/quality_notification_data.php',type:'post',data:function(d){$.extend(d,qnFilters());},error:function(xhr){console.log(xhr.responseText);qnError('Data NCR gagal dimuat.');}}});
  $('#btn_filter_qn').click(function(){dt.draw();});$('#filter_keyword').keyup(function(e){if(e.keyCode===13)dt.draw();});$('#btn_excel_qn,#btn_excel_qn_top').click(function(){window.location=qnExcelUrl();});
  $('#btn_reset_qn').click(function(){$('#filter_tgl_awal').val('<?=$defaultFrom;?>');$('#filter_tgl_akhir').val('<?=$defaultTo;?>');$('#filter_keyword').val('');$('#filter_material').val(null).trigger('change');$('#filter_status,#filter_severity,#filter_source_type,#filter_responsible_user').val('').trigger('change');dt.draw();});
  $('#btn_add_qn,#btn_add_qn_top').click(function(){resetQnForm();$('#modal_qn_form').modal('show');});
  $('#btn_save_qn').click(function(){var btn=$(this);btn.prop('disabled',true).html('<i class="fa fa-spinner fa-spin"></i> Saving...');$.ajax({url:'<?=base_admin();?>modul/quality_notification/quality_notification_action.php?act=save',type:'POST',data:$('#form_qn').serialize(),dataType:'json',success:function(res){btn.prop('disabled',false).html('<i class="fa fa-save"></i> Save NCR');if(res.status==='good'){$('#modal_qn_form').modal('hide');dt.draw(false);Swal.fire('Success','NCR '+res.notification_no+' tersimpan.','success');}else qnError(res.error_message);},error:function(xhr){btn.prop('disabled',false).html('<i class="fa fa-save"></i> Save NCR');qnError(xhr.responseText);}});});
  $(document).on('click','.btn-qn-detail',function(){$.post('<?=base_admin();?>modul/quality_notification/quality_notification_action.php?act=detail',{id:$(this).data('id')},function(html){$('#qn_detail_body').html(html);$('#modal_qn_detail').modal('show');}).fail(function(){qnError('Detail NCR gagal dibuka.');});});
  $(document).on('click','.btn-qn-action',function(){$.post('<?=base_admin();?>modul/quality_notification/quality_notification_action.php?act=action_form',{id:$(this).data('id')},function(html){$('#qn_action_body').html(html);qnInitSelect();$('#modal_qn_action').modal('show');}).fail(function(){qnError('Form action gagal dibuka.');});});
  $(document).on('click','.btn-qn-edit',function(){resetQnForm();$.post('<?=base_admin();?>modul/quality_notification/quality_notification_action.php?act=get',{id:$(this).data('id')},function(res){if(res.status!=='good'){qnError(res.error_message);return;}var d=res.data;$('#qn_id').val(d.id);$('#notification_no').val(d.notification_no);$('#notification_type').val(d.notification_type).trigger('change');$('#source_type').val(d.source_type).trigger('change');$('#source_ref_id').val(d.source_ref_id);$('#source_ref_no').val(d.source_ref_no);$('#inspection_lot_id').val(d.inspection_lot_id);$('#material_name').val(d.material_name);var opt=new Option(d.material_code+' - '+d.material_name,d.material_code,true,true);$('#material_code').append(opt).trigger('change');$('#defect_qty').val(d.defect_qty);$('#uom').val(d.uom);$('#severity').val(d.severity).trigger('change');$('#priority').val(d.priority).trigger('change');$('#status').val(d.status).trigger('change');$('#defect_category').val(d.defect_category);$('#defect_code').val(d.defect_code);$('#due_date').val(d.due_date);$('#responsible_user').val(d.responsible_user).trigger('change');$('#defect_description').val(d.defect_description);$('#containment_action').val(d.containment_action);$('#root_cause').val(d.root_cause);$('#corrective_action').val(d.corrective_action);$('#preventive_action').val(d.preventive_action);$('#plant_id').val(d.plant_id);$('#storage_location_id').val(d.storage_location_id);$('#storage_bin_id').val(d.storage_bin_id);$('#no_aju').val(d.no_aju);$('#jenis_dokpab').val(d.jenis_dokpab);$('#no_dokpab').val(d.no_dokpab);$('#no_bpb').val(d.no_bpb);$('#modal_qn_form').modal('show');},'json').fail(function(xhr){qnError(xhr.responseText);});});
  $('#btn_save_qn_action').click(function(){var btn=$(this);btn.prop('disabled',true).html('<i class="fa fa-spinner fa-spin"></i> Saving...');$.ajax({url:'<?=base_admin();?>modul/quality_notification/quality_notification_action.php?act=post_action',type:'POST',data:$('#form_qn_action').serialize(),dataType:'json',success:function(res){btn.prop('disabled',false).html('<i class="fa fa-tasks"></i> Save Action');if(res.status==='good'){$('#modal_qn_action').modal('hide');dt.draw(false);Swal.fire('Success','Action NCR tersimpan.','success');}else qnError(res.error_message);},error:function(xhr){btn.prop('disabled',false).html('<i class="fa fa-tasks"></i> Save Action');qnError(xhr.responseText);}});});
  $('.hide_alert_notif').click(function(){$('.error_data_delete').hide();});
});
</script>
