<?php
include_once "usage_decision_lib.php";
$defaultFrom = date('Y-m-01');
$defaultTo = date('Y-m-d');
$kpi = ud_kpi($db);
$nextNo = ud_next_number(date('Y-m-d'));
?>
<style>
.ud-hero{background:linear-gradient(135deg,#111827,#7c2d12);color:#fff;border-radius:14px;padding:21px 22px;margin-bottom:18px;box-shadow:0 10px 24px rgba(15,23,42,.18)}
.ud-hero h1{margin:0 0 6px;font-size:26px;font-weight:700}.ud-hero p{margin:0;opacity:.92}
.ud-kpi{border-radius:12px;background:#fff;border:1px solid #e5edf5;padding:15px;margin-bottom:14px;box-shadow:0 4px 14px rgba(15,23,42,.05)}
.ud-kpi span{display:block;color:#64748b;font-size:12px;text-transform:uppercase;letter-spacing:.04em}.ud-kpi strong{display:block;font-size:23px;margin-top:6px;color:#111827}.ud-kpi i{float:right;font-size:26px;color:#c2410c;opacity:.55}
.ud-card{border-radius:12px;border:1px solid #e5edf5;box-shadow:0 5px 16px rgba(15,23,42,.05)}.ud-filter .form-group{margin-bottom:12px}
#dtb_ud_pending th,#dtb_ud_pending td,#dtb_ud_posted th,#dtb_ud_posted td{font-size:12px;vertical-align:middle}.select2-container{width:100%!important}.ud-modal .modal-body{max-height:72vh;overflow:auto}
.ud-help{color:#64748b;margin-top:6px}.ud-mode-tabs{margin-bottom:14px}
</style>
<section class="content-header">
  <h1>Usage Decision <small>SAP QM UD</small></h1>
  <ol class="breadcrumb"><li><a href="<?=base_index();?>"><i class="fa fa-dashboard"></i> Home</a></li><li><a href="<?=base_index();?>quality-dashboard">Quality Management</a></li><li class="active">Usage Decision</li></ol>
</section>
<section class="content">
  <div class="ud-hero"><div class="row"><div class="col-md-8"><h1>Usage Decision Workbench</h1><p>Finalisasi inspection lot: release stock, block/reject, partial accept, rework, return to vendor, atau scrap dengan jejak dokumen BC tetap terbawa.</p></div><div class="col-md-4 text-right"><button type="button" id="btn_add_ud_top" class="btn btn-warning"><i class="fa fa-gavel"></i> Post UD</button> <button type="button" id="btn_excel_ud_top" class="btn btn-success"><i class="fa fa-file-excel-o"></i> Export</button></div></div></div>
  <div class="row">
    <div class="col-sm-3"><div class="ud-kpi"><i class="fa fa-hourglass-half"></i><span>Pending Lot</span><strong><?=number_format((float)$kpi->pending_lot,0,',','.');?></strong></div></div>
    <div class="col-sm-3"><div class="ud-kpi"><i class="fa fa-calendar-check-o"></i><span>UD Today</span><strong><?=number_format((float)$kpi->today_ud,0,',','.');?></strong></div></div>
    <div class="col-sm-3"><div class="ud-kpi"><i class="fa fa-warning"></i><span>Exception UD</span><strong><?=number_format((float)$kpi->exception_ud,0,',','.');?></strong></div></div>
    <div class="col-sm-3"><div class="ud-kpi"><i class="fa fa-cubes"></i><span>Stock Posted</span><strong><?=number_format((float)$kpi->posted_ud,0,',','.');?></strong></div></div>
  </div>
  <div class="box ud-card"><div class="box-header with-border"><h3 class="box-title"><i class="fa fa-filter"></i> Filter Usage Decision</h3></div><div class="box-body">
    <form class="form-horizontal ud-filter" onsubmit="return false;">
      <div class="form-group"><label class="control-label col-lg-2">Decision Date</label><div class="col-lg-2"><div class="input-group date ud-date"><input id="filter_tgl_awal" class="form-control" value="<?=$defaultFrom;?>" autocomplete="off"><span class="input-group-addon"><span class="glyphicon glyphicon-calendar"></span></span></div></div><div class="col-lg-2"><div class="input-group date ud-date"><input id="filter_tgl_akhir" class="form-control" value="<?=$defaultTo;?>" autocomplete="off"><span class="input-group-addon"><span class="glyphicon glyphicon-calendar"></span></span></div></div><label class="control-label col-lg-1">Origin</label><div class="col-lg-2"><select id="filter_inspection_origin" class="form-control"><option value="">Semua</option><option>GOODS_RECEIPT</option><option>PRODUCTION</option><option>MANUAL</option><option>TRANSFER</option><option>RETURN</option></select></div><label class="control-label col-lg-1">Decision</label><div class="col-lg-2"><select id="filter_decision_code" class="form-control"><option value="">Semua</option><option value="A">Accept</option><option value="R">Reject</option><option value="P">Partial</option><option value="RW">Rework</option><option value="RTV">Return Vendor</option><option value="SCRAP">Scrap</option></select></div></div>
      <div class="form-group"><label class="control-label col-lg-2">Stock Posted</label><div class="col-lg-2"><select id="filter_stock_posted" class="form-control"><option value="">Semua</option><option>Y</option><option>N</option></select></div><label class="control-label col-lg-1">Search</label><div class="col-lg-5"><input id="filter_keyword" class="form-control" placeholder="UD, lot, material, source, dokumen BC"></div><div class="col-lg-2"><button type="button" id="btn_filter_ud" class="btn btn-primary"><i class="fa fa-filter"></i> Filter</button> <button type="button" id="btn_reset_ud" class="btn btn-default"><i class="fa fa-refresh"></i></button></div></div>
      <div class="form-group"><div class="col-lg-offset-2 col-lg-10"><button type="button" id="btn_add_ud" class="btn btn-warning"><i class="fa fa-gavel"></i> Post Usage Decision</button> <button type="button" id="btn_excel_ud" class="btn btn-success"><i class="fa fa-file-excel-o"></i> Export Excel</button></div></div>
    </form>
  </div></div>
  <div class="nav-tabs-custom ud-card">
    <ul class="nav nav-tabs ud-mode-tabs"><li class="active"><a href="#tab_pending_ud" data-toggle="tab"><i class="fa fa-hourglass-half"></i> Pending Inspection Lots</a></li><li><a href="#tab_posted_ud" data-toggle="tab"><i class="fa fa-check"></i> Posted Usage Decisions</a></li></ul>
    <div class="tab-content"><div class="alert alert-warning error_data_delete" style="display:none"><button type="button" class="close hide_alert_notif">&times;</button><i class="icon fa fa-warning"></i> <span class="isi_warning_delete"></span></div>
      <div class="tab-pane active" id="tab_pending_ud"><div class="table-responsive"><table id="dtb_ud_pending" class="table table-bordered table-striped table-condensed" style="width:100%"><thead><tr><th>No</th><th>Action</th><th>Lot</th><th>Material</th><th>Lot Qty</th><th>Defect</th><th>Status</th><th>Location</th><th>Source / BC</th><th>Created</th></tr></thead><tbody></tbody></table></div></div>
      <div class="tab-pane" id="tab_posted_ud"><div class="table-responsive"><table id="dtb_ud_posted" class="table table-bordered table-striped table-condensed" style="width:100%"><thead><tr><th>No</th><th>Action</th><th>UD / Lot</th><th>Material</th><th>Decision</th><th>Accepted</th><th>Rejected</th><th>Posting</th><th>Location</th><th>Decision At</th></tr></thead><tbody></tbody></table></div></div>
    </div>
  </div>
  <div id="modal_ud_form" class="modal fade ud-modal"><div class="modal-dialog modal-lg" style="width:96%"><div class="modal-content"><div class="modal-header"><button class="close" data-dismiss="modal">&times;</button><h4 class="modal-title">Post Usage Decision</h4></div><div class="modal-body">
    <form id="form_ud" class="form-horizontal">
      <input type="hidden" name="inspection_lot_id" id="inspection_lot_id"><input type="hidden" id="lot_qty_raw"><input type="hidden" id="fail_count_raw">
      <div class="alert alert-info"><strong>SAP QM hint:</strong> UD adalah final decision inspection lot. Setelah diposting, lot menjadi final dan stock effect hanya dibuat sekali.</div>
      <div class="form-group"><label class="control-label col-sm-2">Inspection Lot</label><div class="col-sm-6"><select id="lot_candidate" class="form-control"></select><div class="ud-help">Pilih lot yang sudah siap usage decision.</div></div><label class="control-label col-sm-2">UD No</label><div class="col-sm-2"><input name="ud_no" id="ud_no" class="form-control" value="<?=ud_h($nextNo);?>"></div></div>
      <div class="form-group"><label class="control-label col-sm-2">Material</label><div class="col-sm-4"><input id="material_text" class="form-control" readonly></div><label class="control-label col-sm-2">Lot Qty</label><div class="col-sm-2"><input id="lot_qty_display" class="form-control text-right" readonly></div><div class="col-sm-2"><input id="uom_display" class="form-control" readonly></div></div>
      <div class="form-group"><label class="control-label col-sm-2">Decision *</label><div class="col-sm-3"><select name="decision_code" id="decision_code" class="form-control"><option value="">Pilih</option><option value="A">Accept / Release</option><option value="R">Reject / Block</option><option value="P">Partial Accept</option><option value="RW">Rework</option><option value="RTV">Return to Vendor</option><option value="SCRAP">Scrap</option></select></div><label class="control-label col-sm-2">Accepted Qty</label><div class="col-sm-2"><input name="accepted_qty" id="accepted_qty" class="form-control text-right" value="0"></div><label class="control-label col-sm-1">Reject</label><div class="col-sm-2"><input name="rejected_qty" id="rejected_qty" class="form-control text-right" value="0"></div></div>
      <div class="form-group"><label class="control-label col-sm-2">Reason</label><div class="col-sm-3"><select name="reason_code" id="reason_code" class="form-control"><option value="INSPECTION_OK">Inspection OK</option><option value="MINOR_DEFECT_ACCEPTED">Minor Defect Accepted</option><option value="QUALITY_REJECT">Quality Reject</option><option value="REWORK_REQUIRED">Rework Required</option><option value="SUPPLIER_RETURN">Supplier Return</option><option value="SCRAP_DECISION">Scrap Decision</option><option value="OTHER">Other</option></select></div><label class="control-label col-sm-2">Stock Effect</label><div class="col-sm-5"><input id="stock_effect_text" class="form-control" readonly value="-"></div></div>
      <div class="form-group"><label class="control-label col-sm-2">Notes</label><div class="col-sm-10"><textarea name="notes" id="notes" class="form-control" rows="3" placeholder="Catatan keputusan, evidence, atau instruksi follow-up"></textarea></div></div>
    </form>
  </div><div class="modal-footer"><span id="ud_submit_help" class="text-muted pull-left">Pilih lot dan decision untuk posting UD.</span><button class="btn btn-default" data-dismiss="modal">Close</button><button id="btn_save_ud" class="btn btn-warning" disabled><i class="fa fa-gavel"></i> Post UD</button></div></div></div></div>
  <div id="modal_ud_detail" class="modal fade ud-modal"><div class="modal-dialog modal-lg" style="width:96%"><div class="modal-content"><div class="modal-header"><button class="close" data-dismiss="modal">&times;</button><h4 class="modal-title">Usage Decision Detail</h4></div><div class="modal-body" id="ud_detail_body"></div><div class="modal-footer"><button class="btn btn-default" data-dismiss="modal">Close</button></div></div></div></div>
  <div id="modal_ud_lot_detail" class="modal fade ud-modal"><div class="modal-dialog modal-lg" style="width:96%"><div class="modal-content"><div class="modal-header"><button class="close" data-dismiss="modal">&times;</button><h4 class="modal-title">Inspection Lot Detail</h4></div><div class="modal-body" id="ud_lot_detail_body"></div><div class="modal-footer"><button class="btn btn-default" data-dismiss="modal">Close</button></div></div></div></div>
</section>
<script src="<?=base_admin();?>assets/plugins/select2/select2.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
<script>
function udError(m){$('.isi_warning_delete').text(m||'Usage Decision gagal diproses.');$('.error_data_delete').fadeIn();}
function udFilters(){return{tgl_awal:$('#filter_tgl_awal').val(),tgl_akhir:$('#filter_tgl_akhir').val(),inspection_origin:$('#filter_inspection_origin').val(),decision_code:$('#filter_decision_code').val(),stock_posted:$('#filter_stock_posted').val(),keyword:$('#filter_keyword').val()};}
function udExcelUrl(){return '<?=base_admin();?>modul/usage_decision/usage_decision_action.php?act=excel&'+$.param(udFilters());}
function n(v){return parseFloat(String(v||'0').replace(',','.'))||0;}
function fmt(v){return (Math.round(n(v)*100000)/100000).toString();}
function updateUdState(){var lot=$('#inspection_lot_id').val(),code=$('#decision_code').val(),acc=n($('#accepted_qty').val()),rej=n($('#rejected_qty').val()),lotQty=n($('#lot_qty_raw').val()),ok=!!lot&&!!code&&acc>=0&&rej>=0&&(acc+rej)>0&&(acc+rej)<=lotQty+0.00001;if(code==='A'&&rej>0)ok=false;if(['R','RW','RTV','SCRAP'].indexOf(code)>=0&&acc>0)ok=false;if(code==='P'&&(acc<=0||rej<=0))ok=false;$('#btn_save_ud').prop('disabled',!ok);$('#ud_submit_help').toggleClass('text-danger',!ok).text(ok?'Siap posting usage decision.':'Lengkapi lot, decision, dan qty sesuai rule UD.');var txt='-';if(code==='A')txt='321: QUALITY/BLOCKED -> UNRESTRICTED';else if(code==='R'||code==='RW')txt='350: QUALITY -> BLOCKED';else if(code==='P')txt='Split: accepted UNRESTRICTED, rejected BLOCKED';else if(code==='RTV')txt='Follow-up Return to Vendor, stock diblokir';else if(code==='SCRAP')txt='Follow-up Scrap Issue, stock diblokir';$('#stock_effect_text').val(txt);}
function resetUdForm(){$('#form_ud')[0].reset();$('#inspection_lot_id,#lot_qty_raw,#fail_count_raw').val('');$('#ud_no').val('<?=ud_h($nextNo);?>');$('#lot_candidate').val(null).trigger('change');$('#material_text,#lot_qty_display,#uom_display').val('');$('#decision_code').val('').trigger('change');$('#reason_code').val('INSPECTION_OK').trigger('change');updateUdState();}
function fillLot(d){$('#inspection_lot_id').val(d.id);$('#lot_qty_raw').val(d.lot_qty||0);$('#fail_count_raw').val(d.fail_count||0);$('#material_text').val((d.material_code||'')+' - '+(d.material_name||''));$('#lot_qty_display').val(d.lot_qty||0);$('#uom_display').val(d.uom||'');var suggested=d.suggested_decision||'A';$('#decision_code').val(suggested).trigger('change');if(suggested==='A'){$('#accepted_qty').val(d.lot_qty||0);$('#rejected_qty').val(0);$('#reason_code').val('INSPECTION_OK').trigger('change');}else{$('#accepted_qty').val(Math.max(0,n(d.lot_qty)-n(d.defect_qty)));$('#rejected_qty').val(n(d.defect_qty)>0?d.defect_qty:0);$('#reason_code').val('MINOR_DEFECT_ACCEPTED').trigger('change');}updateUdState();}
function initUdSelect(){if(!$.fn.select2)return;$('#filter_inspection_origin,#filter_decision_code,#filter_stock_posted,#decision_code,#reason_code').select2({width:'100%',allowClear:true});$('#lot_candidate').select2({width:'100%',dropdownParent:$('#modal_ud_form'),placeholder:'Cari inspection lot...',minimumInputLength:0,ajax:{url:'<?=base_admin();?>modul/usage_decision/usage_decision_action.php?act=lot_candidate',type:'POST',dataType:'json',delay:250,data:function(p){return{term:p.term||''};},processResults:function(d){return{results:d.results||[]};}}}).on('select2:select',function(e){fillLot(e.params.data);});}
$(function(){
  if($.fn.datepicker){$('.ud-date').datepicker({format:'yyyy-mm-dd',autoclose:true,todayHighlight:true});}
  initUdSelect();
  var pending=$('#dtb_ud_pending').DataTable({bProcessing:true,bServerSide:true,pageLength:25,ordering:false,dom:"<'row'<'col-sm-12'B>>"+"<'row'<'col-sm-6'l><'col-sm-6'f>>"+"<'row'<'col-sm-12'tr>>"+"<'row'<'col-sm-5'i><'col-sm-7'p>>",buttons:[{extend:'collection',text:'Export Data',buttons:['copyHtml5','excelHtml5','csvHtml5','pdfHtml5']}],columnDefs:[{targets:[0,1],orderable:false,searchable:false},{targets:[4,5],className:'text-right'},{width:'42px',targets:0},{width:'85px',targets:1}],ajax:{url:'<?=base_admin();?>modul/usage_decision/usage_decision_data.php',type:'post',data:function(d){$.extend(d,udFilters());d.mode='pending';},error:function(xhr){console.log(xhr.responseText);udError('Data pending lot gagal dimuat.');}}});
  var posted=$('#dtb_ud_posted').DataTable({bProcessing:true,bServerSide:true,pageLength:25,ordering:false,dom:"<'row'<'col-sm-12'B>>"+"<'row'<'col-sm-6'l><'col-sm-6'f>>"+"<'row'<'col-sm-12'tr>>"+"<'row'<'col-sm-5'i><'col-sm-7'p>>",buttons:[{extend:'collection',text:'Export Data',buttons:['copyHtml5','excelHtml5','csvHtml5','pdfHtml5']}],columnDefs:[{targets:[0,1],orderable:false,searchable:false},{targets:[5,6],className:'text-right'},{width:'42px',targets:0},{width:'55px',targets:1}],ajax:{url:'<?=base_admin();?>modul/usage_decision/usage_decision_data.php',type:'post',data:function(d){$.extend(d,udFilters());d.mode='posted';},error:function(xhr){console.log(xhr.responseText);udError('Data posted UD gagal dimuat.');}}});
  $('a[data-toggle="tab"]').on('shown.bs.tab',function(){pending.columns.adjust();posted.columns.adjust();});
  $('#btn_filter_ud').click(function(){pending.draw();posted.draw();});$('#filter_keyword').keyup(function(e){if(e.keyCode===13){pending.draw();posted.draw();}});$('#btn_excel_ud,#btn_excel_ud_top').click(function(){window.location=udExcelUrl();});
  $('#btn_reset_ud').click(function(){$('#filter_tgl_awal').val('<?=$defaultFrom;?>');$('#filter_tgl_akhir').val('<?=$defaultTo;?>');$('#filter_keyword').val('');$('#filter_inspection_origin,#filter_decision_code,#filter_stock_posted').val('').trigger('change');pending.draw();posted.draw();});
  $('#btn_add_ud,#btn_add_ud_top').click(function(){resetUdForm();$('#modal_ud_form').modal('show');});
  $(document).on('click','.btn-ud-post',function(){resetUdForm();var id=$(this).data('id');$.post('<?=base_admin();?>modul/usage_decision/usage_decision_action.php?act=lot_candidate',{term:''},function(res){var chosen=null;(res.results||[]).forEach(function(x){if(String(x.id)===String(id))chosen=x;});if(chosen){var opt=new Option(chosen.text,chosen.id,true,true);$('#lot_candidate').append(opt).trigger('change');fillLot(chosen);}$('#modal_ud_form').modal('show');},'json').fail(function(){ $('#inspection_lot_id').val(id); $('#modal_ud_form').modal('show'); });});
  $(document).on('click','.btn-ud-lot-detail',function(){$.post('<?=base_admin();?>modul/usage_decision/usage_decision_action.php?act=lot_detail',{id:$(this).data('id')},function(html){$('#ud_lot_detail_body').html(html);$('#modal_ud_lot_detail').modal('show');}).fail(function(){udError('Detail lot gagal dibuka.');});});
  $(document).on('click','.btn-ud-detail',function(){$.post('<?=base_admin();?>modul/usage_decision/usage_decision_action.php?act=detail',{id:$(this).data('id')},function(html){$('#ud_detail_body').html(html);$('#modal_ud_detail').modal('show');}).fail(function(){udError('Detail UD gagal dibuka.');});});
  $('#decision_code,#accepted_qty,#rejected_qty').on('change keyup',updateUdState);
  $('#btn_save_ud').click(function(){if($(this).prop('disabled'))return;Swal.fire({title:'Post Usage Decision?',text:'UD akan memfinalisasi inspection lot dan membuat stock effect jika ada stock layer.',icon:'question',showCancelButton:true,confirmButtonText:'Post UD'}).then(function(r){if(!r.isConfirmed)return;var btn=$('#btn_save_ud');btn.prop('disabled',true).html('<i class="fa fa-spinner fa-spin"></i> Posting...');$.ajax({url:'<?=base_admin();?>modul/usage_decision/usage_decision_action.php?act=post',type:'POST',data:$('#form_ud').serialize(),dataType:'json',success:function(res){btn.html('<i class="fa fa-gavel"></i> Post UD');updateUdState();if(res.status==='good'){$('#modal_ud_form').modal('hide');pending.draw(false);posted.draw(false);Swal.fire('Success','Usage Decision '+res.ud_no+' berhasil diposting.','success');}else udError(res.error_message);},error:function(xhr){btn.html('<i class="fa fa-gavel"></i> Post UD');updateUdState();udError(xhr.responseText);}});});});
  $('.hide_alert_notif').click(function(){$('.error_data_delete').hide();});
});
</script>
