<?php
if (!function_exists('hr_t')) {
  function hr_t($key, $fallback = '') { return lang_text($key, $fallback); }
}
if (!function_exists('hr_h')) {
  function hr_h($key, $fallback = '') { return htmlspecialchars((string) hr_t($key, $fallback), ENT_QUOTES, 'UTF-8'); }
}
if (!function_exists('hr_js')) {
  function hr_js($key, $fallback = '') { return json_encode(hr_t($key, $fallback), JSON_HEX_TAG | JSON_HEX_APOS | JSON_HEX_AMP | JSON_HEX_QUOT); }
}
if (session_status() === PHP_SESSION_NONE) session_start();
include "../../inc/config.php";
session_check_json();
function ecd_h($v){return htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');}
function ecd_label($s){$m=array('DRAFT'=>'default','ACTIVE'=>'success','EXPIRED'=>'warning','TERMINATED'=>'danger','RENEWED'=>'info','CANCELLED'=>'default','PENDING'=>'warning','APPROVED'=>'success','REJECTED'=>'danger','NOT_REQUIRED'=>'default');$c=isset($m[$s])?$m[$s]:'default';return '<span class="label label-'.$c.'">'.ecd_h($s).'</span>';}
$draw=isset($_POST['draw'])?(int)$_POST['draw']:1;$start=isset($_POST['start'])?max(0,(int)$_POST['start']):0;$length=isset($_POST['length'])?(int)$_POST['length']:25;if($length<=0||$length>500)$length=25;
$from=isset($_POST['tgl_awal'])&&$_POST['tgl_awal']!==''?$_POST['tgl_awal']:date('Y-01-01');$to=isset($_POST['tgl_akhir'])&&$_POST['tgl_akhir']!==''?$_POST['tgl_akhir']:date('Y-m-d');$type=isset($_POST['contract_type'])?trim($_POST['contract_type']):'';$status=isset($_POST['contract_status'])?trim($_POST['contract_status']):'';$approval=isset($_POST['approval_status'])?trim($_POST['approval_status']):'';$dept=isset($_POST['department_code'])?trim($_POST['department_code']):'';$kw=isset($_POST['keyword'])?trim($_POST['keyword']):'';
$w=" WHERE c.contract_start<=? AND COALESCE(c.contract_end,'9999-12-31')>=? ";$p=array($to,$from);
if($type!==''){$w.=" AND c.contract_type=? ";$p[]=$type;}if($status!==''){$w.=" AND c.contract_status=? ";$p[]=$status;}if($approval!==''){$w.=" AND c.approval_status=? ";$p[]=$approval;}if($dept!==''){$w.=" AND c.department_code=? ";$p[]=$dept;}if($kw!==''){$like='%'.$kw.'%';$w.=" AND (c.contract_no LIKE ? OR e.employee_no LIKE ? OR e.full_name LIKE ? OR j.job_title_code LIKE ? OR j.job_title_name LIKE ?) ";array_push($p,$like,$like,$like,$like,$like);}
$kpi=$db->fetch("SELECT COUNT(*) total,SUM(contract_status='ACTIVE') active,SUM(contract_status='EXPIRED') expired,SUM(approval_status='PENDING') pending,SUM(contract_end IS NOT NULL AND contract_end BETWEEN CURDATE() AND DATE_ADD(CURDATE(),INTERVAL 60 DAY)) expiring_soon FROM erp_employee_contract");
$cnt=$db->fetch("SELECT COUNT(*) jml FROM erp_employee_contract c JOIN erp_employee_master e ON e.id=c.employee_id LEFT JOIN erp_job_title j ON j.id=c.job_title_id $w",$p);$total=$cnt?(int)$cnt->jml:0;
$orderMap=array(2=>'c.contract_no',3=>'e.employee_no',4=>'c.contract_type',5=>'c.contract_status',6=>'c.approval_status',7=>'c.contract_start',8=>'d.kd_dept',9=>'j.job_title_code',10=>'c.basic_salary',11=>'c.updated_at');$orderBy='c.contract_start DESC,c.contract_no DESC';
if(isset($_POST['order'][0]['column'])){$col=(int)$_POST['order'][0]['column'];$dir=(isset($_POST['order'][0]['dir'])&&strtolower($_POST['order'][0]['dir'])==='desc')?'DESC':'ASC';if(isset($orderMap[$col]))$orderBy=$orderMap[$col].' '.$dir;}
$rows=$db->query("SELECT c.*,e.employee_no,e.full_name,d.nm_dept,j.job_title_code,j.job_title_name,pn.position_code,pn.position_name,wl.location_code,wl.location_name,ap.employee_no approved_no,ap.full_name approved_name FROM erp_employee_contract c JOIN erp_employee_master e ON e.id=c.employee_id LEFT JOIN dept d ON d.kd_dept=c.department_code LEFT JOIN erp_job_title j ON j.id=c.job_title_id LEFT JOIN erp_position pn ON pn.id=c.position_id LEFT JOIN erp_work_location wl ON wl.id=c.work_location_id LEFT JOIN erp_employee_master ap ON ap.id=c.approved_by_employee_id $w ORDER BY $orderBy LIMIT $start,$length",$p);
$data=array();$no=$start+1;
foreach($rows as $r){$next=$r->contract_status==='ACTIVE'?'EXPIRED':'ACTIVE';$btn=$r->contract_status==='ACTIVE'?'warning':'success';$icon=$r->contract_status==='ACTIVE'?'fa-clock-o':'fa-check';$act='<div class="ec-action"><button class="btn btn-info btn-xs btn-ec-detail" data-id="'.(int)$r->id.'" title="'.hr_h('common_detail', 'Detail').'"><i class="fa fa-eye"></i></button> <button class="btn btn-primary btn-xs btn-ec-edit" data-id="'.(int)$r->id.'" title="'.hr_h('common_edit', 'Edit').'"><i class="fa fa-pencil"></i></button> <button class="btn btn-'.$btn.' btn-xs btn-ec-status" data-id="'.(int)$r->id.'" data-status="'.$next.'" title="'.$next.'"><i class="fa '.$icon.'"></i></button> <button class="btn btn-danger btn-xs btn-ec-delete" data-id="'.(int)$r->id.'" data-no="'.ecd_h($r->contract_no).'" title="'.hr_h('common_delete', 'Delete').'"><i class="fa fa-trash"></i></button></div>';
  $data[]=array($no++,$act,'<strong>'.ecd_h($r->contract_no).'</strong><br><small>SAP: '.ecd_h($r->sap_reference?:'-').'</small>','<strong>'.ecd_h($r->employee_no).'</strong><br><small>'.ecd_h($r->full_name).'</small>',ecd_h($r->contract_type).'<br><small>Renewal: '.(int)$r->renewal_no.'</small>',ecd_label($r->contract_status),ecd_label($r->approval_status),ecd_h($r->contract_start.' s/d '.($r->contract_end?:'Permanent')).'<br><small>Probation '.ecd_h(($r->probation_start?:'-').' s/d '.($r->probation_end?:'-')).'</small>','<strong>'.ecd_h($r->department_code?:'-').'</strong><br><small>'.ecd_h($r->nm_dept?:'').'</small>','<strong>'.ecd_h($r->job_title_code?:'-').'</strong><br><small>'.ecd_h($r->position_code?:'-').'</small>',ecd_h($r->currency).' '.number_format((float)$r->basic_salary,2).'<br><small>'.ecd_h($r->working_hours_per_week).' h/week</small>',ecd_h($r->updated_by?:$r->created_by?:'-').'<br><small>'.ecd_h($r->updated_at?:$r->created_at).'</small>');}
header('Content-Type: application/json; charset=utf-8');echo json_encode(array('draw'=>$draw,'recordsTotal'=>$total,'recordsFiltered'=>$total,'data'=>$data,'kpi'=>array('total'=>$kpi?(int)$kpi->total:0,'active'=>$kpi?(int)$kpi->active:0,'expired'=>$kpi?(int)$kpi->expired:0,'pending'=>$kpi?(int)$kpi->pending:0,'expiring_soon'=>$kpi?(int)$kpi->expiring_soon:0)));
?>
