<?php
if (!function_exists('hr_t')) {
  function hr_t($key, $fallback = '') { return lang_text($key, $fallback); }
}
if (!function_exists('hr_h')) {
  function hr_h($key, $fallback = '') { return htmlspecialchars((string) hr_t($key, $fallback), ENT_QUOTES, 'UTF-8'); }
}
if (!function_exists('hr_js')) {
  function hr_js($key, $fallback = '') { return json_encode(hr_t($key, $fallback), JSON_HEX_TAG | JSON_HEX_APOS | JSON_HEX_AMP | JSON_HEX_QUOT); }
}
$defaultFrom=date('Y-01-01');$defaultTo=date('Y-m-d');$canInsert=isset($role_act['insert_act'])&&$role_act['insert_act']==='Y'; ?>
<style>
.ec-hero{background:linear-gradient(135deg,#1d4ed8,#7c3aed);color:#fff;border-radius:14px;padding:20px;margin-bottom:18px;box-shadow:0 10px 24px rgba(15,23,42,.16)}.ec-hero h1{margin:0 0 6px;font-size:26px;font-weight:700}.ec-hero p{margin:0;opacity:.93}.ec-card{border-radius:12px;background:#fff;border:1px solid #e5edf5;box-shadow:0 5px 16px rgba(15,23,42,.05);margin-bottom:14px}.ec-kpi{padding:14px;border-radius:12px;background:#f8fafc;border:1px solid #e5edf5}.ec-kpi b{font-size:22px;display:block}#dtb_employee_contract th,#dtb_employee_contract td{font-size:12px;vertical-align:middle}.select2-container{width:100%!important}.required-label:after{content:' *';color:#dd4b39}.ec-action{white-space:nowrap}#modal_employee_contract .modal-body{max-height:calc(100vh - 185px);overflow-y:auto}.ec-note{color:#64748b;font-size:12px;margin-top:5px}
</style>
<section class="content-header"><h1><?=hr_h('hr_employee_contract', 'Employee Contract');?> <small>SAP HR Contract Management</small></h1><ol class="breadcrumb"><li><a href="<?=base_index();?>"><i class="fa fa-dashboard"></i> <?=hr_h('common_home', 'Home');?></a></li><li>Human Resource</li><li>Personnel Administration</li><li class="active"><?=hr_h('hr_employee_contract', 'Employee Contract');?></li></ol></section>
<section class="content">
<div class="ec-hero"><div class="row"><div class="col-md-8"><h1>Employee Contract Workbench</h1><p>Kelola PKWTT, PKWT, probation, renewal, approval, masa berlaku, dan attachment kontrak karyawan.</p></div><div class="col-md-4 text-right"><?php if($canInsert){ ?><button id="btn_open_ec" class="btn btn-warning"><i class="fa fa-plus"></i> Create Contract</button><?php } ?> <button id="btn_export_ec" class="btn btn-success"><i class="fa fa-file-excel-o"></i> <?=hr_h('common_export_excel', 'Export Excel');?></button></div></div></div>
<div class="row"><div class="col-sm-2"><div class="ec-kpi"><span>Total</span><b id="kpi_total">0</b></div></div><div class="col-sm-2"><div class="ec-kpi"><span><?=hr_h('hr_active', 'Active');?></span><b id="kpi_active">0</b></div></div><div class="col-sm-2"><div class="ec-kpi"><span>Expired</span><b id="kpi_expired">0</b></div></div><div class="col-sm-2"><div class="ec-kpi"><span><?=hr_h('hr_pending', 'Pending');?></span><b id="kpi_pending">0</b></div></div><div class="col-sm-2"><div class="ec-kpi"><span>Expiring 60d</span><b id="kpi_expiring_soon">0</b></div></div><div class="col-sm-2"><div class="ec-kpi"><span>Today</span><b><?=date('d M');?></b></div></div></div>
<div class="box ec-card"><div class="box-header"><h3 class="box-title"><i class="fa fa-filter"></i> Filter Contract</h3></div><div class="box-body"><form class="form-horizontal" onsubmit="return false;"><div class="form-group"><label class="control-label col-lg-2">Contract Period</label><div class="col-lg-2"><div class="input-group date ec-date"><input id="filter_tgl_awal" class="form-control" value="<?=$defaultFrom;?>"><span class="input-group-addon"><span class="glyphicon glyphicon-calendar"></span></span></div></div><div class="col-lg-2"><div class="input-group date ec-date"><input id="filter_tgl_akhir" class="form-control" value="<?=$defaultTo;?>"><span class="input-group-addon"><span class="glyphicon glyphicon-calendar"></span></span></div></div><label class="control-label col-lg-1">Type</label><div class="col-lg-2"><select id="filter_contract_type" class="form-control"><option value=""><?=hr_h('common_all', 'All');?></option><option>PERMANENT</option><option>FIXED_TERM</option><option>PROBATION</option><option>INTERNSHIP</option><option>OUTSOURCING</option><option>DAILY_WORKER</option><option>CONSULTANT</option></select></div><label class="control-label col-lg-1"><?=hr_h('common_status', 'Status');?></label><div class="col-lg-2"><select id="filter_contract_status" class="form-control"><option value=""><?=hr_h('common_all', 'All');?></option><option>DRAFT</option><option>ACTIVE</option><option>EXPIRED</option><option>TERMINATED</option><option>RENEWED</option><option>CANCELLED</option></select></div></div><div class="form-group"><label class="control-label col-lg-2">Approval</label><div class="col-lg-2"><select id="filter_approval_status" class="form-control"><option value=""><?=hr_h('common_all', 'All');?></option><option>NOT_REQUIRED</option><option>PENDING</option><option>APPROVED</option><option>REJECTED</option></select></div><label class="control-label col-lg-1"><?=hr_h('hr_department', 'Department');?></label><div class="col-lg-3"><select id="filter_department_code" class="form-control"></select></div><label class="control-label col-lg-1"><?=hr_h('common_search', 'Search');?></label><div class="col-lg-3"><input id="filter_keyword" class="form-control" placeholder="Contract no, employee, job title"></div></div><div class="form-group"><div class="col-lg-offset-2 col-lg-10"><button id="btn_filter_ec" class="btn btn-primary"><i class="fa fa-filter"></i> <?=hr_h('common_filter', 'Filter');?></button> <button id="btn_reset_ec" class="btn btn-default"><i class="fa fa-refresh"></i> <?=hr_h('common_reset', 'Reset');?></button></div></div></form></div></div>
<div class="box ec-card"><div class="box-body"><div class="alert alert-warning error_data_delete" style="display:none"><button type="button" class="close hide_alert_notif">&times;</button><span class="isi_warning_delete"></span></div><div class="table-responsive"><table id="dtb_employee_contract" class="table table-bordered table-striped" style="width:100%"><thead><tr><th><?=hr_h('common_no', 'No');?></th><th><?=hr_h('common_action', 'Action');?></th><th>Contract</th><th><?=hr_h('hr_employee', 'Employee');?></th><th>Type</th><th><?=hr_h('common_status', 'Status');?></th><th>Approval</th><th><?=hr_h('hr_period', 'Period');?></th><th><?=hr_h('hr_department', 'Department');?></th><th>Job / Position</th><th>Salary</th><th>Updated</th></tr></thead><tbody></tbody></table></div></div></div>
<div id="modal_employee_contract" class="modal fade"><div class="modal-dialog modal-lg" style="width:94%"><div class="modal-content"><form id="form_employee_contract"><input type="hidden" name="id" id="ec_id"><div class="modal-header"><button type="button" class="close" data-dismiss="modal">&times;</button><h4 class="modal-title">Create Employee Contract</h4></div><div class="modal-body"><div class="alert alert-info"><strong>SAP hint:</strong> Kontrak aktif idealnya satu per employee. Renewal disimpan sebagai kontrak baru dan boleh dihubungkan ke previous contract.</div>
<div class="row"><div class="col-md-2 form-group"><label class="required-label">Contract No</label><input name="contract_no" id="contract_no" class="form-control text-uppercase" required maxlength="30" placeholder="CTR-2026-0001"></div><div class="col-md-4 form-group"><label class="required-label"><?=hr_h('hr_employee', 'Employee');?></label><select name="employee_id" id="employee_id" class="form-control" required></select></div><div class="col-md-2 form-group"><label class="required-label">Type</label><select name="contract_type" id="contract_type" class="form-control" required><option>PERMANENT</option><option>FIXED_TERM</option><option>PROBATION</option><option>INTERNSHIP</option><option>OUTSOURCING</option><option>DAILY_WORKER</option><option>CONSULTANT</option></select></div><div class="col-md-2 form-group"><label><?=hr_h('common_status', 'Status');?></label><select name="contract_status" id="contract_status" class="form-control"><option>DRAFT</option><option>ACTIVE</option><option>EXPIRED</option><option>TERMINATED</option><option>RENEWED</option><option>CANCELLED</option></select></div><div class="col-md-2 form-group"><label>Approval</label><select name="approval_status" id="approval_status" class="form-control"><option>PENDING</option><option>APPROVED</option><option>REJECTED</option><option>NOT_REQUIRED</option></select></div></div>
<div class="row"><div class="col-md-2 form-group"><label class="required-label">Start</label><input name="contract_start" id="contract_start" class="form-control date-field" required value="<?=date('Y-m-d');?>"></div><div class="col-md-2 form-group"><label>End</label><input name="contract_end" id="contract_end" class="form-control date-field"></div><div class="col-md-2 form-group"><label>Probation Start</label><input name="probation_start" id="probation_start" class="form-control date-field"></div><div class="col-md-2 form-group"><label>Probation End</label><input name="probation_end" id="probation_end" class="form-control date-field"></div><div class="col-md-2 form-group"><label>Renewal No</label><input name="renewal_no" id="renewal_no" class="form-control text-right" type="number" min="0" value="0"></div><div class="col-md-2 form-group"><label>Previous Contract</label><select name="previous_contract_id" id="previous_contract_id" class="form-control"></select></div></div>
<div class="row"><div class="col-md-3 form-group"><label><?=hr_h('hr_department', 'Department');?></label><select name="department_code" id="department_code" class="form-control"></select></div><div class="col-md-3 form-group"><label><?=hr_h('hr_job_title', 'Job Title');?></label><select name="job_title_id" id="job_title_id" class="form-control"></select></div><div class="col-md-3 form-group"><label><?=hr_h('hr_position', 'Position');?></label><select name="position_id" id="position_id" class="form-control"></select></div><div class="col-md-3 form-group"><label>Org Unit</label><select name="company_structure_id" id="company_structure_id" class="form-control"></select></div></div>
<div class="row"><div class="col-md-3 form-group"><label><?=hr_h('hr_work_location', 'Work Location');?></label><select name="work_location_id" id="work_location_id" class="form-control"></select></div><div class="col-md-2 form-group"><label>Employee Group</label><select name="employee_group" id="employee_group" class="form-control"><option>DIRECTOR</option><option>MANAGER</option><option selected>STAFF</option><option>NON_STAFF</option><option>OPERATOR</option><option>CONTRACT</option><option>DAILY_WORKER</option><option>TRAINEE</option></select></div><div class="col-md-2 form-group"><label>Pay Grade</label><select name="pay_grade" id="pay_grade" class="form-control"><option value="">Grade</option><option>G01</option><option>G02</option><option>G03</option><option>G04</option><option>G05</option><option>G06</option><option>G07</option><option>G08</option><option>M01</option><option>M02</option><option>M03</option><option>DIR</option></select></div><div class="col-md-2 form-group"><label>Payroll Area</label><select name="payroll_area" id="payroll_area" class="form-control"><option value="">Area</option><option>MONTHLY</option><option>DAILY</option><option>CONTRACT</option><option>MANAGEMENT</option></select></div><div class="col-md-3 form-group"><label><?=hr_h('hr_basic_salary', 'Basic Salary');?></label><input name="basic_salary" id="basic_salary" type="number" min="0" step="0.01" class="form-control text-right" value="0"></div></div>
<div class="row"><div class="col-md-2 form-group"><label>Currency</label><select name="currency" id="currency" class="form-control"><option>IDR</option><option>USD</option><option>EUR</option><option>SGD</option></select></div><div class="col-md-2 form-group"><label>Hours / Week</label><input name="working_hours_per_week" id="working_hours_per_week" class="form-control text-right" type="number" step="0.01" value="40.00"></div><div class="col-md-2 form-group"><label>Notice Days</label><input name="notice_period_days" id="notice_period_days" class="form-control text-right" type="number" value="30"></div><div class="col-md-2 form-group"><label>Reason</label><select name="contract_reason" id="contract_reason" class="form-control"><option>NEW_HIRE</option><option>RENEWAL</option><option>PROMOTION</option><option>MUTATION</option><option>PROBATION_PASS</option><option>CORRECTION</option><option>OTHER</option></select></div><div class="col-md-4 form-group"><label>Approved By</label><select name="approved_by_employee_id" id="approved_by_employee_id" class="form-control"></select></div></div>
<div class="row"><div class="col-md-2 form-group"><label>Approved At</label><input name="approved_at" id="approved_at" class="form-control" placeholder="YYYY-MM-DD HH:MM:SS"></div><div class="col-md-3 form-group"><label>Attachment Ref</label><input name="attachment_ref" id="attachment_ref" class="form-control" maxlength="255"></div><div class="col-md-3 form-group"><label>SAP Reference</label><input name="sap_reference" id="sap_reference" class="form-control" maxlength="50"></div><div class="col-md-4 form-group"><label>Termination Reason</label><input name="termination_reason" id="termination_reason" class="form-control" maxlength="255"></div></div><div class="form-group"><label><?=hr_h('common_remarks', 'Remarks');?></label><textarea name="remarks" id="remarks" class="form-control" rows="3"></textarea></div>
</div><div class="modal-footer"><button type="button" class="btn btn-default" data-dismiss="modal"><?=hr_h('common_cancel', 'Cancel');?></button><button type="submit" class="btn btn-primary"><i class="fa fa-save"></i> Save Contract</button></div></form></div></div></div>
<div id="modal_ec_detail" class="modal fade"><div class="modal-dialog modal-lg" style="width:92%"><div class="modal-content"><div class="modal-header"><button class="close" data-dismiss="modal">&times;</button><h4 class="modal-title">Employee Contract Detail</h4></div><div class="modal-body" id="ec_detail_body"></div><div class="modal-footer"><button class="btn btn-default" data-dismiss="modal"><?=hr_h('common_close', 'Close');?></button></div></div></div></div>
</section>
<script src="<?=base_admin();?>assets/plugins/select2/select2.min.js"></script><script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
<script>
function ecError(m){$('.isi_warning_delete').text(m||'Employee Contract gagal diproses.');$('.error_data_delete').fadeIn();}
function ecFilters(){return{tgl_awal:$('#filter_tgl_awal').val(),tgl_akhir:$('#filter_tgl_akhir').val(),contract_type:$('#filter_contract_type').val(),contract_status:$('#filter_contract_status').val(),approval_status:$('#filter_approval_status').val(),department_code:$('#filter_department_code').val(),keyword:$('#filter_keyword').val()};}
function ecSet(s,v,t){var e=$(s);if(!v){e.val(null).trigger('change');return;}if(!e.find('option[value="'+v+'"]').length)e.append(new Option(t||v,v,true,true));e.val(v).trigger('change');}
function ecReset(title){$('#form_employee_contract')[0].reset();$('#ec_id').val('');$('#employee_id,#previous_contract_id,#department_code,#job_title_id,#position_id,#company_structure_id,#work_location_id,#approved_by_employee_id').val(null).trigger('change');$('#contract_type').val('FIXED_TERM').trigger('change');$('#contract_status').val('DRAFT').trigger('change');$('#approval_status').val('PENDING').trigger('change');$('#employee_group').val('STAFF').trigger('change');$('#currency').val('IDR').trigger('change');$('#contract_reason').val('NEW_HIRE').trigger('change');$('#contract_start').val('<?=date('Y-m-d');?>');$('#working_hours_per_week').val('40.00');$('#notice_period_days').val('30');$('#renewal_no').val('0');$('#basic_salary').val('0');$('#modal_employee_contract .modal-title').text(title||'Create Employee Contract');}
function ecAjax(s,a,p){$(s).select2({width:'100%',allowClear:true,placeholder:p,dropdownParent:$('#modal_employee_contract'),ajax:{url:'<?=base_admin();?>modul/employee_contract/employee_contract_action.php?act='+a,type:'POST',dataType:'json',delay:250,data:function(q){return{term:q.term||'',exclude:$('#ec_id').val()};},processResults:function(d){return{results:d.results||[]};}}});}
$(function(){if($.fn.datepicker){$('.ec-date,.date-field').datepicker({format:'yyyy-mm-dd',autoclose:true,todayHighlight:true});}if($.fn.select2){$('#filter_contract_type,#filter_contract_status,#filter_approval_status,#contract_type,#contract_status,#approval_status,#employee_group,#pay_grade,#payroll_area,#currency,#contract_reason').select2({width:'100%',allowClear:true});$('#filter_department_code').select2({width:'100%',allowClear:true,placeholder:'Semua Department',ajax:{url:'<?=base_admin();?>modul/employee_contract/employee_contract_action.php?act=department_search',type:'POST',dataType:'json',delay:250,data:function(p){return{term:p.term||''};},processResults:function(d){return{results:d.results||[]};}}});ecAjax('#employee_id','employee_search','Pilih Employee...');ecAjax('#previous_contract_id','contract_search','Pilih Previous Contract...');ecAjax('#department_code','department_search','Pilih Department...');ecAjax('#job_title_id','job_title_search','Pilih Job Title...');ecAjax('#position_id','position_search','Pilih Position...');ecAjax('#company_structure_id','company_structure_search','Pilih Org Unit...');ecAjax('#work_location_id','work_location_search','Pilih Work Location...');ecAjax('#approved_by_employee_id','employee_search','Pilih Approver...');}
var dt=$('#dtb_employee_contract').DataTable({bProcessing:true,bServerSide:true,pageLength:25,dom:"<'row'<'col-sm-12'B>>"+"<'row'<'col-sm-6'l><'col-sm-6'f>>"+"<'row'<'col-sm-12'tr>>"+"<'row'<'col-sm-5'i><'col-sm-7'p>>",buttons:[{extend:'collection',text:<?=hr_js('common_export_data', 'Export Data');?>,buttons:['copyHtml5','excelHtml5','csvHtml5','pdfHtml5']}],columnDefs:[{targets:[0,1],orderable:false,searchable:false},{width:'42px',targets:0},{width:'150px',targets:1}],ajax:{url:'<?=base_admin();?>modul/employee_contract/employee_contract_data.php',type:'post',data:function(d){$.extend(d,ecFilters());},dataSrc:function(j){var k=j.kpi||{};$('#kpi_total').text(k.total||0);$('#kpi_active').text(k.active||0);$('#kpi_expired').text(k.expired||0);$('#kpi_pending').text(k.pending||0);$('#kpi_expiring_soon').text(k.expiring_soon||0);return j.data||[];},error:function(x){console.log(x.responseText);ecError('Data Employee Contract gagal dimuat.');}}});
$('#btn_open_ec').click(function(){ecReset('Create Employee Contract');$('#modal_employee_contract').modal({backdrop:'static',keyboard:false});});$('#btn_filter_ec').click(function(){dt.draw();});$('#filter_keyword').keyup(function(e){if(e.keyCode===13)dt.draw();});$('#btn_reset_ec').click(function(){$('#filter_tgl_awal').val('<?=$defaultFrom;?>');$('#filter_tgl_akhir').val('<?=$defaultTo;?>');$('#filter_contract_type,#filter_contract_status,#filter_approval_status,#filter_department_code').val(null).trigger('change');$('#filter_keyword').val('');dt.draw();});$('#btn_export_ec').click(function(){window.location='<?=base_admin();?>modul/employee_contract/employee_contract_action.php?act=export&'+$.param(ecFilters());});$('.hide_alert_notif').click(function(){$('.error_data_delete').hide();});$('#contract_no').on('keyup change',function(){this.value=this.value.toUpperCase();});
$('#form_employee_contract').submit(function(e){e.preventDefault();var b=$(this).find('button[type=submit]');b.prop('disabled',true).html('<i class="fa fa-spinner fa-spin"></i> <?=hr_h('common_saving', 'Saving...');?>');$.post('<?=base_admin();?>modul/employee_contract/employee_contract_action.php?act=save',$(this).serialize(),function(r){b.prop('disabled',false).html('<i class="fa fa-save"></i> Save Contract');if(r.status==='good'){$('#modal_employee_contract').modal('hide');dt.draw(false);Swal.fire('Saved','Employee Contract berhasil disimpan.','success');}else ecError(r.error_message);},'json').fail(function(x){b.prop('disabled',false).html('<i class="fa fa-save"></i> Save Contract');ecError(x.responseText);});});
$(document).on('click','.btn-ec-detail',function(){$.post('<?=base_admin();?>modul/employee_contract/employee_contract_action.php?act=detail',{id:$(this).data('id')},function(h){$('#ec_detail_body').html(h);$('#modal_ec_detail').modal('show');});});
$(document).on('click','.btn-ec-edit',function(){var id=$(this).data('id');$.post('<?=base_admin();?>modul/employee_contract/employee_contract_action.php?act=get',{id:id},function(r){if(r.status!=='good'){ecError(r.error_message);return;}ecReset('Edit Employee Contract');var h=r.data||{};Object.keys(h).forEach(function(k){var el=$('#'+k);if(el.length&&!['employee_id','previous_contract_id','department_code','job_title_id','position_id','company_structure_id','work_location_id','approved_by_employee_id'].includes(k))el.val(h[k]);});$('#ec_id').val(h.id);ecSet('#employee_id',h.employee_id,h.employee_text);ecSet('#previous_contract_id',h.previous_contract_id,h.previous_contract_text);ecSet('#department_code',h.department_code,h.department_text);ecSet('#job_title_id',h.job_title_id,h.job_title_text);ecSet('#position_id',h.position_id,h.position_text);ecSet('#company_structure_id',h.company_structure_id,h.company_structure_text);ecSet('#work_location_id',h.work_location_id,h.work_location_text);ecSet('#approved_by_employee_id',h.approved_by_employee_id,h.approved_by_text);$('#contract_type,#contract_status,#approval_status,#employee_group,#pay_grade,#payroll_area,#currency,#contract_reason').trigger('change');$('#modal_employee_contract').modal({backdrop:'static',keyboard:false});},'json');});
$(document).on('click','.btn-ec-status',function(){var id=$(this).data('id'),status=$(this).data('status');$.post('<?=base_admin();?>modul/employee_contract/employee_contract_action.php?act=status',{id:id,status:status},function(r){if(r.status==='good'){dt.draw(false);Swal.fire('Updated','Status kontrak berhasil diubah.','success');}else ecError(r.error_message);},'json');});
$(document).on('click','.btn-ec-delete',function(){var id=$(this).data('id'),no=$(this).data('no');Swal.fire({title:erpLang('confirm_delete_title','Delete Confirmation'),text:no,icon:'warning',showCancelButton:true,confirmButtonText:erpLang('common_delete','Delete'),cancelButtonText:erpLang('common_cancel','Cancel')}).then(function(x){if(!x.isConfirmed)return;$.post('<?=base_admin();?>modul/employee_contract/employee_contract_action.php?act=delete',{id:id},function(r){if(r.status==='good'){dt.draw(false);Swal.fire(erpLang('common_deleted','Deleted'),erpLang('common_deleted_message','Data deleted successfully.'),'success');}else ecError(r.error_message);},'json').fail(function(x){ecError(x.responseText);});});});
});
</script>
