<?php
if (!function_exists('hr_t')) {
  function hr_t($key, $fallback = '') { return lang_text($key, $fallback); }
}
if (!function_exists('hr_h')) {
  function hr_h($key, $fallback = '') { return htmlspecialchars((string) hr_t($key, $fallback), ENT_QUOTES, 'UTF-8'); }
}
if (!function_exists('hr_js')) {
  function hr_js($key, $fallback = '') { return json_encode(hr_t($key, $fallback), JSON_HEX_TAG | JSON_HEX_APOS | JSON_HEX_AMP | JSON_HEX_QUOT); }
}
if (session_status() === PHP_SESSION_NONE) session_start();
include "../../inc/config.php";
session_check_json();
function ed_json($s,$m='',$x=array()){header('Content-Type: application/json; charset=utf-8');$p=array('status'=>$s);if($m!=='')$p[$s==='good'?'message':'error_message']=$m;foreach($x as $k=>$v)$p[$k]=$v;echo json_encode($p);exit;}
function ed_h($v){return htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');}
function ed_p($k,$d=''){return isset($_POST[$k])?$_POST[$k]:$d;}
function ed_g($k,$d=''){return isset($_GET[$k])?$_GET[$k]:$d;}
function ed_c($v){return strtoupper(trim((string)$v));}
function ed_user(){return isset($_SESSION['username'])&&$_SESSION['username']!==''?$_SESSION['username']:'system';}
function ed_select2($rows,$id,$cb){$out=array();foreach($rows as $r)$out[]=array('id'=>$r->$id,'text'=>$cb($r));header('Content-Type: application/json; charset=utf-8');echo json_encode(array('results'=>$out));exit;}
function ed_row($id){global $db;return $db->fetch("SELECT doc.*,e.employee_no,e.full_name,e.department_code,d.nm_dept,j.job_title_code,j.job_title_name,v.employee_no verifier_no,v.full_name verifier_name FROM erp_employee_document doc JOIN erp_employee_master e ON e.id=doc.employee_id LEFT JOIN dept d ON d.kd_dept=e.department_code LEFT JOIN erp_job_title j ON j.id=e.job_title_id LEFT JOIN erp_employee_master v ON v.id=doc.verified_by_employee_id WHERE doc.id=? LIMIT 1",array((int)$id));}
function ed_payload($r){$d=(array)$r;$d['employee_text']=$r->employee_id?($r->employee_no.' - '.$r->full_name):'';$d['verified_by_text']=$r->verified_by_employee_id?($r->verifier_no.' - '.$r->verifier_name):'';return $d;}
function ed_rows($from,$to,$type,$cat,$verify,$status,$expiring,$kw){global $db;$w=" WHERE doc.effective_from<=? AND doc.effective_to>=? ";$p=array($to,$from);if($type!==''){$w.=" AND doc.document_type=? ";$p[]=$type;}if($cat!==''){$w.=" AND doc.document_category=? ";$p[]=$cat;}if($verify!==''){$w.=" AND doc.verification_status=? ";$p[]=$verify;}if($status!==''){$w.=" AND doc.status=? ";$p[]=$status;}if($expiring==='Y'){$w.=" AND doc.expiry_date IS NOT NULL AND doc.expiry_date BETWEEN CURDATE() AND DATE_ADD(CURDATE(),INTERVAL 90 DAY) ";}if($kw!==''){$like='%'.$kw.'%';$w.=" AND (doc.document_no LIKE ? OR doc.document_title LIKE ? OR doc.document_number LIKE ? OR e.employee_no LIKE ? OR e.full_name LIKE ? OR doc.file_name LIKE ?) ";array_push($p,$like,$like,$like,$like,$like,$like);}return $db->query("SELECT doc.*,e.employee_no,e.full_name,e.department_code,d.nm_dept,j.job_title_code,j.job_title_name,v.employee_no verifier_no,v.full_name verifier_name FROM erp_employee_document doc JOIN erp_employee_master e ON e.id=doc.employee_id LEFT JOIN dept d ON d.kd_dept=e.department_code LEFT JOIN erp_job_title j ON j.id=e.job_title_id LEFT JOIN erp_employee_master v ON v.id=doc.verified_by_employee_id $w ORDER BY e.employee_no,doc.document_category,doc.document_type",$p);}
$act=isset($_GET['act'])?$_GET['act']:'';$username=ed_user();
$types=array('KTP','NPWP','KK','IJAZAH','SERTIFIKAT','KONTRAK','BPJS_KESEHATAN','BPJS_TK','PASSPORT','VISA','SIM','LICENSE','WARNING_LETTER','APPRAISAL','OTHER');
$cats=array('PERSONAL','EMPLOYMENT','PAYROLL_TAX','BENEFIT','LEGAL','TRAINING','PERFORMANCE','DISCIPLINARY','OTHER');
$ver=array('PENDING','VERIFIED','REJECTED');$stats=array('ACTIVE','INACTIVE','EXPIRED','ARCHIVED');
switch($act){
case 'employee_search':$t=trim(ed_p('term'));$like='%'.$t.'%';$rows=$db->query("SELECT id,employee_no,full_name,employment_status FROM erp_employee_master WHERE employment_status IN ('ACTIVE','PROBATION','CONTRACT') AND (?='' OR employee_no LIKE ? OR full_name LIKE ?) ORDER BY employee_no LIMIT 30",array($t,$like,$like));ed_select2($rows,'id',function($r){return $r->employee_no.' - '.$r->full_name.' ['.$r->employment_status.']';});break;
case 'get':$r=ed_row((int)ed_p('id'));if(!$r)ed_json('error',hr_t('hr_employee_document_not_found', 'Employee Document not found.'));ed_json('good','',array('data'=>ed_payload($r)));break;
case 'save':
  $id=(int)ed_p('id');$no=ed_c(ed_p('document_no'));$emp=(int)ed_p('employee_id');$type=ed_c(ed_p('document_type'));$cat=ed_c(ed_p('document_category'));$title=trim(ed_p('document_title'));$verify=ed_c(ed_p('verification_status','PENDING'));$from=trim(ed_p('effective_from'));$to=trim(ed_p('effective_to','9999-12-31'));$status=ed_c(ed_p('status','ACTIVE'));
  if($no==='')ed_json('error','Document No wajib diisi.');if(!preg_match('/^[A-Z0-9_-]{3,30}$/',$no))ed_json('error','Document No hanya boleh huruf besar, angka, underscore, atau dash.');if(!$emp)ed_json('error','Employee wajib dipilih.');if($title==='')ed_json('error','Document Title wajib diisi.');if(!in_array($type,$types,true))ed_json('error','Document Type tidak valid.');if(!in_array($cat,$cats,true))ed_json('error','Document Category tidak valid.');if(!in_array($verify,$ver,true))ed_json('error','Verification Status tidak valid.');if(!in_array($status,$stats,true))ed_json('error','Status tidak valid.');if($from===''||$to==='')ed_json('error','Effective From/To wajib diisi.');if(strtotime($to)<strtotime($from))ed_json('error','Effective To tidak boleh sebelum Effective From.');
  $issue=trim(ed_p('issue_date'));$expiry=trim(ed_p('expiry_date'));if($issue!==''&&$expiry!==''&&strtotime($expiry)<strtotime($issue))ed_json('error','Expiry Date tidak boleh sebelum Issue Date.');
  if(!$db->fetch("SELECT id FROM erp_employee_master WHERE id=? LIMIT 1",array($emp)))ed_json('error','Employee tidak valid.');if($db->fetch("SELECT id FROM erp_employee_document WHERE document_no=? AND id<>? LIMIT 1",array($no,$id)))ed_json('error','Document No sudah digunakan.');
  $yn=array('Y','N');$conf=ed_c(ed_p('confidential','N'));$mand=ed_c(ed_p('mandatory_document','N'));$renew=ed_c(ed_p('renewal_required','N'));foreach(array($conf,$mand,$renew) as $v){if(!in_array($v,$yn,true))ed_json('error','Flag Y/N tidak valid.');}
  $data=array('document_no'=>$no,'employee_id'=>$emp,'document_type'=>$type,'document_category'=>$cat,'document_title'=>$title,'document_number'=>trim(ed_p('document_number')),'issue_date'=>$issue?:null,'expiry_date'=>$expiry?:null,'issuing_authority'=>trim(ed_p('issuing_authority')),'issuing_country'=>ed_c(ed_p('issuing_country','ID')),'file_ref'=>trim(ed_p('file_ref')),'file_name'=>trim(ed_p('file_name')),'file_type'=>ed_c(ed_p('file_type')),'confidential'=>$conf,'mandatory_document'=>$mand,'renewal_required'=>$renew,'verification_status'=>$verify,'verified_by_employee_id'=>ed_p('verified_by_employee_id')!==''?(int)ed_p('verified_by_employee_id'):null,'verified_at'=>trim(ed_p('verified_at'))?:null,'effective_from'=>$from,'effective_to'=>$to,'status'=>$status,'sap_reference'=>trim(ed_p('sap_reference')),'remarks'=>trim(ed_p('remarks')),'updated_by'=>$username,'updated_at'=>date('Y-m-d H:i:s'));
  if($id>0){if(!$db->fetch("SELECT id FROM erp_employee_document WHERE id=? LIMIT 1",array($id)))ed_json('error',hr_t('hr_employee_document_not_found', 'Employee Document not found.'));$ok=$db->update('erp_employee_document',$data,'id',$id);}else{$data['created_by']=$username;$ok=$db->insert('erp_employee_document',$data);$id=$db->last_insert_id();}
  if(!$ok)ed_json('error',$db->getErrorMessage()?:hr_t('hr_employee_document_save_failed', 'Employee Document failed to save.'));if(function_exists('simpan_log'))simpan_log('User '.$username.' menyimpan Employee Document '.$no.' pada '.date('Y-m-d H:i:s'),$username);ed_json('good',hr_t('hr_employee_document_save_success', 'Employee Document saved successfully.'),array('id'=>$id));
case 'delete':$id=(int)ed_p('id');$r=$db->fetch("SELECT * FROM erp_employee_document WHERE id=? LIMIT 1",array($id));if(!$r)ed_json('error',hr_t('hr_employee_document_not_found', 'Employee Document not found.'));$db->delete('erp_employee_document','id',$id);if($db->getErrorMessage())ed_json('error',$db->getErrorMessage());if(function_exists('simpan_log'))simpan_log('User '.$username.' menghapus Employee Document '.$r->document_no,$username);ed_json('good','Employee Document berhasil dihapus.');
case 'status':$id=(int)ed_p('id');$status=ed_c(ed_p('status'));if(!in_array($status,$stats,true))ed_json('error','Status tidak valid.');$r=$db->fetch("SELECT * FROM erp_employee_document WHERE id=? LIMIT 1",array($id));if(!$r)ed_json('error',hr_t('hr_employee_document_not_found', 'Employee Document not found.'));$ok=$db->update('erp_employee_document',array('status'=>$status,'updated_by'=>$username,'updated_at'=>date('Y-m-d H:i:s')),'id',$id);if(!$ok)ed_json('error',$db->getErrorMessage()?:'Status gagal diubah.');ed_json('good','Status berhasil diubah.');
case 'detail':$r=ed_row((int)ed_p('id'));if(!$r){echo '<div class="alert alert-warning">Employee Document tidak ditemukan.</div>';break;}echo '<h3 style="margin-top:0">'.ed_h($r->document_no).' <small>'.ed_h($r->document_title).'</small></h3><span class="label label-success">'.ed_h($r->status).'</span> <span class="label label-info">'.ed_h($r->document_type.' / '.$r->document_category).'</span> <span class="label label-primary">'.ed_h($r->verification_status).'</span><hr>';echo '<div class="row"><div class="col-sm-3"><b>'.hr_h('hr_employee', 'Employee').'</b><br>'.ed_h($r->employee_no.' - '.$r->full_name).'</div><div class="col-sm-3"><b>Document Number</b><br>'.ed_h($r->document_number?:'-').'</div><div class="col-sm-3"><b>Issue / Expiry</b><br>'.ed_h(($r->issue_date?:'-').' / '.($r->expiry_date?:'-')).'</div><div class="col-sm-3"><b>Authority</b><br>'.ed_h($r->issuing_authority?:'-').'</div></div><hr>';echo '<div class="row"><div class="col-sm-3"><b>'.hr_h('hr_file', 'File').'</b><br>'.ed_h($r->file_name?:'-').'<br><small>'.ed_h($r->file_ref?:'-').'</small></div><div class="col-sm-3"><b>Flags</b><br>Confidential '.ed_h($r->confidential).' | Mandatory '.ed_h($r->mandatory_document).'<br><small>Renewal '.ed_h($r->renewal_required).'</small></div><div class="col-sm-3"><b>Verified By</b><br>'.ed_h($r->verifier_no?($r->verifier_no.' - '.$r->verifier_name):'-').'</div><div class="col-sm-3"><b>Effective</b><br>'.ed_h($r->effective_from.' s/d '.$r->effective_to).'</div></div><hr><b>'.hr_h('common_remarks', 'Remarks').'</b><p>'.nl2br(ed_h($r->remarks?:'-')).'</p>';break;
case 'export':
  $initial=ob_get_level();ob_start();error_reporting(E_ALL & ~E_NOTICE & ~E_WARNING & ~E_DEPRECATED & ~E_USER_DEPRECATED);require_once "../../inc/lib/PHPExcel.php";require_once "../../inc/excel_style_helper.php";PHPExcel_Shared_File::setUseUploadTempDirectory(true);$from=ed_g('tgl_awal',date('Y-01-01'));$to=ed_g('tgl_akhir','9999-12-31');$rows=ed_rows($from,$to,ed_g('document_type',''),ed_g('document_category',''),ed_g('verification_status',''),ed_g('status',''),ed_g('expiring_soon',''),ed_g('keyword',''));$excel=new PHPExcel();$sheet=$excel->setActiveSheetIndex(0);$sheet->setTitle(erp_export_sheet_title('Employee Document'));$heads=array(erp_export_label("No"),erp_export_label("Document No"),erp_export_label("Employee"),erp_export_label("Type"),erp_export_label("Category"),erp_export_label("Title"),erp_export_label("Document Number"),erp_export_label("Issue Date"),erp_export_label("Expiry Date"),erp_export_label("Authority"),erp_export_label("Country"),erp_export_label("File"),erp_export_label("Confidential"),erp_export_label("Mandatory"),erp_export_label("Renewal"),erp_export_label("Verification"),erp_export_label("Verifier"),erp_export_label("Effective"),erp_export_label("Status"),erp_export_label("SAP Ref"),erp_export_label("Updated By"));foreach($heads as $i=>$h)$sheet->setCellValue(PHPExcel_Cell::stringFromColumnIndex($i).'4',$h);$rnum=5;$n=1;foreach($rows as $r){$vals=array($n++,$r->document_no,$r->employee_no.' - '.$r->full_name,$r->document_type,$r->document_category,$r->document_title,$r->document_number,$r->issue_date,$r->expiry_date,$r->issuing_authority,$r->issuing_country,$r->file_ref,$r->confidential,$r->mandatory_document,$r->renewal_required,$r->verification_status,$r->verifier_no.' - '.$r->verifier_name,$r->effective_from.' s/d '.$r->effective_to,$r->status,$r->sap_reference,$r->updated_by?:$r->created_by);foreach($vals as $i=>$v)$sheet->setCellValue(PHPExcel_Cell::stringFromColumnIndex($i).$rnum,$v);$rnum++;}erpkb_excel_apply_standard_style($excel,array('sheet'=>$sheet,'title'=>erp_export_title('EMPLOYEE DOCUMENT REPORT'),'header_row'=>4,'first_data_row'=>5,'last_data_row'=>max(5,$rnum-1),'column_count'=>count($heads),'filters'=>array('Effective'=>$from.' s/d '.$to)));$tmp=erpkb_excel_temp_file('employee_document_');PHPExcel_IOFactory::createWriter($excel,'Excel2007')->save($tmp);$size=@filesize($tmp);$sig=@file_get_contents($tmp,false,null,0,2);if(!$size||$sig!=='PK'){@unlink($tmp);while(ob_get_level()>$initial)ob_end_clean();echo erp_t('export_excel_invalid_file','File Excel gagal dibuat dengan benar.');exit;}while(ob_get_level()>$initial)ob_end_clean();header('Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');header('Content-Disposition: attachment; filename="employee_document_'.date('Ymd_His').'.xlsx"');header('Content-Length: '.$size);header('Cache-Control: max-age=0');header('Pragma: public');readfile($tmp);@unlink($tmp);exit;
default:ed_json('error','Action tidak dikenal.');
}
?>
