<?php
if (!function_exists('hr_t')) {
  function hr_t($key, $fallback = '') { return lang_text($key, $fallback); }
}
if (!function_exists('hr_h')) {
  function hr_h($key, $fallback = '') { return htmlspecialchars((string) hr_t($key, $fallback), ENT_QUOTES, 'UTF-8'); }
}
if (!function_exists('hr_js')) {
  function hr_js($key, $fallback = '') { return json_encode(hr_t($key, $fallback), JSON_HEX_TAG | JSON_HEX_APOS | JSON_HEX_AMP | JSON_HEX_QUOT); }
}
$defaultFrom=date('Y-01-01');$defaultTo=date('Y-m-d'); ?>
<style>.la-hero{background:linear-gradient(135deg,#166534,#2563eb);color:#fff;border-radius:14px;padding:20px;margin-bottom:18px;box-shadow:0 10px 24px rgba(15,23,42,.16)}.la-hero h1{margin:0 0 6px;font-size:26px;font-weight:700}.la-card{border-radius:12px;background:#fff;border:1px solid #e5edf5;box-shadow:0 5px 16px rgba(15,23,42,.05);margin-bottom:14px}.la-kpi{padding:14px;border-radius:12px;background:#f8fafc;border:1px solid #e5edf5}.la-kpi b{font-size:22px;display:block}#dtb_leave_approval th,#dtb_leave_approval td{font-size:12px;vertical-align:middle}.select2-container{width:100%!important}.la-action{white-space:nowrap;min-width:120px}.la-pill{display:inline-block;border-radius:999px;padding:3px 9px;background:#eef2ff;color:#3730a3;font-weight:700;font-size:11px}</style>
<section class="content-header"><h1><?=hr_h('hr_leave_approval', 'Leave Approval');?> <small>SAP HCM Time Approval</small></h1><ol class="breadcrumb"><li><a href="<?=base_index();?>"><i class="fa fa-dashboard"></i> <?=hr_h('common_home', 'Home');?></a></li><li>Human Resource</li><li>Time Management</li><li class="active"><?=hr_h('hr_leave_approval', 'Leave Approval');?></li></ol></section>
<section class="content"><div class="la-hero"><div class="row"><div class="col-md-8"><h1>Leave Approval Workbench</h1><p>Approve, reject, return, dan review histori approval leave request berbasis manager dan HR step.</p></div><div class="col-md-4 text-right"><button id="btn_export_la" class="btn btn-success"><i class="fa fa-file-excel-o"></i> <?=hr_h('common_download_excel', 'Download Excel');?></button></div></div></div>
<div class="row"><div class="col-sm-3"><div class="la-kpi"><span>Total Request</span><b id="kpi_total">0</b></div></div><div class="col-sm-3"><div class="la-kpi"><span>Pending Manager</span><b id="kpi_pm">0</b></div></div><div class="col-sm-3"><div class="la-kpi"><span>Pending HR</span><b id="kpi_ph">0</b></div></div><div class="col-sm-3"><div class="la-kpi"><span><?=hr_h('hr_approved', 'Approved');?></span><b id="kpi_ap">0</b></div></div></div>
<div class="box la-card"><div class="box-header"><h3 class="box-title"><i class="fa fa-filter"></i> Filter Leave Approval</h3></div><div class="box-body"><form class="form-horizontal" onsubmit="return false;"><div class="form-group"><label class="control-label col-lg-2">Periode</label><div class="col-lg-2"><div class="input-group date la-date"><input id="filter_tgl_awal" class="form-control" value="<?=$defaultFrom;?>"><span class="input-group-addon"><span class="glyphicon glyphicon-calendar"></span></span></div></div><div class="col-lg-2"><div class="input-group date la-date"><input id="filter_tgl_akhir" class="form-control" value="<?=$defaultTo;?>"><span class="input-group-addon"><span class="glyphicon glyphicon-calendar"></span></span></div></div><label class="control-label col-lg-1"><?=hr_h('common_status', 'Status');?></label><div class="col-lg-2"><select id="filter_status" class="form-control"><option value=""><?=hr_h('common_all', 'All');?></option><option>SUBMITTED</option><option>MANAGER_APPROVED</option><option>HR_APPROVED</option><option>APPROVED</option><option>REJECTED</option><option>RETURNED</option><option>CANCELLED</option></select></div><label class="control-label col-lg-1"><?=hr_h('hr_department', 'Department');?></label><div class="col-lg-2"><select id="filter_department_code" class="form-control"></select></div></div><div class="form-group"><label class="control-label col-lg-2"><?=hr_h('common_search', 'Search');?></label><div class="col-lg-7"><input id="filter_keyword" class="form-control" placeholder="Leave no, employee"></div><div class="col-lg-3"><button id="btn_filter_la" class="btn btn-primary"><i class="fa fa-filter"></i> <?=hr_h('common_filter', 'Filter');?></button> <button id="btn_reset_la" class="btn btn-default"><i class="fa fa-refresh"></i></button></div></div></form></div></div>
<div class="box la-card"><div class="box-body"><div class="alert alert-warning error_data_delete" style="display:none"><button class="close hide_alert_notif">&times;</button><span class="isi_warning_delete"></span></div><div class="table-responsive"><table id="dtb_leave_approval" class="table table-bordered table-striped" style="width:100%"><thead><tr><th><?=hr_h('common_no', 'No');?></th><th><?=hr_h('common_action', 'Action');?></th><th>Leave</th><th><?=hr_h('hr_employee', 'Employee');?></th><th>Type</th><th><?=hr_h('hr_period', 'Period');?></th><th>Days/Quota</th><th><?=hr_h('common_status', 'Status');?></th><th>Approver</th><th>Last Approval</th></tr></thead></table></div></div></div>
<div id="modal_la_detail" class="modal fade"><div class="modal-dialog modal-lg" style="width:92%"><div class="modal-content"><div class="modal-header"><button class="close" data-dismiss="modal">&times;</button><h4 class="modal-title">Leave Approval Detail</h4></div><div class="modal-body" id="la_detail_body"></div><div class="modal-footer"><button class="btn btn-default" data-dismiss="modal"><?=hr_h('common_close', 'Close');?></button></div></div></div></div></section>
<script src="<?=base_admin();?>assets/plugins/select2/select2.min.js"></script><script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
<script>
function laErr(m){$('.isi_warning_delete').text(m||'Leave approval gagal diproses.');$('.error_data_delete').fadeIn()}function laFilters(){return{tgl_awal:$('#filter_tgl_awal').val(),tgl_akhir:$('#filter_tgl_akhir').val(),status:$('#filter_status').val(),department_code:$('#filter_department_code').val(),keyword:$('#filter_keyword').val()}}
$(function(){if($.fn.datepicker){$('.la-date').datepicker({format:'yyyy-mm-dd',autoclose:true,todayHighlight:true})}if($.fn.select2){$('#filter_status').select2({width:'100%',allowClear:true});$('#filter_department_code').select2({width:'100%',allowClear:true,placeholder:'Semua Department',ajax:{url:'<?=base_admin();?>modul/leave_approval/leave_approval_action.php?act=department_search',type:'POST',dataType:'json',delay:250,data:function(p){return{term:p.term||''}},processResults:function(d){return{results:d.results||[]}}}})}
var dt=$('#dtb_leave_approval').DataTable({bProcessing:true,bServerSide:true,pageLength:25,dom:"<'row'<'col-sm-12'B>>"+"<'row'<'col-sm-6'l><'col-sm-6'f>>"+"<'row'<'col-sm-12'tr>>"+"<'row'<'col-sm-5'i><'col-sm-7'p>>",buttons:[{extend:'collection',text:<?=hr_js('common_export_data', 'Export Data');?>,buttons:['copyHtml5','excelHtml5','csvHtml5']}],columnDefs:[{targets:[0,1],orderable:false,searchable:false}],ajax:{url:'<?=base_admin();?>modul/leave_approval/leave_approval_data.php',type:'post',data:function(d){$.extend(d,laFilters())},dataSrc:function(j){var k=j.kpi||{};$('#kpi_total').text(k.total||0);$('#kpi_pm').text(k.pending_manager||0);$('#kpi_ph').text(k.pending_hr||0);$('#kpi_ap').text(k.approved||0);return j.data||[]},error:function(x){console.log(x.responseText);laErr('Data Leave Approval gagal dimuat.')}}});$('#btn_filter_la').click(function(){dt.draw()});$('#btn_reset_la').click(function(){$('#filter_tgl_awal').val('<?=$defaultFrom;?>');$('#filter_tgl_akhir').val('<?=$defaultTo;?>');$('#filter_status,#filter_department_code').val(null).trigger('change');$('#filter_keyword').val('');dt.draw()});$('#btn_export_la').click(function(){window.location='<?=base_admin();?>modul/leave_approval/leave_approval_action.php?act=export&'+$.param(laFilters())});$('.hide_alert_notif').click(function(){$('.error_data_delete').hide()});$(document).on('click','.btn-la-detail',function(){$.post('<?=base_admin();?>modul/leave_approval/leave_approval_action.php?act=detail',{id:$(this).data('id')},function(h){$('#la_detail_body').html(h);$('#modal_la_detail').modal('show')})});$(document).on('click','.btn-la-decision',function(){var id=$(this).data('id'),no=$(this).data('no'),decision=$(this).data('decision'),step=$(this).data('step')||'FINAL';Swal.fire({title:decision+' leave?',text:no,input:'textarea',inputPlaceholder:'Catatan approval',showCancelButton:true,confirmButtonText:decision}).then(function(x){if(!x.isConfirmed)return;$.post('<?=base_admin();?>modul/leave_approval/leave_approval_action.php?act=decision',{leave_request_id:id,decision:decision,approval_step:step,approval_note:x.value||''},function(r){if(r.status==='good'){dt.draw(false);Swal.fire('Saved',r.message,'success')}else laErr(r.error_message)},'json')})})});
</script>
