<?php
if (!function_exists('hr_t')) {
  function hr_t($key, $fallback = '') { return lang_text($key, $fallback); }
}
if (!function_exists('hr_h')) {
  function hr_h($key, $fallback = '') { return htmlspecialchars((string) hr_t($key, $fallback), ENT_QUOTES, 'UTF-8'); }
}
if (!function_exists('hr_js')) {
  function hr_js($key, $fallback = '') { return json_encode(hr_t($key, $fallback), JSON_HEX_TAG | JSON_HEX_APOS | JSON_HEX_AMP | JSON_HEX_QUOT); }
}
if (session_status() === PHP_SESSION_NONE) session_start();

function tpv_h($value){ return htmlspecialchars((string)$value, ENT_QUOTES, 'UTF-8'); }
function tpv_num($value, $dec = 0){ return number_format((float)$value, $dec, '.', ','); }
function tpv_valid_date($value, $fallback){ $value = trim((string)$value); return preg_match('/^\d{4}-\d{2}-\d{2}$/', $value) ? $value : $fallback; }
function tpv_in_placeholders($count){ return implode(',', array_fill(0, max(1, (int)$count), '?')); }
function tpv_rating_class($rating){ $rating=(string)$rating; $map=array('A'=>'success','B'=>'primary','C'=>'info','D'=>'warning','E'=>'danger'); return isset($map[$rating])?$map[$rating]:'default'; }
function tpv_status_class($status){ $status=(string)$status; $map=array('DRAFT'=>'default','ASSIGNED'=>'info','ACKNOWLEDGED'=>'primary','IN_REVIEW'=>'warning','COMPLETED'=>'success','SUBMITTED'=>'primary','MANAGER_REVIEW'=>'warning','APPROVED'=>'success','REJECTED'=>'danger','RETURNED'=>'warning','CANCELLED'=>'default'); return isset($map[$status])?$map[$status]:'default'; }
function tpv_workdays($from, $to){ $s=strtotime($from); $e=strtotime($to); if(!$s||!$e||$e<$s)return 0; $n=0; for($t=$s;$t<=$e;$t=strtotime('+1 day',$t)) if((int)date('N',$t)<=5)$n++; return $n; }

if (!defined('TEAM_PERFORMANCE_VIEW_INCLUDE')) define('TEAM_PERFORMANCE_VIEW_INCLUDE', true);
require_once __DIR__ . '/team_performance_action.php';

$today = date('Y-m-d');
$from = tpv_valid_date(isset($_GET['tgl_awal']) ? $_GET['tgl_awal'] : '', date('Y-m-01'));
$to = tpv_valid_date(isset($_GET['tgl_akhir']) ? $_GET['tgl_akhir'] : '', $today);
if (strtotime($from) > strtotime($to)) $from = $to;
$filterEmployee = isset($_GET['employee_id']) ? (int)$_GET['employee_id'] : 0;
$filterDept = isset($_GET['department_code']) ? trim($_GET['department_code']) : '';
$filterRating = isset($_GET['final_rating']) ? trim($_GET['final_rating']) : '';
$filterStatus = isset($_GET['appraisal_status']) ? trim($_GET['appraisal_status']) : '';
$keyword = isset($_GET['keyword']) ? trim($_GET['keyword']) : '';

list($manager, $subIds) = tpa_manager_scope($db);
$subordinates = array();
if ($manager) {
  $stmtSub = $db->query("SELECT e.*, d.nm_dept, jt.job_title_name FROM erp_employee_master e LEFT JOIN dept d ON d.kd_dept=e.department_code LEFT JOIN erp_job_title jt ON jt.id=e.job_title_id WHERE e.manager_employee_id=? ORDER BY e.department_code,e.full_name", array((int)$manager->id));
  $subordinates = $stmtSub ? $stmtSub->fetchAll(PDO::FETCH_OBJ) : array();
}
$f = array('from'=>$from,'to'=>$to,'employee_id'=>$filterEmployee,'department_code'=>$filterDept,'final_rating'=>$filterRating,'appraisal_status'=>$filterStatus,'keyword'=>$keyword);
$rows = !empty($subIds) ? tpa_team_rows($db, $subIds, $f) : array();

$summary = array('team'=>count($subordinates),'attendance_records'=>0,'present_days'=>0,'late_count'=>0,'late_minutes'=>0,'actual_hours'=>0,'approved_ot'=>0,'leave_days'=>0,'avg_score'=>0,'rated'=>0,'pip'=>0);
$ratingChart = array(); $statusChart = array(); $scoreCategories = array(); $scoreData = array(); $lateData = array(); $presenceData = array();
$expectedSlots = tpv_workdays($from, $to);
foreach ($rows as $r) {
  $summary['attendance_records'] += (float)$r->attendance_records;
  $summary['present_days'] += (float)$r->present_days;
  $summary['late_count'] += (float)$r->late_count;
  $summary['late_minutes'] += (float)$r->late_minutes;
  $summary['actual_hours'] += (float)$r->actual_hours;
  $summary['approved_ot'] += (float)$r->approved_ot_hours;
  $summary['leave_days'] += (float)$r->leave_days_total;
  if ($r->final_score !== null && (float)$r->final_score > 0) { $summary['avg_score'] += (float)$r->final_score; $summary['rated']++; }
  if ($r->improvement_required === 'Y') $summary['pip']++;
  $rating = $r->final_rating ?: 'NO_RATING';
  if (!isset($ratingChart[$rating])) $ratingChart[$rating]=0; $ratingChart[$rating]++;
  $status = $r->appraisal_status ?: 'NO_APPRAISAL';
  if (!isset($statusChart[$status])) $statusChart[$status]=0; $statusChart[$status]++;
  $scoreCategories[] = $r->employee_no.' - '.$r->full_name;
  $scoreData[] = (float)$r->final_score;
  $lateData[] = (float)$r->late_minutes;
  $presenceData[] = $expectedSlots > 0 ? round(((float)$r->present_days / $expectedSlots) * 100, 1) : 0;
}
$summary['avg_score'] = $summary['rated'] ? round($summary['avg_score'] / $summary['rated'], 2) : 0;
$presenceRate = ($expectedSlots * max(1, $summary['team'])) > 0 ? round(($summary['present_days'] / ($expectedSlots * max(1, $summary['team']))) * 100, 1) : 0;
$ratingSeries = array(); foreach($ratingChart as $k=>$v) $ratingSeries[] = array($k, (int)$v);
$statusSeries = array(); foreach($statusChart as $k=>$v) $statusSeries[] = array($k, (int)$v);
$photoUrl = $manager ? erpkb_user_photo_url(isset($manager->foto_user) ? $manager->foto_user : '', 'back_profil_foto') : base_admin().'assets/dist/img/default-user-neutral.svg';
?>
<style>
.tp-hero{position:relative;overflow:hidden;border-radius:20px;background:linear-gradient(135deg,#312e81,#2563eb 55%,#0f766e);color:#fff;padding:24px;margin-bottom:18px;box-shadow:0 18px 42px rgba(15,23,42,.18)}.tp-hero:after{content:"";position:absolute;right:-95px;top:-120px;width:330px;height:330px;border-radius:50%;background:rgba(255,255,255,.12)}.tp-profile{position:relative;z-index:1;display:flex;gap:16px;align-items:center;flex-wrap:wrap}.tp-photo{width:72px;height:72px;border-radius:22px;object-fit:cover;background:#fff;border:3px solid rgba(255,255,255,.7)}.tp-hero h1{margin:0 0 6px;font-weight:800}.tp-hero p{margin:0;color:rgba(255,255,255,.86)}.tp-hero .btn{border-radius:999px;font-weight:700}.tp-card,.tp-filter{border:1px solid #e5edf5;border-radius:18px;background:#fff;box-shadow:0 10px 24px rgba(15,23,42,.055);margin-bottom:16px}.tp-filter .box-body,.tp-card .box-body{padding:18px 20px}.tp-card .box-header{padding:16px 20px 4px;border-bottom:0}.tp-card .box-title{font-weight:800;color:#0f172a}.tp-filter label{font-size:12px;color:#475569;text-transform:uppercase;letter-spacing:.03em}.select2-container{width:100%!important}.tp-kpi{border:1px solid #e5edf5;border-radius:18px;background:#fff;padding:16px;min-height:118px;margin-bottom:16px;box-shadow:0 8px 22px rgba(15,23,42,.045)}.tp-kpi i{width:38px;height:38px;border-radius:14px;display:inline-flex;align-items:center;justify-content:center;margin-bottom:10px;color:#fff;background:#2563eb}.tp-kpi i.green{background:#0f766e}.tp-kpi i.orange{background:#f97316}.tp-kpi i.red{background:#dc2626}.tp-kpi span{display:block;color:#64748b;font-size:12px;font-weight:800;text-transform:uppercase;letter-spacing:.04em}.tp-kpi strong{display:block;color:#0f172a;font-size:25px;line-height:1.25}.tp-kpi small{color:#64748b}.tp-chart{height:290px}.tp-chart-sm{height:255px}.tp-table>thead>tr>th{background:#f8fafc;color:#334155;font-size:12px;text-transform:uppercase;letter-spacing:.03em}.tp-table>tbody>tr>td{vertical-align:middle;font-size:12px}.tp-empty{padding:24px;border:1px dashed #cbd5e1;border-radius:18px;background:#f8fafc;color:#475569}.tp-action{white-space:nowrap}.tp-score{font-size:22px;font-weight:800;color:#0f172a}
</style>
<section class="content-header"><h1><?=hr_h('hr_team_performance', 'Team Performance');?> <small>Manager Self Service</small></h1><ol class="breadcrumb"><li><a href="<?=base_index();?>"><i class="fa fa-dashboard"></i> <?=hr_h('common_home', 'Home');?></a></li><li>Manager Self Service</li><li class="active"><?=hr_h('hr_team_performance', 'Team Performance');?></li></ol></section>
<section class="content">
  <div class="tp-hero"><div class="row"><div class="col-md-8"><div class="tp-profile"><img class="tp-photo" src="<?=tpv_h($photoUrl);?>" alt="Manager"><div><h1>Team Performance Cockpit</h1><p><?= $manager ? tpv_h($manager->employee_no.' - '.$manager->full_name) : 'Manager belum terhubung ke employee master'; ?><?= $manager && $manager->department_code ? ' | '.tpv_h($manager->department_code) : ''; ?></p><p>Gabungan KPI/appraisal, attendance discipline, overtime, dan leave untuk membaca kondisi performa bawahan.</p></div></div></div><div class="col-md-4 text-right" style="position:relative;z-index:1"><a class="btn btn-success" href="<?=base_admin();?>modul/team_performance/team_performance_action.php?act=export&<?=http_build_query($_GET);?>"><i class="fa fa-file-excel-o"></i> <?=hr_h('common_export_excel', 'Export Excel');?></a></div></div></div>
  <?php if (!$manager) { ?><div class="tp-empty"><b>Employee profile manager belum ditemukan.</b><br>User login ini belum tersambung ke `erp_employee_master.user_id`.</div><?php } elseif (empty($subordinates)) { ?><div class="tp-empty"><b>Belum ada bawahan langsung.</b><br>Isi `manager_employee_id` di Employee Master agar data performance team muncul.</div><?php } else { ?>
  <div class="box tp-filter"><div class="box-body"><form method="get" class="form-horizontal"><div class="form-group"><label class="col-lg-1 control-label"><?=hr_h('hr_date', 'Date');?></label><div class="col-lg-2"><input name="tgl_awal" class="form-control tp-date" value="<?=tpv_h($from);?>"></div><div class="col-lg-2"><input name="tgl_akhir" class="form-control tp-date" value="<?=tpv_h($to);?>"></div><label class="col-lg-1 control-label"><?=hr_h('hr_employee', 'Employee');?></label><div class="col-lg-3"><select name="employee_id" class="form-control select2-basic"><option value="">All Team Member</option><?php foreach($subordinates as $s){ ?><option value="<?=$s->id;?>" <?=$filterEmployee===(int)$s->id?'selected':'';?>><?=tpv_h($s->employee_no.' - '.$s->full_name);?></option><?php } ?></select></div><label class="col-lg-1 control-label"><?=hr_h('hr_rating', 'Rating');?></label><div class="col-lg-2"><select name="final_rating" class="form-control select2-basic"><option value="">All</option><?php foreach(array('A','B','C','D','E') as $r){ ?><option value="<?=$r;?>" <?=$filterRating===$r?'selected':'';?>><?=$r;?></option><?php } ?></select></div></div><div class="form-group"><label class="col-lg-1 control-label">Dept</label><div class="col-lg-2"><select name="department_code" class="form-control select2-basic"><option value="">All Department</option><?php $seen=array(); foreach($subordinates as $s){ if($s->department_code && !isset($seen[$s->department_code])){ $seen[$s->department_code]=1; ?><option value="<?=tpv_h($s->department_code);?>" <?=$filterDept===$s->department_code?'selected':'';?>><?=tpv_h($s->department_code.' - '.$s->nm_dept);?></option><?php }} ?></select></div><label class="col-lg-1 control-label"><?=hr_h('common_status', 'Status');?></label><div class="col-lg-2"><select name="appraisal_status" class="form-control select2-basic"><option value="">All</option><?php foreach(array('DRAFT','SELF_ASSESSED','MANAGER_REVIEW','SUBMITTED','APPROVED','REJECTED','RETURNED','CANCELLED') as $s){ ?><option value="<?=$s;?>" <?=$filterStatus===$s?'selected':'';?>><?=$s;?></option><?php } ?></select></div><label class="col-lg-1 control-label"><?=hr_h('common_search', 'Search');?></label><div class="col-lg-3"><input name="keyword" class="form-control" value="<?=tpv_h($keyword);?>" placeholder="Employee, dept, position"></div><div class="col-lg-2"><button class="btn btn-primary"><i class="fa fa-filter"></i> <?=hr_h('common_filter', 'Filter');?></button> <a class="btn btn-default" href="<?=base_index();?>team-performance"><i class="fa fa-refresh"></i></a></div></div></form></div></div>
  <div class="row"><div class="col-md-2 col-sm-6"><div class="tp-kpi"><i class="fa fa-users"></i><span>Team</span><strong><?=tpv_num($summary['team']);?></strong><small>Bawahan langsung</small></div></div><div class="col-md-2 col-sm-6"><div class="tp-kpi"><i class="fa fa-star green"></i><span>Avg Score</span><strong><?=tpv_num($summary['avg_score'],2);?></strong><small><?=tpv_num($summary['rated']);?> employee rated</small></div></div><div class="col-md-2 col-sm-6"><div class="tp-kpi"><i class="fa fa-calendar-check-o green"></i><span>Presence Rate</span><strong><?=tpv_num($presenceRate,1);?>%</strong><small><?=tpv_num($summary['present_days']);?> present days</small></div></div><div class="col-md-2 col-sm-6"><div class="tp-kpi"><i class="fa fa-clock-o orange"></i><span>Late Minutes</span><strong><?=tpv_num($summary['late_minutes']);?></strong><small><?=tpv_num($summary['late_count']);?> late records</small></div></div><div class="col-md-2 col-sm-6"><div class="tp-kpi"><i class="fa fa-hourglass-half"></i><span>Approved OT</span><strong><?=tpv_num($summary['approved_ot'],1);?></strong><small>Jam lembur approved</small></div></div><div class="col-md-2 col-sm-6"><div class="tp-kpi"><i class="fa fa-warning red"></i><span>PIP</span><strong><?=tpv_num($summary['pip']);?></strong><small>Improvement required</small></div></div></div>
  <div class="row"><div class="col-md-5"><div class="box tp-card"><div class="box-header"><h3 class="box-title">Score vs Presence</h3></div><div class="box-body"><div id="tp_score_chart" class="tp-chart"></div></div></div></div><div class="col-md-4"><div class="box tp-card"><div class="box-header"><h3 class="box-title">Late Minutes</h3></div><div class="box-body"><div id="tp_late_chart" class="tp-chart"></div></div></div></div><div class="col-md-3"><div class="box tp-card"><div class="box-header"><h3 class="box-title"><?=hr_h('hr_rating', 'Rating');?></h3></div><div class="box-body"><div id="tp_rating_chart" class="tp-chart-sm"></div></div></div></div></div>
  <div class="box tp-card"><div class="box-header"><h3 class="box-title"><i class="fa fa-list"></i> Team Performance Detail</h3></div><div class="box-body table-responsive"><div class="alert alert-warning error_data_delete" style="display:none"><button class="close hide_alert_notif">&times;</button><span class="isi_warning_delete"></span></div><table id="tp_table" class="table table-bordered table-striped tp-table" style="width:100%"><thead><tr><th><?=hr_h('hr_employee', 'Employee');?></th><th><?=hr_h('hr_attendance', 'Attendance');?></th><th>Late / Leave / OT</th><th>KPI Assignment</th><th>Appraisal</th><th>Recommendation</th><th><?=hr_h('common_action', 'Action');?></th></tr></thead><tbody><?php foreach($rows as $r){ ?><tr><td><b><?=tpv_h($r->employee_no);?></b><br><?=tpv_h($r->full_name);?><br><small><?=tpv_h(($r->department_code?:'-').' - '.($r->nm_dept?:'-'));?></small></td><td>Present <b><?=tpv_num($r->present_days);?></b><br>Absence <?=tpv_num($r->absence_days);?> | Sick <?=tpv_num($r->sick_days);?><br><small>Actual <?=tpv_num($r->actual_hours,1);?> h</small></td><td>Late <b><?=tpv_num($r->late_minutes);?></b> min<br>Leave <?=tpv_num($r->leave_days_total,1);?> days<br>Approved OT <?=tpv_num($r->approved_ot_hours,1);?> h</td><td><b><?=tpv_h($r->employee_kpi_no ?: '-');?></b><br><span class="label label-<?=tpv_status_class($r->target_status);?>"><?=tpv_h($r->target_status ?: '-');?></span><br><small>Weight <?=tpv_num($r->total_weight,2);?>%</small></td><td><span class="tp-score"><?=tpv_num($r->final_score,2);?></span> <span class="label label-<?=tpv_rating_class($r->final_rating);?>"><?=tpv_h($r->final_rating ?: '-');?></span><br><small>KPI <?=tpv_num($r->manager_kpi_score,2);?> | Comp <?=tpv_num($r->competency_score,2);?> | Beh <?=tpv_num($r->behavior_score,2);?></small><br><span class="label label-<?=tpv_status_class($r->appraisal_status);?>"><?=tpv_h($r->appraisal_status ?: '-');?></span></td><td><?=tpv_h($r->reward_recommendation ?: '-');?><br><small><?=tpv_h($r->improvement_required==='Y'?'Improvement required':'No PIP');?></small></td><td class="tp-action"><button class="btn btn-info btn-xs btn-tp-detail" data-id="<?=(int)$r->employee_id;?>"><i class="fa fa-eye"></i></button></td></tr><?php } ?></tbody></table></div></div>
  <?php } ?>
</section>
<div id="modal_tp_detail" class="modal fade"><div class="modal-dialog modal-lg" style="width:92%"><div class="modal-content"><div class="modal-header"><button class="close" data-dismiss="modal">&times;</button><h4 class="modal-title">Team Performance Detail</h4></div><div class="modal-body" id="tp_detail_body"></div><div class="modal-footer"><button class="btn btn-default" data-dismiss="modal"><?=hr_h('common_close', 'Close');?></button></div></div></div></div>
<script src="<?=base_admin();?>assets/plugins/select2/select2.min.js"></script><script src="<?=base_admin();?>assets/js/highcharts.js"></script><script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
<script>
function tpError(m){$('.isi_warning_delete').text(m||'Team Performance gagal diproses.');$('.error_data_delete').fadeIn();}
$(function(){if($.fn.datepicker){$('.tp-date').datepicker({format:'yyyy-mm-dd',autoclose:true,todayHighlight:true});}if($.fn.select2){$('.select2-basic').select2({width:'100%',allowClear:true});}if($.fn.DataTable){$('#tp_table').DataTable({pageLength:25,order:[[4,'desc']],columnDefs:[{targets:[6],orderable:false}]});}$('.hide_alert_notif').click(function(){$('.error_data_delete').hide();});$(document).on('click','.btn-tp-detail',function(){$.post('<?=base_admin();?>modul/team_performance/team_performance_action.php?act=detail',{employee_id:$(this).data('id'),tgl_awal:'<?=tpv_h($from);?>',tgl_akhir:'<?=tpv_h($to);?>'},function(html){$('#tp_detail_body').html(html);$('#modal_tp_detail').modal('show');}).fail(function(xhr){tpError(xhr.responseText);});});if(typeof Highcharts!=='undefined'&&document.getElementById('tp_score_chart')){Highcharts.chart('tp_score_chart',{chart:{zoomType:'xy'},title:{text:null},xAxis:{categories:<?=json_encode($scoreCategories);?>},yAxis:[{title:{text:'Score / Presence %'},max:100}],tooltip:{shared:true},credits:{enabled:false},series:[{name:'Final Score',type:'column',data:<?=json_encode($scoreData);?>,color:'#2563eb'},{name:'Presence %',type:'spline',data:<?=json_encode($presenceData);?>,color:'#0f766e'}]});Highcharts.chart('tp_late_chart',{chart:{type:'bar'},title:{text:null},xAxis:{categories:<?=json_encode($scoreCategories);?>},yAxis:{title:{text:'Minutes'}},legend:{enabled:false},credits:{enabled:false},series:[{name:'Late Minutes',data:<?=json_encode($lateData);?>,color:'#f97316'}]});Highcharts.chart('tp_rating_chart',{chart:{type:'pie'},title:{text:null},credits:{enabled:false},plotOptions:{pie:{innerSize:'58%',dataLabels:{enabled:true,format:'{point.name}<br>{point.y}'}}},series:[{name:'Rating',data:<?=json_encode($ratingSeries);?>}]});}});
</script>
