<?php
if (!function_exists('fin_t')) {
  function fin_t($key, $fallback = '') { return lang_text($key, $fallback); }
}
if (!function_exists('fin_h')) {
  function fin_h($key, $fallback = '') { return htmlspecialchars((string) fin_t($key, $fallback), ENT_QUOTES, 'UTF-8'); }
}
if (!function_exists('fin_js')) {
  function fin_js($key, $fallback = '') { return json_encode(fin_t($key, $fallback), JSON_HEX_TAG | JSON_HEX_APOS | JSON_HEX_AMP | JSON_HEX_QUOT); }
}
$initialOutputBufferLevel=ob_get_level();ob_start();session_start();include __DIR__."/../../inc/config.php";require_once __DIR__."/../../inc/lib/PHPExcel.php";require_once __DIR__."/../../inc/excel_style_helper.php";session_check_json();
function ti_a_h($v){return htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');}
function ti_a_n($v){return number_format((float)$v,2,'.',',');}
function ti_a_amt($v){return round((float)str_replace(',','',trim((string)$v)),2);}
function ti_a_date($d){$x=DateTime::createFromFormat('Y-m-d',$d);return $x&&$x->format('Y-m-d')===$d;}
function ti_a_user(){return $_SESSION['username']??'system';}
function ti_a_json($s,$m='',$e=array()){header('Content-Type: application/json');echo json_encode(array_merge(array('status'=>$s,'message'=>$m),$e));exit;}
function ti_a_list($db,$dir,$period,$status,$valid){$w="ti.tax_direction=? AND ti.tax_period=?";$p=array($dir,$period);if($status!==''){$w.=" AND ti.status=?";$p[]=$status;}if($valid!==''){$w.=" AND ti.validation_status=?";$p[]=$valid;}return $db->query("SELECT ti.*,tc.tax_code FROM erp_tax_invoice ti LEFT JOIN erp_tax_code tc ON tc.id=ti.tax_code_id WHERE $w ORDER BY ti.tax_invoice_date DESC,ti.id DESC",$p);}
$act=$_GET['act']??'';
try{
 if($act==='save'||$act==='post'){
  $id=(int)($_POST['id']??0);if($act==='post'&&$id&&empty($_POST['tax_invoice_no'])){$db->update('erp_tax_invoice',array('status'=>'POSTED','validation_status'=>'VALID','posted_by'=>ti_a_user(),'posted_at'=>date('Y-m-d H:i:s'),'updated_by'=>ti_a_user(),'updated_at'=>date('Y-m-d H:i:s')),'id',$id);ti_a_json('success','Tax invoice berhasil diposting.');}
  $dir=$_POST['tax_direction']==='IN'?'IN':'OUT';$no=trim($_POST['tax_invoice_no']);$date=trim($_POST['tax_invoice_date']);$period=trim($_POST['tax_period']);if($no===''||!ti_a_date($date)||!preg_match('/^\d{4}-(0[1-9]|1[0-2])$/',$period))throw new Exception('Nomor/tanggal/period pajak tidak valid.');$dpp=ti_a_amt($_POST['dpp_amount']);$vat=ti_a_amt($_POST['vat_amount']);if($dpp<=0||$vat<0)throw new Exception('DPP wajib > 0 dan VAT tidak boleh negatif.');
  $data=array('tax_direction'=>$dir,'tax_invoice_no'=>$no,'tax_invoice_date'=>$date,'tax_period'=>$period,'partner_code'=>trim($_POST['partner_code']),'partner_name'=>trim($_POST['partner_name']),'source_module'=>trim($_POST['source_module']),'source_id'=>$_POST['source_id']!==''?(int)$_POST['source_id']:null,'source_document_no'=>trim($_POST['source_document_no']),'tax_code_id'=>$_POST['tax_code_id']!==''?(int)$_POST['tax_code_id']:null,'dpp_amount'=>$dpp,'vat_amount'=>$vat,'currency'=>strtoupper(trim($_POST['currency']?:'IDR')),'description'=>trim($_POST['description']),'updated_by'=>ti_a_user(),'updated_at'=>date('Y-m-d H:i:s'));
  if($id){$old=$db->fetch("SELECT * FROM erp_tax_invoice WHERE id=? LIMIT 1",array($id));if(!$old||$old->status==='POSTED')throw new Exception('Hanya draft yang bisa diedit.');$db->update('erp_tax_invoice',$data,'id',$id);}else{if($db->fetch("SELECT id FROM erp_tax_invoice WHERE tax_direction=? AND tax_invoice_no=? LIMIT 1",array($dir,$no)))throw new Exception('Nomor faktur pajak sudah ada.');$data['status']='DRAFT';$data['validation_status']='NOT_VALIDATED';$data['created_by']=ti_a_user();$data['created_at']=date('Y-m-d H:i:s');$db->insert('erp_tax_invoice',$data);$id=$db->last_insert_id();}
  if($act==='post'){$db->update('erp_tax_invoice',array('status'=>'POSTED','validation_status'=>'VALID','posted_by'=>ti_a_user(),'posted_at'=>date('Y-m-d H:i:s')),'id',$id);ti_a_json('success','Tax invoice berhasil disimpan dan diposting.');}
  ti_a_json('success','Draft tax invoice berhasil disimpan.');
 }
 if($act==='filter'){ $dir=$_POST['tax_direction']==='IN'?'IN':'OUT';$period=$_POST['tax_period']??date('Y-m');$status=trim($_POST['status']??'');$valid=trim($_POST['validation_status']??'');$rows=ti_a_list($db,$dir,$period,$status,$valid);$html='';$dpp=0;$vat=0;$n=0;foreach($rows as $r){$n++;$dpp+=(float)$r->dpp_amount;$vat+=(float)$r->vat_amount;$cls=$r->status==='POSTED'?'success':($r->status==='CANCELLED'?'danger':'warning');$partner=trim($r->partner_code.' - '.$r->partner_name,' -');$source=trim($r->source_module.' '.$r->source_document_no);$actn='<div class="btn-group btn-group-xs"><button class="btn btn-info ti-detail" data-no="'.ti_a_h($r->tax_invoice_no).'" data-date="'.ti_a_h($r->tax_invoice_date).'" data-partner="'.ti_a_h($partner).'" data-source="'.ti_a_h($source).'" data-dpp="'.ti_a_h(ti_a_n($r->dpp_amount)).'" data-vat="'.ti_a_h(ti_a_n($r->vat_amount)).'" data-status="'.ti_a_h($r->status).'" data-validation="'.ti_a_h($r->validation_status).'" title="'.fin_h('common_detail', 'Detail').'"><i class="fa fa-eye"></i></button>';if($r->status==='DRAFT')$actn.='<button class="btn btn-success ti-post" data-id="'.$r->id.'"><i class="fa fa-check"></i></button>';$actn.='<button class="btn btn-danger ti-cancel" data-id="'.$r->id.'"><i class="fa fa-ban"></i></button></div>';$html.='<tr><td>'.$n.'</td><td>'.ti_a_h($r->tax_invoice_no).'</td><td>'.ti_a_h($r->tax_invoice_date).'</td><td>'.ti_a_h($partner).'</td><td>'.ti_a_h($source).'</td><td class="text-right">'.ti_a_n($r->dpp_amount).'</td><td class="text-right">'.ti_a_n($r->vat_amount).'</td><td><span class="label label-'.$cls.'">'.ti_a_h($r->status).'</span></td><td>'.ti_a_h($r->validation_status).'</td><td>'.$actn.'</td></tr>';}if($n===0)$html='<tr><td colspan="10" class="text-center text-muted">Tidak ada data.</td></tr>';ti_a_json('success','OK',array('html'=>$html,'dpp'=>ti_a_n($dpp),'vat'=>ti_a_n($vat),'count'=>$n));}
 if($act==='cancel'){$id=(int)($_POST['id']??0);$db->update('erp_tax_invoice',array('status'=>'CANCELLED','updated_by'=>ti_a_user(),'updated_at'=>date('Y-m-d H:i:s')),'id',$id);ti_a_json('success','Tax invoice berhasil dibatalkan.');}
 if($act==='excel'){ $dir=$_GET['tax_direction']==='IN'?'IN':'OUT';$period=$_GET['tax_period']??date('Y-m');$status=trim($_GET['status']??'');$valid=trim($_GET['validation_status']??'');$excel=new PHPExcel();$sh=$excel->setActiveSheetIndex(0);$sh->setTitle($dir==='IN'?'Tax In':'Tax Out');$headers=array(erp_export_label("No"),erp_export_label("Direction"),erp_export_label("Period"),erp_export_label("Tax Invoice"),erp_export_label("Date"),erp_export_label("Partner"),erp_export_label("Source"),erp_export_label("DPP"),erp_export_label("VAT"),erp_export_label("Status"),erp_export_label("Validation"));foreach($headers as $i=>$h)$sh->setCellValueByColumnAndRow($i,4,$h);$rn=5;$no=1;foreach(ti_a_list($db,$dir,$period,$status,$valid) as $r){$vals=array($no++,$r->tax_direction,$r->tax_period,$r->tax_invoice_no,$r->tax_invoice_date,trim($r->partner_code.' - '.$r->partner_name,' -'),$r->source_module.' '.$r->source_document_no,$r->dpp_amount,$r->vat_amount,$r->status,$r->validation_status);foreach($vals as $i=>$v)$sh->setCellValueByColumnAndRow($i,$rn,$v);$rn++;}erpkb_excel_apply_standard_style($excel,array('sheet'=>$sh,'title'=>erp_export_title('TAX INVOICE ').($dir==='IN'?'IN':'OUT'),'header_row'=>4,'first_data_row'=>5,'last_data_row'=>max(5,$rn-1),'column_count'=>count($headers),'money_columns'=>array('H','I'),'filters'=>array('Period'=>$period,'Direction'=>$dir)));while(ob_get_level()>$initialOutputBufferLevel)ob_end_clean();header('Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');header('Content-Disposition: attachment;filename="tax_invoice_'.strtolower($dir).'_'.date('YmdHis').'.xlsx"');header('Cache-Control: max-age=0');PHPExcel_IOFactory::createWriter($excel,'Excel2007')->save('php://output');exit;}
 ti_a_json('error','Action tidak dikenal.');
}catch(Exception $e){ti_a_json('error',$e->getMessage());}
