<?php
if (!function_exists('hr_t')) {
  function hr_t($key, $fallback = '') { return lang_text($key, $fallback); }
}
if (!function_exists('hr_h')) {
  function hr_h($key, $fallback = '') { return htmlspecialchars((string) hr_t($key, $fallback), ENT_QUOTES, 'UTF-8'); }
}
if (!function_exists('hr_js')) {
  function hr_js($key, $fallback = '') { return json_encode(hr_t($key, $fallback), JSON_HEX_TAG | JSON_HEX_APOS | JSON_HEX_AMP | JSON_HEX_QUOT); }
}
if (session_status() === PHP_SESSION_NONE) session_start();
include "../../inc/config.php";
session_check_json();
function pcd_h($v){return htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');}
function pcd_label($s){$map=array('DRAFT'=>'warning','ACTIVE'=>'success','INACTIVE'=>'default');$c=isset($map[$s])?$map[$s]:'default';return '<span class="label label-'.$c.'">'.pcd_h($s).'</span>';}
$draw=isset($_POST['draw'])?(int)$_POST['draw']:1;$start=isset($_POST['start'])?max(0,(int)$_POST['start']):0;$length=isset($_POST['length'])?(int)$_POST['length']:25;if($length<=0||$length>500)$length=25;
$from=isset($_POST['tgl_awal'])&&$_POST['tgl_awal']!==''?$_POST['tgl_awal']:date('Y-01-01');$to=isset($_POST['tgl_akhir'])&&$_POST['tgl_akhir']!==''?$_POST['tgl_akhir']:'9999-12-31';$type=isset($_POST['component_type'])?trim($_POST['component_type']):'';$cat=isset($_POST['component_category'])?trim($_POST['component_category']):'';$area=isset($_POST['payroll_area'])?trim($_POST['payroll_area']):'';$group=isset($_POST['employee_group'])?trim($_POST['employee_group']):'';$status=isset($_POST['component_status'])?trim($_POST['component_status']):'';$kw=isset($_POST['keyword'])?trim($_POST['keyword']):'';
$w=" WHERE pc.valid_from<=? AND pc.valid_to>=? ";$p=array($to,$from);if($type!==''){$w.=" AND pc.component_type=? ";$p[]=$type;}if($cat!==''){$w.=" AND pc.component_category=? ";$p[]=$cat;}if($area!==''){$w.=" AND pc.payroll_area=? ";$p[]=$area;}if($group!==''){$w.=" AND pc.employee_group=? ";$p[]=$group;}if($status!==''){$w.=" AND pc.component_status=? ";$p[]=$status;}if($kw!==''){$like='%'.$kw.'%';$w.=" AND (pc.component_code LIKE ? OR pc.component_name LIKE ? OR pc.wage_type_code LIKE ? OR pc.formula_text LIKE ? OR pc.sap_reference LIKE ?) ";array_push($p,$like,$like,$like,$like,$like);}
$kpi=$db->fetch("SELECT COUNT(*) total,SUM(component_status='ACTIVE') active,SUM(component_type='EARNING') earning,SUM(component_type='DEDUCTION') deduction,SUM(component_type='TAX') tax,SUM(posting_required='Y') posting FROM erp_payroll_component");
$cnt=$db->fetch("SELECT COUNT(*) jml FROM erp_payroll_component pc $w",$p);$total=$cnt?(int)$cnt->jml:0;
$orderMap=array(2=>'pc.component_code',3=>'pc.wage_type_code',4=>'pc.component_type',5=>'pc.payroll_area',6=>'pc.calculation_method',7=>'pc.default_amount',8=>'pc.sequence_no',9=>'pc.component_status',10=>'pc.updated_at');$orderBy='pc.sequence_no,pc.component_code';if(isset($_POST['order'][0]['column'])){$col=(int)$_POST['order'][0]['column'];$dir=(isset($_POST['order'][0]['dir'])&&strtolower($_POST['order'][0]['dir'])==='desc')?'DESC':'ASC';if(isset($orderMap[$col]))$orderBy=$orderMap[$col].' '.$dir;}
$rows=$db->query("SELECT pc.*,cc.cost_center_name FROM erp_payroll_component pc LEFT JOIN erp_cost_center cc ON cc.cost_center_code=pc.cost_center_code $w ORDER BY $orderBy LIMIT $start,$length",$p);
$data=array();$no=$start+1;foreach($rows as $r){$canDel=$r->component_status==='ACTIVE'?' disabled':'';$next=$r->component_status==='ACTIVE'?'INACTIVE':'ACTIVE';$act='<div class="pc-action"><button class="btn btn-info btn-xs btn-pc-detail" data-id="'.(int)$r->id.'" title="'.hr_h('common_detail', 'Detail').'"><i class="fa fa-eye"></i></button> <button class="btn btn-primary btn-xs btn-pc-edit" data-id="'.(int)$r->id.'" title="'.hr_h('common_edit', 'Edit').'"><i class="fa fa-pencil"></i></button> <button class="btn btn-warning btn-xs btn-pc-status" data-id="'.(int)$r->id.'" data-status="'.$next.'" title="'.$next.'"><i class="fa fa-refresh"></i></button> <button class="btn btn-danger btn-xs btn-pc-delete" data-id="'.(int)$r->id.'" data-no="'.pcd_h($r->component_code).'" title="'.hr_h('common_delete', 'Delete').'"'.$canDel.'><i class="fa fa-trash"></i></button></div>';
  $data[]=array($no++,$act,'<strong>'.pcd_h($r->component_code).'</strong><br><small>'.pcd_h($r->component_name).'</small>','<strong>'.pcd_h($r->wage_type_code).'</strong><br><small>Seq '.(int)$r->sequence_no.'</small>','<strong>'.pcd_h($r->component_type).'</strong><br><small>'.pcd_h($r->component_category).'</small>','<strong>'.pcd_h($r->payroll_area).'</strong><br><small>'.pcd_h($r->employee_group).'</small>','<strong>'.pcd_h($r->calculation_method).'</strong><br><small>'.pcd_h($r->calculation_base).'</small>','Amt '.number_format((float)$r->default_amount,2).'<br><small>Rate '.pcd_h($r->percentage_rate).'%</small>','Tax '.pcd_h($r->taxable).' | BPJS '.pcd_h($r->bpjs_base).'<br><small>Post '.pcd_h($r->posting_required).' / '.pcd_h($r->debit_credit).'</small>',pcd_label($r->component_status),pcd_h($r->updated_by?:$r->created_by?:'-').'<br><small>'.pcd_h($r->updated_at?:$r->created_at).'</small>');}
header('Content-Type: application/json; charset=utf-8');echo json_encode(array('draw'=>$draw,'recordsTotal'=>$total,'recordsFiltered'=>$total,'data'=>$data,'kpi'=>array('total'=>$kpi?(int)$kpi->total:0,'active'=>$kpi?(int)$kpi->active:0,'earning'=>$kpi?(int)$kpi->earning:0,'deduction'=>$kpi?(int)$kpi->deduction:0,'tax'=>$kpi?(int)$kpi->tax:0,'posting'=>$kpi?(int)$kpi->posting:0)));
?>
