<?php
if (!function_exists('fin_t')) {
  function fin_t($key, $fallback = '') { return lang_text($key, $fallback); }
}
if (!function_exists('fin_h')) {
  function fin_h($key, $fallback = '') { return htmlspecialchars((string) fin_t($key, $fallback), ENT_QUOTES, 'UTF-8'); }
}
if (!function_exists('fin_js')) {
  function fin_js($key, $fallback = '') { return json_encode(fin_t($key, $fallback), JSON_HEX_TAG | JSON_HEX_APOS | JSON_HEX_AMP | JSON_HEX_QUOT); }
}
$initialOutputBufferLevel=ob_get_level();ob_start();
session_start();
include "../../inc/config.php";
require_once "../../inc/lib/PHPExcel.php";
require_once "../../inc/excel_style_helper.php";
require_once "customer_invoice_lib.php";
session_check_json();

function ci_json($s,$m='',$e=array()){header('Content-Type: application/json');echo json_encode(array_merge(array('status'=>$s,'message'=>$m),$e));exit;}
function ci_params(){ $st=$_REQUEST['start_date']??date('Y-m-01');$en=$_REQUEST['end_date']??date('Y-m-d');if(!ci_valid_date($st)||!ci_valid_date($en)||$st>$en)throw new Exception('Periode tanggal tidak valid.');return array($st,$en,trim($_REQUEST['status']??''),trim($_REQUEST['customer_code']??''));}
function ci_list($db,$st,$en,$status,$cust){$w="COALESCE(si.posting_date,si.invoice_date) BETWEEN ? AND ?";$p=array($st,$en);if($status!==''){$w.=" AND si.billing_status=?";$p[]=$status;}if($cust!==''){$w.=" AND si.bill_to=?";$p[]=$cust;}return $db->query("SELECT si.*,COALESCE(c.nama,p.nama) customer_name,aa.nama_rek ar_account_name,ra.nama_rek revenue_account_name,ta.nama_rek tax_account_name,jh.no_jurnal,COALESCE((SELECT SUM(ip.amount) FROM erp_incoming_payment ip WHERE ip.sales_invoice_id=si.id_sales AND ip.status='POSTED'),0) paid_amount FROM sales_invoice si LEFT JOIN customer c ON c.kode_pemasok=si.bill_to LEFT JOIN penerima p ON p.kode_penerima=si.bill_to LEFT JOIN rekening aa ON aa.no_rek=si.ar_account LEFT JOIN rekening ra ON ra.no_rek=si.revenue_account LEFT JOIN rekening ta ON ta.no_rek=si.tax_account LEFT JOIN jurnal_header jh ON jh.id=si.journal_header_id WHERE $w ORDER BY COALESCE(si.posting_date,si.invoice_date) DESC,si.id_sales DESC",$p);}
function ci_sync_tax_invoice_out($db,$invoice)
{
    if((float)$invoice->tax_amount<=0)return;
    $exists=$db->fetch("SELECT id FROM erp_tax_invoice WHERE tax_direction='OUT' AND source_module='CUSTOMER_INVOICE' AND source_id=? AND status<>'CANCELLED' LIMIT 1",array($invoice->id_sales));
    $taxNo='FP-'.$invoice->no_sales_invoice;
    $period=substr($invoice->posting_date ?: $invoice->invoice_date,0,7);
    $customer=$db->fetch("SELECT nama FROM (SELECT kode_penerima code,nama FROM penerima UNION SELECT kode_pemasok code,nama FROM customer) x WHERE code=? LIMIT 1",array($invoice->bill_to));
    $data=array('tax_direction'=>'OUT','tax_invoice_no'=>$taxNo,'tax_invoice_date'=>$invoice->posting_date ?: $invoice->invoice_date,'tax_period'=>$period,'partner_code'=>$invoice->bill_to,'partner_name'=>$customer?$customer->nama:$invoice->bill_to,'source_module'=>'CUSTOMER_INVOICE','source_id'=>$invoice->id_sales,'source_document_no'=>$invoice->no_sales_invoice,'dpp_amount'=>$invoice->net_amount,'vat_amount'=>$invoice->tax_amount,'currency'=>$invoice->valuta?:'IDR','status'=>'POSTED','validation_status'=>'VALID','description'=>'Auto from Customer Invoice '.$invoice->no_sales_invoice,'updated_by'=>ci_user(),'updated_at'=>date('Y-m-d H:i:s'),'posted_by'=>ci_user(),'posted_at'=>date('Y-m-d H:i:s'));
    if($exists)$db->update('erp_tax_invoice',$data,'id',$exists->id);
    else{$data['created_by']=ci_user();$data['created_at']=date('Y-m-d H:i:s');$db->insert('erp_tax_invoice',$data);}
}

$act=$_GET['act']??'';
try{
switch($act){
case 'get_no':ci_json('success','OK',array('no'=>ci_next_no($db)));break;
case 'save':case 'post':
  $id=(int)($_POST['id_sales']??0);
  if($act==='post'&&$id&&empty($_POST['no_sales_invoice'])){$inv=$db->fetch("SELECT * FROM sales_invoice WHERE id_sales=? LIMIT 1",array($id));if(!$inv)throw new Exception('Customer invoice tidak ditemukan.');if($inv->billing_status==='CANCELLED'||$inv->billing_status==='REVERSED')throw new Exception('Invoice tidak dapat diposting.');ci_post_to_gl($db,$inv);$inv=$db->fetch("SELECT * FROM sales_invoice WHERE id_sales=? LIMIT 1",array($id));ci_sync_tax_invoice_out($db,$inv);ci_json('success','Customer invoice berhasil diposting.',array('id'=>$id));}
  $no=trim($_POST['no_sales_invoice']??'');if($no==='')$no=ci_next_no($db);
  $customer=trim($_POST['bill_to']);if(!$db->fetch("SELECT code FROM (SELECT kode_penerima code FROM penerima UNION SELECT kode_pemasok code FROM customer) x WHERE code=? LIMIT 1",array($customer)))throw new Exception('Customer tidak valid.');
  $doc=trim($_POST['invoice_date']);$post=trim($_POST['posting_date']);$due=trim($_POST['due_date']??'');if(!ci_valid_date($doc)||!ci_valid_date($post)||($due!==''&&!ci_valid_date($due)))throw new Exception('Tanggal invoice/posting/due date tidak valid.');
  if($act==='post'){$per=ci_period_open($db,$post);if($per!==true)throw new Exception($per);}
  $ar=trim($_POST['ar_account']);$rev=trim($_POST['revenue_account']);$taxAcc=trim($_POST['tax_account']??'');$net=ci_amount($_POST['net_amount']);$tax=ci_amount($_POST['tax_amount']);$gross=ci_amount($_POST['gross_amount']);if($net<=0||$gross<=0)throw new Exception('Net dan gross amount wajib lebih dari nol.');if(round($net+$tax,2)!==round($gross,2))throw new Exception('Gross amount harus sama dengan net + tax.');
  ci_account_leaf($db,$ar,'AR account');ci_account_leaf($db,$rev,'Revenue account');ci_account_leaf($db,$taxAcc,'Tax account',$tax>0);
  $data=array('billing_type'=>'F2','reference_type'=>trim($_POST['reference_type']?:'MANUAL'),'reference_no'=>trim($_POST['reference_no']),'bill_to'=>$customer,'ship_to'=>trim($_POST['ship_to']?:$customer),'invoice_date'=>$doc,'posting_date'=>$post,'due_date'=>$due!==''?$due:null,'no_sales_invoice'=>$no,'invoice_no'=>$no,'no_sales_order'=>trim($_POST['no_sales_order']),'nopo'=>trim($_POST['nopo']),'term'=>trim($_POST['term']),'valuta'=>strtoupper(trim($_POST['valuta']?:'IDR')),'tax'=>$tax>0?'1':'0','tax_code'=>trim($_POST['tax_code']?:($tax>0?'PPN-OUT':'NON_TAX')),'tax_rate'=>ci_amount($_POST['tax_rate']?:0),'ar_account'=>$ar,'revenue_account'=>$rev,'tax_account'=>$taxAcc!==''?$taxAcc:null,'net_amount'=>$net,'tax_amount'=>$tax,'gross_amount'=>$gross,'catatan'=>trim($_POST['catatan']),'created_by'=>ci_user());
  if($id){$old=$db->fetch("SELECT * FROM sales_invoice WHERE id_sales=? LIMIT 1",array($id));if(!$old)throw new Exception('Customer invoice tidak ditemukan.');if($old->billing_status!=='DRAFT')throw new Exception('Hanya draft yang boleh diedit.');$db->update('sales_invoice',$data,'id_sales',$id);$db->query("DELETE FROM sales_invoice_detail WHERE id_sales=?",array($id));}
  else{if($db->fetch("SELECT id_sales FROM sales_invoice WHERE no_sales_invoice=? LIMIT 1",array($no)))throw new Exception('Nomor invoice sudah digunakan.');$data['billing_status']='DRAFT';$data['date_created']=date('Y-m-d H:i:s');$db->insert('sales_invoice',$data);$id=$db->last_insert_id();}
  $qty=ci_amount($_POST['qty']?:1);$price=$qty>0?round($net/$qty,2):$net;
  $db->insert('sales_invoice_detail',array('id_sales'=>$id,'line_no'=>10,'billing_item_type'=>'CUSTOMER_INVOICE','kd_barang'=>trim($_POST['item_code']),'nm_barang'=>trim($_POST['item_description']?:'Customer invoice item'),'qty'=>$qty,'harga'=>$price,'unit'=>trim($_POST['unit']?:'EA'),'nilai'=>$net,'tax_code'=>$data['tax_code'],'tax_rate'=>$data['tax_rate'],'tax_amount'=>$tax,'gross_amount'=>$gross));
  if($act==='post'){$inv=$db->fetch("SELECT * FROM sales_invoice WHERE id_sales=? LIMIT 1",array($id));ci_post_to_gl($db,$inv);$inv=$db->fetch("SELECT * FROM sales_invoice WHERE id_sales=? LIMIT 1",array($id));ci_sync_tax_invoice_out($db,$inv);ci_json('success','Customer invoice berhasil disimpan dan diposting.',array('id'=>$id));}
  ci_json('success','Draft customer invoice berhasil disimpan.',array('id'=>$id));break;
case 'get':
  $id=(int)($_GET['id']??0);$r=$db->fetch("SELECT si.*,d.kd_barang item_code,d.nm_barang item_description,d.qty,d.unit FROM sales_invoice si LEFT JOIN sales_invoice_detail d ON d.id_sales=si.id_sales WHERE si.id_sales=? LIMIT 1",array($id));if(!$r)throw new Exception('Customer invoice tidak ditemukan.');ci_json('success','OK',array('data'=>$r));break;
case 'filter':
  list($st,$en,$status,$cust)=ci_params();$rows=ci_list($db,$st,$en,$status,$cust);$html='';$total=0;$open=0;$posted=0;$n=0;foreach($rows as $r){$n++;$total+=(float)$r->gross_amount;if($r->billing_status==='POSTED')$posted+=(float)$r->gross_amount;$out=max(0,(float)$r->gross_amount-(float)$r->paid_amount);$open+=$out;$cls=$r->billing_status==='POSTED'?'success':($r->billing_status==='REVERSED'?'danger':($r->billing_status==='CANCELLED'?'danger':'warning'));$actions='<div class="btn-group btn-group-xs"><button class="btn btn-info ci-detail" data-id="'.$r->id_sales.'"><i class="fa fa-search"></i></button>';if($r->billing_status==='DRAFT')$actions.='<button class="btn btn-primary ci-edit" data-id="'.$r->id_sales.'"><i class="fa fa-pencil"></i></button><button class="btn btn-success ci-post" data-id="'.$r->id_sales.'"><i class="fa fa-check"></i></button>';if($r->billing_status==='POSTED')$actions.='<button class="btn btn-warning ci-reverse" data-id="'.$r->id_sales.'"><i class="fa fa-undo"></i></button>';$actions.='</div>';$html.='<tr><td>'.$n.'</td><td>'.ci_h($r->posting_date).'</td><td>'.ci_h($r->no_sales_invoice).'</td><td>'.ci_h($r->bill_to.' - '.$r->customer_name).'</td><td><span class="label label-'.$cls.'">'.ci_h($r->billing_status).'</span></td><td>'.ci_h($r->reference_no).'</td><td class="text-right">'.ci_num($r->net_amount).'</td><td class="text-right">'.ci_num($r->tax_amount).'</td><td class="text-right">'.ci_num($r->gross_amount).'</td><td class="text-right">'.ci_num($out).'</td><td>'.ci_h($r->valuta).'</td><td>'.$actions.'</td></tr>';}if($n===0)$html='<tr><td colspan="12" class="text-center text-muted">Tidak ada data.</td></tr>';ci_json('success','OK',array('html'=>$html,'total'=>ci_num($total),'open'=>ci_num($open),'posted'=>ci_num($posted),'count'=>$n));break;
case 'detail':
  $id=(int)($_GET['id']??0);$r=$db->fetch("SELECT si.*,COALESCE(c.nama,p.nama) customer_name,aa.nama_rek ar_account_name,ra.nama_rek revenue_account_name,ta.nama_rek tax_account_name,jh.no_jurnal,COALESCE((SELECT SUM(ip.amount) FROM erp_incoming_payment ip WHERE ip.sales_invoice_id=si.id_sales AND ip.status='POSTED'),0) paid_amount FROM sales_invoice si LEFT JOIN customer c ON c.kode_pemasok=si.bill_to LEFT JOIN penerima p ON p.kode_penerima=si.bill_to LEFT JOIN rekening aa ON aa.no_rek=si.ar_account LEFT JOIN rekening ra ON ra.no_rek=si.revenue_account LEFT JOIN rekening ta ON ta.no_rek=si.tax_account LEFT JOIN jurnal_header jh ON jh.id=si.journal_header_id WHERE si.id_sales=? LIMIT 1",array($id));if(!$r)throw new Exception('Customer invoice tidak ditemukan.');$items=$db->query("SELECT * FROM sales_invoice_detail WHERE id_sales=? ORDER BY line_no,id_sales_detail",array($id));$itemHtml='';foreach($items as $it){$itemHtml.='<tr><td>'.ci_h($it->kd_barang).'</td><td>'.ci_h($it->nm_barang).'</td><td class="text-right">'.ci_num($it->qty).'</td><td>'.ci_h($it->unit).'</td><td class="text-right">'.ci_num($it->nilai).'</td></tr>';}$html='<div class="row"><div class="col-md-3"><b>'.fin_h('common_no', 'No').'</b><br>'.ci_h($r->no_sales_invoice).'</div><div class="col-md-3"><b>'.fin_h('common_status', 'Status').'</b><br>'.ci_h($r->billing_status).'</div><div class="col-md-3"><b>Journal</b><br>'.ci_h($r->no_jurnal).'</div><div class="col-md-3"><b>Outstanding</b><br>'.ci_num(max(0,(float)$r->gross_amount-(float)$r->paid_amount)).'</div></div><hr><table class="table table-bordered table-condensed"><tr><th>'.fin_h('finance_customer', 'Customer').'</th><td>'.ci_h($r->bill_to.' - '.$r->customer_name).'</td><th>'.fin_h('finance_posting_date', 'Posting Date').'</th><td>'.ci_h($r->posting_date).'</td></tr><tr><th>AR Account</th><td>'.ci_h($r->ar_account.' - '.$r->ar_account_name).'</td><th>Revenue</th><td>'.ci_h($r->revenue_account.' - '.$r->revenue_account_name).'</td></tr><tr><th>Tax Account</th><td>'.ci_h(trim($r->tax_account.' - '.$r->tax_account_name,' -')).'</td><th>'.fin_h('finance_due_date', 'Due Date').'</th><td>'.ci_h($r->due_date).'</td></tr><tr><th>Net</th><td class="text-right">'.ci_num($r->net_amount).'</td><th>'.fin_h('finance_tax', 'Tax').'</th><td class="text-right">'.ci_num($r->tax_amount).'</td></tr><tr><th>Gross</th><td class="text-right">'.ci_num($r->gross_amount).' '.ci_h($r->valuta).'</td><th>Paid</th><td class="text-right">'.ci_num($r->paid_amount).'</td></tr><tr><th>'.fin_h('finance_description', 'Description').'</th><td colspan="3">'.ci_h($r->catatan).'</td></tr></table><h4>Items</h4><table class="table table-bordered table-condensed"><thead><tr><th>Code</th><th>'.fin_h('finance_description', 'Description').'</th><th>Qty</th><th>Unit</th><th>Net</th></tr></thead><tbody>'.$itemHtml.'</tbody></table>';ci_json('success','OK',array('html'=>$html));break;
case 'reverse':
  $id=(int)($_POST['id']??0);$inv=$db->fetch("SELECT * FROM sales_invoice WHERE id_sales=? LIMIT 1",array($id));if(!$inv||$inv->billing_status!=='POSTED'||!$inv->journal_header_id)throw new Exception('Hanya invoice POSTED yang bisa reversal.');if(ci_paid_amount($db,$id)>0)throw new Exception('Invoice yang sudah dibayar tidak boleh reversal dari menu ini.');$per=ci_period_open($db,date('Y-m-d'));if($per!==true)throw new Exception($per);$lines=$db->query("SELECT * FROM jurnal_detail WHERE id_header=? ORDER BY line_no,id",array($inv->journal_header_id));$db->query("START TRANSACTION");$db->insert('jurnal_header',array('no_jurnal'=>generate_no_jurnal(),'document_type'=>'RV','posting_status'=>'POSTED','tgl_jurnal'=>date('Y-m-d'),'ket'=>'REVERSAL CUSTOMER INVOICE: '.$inv->no_sales_invoice,'no_bukti'=>'RV-'.$inv->no_sales_invoice,'source_module'=>'CUSTOMER_INVOICE_REVERSAL','source_document_no'=>$inv->no_sales_invoice,'reversal_of'=>$inv->journal_header_id,'username'=>ci_user(),'posted_by'=>ci_user(),'posted_at'=>date('Y-m-d H:i:s'),'tgl_insert'=>date('Y-m-d H:i:s')));$rev=$db->last_insert_id();$ln=1;foreach($lines as $l){$db->insert('jurnal_detail',array('id_header'=>$rev,'line_no'=>$ln++,'no_rek'=>$l->no_rek,'line_text'=>'Reversal '.$inv->no_sales_invoice,'debet'=>$l->kredit,'kredit'=>$l->debet,'valuta'=>$l->valuta,'kurs'=>$l->kurs));}$db->update('jurnal_header',array('posting_status'=>'REVERSED','updated_by'=>ci_user(),'updated_at'=>date('Y-m-d H:i:s')),'id',$inv->journal_header_id);$db->update('sales_invoice',array('billing_status'=>'REVERSED','reversal_journal_header_id'=>$rev,'cancelled_by'=>ci_user(),'cancelled_at'=>date('Y-m-d H:i:s'),'cancel_reason'=>'Reversal from Customer Invoice module'),'id_sales',$id);$db->query("UPDATE erp_tax_invoice SET status='CANCELLED',updated_by=?,updated_at=? WHERE source_module='CUSTOMER_INVOICE' AND source_id=?",array(ci_user(),date('Y-m-d H:i:s'),$id));$db->query("COMMIT");ci_json('success','Customer invoice berhasil direversal.');break;
case 'excel':
  error_reporting(E_ALL & ~E_NOTICE & ~E_WARNING & ~E_DEPRECATED & ~E_USER_DEPRECATED);
  PHPExcel_Shared_File::setUseUploadTempDirectory(true);
  list($st,$en,$status,$cust)=ci_params();$excel=new PHPExcel();$sheet=$excel->setActiveSheetIndex(0);$sheet->setTitle(erp_export_sheet_title('Customer Invoice'));$headers=array(erp_export_label("No"),erp_export_label("Posting Date"),erp_export_label("Invoice No"),erp_export_label("Customer"),erp_export_label("Status"),erp_export_label("Reference"),erp_export_label("Net"),erp_export_label("Tax"),erp_export_label("Gross"),erp_export_label("Outstanding"),erp_export_label("Currency"),erp_export_label("Journal"));foreach($headers as $i=>$h)$sheet->setCellValueByColumnAndRow($i,4,$h);$rows=ci_list($db,$st,$en,$status,$cust);$rn=5;$no=1;foreach($rows as $r){$out=max(0,(float)$r->gross_amount-(float)$r->paid_amount);$vals=array($no++,$r->posting_date,$r->no_sales_invoice,$r->bill_to.' - '.$r->customer_name,$r->billing_status,$r->reference_no,$r->net_amount,$r->tax_amount,$r->gross_amount,$out,$r->valuta,$r->no_jurnal);foreach($vals as $i=>$v)$sheet->setCellValueByColumnAndRow($i,$rn,$v);$rn++;}erpkb_excel_apply_standard_style($excel,array('sheet'=>$sheet,'title'=>erp_export_title('CUSTOMER INVOICE'),'header_row'=>4,'first_data_row'=>5,'last_data_row'=>max(5,$rn-1),'column_count'=>count($headers),'money_columns'=>array('G','H','I','J'),'filters'=>array('Periode'=>$st.' s/d '.$en,'Status'=>$status,'Customer'=>$cust)));$tmp=erpkb_excel_temp_file('customer_invoice_');PHPExcel_IOFactory::createWriter($excel,'Excel2007')->save($tmp);$size=@filesize($tmp);$sig=@file_get_contents($tmp,false,null,0,2);if(!$size||$sig!=='PK'){@unlink($tmp);while(ob_get_level()>$initialOutputBufferLevel)ob_end_clean();header('Content-Type:text/plain; charset=utf-8');echo erp_t('export_excel_invalid_file','File Excel gagal dibuat dengan benar.');exit;}while(ob_get_level()>$initialOutputBufferLevel)ob_end_clean();header('Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');header('Content-Disposition: attachment;filename="customer_invoice_'.date('YmdHis').'.xlsx"');header('Content-Length: '.$size);header('Cache-Control: max-age=0');header('Pragma: public');readfile($tmp);@unlink($tmp);exit;
default:ci_json('error','Action tidak dikenal.');
}
}catch(Exception $e){if(isset($db))$db->query("ROLLBACK");ci_json('error',$e->getMessage());}
