<?php
if (!function_exists('hr_t')) {
  function hr_t($key, $fallback = '') { return lang_text($key, $fallback); }
}
if (!function_exists('hr_h')) {
  function hr_h($key, $fallback = '') { return htmlspecialchars((string) hr_t($key, $fallback), ENT_QUOTES, 'UTF-8'); }
}
if (!function_exists('hr_js')) {
  function hr_js($key, $fallback = '') { return json_encode(hr_t($key, $fallback), JSON_HEX_TAG | JSON_HEX_APOS | JSON_HEX_AMP | JSON_HEX_QUOT); }
}
$defaultFrom=date('Y-m-01');$defaultTo=date('Y-m-t');$canInsert=isset($role_act['insert_act'])&&$role_act['insert_act']==='Y'; ?>
<style>
.pyp-hero{background:linear-gradient(135deg,#064e3b,#0ea5e9);color:#fff;border-radius:14px;padding:20px;margin-bottom:18px;box-shadow:0 10px 24px rgba(15,23,42,.16)}.pyp-hero h1{margin:0 0 6px;font-size:26px;font-weight:700}.pyp-card{border-radius:12px;background:#fff;border:1px solid #e5edf5;box-shadow:0 5px 16px rgba(15,23,42,.05);margin-bottom:14px}.pyp-kpi{padding:14px;border-radius:12px;background:#ecfdf5;border:1px solid #a7f3d0}.pyp-kpi b{font-size:22px;display:block}#dtb_payroll_posting th,#dtb_payroll_posting td{font-size:12px;vertical-align:middle}.select2-container{width:100%!important}.required-label:after{content:' *';color:#dd4b39}.pyp-action{white-space:nowrap}#modal_payroll_posting .modal-body{max-height:calc(100vh - 185px);overflow-y:auto}.pyp-section-title{font-weight:700;color:#334155;margin:8px 0 12px;border-bottom:1px solid #e5e7eb;padding-bottom:7px}.pyp-hint{background:#ecfeff;border:1px solid #a5f3fc;border-radius:10px;padding:10px;margin-bottom:10px}.pyp-summary{background:#f8fafc;border:1px dashed #cbd5e1;border-radius:10px;padding:10px;margin-bottom:10px}
</style>
<section class="content-header"><h1><?=hr_h('hr_payroll_posting', 'Payroll Posting');?> <small>SAP FI Payroll Posting</small></h1><ol class="breadcrumb"><li><a href="<?=base_index();?>"><i class="fa fa-dashboard"></i> <?=hr_h('common_home', 'Home');?></a></li><li>Human Resource</li><li>Payroll</li><li class="active"><?=hr_h('hr_payroll_posting', 'Payroll Posting');?></li></ol></section>
<section class="content">
<div class="pyp-hero"><div class="row"><div class="col-md-8"><h1>Payroll Posting Cockpit</h1><p>Posting hasil payroll ke jurnal FI: expense, payroll payable, PPh 21 payable, deduction payable, reversal, dan audit link ke payroll run.</p></div><div class="col-md-4 text-right"><?php if($canInsert){ ?><button id="btn_open_pyp" class="btn btn-warning"><i class="fa fa-plus"></i> Create Posting</button><?php } ?> <button id="btn_export_pyp" class="btn btn-success"><i class="fa fa-file-excel-o"></i> <?=hr_h('common_export_excel', 'Export Excel');?></button></div></div></div>
<div class="row"><div class="col-sm-2"><div class="pyp-kpi"><span>Total</span><b id="kpi_total">0</b></div></div><div class="col-sm-2"><div class="pyp-kpi"><span>Ready</span><b id="kpi_ready">0</b></div></div><div class="col-sm-2"><div class="pyp-kpi"><span><?=hr_h('hr_posted', 'Posted');?></span><b id="kpi_posted">0</b></div></div><div class="col-sm-2"><div class="pyp-kpi"><span>Reversed</span><b id="kpi_reversed">0</b></div></div><div class="col-sm-2"><div class="pyp-kpi"><span>Employees</span><b id="kpi_employees">0</b></div></div><div class="col-sm-2"><div class="pyp-kpi"><span>Net</span><b id="kpi_net">0</b></div></div></div>
<div class="box pyp-card"><div class="box-header"><h3 class="box-title"><i class="fa fa-filter"></i> Filter Payroll Posting</h3></div><div class="box-body"><form class="form-horizontal" onsubmit="return false;"><div class="form-group"><label class="control-label col-lg-2">Posting Date</label><div class="col-lg-2"><div class="input-group date pyp-date"><input id="filter_tgl_awal" class="form-control" value="<?=$defaultFrom;?>"><span class="input-group-addon"><span class="glyphicon glyphicon-calendar"></span></span></div></div><div class="col-lg-2"><div class="input-group date pyp-date"><input id="filter_tgl_akhir" class="form-control" value="<?=$defaultTo;?>"><span class="input-group-addon"><span class="glyphicon glyphicon-calendar"></span></span></div></div><label class="control-label col-lg-1">Area</label><div class="col-lg-2"><select id="filter_payroll_area" class="form-control"><option value="">All</option><option>MONTHLY</option><option>DAILY</option><option>WEEKLY</option><option>CONTRACT</option><option>MANAGEMENT</option><option>ALL</option></select></div><label class="control-label col-lg-1"><?=hr_h('common_status', 'Status');?></label><div class="col-lg-2"><select id="filter_posting_status" class="form-control"><option value="">All</option><option>DRAFT</option><option>READY</option><option>POSTED</option><option>REVERSED</option><option>CANCELLED</option></select></div></div><div class="form-group"><label class="control-label col-lg-2">Variant</label><div class="col-lg-2"><select id="filter_posting_variant" class="form-control"><option value="">All</option><option>SUMMARY</option><option>BY_COST_CENTER</option><option>BY_EMPLOYEE</option></select></div><label class="control-label col-lg-1">Keyword</label><div class="col-lg-3"><input id="filter_keyword" class="form-control" placeholder="Posting no, run no, ref"></div><div class="col-lg-4"><button id="btn_filter_pyp" class="btn btn-primary"><i class="fa fa-filter"></i> <?=hr_h('common_filter', 'Filter');?></button> <button id="btn_reset_pyp" class="btn btn-default"><i class="fa fa-refresh"></i></button></div></div></form></div></div>
<div class="box pyp-card"><div class="box-body"><div class="alert alert-warning error_data_delete" style="display:none"><button type="button" class="close hide_alert_notif">&times;</button><span class="isi_warning_delete"></span></div><div class="table-responsive"><table id="dtb_payroll_posting" class="table table-bordered table-striped" style="width:100%"><thead><tr><th><?=hr_h('common_no', 'No');?></th><th><?=hr_h('common_action', 'Action');?></th><th>Posting</th><th>Payroll Run</th><th><?=hr_h('hr_date', 'Date');?></th><th>Area</th><th><?=hr_h('hr_employee', 'Employee');?></th><th>Amount</th><th><?=hr_h('common_status', 'Status');?></th><th>Updated</th></tr></thead><tbody></tbody></table></div></div></div>
<div id="modal_payroll_posting" class="modal fade"><div class="modal-dialog modal-lg" style="width:94%"><div class="modal-content"><form id="form_payroll_posting"><input type="hidden" name="id" id="pyp_id"><div class="modal-header"><button type="button" class="close" data-dismiss="modal">&times;</button><h4 class="modal-title">Create Payroll Posting</h4></div><div class="modal-body"><div class="pyp-hint"><strong>SAP hint:</strong> Payroll Posting membuat FI document type <b>PY</b>. Total debit harus sama dengan total credit sebelum bisa POSTED.</div>
<div class="pyp-section-title">Posting Header</div><div class="row"><div class="col-md-3 form-group"><label class="required-label">Posting No</label><input name="posting_no" id="posting_no" class="form-control text-uppercase" required placeholder="PYP-..."></div><div class="col-md-5 form-group"><label class="required-label"><?=hr_h('hr_payroll_process', 'Payroll Process');?></label><select name="payroll_process_id" id="payroll_process_id" class="form-control"></select></div><div class="col-md-2 form-group"><label>Posting Date</label><input name="posting_date" id="posting_date" class="form-control date-field" value="<?=$defaultTo;?>"></div><div class="col-md-2 form-group"><label>Document Date</label><input name="document_date" id="document_date" class="form-control date-field" value="<?=$defaultTo;?>"></div></div>
<div class="row"><div class="col-md-2 form-group"><label>Doc Type</label><input name="document_type" id="document_type" class="form-control text-uppercase" value="PY"></div><div class="col-md-2 form-group"><label>Variant</label><select name="posting_variant" id="posting_variant" class="form-control"><option>SUMMARY</option><option>BY_COST_CENTER</option><option>BY_EMPLOYEE</option></select></div><div class="col-md-2 form-group"><label><?=hr_h('common_status', 'Status');?></label><select name="posting_status" id="posting_status" class="form-control"><option>DRAFT</option><option>READY</option><option>CANCELLED</option></select></div><div class="col-md-3 form-group"><label>External Ref</label><input name="external_reference" id="external_reference" class="form-control"></div><div class="col-md-3 form-group"><label>SAP Reference</label><input name="sap_reference" id="sap_reference" class="form-control"></div></div>
<div class="pyp-section-title">Payroll Amount Summary</div><div class="pyp-summary"><div class="row"><div class="col-sm-2"><b>Area</b><br><span id="sum_area">-</span></div><div class="col-sm-2"><b><?=hr_h('hr_employee', 'Employee');?></b><br><span id="sum_employee">0</span></div><div class="col-sm-2"><b>Gross</b><br><span id="sum_gross">0</span></div><div class="col-sm-2"><b><?=hr_h('hr_deduction', 'Deduction');?></b><br><span id="sum_deduction">0</span></div><div class="col-sm-2"><b>Tax</b><br><span id="sum_tax">0</span></div><div class="col-sm-2"><b>Net</b><br><span id="sum_net">0</span></div></div></div>
<div class="pyp-section-title">GL Accounts</div><div class="row"><div class="col-md-3 form-group"><label>Salary Expense</label><select name="salary_expense_account" id="salary_expense_account" class="form-control"></select></div><div class="col-md-3 form-group"><label>Payroll Payable</label><select name="payroll_payable_account" id="payroll_payable_account" class="form-control"></select></div><div class="col-md-3 form-group"><label>Tax Payable</label><select name="tax_payable_account" id="tax_payable_account" class="form-control"></select></div><div class="col-md-3 form-group"><label>Deduction Payable</label><select name="deduction_payable_account" id="deduction_payable_account" class="form-control"></select></div></div>
<div class="form-group"><label><?=hr_h('common_remarks', 'Remarks');?></label><input name="remarks" id="remarks" class="form-control"></div>
</div><div class="modal-footer"><button type="button" class="btn btn-default" data-dismiss="modal"><?=hr_h('common_cancel', 'Cancel');?></button><button type="submit" class="btn btn-primary"><i class="fa fa-save"></i> Save Posting</button></div></form></div></div></div>
<div id="modal_pyp_detail" class="modal fade"><div class="modal-dialog modal-lg" style="width:94%"><div class="modal-content"><div class="modal-header"><button class="close" data-dismiss="modal">&times;</button><h4 class="modal-title">Payroll Posting Detail</h4></div><div class="modal-body" id="pyp_detail_body"></div><div class="modal-footer"><button class="btn btn-default" data-dismiss="modal"><?=hr_h('common_close', 'Close');?></button></div></div></div></div>
</section>
<script src="<?=base_admin();?>assets/plugins/select2/select2.min.js"></script><script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
<script>
function pypError(m){$('.isi_warning_delete').text(m||'Payroll Posting gagal diproses.');$('.error_data_delete').fadeIn();}
function pypFilters(){return{tgl_awal:$('#filter_tgl_awal').val(),tgl_akhir:$('#filter_tgl_akhir').val(),payroll_area:$('#filter_payroll_area').val(),posting_status:$('#filter_posting_status').val(),posting_variant:$('#filter_posting_variant').val(),keyword:$('#filter_keyword').val()};}
function pypSet(s,v,t){var e=$(s);if(!v){e.val(null).trigger('change');return;}if(!e.find('option[value="'+v+'"]').length)e.append(new Option(t||v,v,true,true));e.val(v).trigger('change');}
function pypAjax(s,act,p,parent){$(s).select2({width:'100%',allowClear:true,placeholder:p,dropdownParent:parent||$(document.body),ajax:{url:'<?=base_admin();?>modul/payroll_posting/payroll_posting_action.php?act='+act,type:'POST',dataType:'json',delay:250,data:function(q){return{term:q.term||''};},processResults:function(d){return{results:d.results||[]};}}});}
function pypMoney(v){return (parseFloat(v||0)||0).toLocaleString('id-ID');}
function pypSummary(r){$('#sum_area').text(r.payroll_area||'-');$('#sum_employee').text(r.total_employee||0);$('#sum_gross').text(pypMoney(r.gross_amount));$('#sum_deduction').text(pypMoney(r.deduction_amount));$('#sum_tax').text(pypMoney(r.tax_amount));$('#sum_net').text(pypMoney(r.net_amount));}
function pypReset(title){$('#form_payroll_posting')[0].reset();$('#pyp_id').val('');$('#payroll_process_id,#salary_expense_account,#payroll_payable_account,#tax_payable_account,#deduction_payable_account').val(null).trigger('change');$('#posting_date,#document_date').val('<?=$defaultTo;?>');$('#document_type').val('PY');$('#posting_variant').val('SUMMARY').trigger('change');$('#posting_status').val('DRAFT').trigger('change');pypSummary({});$('#modal_payroll_posting .modal-title').text(title||'Create Payroll Posting');pypSet('#salary_expense_account','51301','51301 - Beban Gaji & Upah');pypSet('#payroll_payable_account','21199','21199 - Hutang Lain-Lain');pypSet('#tax_payable_account','21801','21801 - PPh 21 Yang Masih Harus Dibayar');pypSet('#deduction_payable_account','21199','21199 - Hutang Lain-Lain');}
$(function(){if($.fn.datepicker){$('.pyp-date,.date-field').datepicker({format:'yyyy-mm-dd',autoclose:true,todayHighlight:true});}if($.fn.select2){$('#filter_payroll_area,#filter_posting_status,#filter_posting_variant,#posting_variant,#posting_status').select2({width:'100%',allowClear:true});pypAjax('#payroll_process_id','process_search','Pilih Payroll Process',$('#modal_payroll_posting'));pypAjax('#salary_expense_account,#payroll_payable_account,#tax_payable_account,#deduction_payable_account','account_search','Pilih Account',$('#modal_payroll_posting'));}
var dt=$('#dtb_payroll_posting').DataTable({bProcessing:true,bServerSide:true,pageLength:25,dom:"<'row'<'col-sm-12'B>>"+"<'row'<'col-sm-6'l><'col-sm-6'f>>"+"<'row'<'col-sm-12'tr>>"+"<'row'<'col-sm-5'i><'col-sm-7'p>>",buttons:[{extend:'collection',text:<?=hr_js('common_export_data', 'Export Data');?>,buttons:['copyHtml5','excelHtml5','csvHtml5','pdfHtml5']}],columnDefs:[{targets:[0,1],orderable:false,searchable:false},{width:'42px',targets:0},{width:'170px',targets:1}],ajax:{url:'<?=base_admin();?>modul/payroll_posting/payroll_posting_data.php',type:'post',data:function(d){$.extend(d,pypFilters());},dataSrc:function(j){var k=j.kpi||{};$('#kpi_total').text(k.total||0);$('#kpi_ready').text(k.ready||0);$('#kpi_posted').text(k.posted||0);$('#kpi_reversed').text(k.reversed||0);$('#kpi_employees').text(k.employees||0);$('#kpi_net').text(pypMoney(k.net));return j.data||[];},error:function(x){console.log(x.responseText);pypError('Data Payroll Posting gagal dimuat.');}}});
$('#btn_open_pyp').click(function(){pypReset('Create Payroll Posting');$('#modal_payroll_posting').modal({backdrop:'static',keyboard:false});});$('#btn_filter_pyp').click(function(){dt.draw();});$('#filter_keyword').keyup(function(e){if(e.keyCode===13)dt.draw();});$('#btn_reset_pyp').click(function(){$('#filter_tgl_awal').val('<?=$defaultFrom;?>');$('#filter_tgl_akhir').val('<?=$defaultTo;?>');$('#filter_payroll_area,#filter_posting_status,#filter_posting_variant').val(null).trigger('change');$('#filter_keyword').val('');dt.draw();});$('#btn_export_pyp').click(function(){window.location='<?=base_admin();?>modul/payroll_posting/payroll_posting_action.php?act=export&'+$.param(pypFilters());});$('.hide_alert_notif').click(function(){$('.error_data_delete').hide();});$('#posting_no,#document_type').on('keyup change',function(){this.value=this.value.toUpperCase();});
$('#payroll_process_id').on('change',function(){var id=$(this).val();if(!id)return;$.post('<?=base_admin();?>modul/payroll_posting/payroll_posting_action.php?act=process_info',{payroll_process_id:id},function(r){if(r.status==='good')pypSummary(r);},'json');});
$('#form_payroll_posting').submit(function(e){e.preventDefault();var b=$(this).find('button[type=submit]');b.prop('disabled',true).html('<i class="fa fa-spinner fa-spin"></i> <?=hr_h('common_saving', 'Saving...');?>');$.post('<?=base_admin();?>modul/payroll_posting/payroll_posting_action.php?act=save',$(this).serialize(),function(r){b.prop('disabled',false).html('<i class="fa fa-save"></i> Save Posting');if(r.status==='good'){$('#modal_payroll_posting').modal('hide');dt.draw(false);Swal.fire('Saved','Payroll Posting berhasil disimpan.','success');}else pypError(r.error_message);},'json').fail(function(x){b.prop('disabled',false).html('<i class="fa fa-save"></i> Save Posting');pypError(x.responseText);});});
$(document).on('click','.btn-pyp-detail',function(){$.post('<?=base_admin();?>modul/payroll_posting/payroll_posting_action.php?act=detail',{id:$(this).data('id')},function(h){$('#pyp_detail_body').html(h);$('#modal_pyp_detail').modal('show');});});
$(document).on('click','.btn-pyp-edit',function(){var id=$(this).data('id');$.post('<?=base_admin();?>modul/payroll_posting/payroll_posting_action.php?act=get',{id:id},function(r){if(r.status!=='good'){pypError(r.error_message);return;}pypReset('Edit Payroll Posting');var h=r.data||{};Object.keys(h).forEach(function(k){var el=$('#'+k);if(el.length&&k!=='payroll_process_id'&&k.indexOf('_account')===-1)el.val(h[k]);});$('#pyp_id').val(h.id);pypSet('#payroll_process_id',h.payroll_process_id,h.process_text);pypSet('#salary_expense_account',h.salary_expense_account,h.salary_expense_account_text);pypSet('#payroll_payable_account',h.payroll_payable_account,h.payroll_payable_account_text);pypSet('#tax_payable_account',h.tax_payable_account,h.tax_payable_account_text);pypSet('#deduction_payable_account',h.deduction_payable_account,h.deduction_payable_account_text);$('#posting_variant,#posting_status').trigger('change');pypSummary(h);$('#modal_payroll_posting').modal({backdrop:'static',keyboard:false});},'json');});
$(document).on('click','.btn-pyp-post',function(){if($(this).is(':disabled'))return;var id=$(this).data('id');Swal.fire({title:'Post payroll to FI?',text:'Sistem akan membuat jurnal PY.',icon:'question',showCancelButton:true,confirmButtonText:'Post'}).then(function(x){if(!x.isConfirmed)return;$.post('<?=base_admin();?>modul/payroll_posting/payroll_posting_action.php?act=post',{id:id},function(r){if(r.status==='good'){dt.draw(false);Swal.fire('Posted','Payroll Posting berhasil diposting.','success');}else pypError(r.error_message);},'json').fail(function(x){pypError(x.responseText);});});});
$(document).on('click','.btn-pyp-reverse',function(){if($(this).is(':disabled'))return;var id=$(this).data('id');Swal.fire({title:'Reverse payroll posting?',text:'Jurnal reversal akan dibuat.',icon:'warning',showCancelButton:true,confirmButtonText:'Reverse'}).then(function(x){if(!x.isConfirmed)return;$.post('<?=base_admin();?>modul/payroll_posting/payroll_posting_action.php?act=reverse',{id:id},function(r){if(r.status==='good'){dt.draw(false);Swal.fire('Reversed','Payroll Posting berhasil direversal.','success');}else pypError(r.error_message);},'json').fail(function(x){pypError(x.responseText);});});});
$(document).on('click','.btn-pyp-delete',function(){if($(this).is(':disabled'))return;var id=$(this).data('id'),no=$(this).data('no');Swal.fire({title:erpLang('confirm_delete_title','Delete Confirmation'),text:no,icon:'warning',showCancelButton:true,confirmButtonText:erpLang('common_delete','Delete'),cancelButtonText:erpLang('common_cancel','Cancel')}).then(function(x){if(!x.isConfirmed)return;$.post('<?=base_admin();?>modul/payroll_posting/payroll_posting_action.php?act=delete',{id:id},function(r){if(r.status==='good'){dt.draw(false);Swal.fire(erpLang('common_deleted','Deleted'),erpLang('common_deleted_message','Data deleted successfully.'),'success');}else pypError(r.error_message);},'json').fail(function(x){pypError(x.responseText);});});});
});
</script>
