<?php
if (!function_exists('prod_t')) {
  function prod_t($key, $fallback = '') { return lang_text($key, $fallback); }
}
if (!function_exists('prod_h')) {
  function prod_h($key, $fallback = '') { return htmlspecialchars((string) prod_t($key, $fallback), ENT_QUOTES, 'UTF-8'); }
}
if (!function_exists('prod_js')) {
  function prod_js($key, $fallback = '') { return json_encode(prod_t($key, $fallback), JSON_HEX_TAG | JSON_HEX_APOS | JSON_HEX_AMP | JSON_HEX_QUOT); }
}
$defaultFrom=date('Y-m-01');$defaultTo=date('Y-m-d');
$plants=$db->query("SELECT id,plant_code,plant_name FROM erp_plant WHERE status='Aktif' ORDER BY plant_code");
$kpi=$db->fetch("SELECT COUNT(*) trace_lines,COUNT(DISTINCT gr_id) gr_count,COUNT(DISTINCT raw_material_code) raw_count,COALESCE(SUM(qty),0) trace_qty FROM erp_gr_production_trace WHERE created_at BETWEEN ? AND ?",array($defaultFrom.' 00:00:00',$defaultTo.' 23:59:59'));
?>
<style>
.ptr-hero{background:linear-gradient(135deg,#4338ca,#0f766e);color:#fff;border-radius:14px;padding:20px 22px;margin-bottom:18px;box-shadow:0 10px 24px rgba(15,23,42,.18)}.ptr-hero h1{margin:0 0 6px;font-size:26px;font-weight:700}.ptr-hero p{margin:0;opacity:.92}.ptr-card{border-radius:12px;background:#fff;border:1px solid #e5edf5;box-shadow:0 5px 16px rgba(15,23,42,.05);margin-bottom:14px}.ptr-kpi{border-radius:12px;background:#fff;border:1px solid #edf2f7;padding:15px;margin-bottom:14px}.ptr-kpi span{display:block;color:#64748b;font-size:12px;text-transform:uppercase}.ptr-kpi strong{display:block;font-size:24px;margin-top:6px}.ptr-kpi i{float:right;font-size:26px;color:#4338ca;opacity:.55}#dtb_production_traceability th,#dtb_production_traceability td{font-size:12px;vertical-align:middle}.select2-container{width:100%!important}.ptr-filter .form-group{margin-bottom:12px}
</style>
<section class="content-header"><h1><?=prod_h('production_traceability', 'Production Traceability');?> <small>SAP Batch Genealogy</small></h1><ol class="breadcrumb"><li><a href="<?=base_index();?>"><i class="fa fa-dashboard"></i> <?=prod_h('common_home', 'Home');?></a></li><li class="active"><?=prod_h('production_traceability', 'Production Traceability');?></li></ol></section>
<section class="content">
  <div class="ptr-hero"><div class="row"><div class="col-md-8"><h1>Production Traceability Workbench</h1><p>Lacak hasil produksi FG/SFG sampai bahan baku asal, lot/batch, BPB, aju, dokumen BC, dan trace inherited multi-level.</p></div><div class="col-md-4 text-right"><button id="btn_excel_ptr_top" class="btn btn-success"><i class="fa fa-file-excel-o"></i> Export Trace</button></div></div></div>
  <div class="row"><div class="col-sm-3"><div class="ptr-kpi"><i class="fa fa-random"></i><span>Trace Lines</span><strong><?=number_format((float)$kpi->trace_lines,0,',','.');?></strong></div></div><div class="col-sm-3"><div class="ptr-kpi"><i class="fa fa-file-text-o"></i><span>GR Documents</span><strong><?=number_format((float)$kpi->gr_count,0,',','.');?></strong></div></div><div class="col-sm-3"><div class="ptr-kpi"><i class="fa fa-cubes"></i><span>Raw Materials</span><strong><?=number_format((float)$kpi->raw_count,0,',','.');?></strong></div></div><div class="col-sm-3"><div class="ptr-kpi"><i class="fa fa-balance-scale"></i><span>Trace Qty</span><strong><?=number_format((float)$kpi->trace_qty,2,',','.');?></strong></div></div></div>
  <div class="box ptr-card"><div class="box-header"><h3 class="box-title"><i class="fa fa-filter"></i> Filter Traceability</h3></div><div class="box-body"><form class="form-horizontal ptr-filter" onsubmit="return false;"><div class="form-group"><label class="control-label col-lg-2">GR Posting Date</label><div class="col-lg-2"><div class="input-group date ptr-date"><input id="filter_tgl_awal" class="form-control" value="<?=$defaultFrom;?>"><span class="input-group-addon"><span class="glyphicon glyphicon-calendar"></span></span></div></div><div class="col-lg-2"><div class="input-group date ptr-date"><input id="filter_tgl_akhir" class="form-control" value="<?=$defaultTo;?>"><span class="input-group-addon"><span class="glyphicon glyphicon-calendar"></span></span></div></div><label class="control-label col-lg-1"><?=prod_h('production_plant', 'Plant');?></label><div class="col-lg-2"><select id="filter_plant_id" class="form-control"><option value=""><?=prod_h('common_all', 'All');?></option><?php foreach($plants as $p){ ?><option value="<?=intval($p->id);?>"><?=htmlspecialchars($p->plant_code.' - '.$p->plant_name,ENT_QUOTES,'UTF-8');?></option><?php } ?></select></div><label class="control-label col-lg-1">Stock Type</label><div class="col-lg-2"><select id="filter_stock_type" class="form-control"><option value=""><?=prod_h('common_all', 'All');?></option><option>UNRESTRICTED</option><option>QUALITY</option><option>BLOCKED</option></select></div></div><div class="form-group"><label class="control-label col-lg-2">Trace Source</label><div class="col-lg-2"><select id="filter_trace_source" class="form-control"><option value=""><?=prod_h('common_all', 'All');?></option><option>DIRECT</option><option>INHERITED</option></select></div><label class="control-label col-lg-1"><?=prod_h('production_material', 'Material');?></label><div class="col-lg-3"><select id="filter_material" class="form-control"></select></div><label class="control-label col-lg-1"><?=prod_h('common_search', 'Search');?></label><div class="col-lg-3"><input id="filter_keyword" class="form-control" placeholder="GR, PO, material, aju, dokumen BC, lot"></div></div><div class="form-group"><div class="col-lg-offset-2 col-lg-10"><button id="btn_filter_ptr" class="btn btn-primary"><i class="fa fa-filter"></i> <?=prod_h('common_filter', 'Filter');?></button> <button id="btn_reset_ptr" class="btn btn-default"><i class="fa fa-refresh"></i> <?=prod_h('common_reset', 'Reset');?></button> <button id="btn_excel_ptr" class="btn btn-success"><i class="fa fa-file-excel-o"></i> <?=prod_h('common_export_excel', 'Export Excel');?></button></div></div></form></div></div>
  <div class="box ptr-card"><div class="box-body"><div class="alert alert-warning error_data_delete" style="display:none"><button type="button" class="close hide_alert_notif">&times;</button><span class="isi_warning_delete"></span></div><div class="table-responsive"><table id="dtb_production_traceability" class="table table-bordered table-striped table-condensed" style="width:100%"><thead><tr><th><?=prod_h('common_no', 'No');?></th><th><?=prod_h('common_action', 'Action');?></th><th>GR / Production</th><th>Output Material</th><th>Source Material</th><th>Raw Material</th><th>Trace Qty</th><th><?=prod_h('production_uom', 'UOM');?></th><th>BC Document</th><th>Lot</th><th>BPB</th><th>Location</th><th>Trace Source</th><th><?=prod_h('common_status', 'Status');?></th></tr></thead><tbody></tbody></table></div></div></div>
  <div id="modal_detail_ptr" class="modal fade"><div class="modal-dialog modal-lg" style="width:96%"><div class="modal-content"><div class="modal-header"><button class="close" data-dismiss="modal">&times;</button><h4 class="modal-title">Production Genealogy Detail</h4></div><div class="modal-body" id="ptr_detail_body"></div><div class="modal-footer"><button class="btn btn-default" data-dismiss="modal"><?=prod_h('common_close', 'Close');?></button></div></div></div></div>
</section>
<script src="<?=base_admin();?>assets/plugins/select2/select2.min.js"></script>
<script>
function ptrError(m){$('.isi_warning_delete').text(m||<?=prod_js('production_traceability_process_failed', 'Production Traceability failed to process.');?>);$('.error_data_delete').fadeIn();}
function ptrFilters(){return{tgl_awal:$('#filter_tgl_awal').val(),tgl_akhir:$('#filter_tgl_akhir').val(),plant_id:$('#filter_plant_id').val(),stock_type:$('#filter_stock_type').val(),trace_source:$('#filter_trace_source').val(),material_code:$('#filter_material').val(),keyword:$('#filter_keyword').val()};}
function ptrQuery(){return $.param(ptrFilters());}
$(function(){if($.fn.datepicker){$('.ptr-date').datepicker({format:'yyyy-mm-dd',autoclose:true,todayHighlight:true});}if($.fn.select2){$('#filter_plant_id,#filter_stock_type,#filter_trace_source').select2({width:'100%',allowClear:true});$('#filter_material').select2({width:'100%',allowClear:true,placeholder:'Cari output/source/raw material...',minimumInputLength:1,ajax:{url:'<?=base_admin();?>modul/production_traceability/production_traceability_action.php?act=material_search',type:'POST',dataType:'json',delay:250,data:function(p){return{term:p.term||''};},processResults:function(d){return{results:d.results||[]};}}});}
var dt=$('#dtb_production_traceability').DataTable({bProcessing:true,bServerSide:true,pageLength:25,ordering:false,dom:"<'row'<'col-sm-12'B>>"+"<'row'<'col-sm-6'l><'col-sm-6'f>>"+"<'row'<'col-sm-12'tr>>"+"<'row'<'col-sm-5'i><'col-sm-7'p>>",buttons:[{extend:'collection',text:<?=prod_js('common_export_data', 'Export Data');?>,buttons:['copyHtml5','excelHtml5','csvHtml5','pdfHtml5']}],columnDefs:[{targets:[0,1],orderable:false,searchable:false},{targets:[6],className:'text-right'},{width:'38px',targets:0},{width:'58px',targets:1}],ajax:{url:'<?=base_admin();?>modul/production_traceability/production_traceability_data.php',type:'post',data:function(d){$.extend(d,ptrFilters());},error:function(xhr){console.log(xhr.responseText);ptrError(<?=prod_js('production_traceability_load_failed', 'Traceability data failed to load.');?>);}}});
$('#btn_filter_ptr').click(function(){dt.draw();});$('#filter_keyword').keyup(function(e){if(e.keyCode===13)dt.draw();});$('#btn_reset_ptr').click(function(){$('#filter_tgl_awal').val('<?=$defaultFrom;?>');$('#filter_tgl_akhir').val('<?=$defaultTo;?>');$('#filter_plant_id,#filter_stock_type,#filter_trace_source').val('').trigger('change');$('#filter_material').val(null).trigger('change');$('#filter_keyword').val('');dt.draw();});$('#btn_excel_ptr,#btn_excel_ptr_top').click(function(){window.location='<?=base_admin();?>modul/production_traceability/production_traceability_action.php?act=excel&'+ptrQuery();});
$(document).on('click','.btn-ptr-detail',function(){var el=$(this);$.post('<?=base_admin();?>modul/production_traceability/production_traceability_action.php?act=detail',{gr_id:el.data('id'),output_stock_layer_id:el.data('output-layer')},function(html){$('#ptr_detail_body').html(html);$('#modal_detail_ptr').modal('show');}).fail(function(){ptrError('Detail genealogy gagal dibuka.');});});$('.hide_alert_notif').click(function(){$('.error_data_delete').hide();});
});
</script>
