<?php
if (!function_exists('prod_t')) {
  function prod_t($key, $fallback = '') { return lang_text($key, $fallback); }
}
if (!function_exists('prod_h')) {
  function prod_h($key, $fallback = '') { return htmlspecialchars((string) prod_t($key, $fallback), ENT_QUOTES, 'UTF-8'); }
}
if (!function_exists('prod_js')) {
  function prod_js($key, $fallback = '') { return json_encode(prod_t($key, $fallback), JSON_HEX_TAG | JSON_HEX_APOS | JSON_HEX_AMP | JSON_HEX_QUOT); }
}
if(session_status()===PHP_SESSION_NONE)session_start();
include "../../inc/config.php";
session_check_json();
error_reporting(E_ALL & ~E_NOTICE & ~E_WARNING & ~E_DEPRECATED & ~E_USER_DEPRECATED);
function pta_h($v){return htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');}
function pta_num($v,$d=5){return number_format((float)$v,$d,',','.');}
$act=isset($_GET['act'])?$_GET['act']:'';
switch($act){
  case 'material_search':
    $term=isset($_POST['term'])?trim($_POST['term']):'';$like='%'.$term.'%';
    $rows=$db->query("SELECT material_code,material_name FROM (SELECT DISTINCT d.material_code,d.material_name FROM erp_gr_production_detail d UNION SELECT DISTINCT raw_material_code,raw_material_name FROM erp_gr_production_trace UNION SELECT DISTINCT source_material_code,source_material_name FROM erp_gr_production_trace) x WHERE material_code IS NOT NULL AND (?='' OR material_code LIKE ? OR material_name LIKE ?) ORDER BY material_code LIMIT 30",array($term,$like,$like));
    $res=array();foreach($rows as $r)$res[]=array('id'=>$r->material_code,'text'=>$r->material_code.' - '.$r->material_name);
    echo json_encode(array('results'=>$res));break;
  case 'detail':
    $grId=isset($_POST['gr_id'])?(int)$_POST['gr_id']:0;$outLayer=isset($_POST['output_stock_layer_id'])?(int)$_POST['output_stock_layer_id']:0;
    $h=$db->fetch("SELECT h.*,d.material_code,d.material_name,d.qty,d.uom,ep.plant_code,es.storage_code,eb.bin_code FROM erp_gr_production h JOIN erp_gr_production_detail d ON d.gr_id=h.id LEFT JOIN erp_plant ep ON ep.id=h.plant_id LEFT JOIN erp_storage_location es ON es.id=h.storage_location_id LEFT JOIN erp_storage_bin eb ON eb.id=h.storage_bin_id WHERE h.id=? LIMIT 1",array($grId));
    if(!$h){echo '<div class="alert alert-warning">Trace tidak ditemukan.</div>';break;}
    $params=array($grId);$where=" WHERE tr.gr_id=? ";if($outLayer>0){$where.=" AND tr.output_stock_layer_id=? ";$params[]=$outLayer;}
    $rows=$db->query("SELECT tr.*,d.material_code output_material_code,d.material_name output_material_name,d.qty output_qty,d.uom output_uom,sl.no_bpb output_no_bpb,sl.qty_sisa output_qty_sisa FROM erp_gr_production_trace tr JOIN erp_gr_production_detail d ON d.id=tr.gr_detail_id LEFT JOIN stock_layer sl ON sl.id=tr.output_stock_layer_id ".$where." ORDER BY tr.trace_source,tr.raw_material_code,tr.no_aju,tr.id",$params);
    echo '<h3 style="margin-top:0">'.pta_h($h->gr_no).' <small>'.pta_h($h->status).'</small></h3><div class="row"><div class="col-sm-3"><strong>Production Order</strong><br>'.pta_h($h->no_production_order).'</div><div class="col-sm-4"><strong>Output</strong><br>'.pta_h($h->material_code.' - '.$h->material_name).'</div><div class="col-sm-2"><strong>Qty</strong><br>'.pta_num($h->qty).' '.pta_h($h->uom).'</div><div class="col-sm-3"><strong>Location</strong><br>'.pta_h(trim($h->plant_code.' / '.$h->storage_code.' / '.$h->bin_code,' /')).'</div></div><hr>';
    echo '<h4>Raw Material Genealogy</h4><div class="table-responsive"><table class="table table-bordered table-condensed"><thead><tr class="bg-gray"><th>Output Layer</th><th>Source Material</th><th>Raw Material</th><th class="text-right">Trace Qty</th><th>UOM</th><th>BC Document</th><th>Lot/BPB</th><th>Source</th></tr></thead><tbody>';
    $total=0;foreach($rows as $r){$total+=(float)$r->qty;echo '<tr><td>#'.(int)$r->output_stock_layer_id.'<br><small>'.pta_h($r->output_no_bpb).'</small></td><td><strong>'.pta_h($r->source_material_code).'</strong><br><small>'.pta_h($r->source_material_name).'</small></td><td><strong>'.pta_h($r->raw_material_code).'</strong><br><small>'.pta_h($r->raw_material_name).'</small></td><td class="text-right">'.pta_num($r->qty).'</td><td>'.pta_h($r->uom).'</td><td>'.pta_h(trim(($r->jenis_dokpab?:'').' '.$r->no_aju.' / '.$r->no_dokpab)).'</td><td>'.pta_h(trim(($r->lot_no?:'-').' / '.($r->no_bpb?:'-'))).'</td><td>'.pta_h($r->trace_source).'</td></tr>';}
    echo '</tbody><tfoot><tr><th colspan="3" class="text-right">Total Trace Qty</th><th class="text-right">'.pta_num($total).'</th><th colspan="4"></th></tr></tfoot></table></div>';break;
  case 'excel':
    $initial=ob_get_level();ob_start();require_once "../../inc/lib/PHPExcel.php";require_once "../../inc/excel_style_helper.php";PHPExcel_Shared_File::setUseUploadTempDirectory(true);$from=isset($_GET['tgl_awal'])?$_GET['tgl_awal']:date('Y-m-01');$to=isset($_GET['tgl_akhir'])?$_GET['tgl_akhir']:date('Y-m-d');$traceSource=isset($_GET['trace_source'])?trim($_GET['trace_source']):'';$p=array($from,$to);$w=" WHERE h.posting_date BETWEEN ? AND ? ";if($traceSource!==''){$w.=" AND tr.trace_source=? ";$p[]=$traceSource;}
    $rows=$db->query("SELECT h.gr_no,h.no_production_order,h.confirmation_no,h.posting_date,h.status,d.material_code output_material_code,d.material_name output_material_name,d.qty output_qty,d.uom output_uom,tr.source_material_code,tr.source_material_name,tr.raw_material_code,tr.raw_material_name,tr.qty,tr.uom,tr.lot_no,tr.no_bpb,tr.no_aju,tr.jenis_dokpab,tr.no_dokpab,tr.hs_code,tr.trace_source FROM erp_gr_production_trace tr JOIN erp_gr_production h ON h.id=tr.gr_id JOIN erp_gr_production_detail d ON d.id=tr.gr_detail_id $w ORDER BY h.posting_date,h.gr_no,tr.raw_material_code",$p);
    $excel=new PHPExcel();$sh=$excel->setActiveSheetIndex(0);$sh->setTitle(erp_export_sheet_title('Prod Trace'));$heads=array(erp_export_label("No"),erp_export_label("GR No"),erp_export_label("Production Order"),erp_export_label("Confirmation"),erp_export_label("Posting Date"),erp_export_label("Output Material"),erp_export_label("Output Qty"),erp_export_label("Output UOM"),erp_export_label("Source Material"),erp_export_label("Raw Material"),erp_export_label("Trace Qty"),erp_export_label("Trace UOM"),erp_export_label("Lot"),erp_export_label("BPB"),erp_export_label("Jenis BC"),erp_export_label("No Aju"),erp_export_label("No Dok BC"),erp_export_label("HS Code"),erp_export_label("Trace Source"),erp_export_label("Status"));foreach($heads as $i=>$v)$sh->setCellValue(PHPExcel_Cell::stringFromColumnIndex($i).'4',$v);$r=5;$n=1;foreach($rows as $row){$vals=array($n++,$row->gr_no,$row->no_production_order,$row->confirmation_no,$row->posting_date,$row->output_material_code.' - '.$row->output_material_name,(float)$row->output_qty,$row->output_uom,$row->source_material_code.' - '.$row->source_material_name,$row->raw_material_code.' - '.$row->raw_material_name,(float)$row->qty,$row->uom,$row->lot_no,$row->no_bpb,$row->jenis_dokpab,$row->no_aju,$row->no_dokpab,$row->hs_code,$row->trace_source,$row->status);foreach($vals as $i=>$v)$sh->setCellValue(PHPExcel_Cell::stringFromColumnIndex($i).$r,$v);$r++;}
    erpkb_excel_apply_standard_style($excel,array('sheet'=>$sh,'title'=>erp_export_title('PRODUCTION TRACEABILITY'),'header_row'=>4,'first_data_row'=>5,'last_data_row'=>max(5,$r-1),'column_count'=>20,'numeric_columns'=>array('G','K'),'filters'=>array('Posting Date'=>$from.' s/d '.$to,'Trace Source'=>$traceSource?:erp_export_all_text())));$tmp=erpkb_excel_temp_file('production_traceability_');PHPExcel_IOFactory::createWriter($excel,'Excel2007')->save($tmp);$size=@filesize($tmp);$sig=@file_get_contents($tmp,false,null,0,2);if(!$size||$sig!=='PK'){@unlink($tmp);while(ob_get_level()>$initial)ob_end_clean();header('Content-Type:text/plain; charset=utf-8');echo erp_t('export_excel_invalid_file','File Excel gagal dibuat dengan benar.');exit;}while(ob_get_level()>$initial)ob_end_clean();header('Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');header('Content-Disposition: attachment; filename="production_traceability_'.date('Ymd_His').'.xlsx"');header('Content-Length: '.$size);header('Cache-Control: max-age=0');header('Pragma: public');readfile($tmp);@unlink($tmp);exit;
  default:header('Content-Type: application/json');echo json_encode(array('status'=>'error','error_message'=>'Action tidak dikenal.'));
}
?>
