<?php
if (!function_exists('prod_t')) {
  function prod_t($key, $fallback = '') { return lang_text($key, $fallback); }
}
if (!function_exists('prod_h')) {
  function prod_h($key, $fallback = '') { return htmlspecialchars((string) prod_t($key, $fallback), ENT_QUOTES, 'UTF-8'); }
}
if (!function_exists('prod_js')) {
  function prod_js($key, $fallback = '') { return json_encode(prod_t($key, $fallback), JSON_HEX_TAG | JSON_HEX_APOS | JSON_HEX_AMP | JSON_HEX_QUOT); }
}
$defaultFrom=date('Y-m-d',strtotime('-30 days'));$defaultTo=date('Y-m-d');
$plants=$db->query("SELECT DISTINCT plant FROM production_order WHERE plant IS NOT NULL AND plant<>'' ORDER BY plant");
$kpi=$db->fetch("SELECT COALESCE(SUM(conf.yield_qty),0) yield_qty,COALESCE(SUM(conf.scrap_qty),0) scrap_qty,COALESCE(SUM(conf.rework_qty),0) rework_qty,COALESCE(SUM(gr.gr_qty),0) gr_qty FROM production_order p LEFT JOIN(SELECT id_production_order,SUM(CASE WHEN status='POSTED' THEN yield_qty ELSE 0 END) yield_qty,SUM(CASE WHEN status='POSTED' THEN scrap_qty ELSE 0 END) scrap_qty,SUM(CASE WHEN status='POSTED' THEN rework_qty ELSE 0 END) rework_qty FROM production_order_confirmation GROUP BY id_production_order) conf ON conf.id_production_order=p.id_production_order LEFT JOIN(SELECT h.id_production_order,SUM(CASE WHEN h.status='POSTED' THEN d.qty ELSE 0 END) gr_qty FROM erp_gr_production h JOIN erp_gr_production_detail d ON d.gr_id=h.id GROUP BY h.id_production_order) gr ON gr.id_production_order=p.id_production_order WHERE p.status IN ('RELEASED','IN_PROCESS','CONFIRMED','TECO','CLOSED') AND p.start_date BETWEEN ? AND ?",array($defaultFrom,$defaultTo));
$outstanding=(float)$kpi->yield_qty-(float)$kpi->gr_qty;
?>
<style>
.om-hero{background:linear-gradient(135deg,#14532d,#1d4ed8);color:#fff;border-radius:14px;padding:20px 22px;margin-bottom:18px;box-shadow:0 10px 24px rgba(15,23,42,.18)}.om-hero h1{margin:0 0 6px;font-size:26px;font-weight:700}.om-card{border-radius:12px;background:#fff;border:1px solid #e5edf5;box-shadow:0 5px 16px rgba(15,23,42,.05);margin-bottom:14px}.om-kpi{border-radius:12px;background:#fff;border:1px solid #edf2f7;padding:15px;margin-bottom:14px}.om-kpi span{display:block;color:#64748b;font-size:12px;text-transform:uppercase}.om-kpi strong{display:block;font-size:24px;margin-top:6px}.om-kpi i{float:right;font-size:26px;color:#14532d;opacity:.55}#dtb_output_monitoring th,#dtb_output_monitoring td{font-size:12px;vertical-align:middle}.select2-container{width:100%!important}.progress-xs{height:7px}.om-progress{min-width:150px}.om-help{background:#f8fafc;border:1px dashed #cbd5e1;border-radius:10px;padding:12px;margin-bottom:14px;color:#475569}
</style>
<section class="content-header"><h1><?=prod_h('production_output_monitoring', 'Output Monitoring');?> <small><?=prod_h('production_output_cockpit_subtitle', 'SAP PP Output & GR Cockpit');?></small></h1><ol class="breadcrumb"><li><a href="<?=base_index();?>"><i class="fa fa-dashboard"></i> <?=prod_h('common_home', 'Home');?></a></li><li class="active"><?=prod_h('production_output_monitoring', 'Output Monitoring');?></li></ol></section>
<section class="content">
  <div class="om-hero"><div class="row"><div class="col-md-8"><h1><?=prod_h('production_output_monitoring_title', 'Production Output Monitoring');?></h1><p><?=prod_h('production_output_monitoring_intro', 'Monitor production output from confirmation to GR into warehouse, including outstanding yield, scrap, rework, and trace preview.');?></p></div><div class="col-md-4 text-right"><a class="btn btn-primary btn-lg" href="<?=base_index();?>gr-from-production-order"><i class="fa fa-arrow-down"></i> <?=prod_h('production_gr_from_production', 'GR from Production');?></a></div></div></div>
  <div class="row"><div class="col-sm-3"><div class="om-kpi"><i class="fa fa-check-square-o"></i><span><?=prod_h('production_total_yield', 'Total Yield');?></span><strong><?=number_format((float)$kpi->yield_qty,2,',','.');?></strong></div></div><div class="col-sm-3"><div class="om-kpi"><i class="fa fa-arrow-down"></i><span><?=prod_h('production_total_gr', 'Total GR');?></span><strong><?=number_format((float)$kpi->gr_qty,2,',','.');?></strong></div></div><div class="col-sm-3"><div class="om-kpi"><i class="fa fa-hourglass-half"></i><span><?=prod_h('production_outstanding', 'Outstanding');?></span><strong><?=number_format($outstanding,2,',','.');?></strong></div></div><div class="col-sm-3"><div class="om-kpi"><i class="fa fa-recycle"></i><span><?=prod_h('production_scrap_rework', 'Scrap/Rework');?></span><strong><?=number_format((float)$kpi->scrap_qty+(float)$kpi->rework_qty,2,',','.');?></strong></div></div></div>
  <div class="om-help"><strong><?=prod_h('production_sap_standard', 'SAP Standard');?>:</strong> <?=prod_h('production_output_help', 'Confirmation records yield/scrap/rework in production, while GR from Production Order receives production output into warehouse. Output Monitoring shows the gap between them.');?></div>
  <div class="box om-card"><div class="box-header"><h3 class="box-title"><i class="fa fa-filter"></i> <?=prod_h('production_filter_output', 'Filter Output');?></h3></div><div class="box-body"><form class="form-horizontal" onsubmit="return false;"><div class="form-group"><label class="control-label col-lg-2"><?=prod_h('production_start_date', 'Start Date');?></label><div class="col-lg-2"><div class="input-group date om-date"><input id="filter_tgl_awal" class="form-control" value="<?=$defaultFrom;?>"><span class="input-group-addon"><span class="glyphicon glyphicon-calendar"></span></span></div></div><div class="col-lg-2"><div class="input-group date om-date"><input id="filter_tgl_akhir" class="form-control" value="<?=$defaultTo;?>"><span class="input-group-addon"><span class="glyphicon glyphicon-calendar"></span></span></div></div><label class="control-label col-lg-1"><?=prod_h('production_plant', 'Plant');?></label><div class="col-lg-2"><select id="filter_plant" class="form-control"><option value=""><?=prod_h('common_all', 'All');?></option><?php foreach($plants as $p){ ?><option value="<?=htmlspecialchars($p->plant,ENT_QUOTES,'UTF-8');?>"><?=htmlspecialchars($p->plant,ENT_QUOTES,'UTF-8');?></option><?php } ?></select></div><label class="control-label col-lg-1"><?=prod_h('production_po_status', 'PO Status');?></label><div class="col-lg-2"><select id="filter_po_status" class="form-control"><option value=""><?=prod_h('common_all', 'All');?></option><option>RELEASED</option><option>IN_PROCESS</option><option>CONFIRMED</option><option>TECO</option><option>CLOSED</option></select></div></div><div class="form-group"><label class="control-label col-lg-2"><?=prod_h('production_output_status', 'Output Status');?></label><div class="col-lg-3"><select id="filter_output_status" class="form-control"><option value=""><?=prod_h('common_all', 'All');?></option><option>NO_CONFIRMATION</option><option>WAITING_GR</option><option>PARTIAL_GR</option><option>COMPLETED</option><option>OVER_GR</option></select></div><label class="control-label col-lg-1"><?=prod_h('common_search', 'Search');?></label><div class="col-lg-3"><input id="filter_keyword" class="form-control" placeholder="<?=prod_h('production_search_output_placeholder', 'PO, material, SO');?>"></div><div class="col-lg-3"><button id="btn_filter_om" class="btn btn-primary"><i class="fa fa-filter"></i> <?=prod_h('common_filter', 'Filter');?></button> <button id="btn_reset_om" class="btn btn-default"><i class="fa fa-refresh"></i> <?=prod_h('common_reset', 'Reset');?></button> <button id="btn_excel_om" class="btn btn-success"><i class="fa fa-file-excel-o"></i> <?=prod_h('common_export_excel', 'Export Excel');?></button></div></div></form></div></div>
  <div class="box om-card"><div class="box-body"><div class="alert alert-warning error_data_delete" style="display:none"><button type="button" class="close hide_alert_notif">&times;</button><span class="isi_warning_delete"></span></div><div class="table-responsive"><table id="dtb_output_monitoring" class="table table-bordered table-striped table-condensed" style="width:100%"><thead><tr><th><?=prod_h('common_no', 'No');?></th><th><?=prod_h('common_action', 'Action');?></th><th><?=prod_h('production_order', 'Production Order');?></th><th><?=prod_h('production_material', 'Material');?></th><th><?=prod_h('production_order_qty', 'Order Qty');?></th><th><?=prod_h('production_plant_sloc', 'Plant/SLoc');?></th><th><?=prod_h('production_confirmation_short', 'Confirmation');?></th><th><?=prod_h('production_gr_output', 'GR Output');?></th><th><?=prod_h('production_last_date', 'Last Date');?></th><th><?=prod_h('production_downtime', 'Downtime');?></th><th><?=prod_h('production_docs', 'Docs');?></th><th><?=prod_h('production_output_status', 'Output Status');?></th><th><?=prod_h('production_po_status', 'PO Status');?></th></tr></thead><tbody></tbody></table></div></div></div>
  <div id="modal_detail_om" class="modal fade"><div class="modal-dialog modal-lg" style="width:94%"><div class="modal-content"><div class="modal-header"><button class="close" data-dismiss="modal">&times;</button><h4 class="modal-title"><?=prod_h('production_output_detail', 'Output Detail');?></h4></div><div class="modal-body" id="om_detail_body"></div><div class="modal-footer"><a class="btn btn-success" href="<?=base_index();?>production-confirmation"><i class="fa fa-check-square-o"></i> <?=prod_h('production_confirmation_short', 'Confirmation');?></a><a class="btn btn-primary" href="<?=base_index();?>gr-from-production-order"><i class="fa fa-arrow-down"></i> <?=prod_h('production_gr_production', 'GR Production');?></a><button class="btn btn-default" data-dismiss="modal"><?=prod_h('common_close', 'Close');?></button></div></div></div></div>
</section>
<script src="<?=base_admin();?>assets/plugins/select2/select2.min.js"></script>
<script>
function omError(m){$('.isi_warning_delete').text(m||<?=prod_js('production_output_monitoring_process_failed', 'Output Monitoring failed to process.');?>);$('.error_data_delete').fadeIn();}
function omFilters(){return{tgl_awal:$('#filter_tgl_awal').val(),tgl_akhir:$('#filter_tgl_akhir').val(),plant:$('#filter_plant').val(),po_status:$('#filter_po_status').val(),output_status:$('#filter_output_status').val(),keyword:$('#filter_keyword').val()};}
function omQuery(){return $.param(omFilters());}
$(function(){if($.fn.datepicker){$('.om-date').datepicker({format:'yyyy-mm-dd',autoclose:true,todayHighlight:true});}if($.fn.select2){$('#filter_plant,#filter_po_status,#filter_output_status').select2({width:'100%',allowClear:true});}
var dt=$('#dtb_output_monitoring').DataTable({bProcessing:true,bServerSide:true,pageLength:25,ordering:false,dom:"<'row'<'col-sm-12'B>>"+"<'row'<'col-sm-6'l><'col-sm-6'f>>"+"<'row'<'col-sm-12'tr>>"+"<'row'<'col-sm-5'i><'col-sm-7'p>>",buttons:[{extend:'collection',text:<?=prod_js('common_export_data', 'Export Data');?>,buttons:['copyHtml5','excelHtml5','csvHtml5','pdfHtml5']}],columnDefs:[{targets:[0,1],orderable:false,searchable:false},{width:'38px',targets:0},{width:'100px',targets:1},{className:'om-progress',targets:[6,7]}],ajax:{url:'<?=base_admin();?>modul/output_monitoring/output_monitoring_data.php',type:'post',data:function(d){$.extend(d,omFilters());},error:function(xhr){console.log(xhr.responseText);omError(<?=prod_js('production_output_monitoring_load_failed', 'Output Monitoring data failed to load.');?>);}}});
$('#btn_filter_om').click(function(){dt.draw();});$('#filter_keyword').keyup(function(e){if(e.keyCode===13)dt.draw();});$('#btn_reset_om').click(function(){$('#filter_tgl_awal').val('<?=$defaultFrom;?>');$('#filter_tgl_akhir').val('<?=$defaultTo;?>');$('#filter_plant,#filter_po_status,#filter_output_status').val('').trigger('change');$('#filter_keyword').val('');dt.draw();});$('#btn_excel_om').click(function(){window.location='<?=base_admin();?>modul/output_monitoring/output_monitoring_action.php?act=excel&'+omQuery();});
$(document).on('click','.btn-om-detail',function(){$.post('<?=base_admin();?>modul/output_monitoring/output_monitoring_action.php?act=detail',{id:$(this).data('id')},function(html){$('#om_detail_body').html(html);$('#modal_detail_om').modal('show');}).fail(function(){omError(<?=prod_js('production_detail_open_failed', 'Detail failed to open.');?>);});});$('.hide_alert_notif').click(function(){$('.error_data_delete').hide();});
});
</script>
