<?php
if (!function_exists('prod_t')) {
  function prod_t($key, $fallback = '') { return lang_text($key, $fallback); }
}
if (!function_exists('prod_h')) {
  function prod_h($key, $fallback = '') { return htmlspecialchars((string) prod_t($key, $fallback), ENT_QUOTES, 'UTF-8'); }
}
if (!function_exists('prod_js')) {
  function prod_js($key, $fallback = '') { return json_encode(prod_t($key, $fallback), JSON_HEX_TAG | JSON_HEX_APOS | JSON_HEX_AMP | JSON_HEX_QUOT); }
}
if(session_status()===PHP_SESSION_NONE)session_start();
include "../../inc/config.php";
session_check_json();
error_reporting(E_ALL & ~E_NOTICE & ~E_WARNING & ~E_DEPRECATED & ~E_USER_DEPRECATED);
function oma_h($v){return htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');}
function oma_num($v,$d=5){return number_format((float)$v,$d,',','.');}
function oma_pct($a,$b){$b=(float)$b;return $b>0?max(0,min(999,round(((float)$a/$b)*100,1))):0;}
function oma_status_text($s){$m=array('NO_CONFIRMATION'=>'production_no_confirmation','WAITING_GR'=>'production_waiting_gr','PARTIAL_GR'=>'production_partial_gr','COMPLETED'=>'production_completed','OVER_GR'=>'production_over_gr');return prod_t(isset($m[$s])?$m[$s]:'',$s);}
$act=isset($_GET['act'])?$_GET['act']:'';
switch($act){
  case 'detail':
    $id=isset($_POST['id'])?(int)$_POST['id']:0;$po=$db->fetch("SELECT * FROM production_order WHERE id_production_order=? LIMIT 1",array($id));
    if(!$po){echo '<div class="alert alert-warning">'.prod_h('production_order_not_found','Production Order was not found.').'</div>';break;}
    $sum=$db->fetch("SELECT COALESCE((SELECT SUM(yield_qty) FROM production_order_confirmation WHERE id_production_order=? AND status='POSTED'),0) yield_qty,COALESCE((SELECT SUM(scrap_qty) FROM production_order_confirmation WHERE id_production_order=? AND status='POSTED'),0) scrap_qty,COALESCE((SELECT SUM(rework_qty) FROM production_order_confirmation WHERE id_production_order=? AND status='POSTED'),0) rework_qty,COALESCE((SELECT SUM(d.qty) FROM erp_gr_production h JOIN erp_gr_production_detail d ON d.gr_id=h.id WHERE h.id_production_order=? AND h.status='POSTED'),0) gr_qty",array($id,$id,$id,$id));
    $confs=$db->query("SELECT * FROM production_order_confirmation WHERE id_production_order=? ORDER BY posting_date,id_confirmation",array($id));
    $grs=$db->query("SELECT h.*,d.material_code,d.material_name,d.qty,d.uom,d.stock_layer_id,ep.plant_code,es.storage_code,eb.bin_code FROM erp_gr_production h JOIN erp_gr_production_detail d ON d.gr_id=h.id LEFT JOIN erp_plant ep ON ep.id=h.plant_id LEFT JOIN erp_storage_location es ON es.id=h.storage_location_id LEFT JOIN erp_storage_bin eb ON eb.id=h.storage_bin_id WHERE h.id_production_order=? ORDER BY h.posting_date,h.id",array($id));
    $trace=$db->query("SELECT h.gr_no,tr.raw_material_code,tr.raw_material_name,tr.qty,tr.uom,tr.lot_no,tr.no_bpb,tr.jenis_dokpab,tr.no_aju,tr.no_dokpab,tr.trace_source FROM erp_gr_production_trace tr JOIN erp_gr_production h ON h.id=tr.gr_id WHERE h.id_production_order=? ORDER BY h.gr_no,tr.raw_material_code,tr.id LIMIT 100",array($id));
    $outstanding=(float)$sum->yield_qty-(float)$sum->gr_qty;
    echo '<h3 style="margin-top:0">'.oma_h($po->no_production_order).' <small>'.oma_h($po->status.' / '.$po->priority).'</small></h3><div class="row"><div class="col-sm-4"><strong>'.prod_h('production_material','Material').'</strong><br>'.oma_h($po->material_code.' - '.$po->material_name).'</div><div class="col-sm-2"><strong>'.prod_h('production_order_qty','Order Qty').'</strong><br>'.oma_num($po->order_qty).' '.oma_h($po->uom).'</div><div class="col-sm-2"><strong>'.prod_h('production_yield_gr','Yield / GR').'</strong><br>'.oma_num($sum->yield_qty).' / '.oma_num($sum->gr_qty).'</div><div class="col-sm-2"><strong>'.prod_h('production_outstanding','Outstanding').'</strong><br>'.oma_num($outstanding).'</div><div class="col-sm-2"><strong>'.prod_h('production_plant_sloc','Plant/SLoc').'</strong><br>'.oma_h($po->plant.' / '.$po->storage_location).'</div></div><hr>';
    echo '<h4>'.prod_h('production_confirmations','Confirmations').'</h4><table class="table table-bordered table-condensed"><thead><tr class="bg-gray"><th>'.prod_h('production_confirmation_short','Confirmation').'</th><th>'.prod_h('production_posting','Posting').'</th><th>'.prod_h('production_operation','Operation').'</th><th>'.prod_h('production_operator','Operator').'</th><th class="text-right">'.prod_h('production_yield','Yield').'</th><th class="text-right">'.prod_h('production_scrap','Scrap').'</th><th class="text-right">'.prod_h('production_rework','Rework').'</th><th>'.prod_h('common_status','Status').'</th></tr></thead><tbody>';
    foreach($confs as $c)echo '<tr><td>'.oma_h($c->confirmation_no).'</td><td>'.oma_h($c->posting_date).'</td><td>'.oma_h($c->operation_no.' / '.$c->work_center).'</td><td>'.oma_h($c->operator_name).'</td><td class="text-right">'.oma_num($c->yield_qty).'</td><td class="text-right">'.oma_num($c->scrap_qty).'</td><td class="text-right">'.oma_num($c->rework_qty).'</td><td>'.oma_h($c->status).'</td></tr>';
    echo '</tbody></table><h4>'.prod_h('production_gr_from_production_order','GR from Production Order').'</h4><table class="table table-bordered table-condensed"><thead><tr class="bg-gray"><th>'.prod_h('production_gr_short','GR').'</th><th>'.prod_h('production_posting','Posting').'</th><th>'.prod_h('production_confirmation_short','Confirmation').'</th><th>'.prod_h('production_material','Material').'</th><th>'.prod_h('warehouse_location','Location').'</th><th class="text-right">'.prod_h('production_qty','Qty').'</th><th>'.prod_h('common_status','Status').'</th></tr></thead><tbody>';
    foreach($grs as $g)echo '<tr><td>'.oma_h($g->gr_no).'</td><td>'.oma_h($g->posting_date).'</td><td>'.oma_h($g->confirmation_no).'</td><td><strong>'.oma_h($g->material_code).'</strong><br><small>'.oma_h($g->material_name).'</small></td><td>'.oma_h(trim($g->plant_code.' / '.$g->storage_code.' / '.$g->bin_code,' /')).'</td><td class="text-right">'.oma_num($g->qty).' '.oma_h($g->uom).'</td><td>'.oma_h($g->status).'</td></tr>';
    echo '</tbody></table><h4>'.prod_h('production_trace_preview','Trace Preview').'</h4><table class="table table-bordered table-condensed"><thead><tr class="bg-gray"><th>'.prod_h('production_gr_short','GR').'</th><th>'.prod_h('production_raw_material','Raw Material').'</th><th class="text-right">'.prod_h('production_qty','Qty').'</th><th>'.prod_h('production_lot_bpb','Lot/BPB').'</th><th>'.prod_h('production_bc_document','BC Document').'</th><th>'.prod_h('production_source','Source').'</th></tr></thead><tbody>';
    foreach($trace as $t)echo '<tr><td>'.oma_h($t->gr_no).'</td><td><strong>'.oma_h($t->raw_material_code).'</strong><br><small>'.oma_h($t->raw_material_name).'</small></td><td class="text-right">'.oma_num($t->qty).' '.oma_h($t->uom).'</td><td>'.oma_h(trim($t->lot_no.' / '.$t->no_bpb,' /')).'</td><td>'.oma_h(trim($t->jenis_dokpab.' '.$t->no_aju.' / '.$t->no_dokpab,' /')).'</td><td>'.oma_h($t->trace_source).'</td></tr>';
    echo '</tbody></table>';break;
  case 'excel':
    $initial=ob_get_level();ob_start();require_once "../../inc/lib/PHPExcel.php";require_once "../../inc/excel_style_helper.php";PHPExcel_Shared_File::setUseUploadTempDirectory(true);$from=isset($_GET['tgl_awal'])?$_GET['tgl_awal']:date('Y-m-01');$to=isset($_GET['tgl_akhir'])?$_GET['tgl_akhir']:date('Y-m-d');$p=array($from,$to);$w=" WHERE p.status IN ('RELEASED','IN_PROCESS','CONFIRMED','TECO','CLOSED') AND p.start_date BETWEEN ? AND ? ";if(!empty($_GET['plant'])){$w.=" AND p.plant=? ";$p[]=$_GET['plant'];}if(!empty($_GET['po_status'])){$w.=" AND p.status=? ";$p[]=$_GET['po_status'];}
    $rows=$db->query("SELECT p.*,COALESCE(conf.conf_count,0) conf_count,COALESCE(conf.yield_qty,0) yield_qty,COALESCE(conf.scrap_qty,0) scrap_qty,COALESCE(conf.rework_qty,0) rework_qty,COALESCE(gr.gr_count,0) gr_count,COALESCE(gr.gr_qty,0) gr_qty FROM production_order p LEFT JOIN(SELECT id_production_order,COUNT(*) conf_count,SUM(CASE WHEN status='POSTED' THEN yield_qty ELSE 0 END) yield_qty,SUM(CASE WHEN status='POSTED' THEN scrap_qty ELSE 0 END) scrap_qty,SUM(CASE WHEN status='POSTED' THEN rework_qty ELSE 0 END) rework_qty FROM production_order_confirmation GROUP BY id_production_order) conf ON conf.id_production_order=p.id_production_order LEFT JOIN(SELECT h.id_production_order,COUNT(DISTINCT h.id) gr_count,SUM(CASE WHEN h.status='POSTED' THEN d.qty ELSE 0 END) gr_qty FROM erp_gr_production h JOIN erp_gr_production_detail d ON d.gr_id=h.id GROUP BY h.id_production_order) gr ON gr.id_production_order=p.id_production_order $w ORDER BY p.start_date,p.id_production_order",$p);
    $excel=new PHPExcel();$sh=$excel->setActiveSheetIndex(0);$sh->setTitle(erp_export_sheet_title(prod_t('production_output_monitoring','Output Monitoring')));$heads=array(prod_t('common_no','No'),prod_t('production_order','Production Order'),prod_t('production_po_status','PO Status'),prod_t('production_plant','Plant'),prod_t('production_material','Material'),prod_t('production_order_qty','Order Qty'),prod_t('production_uom','UOM'),prod_t('production_confirmation_count','Confirmation Count'),prod_t('production_yield','Yield'),prod_t('production_scrap','Scrap'),prod_t('production_rework','Rework'),prod_t('production_gr_count','GR Count'),prod_t('production_gr_qty','GR Qty'),prod_t('production_outstanding','Outstanding'),prod_t('production_yield_percent','Yield %'),prod_t('production_gr_percent','GR %'),prod_t('production_output_status','Output Status'));foreach($heads as $i=>$v)$sh->setCellValue(PHPExcel_Cell::stringFromColumnIndex($i).'4',$v);$r=5;$n=1;foreach($rows as $row){$out=(float)$row->yield_qty-(float)$row->gr_qty;$status='NO_CONFIRMATION';if($row->yield_qty>0&&$row->gr_qty==0)$status='WAITING_GR';if($row->gr_qty>0&&$row->gr_qty<$row->yield_qty)$status='PARTIAL_GR';if($row->yield_qty>0&&abs((float)$row->gr_qty-(float)$row->yield_qty)<0.00001)$status='COMPLETED';if($row->gr_qty>$row->yield_qty)$status='OVER_GR';$vals=array($n++,$row->no_production_order,$row->status,$row->plant,$row->material_code.' - '.$row->material_name,(float)$row->order_qty,$row->uom,(int)$row->conf_count,(float)$row->yield_qty,(float)$row->scrap_qty,(float)$row->rework_qty,(int)$row->gr_count,(float)$row->gr_qty,$out,oma_pct($row->yield_qty,$row->order_qty),oma_pct($row->gr_qty,$row->yield_qty),oma_status_text($status));foreach($vals as $i=>$v)$sh->setCellValue(PHPExcel_Cell::stringFromColumnIndex($i).$r,$v);$r++;}
    erpkb_excel_apply_standard_style($excel,array('sheet'=>$sh,'title'=>prod_t('production_output_monitoring_title','Production Output Monitoring'),'header_row'=>4,'first_data_row'=>5,'last_data_row'=>max(5,$r-1),'column_count'=>17,'numeric_columns'=>array('F','H','I','J','K','L','M','N'),'decimal_columns'=>array('O','P'),'filters'=>array(prod_t('production_start_date','Start Date')=>$from.' s/d '.$to,prod_t('production_plant','Plant')=>isset($_GET['plant'])?$_GET['plant']:erp_export_all_text(),prod_t('production_po_status','PO Status')=>isset($_GET['po_status'])?$_GET['po_status']:erp_export_all_text())));$tmp=erpkb_excel_temp_file('output_monitoring_');PHPExcel_IOFactory::createWriter($excel,'Excel2007')->save($tmp);$size=@filesize($tmp);$sig=@file_get_contents($tmp,false,null,0,2);if(!$size||$sig!=='PK'){@unlink($tmp);while(ob_get_level()>$initial)ob_end_clean();header('Content-Type:text/plain; charset=utf-8');echo erp_t('export_excel_invalid_file','File Excel gagal dibuat dengan benar.');exit;}while(ob_get_level()>$initial)ob_end_clean();header('Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');header('Content-Disposition: attachment; filename="output_monitoring_'.date('Ymd_His').'.xlsx"');header('Content-Length: '.$size);header('Cache-Control: max-age=0');header('Pragma: public');readfile($tmp);@unlink($tmp);exit;
  default:header('Content-Type: application/json');echo json_encode(array('status'=>'error','error_message'=>prod_t('common_unknown_action','Unknown action.')));
}
?>
