<?php
if (!function_exists('sd_t')) {
  function sd_t($key, $fallback = '') { return lang_text($key, $fallback); }
}
if (!function_exists('sd_h')) {
  function sd_h($key, $fallback = '') { return htmlspecialchars((string) sd_t($key, $fallback), ENT_QUOTES, 'UTF-8'); }
}
if (!function_exists('sd_js')) {
  function sd_js($key, $fallback = '') { return json_encode(sd_t($key, $fallback), JSON_HEX_TAG | JSON_HEX_APOS | JSON_HEX_AMP | JSON_HEX_QUOT); }
}
$defaultFrom=date('Y-m-01');$defaultTo=date('Y-m-d');
$customers=$db->query("SELECT kode_penerima,nama FROM penerima ORDER BY nama");
$currencies=$db->query("SELECT DISTINCT valuta FROM sales_invoice WHERE valuta IS NOT NULL AND valuta<>'' ORDER BY valuta");
$kpi=$db->fetch("SELECT COUNT(*) invoice_count,COALESCE(SUM(d.subtotal),0) subtotal,COALESCE(SUM(CASE WHEN si.tax='1' THEN d.subtotal*0.11 ELSE 0 END),0) tax_amount,COALESCE(SUM(d.subtotal + CASE WHEN si.tax='1' THEN d.subtotal*0.11 ELSE 0 END),0) grand_total FROM sales_invoice si LEFT JOIN (SELECT id_sales,SUM(nilai) subtotal FROM sales_invoice_detail GROUP BY id_sales) d ON d.id_sales=si.id_sales WHERE si.invoice_date BETWEEN ? AND ?",array($defaultFrom,$defaultTo));
?>
<style>
.bh-hero{background:linear-gradient(135deg,#0f172a,#2563eb);color:#fff;border-radius:14px;padding:20px 22px;margin-bottom:18px;box-shadow:0 10px 24px rgba(15,23,42,.18)}.bh-hero h1{margin:0 0 6px;font-size:26px;font-weight:700}.bh-card{border-radius:12px;background:#fff;border:1px solid #e5edf5;box-shadow:0 5px 16px rgba(15,23,42,.05);margin-bottom:14px}.bh-kpi{border-radius:12px;background:#fff;border:1px solid #edf2f7;padding:15px;margin-bottom:14px}.bh-kpi span{display:block;color:#64748b;font-size:12px;text-transform:uppercase}.bh-kpi strong{display:block;font-size:22px;margin-top:6px}.bh-kpi i{float:right;font-size:26px;color:#2563eb;opacity:.55}#dtb_billing_history th,#dtb_billing_history td{font-size:12px;vertical-align:middle}.select2-container{width:100%!important}.bh-help{background:#f8fafc;border:1px dashed #cbd5e1;border-radius:10px;padding:12px;margin-bottom:14px;color:#475569}
</style>
<section class="content-header"><h1><?=sd_h('sales_billing_history', 'Billing History');?> <small>SAP SD Billing Document History</small></h1><ol class="breadcrumb"><li><a href="<?=base_index();?>"><i class="fa fa-dashboard"></i> <?=sd_h('common_home', 'Home');?></a></li><li class="active"><?=sd_h('sales_billing_history', 'Billing History');?></li></ol></section>
<section class="content">
  <div class="bh-hero"><div class="row"><div class="col-md-8"><h1>Billing History Cockpit</h1><p>Histori dokumen billing/invoice pelanggan untuk monitoring invoice, nilai, pajak, customer, referensi sales order dan surat jalan.</p></div><div class="col-md-4 text-right"><a class="btn btn-warning btn-lg" href="<?=base_index();?>sales-invoice"><i class="fa fa-file-text"></i> <?=sd_h('sales_invoice', 'Sales Invoice');?></a></div></div></div>
  <div class="row"><div class="col-sm-3"><div class="bh-kpi"><i class="fa fa-file-text-o"></i><span>Invoices</span><strong><?=number_format((float)$kpi->invoice_count,0,',','.');?></strong></div></div><div class="col-sm-3"><div class="bh-kpi"><i class="fa fa-calculator"></i><span>DPP</span><strong><?=number_format((float)$kpi->subtotal,2,',','.');?></strong></div></div><div class="col-sm-3"><div class="bh-kpi"><i class="fa fa-percent"></i><span>PPN</span><strong><?=number_format((float)$kpi->tax_amount,2,',','.');?></strong></div></div><div class="col-sm-3"><div class="bh-kpi"><i class="fa fa-money"></i><span>Grand Total</span><strong><?=number_format((float)$kpi->grand_total,2,',','.');?></strong></div></div></div>
  <div class="bh-help"><strong>Standar SAP:</strong> Billing History adalah layar monitoring dokumen billing yang sudah dibuat. Pembuatan invoice tetap di menu Sales Invoice, sedangkan histori ini fokus audit, print, filter, dan export.</div>
  <div class="box bh-card"><div class="box-header"><h3 class="box-title"><i class="fa fa-filter"></i> Filter Billing</h3></div><div class="box-body"><form class="form-horizontal" onsubmit="return false;"><div class="form-group"><label class="control-label col-lg-2">Invoice Date</label><div class="col-lg-2"><div class="input-group date bh-date"><input id="filter_tgl_awal" class="form-control" value="<?=$defaultFrom;?>"><span class="input-group-addon"><span class="glyphicon glyphicon-calendar"></span></span></div></div><div class="col-lg-2"><div class="input-group date bh-date"><input id="filter_tgl_akhir" class="form-control" value="<?=$defaultTo;?>"><span class="input-group-addon"><span class="glyphicon glyphicon-calendar"></span></span></div></div><label class="control-label col-lg-1"><?=sd_h('sales_customer', 'Customer');?></label><div class="col-lg-3"><select id="filter_customer" class="form-control"><option value=""><?=sd_h('common_all', 'All');?></option><?php foreach($customers as $c){ ?><option value="<?=htmlspecialchars($c->kode_penerima,ENT_QUOTES,'UTF-8');?>"><?=htmlspecialchars($c->nama,ENT_QUOTES,'UTF-8');?></option><?php } ?></select></div><div class="col-lg-2"><select id="filter_currency" class="form-control"><option value=""><?=sd_h('sales_currency', 'Currency');?></option><?php foreach($currencies as $c){ ?><option value="<?=htmlspecialchars($c->valuta,ENT_QUOTES,'UTF-8');?>"><?=htmlspecialchars($c->valuta,ENT_QUOTES,'UTF-8');?></option><?php } ?></select></div></div><div class="form-group"><label class="control-label col-lg-2">Tax Status</label><div class="col-lg-2"><select id="filter_tax_status" class="form-control"><option value=""><?=sd_h('common_all', 'All');?></option><option>TAXED</option><option>NO_TAX</option></select></div><label class="control-label col-lg-1"><?=sd_h('common_search', 'Search');?></label><div class="col-lg-4"><input id="filter_keyword" class="form-control" placeholder="Invoice, SO, SJ/DO, PO, customer"></div><div class="col-lg-3"><button id="btn_filter_bh" class="btn btn-primary"><i class="fa fa-filter"></i> <?=sd_h('common_filter', 'Filter');?></button> <button id="btn_reset_bh" class="btn btn-default"><i class="fa fa-refresh"></i> <?=sd_h('common_reset', 'Reset');?></button> <button id="btn_excel_bh" class="btn btn-success"><i class="fa fa-file-excel-o"></i> <?=sd_h('common_export_excel', 'Export Excel');?></button></div></div></form></div></div>
  <div class="box bh-card"><div class="box-body"><div class="alert alert-warning error_data_delete" style="display:none"><button type="button" class="close hide_alert_notif">&times;</button><span class="isi_warning_delete"></span></div><div class="table-responsive"><table id="dtb_billing_history" class="table table-bordered table-striped table-condensed" style="width:100%"><thead><tr><th><?=sd_h('common_no', 'No');?></th><th><?=sd_h('common_action', 'Action');?></th><th>Invoice</th><th><?=sd_h('sales_customer', 'Customer');?></th><th><?=sd_h('sales_reference', 'Reference');?></th><th>Term</th><th><?=sd_h('sales_items', 'Items');?></th><th><?=sd_h('sales_amount', 'Amount');?></th><th><?=sd_h('common_status', 'Status');?></th><th>Signed</th><th>Notes</th></tr></thead><tbody></tbody></table></div></div></div>
  <div id="modal_detail_bh" class="modal fade"><div class="modal-dialog modal-lg" style="width:94%"><div class="modal-content"><div class="modal-header"><button class="close" data-dismiss="modal">&times;</button><h4 class="modal-title">Billing Detail</h4></div><div class="modal-body" id="bh_detail_body"></div><div class="modal-footer"><a class="btn btn-warning" href="<?=base_index();?>sales-invoice"><i class="fa fa-file-text"></i> <?=sd_h('sales_invoice', 'Sales Invoice');?></a><button class="btn btn-default" data-dismiss="modal"><?=sd_h('common_close', 'Close');?></button></div></div></div></div>
</section>
<script src="<?=base_admin();?>assets/plugins/select2/select2.min.js"></script>
<script>
function bhError(m){$('.isi_warning_delete').text(m||<?=sd_js('sales_billing_history_process_failed', 'Billing History failed to process.');?>);$('.error_data_delete').fadeIn();}
function bhFilters(){return{tgl_awal:$('#filter_tgl_awal').val(),tgl_akhir:$('#filter_tgl_akhir').val(),customer:$('#filter_customer').val(),currency:$('#filter_currency').val(),tax_status:$('#filter_tax_status').val(),keyword:$('#filter_keyword').val()};}
function bhQuery(){return $.param(bhFilters());}
$(function(){if($.fn.datepicker){$('.bh-date').datepicker({format:'yyyy-mm-dd',autoclose:true,todayHighlight:true});}if($.fn.select2){$('#filter_customer,#filter_currency,#filter_tax_status').select2({width:'100%',allowClear:true});}
var dt=$('#dtb_billing_history').DataTable({bProcessing:true,bServerSide:true,pageLength:25,ordering:false,dom:"<'row'<'col-sm-12'B>>"+"<'row'<'col-sm-6'l><'col-sm-6'f>>"+"<'row'<'col-sm-12'tr>>"+"<'row'<'col-sm-5'i><'col-sm-7'p>>",buttons:[{extend:'collection',text:<?=sd_js('common_export_data', 'Export Data');?>,buttons:['copyHtml5','excelHtml5','csvHtml5','pdfHtml5']}],columnDefs:[{targets:[0,1],orderable:false,searchable:false},{width:'38px',targets:0},{width:'78px',targets:1}],ajax:{url:'<?=base_admin();?>modul/billing_history/billing_history_data.php',type:'post',data:function(d){$.extend(d,bhFilters());},error:function(xhr){console.log(xhr.responseText);bhError(<?=sd_js('sales_billing_history_load_failed', 'Billing History data failed to load.');?>);}}});
$('#btn_filter_bh').click(function(){dt.draw();});$('#filter_keyword').keyup(function(e){if(e.keyCode===13)dt.draw();});$('#btn_reset_bh').click(function(){$('#filter_tgl_awal').val('<?=$defaultFrom;?>');$('#filter_tgl_akhir').val('<?=$defaultTo;?>');$('#filter_customer,#filter_currency,#filter_tax_status').val('').trigger('change');$('#filter_keyword').val('');dt.draw();});$('#btn_excel_bh').click(function(){window.location='<?=base_admin();?>modul/billing_history/billing_history_action.php?act=excel&'+bhQuery();});
$(document).on('click','.btn-bh-detail',function(){$.post('<?=base_admin();?>modul/billing_history/billing_history_action.php?act=detail',{id:$(this).data('id')},function(html){$('#bh_detail_body').html(html);$('#modal_detail_bh').modal('show');}).fail(function(){bhError('Detail gagal dibuka.');});});$('.hide_alert_notif').click(function(){$('.error_data_delete').hide();});
});
</script>
