<?php
if (!function_exists('hr_t')) {
  function hr_t($key, $fallback = '') { return lang_text($key, $fallback); }
}
if (!function_exists('hr_h')) {
  function hr_h($key, $fallback = '') { return htmlspecialchars((string) hr_t($key, $fallback), ENT_QUOTES, 'UTF-8'); }
}
if (!function_exists('hr_js')) {
  function hr_js($key, $fallback = '') { return json_encode(hr_t($key, $fallback), JSON_HEX_TAG | JSON_HEX_APOS | JSON_HEX_AMP | JSON_HEX_QUOT); }
}
if (session_status() === PHP_SESSION_NONE) session_start();
include "../../inc/config.php";
session_check_json();
function ps_json($s,$m='',$x=array()){header('Content-Type: application/json; charset=utf-8');$p=array('status'=>$s);if($m!=='')$p[$s==='good'?'message':'error_message']=$m;foreach($x as $k=>$v)$p[$k]=$v;echo json_encode($p);exit;}
function ps_h($v){return htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');}
function ps_p($k,$d=''){return isset($_POST[$k])?$_POST[$k]:$d;}
function ps_g($k,$d=''){return isset($_GET[$k])?$_GET[$k]:$d;}
function ps_c($v){return strtoupper(trim((string)$v));}
function ps_user(){return isset($_SESSION['username'])&&$_SESSION['username']!==''?$_SESSION['username']:'system';}
function ps_select2($rows,$id,$cb){$out=array();foreach($rows as $r)$out[]=array('id'=>$r->$id,'text'=>$cb($r));header('Content-Type: application/json; charset=utf-8');echo json_encode(array('results'=>$out));exit;}
function ps_row($id){global $db;return $db->fetch("SELECT ps.*,d.nm_dept FROM erp_payslip ps LEFT JOIN dept d ON d.kd_dept=ps.department_code WHERE ps.id=? LIMIT 1",array((int)$id));}
function ps_rows($from,$to,$area,$status,$emp,$kw){global $db;$w=" WHERE ps.period_from<=? AND ps.period_to>=? ";$p=array($to,$from);if($area!==''){$w.=" AND ps.payroll_area=? ";$p[]=$area;}if($status!==''){$w.=" AND ps.payslip_status=? ";$p[]=$status;}if($emp!==''){$w.=" AND ps.employee_id=? ";$p[]=(int)$emp;}if($kw!==''){$like='%'.$kw.'%';$w.=" AND (ps.payslip_no LIKE ? OR ps.payroll_run_no LIKE ? OR ps.employee_no LIKE ? OR ps.full_name LIKE ? OR ps.sap_reference LIKE ?) ";array_push($p,$like,$like,$like,$like,$like);}return $db->query("SELECT ps.*,d.nm_dept FROM erp_payslip ps LEFT JOIN dept d ON d.kd_dept=ps.department_code $w ORDER BY ps.period_year DESC,ps.period_month DESC,ps.employee_no",$p);}
function ps_generate($payrollEmployeeId,$channel,$status,$remarks){global $db;$pe=$db->fetch("SELECT pe.*,p.payroll_run_no,p.period_year,p.period_month,p.period_from,p.period_to,p.pay_date,p.currency FROM erp_payroll_process_employee pe JOIN erp_payroll_process p ON p.id=pe.payroll_process_id WHERE pe.id=? LIMIT 1",array((int)$payrollEmployeeId));if(!$pe)throw new Exception('Payroll employee tidak ditemukan.');$no='PSL-'.$pe->period_year.'-'.str_pad($pe->period_month,2,'0',STR_PAD_LEFT).'-'.$pe->employee_no;$existing=$db->fetch("SELECT id,payslip_status FROM erp_payslip WHERE payroll_process_id=? AND employee_id=? LIMIT 1",array($pe->payroll_process_id,$pe->employee_id));if($existing&&$existing->payslip_status==='RELEASED')throw new Exception('Payslip RELEASED tidak bisa digenerate ulang.');$data=array('payslip_no'=>$no,'payroll_process_id'=>$pe->payroll_process_id,'payroll_employee_id'=>$pe->id,'payroll_run_no'=>$pe->payroll_run_no,'employee_id'=>$pe->employee_id,'employee_no'=>$pe->employee_no,'full_name'=>$pe->full_name,'department_code'=>$pe->department_code,'employee_group'=>$pe->employee_group,'payroll_area'=>$pe->payroll_area,'period_year'=>$pe->period_year,'period_month'=>$pe->period_month,'period_from'=>$pe->period_from,'period_to'=>$pe->period_to,'pay_date'=>$pe->pay_date,'salary_structure_code'=>$pe->salary_structure_code,'working_days'=>$pe->working_days,'paid_days'=>$pe->paid_days,'absence_days'=>$pe->absence_days,'overtime_hours'=>$pe->overtime_hours,'gross_pay'=>$pe->gross_pay,'total_earning'=>$pe->total_earning,'total_deduction'=>$pe->total_deduction,'tax_amount'=>$pe->tax_amount,'net_pay'=>$pe->net_pay,'currency'=>$pe->currency,'payslip_status'=>$status,'release_channel'=>$channel,'generated_by'=>ps_user(),'generated_at'=>date('Y-m-d H:i:s'),'sap_reference'=>'SAP-HCM-'.$no,'remarks'=>$remarks,'updated_by'=>ps_user(),'updated_at'=>date('Y-m-d H:i:s'));if($status==='RELEASED'){$data['released_by']=ps_user();$data['released_at']=date('Y-m-d H:i:s');}if($existing){$id=$existing->id;$ok=$db->update('erp_payslip',$data,'id',$id);}else{$data['created_by']=ps_user();$ok=$db->insert('erp_payslip',$data);$id=$db->last_insert_id();}if(!$ok)throw new Exception($db->getErrorMessage()?:'Payslip gagal disimpan.');$db->delete('erp_payslip_detail','payslip_id',$id);$rows=$db->query("SELECT * FROM erp_payroll_process_result WHERE payroll_employee_id=? AND payslip_display='Y' ORDER BY sequence_no,id",array($pe->id));foreach($rows as $r){$db->insert('erp_payslip_detail',array('payslip_id'=>$id,'line_no'=>$r->sequence_no,'component_code'=>$r->component_code,'component_name'=>$r->component_name,'wage_type_code'=>$r->wage_type_code,'component_type'=>$r->component_type,'quantity'=>$r->quantity,'rate'=>$r->rate,'amount'=>$r->amount,'currency'=>$r->currency,'taxable'=>$r->taxable,'sequence_no'=>$r->sequence_no));}return $id;}
$act=isset($_GET['act'])?$_GET['act']:'';$username=ps_user();$statuses=array('DRAFT','GENERATED','RELEASED','VOID');$channels=array('PORTAL','EMAIL','PRINT','MANUAL');
switch($act){
case 'employee_search':$t=trim(ps_p('term'));$like='%'.$t.'%';$rows=$db->query("SELECT id,employee_no,full_name,employee_group,payroll_area FROM erp_employee_master WHERE employment_status IN ('ACTIVE','PROBATION','CONTRACT') AND (?='' OR employee_no LIKE ? OR full_name LIKE ?) ORDER BY employee_no LIMIT 40",array($t,$like,$like));ps_select2($rows,'id',function($r){return $r->employee_no.' - '.$r->full_name.' ['.$r->employee_group.' / '.$r->payroll_area.']';});
case 'payroll_employee_search':$t=trim(ps_p('term'));$like='%'.$t.'%';$rows=$db->query("SELECT pe.id,pe.employee_no,pe.full_name,p.payroll_run_no,p.period_year,p.period_month,pe.net_pay FROM erp_payroll_process_employee pe JOIN erp_payroll_process p ON p.id=pe.payroll_process_id LEFT JOIN erp_payslip ps ON ps.payroll_process_id=pe.payroll_process_id AND ps.employee_id=pe.employee_id AND ps.payslip_status<>'VOID' WHERE ps.id IS NULL AND pe.process_status IN ('CALCULATED','POSTED','LOCKED') AND (?='' OR pe.employee_no LIKE ? OR pe.full_name LIKE ? OR p.payroll_run_no LIKE ?) ORDER BY p.period_year DESC,p.period_month DESC,pe.employee_no LIMIT 50",array($t,$like,$like,$like));ps_select2($rows,'id',function($r){return $r->payroll_run_no.' - '.$r->employee_no.' '.$r->full_name.' [Net '.number_format((float)$r->net_pay,0).']';});
case 'get':$r=ps_row((int)ps_p('id'));if(!$r)ps_json('error','Payslip tidak ditemukan.');ps_json('good','',array('data'=>(array)$r));
case 'generate':try{$id=ps_generate((int)ps_p('payroll_employee_id'),ps_c(ps_p('release_channel','PORTAL')),ps_c(ps_p('payslip_status','GENERATED')),trim(ps_p('remarks')));if(function_exists('simpan_log'))simpan_log('User '.$username.' generate Payslip ID '.$id.' pada '.date('Y-m-d H:i:s'),$username);ps_json('good','Payslip berhasil digenerate.',array('id'=>$id));}catch(Exception $e){ps_json('error',$e->getMessage());}
case 'status':$id=(int)ps_p('id');$status=ps_c(ps_p('status'));if(!in_array($status,$statuses,true))ps_json('error','Status tidak valid.');$r=ps_row($id);if(!$r)ps_json('error','Payslip tidak ditemukan.');$data=array('payslip_status'=>$status,'updated_by'=>$username,'updated_at'=>date('Y-m-d H:i:s'));if($status==='RELEASED'){$data['released_by']=$username;$data['released_at']=date('Y-m-d H:i:s');}if($status==='VOID'){$data['voided_by']=$username;$data['voided_at']=date('Y-m-d H:i:s');}$db->update('erp_payslip',$data,'id',$id);ps_json('good','Status payslip berhasil diubah.');
case 'delete':$id=(int)ps_p('id');$r=ps_row($id);if(!$r)ps_json('error','Payslip tidak ditemukan.');if($r->payslip_status==='RELEASED')ps_json('error','Payslip RELEASED tidak bisa dihapus. Void terlebih dahulu bila perlu.');$db->delete('erp_payslip','id',$id);if($db->getErrorMessage())ps_json('error',$db->getErrorMessage());ps_json('good','Payslip berhasil dihapus.');
case 'detail':$r=ps_row((int)ps_p('id'));if(!$r){echo '<div class="alert alert-warning">Payslip tidak ditemukan.</div>';break;}$lines=$db->query("SELECT * FROM erp_payslip_detail WHERE payslip_id=? ORDER BY sequence_no,id",array((int)$r->id));echo '<div class="ps-slip"><div class="row"><div class="col-sm-6"><h3 style="margin-top:0">'.ps_h($r->payslip_no).'</h3><p><b>'.ps_h($r->full_name).'</b><br>'.ps_h($r->employee_no.' / '.$r->department_code.' '.$r->nm_dept).'</p></div><div class="col-sm-6 text-right"><h4>'.ps_h($r->period_from.' s/d '.$r->period_to).'</h4><span class="label label-success">'.ps_h($r->payslip_status).'</span></div></div><hr><div class="row"><div class="col-sm-3"><b>Working / Paid Days</b><br>'.ps_h($r->working_days.' / '.$r->paid_days).'</div><div class="col-sm-3"><b>'.hr_h('hr_overtime', 'Overtime').'</b><br>'.ps_h($r->overtime_hours).' hours</div><div class="col-sm-3"><b>Pay Date</b><br>'.ps_h($r->pay_date).'</div><div class="col-sm-3"><b>'.hr_h('hr_net_pay', 'Net Pay').'</b><br><b>'.number_format((float)$r->net_pay,2).'</b></div></div><hr><div class="row"><div class="col-sm-6"><h4>Earnings</h4><table class="table table-bordered table-condensed"><tbody>';$ded='';foreach($lines as $l){$row='<tr><td>'.ps_h($l->component_code.' - '.$l->component_name).'</td><td class="text-right">'.number_format((float)$l->amount,2).'</td></tr>';if(in_array($l->component_type,array('EARNING','BENEFIT','INFORMATION'),true))echo $row;else $ded.=$row;}echo '</tbody></table></div><div class="col-sm-6"><h4>Deductions & Tax</h4><table class="table table-bordered table-condensed"><tbody>'.$ded.'</tbody></table></div></div><hr><div class="row"><div class="col-sm-3"><b>Gross</b><br>'.number_format((float)$r->gross_pay,2).'</div><div class="col-sm-3"><b>'.hr_h('hr_deduction', 'Deduction').'</b><br>'.number_format((float)$r->total_deduction,2).'</div><div class="col-sm-3"><b>Tax</b><br>'.number_format((float)$r->tax_amount,2).'</div><div class="col-sm-3"><b>Take Home Pay</b><br><b>'.number_format((float)$r->net_pay,2).'</b></div></div></div>';break;
case 'export':$initial=ob_get_level();ob_start();error_reporting(E_ALL & ~E_NOTICE & ~E_WARNING & ~E_DEPRECATED & ~E_USER_DEPRECATED);require_once "../../inc/lib/PHPExcel.php";require_once "../../inc/excel_style_helper.php";PHPExcel_Shared_File::setUseUploadTempDirectory(true);$from=ps_g('tgl_awal',date('Y-m-01'));$to=ps_g('tgl_akhir',date('Y-m-t'));$rows=ps_rows($from,$to,ps_g('payroll_area',''),ps_g('payslip_status',''),ps_g('employee_id',''),ps_g('keyword',''));$excel=new PHPExcel();$sheet=$excel->setActiveSheetIndex(0);$sheet->setTitle(erp_export_sheet_title('Payslip'));$heads=array(erp_export_label("No"),erp_export_label("Payslip No"),erp_export_label("Payroll Run"),erp_export_label("Employee No"),erp_export_label("Employee"),erp_export_label("Department"),erp_export_label("Area"),erp_export_label("Period"),erp_export_label("Pay Date"),erp_export_label("Status"),erp_export_label("Gross"),erp_export_label("Earning"),erp_export_label("Deduction"),erp_export_label("Tax"),erp_export_label("Net"),erp_export_label("Channel"),erp_export_label("Released At"),erp_export_label("Updated By"));foreach($heads as $i=>$h)$sheet->setCellValue(PHPExcel_Cell::stringFromColumnIndex($i).'4',$h);$rn=5;$n=1;foreach($rows as $r){$vals=array($n++,$r->payslip_no,$r->payroll_run_no,$r->employee_no,$r->full_name,$r->department_code.' - '.$r->nm_dept,$r->payroll_area,$r->period_from.' s/d '.$r->period_to,$r->pay_date,$r->payslip_status,$r->gross_pay,$r->total_earning,$r->total_deduction,$r->tax_amount,$r->net_pay,$r->release_channel,$r->released_at,$r->updated_by?:$r->created_by);foreach($vals as $i=>$v)$sheet->setCellValue(PHPExcel_Cell::stringFromColumnIndex($i).$rn,$v);$rn++;}erpkb_excel_apply_standard_style($excel,array('sheet'=>$sheet,'title'=>erp_export_title('PAYSLIP REPORT'),'header_row'=>4,'first_data_row'=>5,'last_data_row'=>max(5,$rn-1),'column_count'=>count($heads),'decimal_columns'=>array('K','L','M','N','O'),'filters'=>array('Period'=>$from.' s/d '.$to,'Area'=>ps_g('payroll_area',erp_export_all_text()),'Status'=>ps_g('payslip_status',erp_export_all_text()))));$tmp=erpkb_excel_temp_file('payslip_');PHPExcel_IOFactory::createWriter($excel,'Excel2007')->save($tmp);$size=@filesize($tmp);$sig=@file_get_contents($tmp,false,null,0,2);if(!$size||$sig!=='PK'){@unlink($tmp);while(ob_get_level()>$initial)ob_end_clean();echo erp_t('export_excel_invalid_file','File Excel gagal dibuat dengan benar.');exit;}while(ob_get_level()>$initial)ob_end_clean();header('Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');header('Content-Disposition: attachment; filename="payslip_'.date('Ymd_His').'.xlsx"');header('Content-Length: '.$size);header('Cache-Control: max-age=0');header('Pragma: public');readfile($tmp);@unlink($tmp);exit;
default:ps_json('error','Action tidak dikenal.');
}
?>
