<?php
if (!function_exists('fin_t')) {
  function fin_t($key, $fallback = '') { return lang_text($key, $fallback); }
}
if (!function_exists('fin_h')) {
  function fin_h($key, $fallback = '') { return htmlspecialchars((string) fin_t($key, $fallback), ENT_QUOTES, 'UTF-8'); }
}
if (!function_exists('fin_js')) {
  function fin_js($key, $fallback = '') { return json_encode(fin_t($key, $fallback), JSON_HEX_TAG | JSON_HEX_APOS | JSON_HEX_AMP | JSON_HEX_QUOT); }
}
$initialOutputBufferLevel=ob_get_level();ob_start();session_start();include "../../inc/config.php";require_once "../../inc/lib/PHPExcel.php";require_once "../../inc/excel_style_helper.php";session_check_json();
function ar_h($v){return htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');}
function ar_n($v){return number_format((float)$v,2,'.',',');}
function ar_json($s,$m='',$e=array()){header('Content-Type: application/json');echo json_encode(array_merge(array('status'=>$s,'message'=>$m),$e));exit;}
function ar_rows($db,$asOf,$customer){
 $where="si.billing_status IN ('POSTED','DRAFT') AND COALESCE(si.due_date,si.invoice_date,si.posting_date)<=?";
 $p=array($asOf);if($customer!==''){$where.=" AND (si.bill_to=? OR si.ship_to=?)";$p[]=$customer;$p[]=$customer;}
 return $db->query("SELECT si.id_sales,si.no_sales_invoice,si.invoice_no,si.bill_to,COALESCE(c.nama,si.bill_to) customer_name,si.invoice_date,si.posting_date,si.due_date,si.gross_amount,COALESCE((SELECT SUM(ip.amount) FROM erp_incoming_payment ip WHERE ip.sales_invoice_id=si.id_sales AND ip.status='POSTED'),0) paid_amount,DATEDIFF(?,COALESCE(si.due_date,si.invoice_date,si.posting_date)) age_days FROM sales_invoice si LEFT JOIN customer c ON c.kode_pemasok=si.bill_to WHERE $where ORDER BY customer_name,COALESCE(si.due_date,si.invoice_date) ASC",array_merge(array($asOf),$p));
}
$act=$_GET['act']??'';
try{
 if($act==='filter'){ $as=$_POST['as_of_date']??date('Y-m-d');$cust=trim($_POST['customer_code']??'');$rows=ar_rows($db,$as,$cust);$html='';$bucket=array('current'=>0,'d1'=>0,'d31'=>0,'d61'=>0,'d91'=>0,'total'=>0);$n=0;foreach($rows as $r){$open=(float)$r->gross_amount-(float)$r->paid_amount;if($open<=0)continue;$n++;$age=(int)$r->age_days;$b=$age<=0?'current':($age<=30?'d1':($age<=60?'d31':($age<=90?'d61':'d91')));$bucket[$b]+=$open;$bucket['total']+=$open;$invoice=$r->no_sales_invoice?:$r->invoice_no;$detail='<button type="button" class="btn btn-info btn-xs btn-detail-ar" data-customer="'.ar_h($r->customer_name).'" data-invoice="'.ar_h($invoice).'" data-invoice-date="'.ar_h($r->invoice_date).'" data-due-date="'.ar_h($r->due_date).'" data-gross="'.ar_h(ar_n($r->gross_amount)).'" data-paid="'.ar_h(ar_n($r->paid_amount)).'" data-outstanding="'.ar_h(ar_n($open)).'" data-age="'.ar_h($age).'"><i class="fa fa-eye"></i></button>';$html.='<tr><td>'.$n.'</td><td>'.ar_h($r->customer_name).'</td><td>'.ar_h($invoice).'</td><td>'.ar_h($r->invoice_date).'</td><td>'.ar_h($r->due_date).'</td><td class="text-right">'.ar_n($r->gross_amount).'</td><td class="text-right">'.ar_n($r->paid_amount).'</td><td class="text-right">'.ar_n($open).'</td><td class="text-right">'.$age.'</td><td class="text-center">'.$detail.'</td></tr>';}if($n===0)$html='<tr><td colspan="10" class="text-center text-muted">Tidak ada AR outstanding.</td></tr>';ar_json('success','OK',array('html'=>$html,'current'=>ar_n($bucket['current']),'d1'=>ar_n($bucket['d1']),'d31'=>ar_n($bucket['d31']),'d61'=>ar_n($bucket['d61']),'d91'=>ar_n($bucket['d91']),'total'=>ar_n($bucket['total']),'count'=>$n));}
 if($act==='excel'){ $as=$_GET['as_of_date']??date('Y-m-d');$cust=trim($_GET['customer_code']??'');$excel=new PHPExcel();$sh=$excel->setActiveSheetIndex(0);$sh->setTitle(erp_export_sheet_title('AR Aging'));$headers=array(erp_export_label("No"),erp_export_label("Customer"),erp_export_label("Invoice"),erp_export_label("Invoice Date"),erp_export_label("Due Date"),erp_export_label("Gross"),erp_export_label("Paid"),erp_export_label("Outstanding"),erp_export_label("Age Days"),erp_export_label("Bucket"));foreach($headers as $i=>$h)$sh->setCellValueByColumnAndRow($i,4,$h);$rn=5;$no=1;foreach(ar_rows($db,$as,$cust) as $r){$open=(float)$r->gross_amount-(float)$r->paid_amount;if($open<=0)continue;$age=(int)$r->age_days;$bucket=$age<=0?'Current':($age<=30?'1-30':($age<=60?'31-60':($age<=90?'61-90':'>90')));$vals=array($no++,$r->customer_name,$r->no_sales_invoice?:$r->invoice_no,$r->invoice_date,$r->due_date,$r->gross_amount,$r->paid_amount,$open,$age,$bucket);foreach($vals as $i=>$v)$sh->setCellValueByColumnAndRow($i,$rn,$v);$rn++;}erpkb_excel_apply_standard_style($excel,array('sheet'=>$sh,'title'=>erp_export_title('AR AGING'),'header_row'=>4,'first_data_row'=>5,'last_data_row'=>max(5,$rn-1),'column_count'=>count($headers),'money_columns'=>array('F','G','H'),'filters'=>array('As Of'=>$as,'Customer'=>$cust)));while(ob_get_level()>$initialOutputBufferLevel)ob_end_clean();header('Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');header('Content-Disposition: attachment;filename="ar_aging_'.date('YmdHis').'.xlsx"');header('Cache-Control: max-age=0');PHPExcel_IOFactory::createWriter($excel,'Excel2007')->save('php://output');exit;}
 ar_json('error','Action tidak dikenal.');
}catch(Exception $e){ar_json('error',$e->getMessage());}
