<?php
if (!function_exists('hr_t')) {
  function hr_t($key, $fallback = '') { return lang_text($key, $fallback); }
}
if (!function_exists('hr_h')) {
  function hr_h($key, $fallback = '') { return htmlspecialchars((string) hr_t($key, $fallback), ENT_QUOTES, 'UTF-8'); }
}
if (!function_exists('hr_js')) {
  function hr_js($key, $fallback = '') { return json_encode(hr_t($key, $fallback), JSON_HEX_TAG | JSON_HEX_APOS | JSON_HEX_AMP | JSON_HEX_QUOT); }
}
if (session_status() === PHP_SESSION_NONE) session_start();
include "../../inc/config.php";
session_check_json();
function er_h($v){return htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');}
function er_label($s){$m=array('ACTIVE'=>'success','PROBATION'=>'info','CONTRACT'=>'primary','INACTIVE'=>'warning','TERMINATED'=>'danger');$c=isset($m[$s])?$m[$s]:'default';return '<span class="label label-'.$c.'">'.er_h($s).'</span>';}
function er_filters(){return array('as_of'=>isset($_POST['as_of_date'])&&$_POST['as_of_date']!==''?$_POST['as_of_date']:date('Y-m-d'),'status'=>isset($_POST['employment_status'])?trim($_POST['employment_status']):'','group'=>isset($_POST['employee_group'])?trim($_POST['employee_group']):'','dept'=>isset($_POST['department_code'])?trim($_POST['department_code']):'','job'=>isset($_POST['job_title_id'])?trim($_POST['job_title_id']):'','org'=>isset($_POST['company_structure_id'])?trim($_POST['company_structure_id']):'','manager'=>isset($_POST['manager_employee_id'])?trim($_POST['manager_employee_id']):'','work'=>isset($_POST['work_location_type'])?trim($_POST['work_location_type']):'','keyword'=>isset($_POST['keyword'])?trim($_POST['keyword']):'');}
function er_where($f,&$p){$w=" WHERE e.valid_from<=? AND e.valid_to>=? ";array_push($p,$f['as_of'],$f['as_of']);if($f['status']!==''){$w.=" AND e.employment_status=? ";$p[]=$f['status'];}if($f['group']!==''){$w.=" AND e.employee_group=? ";$p[]=$f['group'];}if($f['dept']!==''){$w.=" AND e.department_code=? ";$p[]=$f['dept'];}if($f['job']!==''){$w.=" AND e.job_title_id=? ";$p[]=(int)$f['job'];}if($f['org']!==''){$w.=" AND e.company_structure_id=? ";$p[]=(int)$f['org'];}if($f['manager']!==''){$w.=" AND e.manager_employee_id=? ";$p[]=(int)$f['manager'];}if($f['work']!==''){$w.=" AND e.work_location_type=? ";$p[]=$f['work'];}if($f['keyword']!==''){$kw='%'.$f['keyword'].'%';$w.=" AND (e.employee_no LIKE ? OR e.personnel_no LIKE ? OR e.full_name LIKE ? OR e.email LIKE ? OR e.phone LIKE ? OR e.identity_no LIKE ? OR d.nm_dept LIKE ? OR j.job_title_name LIKE ?) ";for($i=0;$i<8;$i++)$p[]=$kw;}return $w;}
$draw=isset($_POST['draw'])?(int)$_POST['draw']:1;$start=isset($_POST['start'])?max(0,(int)$_POST['start']):0;$length=isset($_POST['length'])?(int)$_POST['length']:25;if($length<=0||$length>500)$length=25;
$f=er_filters();$p=array();$w=er_where($f,$p);
$base=" FROM erp_employee_master e LEFT JOIN dept d ON d.kd_dept=e.department_code LEFT JOIN erp_job_title j ON j.id=e.job_title_id LEFT JOIN erp_company_structure cs ON cs.id=e.company_structure_id LEFT JOIN erp_cost_center cc ON cc.cost_center_code=e.cost_center_code LEFT JOIN erp_profit_center pc ON pc.profit_center_code=e.profit_center_code LEFT JOIN erp_employee_master m ON m.id=e.manager_employee_id ";
$kpi=$db->fetch("SELECT COUNT(*) total,SUM(e.employment_status IN ('ACTIVE','PROBATION','CONTRACT')) active_count,SUM(e.employment_status='PROBATION') probation_count,SUM(e.employment_status='CONTRACT') contract_count,SUM(e.employee_group='OPERATOR') operator_count,SUM(e.employee_group IN ('MANAGER','DIRECTOR')) leader_count $base $w",$p);
$cnt=$db->fetch("SELECT COUNT(*) jml $base $w",$p);$total=$cnt?(int)$cnt->jml:0;
$orderMap=array(2=>'e.employee_no',3=>'e.full_name',4=>'j.job_title_code',5=>'d.kd_dept',6=>'cs.structure_code',7=>'m.employee_no',8=>'e.employee_group',9=>'e.hire_date',10=>'e.employment_status',11=>'e.updated_at');$orderBy='e.employee_no ASC';
if(isset($_POST['order'][0]['column'])){$col=(int)$_POST['order'][0]['column'];$dir=(isset($_POST['order'][0]['dir'])&&strtolower($_POST['order'][0]['dir'])==='desc')?'DESC':'ASC';if(isset($orderMap[$col]))$orderBy=$orderMap[$col].' '.$dir;}
$rows=$db->query("SELECT e.*,d.nm_dept,j.job_title_code,j.job_title_name,j.job_level,cs.structure_code,cs.structure_name,cc.cost_center_name,pc.profit_center_name,m.employee_no manager_no,m.full_name manager_name $base $w ORDER BY $orderBy LIMIT $start,$length",$p);
$data=array();$no=$start+1;$asOf=new DateTime($f['as_of']);
foreach($rows as $r){$hire=$r->hire_date?new DateTime($r->hire_date):null;$tenure=$hire?$hire->diff($asOf)->y.'y '.$hire->diff($asOf)->m.'m':'-';$data[]=array($no++,'<button class="btn btn-info btn-xs btn-er-detail" data-id="'.(int)$r->id.'"><i class="fa fa-eye"></i></button>','<strong>'.er_h($r->employee_no).'</strong><br><small>Personnel: '.er_h($r->personnel_no?:'-').'</small>','<strong>'.er_h($r->full_name).'</strong><br><small>'.er_h($r->gender).' | '.er_h($r->email?:'-').'</small>','<strong>'.er_h($r->job_title_code?:'-').'</strong><br><small>'.er_h($r->job_title_name?:'-').' ['.er_h($r->job_level?:'-').']</small>','<strong>'.er_h($r->department_code?:'-').'</strong><br><small>'.er_h($r->nm_dept?:'-').'</small>','<strong>'.er_h($r->structure_code?:'-').'</strong><br><small>'.er_h($r->cost_center_code?:'-').' / '.er_h($r->profit_center_code?:'-').'</small>',er_h($r->manager_no?($r->manager_no.' - '.$r->manager_name):'-'),er_h($r->employee_group).'<br><small>'.er_h($r->work_location_type).' / Grade '.er_h($r->pay_grade?:'-').'</small>',er_h($r->hire_date).'<br><small>Tenure '.$tenure.'</small>',er_label($r->employment_status),er_h($r->updated_by?:$r->created_by?:'-').'<br><small>'.er_h($r->updated_at?:$r->created_at).'</small>');}
header('Content-Type: application/json; charset=utf-8');echo json_encode(array('draw'=>$draw,'recordsTotal'=>$total,'recordsFiltered'=>$total,'data'=>$data,'kpi'=>array('total'=>$kpi?(int)$kpi->total:0,'active'=>$kpi?(int)$kpi->active_count:0,'probation'=>$kpi?(int)$kpi->probation_count:0,'contract'=>$kpi?(int)$kpi->contract_count:0,'operator'=>$kpi?(int)$kpi->operator_count:0,'leader'=>$kpi?(int)$kpi->leader_count:0)));
?>
