<?php
if (!function_exists('hr_t')) {
  function hr_t($key, $fallback = '') { return lang_text($key, $fallback); }
}
if (!function_exists('hr_h')) {
  function hr_h($key, $fallback = '') { return htmlspecialchars((string) hr_t($key, $fallback), ENT_QUOTES, 'UTF-8'); }
}
if (!function_exists('hr_js')) {
  function hr_js($key, $fallback = '') { return json_encode(hr_t($key, $fallback), JSON_HEX_TAG | JSON_HEX_APOS | JSON_HEX_AMP | JSON_HEX_QUOT); }
}
if (session_status() === PHP_SESSION_NONE) session_start();
include "../../inc/config.php";
session_check_json();
function ssd_h($v){return htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');}
function ssd_label($s){$map=array('DRAFT'=>'warning','ACTIVE'=>'success','INACTIVE'=>'default');$c=isset($map[$s])?$map[$s]:'default';return '<span class="label label-'.$c.'">'.ssd_h($s).'</span>';}
$draw=isset($_POST['draw'])?(int)$_POST['draw']:1;$start=isset($_POST['start'])?max(0,(int)$_POST['start']):0;$length=isset($_POST['length'])?(int)$_POST['length']:25;if($length<=0||$length>500)$length=25;
$from=isset($_POST['tgl_awal'])&&$_POST['tgl_awal']!==''?$_POST['tgl_awal']:date('Y-01-01');$to=isset($_POST['tgl_akhir'])&&$_POST['tgl_akhir']!==''?$_POST['tgl_akhir']:'9999-12-31';$type=isset($_POST['pay_scale_type'])?trim($_POST['pay_scale_type']):'';$grade=isset($_POST['pay_grade'])?trim($_POST['pay_grade']):'';$group=isset($_POST['employee_group'])?trim($_POST['employee_group']):'';$status=isset($_POST['structure_status'])?trim($_POST['structure_status']):'';$kw=isset($_POST['keyword'])?trim($_POST['keyword']):'';
$w=" WHERE s.valid_from<=? AND s.valid_to>=? ";$p=array($to,$from);if($type!==''){$w.=" AND s.pay_scale_type=? ";$p[]=$type;}if($grade!==''){$w.=" AND s.pay_grade=? ";$p[]=$grade;}if($group!==''){$w.=" AND s.employee_group=? ";$p[]=$group;}if($status!==''){$w.=" AND s.structure_status=? ";$p[]=$status;}if($kw!==''){$like='%'.$kw.'%';$w.=" AND (s.structure_code LIKE ? OR s.structure_name LIKE ? OR s.pay_level LIKE ? OR s.position_level LIKE ? OR s.sap_reference LIKE ?) ";array_push($p,$like,$like,$like,$like,$like);}
$kpi=$db->fetch("SELECT COUNT(*) total,SUM(structure_status='ACTIVE') active,COUNT(DISTINCT pay_grade) grade_count,SUM(pay_scale_type='MONTHLY') monthly,SUM(pay_scale_type='DAILY') daily,SUM(pay_scale_type='MANAGEMENT') management FROM erp_salary_structure");
$cnt=$db->fetch("SELECT COUNT(*) jml FROM erp_salary_structure s $w",$p);$total=$cnt?(int)$cnt->jml:0;
$orderMap=array(2=>'s.structure_code',3=>'s.pay_scale_type',4=>'s.pay_grade',5=>'s.employee_group',6=>'s.base_salary_mid',7=>'item_count',8=>'s.structure_status',9=>'s.updated_at');$orderBy='s.pay_grade,s.pay_level,s.structure_code';if(isset($_POST['order'][0]['column'])){$col=(int)$_POST['order'][0]['column'];$dir=(isset($_POST['order'][0]['dir'])&&strtolower($_POST['order'][0]['dir'])==='desc')?'DESC':'ASC';if(isset($orderMap[$col]))$orderBy=$orderMap[$col].' '.$dir;}
$rows=$db->query("SELECT s.*,cc.cost_center_name,pc.profit_center_name,(SELECT COUNT(*) FROM erp_salary_structure_detail d WHERE d.structure_id=s.id) item_count FROM erp_salary_structure s LEFT JOIN erp_cost_center cc ON cc.cost_center_code=s.cost_center_code LEFT JOIN erp_profit_center pc ON pc.profit_center_code=s.profit_center_code $w ORDER BY $orderBy LIMIT $start,$length",$p);
$data=array();$no=$start+1;foreach($rows as $r){$canDel=$r->structure_status==='ACTIVE'?' disabled':'';$next=$r->structure_status==='ACTIVE'?'INACTIVE':'ACTIVE';$act='<div class="ss-action"><button class="btn btn-info btn-xs btn-ss-detail" data-id="'.(int)$r->id.'" title="'.hr_h('common_detail', 'Detail').'"><i class="fa fa-eye"></i></button> <button class="btn btn-primary btn-xs btn-ss-edit" data-id="'.(int)$r->id.'" title="'.hr_h('common_edit', 'Edit').'"><i class="fa fa-pencil"></i></button> <button class="btn btn-warning btn-xs btn-ss-status" data-id="'.(int)$r->id.'" data-status="'.$next.'" title="'.$next.'"><i class="fa fa-refresh"></i></button> <button class="btn btn-danger btn-xs btn-ss-delete" data-id="'.(int)$r->id.'" data-no="'.ssd_h($r->structure_code).'" title="'.hr_h('common_delete', 'Delete').'"'.$canDel.'><i class="fa fa-trash"></i></button></div>';
  $data[]=array($no++,$act,'<strong>'.ssd_h($r->structure_code).'</strong><br><small>'.ssd_h($r->structure_name).'</small>','<strong>'.ssd_h($r->pay_scale_type).'</strong><br><small>'.ssd_h($r->pay_scale_area).'</small>','<strong>'.ssd_h($r->pay_grade).'</strong><br><small>'.ssd_h($r->pay_level.' / '.$r->position_level).'</small>','<strong>'.ssd_h($r->employee_group).'</strong><br><small>'.ssd_h($r->payroll_area).'</small>','Min '.number_format((float)$r->base_salary_min,0).'<br><b>Mid '.number_format((float)$r->base_salary_mid,0).'</b><br><small>Max '.number_format((float)$r->base_salary_max,0).'</small>','<span class="badge bg-blue">'.(int)$r->item_count.' item</span>',ssd_label($r->structure_status),ssd_h($r->updated_by?:$r->created_by?:'-').'<br><small>'.ssd_h($r->updated_at?:$r->created_at).'</small>');}
header('Content-Type: application/json; charset=utf-8');echo json_encode(array('draw'=>$draw,'recordsTotal'=>$total,'recordsFiltered'=>$total,'data'=>$data,'kpi'=>array('total'=>$kpi?(int)$kpi->total:0,'active'=>$kpi?(int)$kpi->active:0,'grade'=>$kpi?(int)$kpi->grade_count:0,'monthly'=>$kpi?(int)$kpi->monthly:0,'daily'=>$kpi?(int)$kpi->daily:0,'management'=>$kpi?(int)$kpi->management:0)));
?>
