<?php
if (!function_exists('hr_t')) {
  function hr_t($key, $fallback = '') { return lang_text($key, $fallback); }
}
if (!function_exists('hr_h')) {
  function hr_h($key, $fallback = '') { return htmlspecialchars((string) hr_t($key, $fallback), ENT_QUOTES, 'UTF-8'); }
}
if (!function_exists('hr_js')) {
  function hr_js($key, $fallback = '') { return json_encode(hr_t($key, $fallback), JSON_HEX_TAG | JSON_HEX_APOS | JSON_HEX_AMP | JSON_HEX_QUOT); }
}
$defaultFrom=date('Y-01-01');$defaultTo='9999-12-31';$canInsert=isset($role_act['insert_act'])&&$role_act['insert_act']==='Y'; ?>
<style>
.ss-hero{background:linear-gradient(135deg,#7c2d12,#f59e0b);color:#fff;border-radius:14px;padding:20px;margin-bottom:18px;box-shadow:0 10px 24px rgba(15,23,42,.16)}.ss-hero h1{margin:0 0 6px;font-size:26px;font-weight:700}.ss-hero p{margin:0;opacity:.94}.ss-card{border-radius:12px;background:#fff;border:1px solid #e5edf5;box-shadow:0 5px 16px rgba(15,23,42,.05);margin-bottom:14px}.ss-kpi{padding:14px;border-radius:12px;background:#fffbeb;border:1px solid #fde68a}.ss-kpi b{font-size:22px;display:block}#dtb_salary_structure th,#dtb_salary_structure td{font-size:12px;vertical-align:middle}.select2-container{width:100%!important}.required-label:after{content:' *';color:#dd4b39}.ss-action{white-space:nowrap}#modal_salary_structure .modal-body{max-height:calc(100vh - 185px);overflow-y:auto}.ss-section-title{font-weight:700;color:#334155;margin:8px 0 12px;border-bottom:1px solid #e5e7eb;padding-bottom:7px}.ss-hint{background:#fef3c7;border:1px solid #fcd34d;border-radius:10px;padding:10px;margin-bottom:10px}.ss-detail-table th,.ss-detail-table td{font-size:12px;vertical-align:middle}.ss-detail-table .form-control{height:30px;padding:4px 6px;font-size:12px}.ss-detail-table .select2-container .select2-selection--single{height:30px}.ss-detail-table .select2-container--default .select2-selection--single .select2-selection__rendered{line-height:28px;font-size:12px}.ss-summary{background:#f8fafc;border:1px dashed #cbd5e1;border-radius:10px;padding:10px;margin-bottom:10px}
</style>
<section class="content-header"><h1><?=hr_h('hr_salary_structure', 'Salary Structure');?> <small>SAP HR Pay Scale Structure</small></h1><ol class="breadcrumb"><li><a href="<?=base_index();?>"><i class="fa fa-dashboard"></i> <?=hr_h('common_home', 'Home');?></a></li><li>Human Resource</li><li>Payroll</li><li class="active"><?=hr_h('hr_salary_structure', 'Salary Structure');?></li></ol></section>
<section class="content">
<div class="ss-hero"><div class="row"><div class="col-md-8"><h1>Salary Structure Workbench</h1><p>Kelola pay grade, pay level, salary band, effective date, cost/profit center, dan paket payroll component per struktur gaji.</p></div><div class="col-md-4 text-right"><?php if($canInsert){ ?><button id="btn_open_ss" class="btn btn-warning"><i class="fa fa-plus"></i> Create Structure</button><?php } ?> <button id="btn_export_ss" class="btn btn-success"><i class="fa fa-file-excel-o"></i> <?=hr_h('common_export_excel', 'Export Excel');?></button></div></div></div>
<div class="row"><div class="col-sm-2"><div class="ss-kpi"><span>Total</span><b id="kpi_total">0</b></div></div><div class="col-sm-2"><div class="ss-kpi"><span><?=hr_h('hr_active', 'Active');?></span><b id="kpi_active">0</b></div></div><div class="col-sm-2"><div class="ss-kpi"><span>Grades</span><b id="kpi_grade">0</b></div></div><div class="col-sm-2"><div class="ss-kpi"><span>Monthly</span><b id="kpi_monthly">0</b></div></div><div class="col-sm-2"><div class="ss-kpi"><span>Daily</span><b id="kpi_daily">0</b></div></div><div class="col-sm-2"><div class="ss-kpi"><span>Mgmt</span><b id="kpi_management">0</b></div></div></div>
<div class="box ss-card"><div class="box-header"><h3 class="box-title"><i class="fa fa-filter"></i> Filter Salary Structure</h3></div><div class="box-body"><form class="form-horizontal" onsubmit="return false;"><div class="form-group"><label class="control-label col-lg-2">Validity</label><div class="col-lg-2"><div class="input-group date ss-date"><input id="filter_tgl_awal" class="form-control" value="<?=$defaultFrom;?>"><span class="input-group-addon"><span class="glyphicon glyphicon-calendar"></span></span></div></div><div class="col-lg-2"><div class="input-group date ss-date"><input id="filter_tgl_akhir" class="form-control" value="<?=$defaultTo;?>"><span class="input-group-addon"><span class="glyphicon glyphicon-calendar"></span></span></div></div><label class="control-label col-lg-1">Scale</label><div class="col-lg-2"><select id="filter_pay_scale_type" class="form-control"><option value="">All</option><option>MONTHLY</option><option>DAILY</option><option>HOURLY</option><option>CONTRACT</option><option>MANAGEMENT</option></select></div><label class="control-label col-lg-1"><?=hr_h('common_status', 'Status');?></label><div class="col-lg-2"><select id="filter_structure_status" class="form-control"><option value="">All</option><option>DRAFT</option><option>ACTIVE</option><option>INACTIVE</option></select></div></div><div class="form-group"><label class="control-label col-lg-2">Pay Grade</label><div class="col-lg-2"><input id="filter_pay_grade" class="form-control text-uppercase" placeholder="G07"></div><label class="control-label col-lg-1">Group</label><div class="col-lg-2"><select id="filter_employee_group" class="form-control"><option value="">All</option><option>DIRECTOR</option><option>MANAGER</option><option>STAFF</option><option>NON_STAFF</option><option>OPERATOR</option><option>CONTRACT</option><option>DAILY_WORKER</option><option>TRAINEE</option><option>ALL</option></select></div><label class="control-label col-lg-1">Keyword</label><div class="col-lg-2"><input id="filter_keyword" class="form-control" placeholder="Code, name, level"></div><div class="col-lg-2"><button id="btn_filter_ss" class="btn btn-primary"><i class="fa fa-filter"></i> <?=hr_h('common_filter', 'Filter');?></button> <button id="btn_reset_ss" class="btn btn-default"><i class="fa fa-refresh"></i></button></div></div></form></div></div>
<div class="box ss-card"><div class="box-body"><div class="alert alert-warning error_data_delete" style="display:none"><button type="button" class="close hide_alert_notif">&times;</button><span class="isi_warning_delete"></span></div><div class="table-responsive"><table id="dtb_salary_structure" class="table table-bordered table-striped" style="width:100%"><thead><tr><th><?=hr_h('common_no', 'No');?></th><th><?=hr_h('common_action', 'Action');?></th><th>Structure</th><th>Pay Scale</th><th>Grade</th><th>Group</th><th>Salary Band</th><th>Component</th><th><?=hr_h('common_status', 'Status');?></th><th>Updated</th></tr></thead><tbody></tbody></table></div></div></div>
<div id="modal_salary_structure" class="modal fade"><div class="modal-dialog modal-lg" style="width:96%"><div class="modal-content"><form id="form_salary_structure"><input type="hidden" name="id" id="ss_id"><input type="hidden" name="detail_json" id="detail_json"><div class="modal-header"><button type="button" class="close" data-dismiss="modal">&times;</button><h4 class="modal-title">Create Salary Structure</h4></div><div class="modal-body"><div class="ss-hint"><strong>SAP hint:</strong> Salary Structure menggabungkan pay scale/grade dengan wage type. Detail component dipakai sebagai template payroll untuk employee yang masuk grade tersebut.</div>
<div class="ss-section-title">Structure Header</div><div class="row"><div class="col-md-2 form-group"><label class="required-label">Structure Code</label><input name="structure_code" id="structure_code" class="form-control text-uppercase" required maxlength="30" placeholder="SS-..."></div><div class="col-md-4 form-group"><label class="required-label">Structure Name</label><input name="structure_name" id="structure_name" class="form-control" required maxlength="150"></div><div class="col-md-2 form-group"><label>Pay Scale Type</label><select name="pay_scale_type" id="pay_scale_type" class="form-control"><option>MONTHLY</option><option>DAILY</option><option>HOURLY</option><option>CONTRACT</option><option>MANAGEMENT</option></select></div><div class="col-md-2 form-group"><label>Pay Scale Area</label><input name="pay_scale_area" id="pay_scale_area" class="form-control text-uppercase" value="ID"></div><div class="col-md-2 form-group"><label><?=hr_h('common_status', 'Status');?></label><select name="structure_status" id="structure_status" class="form-control"><option>DRAFT</option><option>ACTIVE</option><option>INACTIVE</option></select></div></div>
<div class="row"><div class="col-md-2 form-group"><label class="required-label">Pay Grade</label><input name="pay_grade" id="pay_grade" class="form-control text-uppercase" required placeholder="G07"></div><div class="col-md-2 form-group"><label class="required-label">Pay Level</label><input name="pay_level" id="pay_level" class="form-control text-uppercase" required placeholder="L1"></div><div class="col-md-3 form-group"><label>Position Level</label><input name="position_level" id="position_level" class="form-control"></div><div class="col-md-2 form-group"><label>Employee Group</label><select name="employee_group" id="employee_group" class="form-control"><option>ALL</option><option>DIRECTOR</option><option>MANAGER</option><option>STAFF</option><option>NON_STAFF</option><option>OPERATOR</option><option>CONTRACT</option><option>DAILY_WORKER</option><option>TRAINEE</option></select></div><div class="col-md-2 form-group"><label>Payroll Area</label><select name="payroll_area" id="payroll_area" class="form-control"><option>MONTHLY</option><option>DAILY</option><option>WEEKLY</option><option>CONTRACT</option><option>MANAGEMENT</option><option>ALL</option></select></div><div class="col-md-1 form-group"><label>Curr</label><select name="currency" id="currency" class="form-control"><option>IDR</option><option>USD</option></select></div></div>
<div class="ss-section-title">Salary Band & Organization</div><div class="row"><div class="col-md-2 form-group"><label>Salary Min</label><input name="base_salary_min" id="base_salary_min" type="number" step="0.01" min="0" class="form-control ss-amount" value="0"></div><div class="col-md-2 form-group"><label>Salary Mid</label><input name="base_salary_mid" id="base_salary_mid" type="number" step="0.01" min="0" class="form-control ss-amount" value="0"></div><div class="col-md-2 form-group"><label>Salary Max</label><input name="base_salary_max" id="base_salary_max" type="number" step="0.01" min="0" class="form-control ss-amount" value="0"></div><div class="col-md-2 form-group"><label>Annual CTC Min</label><input name="annual_ctc_min" id="annual_ctc_min" type="number" step="0.01" min="0" class="form-control" value="0"></div><div class="col-md-2 form-group"><label>Annual CTC Max</label><input name="annual_ctc_max" id="annual_ctc_max" type="number" step="0.01" min="0" class="form-control" value="0"></div><div class="col-md-1 form-group"><label>From</label><input name="valid_from" id="valid_from" class="form-control date-field" value="<?=$defaultFrom;?>"></div><div class="col-md-1 form-group"><label>To</label><input name="valid_to" id="valid_to" class="form-control date-field" value="<?=$defaultTo;?>"></div></div>
<div class="row"><div class="col-md-4 form-group"><label>Cost Center</label><select name="cost_center_code" id="cost_center_code" class="form-control"></select></div><div class="col-md-4 form-group"><label>Profit Center</label><select name="profit_center_code" id="profit_center_code" class="form-control"></select></div><div class="col-md-2 form-group"><label>SAP Reference</label><input name="sap_reference" id="sap_reference" class="form-control"></div><div class="col-md-2 form-group"><label><?=hr_h('common_remarks', 'Remarks');?></label><input name="remarks" id="remarks" class="form-control"></div></div>
<div class="ss-section-title">Payroll Component Package</div><div class="ss-summary"><div class="row"><div class="col-sm-4"><b>Total Component:</b> <span id="ss_component_count">0</span></div><div class="col-sm-4"><b>Total Fixed Amount:</b> <span id="ss_component_amount">0</span></div><div class="col-sm-4 text-right"><button type="button" id="btn_add_component" class="btn btn-sm btn-info"><i class="fa fa-plus"></i> Add Component</button></div></div></div>
<div class="table-responsive"><table class="table table-bordered table-condensed ss-detail-table"><thead><tr><th style="width:260px"><?=hr_h('hr_payroll_component', 'Payroll Component');?></th><th style="width:150px">Method</th><th style="width:110px">Amount</th><th style="width:90px">Rate</th><th>Formula</th><th style="width:75px">Mandatory</th><th style="width:70px">Tax</th><th style="width:70px">Slip</th><th style="width:75px">Seq</th><th style="width:45px"></th></tr></thead><tbody id="ss_component_body"></tbody></table></div>
</div><div class="modal-footer"><button type="button" class="btn btn-default" data-dismiss="modal"><?=hr_h('common_cancel', 'Cancel');?></button><button type="submit" class="btn btn-primary"><i class="fa fa-save"></i> Save Structure</button></div></form></div></div></div>
<div id="modal_ss_detail" class="modal fade"><div class="modal-dialog modal-lg" style="width:92%"><div class="modal-content"><div class="modal-header"><button class="close" data-dismiss="modal">&times;</button><h4 class="modal-title">Salary Structure Detail</h4></div><div class="modal-body" id="ss_detail_body"></div><div class="modal-footer"><button class="btn btn-default" data-dismiss="modal"><?=hr_h('common_close', 'Close');?></button></div></div></div></div>
</section>
<script src="<?=base_admin();?>assets/plugins/select2/select2.min.js"></script><script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
<script>
function ssError(m){$('.isi_warning_delete').text(m||'Salary Structure gagal diproses.');$('.error_data_delete').fadeIn();}
function ssFilters(){return{tgl_awal:$('#filter_tgl_awal').val(),tgl_akhir:$('#filter_tgl_akhir').val(),pay_scale_type:$('#filter_pay_scale_type').val(),pay_grade:$('#filter_pay_grade').val(),employee_group:$('#filter_employee_group').val(),structure_status:$('#filter_structure_status').val(),keyword:$('#filter_keyword').val()};}
function ssSet(s,v,t){var e=$(s);if(!v){e.val(null).trigger('change');return;}if(!e.find('option[value="'+v+'"]').length)e.append(new Option(t||v,v,true,true));e.val(v).trigger('change');}
function ssAjax(s,act,p,parent){$(s).select2({width:'100%',allowClear:true,placeholder:p,dropdownParent:parent||$(document.body),ajax:{url:'<?=base_admin();?>modul/salary_structure/salary_structure_action.php?act='+act,type:'POST',dataType:'json',delay:250,data:function(q){return{term:q.term||''};},processResults:function(d){return{results:d.results||[]};}}});}
function ssComponentRow(item){item=item||{};var tr=$('<tr>');tr.append('<td><select class="form-control ss-component"></select></td>');tr.append('<td><select class="form-control ss-method"><option>FIXED_AMOUNT</option><option>PERCENTAGE</option><option>FORMULA</option><option>ATTENDANCE_BASED</option><option>OVERTIME_BASED</option><option>MANUAL_INPUT</option></select></td>');tr.append('<td><input type="number" min="0" step="0.01" class="form-control ss-item-amount" value="'+(item.amount||0)+'"></td>');tr.append('<td><input type="number" min="0" step="0.0001" class="form-control ss-item-rate" value="'+(item.percentage_rate||0)+'"></td>');tr.append('<td><input class="form-control ss-formula" value="'+(item.formula_text||'')+'"></td>');tr.append('<td><select class="form-control ss-mandatory"><option>Y</option><option>N</option></select></td>');tr.append('<td><select class="form-control ss-taxable"><option>Y</option><option>N</option></select></td>');tr.append('<td><select class="form-control ss-slip"><option>Y</option><option>N</option></select></td>');tr.append('<td><input type="number" class="form-control ss-seq" value="'+(item.sequence_no||100)+'"></td>');tr.append('<td><button type="button" class="btn btn-danger btn-xs btn-remove-component"><i class="fa fa-trash"></i></button></td>');$('#ss_component_body').append(tr);ssAjax(tr.find('.ss-component'),'component_search','Pilih Payroll Component',$('#modal_salary_structure'));tr.find('.ss-method,.ss-mandatory,.ss-taxable,.ss-slip').select2({width:'100%',dropdownParent:$('#modal_salary_structure')});if(item.component_code)ssSet(tr.find('.ss-component'),item.component_code,item.component_text);tr.find('.ss-method').val(item.calculation_method||'FIXED_AMOUNT').trigger('change');tr.find('.ss-mandatory').val(item.mandatory||'Y').trigger('change');tr.find('.ss-taxable').val(item.taxable||'Y').trigger('change');tr.find('.ss-slip').val(item.payslip_display||'Y').trigger('change');ssCalcSummary();}
function ssCollect(){var arr=[];$('#ss_component_body tr').each(function(){arr.push({component_code:$(this).find('.ss-component').val()||'',calculation_method:$(this).find('.ss-method').val()||'FIXED_AMOUNT',amount:$(this).find('.ss-item-amount').val()||0,percentage_rate:$(this).find('.ss-item-rate').val()||0,formula_text:$(this).find('.ss-formula').val()||'',mandatory:$(this).find('.ss-mandatory').val()||'Y',taxable:$(this).find('.ss-taxable').val()||'Y',payslip_display:$(this).find('.ss-slip').val()||'Y',sequence_no:$(this).find('.ss-seq').val()||100});});return arr;}
function ssCalcSummary(){var arr=ssCollect(),sum=0;arr.forEach(function(x){sum+=parseFloat(x.amount||0)||0;});$('#ss_component_count').text(arr.length);$('#ss_component_amount').text(sum.toLocaleString('id-ID'));}
function ssReset(title){$('#form_salary_structure')[0].reset();$('#ss_id,#detail_json').val('');$('#cost_center_code,#profit_center_code').val(null).trigger('change');$('#ss_component_body').empty();$('#pay_scale_type').val('MONTHLY').trigger('change');$('#pay_scale_area').val('ID');$('#employee_group').val('ALL').trigger('change');$('#payroll_area').val('MONTHLY').trigger('change');$('#currency').val('IDR').trigger('change');$('#structure_status').val('DRAFT').trigger('change');$('#valid_from').val('<?=$defaultFrom;?>');$('#valid_to').val('<?=$defaultTo;?>');$('#base_salary_min,#base_salary_mid,#base_salary_max,#annual_ctc_min,#annual_ctc_max').val(0);$('#modal_salary_structure .modal-title').text(title||'Create Salary Structure');ssComponentRow({calculation_method:'FIXED_AMOUNT',mandatory:'Y',taxable:'Y',payslip_display:'Y',sequence_no:10});}
$(function(){if($.fn.datepicker){$('.ss-date,.date-field').datepicker({format:'yyyy-mm-dd',autoclose:true,todayHighlight:true});}if($.fn.select2){$('#filter_pay_scale_type,#filter_employee_group,#filter_structure_status,#pay_scale_type,#employee_group,#payroll_area,#currency,#structure_status').select2({width:'100%',allowClear:true});ssAjax('#cost_center_code','cost_center_search','Pilih Cost Center',$('#modal_salary_structure'));ssAjax('#profit_center_code','profit_center_search','Pilih Profit Center',$('#modal_salary_structure'));}
var dt=$('#dtb_salary_structure').DataTable({bProcessing:true,bServerSide:true,pageLength:25,dom:"<'row'<'col-sm-12'B>>"+"<'row'<'col-sm-6'l><'col-sm-6'f>>"+"<'row'<'col-sm-12'tr>>"+"<'row'<'col-sm-5'i><'col-sm-7'p>>",buttons:[{extend:'collection',text:<?=hr_js('common_export_data', 'Export Data');?>,buttons:['copyHtml5','excelHtml5','csvHtml5','pdfHtml5']}],columnDefs:[{targets:[0,1],orderable:false,searchable:false},{width:'42px',targets:0},{width:'150px',targets:1}],ajax:{url:'<?=base_admin();?>modul/salary_structure/salary_structure_data.php',type:'post',data:function(d){$.extend(d,ssFilters());},dataSrc:function(j){var k=j.kpi||{};$('#kpi_total').text(k.total||0);$('#kpi_active').text(k.active||0);$('#kpi_grade').text(k.grade||0);$('#kpi_monthly').text(k.monthly||0);$('#kpi_daily').text(k.daily||0);$('#kpi_management').text(k.management||0);return j.data||[];},error:function(x){console.log(x.responseText);ssError('Data Salary Structure gagal dimuat.');}}});
$('#btn_open_ss').click(function(){ssReset('Create Salary Structure');$('#modal_salary_structure').modal({backdrop:'static',keyboard:false});});$('#btn_filter_ss').click(function(){dt.draw();});$('#filter_keyword,#filter_pay_grade').keyup(function(e){if(e.keyCode===13)dt.draw();});$('#btn_reset_ss').click(function(){$('#filter_tgl_awal').val('<?=$defaultFrom;?>');$('#filter_tgl_akhir').val('<?=$defaultTo;?>');$('#filter_pay_scale_type,#filter_employee_group,#filter_structure_status').val(null).trigger('change');$('#filter_pay_grade,#filter_keyword').val('');dt.draw();});$('#btn_export_ss').click(function(){window.location='<?=base_admin();?>modul/salary_structure/salary_structure_action.php?act=export&'+$.param(ssFilters());});$('.hide_alert_notif').click(function(){$('.error_data_delete').hide();});$('#structure_code,#pay_grade,#pay_level,#pay_scale_area').on('keyup change',function(){this.value=this.value.toUpperCase();});$('#btn_add_component').click(function(){ssComponentRow({sequence_no:($('#ss_component_body tr').length+1)*10});});$(document).on('keyup change','.ss-item-amount,.ss-item-rate,.ss-formula,.ss-seq,.ss-component,.ss-method,.ss-mandatory,.ss-taxable,.ss-slip',ssCalcSummary);$(document).on('click','.btn-remove-component',function(){$(this).closest('tr').remove();ssCalcSummary();});
$('#form_salary_structure').submit(function(e){e.preventDefault();$('#detail_json').val(JSON.stringify(ssCollect()));var b=$(this).find('button[type=submit]');b.prop('disabled',true).html('<i class="fa fa-spinner fa-spin"></i> <?=hr_h('common_saving', 'Saving...');?>');$.post('<?=base_admin();?>modul/salary_structure/salary_structure_action.php?act=save',$(this).serialize(),function(r){b.prop('disabled',false).html('<i class="fa fa-save"></i> Save Structure');if(r.status==='good'){$('#modal_salary_structure').modal('hide');dt.draw(false);Swal.fire('Saved','Salary Structure berhasil disimpan.','success');}else ssError(r.error_message);},'json').fail(function(x){b.prop('disabled',false).html('<i class="fa fa-save"></i> Save Structure');ssError(x.responseText);});});
$(document).on('click','.btn-ss-detail',function(){$.post('<?=base_admin();?>modul/salary_structure/salary_structure_action.php?act=detail',{id:$(this).data('id')},function(h){$('#ss_detail_body').html(h);$('#modal_ss_detail').modal('show');});});
$(document).on('click','.btn-ss-edit',function(){var id=$(this).data('id');$.post('<?=base_admin();?>modul/salary_structure/salary_structure_action.php?act=get',{id:id},function(r){if(r.status!=='good'){ssError(r.error_message);return;}ssReset('Edit Salary Structure');var h=r.data||{};Object.keys(h).forEach(function(k){var el=$('#'+k);if(el.length&&k!=='cost_center_code'&&k!=='profit_center_code')el.val(h[k]);});$('#ss_id').val(h.id);ssSet('#cost_center_code',h.cost_center_code,h.cost_center_text);ssSet('#profit_center_code',h.profit_center_code,h.profit_center_text);$('#pay_scale_type,#employee_group,#payroll_area,#currency,#structure_status').trigger('change');$('#ss_component_body').empty();(h.items||[]).forEach(function(x){ssComponentRow(x);});if(!h.items||!h.items.length)ssComponentRow();$('#modal_salary_structure').modal({backdrop:'static',keyboard:false});},'json');});
$(document).on('click','.btn-ss-status',function(){var id=$(this).data('id'),status=$(this).data('status');$.post('<?=base_admin();?>modul/salary_structure/salary_structure_action.php?act=status',{id:id,status:status},function(r){if(r.status==='good'){dt.draw(false);Swal.fire('Updated','Status berhasil diubah.','success');}else ssError(r.error_message);},'json');});
$(document).on('click','.btn-ss-delete',function(){if($(this).is(':disabled'))return;var id=$(this).data('id'),no=$(this).data('no');Swal.fire({title:erpLang('confirm_delete_title','Delete Confirmation'),text:no,icon:'warning',showCancelButton:true,confirmButtonText:erpLang('common_delete','Delete'),cancelButtonText:erpLang('common_cancel','Cancel')}).then(function(x){if(!x.isConfirmed)return;$.post('<?=base_admin();?>modul/salary_structure/salary_structure_action.php?act=delete',{id:id},function(r){if(r.status==='good'){dt.draw(false);Swal.fire(erpLang('common_deleted','Deleted'),erpLang('common_deleted_message','Data deleted successfully.'),'success');}else ssError(r.error_message);},'json').fail(function(x){ssError(x.responseText);});});});
});
</script>
