<?php
if (!function_exists('hr_t')) {
  function hr_t($key, $fallback = '') { return lang_text($key, $fallback); }
}
if (!function_exists('hr_h')) {
  function hr_h($key, $fallback = '') { return htmlspecialchars((string) hr_t($key, $fallback), ENT_QUOTES, 'UTF-8'); }
}
if (!function_exists('hr_js')) {
  function hr_js($key, $fallback = '') { return json_encode(hr_t($key, $fallback), JSON_HEX_TAG | JSON_HEX_APOS | JSON_HEX_AMP | JSON_HEX_QUOT); }
}
if (session_status() === PHP_SESSION_NONE) session_start();
include "../../inc/config.php";
session_check_json();
function phd_h($v){return htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');}
function phd_label($s){$m=array('ACTIVE'=>'success','ARCHIVED'=>'default','LOCKED'=>'primary','VOID'=>'danger','APPROVED'=>'success','PENDING'=>'warning','SUBMITTED'=>'primary','MANAGER_REVIEW'=>'warning','NOT_SUBMITTED'=>'default');$c=isset($m[$s])?$m[$s]:'default';return '<span class="label label-'.$c.'">'.phd_h($s?:'-').'</span>';}
function phd_rating($r){$m=array('A'=>'success','B'=>'primary','C'=>'info','D'=>'warning','E'=>'danger');$c=isset($m[$r])?$m[$r]:'default';return '<span class="label label-'.$c.'" style="font-size:13px">'.phd_h($r?:'-').'</span>';}
function phd_filters(){return array('from'=>isset($_POST['tgl_awal'])&&$_POST['tgl_awal']!==''?$_POST['tgl_awal']:date('Y-01-01'),'to'=>isset($_POST['tgl_akhir'])&&$_POST['tgl_akhir']!==''?$_POST['tgl_akhir']:date('Y-m-d'),'cycle_year'=>isset($_POST['cycle_year'])?trim($_POST['cycle_year']):'','appraisal_period'=>isset($_POST['appraisal_period'])?trim($_POST['appraisal_period']):'','employee_id'=>isset($_POST['employee_id'])?trim($_POST['employee_id']):'','department_code'=>isset($_POST['department_code'])?trim($_POST['department_code']):'','job_title_id'=>isset($_POST['job_title_id'])?trim($_POST['job_title_id']):'','final_rating'=>isset($_POST['final_rating'])?trim($_POST['final_rating']):'','history_status'=>isset($_POST['history_status'])?trim($_POST['history_status']):'','audit_source'=>isset($_POST['audit_source'])?trim($_POST['audit_source']):'','impact_type'=>isset($_POST['impact_type'])?trim($_POST['impact_type']):'','keyword'=>isset($_POST['keyword'])?trim($_POST['keyword']):'');}
function phd_where($f,&$p){$w=" WHERE h.appraisal_date BETWEEN ? AND ? ";array_push($p,$f['from'],$f['to']);foreach(array('cycle_year','appraisal_period','department_code','final_rating','history_status','audit_source') as $k){if($f[$k]!==''){$w.=" AND h.$k=? ";$p[]=$f[$k];}}foreach(array('employee_id','job_title_id') as $k){if($f[$k]!==''){$w.=" AND h.$k=? ";$p[]=(int)$f[$k];}}if($f['impact_type']==='HIGH')$w.=" AND h.final_rating IN ('A','B') AND h.final_score>=85 ";elseif($f['impact_type']==='LOW')$w.=" AND (h.final_rating IN ('D','E') OR h.final_score<70) ";elseif($f['impact_type']==='PIP')$w.=" AND h.improvement_required='Y' ";if($f['keyword']!==''){$kw='%'.$f['keyword'].'%';$w.=" AND (h.history_no LIKE ? OR h.appraisal_no LIKE ? OR h.employee_no LIKE ? OR h.full_name LIKE ? OR d.nm_dept LIKE ? OR jt.job_title_name LIKE ?) ";for($i=0;$i<6;$i++)$p[]=$kw;}return $w;}
$draw=isset($_POST['draw'])?(int)$_POST['draw']:1;$start=isset($_POST['start'])?max(0,(int)$_POST['start']):0;$length=isset($_POST['length'])?(int)$_POST['length']:25;if($length<=0||$length>500)$length=25;
$f=phd_filters();$p=array();$w=phd_where($f,$p);
$base=" FROM erp_performance_history h LEFT JOIN dept d ON d.kd_dept=h.department_code LEFT JOIN erp_job_title jt ON jt.id=h.job_title_id LEFT JOIN erp_employee_master ap ON ap.id=h.appraiser_employee_id ";
$kpi=$db->fetch("SELECT COUNT(*) total,COUNT(DISTINCT h.employee_id) employees,ROUND(AVG(h.final_score),2) avg_score,SUM(h.history_status='LOCKED') locked_count,SUM(h.final_rating IN ('A','B')) high_count,SUM(h.improvement_required='Y') pip_count $base $w",$p);
$cnt=$db->fetch("SELECT COUNT(*) jml $base $w",$p);$total=$cnt?(int)$cnt->jml:0;
$orderMap=array(2=>'h.history_no',3=>'h.employee_no',4=>'d.kd_dept',5=>'h.cycle_year',6=>'h.manager_kpi_score',7=>'h.final_score',8=>'h.final_rating',9=>'h.history_status',10=>'h.updated_at');$orderBy='h.appraisal_date DESC,h.id DESC';
if(isset($_POST['order'][0]['column'])){$col=(int)$_POST['order'][0]['column'];$dir=(isset($_POST['order'][0]['dir'])&&strtolower($_POST['order'][0]['dir'])==='desc')?'DESC':'ASC';if(isset($orderMap[$col]))$orderBy=$orderMap[$col].' '.$dir;}
$rows=$db->query("SELECT h.*,d.nm_dept,jt.job_title_code,jt.job_title_name,ap.employee_no appraiser_no,ap.full_name appraiser_name,(SELECT COUNT(*) FROM erp_performance_history_detail x WHERE x.performance_history_id=h.id) line_count $base $w ORDER BY $orderBy LIMIT $start,$length",$p);
$data=array();$no=$start+1;foreach($rows as $r){$data[]=array($no++,'<button class="btn btn-info btn-xs btn-phist-detail" data-id="'.(int)$r->id.'"><i class="fa fa-eye"></i></button>','<strong>'.phd_h($r->history_no).'</strong><br><small>'.phd_h($r->appraisal_no?:'-').'</small>','<strong>'.phd_h($r->employee_no).'</strong><br><small>'.phd_h($r->full_name).' / '.phd_h($r->employee_group).'</small>','<strong>'.phd_h($r->department_code?:'-').'</strong><br><small>'.phd_h($r->nm_dept?:'-').'</small><br><small>'.phd_h($r->job_title_code?:'-').' '.phd_h($r->job_title_name?:'').'</small>',phd_h($r->cycle_year.' / '.$r->appraisal_period).'<br><small>'.phd_h($r->appraisal_type).' / '.phd_h($r->appraisal_date).'</small>','KPI '.number_format((float)$r->manager_kpi_score,2).'<br><small>Comp '.number_format((float)$r->competency_score,2).' | Beh '.number_format((float)$r->behavior_score,2).'</small>','<strong>'.number_format((float)$r->final_score,2).'</strong><br><small>Items '.(int)$r->line_count.'</small>',phd_rating($r->final_rating),phd_label($r->history_status).'<br><small>'.phd_h($r->audit_source).'</small>',phd_label($r->appraisal_status).'<br><small>'.phd_h($r->approval_status).'</small>',phd_h($r->updated_by?:$r->created_by?:'-').'<br><small>'.phd_h($r->updated_at?:$r->created_at).'</small>');}
header('Content-Type: application/json; charset=utf-8');echo json_encode(array('draw'=>$draw,'recordsTotal'=>$total,'recordsFiltered'=>$total,'data'=>$data,'kpi'=>array('total'=>$kpi?(int)$kpi->total:0,'employees'=>$kpi?(int)$kpi->employees:0,'avg_score'=>$kpi&&$kpi->avg_score!==null?$kpi->avg_score:0,'locked'=>$kpi?(int)$kpi->locked_count:0,'high'=>$kpi?(int)$kpi->high_count:0,'pip'=>$kpi?(int)$kpi->pip_count:0)));
?>
