<?php
$today=date('Y-m-d');$defaultFrom=date('Y-01-01');$defaultTo=date('Y-12-31');
$plants=$db->query("SELECT id,plant_code,plant_name FROM erp_plant WHERE status='Aktif' ORDER BY plant_code")->fetchAll(PDO::FETCH_OBJ);
$shifts=$db->query("SELECT id,kode_shift,nama_shift,jam_mulai,jam_selesai FROM erp_shift WHERE status='Aktif' ORDER BY kode_shift")->fetchAll(PDO::FETCH_OBJ);
?>
<style>
.fc-hero{background:linear-gradient(135deg,#0f766e,#1d4ed8);color:#fff;border-radius:14px;padding:20px;margin-bottom:18px;box-shadow:0 10px 24px rgba(15,23,42,.16)}.fc-hero h1{margin:0 0 6px;font-size:26px;font-weight:700}.fc-hero p{margin:0;opacity:.92}.fc-card{border-radius:12px;background:#fff;border:1px solid #e5edf5;box-shadow:0 5px 16px rgba(15,23,42,.05);margin-bottom:14px}#dtb_factory_calendar th,#dtb_factory_calendar td{font-size:12px;vertical-align:middle}.select2-container{width:100%!important}.required-label:after{content:' *';color:#dd4b39}.fc-action{white-space:nowrap}.fc-pill{display:inline-block;border-radius:999px;background:#dcfce7;color:#166534;padding:3px 9px;font-size:12px;margin-left:6px}.fc-week{display:flex;gap:8px;flex-wrap:wrap}.fc-week label{border:1px solid #dbeafe;border-radius:10px;padding:8px 10px;background:#f8fafc;min-width:86px}.fc-week input{margin-right:6px}#modal_fc .modal-body{max-height:calc(100vh - 185px);overflow-y:auto}
</style>
<section class="content-header"><h1>Factory Calendar <small>SAP PP Calendar Workbench</small></h1><ol class="breadcrumb"><li><a href="<?=base_index();?>"><i class="fa fa-dashboard"></i> Home</a></li><li class="active">Factory Calendar</li></ol></section>
<section class="content">
  <div class="fc-hero"><div class="row"><div class="col-md-8"><h1>Factory Calendar Workbench</h1><p>Kelola kalender kerja per plant: working day, holiday, special day, default shift, dan jam kerja untuk MRP serta production scheduling.</p></div><div class="col-md-4 text-right"><button id="btn_open_fc" class="btn btn-warning"><i class="fa fa-plus"></i> Create Calendar</button></div></div></div>
  <div class="box fc-card"><div class="box-header"><h3 class="box-title"><i class="fa fa-filter"></i> Filter Factory Calendar</h3></div><div class="box-body"><form class="form-horizontal" onsubmit="return false;"><div class="form-group"><label class="control-label col-lg-2">Validity Overlap</label><div class="col-lg-2"><div class="input-group date fc-date"><input id="filter_tgl_awal" class="form-control" value="<?=$defaultFrom;?>"><span class="input-group-addon"><span class="glyphicon glyphicon-calendar"></span></span></div></div><div class="col-lg-2"><div class="input-group date fc-date"><input id="filter_tgl_akhir" class="form-control" value="<?=$defaultTo;?>"><span class="input-group-addon"><span class="glyphicon glyphicon-calendar"></span></span></div></div><label class="control-label col-lg-1">Plant</label><div class="col-lg-2"><select id="filter_plant" class="form-control"><option value="">Semua</option><?php foreach($plants as $p){ ?><option value="<?=htmlspecialchars($p->plant_code,ENT_QUOTES,'UTF-8');?>"><?=htmlspecialchars($p->plant_code.' - '.$p->plant_name,ENT_QUOTES,'UTF-8');?></option><?php } ?></select></div><label class="control-label col-lg-1">Status</label><div class="col-lg-2"><select id="filter_status" class="form-control"><option value="">Semua</option><option>DRAFT</option><option>RELEASED</option><option>INACTIVE</option></select></div></div><div class="form-group"><label class="control-label col-lg-2">Search</label><div class="col-lg-7"><input id="filter_keyword" class="form-control" placeholder="Calendar code / name / plant / shift"></div><div class="col-lg-3"><button id="btn_filter_fc" class="btn btn-primary"><i class="fa fa-filter"></i> Filter</button> <button id="btn_reset_fc" class="btn btn-default"><i class="fa fa-refresh"></i> Reset</button> <button id="btn_export_fc" class="btn btn-success"><i class="fa fa-file-excel-o"></i> Export Excel</button></div></div></form></div></div>
  <div class="box fc-card"><div class="box-body"><div class="alert alert-warning error_data_delete" style="display:none"><button type="button" class="close hide_alert_notif">&times;</button><span class="isi_warning_delete"></span></div><div class="table-responsive"><table id="dtb_factory_calendar" class="table table-bordered table-striped" style="width:100%"><thead><tr><th>No</th><th>Action</th><th>Calendar</th><th>Plant</th><th>Validity</th><th>Work Pattern</th><th>Default Shift</th><th>Work/Holiday</th><th>Exceptions</th><th>Status</th><th>Updated By</th></tr></thead><tbody></tbody></table></div></div></div>
  <div id="modal_fc" class="modal fade"><div class="modal-dialog modal-lg" style="width:92%"><div class="modal-content"><form id="form_fc"><input type="hidden" name="id" id="fc_id"><div class="modal-header"><button class="close" data-dismiss="modal">&times;</button><h4 class="modal-title">Create Factory Calendar</h4></div><div class="modal-body">
    <div class="alert alert-info">Calendar days otomatis dibuat saat save. Kalau ada hari tertentu yang beda, buka detail lalu ubah exception day dari data harian.</div>
    <div class="row"><div class="col-md-2 form-group"><label>Calendar Code</label><input id="calendar_code" class="form-control" readonly placeholder="Loading..."></div><div class="col-md-4 form-group"><label class="required-label">Calendar Name</label><input name="calendar_name" id="calendar_name" class="form-control" required placeholder="Main Plant Calendar 2026"></div><div class="col-md-2 form-group"><label class="required-label">Plant</label><select name="plant_id" id="plant_id" class="form-control" required><option value="">Pilih Plant</option><?php foreach($plants as $p){ ?><option value="<?=intval($p->id);?>" data-code="<?=htmlspecialchars($p->plant_code,ENT_QUOTES,'UTF-8');?>"><?=htmlspecialchars($p->plant_code.' - '.$p->plant_name,ENT_QUOTES,'UTF-8');?></option><?php } ?></select><input type="hidden" name="plant_code" id="plant_code"></div><div class="col-md-2 form-group"><label class="required-label">Valid From</label><input name="valid_from" id="valid_from" class="form-control date-field" value="<?=$defaultFrom;?>" required></div><div class="col-md-2 form-group"><label class="required-label">Valid To</label><input name="valid_to" id="valid_to" class="form-control date-field" value="<?=$defaultTo;?>" required></div></div>
    <div class="row"><div class="col-md-3 form-group"><label>Default Shift</label><select name="default_shift_id" id="default_shift_id" class="form-control"><option value="">Tanpa Shift</option><?php foreach($shifts as $s){ ?><option value="<?=intval($s->id);?>" data-code="<?=htmlspecialchars($s->kode_shift,ENT_QUOTES,'UTF-8');?>"><?=htmlspecialchars($s->kode_shift.' - '.$s->nama_shift.' ('.$s->jam_mulai.'-'.$s->jam_selesai.')',ENT_QUOTES,'UTF-8');?></option><?php } ?></select><input type="hidden" name="default_shift_code" id="default_shift_code"></div><div class="col-md-2 form-group"><label class="required-label">Working Hours</label><input type="number" step="0.01" min="0.01" name="working_hours" id="working_hours" class="form-control text-right" value="8.00" required></div><div class="col-md-7 form-group"><label>Remarks</label><input name="remarks" id="remarks" class="form-control" placeholder="Catatan kalender, aturan cuti bersama, overtime, dll"></div></div>
    <div class="form-group"><label>Weekly Working Pattern</label><div class="fc-week">
      <label><input type="checkbox" name="monday" id="monday" value="Y" checked>Monday</label>
      <label><input type="checkbox" name="tuesday" id="tuesday" value="Y" checked>Tuesday</label>
      <label><input type="checkbox" name="wednesday" id="wednesday" value="Y" checked>Wednesday</label>
      <label><input type="checkbox" name="thursday" id="thursday" value="Y" checked>Thursday</label>
      <label><input type="checkbox" name="friday" id="friday" value="Y" checked>Friday</label>
      <label><input type="checkbox" name="saturday" id="saturday" value="Y">Saturday</label>
      <label><input type="checkbox" name="sunday" id="sunday" value="Y">Sunday</label>
    </div><small class="text-muted">Default SAP umumnya Senin-Jumat kerja. Sabtu/Minggu bisa diaktifkan bila plant berjalan 6/7 hari.</small></div>
    <div class="fc-pill">Save akan membuat/update daily calendar sesuai pattern, kecuali day yang sudah ditandai EXCEPTION.</div>
  </div><div class="modal-footer"><button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button><button type="submit" class="btn btn-primary"><i class="fa fa-save"></i> Save & Generate Days</button></div></form></div></div></div>
  <div id="modal_fc_detail" class="modal fade"><div class="modal-dialog modal-lg" style="width:96%"><div class="modal-content"><div class="modal-header"><button class="close" data-dismiss="modal">&times;</button><h4 class="modal-title">Factory Calendar Detail</h4></div><div class="modal-body" id="fc_detail_body"></div><div class="modal-footer"><button class="btn btn-default" data-dismiss="modal">Close</button></div></div></div></div>
</section>
<script src="<?=base_admin();?>assets/plugins/select2/select2.min.js"></script><script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
<script>
function fcError(m){$('.isi_warning_delete').text(m||'Factory Calendar gagal diproses.');$('.error_data_delete').fadeIn();}
function esc(s){return String(s||'').replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c];});}
function filters(){return{tgl_awal:$('#filter_tgl_awal').val(),tgl_akhir:$('#filter_tgl_akhir').val(),status:$('#filter_status').val(),plant:$('#filter_plant').val(),keyword:$('#filter_keyword').val()};}
function setWeek(h){['monday','tuesday','wednesday','thursday','friday','saturday','sunday'].forEach(function(k){$('#'+k).prop('checked',(h&&h[k]==='Y')||(!h&&['monday','tuesday','wednesday','thursday','friday'].indexOf(k)>=0));});}
function loadNextNo(){ $('#calendar_code').val('Loading...'); $.post('<?=base_admin();?>modul/factory_calendar/factory_calendar_action.php?act=next_no',{},function(r){$('#calendar_code').val(r.status==='good'?(r.calendar_code||'Auto'):'Auto');},'json').fail(function(){$('#calendar_code').val('Auto');});}
function openForm(title,isEdit){$('#form_fc')[0].reset();$('#fc_id,#plant_code,#default_shift_code').val('');$('#calendar_code').val('');$('#plant_id,#default_shift_id').val('').trigger('change');$('#valid_from').val('<?=$defaultFrom;?>');$('#valid_to').val('<?=$defaultTo;?>');$('#working_hours').val('8.00');setWeek(null);$('#modal_fc .modal-title').text(title||'Create Factory Calendar');$('#modal_fc').modal({backdrop:'static',keyboard:false});if(!isEdit)loadNextNo();}
$(function(){if($.fn.datepicker){$('.fc-date,.date-field').datepicker({format:'yyyy-mm-dd',autoclose:true,todayHighlight:true});}if($.fn.select2){$('#filter_plant,#filter_status').select2({width:'100%'});$('#plant_id,#default_shift_id').select2({width:'100%',dropdownParent:$('#modal_fc')});}
var dt=null;function reloadTable(resetPaging){if(dt&&dt.draw)dt.draw(resetPaging===false?false:undefined);}try{if($.fn.DataTable){dt=$('#dtb_factory_calendar').DataTable({bProcessing:true,bServerSide:true,pageLength:25,dom:"<'row'<'col-sm-12'B>>"+"<'row'<'col-sm-6'l><'col-sm-6'f>>"+"<'row'<'col-sm-12'tr>>"+"<'row'<'col-sm-5'i><'col-sm-7'p>>",buttons:[{extend:'collection',text:'Export Data',buttons:['copyHtml5','excelHtml5','csvHtml5','pdfHtml5']}],columnDefs:[{targets:[0,1],orderable:false,searchable:false},{width:'42px',targets:0},{width:'210px',targets:1}],ajax:{url:'<?=base_admin();?>modul/factory_calendar/factory_calendar_data.php',type:'post',data:function(d){$.extend(d,filters());},error:function(xhr){console.log(xhr.responseText);fcError('Data Factory Calendar gagal dimuat.');}}});}}catch(e){console.error(e);fcError('Data Factory Calendar gagal dimuat. Tombol Create tetap bisa digunakan.');}
$('#btn_open_fc').click(function(){openForm('Create Factory Calendar',false);});$('#plant_id').change(function(){$('#plant_code').val($('#plant_id option:selected').data('code')||'');});$('#default_shift_id').change(function(){$('#default_shift_code').val($('#default_shift_id option:selected').data('code')||'');});$('#btn_filter_fc').click(function(){reloadTable();});$('#filter_keyword').keyup(function(e){if(e.keyCode===13)reloadTable();});$('#btn_reset_fc').click(function(){$('#filter_tgl_awal').val('<?=$defaultFrom;?>');$('#filter_tgl_akhir').val('<?=$defaultTo;?>');$('#filter_status,#filter_plant').val('').trigger('change');$('#filter_keyword').val('');reloadTable();});$('#btn_export_fc').click(function(){window.location='<?=base_admin();?>modul/factory_calendar/factory_calendar_action.php?act=excel&'+$.param(filters());});$('.hide_alert_notif').click(function(){$('.error_data_delete').hide();});
$('#form_fc').submit(function(e){e.preventDefault();var btn=$(this).find('button[type=submit]');btn.prop('disabled',true).html('<i class="fa fa-spinner fa-spin"></i> Saving...');$.post('<?=base_admin();?>modul/factory_calendar/factory_calendar_action.php?act=save',$(this).serialize(),function(r){if(r.status==='good'){$('#modal_fc').modal('hide');reloadTable(false);Swal.fire('Saved','Calendar days generated: '+(r.generated||0),'success');}else fcError(r.error_message);btn.prop('disabled',false).html('<i class="fa fa-save"></i> Save & Generate Days');},'json').fail(function(xhr){fcError(xhr.responseText);btn.prop('disabled',false).html('<i class="fa fa-save"></i> Save & Generate Days');});});
$(document).on('click','.btn-fc-detail',function(){$.post('<?=base_admin();?>modul/factory_calendar/factory_calendar_action.php?act=detail',{id:$(this).data('id')},function(html){$('#fc_detail_body').html(html);$('#modal_fc_detail').modal('show');});});
$(document).on('click','.btn-fc-edit',function(){var id=$(this).data('id');$.post('<?=base_admin();?>modul/factory_calendar/factory_calendar_action.php?act=get',{id:id},function(r){if(r.status!=='good'){fcError(r.error_message);return;}openForm('Edit Factory Calendar',true);var h=r.header||{};$('#fc_id').val(h.id);$('#calendar_code').val(h.calendar_code);$('#calendar_name').val(h.calendar_name);$('#plant_id').val(h.plant_id||'').trigger('change');$('#plant_code').val(h.plant_code||'');$('#valid_from').val(h.valid_from);$('#valid_to').val(h.valid_to);$('#default_shift_id').val(h.default_shift_id||'').trigger('change');$('#default_shift_code').val(h.default_shift_code||'');$('#working_hours').val(h.working_hours||8);$('#remarks').val(h.remarks);setWeek(h);},'json');});
function statusAction(act,id,no,title,input){var cfg={title:title,text:no,icon:'question',showCancelButton:true,confirmButtonText:title};if(input){cfg.input='text';cfg.inputLabel='Reason '+no;cfg.inputValidator=function(v){return !v?'Reason wajib diisi':undefined;};}Swal.fire(cfg).then(function(x){if(!x.isConfirmed)return;var data={id:id};if(input)data.reason=x.value;$.post('<?=base_admin();?>modul/factory_calendar/factory_calendar_action.php?act='+act,data,function(r){if(r.status==='good'){reloadTable(false);if(r.generated)Swal.fire('Generated','Calendar days generated: '+r.generated,'success');}else fcError(r.error_message);},'json').fail(function(xhr){fcError(xhr.responseText);});});}
$(document).on('click','.btn-fc-generate',function(){statusAction('generate',$(this).data('id'),$(this).data('no'),'Generate Days');});$(document).on('click','.btn-fc-release',function(){statusAction('release',$(this).data('id'),$(this).data('no'),'Release Calendar');});$(document).on('click','.btn-fc-inactive',function(){statusAction('inactive',$(this).data('id'),$(this).data('no'),'Set Inactive',true);});$(document).on('click','.btn-fc-delete',function(){statusAction('delete',$(this).data('id'),$(this).data('no'),'Delete Draft');});
});
</script>
