<?php
if(session_status()===PHP_SESSION_NONE)session_start();
include "../../inc/config.php";
session_check_json();
function fc_h($v){return htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');}
function fc_label($s){$m=array('DRAFT'=>'default','RELEASED'=>'success','INACTIVE'=>'warning');$c=isset($m[$s])?$m[$s]:'default';return '<span class="label label-'.$c.'">'.fc_h($s).'</span>';}
function fc_filters(){return array('from'=>isset($_POST['tgl_awal'])&&$_POST['tgl_awal']!==''?$_POST['tgl_awal']:date('Y-01-01'),'to'=>isset($_POST['tgl_akhir'])&&$_POST['tgl_akhir']!==''?$_POST['tgl_akhir']:date('Y-12-31'),'status'=>isset($_POST['status'])?trim($_POST['status']):'','plant'=>isset($_POST['plant'])?trim($_POST['plant']):'','keyword'=>isset($_POST['keyword'])?trim($_POST['keyword']):'');}
function fc_where($f,&$p){$w=" WHERE h.valid_from<=? AND h.valid_to>=? ";$p[]=$f['to'];$p[]=$f['from'];if($f['status']!==''){$w.=" AND h.calendar_status=? ";$p[]=$f['status'];}if($f['plant']!==''){$w.=" AND h.plant_code=? ";$p[]=$f['plant'];}if($f['keyword']!==''){$kw='%'.$f['keyword'].'%';$w.=" AND (h.calendar_code LIKE ? OR h.calendar_name LIKE ? OR h.plant_code LIKE ? OR h.default_shift_code LIKE ?) ";for($i=0;$i<4;$i++)$p[]=$kw;}return $w;}
$draw=isset($_POST['draw'])?(int)$_POST['draw']:1;$start=isset($_POST['start'])?max(0,(int)$_POST['start']):0;$length=isset($_POST['length'])?(int)$_POST['length']:25;if($length<=0||$length>500)$length=25;
$f=fc_filters();$p=array();$w=fc_where($f,$p);$c=$db->fetch("SELECT COUNT(*) jml FROM erp_factory_calendar_header h $w",$p);$total=$c?(int)$c->jml:0;
$rows=$db->query("SELECT h.*,COALESCE(x.total_days,0) total_days,COALESCE(x.work_days,0) work_days,COALESCE(x.holidays,0) holidays,COALESCE(x.exceptions,0) exceptions FROM erp_factory_calendar_header h LEFT JOIN(SELECT calendar_id,COUNT(*) total_days,SUM(tipe_hari='Kerja') work_days,SUM(tipe_hari='Libur') holidays,SUM(source_type='EXCEPTION') exceptions FROM erp_factory_calendar GROUP BY calendar_id)x ON x.calendar_id=h.id $w ORDER BY h.valid_from DESC,h.id DESC LIMIT $start,$length",$p);
$data=array();$no=$start+1;
foreach($rows as $r){$act='<div class="fc-action"><button class="btn btn-info btn-xs btn-fc-detail" data-id="'.(int)$r->id.'" title="Detail"><i class="fa fa-eye"></i></button> <button class="btn btn-default btn-xs btn-fc-generate" data-id="'.(int)$r->id.'" data-no="'.fc_h($r->calendar_code).'" title="Generate"><i class="fa fa-refresh"></i></button> ';if($r->calendar_status==='DRAFT'){$act.='<button class="btn btn-primary btn-xs btn-fc-edit" data-id="'.(int)$r->id.'" title="Edit"><i class="fa fa-pencil"></i></button> <button class="btn btn-success btn-xs btn-fc-release" data-id="'.(int)$r->id.'" data-no="'.fc_h($r->calendar_code).'" title="Release"><i class="fa fa-check"></i></button> <button class="btn btn-danger btn-xs btn-fc-delete" data-id="'.(int)$r->id.'" data-no="'.fc_h($r->calendar_code).'" title="Delete"><i class="fa fa-trash"></i></button>';}elseif($r->calendar_status==='RELEASED'){$act.='<button class="btn btn-warning btn-xs btn-fc-inactive" data-id="'.(int)$r->id.'" data-no="'.fc_h($r->calendar_code).'" title="Inactive"><i class="fa fa-ban"></i></button>';}$act.='</div>';
  $pattern=($r->monday==='Y'?'Mo ':'').($r->tuesday==='Y'?'Tu ':'').($r->wednesday==='Y'?'We ':'').($r->thursday==='Y'?'Th ':'').($r->friday==='Y'?'Fr ':'').($r->saturday==='Y'?'Sa ':'').($r->sunday==='Y'?'Su ':'');
  $data[]=array($no++,$act,'<strong>'.fc_h($r->calendar_code).'</strong><br><small>'.fc_h($r->calendar_name).'</small>',fc_h($r->plant_code),fc_h($r->valid_from.' s/d '.$r->valid_to),fc_h(trim($pattern)),'<strong>'.fc_h($r->default_shift_code?:'-').'</strong><br><small>'.number_format((float)$r->working_hours,2,',','.').' hours</small>','<span class="badge bg-green">'.(int)$r->work_days.'</span> / <span class="badge bg-red">'.(int)$r->holidays.'</span>','<span class="badge bg-yellow">'.(int)$r->exceptions.'</span>',fc_label($r->calendar_status),fc_h($r->updated_by?:$r->created_by));
}
header('Content-Type: application/json; charset=utf-8');echo json_encode(array('draw'=>$draw,'recordsTotal'=>$total,'recordsFiltered'=>$total,'data'=>$data));
?>
