<?php
if (!function_exists('fin_t')) {
  function fin_t($key, $fallback = '') { return lang_text($key, $fallback); }
}
if (!function_exists('fin_h')) {
  function fin_h($key, $fallback = '') { return htmlspecialchars((string) fin_t($key, $fallback), ENT_QUOTES, 'UTF-8'); }
}
if (!function_exists('fin_js')) {
  function fin_js($key, $fallback = '') { return json_encode(fin_t($key, $fallback), JSON_HEX_TAG | JSON_HEX_APOS | JSON_HEX_AMP | JSON_HEX_QUOT); }
}
require_once "incoming_payment_lib.php";
function ip_rows($q){$r=array();foreach($q as $x)$r[]=$x;return $r;}
$customers=ip_rows($db->query("SELECT kode_pemasok,nama FROM customer WHERE kode_pemasok IS NOT NULL ORDER BY nama"));
$invoices=ip_rows($db->query("SELECT si.id_sales,si.no_sales_invoice,si.invoice_no,si.bill_to,COALESCE(c.nama,si.bill_to) customer_name,si.gross_amount,COALESCE((SELECT SUM(amount) FROM erp_incoming_payment ip WHERE ip.sales_invoice_id=si.id_sales AND ip.status='POSTED'),0) paid_amount FROM sales_invoice si LEFT JOIN customer c ON c.kode_pemasok=si.bill_to WHERE si.billing_status IN ('POSTED','DRAFT') ORDER BY si.invoice_date DESC LIMIT 500"));
$bankAccounts=ip_rows($db->query("SELECT r.no_rek,r.nama_rek FROM rekening r LEFT JOIN rekening c ON c.induk=r.no_rek WHERE c.no_rek IS NULL AND (r.no_rek LIKE '112%' OR r.nama_rek LIKE '%Bank%' OR r.nama_rek LIKE '%Giro%') ORDER BY r.no_rek"));
$arAccounts=ip_rows($db->query("SELECT r.no_rek,r.nama_rek FROM rekening r LEFT JOIN rekening c ON c.induk=r.no_rek WHERE c.no_rek IS NULL AND (r.no_rek LIKE '121%' OR r.nama_rek LIKE '%Piutang%') ORDER BY r.no_rek"));
$currencies=ip_rows($db->query("SELECT jenis_valas FROM matauang GROUP BY jenis_valas ORDER BY jenis_valas='IDR' DESC, jenis_valas"));
?>
<link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/css/bootstrap-datepicker.min.css">
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/js/bootstrap-datepicker.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
<style>.ip-table th,.ip-table td{font-size:12px;vertical-align:middle!important}.ip-kpi .description-header{font-size:20px}.ip-help{background:#f8fbff;border-left:3px solid #3c8dbc;padding:10px;margin-bottom:12px}.required:after{content:" *";color:#dd4b39}</style>
<section class="content-header"><h1><?=fin_h('finance_incoming_payment', 'Incoming Payment');?> <small>SAP FI-AR Incoming Payment</small></h1><ol class="breadcrumb"><li><a href="<?=base_index();?>"><i class="fa fa-dashboard"></i> <?=fin_h('common_home', 'Home');?></a></li><li>Akunting</li><li>Accounts Receivable</li><li class="active"><?=fin_h('finance_incoming_payment', 'Incoming Payment');?></li></ol></section>
<section class="content">
<div class="row ip-kpi"><div class="col-md-3"><div class="box box-widget"><div class="box-body"><div class="description-block"><span><?=fin_h('finance_total', 'Total');?></span><h5 id="kpi_total" class="description-header text-blue">0.00</h5></div></div></div></div><div class="col-md-3"><div class="box box-widget"><div class="box-body"><div class="description-block"><span><?=fin_h('finance_posted', 'Posted');?></span><h5 id="kpi_posted" class="description-header text-green">0.00</h5></div></div></div></div><div class="col-md-3"><div class="box box-widget"><div class="box-body"><div class="description-block"><span><?=fin_h('finance_draft', 'Draft');?></span><h5 id="kpi_draft" class="description-header text-yellow">0.00</h5></div></div></div></div><div class="col-md-3"><div class="box box-widget"><div class="box-body"><div class="description-block"><span>Documents</span><h5 id="kpi_count" class="description-header">0</h5></div></div></div></div></div>
<div class="box box-primary"><div class="box-header with-border"><h3 class="box-title">Incoming Payment Cockpit</h3><div class="box-tools"><button id="btn_add" class="btn btn-primary btn-sm"><i class="fa fa-plus"></i> Create Incoming Payment</button> <button id="btn_excel" class="btn btn-success btn-sm"><i class="fa fa-file-excel-o"></i> <?=fin_h('common_export_excel', 'Export Excel');?></button></div></div><div class="box-body">
<form id="ip_filter" class="form-horizontal"><div class="form-group"><label class="control-label col-md-1">Tanggal</label><div class="col-md-2"><div class="input-group date"><input id="start_date" class="form-control" value="<?=date('Y-m-01');?>"><span class="input-group-addon"><i class="fa fa-calendar"></i></span></div></div><div class="col-md-2"><div class="input-group date"><input id="end_date" class="form-control" value="<?=date('Y-m-d');?>"><span class="input-group-addon"><i class="fa fa-calendar"></i></span></div></div><label class="control-label col-md-1"><?=fin_h('common_status', 'Status');?></label><div class="col-md-2"><select id="filter_status" class="form-control select2-filter"><option value="">All</option><option value="DRAFT"><?=fin_h('finance_draft', 'Draft');?></option><option value="POSTED"><?=fin_h('finance_posted', 'Posted');?></option><option value="REVERSED">Reversed</option></select></div><label class="control-label col-md-1"><?=fin_h('finance_customer', 'Customer');?></label><div class="col-md-3"><select id="filter_customer_code" class="form-control select2-filter"><option value=""></option><?php foreach($customers as $c){ ?><option value="<?=ip_h($c->kode_pemasok);?>"><?=ip_h($c->kode_pemasok.' - '.$c->nama);?></option><?php } ?></select></div></div><div class="form-group"><div class="col-md-12"><button type="button" id="btn_filter" class="btn btn-primary"><i class="fa fa-search"></i> Tampilkan</button> <button type="button" id="btn_reset" class="btn btn-default"><i class="fa fa-refresh"></i> <?=fin_h('common_reset', 'Reset');?></button></div></div></form>
<div class="ip-help"><i class="fa fa-info-circle"></i> Posting incoming payment membuat jurnal <b>Dr Bank</b> dan <b>Cr Account Receivable</b>.</div>
<div class="table-responsive"><table class="table table-bordered table-striped ip-table" id="ip_table"><thead><tr><th><?=fin_h('common_no', 'No');?></th><th>Posting</th><th>Payment No</th><th><?=fin_h('finance_customer', 'Customer');?></th><th><?=fin_h('finance_invoice', 'Invoice');?></th><th><?=fin_h('common_status', 'Status');?></th><th><?=fin_h('finance_bank', 'Bank');?></th><th>Method</th><th>Bank Ref</th><th><?=fin_h('finance_amount', 'Amount');?></th><th>Curr</th><th><?=fin_h('common_action', 'Action');?></th></tr></thead><tbody></tbody></table></div>
</div></div></section>
<div class="modal fade" id="ip_modal"><div class="modal-dialog modal-lg"><div class="modal-content"><form id="ip_form"><input type="hidden" name="id" id="id"><input type="hidden" name="sales_invoice_no" id="sales_invoice_no"><div class="modal-header bg-primary"><button type="button" class="close" data-dismiss="modal">&times;</button><h4>Incoming Payment Entry</h4></div><div class="modal-body">
<div class="row"><div class="col-md-3"><label><?=fin_h('common_no', 'No');?></label><input name="incoming_payment_no" id="incoming_payment_no" class="form-control" readonly></div><div class="col-md-5"><label>Sales Invoice</label><select name="sales_invoice_id" id="sales_invoice_id" class="form-control select2-modal"><option value=""></option><?php foreach($invoices as $i){$open=max(0,(float)$i->gross_amount-(float)$i->paid_amount); ?><option value="<?=$i->id_sales;?>" data-no="<?=ip_h($i->no_sales_invoice);?>" data-customer="<?=ip_h($i->bill_to);?>" data-open="<?=$open;?>"><?=ip_h(($i->no_sales_invoice?:$i->invoice_no).' - '.$i->customer_name.' - Open '.ip_num($open));?></option><?php } ?></select></div><div class="col-md-4"><label class="required"><?=fin_h('finance_customer', 'Customer');?></label><select name="customer_code" id="customer_code" class="form-control select2-modal" required><option value=""></option><?php foreach($customers as $c){ ?><option value="<?=ip_h($c->kode_pemasok);?>"><?=ip_h($c->kode_pemasok.' - '.$c->nama);?></option><?php } ?></select></div></div><br>
<div class="row"><div class="col-md-3"><label><?=fin_h('finance_document_date', 'Document Date');?></label><div class="input-group date"><input name="document_date" id="document_date" class="form-control" value="<?=date('Y-m-d');?>"><span class="input-group-addon"><i class="fa fa-calendar"></i></span></div></div><div class="col-md-3"><label><?=fin_h('finance_posting_date', 'Posting Date');?></label><div class="input-group date"><input name="posting_date" id="posting_date" class="form-control" value="<?=date('Y-m-d');?>"><span class="input-group-addon"><i class="fa fa-calendar"></i></span></div></div><div class="col-md-3"><label>Value Date</label><div class="input-group date"><input name="value_date" id="value_date" class="form-control" value="<?=date('Y-m-d');?>"><span class="input-group-addon"><i class="fa fa-calendar"></i></span></div></div><div class="col-md-3"><label>Method</label><select name="payment_method" id="payment_method" class="form-control select2-modal"><option value="TRANSFER">Transfer</option><option value="GIRO">Giro</option><option value="CASH"><?=fin_h('finance_cash', 'Cash');?></option><option value="VIRTUAL_ACCOUNT">Virtual Account</option><option value="OTHER">Other</option></select></div></div><br>
<div class="row"><div class="col-md-6"><label class="required">Bank Account</label><select name="bank_account" id="bank_account" class="form-control select2-modal" required><option value=""></option><?php foreach($bankAccounts as $a){ ?><option value="<?=ip_h($a->no_rek);?>"><?=ip_h($a->no_rek.' - '.$a->nama_rek);?></option><?php } ?></select></div><div class="col-md-6"><label class="required">AR Account</label><select name="ar_account" id="ar_account" class="form-control select2-modal" required><option value=""></option><?php foreach($arAccounts as $a){ ?><option value="<?=ip_h($a->no_rek);?>"><?=ip_h($a->no_rek.' - '.$a->nama_rek);?></option><?php } ?></select></div></div><br>
<div class="row"><div class="col-md-3"><label class="required"><?=fin_h('finance_amount', 'Amount');?></label><input name="amount" id="amount" type="number" step="0.01" class="form-control text-right" required></div><div class="col-md-2"><label><?=fin_h('finance_currency', 'Currency');?></label><select name="currency" id="currency" class="form-control select2-modal"><?php foreach($currencies as $c){ ?><option value="<?=ip_h($c->jenis_valas);?>" <?=$c->jenis_valas==='IDR'?'selected':'';?>><?=ip_h($c->jenis_valas);?></option><?php } ?></select></div><div class="col-md-2"><label>Kurs</label><input name="kurs" id="kurs" type="number" step="0.0001" class="form-control text-right" value="1"></div><div class="col-md-2"><label>Bank Ref</label><input name="bank_reference" id="bank_reference" class="form-control"></div><div class="col-md-3"><label>External Ref</label><input name="external_reference" id="external_reference" class="form-control"></div></div><br><label><?=fin_h('finance_description', 'Description');?></label><input name="description" id="description" class="form-control" required>
</div><div class="modal-footer"><button type="button" class="btn btn-default" data-dismiss="modal"><?=fin_h('common_close', 'Close');?></button><button type="button" class="btn btn-warning ip-save" data-act="save">Save Draft</button><button type="button" class="btn btn-success ip-save" data-act="post"><?=fin_h('common_post', 'Post');?></button></div></form></div></div></div>
<div class="modal fade" id="ip_detail_modal"><div class="modal-dialog modal-lg"><div class="modal-content"><div class="modal-header bg-primary"><button type="button" class="close" data-dismiss="modal">&times;</button><h4>Incoming Payment Detail</h4></div><div class="modal-body" id="ip_detail_body"></div></div></div></div>
<script>
$(function(){ $('.input-group.date').datepicker({format:'yyyy-mm-dd',autoclose:true,todayHighlight:true});$('.select2-filter').select2({width:'100%',allowClear:true,placeholder:'All'});var ipTable=null;function initSel(){$('.select2-modal').select2({width:'100%',dropdownParent:$('#ip_modal'),allowClear:true});}function params(){return{start_date:$('#start_date').val(),end_date:$('#end_date').val(),status:$('#filter_status').val(),customer_code:$('#filter_customer_code').val()};}function rebuildIpTable(){if(ipTable){ipTable.destroy();}ipTable=$('#ip_table').DataTable({pageLength:25,order:[[1,'desc']],dom:'Bfrtip',buttons:[{extend:'excelHtml5',text:'<i class="fa fa-file-excel-o"></i> Excel',className:'btn btn-success btn-sm',title:'Incoming Payment'},{extend:'print',text:'<i class="fa fa-print"></i> Print',className:'btn btn-default btn-sm',title:'Incoming Payment'}],columnDefs:[{targets:[9],className:'text-right'},{targets:[11],orderable:false,searchable:false,className:'text-center'}]});}function loadData(){if(ipTable){ipTable.destroy();ipTable=null;}$('#ip_table tbody').html('<tr><td colspan="12" class="text-center">Loading...</td></tr>');$.post('<?=base_admin();?>modul/incoming_payment/incoming_payment_action.php?act=filter',params(),function(r){if(r.status==='success'){$('#ip_table tbody').html(r.html);$('#kpi_total').text(r.total);$('#kpi_posted').text(r.posted);$('#kpi_draft').text(r.draft);$('#kpi_count').text(r.count);rebuildIpTable();}else{$('#ip_table tbody').html('<tr><td colspan="12" class="text-danger text-center">'+r.message+'</td></tr>');}},'json');}
$('#btn_filter').on('click',loadData);$('#btn_reset').on('click',function(){$('#ip_filter')[0].reset();$('.select2-filter').val('').trigger('change');$('#start_date').val('<?=date('Y-m-01');?>');$('#end_date').val('<?=date('Y-m-d');?>');loadData();});$('#btn_add').on('click',function(){$('#ip_form')[0].reset();$('#id').val('');$('#document_date,#posting_date,#value_date').val('<?=date('Y-m-d');?>');$('#kurs').val('1');$.getJSON('<?=base_admin();?>modul/incoming_payment/incoming_payment_action.php?act=get_no',function(r){$('#incoming_payment_no').val(r.no);});$('#ip_modal').modal('show');initSel();});
$('#sales_invoice_id').on('change',function(){var o=$(this).find(':selected');$('#customer_code').val(o.data('customer')).trigger('change');$('#sales_invoice_no').val(o.data('no'));if(o.data('open'))$('#amount').val(o.data('open'));});
$(document).on('click','.ip-save',function(){var act=$(this).data('act');$.post('<?=base_admin();?>modul/incoming_payment/incoming_payment_action.php?act='+act,$('#ip_form').serialize(),function(r){if(r.status==='success'){Swal.fire('Berhasil',r.message,'success');$('#ip_modal').modal('hide');loadData();}else Swal.fire('Gagal',r.message,'error');},'json');});
$(document).on('click','.ip-edit',function(){$.getJSON('<?=base_admin();?>modul/incoming_payment/incoming_payment_action.php?act=get&id='+$(this).data('id'),function(r){if(r.status!=='success'){Swal.fire('Gagal',r.message,'error');return;}var d=r.data;$('#ip_form')[0].reset();$.each(d,function(k,v){$('#'+k).val(v);});$('#id').val(d.id);$('#ip_modal').modal('show');initSel();$('.select2-modal').trigger('change');});});
$(document).on('click','.ip-detail',function(){$('#ip_detail_modal').modal('show');$('#ip_detail_body').html(<?=fin_js('common_loading', 'Loading...');?>);$.getJSON('<?=base_admin();?>modul/incoming_payment/incoming_payment_action.php?act=detail&id='+$(this).data('id'),function(r){$('#ip_detail_body').html(r.status==='success'?r.html:'<div class="alert alert-danger">'+r.message+'</div>');});});
$(document).on('click','.ip-post',function(){var id=$(this).data('id');Swal.fire({title:'Post incoming payment?',icon:'question',showCancelButton:true}).then(function(x){if(x.isConfirmed){$.post('<?=base_admin();?>modul/incoming_payment/incoming_payment_action.php?act=post',{id:id},function(r){r.status==='success'?Swal.fire('Berhasil',r.message,'success'):Swal.fire('Gagal',r.message,'error');loadData();},'json');}});});$('#btn_excel').on('click',function(){window.open('<?=base_admin();?>modul/incoming_payment/incoming_payment_action.php?act=excel&'+$.param(params()));});loadData();});
</script>
