<?php if (!function_exists('finrep_h')) { function finrep_h($value) { return htmlspecialchars((string)$value, ENT_QUOTES, 'UTF-8'); } } ?>
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
<style>.lrp-table th,.lrp-table td{font-size:12px;vertical-align:middle!important;white-space:nowrap}.lrp-group th{background:#1d4ed8!important;color:#fff}.lrp-category th,.lrp-category td{background:#e0f2fe!important;font-weight:700}.lrp-total th,.lrp-total td{background:#f3f4f6!important;font-weight:700}.lrp-net th,.lrp-net td{background:#0f766e!important;color:#fff;font-weight:700}.lrp-account{padding-left:18px!important}.lrp-level-3{padding-left:34px!important}.lrp-toolbar{margin-bottom:14px}</style>
<section class="content-header"><h1>Laba/Rugi (Perbandingan Periode) <small>Finance Reports</small></h1><ol class="breadcrumb"><li><a href="<?=base_index();?>"><i class="fa fa-dashboard"></i> Home</a></li><li><a href="<?=base_index();?>finance-report">Finance Reports</a></li><li class="active">Laba/Rugi (Perbandingan Periode)</li></ol></section>
<section class="content"><div class="box box-primary"><div class="box-header with-border"><h3 class="box-title">Profit & Loss Comparison</h3><div class="box-tools"><button id="btn_excel" class="btn btn-success btn-sm"><i class="fa fa-file-excel-o"></i> Export Excel</button> <button id="btn_print" class="btn btn-default btn-sm"><i class="fa fa-print"></i> Print/PDF</button></div></div><div class="box-body">
<form id="form_lrp" class="form-horizontal lrp-toolbar"><div class="form-group"><label class="control-label col-md-2">Periode Ini</label><div class="col-md-2"><input type="date" id="current_start_date" name="current_start_date" class="form-control" value="<?=date('Y-m-01');?>"></div><div class="col-md-2"><input type="date" id="current_end_date" name="current_end_date" class="form-control" value="<?=date('Y-m-d');?>"></div><label class="control-label col-md-2">Pembanding</label><div class="col-md-2"><input type="date" id="compare_start_date" name="compare_start_date" class="form-control"></div><div class="col-md-2"><input type="date" id="compare_end_date" name="compare_end_date" class="form-control"></div></div><div class="form-group"><div class="col-md-offset-2 col-md-10"><button type="submit" id="btn_filter" class="btn btn-primary"><i class="fa fa-search"></i> Tampilkan</button> <button type="button" id="btn_auto_compare" class="btn btn-default"><i class="fa fa-refresh"></i> Pembanding Otomatis</button></div></div></form>
<p class="text-muted"><i class="fa fa-info-circle"></i> Nilai dari jurnal FI POSTED dan kategori resmi <code>coa_kategori.kategori_akun</code>. Pendapatan dan beban tampil positif; laba bersih dihitung pendapatan dikurangi beban.</p><div id="lrp_alert" class="alert alert-danger" style="display:none"></div><div id="lrp_result"><div class="text-center text-muted" style="padding:30px">Klik Tampilkan untuk memuat laporan.</div></div></div></div></section>
<script>
$(function(){function fmt(d){var m=('0'+(d.getMonth()+1)).slice(-2),day=('0'+d.getDate()).slice(-2);return d.getFullYear()+'-'+m+'-'+day;}function autoCompare(){var s=new Date($('#current_start_date').val()),e=new Date($('#current_end_date').val());if(isNaN(s)||isNaN(e)||s>e)return;var days=Math.round((e-s)/86400000);var ce=new Date(s);ce.setDate(ce.getDate()-1);var cs=new Date(ce);cs.setDate(cs.getDate()-days);$('#compare_start_date').val(fmt(cs));$('#compare_end_date').val(fmt(ce));}
function qs(){return $('#form_lrp').serialize();}function loadReport(){$('#lrp_alert').hide().text('');$('#lrp_result').html('<div class="text-center" style="padding:30px"><i class="fa fa-spinner fa-spin fa-2x"></i><br>Loading...</div>');$('#btn_filter').prop('disabled',true);$.ajax({url:'<?=base_admin();?>modul/finance_report/finance_report_laba_rugi_perbandingan_periode_action.php?act=filter',type:'POST',dataType:'json',data:qs()}).done(function(res){if(res.status==='success')$('#lrp_result').html(res.html);else{$('#lrp_result').html('<div class="alert alert-danger">'+(res.message||'Laporan gagal diproses.')+'</div>');$('#lrp_alert').text(res.message||'Laporan gagal diproses.').show();}}).fail(function(xhr){$('#lrp_result').html('<div class="alert alert-danger">Server error</div>');$('#lrp_alert').text(xhr.responseText||'Server error').show();}).always(function(){$('#btn_filter').prop('disabled',false);});}
$('#btn_auto_compare').on('click',function(){autoCompare();});$('#current_start_date,#current_end_date').on('change',autoCompare);$('#form_lrp').on('submit',function(e){e.preventDefault();loadReport();});$('#btn_excel').on('click',function(){window.location='<?=base_admin();?>modul/finance_report/finance_report_laba_rugi_perbandingan_periode_action.php?act=excel&'+qs();});$('#btn_print').on('click',function(){window.open('<?=base_admin();?>modul/finance_report/finance_report_laba_rugi_perbandingan_periode_action.php?act=print&'+qs(),'_blank');});autoCompare();loadReport();});
</script>
