<?php if (!function_exists('finrep_h')) { function finrep_h($value) { return htmlspecialchars((string)$value, ENT_QUOTES, 'UTF-8'); } } ?>
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
<style>.lrba-table th,.lrba-table td{font-size:12px;vertical-align:middle!important;white-space:nowrap}.lrba-group th{background:#1d4ed8!important;color:#fff}.lrba-category th,.lrba-category td{background:#e0f2fe!important;font-weight:700}.lrba-total th,.lrba-total td{background:#f3f4f6!important;font-weight:700}.lrba-net th,.lrba-net td{background:#0f766e!important;color:#fff;font-weight:700}.lrba-fav{color:#0f766e;font-weight:700}.lrba-unfav{color:#b91c1c;font-weight:700}.lrba-account{padding-left:18px!important}.lrba-level-3{padding-left:34px!important}.lrba-toolbar{margin-bottom:14px}</style>
<section class="content-header"><h1>Laba/Rugi (Perbandingan Anggaran) <small>Finance Reports</small></h1><ol class="breadcrumb"><li><a href="<?=base_index();?>"><i class="fa fa-dashboard"></i> Home</a></li><li><a href="<?=base_index();?>finance-report">Finance Reports</a></li><li class="active">Laba/Rugi (Perbandingan Anggaran)</li></ol></section>
<section class="content"><div class="box box-primary"><div class="box-header with-border"><h3 class="box-title">P&L Budget Comparison</h3><div class="box-tools"><button id="btn_excel" class="btn btn-success btn-sm"><i class="fa fa-file-excel-o"></i> Export Excel</button> <button id="btn_print" class="btn btn-default btn-sm"><i class="fa fa-print"></i> Print/PDF</button></div></div><div class="box-body">
<form id="form_lrba" class="form-horizontal lrba-toolbar"><div class="form-group"><label class="control-label col-md-1">Periode</label><div class="col-md-2"><input type="date" id="start_date" name="start_date" class="form-control" value="<?=date('Y-m-01');?>"></div><div class="col-md-2"><input type="date" id="end_date" name="end_date" class="form-control" value="<?=date('Y-m-d');?>"></div><label class="control-label col-md-2">Budget Version</label><div class="col-md-2"><input type="text" id="budget_version" name="budget_version" class="form-control" placeholder="Optional"></div><div class="col-md-3"><button type="submit" id="btn_filter" class="btn btn-primary"><i class="fa fa-search"></i> Tampilkan</button></div></div><div class="form-group"><label class="control-label col-md-1">Cost Center</label><div class="col-md-2"><input type="number" id="cost_center" name="cost_center" class="form-control" placeholder="Optional"></div><label class="control-label col-md-2">Profit Center</label><div class="col-md-2"><input type="number" id="profit_center" name="profit_center" class="form-control" placeholder="Optional"></div></div></form>
<p class="text-muted"><i class="fa fa-info-circle"></i> Actual dari jurnal FI POSTED. Budget dari <code>finance_budget_header</code> dan <code>finance_budget_detail</code>. Variance diberi status favorable/unfavorable sesuai sifat income/expense.</p><div id="lrba_alert" class="alert alert-danger" style="display:none"></div><div id="lrba_result"><div class="text-center text-muted" style="padding:30px">Klik Tampilkan untuk memuat laporan.</div></div></div></div></section>
<script>
$(function(){function qs(){return $('#form_lrba').serialize();}function loadReport(){$('#lrba_alert').hide().text('');$('#lrba_result').html('<div class="text-center" style="padding:30px"><i class="fa fa-spinner fa-spin fa-2x"></i><br>Loading...</div>');$('#btn_filter').prop('disabled',true);$.ajax({url:'<?=base_admin();?>modul/finance_report/finance_report_laba_rugi_perbandingan_anggaran_action.php?act=filter',type:'POST',dataType:'json',data:qs()}).done(function(res){if(res.status==='success')$('#lrba_result').html(res.html);else{$('#lrba_result').html('<div class="alert alert-danger">'+(res.message||'Laporan gagal diproses.')+'</div>');$('#lrba_alert').text(res.message||'Laporan gagal diproses.').show();}}).fail(function(xhr){$('#lrba_result').html('<div class="alert alert-danger">Server error</div>');$('#lrba_alert').text(xhr.responseText||'Server error').show();}).always(function(){$('#btn_filter').prop('disabled',false);});}
$('#form_lrba').on('submit',function(e){e.preventDefault();loadReport();});$('#btn_excel').on('click',function(){window.location='<?=base_admin();?>modul/finance_report/finance_report_laba_rugi_perbandingan_anggaran_action.php?act=excel&'+qs();});$('#btn_print').on('click',function(){window.open('<?=base_admin();?>modul/finance_report/finance_report_laba_rugi_perbandingan_anggaran_action.php?act=print&'+qs(),'_blank');});loadReport();});
</script>
