<?php if (!function_exists('finrep_h')) { function finrep_h($value) { return htmlspecialchars((string)$value, ENT_QUOTES, 'UTF-8'); } } ?>
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
<style>.cfi-table th,.cfi-table td{font-size:12px;vertical-align:middle!important}.cfi-section th{background:#1d4ed8!important;color:#fff}.cfi-total th,.cfi-total td{background:#f3f4f6!important;font-weight:700}.cfi-grand th,.cfi-grand td{background:#0f766e!important;color:#fff;font-weight:700}.cfi-check th,.cfi-check td{background:#fff7ed!important;font-weight:700}.cfi-account{padding-left:28px!important}.cfi-toolbar{margin-bottom:14px}</style>
<section class="content-header"><h1>Arus Kas (Tak Langsung) <small>Finance Reports</small></h1><ol class="breadcrumb"><li><a href="<?=base_index();?>"><i class="fa fa-dashboard"></i> Home</a></li><li><a href="<?=base_index();?>finance-report">Finance Reports</a></li><li class="active">Arus Kas (Tak Langsung)</li></ol></section>
<section class="content"><div class="box box-primary"><div class="box-header with-border"><h3 class="box-title">Indirect Cash Flow Statement</h3><div class="box-tools"><button id="btn_excel" class="btn btn-success btn-sm"><i class="fa fa-file-excel-o"></i> Export Excel</button> <button id="btn_print" class="btn btn-default btn-sm"><i class="fa fa-print"></i> Print/PDF</button></div></div><div class="box-body">
<form id="form_cfi" class="form-horizontal cfi-toolbar"><div class="form-group"><label class="control-label col-md-1">Periode</label><div class="col-md-2"><input type="date" id="start_date" name="start_date" class="form-control" value="<?=date('Y-m-01');?>"></div><div class="col-md-2"><input type="date" id="end_date" name="end_date" class="form-control" value="<?=date('Y-m-d');?>"></div><div class="col-md-7"><button type="submit" id="btn_filter" class="btn btn-primary"><i class="fa fa-search"></i> Tampilkan</button></div></div></form>
<p class="text-muted"><i class="fa fa-info-circle"></i> Menggunakan jurnal FI POSTED, kategori resmi COA, dan mapping <code>cash_flow_mapping</code> bila tersedia.</p><div id="cfi_alert" class="alert alert-danger" style="display:none"></div><div id="cfi_result"><div class="text-center text-muted" style="padding:30px">Klik Tampilkan untuk memuat laporan.</div></div></div></div></section>
<script>
$(function(){function loadReport(){$('#cfi_alert').hide().text('');$('#cfi_result').html('<div class="text-center" style="padding:30px"><i class="fa fa-spinner fa-spin fa-2x"></i><br>Loading...</div>');$('#btn_filter').prop('disabled',true);$.ajax({url:'<?=base_admin();?>modul/finance_report/finance_report_arus_kas_tak_langsung_action.php?act=filter',type:'POST',dataType:'json',data:$('#form_cfi').serialize()}).done(function(res){if(res.status==='success')$('#cfi_result').html(res.html);else{$('#cfi_result').html('<div class="alert alert-danger">'+(res.message||'Laporan gagal diproses.')+'</div>');$('#cfi_alert').text(res.message||'Laporan gagal diproses.').show();}}).fail(function(xhr){$('#cfi_result').html('<div class="alert alert-danger">Server error</div>');$('#cfi_alert').text(xhr.responseText||'Server error').show();}).always(function(){$('#btn_filter').prop('disabled',false);});}
$('#form_cfi').on('submit',function(e){e.preventDefault();loadReport();});$('#btn_excel').on('click',function(){window.location='<?=base_admin();?>modul/finance_report/finance_report_arus_kas_tak_langsung_action.php?act=excel&'+$('#form_cfi').serialize();});$('#btn_print').on('click',function(){window.open('<?=base_admin();?>modul/finance_report/finance_report_arus_kas_tak_langsung_action.php?act=print&'+$('#form_cfi').serialize(),'_blank');});loadReport();});
</script>
