<?php if (!function_exists('finrep_h')) { function finrep_h($value) { return htmlspecialchars((string)$value, ENT_QUOTES, 'UTF-8'); } } ?>
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
<style>.nis-table th,.nis-table td{font-size:12px;vertical-align:middle!important}.nis-side{background:#1d4ed8!important;color:#fff;text-align:center}.nis-category td{background:#e0f2fe!important;font-weight:700}.nis-total td{background:#f3f4f6!important;font-weight:700}.nis-grand td{background:#0f766e!important;color:#fff;font-weight:700}.nis-diff td{background:#fff7ed!important;font-weight:700}.nis-account{padding-left:18px!important}.nis-level-3{padding-left:34px!important}.nis-toolbar{margin-bottom:14px}</style>
<section class="content-header"><h1>Neraca (Induk Skontro) <small>Finance Reports</small></h1><ol class="breadcrumb"><li><a href="<?=base_index();?>"><i class="fa fa-dashboard"></i> Home</a></li><li><a href="<?=base_index();?>finance-report">Finance Reports</a></li><li class="active">Neraca (Induk Skontro)</li></ol></section>
<section class="content"><div class="box box-primary"><div class="box-header with-border"><h3 class="box-title">Balance Sheet Skontro</h3><div class="box-tools"><button id="btn_excel" class="btn btn-success btn-sm"><i class="fa fa-file-excel-o"></i> Export Excel</button> <button id="btn_print" class="btn btn-default btn-sm"><i class="fa fa-print"></i> Print/PDF</button></div></div><div class="box-body">
<form id="form_nis" class="form-horizontal nis-toolbar"><div class="form-group"><label class="control-label col-md-2">As Of Date</label><div class="col-md-2"><input type="date" id="as_of_date" name="as_of_date" class="form-control" value="<?=date('Y-m-d');?>"></div><div class="col-md-8"><button type="submit" id="btn_filter" class="btn btn-primary"><i class="fa fa-search"></i> Tampilkan</button></div></div></form>
<p class="text-muted"><i class="fa fa-info-circle"></i> Layout horizontal: Aset di kiri, Kewajiban dan Modal di kanan. Saldo dihitung dari <code>saldo_awal</code> + jurnal FI POSTED, dengan laba/rugi berjalan ke modal.</p><div id="nis_alert" class="alert alert-danger" style="display:none"></div><div id="nis_result"><div class="text-center text-muted" style="padding:30px">Klik Tampilkan untuk memuat laporan.</div></div></div></div></section>
<script>
$(function(){function qs(){return $('#form_nis').serialize();}function loadReport(){$('#nis_alert').hide().text('');$('#nis_result').html('<div class="text-center" style="padding:30px"><i class="fa fa-spinner fa-spin fa-2x"></i><br>Loading...</div>');$('#btn_filter').prop('disabled',true);$.ajax({url:'<?=base_admin();?>modul/finance_report/finance_report_neraca_induk_skontro_action.php?act=filter',type:'POST',dataType:'json',data:qs()}).done(function(res){if(res.status==='success')$('#nis_result').html(res.html);else{$('#nis_result').html('<div class="alert alert-danger">'+(res.message||'Laporan gagal diproses.')+'</div>');$('#nis_alert').text(res.message||'Laporan gagal diproses.').show();}}).fail(function(xhr){$('#nis_result').html('<div class="alert alert-danger">Server error</div>');$('#nis_alert').text(xhr.responseText||'Server error').show();}).always(function(){$('#btn_filter').prop('disabled',false);});}
$('#form_nis').on('submit',function(e){e.preventDefault();loadReport();});$('#btn_excel').on('click',function(){window.location='<?=base_admin();?>modul/finance_report/finance_report_neraca_induk_skontro_action.php?act=excel&'+qs();});$('#btn_print').on('click',function(){window.open('<?=base_admin();?>modul/finance_report/finance_report_neraca_induk_skontro_action.php?act=print&'+qs(),'_blank');});loadReport();});
</script>
