<?php
if (!function_exists('hr_t')) {
  function hr_t($key, $fallback = '') { return lang_text($key, $fallback); }
}
if (!function_exists('hr_h')) {
  function hr_h($key, $fallback = '') { return htmlspecialchars((string) hr_t($key, $fallback), ENT_QUOTES, 'UTF-8'); }
}
if (!function_exists('hr_js')) {
  function hr_js($key, $fallback = '') { return json_encode(hr_t($key, $fallback), JSON_HEX_TAG | JSON_HEX_APOS | JSON_HEX_AMP | JSON_HEX_QUOT); }
}
if (session_status() === PHP_SESSION_NONE) session_start();
include "../../inc/config.php";
session_check_json();
function ek_json($s,$m='',$x=array()){header('Content-Type: application/json; charset=utf-8');$p=array('status'=>$s);if($m!=='')$p[$s==='good'?'message':'error_message']=$m;foreach($x as $k=>$v)$p[$k]=$v;echo json_encode($p);exit;}
function ek_h($v){return htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');}
function ek_p($k,$d=''){return isset($_POST[$k])?$_POST[$k]:$d;}
function ek_user(){return isset($_SESSION['username'])&&$_SESSION['username']!==''?$_SESSION['username']:'admin';}
function ek_select2($rows,$id,$cb){$out=array();foreach($rows as $r)$out[]=array('id'=>$r->$id,'text'=>$cb($r));header('Content-Type: application/json; charset=utf-8');echo json_encode(array('results'=>$out));exit;}
function ek_no($empNo=''){global $db;$prefix='EKPI-'.date('Ym');$r=$db->fetch("SELECT employee_kpi_no FROM erp_employee_kpi WHERE employee_kpi_no LIKE ? ORDER BY employee_kpi_no DESC LIMIT 1",array($prefix.'%'));$n=$r?((int)substr($r->employee_kpi_no,-4)+1):1;return $prefix.sprintf('%04d',$n);}
function ek_filters($src){return array('as_of'=>isset($src['as_of_date'])&&$src['as_of_date']!==''?$src['as_of_date']:date('Y-m-d'),'cycle_year'=>isset($src['cycle_year'])?trim($src['cycle_year']):'','appraisal_period'=>isset($src['appraisal_period'])?trim($src['appraisal_period']):'','employee_id'=>isset($src['employee_id'])?trim($src['employee_id']):'','department_code'=>isset($src['department_code'])?trim($src['department_code']):'','job_title_id'=>isset($src['job_title_id'])?trim($src['job_title_id']):'','kpi_template_id'=>isset($src['kpi_template_id'])?trim($src['kpi_template_id']):'','target_status'=>isset($src['target_status'])?trim($src['target_status']):'','approval_status'=>isset($src['approval_status'])?trim($src['approval_status']):'','weight_status'=>isset($src['weight_status'])?trim($src['weight_status']):'','keyword'=>isset($src['keyword'])?trim($src['keyword']):'');}
function ek_where($f,&$p){$w=" WHERE ek.effective_from<=? AND ek.effective_to>=? ";array_push($p,$f['as_of'],$f['as_of']);foreach(array('cycle_year','appraisal_period','department_code','target_status','approval_status') as $k){if($f[$k]!==''){$w.=" AND ek.$k=? ";$p[]=$f[$k];}}foreach(array('employee_id','job_title_id','kpi_template_id') as $k){if($f[$k]!==''){$w.=" AND ek.$k=? ";$p[]=(int)$f[$k];}}if($f['weight_status']==='COMPLETE')$w.=" AND ROUND(ek.total_weight,2)=100.00 ";elseif($f['weight_status']==='INCOMPLETE')$w.=" AND ROUND(ek.total_weight,2)<>100.00 ";if($f['keyword']!==''){$kw='%'.$f['keyword'].'%';$w.=" AND (ek.employee_kpi_no LIKE ? OR e.employee_no LIKE ? OR e.full_name LIKE ? OR d.nm_dept LIKE ? OR jt.job_title_name LIKE ? OR kt.template_name LIKE ? OR ek.sap_reference LIKE ?) ";for($i=0;$i<7;$i++)$p[]=$kw;}return $w;}
function ek_row($id){global $db;return $db->fetch("SELECT ek.*,e.employee_no,e.full_name,e.employee_group,d.nm_dept,jt.job_title_code,jt.job_title_name,kt.template_no,kt.template_name,ap.employee_no appraiser_no,ap.full_name appraiser_name,hr.employee_no hr_no,hr.full_name hr_name FROM erp_employee_kpi ek JOIN erp_employee_master e ON e.id=ek.employee_id LEFT JOIN dept d ON d.kd_dept=ek.department_code LEFT JOIN erp_job_title jt ON jt.id=ek.job_title_id LEFT JOIN erp_kpi_template kt ON kt.id=ek.kpi_template_id LEFT JOIN erp_employee_master ap ON ap.id=ek.appraiser_employee_id LEFT JOIN erp_employee_master hr ON hr.id=ek.hr_reviewer_employee_id WHERE ek.id=? LIMIT 1",array((int)$id));}
$act=isset($_GET['act'])?$_GET['act']:'';
switch($act){
case 'employee_search':$t=trim(ek_p('term'));$like='%'.$t.'%';$rows=$db->query("SELECT id,employee_no,full_name,department_code,employee_group FROM erp_employee_master WHERE (?='' OR employee_no LIKE ? OR full_name LIKE ? OR department_code LIKE ?) ORDER BY employee_no LIMIT 50",array($t,$like,$like,$like));ek_select2($rows,'id',function($r){return $r->employee_no.' - '.$r->full_name.' ['.$r->department_code.' / '.$r->employee_group.']';});
case 'department_search':$t=trim(ek_p('term'));$like='%'.$t.'%';$rows=$db->query("SELECT kd_dept,nm_dept FROM dept WHERE (?='' OR kd_dept LIKE ? OR nm_dept LIKE ?) ORDER BY kd_dept LIMIT 50",array($t,$like,$like));ek_select2($rows,'kd_dept',function($r){return $r->kd_dept.' - '.$r->nm_dept;});
case 'job_title_search':$t=trim(ek_p('term'));$dept=trim(ek_p('department_code'));$like='%'.$t.'%';$sql="SELECT id,job_title_code,job_title_name,job_level FROM erp_job_title WHERE (?='' OR job_title_code LIKE ? OR job_title_name LIKE ?) ";$p=array($t,$like,$like);if($dept!==''){$sql.=" AND department_code=? ";$p[]=$dept;}$rows=$db->query($sql." ORDER BY job_level DESC,job_title_code LIMIT 50",$p);ek_select2($rows,'id',function($r){return $r->job_title_code.' - '.$r->job_title_name.' ['.$r->job_level.']';});
case 'template_search':$t=trim(ek_p('term'));$like='%'.$t.'%';$rows=$db->query("SELECT id,template_no,template_name,total_weight,status FROM erp_kpi_template WHERE status='ACTIVE' AND (?='' OR template_no LIKE ? OR template_name LIKE ?) ORDER BY template_no LIMIT 50",array($t,$like,$like));ek_select2($rows,'id',function($r){return $r->template_no.' - '.$r->template_name.' ['.number_format((float)$r->total_weight,2).'%]';});
case 'employee_snapshot':
  $r=$db->fetch("SELECT e.id,e.employee_no,e.full_name,e.department_code,e.job_title_id,e.manager_employee_id,d.nm_dept,j.job_title_code,j.job_title_name,m.employee_no manager_no,m.full_name manager_name FROM erp_employee_master e LEFT JOIN dept d ON d.kd_dept=e.department_code LEFT JOIN erp_job_title j ON j.id=e.job_title_id LEFT JOIN erp_employee_master m ON m.id=e.manager_employee_id WHERE e.id=? LIMIT 1",array((int)ek_p('employee_id')));if(!$r)ek_json('error','Employee tidak ditemukan.');ek_json('good','',array('data'=>(array)$r));
case 'template_lines':
  $id=(int)ek_p('kpi_template_id');$r=$db->fetch("SELECT * FROM erp_kpi_template WHERE id=? AND status='ACTIVE' LIMIT 1",array($id));if(!$r)ek_json('error','KPI Template aktif tidak ditemukan.');$rows=$db->query("SELECT * FROM erp_kpi_template_detail WHERE kpi_template_id=? ORDER BY line_no,id",array($id));$lines=array();foreach($rows as $x)$lines[]=(array)$x;ek_json('good','',array('template'=>(array)$r,'lines'=>$lines));
case 'get':
  $r=ek_row((int)ek_p('id'));if(!$r)ek_json('error','Employee KPI tidak ditemukan.');$data=(array)$r;$data['employee_text']=$r->employee_no.' - '.$r->full_name;$data['template_text']=$r->template_no.' - '.$r->template_name;$data['department_text']=$r->department_code?($r->department_code.' - '.$r->nm_dept):'';$data['job_title_text']=$r->job_title_id?($r->job_title_code.' - '.$r->job_title_name):'';$data['appraiser_text']=$r->appraiser_employee_id?($r->appraiser_no.' - '.$r->appraiser_name):'';$data['hr_text']=$r->hr_reviewer_employee_id?($r->hr_no.' - '.$r->hr_name):'';$rows=$db->query("SELECT * FROM erp_employee_kpi_detail WHERE employee_kpi_id=? ORDER BY line_no,id",array((int)$r->id));$lines=array();foreach($rows as $x)$lines[]=(array)$x;ek_json('good','',array('data'=>$data,'lines'=>$lines));
case 'save':
  $id=(int)ek_p('id');$user=ek_user();$employee=(int)ek_p('employee_id');$tpl=(int)ek_p('kpi_template_id');if(!$employee)ek_json('error','Employee wajib dipilih.');if(!$tpl)ek_json('error','KPI Template wajib dipilih.');
  $no=trim(ek_p('employee_kpi_no'))!==''?strtoupper(trim(ek_p('employee_kpi_no'))):ek_no();$dup=$db->fetch("SELECT id FROM erp_employee_kpi WHERE employee_kpi_no=? AND id<>? LIMIT 1",array($no,$id));if($dup)ek_json('error','Employee KPI No sudah digunakan.');
  $codes=isset($_POST['kpi_code'])?$_POST['kpi_code']:array();$lineData=array();$total=0;$line=1;for($i=0;$i<count($codes);$i++){if(trim($codes[$i])==='')continue;$w=(float)$_POST['weight'][$i];if($w<=0)ek_json('error','Weight detail KPI harus lebih dari 0.');$total+=$w;$score=$_POST['score'][$i]!==''?(float)$_POST['score'][$i]:null;$lineData[]=array('template_detail_id'=>$_POST['template_detail_id'][$i]!==''?(int)$_POST['template_detail_id'][$i]:null,'line_no'=>$line++,'kpi_code'=>strtoupper(trim($codes[$i])),'kpi_name'=>trim($_POST['kpi_name'][$i]),'kpi_perspective'=>$_POST['kpi_perspective'][$i],'measure_type'=>$_POST['measure_type'][$i],'target_value'=>$_POST['target_value'][$i]!==''?(float)$_POST['target_value'][$i]:null,'target_text'=>trim($_POST['target_text'][$i]),'unit_of_measure'=>trim($_POST['unit_of_measure'][$i]),'weight'=>$w,'scoring_direction'=>$_POST['scoring_direction'][$i],'minimum_score'=>$_POST['minimum_score'][$i]!==''?(float)$_POST['minimum_score'][$i]:0,'maximum_score'=>$_POST['maximum_score'][$i]!==''?(float)$_POST['maximum_score'][$i]:100,'data_source'=>trim($_POST['data_source'][$i]),'review_frequency'=>$_POST['review_frequency'][$i],'mandatory'=>$_POST['mandatory'][$i],'actual_value'=>$_POST['actual_value'][$i]!==''?(float)$_POST['actual_value'][$i]:null,'actual_text'=>trim($_POST['actual_text'][$i]),'score'=>$score,'weighted_score'=>$score!==null?round(($score*$w)/100,2):null,'remarks'=>trim($_POST['detail_remarks'][$i]));}
  if(!count($lineData))ek_json('error','Minimal satu detail KPI wajib diisi.');
  $data=array('employee_kpi_no'=>$no,'employee_id'=>$employee,'kpi_template_id'=>$tpl,'cycle_year'=>(int)ek_p('cycle_year',date('Y')),'appraisal_period'=>ek_p('appraisal_period','ANNUAL'),'assignment_type'=>ek_p('assignment_type','ANNUAL'),'department_code'=>ek_p('department_code')!==''?ek_p('department_code'):null,'job_title_id'=>ek_p('job_title_id')!==''?(int)ek_p('job_title_id'):null,'appraiser_employee_id'=>ek_p('appraiser_employee_id')!==''?(int)ek_p('appraiser_employee_id'):null,'hr_reviewer_employee_id'=>ek_p('hr_reviewer_employee_id')!==''?(int)ek_p('hr_reviewer_employee_id'):null,'effective_from'=>ek_p('effective_from',date('Y-m-d')),'effective_to'=>ek_p('effective_to','9999-12-31'),'total_weight'=>$total,'target_status'=>ek_p('target_status','DRAFT'),'approval_status'=>ek_p('approval_status','PENDING'),'sap_reference'=>trim(ek_p('sap_reference')),'remarks'=>trim(ek_p('remarks')),'updated_by'=>$user,'updated_at'=>date('Y-m-d H:i:s'));
  if(abs($total-100)>0.01&&$data['target_status']!=='DRAFT')ek_json('error','Employee KPI selain DRAFT harus memiliki total weight 100%.');if($data['approval_status']==='APPROVED'&&ek_p('approved_by')===''){$data['approved_by']=$user;$data['approved_at']=date('Y-m-d H:i:s');}
  if($id>0){$ok=$db->update('erp_employee_kpi',$data,'id',$id);}else{$data['created_by']=$user;$ok=$db->insert('erp_employee_kpi',$data);$id=(int)$db->last_insert_id();}
  if(!$ok)ek_json('error',$db->getErrorMessage()?:'Employee KPI gagal disimpan.');$db->delete('erp_employee_kpi_detail','employee_kpi_id',$id);foreach($lineData as $l){$l['employee_kpi_id']=$id;$db->insert('erp_employee_kpi_detail',$l);}if(function_exists('simpan_log'))simpan_log('User '.$user.' menyimpan Employee KPI '.$no.' pada '.date('Y-m-d H:i:s'),$user);ek_json('good','Employee KPI berhasil disimpan.',array('id'=>$id,'total_weight'=>$total));
case 'delete':$id=(int)ek_p('id');$r=ek_row($id);if(!$r)ek_json('error','Employee KPI tidak ditemukan.');$db->delete('erp_employee_kpi_detail','employee_kpi_id',$id);$db->delete('erp_employee_kpi','id',$id);if($db->getErrorMessage())ek_json('error',$db->getErrorMessage());ek_json('good','Employee KPI berhasil dihapus.');
case 'detail':
  $r=ek_row((int)ek_p('id'));if(!$r){echo '<div class="alert alert-warning">Employee KPI tidak ditemukan.</div>';break;}$lines=$db->query("SELECT * FROM erp_employee_kpi_detail WHERE employee_kpi_id=? ORDER BY line_no,id",array((int)$r->id));echo '<div class="ek-detail"><h3 style="margin-top:0">'.ek_h($r->employee_kpi_no).' <small>'.ek_h($r->employee_no.' - '.$r->full_name).'</small></h3><span class="label label-primary">'.ek_h($r->target_status).'</span> <span class="label label-success">'.ek_h($r->approval_status).'</span><hr><div class="row"><div class="col-sm-3"><b>Template</b><br>'.ek_h($r->template_no.' - '.$r->template_name).'</div><div class="col-sm-3"><b>Org</b><br>'.ek_h($r->department_code.' - '.$r->nm_dept).'<br>'.ek_h($r->job_title_code.' - '.$r->job_title_name).'</div><div class="col-sm-3"><b>Cycle</b><br>'.ek_h($r->cycle_year.' / '.$r->appraisal_period).'</div><div class="col-sm-3"><b>Total Weight</b><br><b>'.number_format((float)$r->total_weight,2).'%</b></div></div><hr><table class="table table-bordered table-condensed"><thead><tr><th>'.hr_h('common_no', 'No').'</th><th>KPI</th><th>Perspective</th><th>Target</th><th>Weight</th><th>Actual</th><th>'.hr_h('hr_score', 'Score').'</th><th>Weighted</th></tr></thead><tbody>';foreach($lines as $l){echo '<tr><td>'.(int)$l->line_no.'</td><td><b>'.ek_h($l->kpi_code).'</b><br><small>'.ek_h($l->kpi_name).'</small></td><td>'.ek_h($l->kpi_perspective).'<br><small>'.ek_h($l->measure_type).'</small></td><td>'.ek_h(($l->target_text?:$l->target_value).' '.($l->unit_of_measure?:'')).'</td><td class="text-right">'.number_format((float)$l->weight,2).'%</td><td>'.ek_h(($l->actual_text?:$l->actual_value?:'-')).'</td><td class="text-right">'.($l->score!==null?number_format((float)$l->score,2):'-').'</td><td class="text-right">'.($l->weighted_score!==null?number_format((float)$l->weighted_score,2):'-').'</td></tr>';}echo '</tbody></table><p><b>SAP Ref:</b> '.ek_h($r->sap_reference?:'-').'<br><b>Remarks:</b> '.ek_h($r->remarks?:'-').'</p></div>';break;
case 'export':
  $initial=ob_get_level();ob_start();error_reporting(E_ALL & ~E_NOTICE & ~E_WARNING & ~E_DEPRECATED & ~E_USER_DEPRECATED);require_once "../../inc/lib/PHPExcel.php";require_once "../../inc/excel_style_helper.php";PHPExcel_Shared_File::setUseUploadTempDirectory(true);$f=ek_filters($_GET);$p=array();$w=ek_where($f,$p);
  $rows=$db->query("SELECT ek.*,e.employee_no,e.full_name,d.nm_dept,jt.job_title_code,jt.job_title_name,kt.template_no,kt.template_name,det.line_no,det.kpi_code,det.kpi_name,det.kpi_perspective,det.target_text,det.target_value,det.unit_of_measure,det.weight,det.actual_value,det.actual_text,det.score,det.weighted_score FROM erp_employee_kpi ek JOIN erp_employee_master e ON e.id=ek.employee_id LEFT JOIN dept d ON d.kd_dept=ek.department_code LEFT JOIN erp_job_title jt ON jt.id=ek.job_title_id LEFT JOIN erp_kpi_template kt ON kt.id=ek.kpi_template_id LEFT JOIN erp_employee_kpi_detail det ON det.employee_kpi_id=ek.id $w ORDER BY ek.employee_kpi_no,det.line_no",$p);
  $excel=new PHPExcel();$sheet=$excel->setActiveSheetIndex(0);$sheet->setTitle(erp_export_sheet_title('Employee KPI'));$heads=array(erp_export_label("No"),erp_export_label("Employee KPI No"),erp_export_label("Employee"),erp_export_label("Department"),erp_export_label("Job Title"),erp_export_label("Template"),erp_export_label("Cycle Year"),erp_export_label("Period"),erp_export_label("Assignment Type"),erp_export_label("Valid From"),erp_export_label("Valid To"),erp_export_label("Total Weight"),erp_export_label("Target Status"),erp_export_label("Approval Status"),erp_export_label("Line"),erp_export_label("KPI Code"),erp_export_label("KPI Name"),erp_export_label("Perspective"),erp_export_label("Target"),erp_export_label("UoM"),erp_export_label("Weight"),erp_export_label("Actual"),erp_export_label("Score"),erp_export_label("Weighted Score"),erp_export_label("SAP Ref"),erp_export_label("Updated By"));foreach($heads as $i=>$h)$sheet->setCellValue(PHPExcel_Cell::stringFromColumnIndex($i).'4',$h);$rn=5;$n=1;foreach($rows as $r){$vals=array($n++,$r->employee_kpi_no,$r->employee_no.' - '.$r->full_name,$r->department_code.' - '.$r->nm_dept,$r->job_title_code.' - '.$r->job_title_name,$r->template_no.' - '.$r->template_name,$r->cycle_year,$r->appraisal_period,$r->assignment_type,$r->effective_from,$r->effective_to,$r->total_weight,$r->target_status,$r->approval_status,$r->line_no,$r->kpi_code,$r->kpi_name,$r->kpi_perspective,$r->target_text?:$r->target_value,$r->unit_of_measure,$r->weight,$r->actual_text?:$r->actual_value,$r->score,$r->weighted_score,$r->sap_reference,$r->updated_by?:$r->created_by);foreach($vals as $i=>$v)$sheet->setCellValue(PHPExcel_Cell::stringFromColumnIndex($i).$rn,$v);$rn++;}
  erpkb_excel_apply_standard_style($excel,array('sheet'=>$sheet,'title'=>erp_export_title('EMPLOYEE KPI REPORT'),'header_row'=>4,'first_data_row'=>5,'last_data_row'=>max(5,$rn-1),'column_count'=>count($heads),'numeric_columns'=>array('L','O','U','W','X'),'filters'=>array('As Of'=>$f['as_of'],'Year'=>$f['cycle_year']?:erp_export_all_text(),'Period'=>$f['appraisal_period']?:erp_export_all_text(),'Status'=>$f['target_status']?:erp_export_all_text()),'widths'=>array('B'=>20,'C'=>28,'D'=>26,'E'=>28,'F'=>32,'P'=>18,'Q'=>30,'Y'=>24,'Z'=>18)));
  $tmp=erpkb_excel_temp_file('employee_kpi_');PHPExcel_IOFactory::createWriter($excel,'Excel2007')->save($tmp);$size=@filesize($tmp);$sig=@file_get_contents($tmp,false,null,0,2);if(!$size||$sig!=='PK'){@unlink($tmp);while(ob_get_level()>$initial)ob_end_clean();echo erp_t('export_excel_invalid_file','File Excel gagal dibuat dengan benar.');exit;}while(ob_get_level()>$initial)ob_end_clean();header('Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');header('Content-Disposition: attachment; filename="employee_kpi_'.date('Ymd_His').'.xlsx"');header('Content-Length: '.$size);header('Cache-Control: max-age=0');header('Pragma: public');readfile($tmp);@unlink($tmp);exit;
default:ek_json('error','Action tidak dikenal.');
}
?>
