<?php
if (!function_exists('hr_t')) {
  function hr_t($key, $fallback = '') { return lang_text($key, $fallback); }
}
if (!function_exists('hr_h')) {
  function hr_h($key, $fallback = '') { return htmlspecialchars((string) hr_t($key, $fallback), ENT_QUOTES, 'UTF-8'); }
}
if (!function_exists('hr_js')) {
  function hr_js($key, $fallback = '') { return json_encode(hr_t($key, $fallback), JSON_HEX_TAG | JSON_HEX_APOS | JSON_HEX_AMP | JSON_HEX_QUOT); }
}
$defaultAsOf=date('Y-m-d');$yearNow=(int)date('Y');$canInsert=isset($role_act['insert_act'])&&$role_act['insert_act']==='Y';$canUpdate=isset($role_act['update_act'])&&$role_act['update_act']==='Y';$canDelete=isset($role_act['delete_act'])&&$role_act['delete_act']==='Y'; ?>
<style>
.ek-hero{background:linear-gradient(135deg,#581c87,#0f766e);color:#fff;border-radius:14px;padding:22px;margin-bottom:16px;box-shadow:0 10px 24px rgba(88,28,135,.18)}.ek-hero h1{margin:0 0 6px;font-size:27px;font-weight:700}.ek-hero p{margin:0;color:#f3e8ff}.ek-card{border-radius:12px;background:#fff;border:1px solid #e5edf5;box-shadow:0 5px 16px rgba(15,23,42,.05);margin-bottom:14px}.ek-kpi{padding:14px;border-radius:12px;background:#f8fafc;border:1px solid #dbeafe;min-height:76px}.ek-kpi span{display:block;color:#64748b;font-size:12px}.ek-kpi b{font-size:21px;color:#0f172a}.ek-kpi.good{background:#ecfdf5;border-color:#bbf7d0}.ek-kpi.warn{background:#fff7ed;border-color:#fed7aa}#dtb_employee_kpi th,#dtb_employee_kpi td{font-size:12px;vertical-align:middle}.select2-container{width:100%!important}.ek-action{white-space:nowrap}.required-label:after{content:' *';color:#dd4b39}.ek-detail{background:#fff;border:1px solid #e5e7eb;border-radius:12px;padding:18px}#modal_ek .modal-body,#modal_ek_detail .modal-body{max-height:calc(100vh - 180px);overflow-y:auto}.ek-line-table th,.ek-line-table td{font-size:12px;vertical-align:middle}.ek-line-table input,.ek-line-table select{min-width:105px}.ek-line-table .wide{min-width:180px}.ek-total-ok{color:#16a34a;font-weight:700}.ek-total-bad{color:#dc2626;font-weight:700}
</style>
<section class="content-header"><h1><?=hr_h('hr_employee_kpi', 'Employee KPI');?> <small>SAP HCM Performance Management</small></h1><ol class="breadcrumb"><li><a href="<?=base_index();?>"><i class="fa fa-dashboard"></i> <?=hr_h('common_home', 'Home');?></a></li><li>Human Resource</li><li>Performance Management</li><li class="active"><?=hr_h('hr_employee_kpi', 'Employee KPI');?></li></ol></section>
<section class="content">
<div class="ek-hero"><div class="row"><div class="col-md-8"><h1>Employee KPI Assignment</h1><p>Assign KPI template ke employee per cycle, simpan target individual, approval status, acknowledgement, dan detail bobot KPI untuk appraisal.</p></div><div class="col-md-4 text-right"><?php if($canInsert){ ?><button id="btn_open_ek" class="btn btn-warning"><i class="fa fa-plus"></i> Assign KPI</button><?php } ?> <button id="btn_export_ek" class="btn btn-success"><i class="fa fa-file-excel-o"></i> <?=hr_h('common_export_excel', 'Export Excel');?></button></div></div></div>
<div class="row"><div class="col-sm-2"><div class="ek-kpi"><span>Total Assignment</span><b id="kpi_total">0</b></div></div><div class="col-sm-2"><div class="ek-kpi"><span>Employees</span><b id="kpi_employees">0</b></div></div><div class="col-sm-2"><div class="ek-kpi good"><span>Assigned</span><b id="kpi_assigned">0</b></div></div><div class="col-sm-2"><div class="ek-kpi"><span>Acknowledged</span><b id="kpi_ack">0</b></div></div><div class="col-sm-2"><div class="ek-kpi good"><span>Completed</span><b id="kpi_completed">0</b></div></div><div class="col-sm-2"><div class="ek-kpi warn"><span>Weight 100%</span><b id="kpi_weight">0</b></div></div></div>
<div class="box ek-card"><div class="box-header"><h3 class="box-title"><i class="fa fa-filter"></i> Filter Employee KPI</h3></div><div class="box-body"><form class="form-horizontal" onsubmit="return false;">
<div class="form-group"><label class="control-label col-lg-2">As Of Date</label><div class="col-lg-2"><div class="input-group date ek-date"><input id="filter_as_of_date" class="form-control" value="<?=$defaultAsOf;?>"><span class="input-group-addon"><span class="glyphicon glyphicon-calendar"></span></span></div></div><label class="control-label col-lg-1">Year</label><div class="col-lg-1"><select id="filter_cycle_year" class="form-control"><option value="">All</option><?php for($y=$yearNow-2;$y<=$yearNow+1;$y++){ ?><option value="<?=$y;?>" <?=$y===$yearNow?'selected':'';?>><?=$y;?></option><?php } ?></select></div><label class="control-label col-lg-1"><?=hr_h('hr_period', 'Period');?></label><div class="col-lg-2"><select id="filter_appraisal_period" class="form-control"><option value="">All</option><option>Q1</option><option>Q2</option><option>Q3</option><option>Q4</option><option>H1</option><option>H2</option><option>ANNUAL</option><option>PROBATION</option><option>SPECIAL</option></select></div><label class="control-label col-lg-1"><?=hr_h('common_status', 'Status');?></label><div class="col-lg-2"><select id="filter_target_status" class="form-control"><option value="">All</option><option>DRAFT</option><option>ASSIGNED</option><option>ACKNOWLEDGED</option><option>IN_REVIEW</option><option>COMPLETED</option><option>CANCELLED</option></select></div></div>
<div class="form-group"><label class="control-label col-lg-2"><?=hr_h('hr_employee', 'Employee');?></label><div class="col-lg-3"><select id="filter_employee_id" class="form-control"></select></div><label class="control-label col-lg-1"><?=hr_h('hr_department', 'Department');?></label><div class="col-lg-3"><select id="filter_department_code" class="form-control"></select></div><label class="control-label col-lg-1"><?=hr_h('hr_job_title', 'Job Title');?></label><div class="col-lg-2"><select id="filter_job_title_id" class="form-control"></select></div></div>
<div class="form-group"><label class="control-label col-lg-2">Template</label><div class="col-lg-3"><select id="filter_kpi_template_id" class="form-control"></select></div><label class="control-label col-lg-1">Approval</label><div class="col-lg-2"><select id="filter_approval_status" class="form-control"><option value="">All</option><option>NOT_REQUIRED</option><option>PENDING</option><option>APPROVED</option><option>REJECTED</option><option>RETURNED</option></select></div><label class="control-label col-lg-1">Weight</label><div class="col-lg-2"><select id="filter_weight_status" class="form-control"><option value="">All</option><option value="COMPLETE">Complete 100%</option><option value="INCOMPLETE">Not 100%</option></select></div></div>
<div class="form-group"><label class="control-label col-lg-2">Keyword</label><div class="col-lg-6"><input id="filter_keyword" class="form-control" placeholder="No, employee, department, job title, template, SAP ref"></div><div class="col-lg-4"><button id="btn_filter_ek" class="btn btn-primary"><i class="fa fa-filter"></i> <?=hr_h('common_filter', 'Filter');?></button> <button id="btn_reset_ek" class="btn btn-default"><i class="fa fa-refresh"></i> <?=hr_h('common_reset', 'Reset');?></button></div></div>
</form></div></div>
<div class="box ek-card"><div class="box-body"><div class="alert alert-warning error_data_delete" style="display:none"><button type="button" class="close hide_alert_notif">&times;</button><span class="isi_warning_delete"></span></div><div class="table-responsive"><table id="dtb_employee_kpi" class="table table-bordered table-striped" style="width:100%"><thead><tr><th><?=hr_h('common_no', 'No');?></th><th><?=hr_h('common_action', 'Action');?></th><th><?=hr_h('hr_employee_kpi', 'Employee KPI');?></th><th><?=hr_h('hr_employee', 'Employee');?></th><th>Organization</th><th>Template</th><th>Cycle</th><th>Weight</th><th>Items</th><th>Target Status</th><th>Approval</th><th>Updated</th></tr></thead><tbody></tbody></table></div></div></div>
<div id="modal_ek" class="modal fade"><div class="modal-dialog modal-lg" style="width:96%"><div class="modal-content"><form id="form_ek"><input type="hidden" name="id" id="ek_id"><div class="modal-header"><button class="close" data-dismiss="modal">&times;</button><h4 class="modal-title">Assign Employee KPI</h4></div><div class="modal-body">
<div class="alert alert-info"><strong>SAP hint:</strong> Pilih employee dan KPI template aktif, lalu klik Generate From Template untuk menyalin item KPI ke target individual.</div>
<div class="row"><div class="col-md-2 form-group"><label>Employee KPI No</label><input name="employee_kpi_no" id="employee_kpi_no" class="form-control" placeholder="Auto"></div><div class="col-md-4 form-group"><label class="required-label"><?=hr_h('hr_employee', 'Employee');?></label><select name="employee_id" id="employee_id" class="form-control"></select></div><div class="col-md-4 form-group"><label class="required-label"><?=hr_h('hr_kpi_template', 'KPI Template');?></label><select name="kpi_template_id" id="kpi_template_id" class="form-control"></select></div><div class="col-md-2 form-group"><label>Year</label><input name="cycle_year" id="cycle_year" class="form-control" value="<?=$yearNow;?>"></div></div>
<div class="row"><div class="col-md-2 form-group"><label><?=hr_h('hr_period', 'Period');?></label><select name="appraisal_period" id="appraisal_period" class="form-control"><option>ANNUAL</option><option>H1</option><option>H2</option><option>Q1</option><option>Q2</option><option>Q3</option><option>Q4</option><option>PROBATION</option><option>SPECIAL</option></select></div><div class="col-md-2 form-group"><label>Type</label><select name="assignment_type" id="assignment_type" class="form-control"><option>ANNUAL</option><option>MID_YEAR</option><option>PROBATION</option><option>PROJECT</option><option>SPECIAL</option></select></div><div class="col-md-3 form-group"><label><?=hr_h('hr_department', 'Department');?></label><select name="department_code" id="department_code" class="form-control"></select></div><div class="col-md-3 form-group"><label><?=hr_h('hr_job_title', 'Job Title');?></label><select name="job_title_id" id="job_title_id" class="form-control"></select></div><div class="col-md-2 form-group"><label><br></label><button type="button" id="btn_generate_lines" class="btn btn-success btn-block"><i class="fa fa-magic"></i> Generate</button></div></div>
<div class="row"><div class="col-md-3 form-group"><label>Appraiser</label><select name="appraiser_employee_id" id="appraiser_employee_id" class="form-control"></select></div><div class="col-md-3 form-group"><label>HR Reviewer</label><select name="hr_reviewer_employee_id" id="hr_reviewer_employee_id" class="form-control"></select></div><div class="col-md-2 form-group"><label>Effective From</label><input name="effective_from" id="effective_from" class="form-control ek-date-field" value="<?=date('Y-m-d');?>"></div><div class="col-md-2 form-group"><label>Effective To</label><input name="effective_to" id="effective_to" class="form-control ek-date-field" value="9999-12-31"></div><div class="col-md-2 form-group"><label>Target Status</label><select name="target_status" id="target_status" class="form-control"><option>DRAFT</option><option>ASSIGNED</option><option>ACKNOWLEDGED</option><option>IN_REVIEW</option><option>COMPLETED</option><option>CANCELLED</option></select></div></div>
<div class="row"><div class="col-md-2 form-group"><label>Approval</label><select name="approval_status" id="approval_status" class="form-control"><option>PENDING</option><option>NOT_REQUIRED</option><option>APPROVED</option><option>REJECTED</option><option>RETURNED</option></select></div><div class="col-md-4 form-group"><label>SAP Reference</label><input name="sap_reference" id="sap_reference" class="form-control"></div><div class="col-md-6 form-group"><label><?=hr_h('common_remarks', 'Remarks');?></label><input name="remarks" id="remarks" class="form-control"></div></div>
<h4>KPI Items <small>Total Weight: <span id="ek_total_weight" class="ek-total-bad">0.00%</span></small></h4><div class="table-responsive"><table class="table table-bordered ek-line-table"><thead><tr><th><?=hr_h('common_no', 'No');?></th><th>KPI Code</th><th>KPI Name</th><th>Perspective</th><th>Target</th><th>UoM</th><th>Weight</th><th>Actual</th><th><?=hr_h('hr_score', 'Score');?></th><th>Source</th><th>Freq</th><th></th></tr></thead><tbody id="ek_lines"></tbody></table></div>
</div><div class="modal-footer"><button type="button" class="btn btn-default" data-dismiss="modal"><?=hr_h('common_cancel', 'Cancel');?></button><button type="submit" class="btn btn-primary"><i class="fa fa-save"></i> Save Employee KPI</button></div></form></div></div></div>
<div id="modal_ek_detail" class="modal fade"><div class="modal-dialog modal-lg" style="width:94%"><div class="modal-content"><div class="modal-header"><button class="close" data-dismiss="modal">&times;</button><h4 class="modal-title">Employee KPI Detail</h4></div><div class="modal-body" id="ek_detail_body"></div><div class="modal-footer"><button class="btn btn-default" data-dismiss="modal"><?=hr_h('common_close', 'Close');?></button></div></div></div></div>
</section>
<script src="<?=base_admin();?>assets/plugins/select2/select2.min.js"></script><script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
<script>
var ekCanUpdate='<?=$canUpdate?'Y':'N';?>',ekCanDelete='<?=$canDelete?'Y':'N';?>';
function ekError(m){$('.isi_warning_delete').text(m||'Employee KPI gagal diproses.');$('.error_data_delete').fadeIn();}
function ekFilters(){return{as_of_date:$('#filter_as_of_date').val(),cycle_year:$('#filter_cycle_year').val(),appraisal_period:$('#filter_appraisal_period').val(),employee_id:$('#filter_employee_id').val(),department_code:$('#filter_department_code').val(),job_title_id:$('#filter_job_title_id').val(),kpi_template_id:$('#filter_kpi_template_id').val(),target_status:$('#filter_target_status').val(),approval_status:$('#filter_approval_status').val(),weight_status:$('#filter_weight_status').val(),keyword:$('#filter_keyword').val()};}
function ekAjax(s,act,p,parent){$(s).select2({width:'100%',allowClear:true,placeholder:p,dropdownParent:parent||$(document.body),ajax:{url:'<?=base_admin();?>modul/employee_kpi/employee_kpi_action.php?act='+act,type:'POST',dataType:'json',delay:250,data:function(q){return{term:q.term||'',department_code:$('#department_code').val()||$('#filter_department_code').val()||''};},processResults:function(d){return{results:d.results||[]};}}});}
function ekSet(sel,val,text){var e=$(sel);if(!val){e.val(null).trigger('change');return;}if(!e.find('option[value="'+val+'"]').length)e.append(new Option(text||val,val,true,true));e.val(val).trigger('change');}
function ekLine(l){l=l||{};var n=$('#ek_lines tr').length+1;return '<tr><td class="line-no">'+n+'</td><td><input name="template_detail_id[]" type="hidden" value="'+(l.template_detail_id||l.id||'')+'"><input name="kpi_code[]" class="form-control" value="'+(l.kpi_code||'')+'"><input name="measure_type[]" type="hidden" value="'+(l.measure_type||'QUANTITATIVE')+'"><input name="scoring_direction[]" type="hidden" value="'+(l.scoring_direction||'HIGHER_BETTER')+'"><input name="minimum_score[]" type="hidden" value="'+(l.minimum_score||'0')+'"><input name="maximum_score[]" type="hidden" value="'+(l.maximum_score||'100')+'"><input name="mandatory[]" type="hidden" value="'+(l.mandatory||'Y')+'"></td><td><input name="kpi_name[]" class="form-control wide" value="'+(l.kpi_name||'')+'"></td><td><select name="kpi_perspective[]" class="form-control"><option '+((l.kpi_perspective||'')=='PROCESS'?'selected':'')+'>PROCESS</option><option '+((l.kpi_perspective||'')=='QUALITY'?'selected':'')+'>QUALITY</option><option '+((l.kpi_perspective||'')=='SAFETY'?'selected':'')+'>SAFETY</option><option '+((l.kpi_perspective||'')=='PEOPLE'?'selected':'')+'>PEOPLE</option><option '+((l.kpi_perspective||'')=='COMPLIANCE'?'selected':'')+'>COMPLIANCE</option><option '+((l.kpi_perspective||'')=='FINANCIAL'?'selected':'')+'>FINANCIAL</option><option '+((l.kpi_perspective||'')=='CUSTOMER'?'selected':'')+'>CUSTOMER</option><option '+((l.kpi_perspective||'')=='INNOVATION'?'selected':'')+'>INNOVATION</option></select></td><td><input name="target_value[]" type="hidden" value="'+(l.target_value||'')+'"><input name="target_text[]" class="form-control wide" value="'+(l.target_text||'')+'"></td><td><input name="unit_of_measure[]" class="form-control" value="'+(l.unit_of_measure||'')+'"></td><td><input name="weight[]" type="number" step="0.01" class="form-control ek-weight" value="'+(l.weight||'0')+'"></td><td><input name="actual_value[]" type="number" step="0.0001" class="form-control" value="'+(l.actual_value||'')+'"><input name="actual_text[]" class="form-control" value="'+(l.actual_text||'')+'" placeholder="Text"></td><td><input name="score[]" type="number" step="0.01" class="form-control" value="'+(l.score||'')+'"></td><td><input name="data_source[]" class="form-control wide" value="'+(l.data_source||'')+'"></td><td><input name="review_frequency[]" class="form-control" value="'+(l.review_frequency||'MONTHLY')+'"><input name="detail_remarks[]" type="hidden" value="'+(l.remarks||'')+'"></td><td><button type="button" class="btn btn-danger btn-xs btn-remove-line"><i class="fa fa-trash"></i></button></td></tr>';}
function ekRenumber(){var total=0;$('#ek_lines tr').each(function(i){$(this).find('.line-no').text(i+1);total+=parseFloat($(this).find('.ek-weight').val()||0)||0;});$('#ek_total_weight').text(total.toFixed(2)+'%').toggleClass('ek-total-ok',Math.abs(total-100)<.01).toggleClass('ek-total-bad',Math.abs(total-100)>=.01);}
function ekReset(){$('#form_ek')[0].reset();$('#ek_id,#employee_kpi_no').val('');$('#cycle_year').val('<?=$yearNow;?>');$('#appraisal_period').val('ANNUAL').trigger('change');$('#assignment_type').val('ANNUAL').trigger('change');$('#target_status').val('DRAFT').trigger('change');$('#approval_status').val('PENDING').trigger('change');$('#employee_id,#kpi_template_id,#department_code,#job_title_id,#appraiser_employee_id,#hr_reviewer_employee_id').val(null).trigger('change');$('#effective_from').val('<?=date('Y-m-d');?>');$('#effective_to').val('9999-12-31');$('#ek_lines').empty();ekRenumber();$('#modal_ek .modal-title').text('Assign Employee KPI');}
$(function(){
 if($.fn.datepicker){$('.ek-date,.ek-date-field').datepicker({format:'yyyy-mm-dd',autoclose:true,todayHighlight:true});}
 if($.fn.select2){$('#filter_cycle_year,#filter_appraisal_period,#filter_target_status,#filter_approval_status,#filter_weight_status,#appraisal_period,#assignment_type,#target_status,#approval_status').select2({width:'100%',allowClear:true});ekAjax('#filter_employee_id','employee_search','Semua Employee');ekAjax('#filter_department_code','department_search','Semua Department');ekAjax('#filter_job_title_id','job_title_search','Semua Job Title');ekAjax('#filter_kpi_template_id','template_search','Semua Template');ekAjax('#employee_id','employee_search','Pilih Employee',$('#modal_ek'));ekAjax('#kpi_template_id','template_search','Pilih KPI Template',$('#modal_ek'));ekAjax('#department_code','department_search','Pilih Department',$('#modal_ek'));ekAjax('#job_title_id','job_title_search','Pilih Job Title',$('#modal_ek'));ekAjax('#appraiser_employee_id','employee_search','Pilih Appraiser',$('#modal_ek'));ekAjax('#hr_reviewer_employee_id','employee_search','Pilih HR Reviewer',$('#modal_ek'));}
 var dt=$('#dtb_employee_kpi').DataTable({bProcessing:true,bServerSide:true,pageLength:25,dom:"<'row'<'col-sm-12'B>>"+"<'row'<'col-sm-6'l><'col-sm-6'f>>"+"<'row'<'col-sm-12'tr>>"+"<'row'<'col-sm-5'i><'col-sm-7'p>>",buttons:[{extend:'collection',text:<?=hr_js('common_export_data', 'Export Data');?>,buttons:['copyHtml5','excelHtml5','csvHtml5']}],columnDefs:[{targets:[0,1],orderable:false,searchable:false},{width:'42px',targets:0},{width:'115px',targets:1}],ajax:{url:'<?=base_admin();?>modul/employee_kpi/employee_kpi_data.php',type:'post',data:function(d){$.extend(d,ekFilters());},dataSrc:function(j){var k=j.kpi||{};$('#kpi_total').text(k.total||0);$('#kpi_employees').text(k.employees||0);$('#kpi_assigned').text(k.assigned||0);$('#kpi_ack').text(k.acknowledged||0);$('#kpi_completed').text(k.completed||0);$('#kpi_weight').text(k.complete_weight||0);return j.data||[];},error:function(x){console.log(x.responseText);ekError('Data Employee KPI gagal dimuat.');}}});
 $('#btn_open_ek').click(function(){ekReset();$('#modal_ek').modal({backdrop:'static',keyboard:false});});$('#btn_filter_ek').click(function(){dt.draw();});$('#filter_keyword').keyup(function(e){if(e.keyCode===13)dt.draw();});$('#btn_reset_ek').click(function(){$('#filter_as_of_date').val('<?=$defaultAsOf;?>');$('#filter_cycle_year').val('<?=$yearNow;?>').trigger('change');$('#filter_appraisal_period,#filter_employee_id,#filter_department_code,#filter_job_title_id,#filter_kpi_template_id,#filter_target_status,#filter_approval_status,#filter_weight_status').val(null).trigger('change');$('#filter_keyword').val('');dt.draw();});$('#btn_export_ek').click(function(){window.location='<?=base_admin();?>modul/employee_kpi/employee_kpi_action.php?act=export&'+$.param(ekFilters());});$('.hide_alert_notif').click(function(){$('.error_data_delete').hide();});
 $('#employee_id').on('change',function(){var id=$(this).val();if(!id)return;$.post('<?=base_admin();?>modul/employee_kpi/employee_kpi_action.php?act=employee_snapshot',{employee_id:id},function(r){if(r.status!=='good')return;var d=r.data;ekSet('#department_code',d.department_code,d.department_code+' - '+(d.nm_dept||''));ekSet('#job_title_id',d.job_title_id,(d.job_title_code||'')+' - '+(d.job_title_name||''));ekSet('#appraiser_employee_id',d.manager_employee_id,d.manager_no?d.manager_no+' - '+d.manager_name:'');},'json');});
 $('#btn_generate_lines').click(function(){var id=$('#kpi_template_id').val();if(!id){ekError('KPI Template wajib dipilih.');return;}$.post('<?=base_admin();?>modul/employee_kpi/employee_kpi_action.php?act=template_lines',{kpi_template_id:id},function(r){if(r.status!=='good'){ekError(r.error_message);return;}$('#ek_lines').empty();(r.lines||[]).forEach(function(l){$('#ek_lines').append(ekLine(l));});ekRenumber();},'json');});
 $(document).on('keyup change','.ek-weight',ekRenumber);$(document).on('click','.btn-remove-line',function(){$(this).closest('tr').remove();ekRenumber();});
 $('#form_ek').submit(function(e){e.preventDefault();var btn=$(this).find('button[type=submit]');btn.prop('disabled',true).html('<i class="fa fa-spinner fa-spin"></i> <?=hr_h('common_saving', 'Saving...');?>');$.post('<?=base_admin();?>modul/employee_kpi/employee_kpi_action.php?act=save',$(this).serialize(),function(r){btn.prop('disabled',false).html('<i class="fa fa-save"></i> Save Employee KPI');if(r.status==='good'){$('#modal_ek').modal('hide');dt.draw(false);Swal.fire('Saved','Employee KPI tersimpan. Total weight '+r.total_weight+'%','success');}else ekError(r.error_message);},'json').fail(function(x){btn.prop('disabled',false).html('<i class="fa fa-save"></i> Save Employee KPI');ekError(x.responseText);});});
 $(document).on('click','.btn-ek-detail',function(){$.post('<?=base_admin();?>modul/employee_kpi/employee_kpi_action.php?act=detail',{id:$(this).data('id')},function(h){$('#ek_detail_body').html(h);$('#modal_ek_detail').modal('show');});});
 $(document).on('click','.btn-ek-edit',function(){if(ekCanUpdate!=='Y')return;ekReset();$.post('<?=base_admin();?>modul/employee_kpi/employee_kpi_action.php?act=get',{id:$(this).data('id')},function(r){if(r.status!=='good'){ekError(r.error_message);return;}var d=r.data;Object.keys(d).forEach(function(k){var e=$('#'+k);if(e.length&&!['employee_id','kpi_template_id','department_code','job_title_id','appraiser_employee_id','hr_reviewer_employee_id'].includes(k))e.val(d[k]);});$('#ek_id').val(d.id);ekSet('#employee_id',d.employee_id,d.employee_text);ekSet('#kpi_template_id',d.kpi_template_id,d.template_text);ekSet('#department_code',d.department_code,d.department_text);ekSet('#job_title_id',d.job_title_id,d.job_title_text);ekSet('#appraiser_employee_id',d.appraiser_employee_id,d.appraiser_text);ekSet('#hr_reviewer_employee_id',d.hr_reviewer_employee_id,d.hr_text);$('#appraisal_period,#assignment_type,#target_status,#approval_status').trigger('change');$('#ek_lines').empty();(r.lines||[]).forEach(function(l){$('#ek_lines').append(ekLine(l));});ekRenumber();$('#modal_ek .modal-title').text('Edit Employee KPI');$('#modal_ek').modal({backdrop:'static',keyboard:false});},'json');});
 $(document).on('click','.btn-ek-delete',function(){if(ekCanDelete!=='Y')return;var id=$(this).data('id'),no=$(this).data('no');Swal.fire({title:erpLang('confirm_delete_title','Delete Confirmation'),text:no,icon:'warning',showCancelButton:true,confirmButtonText:erpLang('common_delete','Delete'),cancelButtonText:erpLang('common_cancel','Cancel')}).then(function(x){if(!x.isConfirmed)return;$.post('<?=base_admin();?>modul/employee_kpi/employee_kpi_action.php?act=delete',{id:id},function(r){if(r.status==='good'){dt.draw(false);Swal.fire(erpLang('common_deleted','Deleted'),erpLang('common_deleted_message','Data deleted successfully.'),'success');}else ekError(r.error_message);},'json');});});
});
</script>
