<?php
if (!function_exists('hr_t')) {
  function hr_t($key, $fallback = '') { return lang_text($key, $fallback); }
}
if (!function_exists('hr_h')) {
  function hr_h($key, $fallback = '') { return htmlspecialchars((string) hr_t($key, $fallback), ENT_QUOTES, 'UTF-8'); }
}
if (!function_exists('hr_js')) {
  function hr_js($key, $fallback = '') { return json_encode(hr_t($key, $fallback), JSON_HEX_TAG | JSON_HEX_APOS | JSON_HEX_AMP | JSON_HEX_QUOT); }
}
if (session_status() === PHP_SESSION_NONE) session_start();
include "../../inc/config.php";
session_check_json();
function ekd_h($v){return htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');}
function ekd_label($s){$m=array('DRAFT'=>'default','ASSIGNED'=>'info','ACKNOWLEDGED'=>'primary','IN_REVIEW'=>'warning','COMPLETED'=>'success','CANCELLED'=>'danger','PENDING'=>'warning','APPROVED'=>'success','REJECTED'=>'danger','RETURNED'=>'warning','NOT_REQUIRED'=>'default');$c=isset($m[$s])?$m[$s]:'default';return '<span class="label label-'.$c.'">'.ekd_h($s?:'-').'</span>';}
function ekd_filters(){return array('as_of'=>isset($_POST['as_of_date'])&&$_POST['as_of_date']!==''?$_POST['as_of_date']:date('Y-m-d'),'cycle_year'=>isset($_POST['cycle_year'])?trim($_POST['cycle_year']):'','appraisal_period'=>isset($_POST['appraisal_period'])?trim($_POST['appraisal_period']):'','employee_id'=>isset($_POST['employee_id'])?trim($_POST['employee_id']):'','department_code'=>isset($_POST['department_code'])?trim($_POST['department_code']):'','job_title_id'=>isset($_POST['job_title_id'])?trim($_POST['job_title_id']):'','kpi_template_id'=>isset($_POST['kpi_template_id'])?trim($_POST['kpi_template_id']):'','target_status'=>isset($_POST['target_status'])?trim($_POST['target_status']):'','approval_status'=>isset($_POST['approval_status'])?trim($_POST['approval_status']):'','weight_status'=>isset($_POST['weight_status'])?trim($_POST['weight_status']):'','keyword'=>isset($_POST['keyword'])?trim($_POST['keyword']):'');}
function ekd_where($f,&$p){$w=" WHERE ek.effective_from<=? AND ek.effective_to>=? ";array_push($p,$f['as_of'],$f['as_of']);foreach(array('cycle_year','appraisal_period','department_code','target_status','approval_status') as $k){if($f[$k]!==''){$w.=" AND ek.$k=? ";$p[]=$f[$k];}}foreach(array('employee_id','job_title_id','kpi_template_id') as $k){if($f[$k]!==''){$w.=" AND ek.$k=? ";$p[]=(int)$f[$k];}}if($f['weight_status']==='COMPLETE')$w.=" AND ROUND(ek.total_weight,2)=100.00 ";elseif($f['weight_status']==='INCOMPLETE')$w.=" AND ROUND(ek.total_weight,2)<>100.00 ";if($f['keyword']!==''){$kw='%'.$f['keyword'].'%';$w.=" AND (ek.employee_kpi_no LIKE ? OR e.employee_no LIKE ? OR e.full_name LIKE ? OR d.nm_dept LIKE ? OR jt.job_title_name LIKE ? OR kt.template_name LIKE ? OR ek.sap_reference LIKE ?) ";for($i=0;$i<7;$i++)$p[]=$kw;}return $w;}
$draw=isset($_POST['draw'])?(int)$_POST['draw']:1;$start=isset($_POST['start'])?max(0,(int)$_POST['start']):0;$length=isset($_POST['length'])?(int)$_POST['length']:25;if($length<=0||$length>500)$length=25;
$f=ekd_filters();$p=array();$w=ekd_where($f,$p);
$base=" FROM erp_employee_kpi ek JOIN erp_employee_master e ON e.id=ek.employee_id LEFT JOIN dept d ON d.kd_dept=ek.department_code LEFT JOIN erp_job_title jt ON jt.id=ek.job_title_id LEFT JOIN erp_kpi_template kt ON kt.id=ek.kpi_template_id LEFT JOIN erp_employee_master ap ON ap.id=ek.appraiser_employee_id LEFT JOIN erp_employee_master hr ON hr.id=ek.hr_reviewer_employee_id ";
$kpi=$db->fetch("SELECT COUNT(*) total,COUNT(DISTINCT ek.employee_id) employees,SUM(ek.target_status='ASSIGNED') assigned,SUM(ek.target_status='ACKNOWLEDGED') acknowledged,SUM(ek.target_status='COMPLETED') completed,SUM(ROUND(ek.total_weight,2)=100.00) complete_weight $base $w",$p);
$cnt=$db->fetch("SELECT COUNT(*) jml $base $w",$p);$total=$cnt?(int)$cnt->jml:0;
$orderMap=array(2=>'ek.employee_kpi_no',3=>'e.employee_no',4=>'d.kd_dept',5=>'kt.template_no',6=>'ek.cycle_year',7=>'ek.total_weight',8=>'line_count',9=>'ek.target_status',10=>'ek.approval_status',11=>'ek.updated_at');$orderBy='ek.updated_at DESC,ek.id DESC';
if(isset($_POST['order'][0]['column'])){$col=(int)$_POST['order'][0]['column'];$dir=(isset($_POST['order'][0]['dir'])&&strtolower($_POST['order'][0]['dir'])==='desc')?'DESC':'ASC';if(isset($orderMap[$col]))$orderBy=$orderMap[$col].' '.$dir;}
$rows=$db->query("SELECT ek.*,e.employee_no,e.full_name,e.employee_group,d.nm_dept,jt.job_title_code,jt.job_title_name,kt.template_no,kt.template_name,ap.employee_no appraiser_no,ap.full_name appraiser_name,hr.employee_no hr_no,(SELECT COUNT(*) FROM erp_employee_kpi_detail x WHERE x.employee_kpi_id=ek.id) line_count $base $w ORDER BY $orderBy LIMIT $start,$length",$p);
$data=array();$no=$start+1;foreach($rows as $r){$act='<div class="ek-action"><button class="btn btn-info btn-xs btn-ek-detail" data-id="'.(int)$r->id.'"><i class="fa fa-eye"></i></button> <button class="btn btn-primary btn-xs btn-ek-edit" data-id="'.(int)$r->id.'"><i class="fa fa-pencil"></i></button> <button class="btn btn-danger btn-xs btn-ek-delete" data-id="'.(int)$r->id.'" data-no="'.ekd_h($r->employee_kpi_no).'"><i class="fa fa-trash"></i></button></div>';$weight=(float)$r->total_weight;$weightLabel=$weight==100.0?'success':'warning';
  $data[]=array($no++,$act,'<strong>'.ekd_h($r->employee_kpi_no).'</strong><br><small>'.ekd_h($r->sap_reference?:'-').'</small>','<strong>'.ekd_h($r->employee_no).'</strong><br><small>'.ekd_h($r->full_name).' / '.ekd_h($r->employee_group).'</small>','<strong>'.ekd_h($r->department_code?:'-').'</strong><br><small>'.ekd_h($r->nm_dept?:'-').'</small><br><small>'.ekd_h($r->job_title_code?:'-').' '.ekd_h($r->job_title_name?:'').'</small>','<strong>'.ekd_h($r->template_no).'</strong><br><small>'.ekd_h($r->template_name).'</small>',ekd_h($r->cycle_year.' / '.$r->appraisal_period).'<br><small>'.ekd_h($r->assignment_type).'</small>','<span class="label label-'.$weightLabel.'">'.number_format($weight,2).'%</span>','<span class="badge bg-blue">'.(int)$r->line_count.'</span>',ekd_label($r->target_status).'<br><small>'.ekd_h($r->effective_from.' s/d '.$r->effective_to).'</small>',ekd_label($r->approval_status).'<br><small>'.ekd_h($r->approved_by?:'-').'</small>',ekd_h($r->updated_by?:$r->created_by?:'-').'<br><small>'.ekd_h($r->updated_at?:$r->created_at).'</small>');
}
header('Content-Type: application/json; charset=utf-8');echo json_encode(array('draw'=>$draw,'recordsTotal'=>$total,'recordsFiltered'=>$total,'data'=>$data,'kpi'=>array('total'=>$kpi?(int)$kpi->total:0,'employees'=>$kpi?(int)$kpi->employees:0,'assigned'=>$kpi?(int)$kpi->assigned:0,'acknowledged'=>$kpi?(int)$kpi->acknowledged:0,'completed'=>$kpi?(int)$kpi->completed:0,'complete_weight'=>$kpi?(int)$kpi->complete_weight:0)));
?>
