CREATE TABLE IF NOT EXISTS erp_employee_mutation (
  id int(11) NOT NULL AUTO_INCREMENT,
  mutation_no varchar(30) NOT NULL,
  mutation_date date NOT NULL,
  effective_date date NOT NULL,
  employee_id int(11) NOT NULL,
  mutation_type enum('TRANSFER','PROMOTION','DEMOTION','JOB_CHANGE','DEPARTMENT_CHANGE','COST_CENTER_CHANGE','STATUS_CHANGE','PAYROLL_CHANGE') NOT NULL DEFAULT 'TRANSFER',
  reason_code varchar(50) DEFAULT NULL,
  reason_text varchar(255) DEFAULT NULL,
  old_department_code char(8) DEFAULT NULL,
  new_department_code char(8) DEFAULT NULL,
  old_job_title_id int(11) DEFAULT NULL,
  new_job_title_id int(11) DEFAULT NULL,
  old_company_structure_id int(11) DEFAULT NULL,
  new_company_structure_id int(11) DEFAULT NULL,
  old_manager_employee_id int(11) DEFAULT NULL,
  new_manager_employee_id int(11) DEFAULT NULL,
  old_cost_center_code varchar(20) DEFAULT NULL,
  new_cost_center_code varchar(20) DEFAULT NULL,
  old_profit_center_code varchar(20) DEFAULT NULL,
  new_profit_center_code varchar(20) DEFAULT NULL,
  old_employee_group varchar(30) DEFAULT NULL,
  new_employee_group varchar(30) DEFAULT NULL,
  old_employee_subgroup varchar(50) DEFAULT NULL,
  new_employee_subgroup varchar(50) DEFAULT NULL,
  old_payroll_area varchar(30) DEFAULT NULL,
  new_payroll_area varchar(30) DEFAULT NULL,
  old_pay_grade varchar(30) DEFAULT NULL,
  new_pay_grade varchar(30) DEFAULT NULL,
  old_work_location_type varchar(30) DEFAULT NULL,
  new_work_location_type varchar(30) DEFAULT NULL,
  old_shift_code varchar(30) DEFAULT NULL,
  new_shift_code varchar(30) DEFAULT NULL,
  approval_status enum('DRAFT','SUBMITTED','APPROVED','REJECTED','POSTED','CANCELLED') NOT NULL DEFAULT 'DRAFT',
  approved_by varchar(50) DEFAULT NULL,
  approved_at datetime DEFAULT NULL,
  posted_by varchar(50) DEFAULT NULL,
  posted_at datetime DEFAULT NULL,
  remarks text DEFAULT NULL,
  created_by varchar(50) DEFAULT NULL,
  created_at datetime NOT NULL DEFAULT current_timestamp(),
  updated_by varchar(50) DEFAULT NULL,
  updated_at datetime DEFAULT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uk_mutation_no (mutation_no),
  KEY idx_mutation_employee (employee_id),
  KEY idx_mutation_date (mutation_date,effective_date),
  KEY idx_mutation_type (mutation_type),
  KEY idx_mutation_status (approval_status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

UPDATE sys_menu
   SET nav_act='employee_mutation', main_table='erp_employee_mutation', icon='fa-exchange', dt_table='Y', tampil='Y'
 WHERE url='employee-mutation';
