CREATE TABLE IF NOT EXISTS erp_routing (
  id int(11) NOT NULL AUTO_INCREMENT,
  routing_no varchar(30) NOT NULL,
  material_code varchar(100) NOT NULL,
  material_name varchar(255) DEFAULT NULL,
  plant_id int(11) DEFAULT NULL,
  plant_code varchar(20) DEFAULT NULL,
  routing_usage varchar(30) DEFAULT 'PRODUCTION',
  alternative_routing varchar(10) DEFAULT '01',
  valid_from date NOT NULL,
  valid_to date DEFAULT NULL,
  base_qty decimal(18,5) DEFAULT 1.00000,
  base_uom varchar(30) DEFAULT NULL,
  routing_status varchar(20) DEFAULT 'DRAFT',
  revision varchar(30) DEFAULT NULL,
  change_number varchar(50) DEFAULT NULL,
  lot_size_from decimal(18,5) DEFAULT NULL,
  lot_size_to decimal(18,5) DEFAULT NULL,
  remarks text DEFAULT NULL,
  created_by varchar(100) DEFAULT NULL,
  created_at datetime DEFAULT CURRENT_TIMESTAMP,
  updated_by varchar(100) DEFAULT NULL,
  updated_at datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  released_by varchar(100) DEFAULT NULL,
  released_at datetime DEFAULT NULL,
  cancel_reason varchar(255) DEFAULT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uk_erp_routing_no (routing_no),
  KEY idx_routing_material_plant_status (material_code,plant_code,routing_usage,routing_status,valid_from,valid_to)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS erp_routing_operation (
  id int(11) NOT NULL AUTO_INCREMENT,
  routing_id int(11) NOT NULL,
  operation_no varchar(20) NOT NULL,
  operation_name varchar(150) NOT NULL,
  work_center_id int(11) DEFAULT NULL,
  work_center_code varchar(100) NOT NULL,
  work_center_name varchar(150) DEFAULT NULL,
  control_key varchar(20) DEFAULT 'PP01',
  standard_text varchar(255) DEFAULT NULL,
  setup_time decimal(18,5) DEFAULT 0.00000,
  machine_time decimal(18,5) DEFAULT 0.00000,
  labor_time decimal(18,5) DEFAULT 0.00000,
  queue_time decimal(18,5) DEFAULT 0.00000,
  move_time decimal(18,5) DEFAULT 0.00000,
  time_uom varchar(20) DEFAULT 'MIN',
  capacity_category varchar(30) DEFAULT 'MACHINE',
  base_qty decimal(18,5) DEFAULT 1.00000,
  yield_percent decimal(9,4) DEFAULT 100.0000,
  scrap_percent decimal(9,4) DEFAULT 0.0000,
  backflush enum('Y','N') DEFAULT 'N',
  quality_check enum('Y','N') DEFAULT 'N',
  milestone enum('Y','N') DEFAULT 'N',
  remarks varchar(255) DEFAULT NULL,
  operation_status varchar(20) DEFAULT 'ACTIVE',
  PRIMARY KEY (id),
  KEY idx_routing_operation_header (routing_id,operation_no),
  CONSTRAINT fk_erp_routing_operation_header FOREIGN KEY (routing_id) REFERENCES erp_routing(id) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

UPDATE sys_menu
SET nav_act='routing',
    main_table='erp_routing',
    page_name='Routing',
    icon='fa-random',
    tampil='Y',
    type_menu='page'
WHERE url='routing';
