START TRANSACTION;

DELETE FROM erp_employee_document
 WHERE document_no IN ('DOC-2026-0001','DOC-2026-0002','DOC-2026-0003','DOC-2026-0004','DOC-2026-0005','DOC-2026-0006','DOC-2026-0007','DOC-2026-0008','DOC-2026-0009','DOC-2026-0010','DOC-2026-0011','DOC-2026-0012');

INSERT INTO erp_employee_document (document_no,employee_id,document_type,document_category,document_title,document_number,issue_date,expiry_date,issuing_authority,issuing_country,file_ref,file_name,file_type,confidential,mandatory_document,renewal_required,verification_status,verified_by_employee_id,verified_at,effective_from,effective_to,status,sap_reference,remarks,created_by,updated_by,updated_at)
SELECT 'DOC-2026-0001',e.id,'KTP','PERSONAL','KTP Deden Firdaus','3171-800101-0001','2020-01-01',NULL,'Dukcapil','ID','employee_documents/DOC-2026-0001.pdf','ktp_deden.pdf','PDF','Y','Y','N','VERIFIED',v.id,'2026-01-02 09:00:00','2026-01-01','9999-12-31','ACTIVE','SAP-DOC-0001','Dokumen identitas karyawan.', 'Tinna','Tinna',NOW() FROM erp_employee_master e LEFT JOIN erp_employee_master v ON v.employee_no='EMP-0003' WHERE e.employee_no='EMP-0001';
INSERT INTO erp_employee_document (document_no,employee_id,document_type,document_category,document_title,document_number,issue_date,expiry_date,issuing_authority,issuing_country,file_ref,file_name,file_type,confidential,mandatory_document,renewal_required,verification_status,verified_by_employee_id,verified_at,effective_from,effective_to,status,sap_reference,remarks,created_by,updated_by,updated_at)
SELECT 'DOC-2026-0002',e.id,'NPWP','PAYROLL_TAX','NPWP Nadia Putri','09.123.456.7-001.000','2019-03-15',NULL,'DJP','ID','employee_documents/DOC-2026-0002.pdf','npwp_nadia.pdf','PDF','Y','Y','N','VERIFIED',v.id,'2026-01-02 10:00:00','2026-01-01','9999-12-31','ACTIVE','SAP-DOC-0002','Dokumen pajak payroll.', 'Nadia','Nadia',NOW() FROM erp_employee_master e LEFT JOIN erp_employee_master v ON v.employee_no='EMP-0003' WHERE e.employee_no='EMP-0002';
INSERT INTO erp_employee_document (document_no,employee_id,document_type,document_category,document_title,document_number,issue_date,expiry_date,issuing_authority,issuing_country,file_ref,file_name,file_type,confidential,mandatory_document,renewal_required,verification_status,verified_by_employee_id,verified_at,effective_from,effective_to,status,sap_reference,remarks,created_by,updated_by,updated_at)
SELECT 'DOC-2026-0003',e.id,'IJAZAH','EMPLOYMENT','Ijazah S1 Tinna Sari','UNJ-PSI-2013-003','2013-08-30',NULL,'Universitas Negeri Jakarta','ID','employee_documents/DOC-2026-0003.pdf','ijazah_tinna.pdf','PDF','Y','Y','N','VERIFIED',v.id,'2026-01-03 09:00:00','2026-01-01','9999-12-31','ACTIVE','SAP-DOC-0003','Ijazah pendidikan formal.', 'Tinna','Tinna',NOW() FROM erp_employee_master e LEFT JOIN erp_employee_master v ON v.employee_no='EMP-0001' WHERE e.employee_no='EMP-0003';
INSERT INTO erp_employee_document (document_no,employee_id,document_type,document_category,document_title,document_number,issue_date,expiry_date,issuing_authority,issuing_country,file_ref,file_name,file_type,confidential,mandatory_document,renewal_required,verification_status,verified_by_employee_id,verified_at,effective_from,effective_to,status,sap_reference,remarks,created_by,updated_by,updated_at)
SELECT 'DOC-2026-0004',e.id,'KONTRAK','EMPLOYMENT','PKWT Agus Santoso','CTR-2026-0004','2026-02-01','2027-01-31','HR Department','ID','employee_documents/DOC-2026-0004.pdf','pkwt_agus.pdf','PDF','Y','Y','Y','VERIFIED',v.id,'2026-02-01 08:00:00','2026-02-01','2027-01-31','ACTIVE','SAP-DOC-0004','Dokumen kontrak kerja.', 'IGPRD','IGPRD',NOW() FROM erp_employee_master e LEFT JOIN erp_employee_master v ON v.employee_no='EMP-0003' WHERE e.employee_no='EMP-0004';
INSERT INTO erp_employee_document (document_no,employee_id,document_type,document_category,document_title,document_number,issue_date,expiry_date,issuing_authority,issuing_country,file_ref,file_name,file_type,confidential,mandatory_document,renewal_required,verification_status,verified_by_employee_id,verified_at,effective_from,effective_to,status,sap_reference,remarks,created_by,updated_by,updated_at)
SELECT 'DOC-2026-0005',e.id,'BPJS_TK','BENEFIT','BPJS Ketenagakerjaan Budi Hartono','BPJSTK-0005','2026-03-01',NULL,'BPJS Ketenagakerjaan','ID','employee_documents/DOC-2026-0005.pdf','bpjstk_budi.pdf','PDF','Y','Y','N','VERIFIED',v.id,'2026-03-02 10:00:00','2026-03-01','9999-12-31','ACTIVE','SAP-DOC-0005','Dokumen benefit BPJS TK.', 'IGWH_IN','IGWH_IN',NOW() FROM erp_employee_master e LEFT JOIN erp_employee_master v ON v.employee_no='EMP-0003' WHERE e.employee_no='EMP-0005';
INSERT INTO erp_employee_document (document_no,employee_id,document_type,document_category,document_title,document_number,issue_date,expiry_date,issuing_authority,issuing_country,file_ref,file_name,file_type,confidential,mandatory_document,renewal_required,verification_status,verified_by_employee_id,verified_at,effective_from,effective_to,status,sap_reference,remarks,created_by,updated_by,updated_at)
SELECT 'DOC-2026-0006',e.id,'SERTIFIKAT','TRAINING','Sertifikat QC Inspector','BNSP-QC-2025-006','2025-12-01','2028-12-01','BNSP','ID','employee_documents/DOC-2026-0006.pdf','sertifikat_qc_siti.pdf','PDF','N','N','Y','PENDING',NULL,NULL,'2026-01-01','9999-12-31','ACTIVE','SAP-DOC-0006','Sertifikat menunggu verifikasi.', 'Nadia','Nadia',NOW() FROM erp_employee_master e WHERE e.employee_no='EMP-0006';
INSERT INTO erp_employee_document (document_no,employee_id,document_type,document_category,document_title,document_number,issue_date,expiry_date,issuing_authority,issuing_country,file_ref,file_name,file_type,confidential,mandatory_document,renewal_required,verification_status,verified_by_employee_id,verified_at,effective_from,effective_to,status,sap_reference,remarks,created_by,updated_by,updated_at)
SELECT 'DOC-2026-0007',e.id,'KTP','PERSONAL','KTP Rizky Pratama','3274-940101-0007','2020-01-01',NULL,'Dukcapil','ID','employee_documents/DOC-2026-0007.pdf','ktp_rizky.pdf','PDF','Y','Y','N','VERIFIED',v.id,'2026-01-05 09:00:00','2026-01-01','9999-12-31','ACTIVE','SAP-DOC-0007','KTP operator mixing.', 'IGPRD','IGPRD',NOW() FROM erp_employee_master e LEFT JOIN erp_employee_master v ON v.employee_no='EMP-0004' WHERE e.employee_no='EMP-0007';
INSERT INTO erp_employee_document (document_no,employee_id,document_type,document_category,document_title,document_number,issue_date,expiry_date,issuing_authority,issuing_country,file_ref,file_name,file_type,confidential,mandatory_document,renewal_required,verification_status,verified_by_employee_id,verified_at,effective_from,effective_to,status,sap_reference,remarks,created_by,updated_by,updated_at)
SELECT 'DOC-2026-0008',e.id,'SIM','LEGAL','SIM Operator Forklift','SIM-B2-0008','2024-06-01','2029-06-01','Polri','ID','employee_documents/DOC-2026-0008.pdf','sim_andi.pdf','PDF','N','N','Y','VERIFIED',v.id,'2026-01-05 10:00:00','2026-01-01','9999-12-31','ACTIVE','SAP-DOC-0008','License operator.', 'IGPRD','IGPRD',NOW() FROM erp_employee_master e LEFT JOIN erp_employee_master v ON v.employee_no='EMP-0004' WHERE e.employee_no='EMP-0008';
INSERT INTO erp_employee_document (document_no,employee_id,document_type,document_category,document_title,document_number,issue_date,expiry_date,issuing_authority,issuing_country,file_ref,file_name,file_type,confidential,mandatory_document,renewal_required,verification_status,verified_by_employee_id,verified_at,effective_from,effective_to,status,sap_reference,remarks,created_by,updated_by,updated_at)
SELECT 'DOC-2026-0009',e.id,'KK','PERSONAL','Kartu Keluarga Dewi Lestari','KK-0009','2021-04-12',NULL,'Dukcapil','ID','employee_documents/DOC-2026-0009.pdf','kk_dewi.pdf','PDF','Y','N','N','VERIFIED',v.id,'2026-01-06 09:00:00','2026-01-01','9999-12-31','ACTIVE','SAP-DOC-0009','Dokumen keluarga.', 'Nadia','Nadia',NOW() FROM erp_employee_master e LEFT JOIN erp_employee_master v ON v.employee_no='EMP-0003' WHERE e.employee_no='EMP-0009';
INSERT INTO erp_employee_document (document_no,employee_id,document_type,document_category,document_title,document_number,issue_date,expiry_date,issuing_authority,issuing_country,file_ref,file_name,file_type,confidential,mandatory_document,renewal_required,verification_status,verified_by_employee_id,verified_at,effective_from,effective_to,status,sap_reference,remarks,created_by,updated_by,updated_at)
SELECT 'DOC-2026-0010',e.id,'APPRAISAL','PERFORMANCE','Appraisal Semester 1','APR-2026-S1-0010','2026-06-15',NULL,'HR Department','ID','employee_documents/DOC-2026-0010.pdf','appraisal_emp10.pdf','PDF','Y','N','N','PENDING',NULL,NULL,'2026-06-15','9999-12-31','ACTIVE','SAP-DOC-0010','Dokumen appraisal menunggu review.', 'Tinna','Tinna',NOW() FROM erp_employee_master e WHERE e.employee_no='EMP-0010';
INSERT INTO erp_employee_document (document_no,employee_id,document_type,document_category,document_title,document_number,issue_date,expiry_date,issuing_authority,issuing_country,file_ref,file_name,file_type,confidential,mandatory_document,renewal_required,verification_status,verified_by_employee_id,verified_at,effective_from,effective_to,status,sap_reference,remarks,created_by,updated_by,updated_at)
SELECT 'DOC-2026-0011',e.id,'PASSPORT','LEGAL','Passport Fajar Nugroho','A1234567','2022-07-01','2027-07-01','Imigrasi','ID','employee_documents/DOC-2026-0011.pdf','passport_fajar.pdf','PDF','Y','N','Y','VERIFIED',v.id,'2026-01-07 09:00:00','2026-01-01','9999-12-31','ACTIVE','SAP-DOC-0011','Dokumen perjalanan.', 'IGWH_IN','IGWH_IN',NOW() FROM erp_employee_master e LEFT JOIN erp_employee_master v ON v.employee_no='EMP-0003' WHERE e.employee_no='EMP-0011';
INSERT INTO erp_employee_document (document_no,employee_id,document_type,document_category,document_title,document_number,issue_date,expiry_date,issuing_authority,issuing_country,file_ref,file_name,file_type,confidential,mandatory_document,renewal_required,verification_status,verified_by_employee_id,verified_at,effective_from,effective_to,status,sap_reference,remarks,created_by,updated_by,updated_at)
SELECT 'DOC-2026-0012',e.id,'WARNING_LETTER','DISCIPLINARY','Surat Peringatan 1','SP1-2025-0012','2025-11-01',NULL,'HR Department','ID','employee_documents/DOC-2026-0012.pdf','sp1_emp12.pdf','PDF','Y','N','N','REJECTED',v.id,'2026-01-08 10:00:00','2025-11-01','9999-12-31','ARCHIVED','SAP-DOC-0012','Contoh dokumen archived/rejected.', 'Tinna','Tinna',NOW() FROM erp_employee_master e LEFT JOIN erp_employee_master v ON v.employee_no='EMP-0003' WHERE e.employee_no='EMP-0012';

COMMIT;
