START TRANSACTION;

DELETE FROM erp_payroll_component
 WHERE component_code IN ('PC-BASIC-001','PC-ALLOW-TRANS','PC-ALLOW-MEAL','PC-OT-REG','PC-BONUS-PROD','PC-DEDUCT-LOAN','PC-BPJS-TK-EMP','PC-BPJS-KES-EMP','PC-TAX-PPH21','PC-INFO-THP');

INSERT INTO erp_payroll_component (component_code,component_name,wage_type_code,component_type,component_category,payroll_area,employee_group,calculation_method,calculation_base,default_amount,percentage_rate,formula_text,currency,taxable,bpjs_base,recurring,prorate,retroactive_allowed,payslip_display,posting_required,debit_credit,gl_account_code,cost_center_code,sequence_no,valid_from,valid_to,component_status,sap_reference,remarks,created_by,updated_by,updated_at) VALUES
('PC-BASIC-001','Basic Salary','1000','EARNING','BASIC_PAY','ALL','ALL','FIXED_AMOUNT','NONE',0,0,NULL,'IDR','Y','Y','Y','Y','Y','Y','Y','DEBIT','PAYROLL-SALARY-EXP','1000-HR',10,'2026-01-01','9999-12-31','ACTIVE','SAP-WT-1000','Gaji pokok sebagai basis payroll, pajak, dan BPJS.','Nadia','Nadia',NOW()),
('PC-ALLOW-TRANS','Transport Allowance','1100','EARNING','ALLOWANCE','MONTHLY','ALL','FIXED_AMOUNT','NONE',500000,0,NULL,'IDR','Y','N','Y','Y','N','Y','Y','DEBIT','PAYROLL-ALLOWANCE-EXP','1000-HR',20,'2026-01-01','9999-12-31','ACTIVE','SAP-WT-1100','Tunjangan transport bulanan.','Tinna','Tinna',NOW()),
('PC-ALLOW-MEAL','Meal Allowance','1110','EARNING','ALLOWANCE','ALL','ALL','ATTENDANCE_BASED','WORKING_DAYS',25000,0,'WORKING_DAYS * 25000','IDR','Y','N','Y','Y','N','Y','Y','DEBIT','PAYROLL-ALLOWANCE-EXP','1000-HR',30,'2026-01-01','9999-12-31','ACTIVE','SAP-WT-1110','Uang makan berdasarkan hari hadir.','Siti Aminah','Siti Aminah',NOW()),
('PC-OT-REG','Regular Overtime','1200','EARNING','OVERTIME','ALL','ALL','OVERTIME_BASED','OVERTIME_HOURS',0,0,'PAYABLE_OT_HOURS * OT_RATE','IDR','Y','N','N','N','Y','Y','Y','DEBIT','PAYROLL-OVERTIME-EXP','1000-PRD',40,'2026-01-01','9999-12-31','ACTIVE','SAP-WT-1200','Komponen lembur dari modul Overtime.','IGPRD','IGPRD',NOW()),
('PC-BONUS-PROD','Production Bonus','1300','EARNING','BONUS','MONTHLY','OPERATOR','FORMULA','GROSS_PAY',0,5.0000,'IF(PRODUCTION_TARGET>=100%, BASIC_SALARY*5%, 0)','IDR','Y','N','N','N','N','Y','Y','DEBIT','PAYROLL-BONUS-EXP','1000-PRD',50,'2026-01-01','9999-12-31','DRAFT','SAP-WT-1300','Bonus produksi berdasarkan pencapaian target.','IGPRD','IGPRD',NOW()),
('PC-DEDUCT-LOAN','Employee Loan Deduction','2100','DEDUCTION','LOAN','ALL','ALL','MANUAL_INPUT','NONE',0,0,NULL,'IDR','N','N','Y','N','Y','Y','Y','CREDIT','PAYROLL-LOAN-REC','1000-FIN',210,'2026-01-01','9999-12-31','ACTIVE','SAP-WT-2100','Potongan cicilan pinjaman karyawan.','Nadia','Nadia',NOW()),
('PC-BPJS-TK-EMP','BPJS TK Employee Contribution','2200','DEDUCTION','SOCIAL_SECURITY','ALL','ALL','PERCENTAGE','BASIC_SALARY',0,2.0000,'BASIC_SALARY * 2%','IDR','N','N','Y','Y','Y','Y','Y','CREDIT','PAYROLL-BPJS-PAYABLE','1000-HR',220,'2026-01-01','9999-12-31','ACTIVE','SAP-WT-2200','Iuran BPJS TK karyawan.','Tinna','Tinna',NOW()),
('PC-BPJS-KES-EMP','BPJS Kesehatan Employee Contribution','2210','DEDUCTION','SOCIAL_SECURITY','ALL','ALL','PERCENTAGE','BASIC_SALARY',0,1.0000,'MIN(BASIC_SALARY, BPJS_CAP) * 1%','IDR','N','N','Y','Y','Y','Y','Y','CREDIT','PAYROLL-BPJS-PAYABLE','1000-HR',230,'2026-01-01','9999-12-31','ACTIVE','SAP-WT-2210','Iuran BPJS Kesehatan karyawan.','Tinna','Tinna',NOW()),
('PC-TAX-PPH21','PPh 21 Withholding','2300','TAX','TAX','ALL','ALL','FORMULA','GROSS_PAY',0,0,'PPH21_PROGRESSIVE(GROSS_TAXABLE)','IDR','N','N','Y','Y','Y','Y','Y','CREDIT','PAYROLL-TAX-PAYABLE','1000-FIN',240,'2026-01-01','9999-12-31','ACTIVE','SAP-WT-2300','Pemotongan PPh 21 payroll.','Nadia','Nadia',NOW()),
('PC-INFO-THP','Take Home Pay Information','9000','INFORMATION','OTHER','ALL','ALL','FORMULA','NET_PAY',0,0,'GROSS_PAY - DEDUCTION - TAX','IDR','N','N','Y','N','N','Y','N','NONE',NULL,NULL,900,'2026-01-01','9999-12-31','ACTIVE','SAP-WT-9000','Komponen informasi THP pada payslip.','Budi Hartono','Budi Hartono',NOW());

COMMIT;
