START TRANSACTION;

DELETE FROM erp_shift_schedule
 WHERE assignment_no IN ('SS-202606-0001','SS-202606-0002','SS-202606-0003','SS-202606-0004','SS-202606-0005','SS-202606-0006','SS-202606-0007','SS-202606-0008');

INSERT INTO erp_shift_schedule (assignment_no,employee_id,employee_no,department_code,work_schedule_id,work_schedule_code,shift_id,shift_code,work_location_id,schedule_from,schedule_to,monday,tuesday,wednesday,thursday,friday,saturday,sunday,planned_start,planned_end,break_minutes,planned_hours_per_day,rotation_group,roster_type,source_type,overtime_eligible,attendance_required,assignment_status,release_by,release_at,sap_reference,remarks,created_by,updated_by,updated_at)
SELECT 'SS-202606-0001',e.id,e.employee_no,e.department_code,ws.id,ws.schedule_code,s.id,s.kode_shift,ws.work_location_id,'2026-06-01','2026-06-30','Y','Y','Y','Y','Y','Y','N',s.jam_mulai,s.jam_selesai,60,8,'PROD-A','ROTATION','WORK_SCHEDULE','Y','Y','RELEASED','IGPRD',NOW(),'SAP-SS-202606-0001','Roster operator mixing shift 1 bulan Juni.', 'IGPRD','IGPRD',NOW()
  FROM erp_employee_master e JOIN erp_shift s ON s.kode_shift='SHIFT-1' JOIN erp_work_schedule ws ON ws.schedule_code='WS-PROD-S1' WHERE e.employee_no='EMP-0007' LIMIT 1;

INSERT INTO erp_shift_schedule (assignment_no,employee_id,employee_no,department_code,work_schedule_id,work_schedule_code,shift_id,shift_code,work_location_id,schedule_from,schedule_to,monday,tuesday,wednesday,thursday,friday,saturday,sunday,planned_start,planned_end,break_minutes,planned_hours_per_day,rotation_group,roster_type,source_type,overtime_eligible,attendance_required,assignment_status,release_by,release_at,sap_reference,remarks,created_by,updated_by,updated_at)
SELECT 'SS-202606-0002',e.id,e.employee_no,e.department_code,ws.id,ws.schedule_code,s.id,s.kode_shift,ws.work_location_id,'2026-06-01','2026-06-30','Y','Y','Y','Y','Y','Y','N',s.jam_mulai,s.jam_selesai,60,8,'PROD-B','ROTATION','WORK_SCHEDULE','Y','Y','RELEASED','IGPRD',NOW(),'SAP-SS-202606-0002','Roster operator coating shift 2 bulan Juni.', 'IGPRD','IGPRD',NOW()
  FROM erp_employee_master e JOIN erp_shift s ON s.kode_shift='SHIFT-2' JOIN erp_work_schedule ws ON ws.schedule_code='WS-PROD-S2' WHERE e.employee_no='EMP-0008' LIMIT 1;

INSERT INTO erp_shift_schedule (assignment_no,employee_id,employee_no,department_code,work_schedule_id,work_schedule_code,shift_id,shift_code,work_location_id,schedule_from,schedule_to,monday,tuesday,wednesday,thursday,friday,saturday,sunday,planned_start,planned_end,break_minutes,planned_hours_per_day,rotation_group,roster_type,source_type,overtime_eligible,attendance_required,assignment_status,release_by,release_at,sap_reference,remarks,created_by,updated_by,updated_at)
SELECT 'SS-202606-0003',e.id,e.employee_no,e.department_code,ws.id,ws.schedule_code,s.id,s.kode_shift,ws.work_location_id,'2026-06-01','2026-06-30','Y','Y','Y','Y','Y','Y','N','07:30:00','16:30:00',60,8,'WH-RM','REGULAR','WORK_SCHEDULE','Y','Y','PLANNED',NULL,NULL,'SAP-SS-202606-0003','Roster warehouse raw material.', 'IGWH_IN','IGWH_IN',NOW()
  FROM erp_employee_master e JOIN erp_shift s ON s.kode_shift='SHIFT-1' JOIN erp_work_schedule ws ON ws.schedule_code='WS-WH-RM' WHERE e.employee_no='EMP-0009' LIMIT 1;

INSERT INTO erp_shift_schedule (assignment_no,employee_id,employee_no,department_code,work_schedule_id,work_schedule_code,shift_id,shift_code,work_location_id,schedule_from,schedule_to,monday,tuesday,wednesday,thursday,friday,saturday,sunday,planned_start,planned_end,break_minutes,planned_hours_per_day,rotation_group,roster_type,source_type,overtime_eligible,attendance_required,assignment_status,release_by,release_at,sap_reference,remarks,created_by,updated_by,updated_at)
SELECT 'SS-202606-0004',e.id,e.employee_no,e.department_code,ws.id,ws.schedule_code,s.id,s.kode_shift,ws.work_location_id,'2026-06-01','2026-06-30','Y','Y','Y','Y','Y','N','N','08:00:00','17:00:00',60,8,'QA-DAY','REGULAR','MANUAL','Y','Y','PLANNED',NULL,NULL,'SAP-SS-202606-0004','Roster staff QA regular day.', 'Siti Aminah','Siti Aminah',NOW()
  FROM erp_employee_master e JOIN erp_shift s ON s.kode_shift='SHIFT-1' JOIN erp_work_schedule ws ON ws.schedule_code='WS-OFFICE-001' WHERE e.employee_no='EMP-0006' LIMIT 1;

INSERT INTO erp_shift_schedule (assignment_no,employee_id,employee_no,department_code,work_schedule_id,work_schedule_code,shift_id,shift_code,work_location_id,schedule_from,schedule_to,monday,tuesday,wednesday,thursday,friday,saturday,sunday,planned_start,planned_end,break_minutes,planned_hours_per_day,rotation_group,roster_type,source_type,overtime_eligible,attendance_required,assignment_status,release_by,release_at,sap_reference,remarks,created_by,updated_by,updated_at)
SELECT 'SS-202606-0005',e.id,e.employee_no,e.department_code,ws.id,ws.schedule_code,s.id,s.kode_shift,ws.work_location_id,'2026-06-01','2026-06-30','Y','Y','Y','Y','Y','N','N','09:00:00','18:00:00',60,8,'SALES-JKT','REGULAR','WORK_SCHEDULE','Y','Y','RELEASED','Nadia',NOW(),'SAP-SS-202606-0005','Roster sales office.', 'Nadia','Nadia',NOW()
  FROM erp_employee_master e JOIN erp_shift s ON s.kode_shift='SHIFT-1' JOIN erp_work_schedule ws ON ws.schedule_code='WS-SALES-001' WHERE e.employee_no='EMP-0010' LIMIT 1;

INSERT INTO erp_shift_schedule (assignment_no,employee_id,employee_no,department_code,work_schedule_id,work_schedule_code,shift_id,shift_code,work_location_id,schedule_from,schedule_to,monday,tuesday,wednesday,thursday,friday,saturday,sunday,planned_start,planned_end,break_minutes,planned_hours_per_day,rotation_group,roster_type,source_type,overtime_eligible,attendance_required,assignment_status,release_by,release_at,sap_reference,remarks,created_by,updated_by,updated_at)
SELECT 'SS-202606-0006',e.id,e.employee_no,e.department_code,ws.id,ws.schedule_code,s.id,s.kode_shift,ws.work_location_id,'2026-06-01','2026-06-30','Y','Y','Y','Y','Y','N','N','08:30:00','17:30:00',60,8,'REMOTE-IT','REGULAR','WORK_SCHEDULE','N','N','PLANNED',NULL,NULL,'SAP-SS-202606-0006','Roster remote IT support.', 'Tinna','Tinna',NOW()
  FROM erp_employee_master e JOIN erp_shift s ON s.kode_shift='SHIFT-1' JOIN erp_work_schedule ws ON ws.schedule_code='WS-REMOTE-001' WHERE e.employee_no='EMP-0003' LIMIT 1;

INSERT INTO erp_shift_schedule (assignment_no,employee_id,employee_no,department_code,work_schedule_id,work_schedule_code,shift_id,shift_code,work_location_id,schedule_from,schedule_to,monday,tuesday,wednesday,thursday,friday,saturday,sunday,planned_start,planned_end,break_minutes,planned_hours_per_day,rotation_group,roster_type,source_type,overtime_eligible,attendance_required,assignment_status,release_by,release_at,sap_reference,remarks,created_by,updated_by,updated_at)
SELECT 'SS-202606-0007',e.id,e.employee_no,e.department_code,ws.id,ws.schedule_code,s.id,s.kode_shift,ws.work_location_id,'2026-06-01','2026-06-30','Y','Y','Y','Y','Y','Y','N',s.jam_mulai,s.jam_selesai,60,8,'MNT-A','REGULAR','MANUAL','Y','Y','DRAFT',NULL,NULL,'SAP-SS-202606-0007','Draft roster maintenance.', 'Budi Hartono','Budi Hartono',NOW()
  FROM erp_employee_master e JOIN erp_shift s ON s.kode_shift='SHIFT-1' JOIN erp_work_schedule ws ON ws.schedule_code='WS-OFFICE-001' WHERE e.employee_no='EMP-0011' LIMIT 1;

INSERT INTO erp_shift_schedule (assignment_no,employee_id,employee_no,department_code,work_schedule_id,work_schedule_code,shift_id,shift_code,work_location_id,schedule_from,schedule_to,monday,tuesday,wednesday,thursday,friday,saturday,sunday,planned_start,planned_end,break_minutes,planned_hours_per_day,rotation_group,roster_type,source_type,overtime_eligible,attendance_required,assignment_status,release_by,release_at,sap_reference,remarks,created_by,updated_by,updated_at)
SELECT 'SS-202606-0008',e.id,e.employee_no,e.department_code,ws.id,ws.schedule_code,s.id,s.kode_shift,ws.work_location_id,'2026-06-01','2026-06-30','Y','Y','Y','Y','Y','N','N','08:00:00','17:00:00',60,8,'FIN-DAY','REGULAR','MANUAL','Y','Y','RELEASED','Nadia',NOW(),'SAP-SS-202606-0008','Roster finance month end support.', 'Nadia','Nadia',NOW()
  FROM erp_employee_master e JOIN erp_shift s ON s.kode_shift='SHIFT-1' JOIN erp_work_schedule ws ON ws.schedule_code='WS-OFFICE-001' WHERE e.employee_no='EMP-0002' LIMIT 1;

COMMIT;
