START TRANSACTION;
DELETE FROM erp_job_title WHERE job_title_code IN ('JT-GM','JT-FIN-MGR','JT-HR-MGR','JT-IT-SPV','JT-PRC-STF','JT-CUS-STF','JT-PRD-MGR','JT-PPIC-SPV','JT-MIX-OPR','JT-COAT-OPR','JT-LAM-OPR','JT-PACK-OPR','JT-WH-MGR','JT-WH-STF','JT-LOG-STF','JT-QA-SPV','JT-QA-INS','JT-MNT-TECH','JT-RND-STF','JT-SLS-MGR','JT-SLS-STF');

INSERT INTO erp_job_title (job_title_code,job_title_name,job_title_short_name,job_family,job_level,employee_group,employee_subgroup,department_code,company_structure_id,reports_to_job_title_id,cost_center_code,profit_center_code,pay_grade,work_location_type,headcount_plan,minimum_education,competency_profile,job_purpose,key_responsibility,authority_limit,valid_from,valid_to,status,sap_reference,remarks,created_by,updated_by,updated_at)
VALUES
('JT-GM','General Manager','GM','EXECUTIVE','L9','DIRECTOR','PERMANENT_MONTHLY','DEP-ADM',(SELECT id FROM erp_company_structure WHERE structure_code='PSA-ADM' LIMIT 1),NULL,'1000-ADM','1000-CORP','DIR','OFFICE',1,'S1','Leadership','Memimpin keseluruhan operasi perusahaan dan memastikan target bisnis tercapai.','Strategi bisnis, governance, review KPI, dan approval lintas fungsi.','Approval strategis dan kebijakan perusahaan.','2026-01-01','9999-12-31','ACTIVE','SAP-JOB-GM','Dummy executive job title.','codex','codex',NOW()),
('JT-FIN-MGR','Finance Manager','Fin Mgr','FINANCE','L7','MANAGER','PERMANENT_MONTHLY','DEP-FIN',(SELECT id FROM erp_company_structure WHERE structure_code='OU-FIN' LIMIT 1),NULL,'1000-FIN','1000-CORP','M03','OFFICE',1,'S1','Finance Accounting','Mengelola accounting, financial reporting, tax, cash bank, dan closing.','Review journal, AP/AR, closing, tax report, budget control.','Approval jurnal, payment proposal, dan financial closing.','2026-01-01','9999-12-31','ACTIVE','SAP-JOB-FIN-MGR','Finance leadership.','codex','codex',NOW()),
('JT-HR-MGR','HR Manager','HR Mgr','HR','L7','MANAGER','PERMANENT_MONTHLY','DEP-HR',(SELECT id FROM erp_company_structure WHERE structure_code='OU-HR' LIMIT 1),NULL,'1000-HR','1000-CORP','M03','OFFICE',1,'S1','HR Operation','Mengelola organization management, employee administration, recruitment, training, dan payroll coordination.','HR policy, manpower planning, employee lifecycle, dan industrial relation.','Approval data HR dan perubahan organisasi.','2026-01-01','9999-12-31','ACTIVE','SAP-JOB-HR-MGR','HR leadership.','codex','codex',NOW()),
('JT-IT-SPV','IT Supervisor','IT Spv','IT','L5','STAFF','PERMANENT_MONTHLY','DEP-IT',(SELECT id FROM erp_company_structure WHERE structure_code='OU-IT' LIMIT 1),NULL,'1000-IT','1000-SERVICE','G07','OFFICE',1,'D1-D3','IT Support','Memastikan ERP, jaringan, user access, dan support berjalan stabil.','User support, access control, backup, incident handling.','Rekomendasi perubahan akses dan konfigurasi aplikasi.','2026-01-01','9999-12-31','ACTIVE','SAP-JOB-IT-SPV','IT supervisor.','codex','codex',NOW()),
('JT-PRC-STF','Purchasing Staff','Purchasing','PROCUREMENT','L3','STAFF','PERMANENT_MONTHLY','DEP-PRC',(SELECT id FROM erp_company_structure WHERE structure_code='OU-PRC' LIMIT 1),NULL,'1000-PRC','1000-CORP','G05','OFFICE',2,'D1-D3','Procurement','Menjalankan PR follow-up, RFQ, PO preparation, dan vendor coordination.','RFQ, comparison, PO admin, delivery follow-up.','Membuat draft PO sesuai approval matrix.','2026-01-01','9999-12-31','ACTIVE','SAP-JOB-PRC-STF','Purchasing staff.','codex','codex',NOW()),
('JT-CUS-STF','Customs Compliance Staff','Customs','ADMINISTRATION','L3','STAFF','PERMANENT_MONTHLY','DEP-CUS',(SELECT id FROM erp_company_structure WHERE structure_code='OU-CUS' LIMIT 1),NULL,'1000-CUS','1000-CUSTOMS','G05','OFFICE',2,'D1-D3','Customs Compliance','Mengelola dokumen BC dan kepatuhan kawasan berikat.','Input dokumen BC, monitoring CEISA, rekonsiliasi dokumen pabean.','Mengusulkan koreksi dokumen pabean.','2026-01-01','9999-12-31','ACTIVE','SAP-JOB-CUS-STF','Customs staff.','codex','codex',NOW()),
('JT-PRD-MGR','Production Manager','Prod Mgr','PRODUCTION','L7','MANAGER','PERMANENT_MONTHLY','DEP-PRD',(SELECT id FROM erp_company_structure WHERE structure_code='OU-PROD' LIMIT 1),NULL,'1000-PRD','1000-MFG','M03','PLANT',1,'S1','Production Operation','Mengelola produksi, output, efficiency, scrap, dan shop floor execution.','Release execution plan, control WIP, review confirmation, koordinasi quality.','Approval produksi dan penggunaan sumber daya produksi.','2026-01-01','9999-12-31','ACTIVE','SAP-JOB-PRD-MGR','Production leadership.','codex','codex',NOW()),
('JT-PPIC-SPV','PPIC Supervisor','PPIC Spv','SUPERVISOR','L5','STAFF','PERMANENT_MONTHLY','DEP-PRD',(SELECT id FROM erp_company_structure WHERE structure_code='OU-PPIC' LIMIT 1),NULL,'1000-PRD','1000-MFG','G07','OFFICE',1,'S1','Production Operation','Mengatur forecast, MRP, material requirement, dan production schedule.','MRP run, material availability, schedule monitoring.','Mengusulkan production order dan material staging.','2026-01-01','9999-12-31','ACTIVE','SAP-JOB-PPIC-SPV','PPIC supervisor.','codex','codex',NOW()),
('JT-MIX-OPR','Mixing Operator','Mix Op','OPERATOR','L2','OPERATOR','PERMANENT_DAILY','DEP-0001',(SELECT id FROM erp_company_structure WHERE structure_code='OU-MIX' LIMIT 1),NULL,'1000-MIX','1000-PROD-A','G02','PLANT',8,'SMA/SMK','Production Operation','Menjalankan proses mixing sesuai production order dan formula.','Setup material, proses mixing, catat hasil dan scrap.','Mengoperasikan mesin sesuai WI.','2026-01-01','9999-12-31','ACTIVE','SAP-JOB-MIX-OPR','Operator mixing.','codex','codex',NOW()),
('JT-COAT-OPR','Coating Operator','Coat Op','OPERATOR','L2','OPERATOR','PERMANENT_DAILY','DEP-0002',(SELECT id FROM erp_company_structure WHERE structure_code='OU-COAT' LIMIT 1),NULL,'1000-COAT','1000-PROD-A','G02','PLANT',8,'SMA/SMK','Production Operation','Menjalankan proses coating sesuai routing dan quality parameter.','Operate coating line, cek parameter, update confirmation.','Mengoperasikan mesin sesuai WI.','2026-01-01','9999-12-31','ACTIVE','SAP-JOB-COAT-OPR','Operator coating.','codex','codex',NOW()),
('JT-LAM-OPR','Laminating Operator','Lam Op','OPERATOR','L2','OPERATOR','PERMANENT_DAILY','DEP-0003',(SELECT id FROM erp_company_structure WHERE structure_code='OU-LAM' LIMIT 1),NULL,'1000-LAM','1000-PROD-B','G02','PLANT',6,'SMA/SMK','Production Operation','Menjalankan proses laminating dan kontrol hasil antara.','Operate laminating, cek WIP, catat yield dan scrap.','Mengoperasikan mesin sesuai WI.','2026-01-01','9999-12-31','ACTIVE','SAP-JOB-LAM-OPR','Operator laminating.','codex','codex',NOW()),
('JT-PACK-OPR','Packing Operator','Pack Op','OPERATOR','L2','OPERATOR','PERMANENT_DAILY','DEP-0005',(SELECT id FROM erp_company_structure WHERE structure_code='OU-PACK' LIMIT 1),NULL,'1000-PACK','1000-MFG','G02','PLANT',10,'SMA/SMK','Production Operation','Melakukan packing FG/SFG sesuai spesifikasi customer.','Packing, labeling, palletizing, dan handover ke warehouse.','Mengoperasikan area packing sesuai WI.','2026-01-01','9999-12-31','ACTIVE','SAP-JOB-PACK-OPR','Operator packing.','codex','codex',NOW()),
('JT-WH-MGR','Warehouse Manager','WH Mgr','WAREHOUSE','L7','MANAGER','PERMANENT_MONTHLY','DEP-WH',(SELECT id FROM erp_company_structure WHERE structure_code='OU-WH' LIMIT 1),NULL,'1000-WH','1000-PLANT01','M03','WAREHOUSE',1,'S1','Warehouse Management','Mengelola warehouse operation, stock accuracy, movement, dan inventory control.','GR, GI, transfer, stock opname, material document, dan traceability.','Approval stock adjustment dan warehouse procedure.','2026-01-01','9999-12-31','ACTIVE','SAP-JOB-WH-MGR','Warehouse leadership.','codex','codex',NOW()),
('JT-WH-STF','Warehouse Staff','WH Staff','WAREHOUSE','L3','STAFF','PERMANENT_MONTHLY','DEP-WH',(SELECT id FROM erp_company_structure WHERE structure_code='OU-WH' LIMIT 1),NULL,'1000-WH','1000-PLANT01','G05','WAREHOUSE',6,'D1-D3','Warehouse Management','Menjalankan receiving, issuing, transfer, dan stock count.','Input material movement, cek batch/lot/BC, stock card.','Posting movement sesuai dokumen approved.','2026-01-01','9999-12-31','ACTIVE','SAP-JOB-WH-STF','Warehouse staff.','codex','codex',NOW()),
('JT-LOG-STF','Logistics Staff','Log Staff','WAREHOUSE','L3','STAFF','PERMANENT_MONTHLY','DEP-LOG',(SELECT id FROM erp_company_structure WHERE structure_code='OU-LOG' LIMIT 1),NULL,'1000-LOG','1000-LOCAL','G05','WAREHOUSE',3,'D1-D3','Sales Distribution','Menyiapkan outbound delivery, packing list, surat jalan, dan shipment.','Picking coordination, packing list, delivery document.','Menyiapkan dokumen kirim sesuai approval.','2026-01-01','9999-12-31','ACTIVE','SAP-JOB-LOG-STF','Logistics staff.','codex','codex',NOW()),
('JT-QA-SPV','QA/QC Supervisor','QA Spv','QUALITY','L5','STAFF','PERMANENT_MONTHLY','DEP-QA',(SELECT id FROM erp_company_structure WHERE structure_code='OU-QA' LIMIT 1),NULL,'1000-QA','1000-MFG','G07','PLANT',1,'S1','Quality Management','Mengelola inspection, usage decision, NCR, dan CAPA.','Review lot inspection, release/block stock, quality report.','Approval usage decision sesuai authority.','2026-01-01','9999-12-31','ACTIVE','SAP-JOB-QA-SPV','QA supervisor.','codex','codex',NOW()),
('JT-QA-INS','Quality Inspector','Inspector','QUALITY','L3','STAFF','PERMANENT_MONTHLY','DEP-QA',(SELECT id FROM erp_company_structure WHERE structure_code='OU-QA' LIMIT 1),NULL,'1000-QA','1000-MFG','G05','PLANT',4,'D1-D3','Quality Management','Melakukan incoming, in-process, dan final inspection.','Record result, sampling, defect note, dan NCR.','Mencatat hasil inspeksi sesuai prosedur.','2026-01-01','9999-12-31','ACTIVE','SAP-JOB-QA-INS','Quality inspector.','codex','codex',NOW()),
('JT-MNT-TECH','Maintenance Technician','Mnt Tech','TECHNICIAN','L3','STAFF','PERMANENT_MONTHLY','DEP-MNT',(SELECT id FROM erp_company_structure WHERE structure_code='OU-MNT' LIMIT 1),NULL,'1000-MNT','1000-SERVICE','G05','PLANT',4,'SMA/SMK','Maintenance Engineering','Menangani preventive dan corrective maintenance.','Maintenance execution, downtime note, spare part request.','Eksekusi work instruction maintenance.','2026-01-01','9999-12-31','ACTIVE','SAP-JOB-MNT-TECH','Maintenance technician.','codex','codex',NOW()),
('JT-RND-STF','R&D Staff','R&D','PROFESSIONAL','L4','STAFF','PERMANENT_MONTHLY','DEP-RND',(SELECT id FROM erp_company_structure WHERE structure_code='OU-RND' LIMIT 1),NULL,'1000-RND','1000-PROD-B','G06','PLANT',2,'S1','Maintenance Engineering','Mengembangkan produk, trial formula, dan sample customer.','Trial plan, formulation, sample evaluation, documentation.','Mengusulkan perubahan formula/BOM trial.','2026-01-01','9999-12-31','ACTIVE','SAP-JOB-RND-STF','R&D staff.','codex','codex',NOW()),
('JT-SLS-MGR','Sales Manager','Sales Mgr','SALES','L7','MANAGER','PERMANENT_MONTHLY','DEP-SLS',(SELECT id FROM erp_company_structure WHERE structure_code='OU-SLS' LIMIT 1),NULL,'1000-SLS','1000-LOCAL','M03','OFFICE',1,'S1','Sales Distribution','Mengelola target sales, quotation, customer relationship, dan order pipeline.','Sales plan, price approval proposal, customer follow-up.','Approval commercial sesuai matrix.','2026-01-01','9999-12-31','ACTIVE','SAP-JOB-SLS-MGR','Sales leadership.','codex','codex',NOW()),
('JT-SLS-STF','Sales Staff','Sales','SALES','L3','STAFF','PERMANENT_MONTHLY','DEP-SLS',(SELECT id FROM erp_company_structure WHERE structure_code='OU-SLS' LIMIT 1),NULL,'1000-SLS','1000-LOCAL','G05','OFFICE',3,'D1-D3','Sales Distribution','Menangani inquiry, quotation, order follow-up, dan customer communication.','Input inquiry, quotation, SO follow-up, delivery coordination.','Menyiapkan dokumen sales sesuai approval.','2026-01-01','9999-12-31','ACTIVE','SAP-JOB-SLS-STF','Sales staff.','codex','codex',NOW());

UPDATE erp_job_title c JOIN erp_job_title p ON p.job_title_code='JT-GM' SET c.reports_to_job_title_id=p.id WHERE c.job_title_code IN ('JT-FIN-MGR','JT-HR-MGR','JT-PRD-MGR','JT-WH-MGR','JT-SLS-MGR');
UPDATE erp_job_title c JOIN erp_job_title p ON p.job_title_code='JT-PRD-MGR' SET c.reports_to_job_title_id=p.id WHERE c.job_title_code IN ('JT-PPIC-SPV','JT-QA-SPV','JT-MIX-OPR','JT-COAT-OPR','JT-LAM-OPR','JT-PACK-OPR','JT-MNT-TECH','JT-RND-STF');
UPDATE erp_job_title c JOIN erp_job_title p ON p.job_title_code='JT-WH-MGR' SET c.reports_to_job_title_id=p.id WHERE c.job_title_code IN ('JT-WH-STF','JT-LOG-STF');
UPDATE erp_job_title c JOIN erp_job_title p ON p.job_title_code='JT-FIN-MGR' SET c.reports_to_job_title_id=p.id WHERE c.job_title_code IN ('JT-PRC-STF','JT-CUS-STF');
UPDATE erp_job_title c JOIN erp_job_title p ON p.job_title_code='JT-QA-SPV' SET c.reports_to_job_title_id=p.id WHERE c.job_title_code='JT-QA-INS';
UPDATE erp_job_title c JOIN erp_job_title p ON p.job_title_code='JT-HR-MGR' SET c.reports_to_job_title_id=p.id WHERE c.job_title_code='JT-IT-SPV';
UPDATE erp_job_title c JOIN erp_job_title p ON p.job_title_code='JT-SLS-MGR' SET c.reports_to_job_title_id=p.id WHERE c.job_title_code='JT-SLS-STF';
COMMIT;
