START TRANSACTION;

DELETE FROM erp_work_schedule
 WHERE schedule_code IN ('WS-OFFICE-001','WS-PROD-S1','WS-PROD-S2','WS-PROD-S3','WS-WH-RM','WS-WH-FG','WS-SALES-001','WS-REMOTE-001');

INSERT INTO erp_work_schedule (schedule_code,schedule_name,schedule_type,schedule_category,calendar_id,calendar_code,default_shift_id,default_shift_code,work_location_id,department_code,employee_group,monday,tuesday,wednesday,thursday,friday,saturday,sunday,planned_start,planned_end,break_minutes,working_hours_per_day,working_hours_per_week,grace_in_minutes,grace_out_minutes,overtime_eligible,attendance_required,valid_from,valid_to,schedule_status,sap_reference,remarks,created_by,updated_by,updated_at)
SELECT 'WS-OFFICE-001','Office Regular Schedule','FIXED','OFFICE',fc.id,fc.calendar_code,s.id,s.kode_shift,wl.id,'DEP-ADM','STAFF','Y','Y','Y','Y','Y','N','N','08:00:00','17:00:00',60,8,40,15,15,'Y','Y','2026-01-01','9999-12-31','ACTIVE','SAP-WS-OFFICE-001','Jadwal office reguler Senin-Jumat.', 'Tinna','Tinna',NOW()
  FROM erp_shift s LEFT JOIN erp_factory_calendar_header fc ON fc.calendar_code='FC-BASE-2026' LEFT JOIN erp_work_location wl ON wl.location_code='WL-HQ-JKT' WHERE s.kode_shift='SHIFT-1' LIMIT 1;

INSERT INTO erp_work_schedule (schedule_code,schedule_name,schedule_type,schedule_category,calendar_id,calendar_code,default_shift_id,default_shift_code,work_location_id,department_code,employee_group,monday,tuesday,wednesday,thursday,friday,saturday,sunday,planned_start,planned_end,break_minutes,working_hours_per_day,working_hours_per_week,grace_in_minutes,grace_out_minutes,overtime_eligible,attendance_required,valid_from,valid_to,schedule_status,sap_reference,remarks,created_by,updated_by,updated_at)
SELECT 'WS-PROD-S1','Production Shift 1','SHIFT','PRODUCTION',fc.id,fc.calendar_code,s.id,s.kode_shift,wl.id,'DEP-PRD','OPERATOR','Y','Y','Y','Y','Y','Y','N',s.jam_mulai,s.jam_selesai,60,8,48,10,10,'Y','Y','2026-01-01','9999-12-31','ACTIVE','SAP-WS-PROD-S1','Jadwal produksi shift 1.', 'IGPRD','IGPRD',NOW()
  FROM erp_shift s LEFT JOIN erp_factory_calendar_header fc ON fc.calendar_code='FC-BASE-2026' LEFT JOIN erp_work_location wl ON wl.location_code='WL-PL01-MFG' WHERE s.kode_shift='SHIFT-1' LIMIT 1;

INSERT INTO erp_work_schedule (schedule_code,schedule_name,schedule_type,schedule_category,calendar_id,calendar_code,default_shift_id,default_shift_code,work_location_id,department_code,employee_group,monday,tuesday,wednesday,thursday,friday,saturday,sunday,planned_start,planned_end,break_minutes,working_hours_per_day,working_hours_per_week,grace_in_minutes,grace_out_minutes,overtime_eligible,attendance_required,valid_from,valid_to,schedule_status,sap_reference,remarks,created_by,updated_by,updated_at)
SELECT 'WS-PROD-S2','Production Shift 2','SHIFT','PRODUCTION',fc.id,fc.calendar_code,s.id,s.kode_shift,wl.id,'DEP-PRD','OPERATOR','Y','Y','Y','Y','Y','Y','N',s.jam_mulai,s.jam_selesai,60,8,48,10,10,'Y','Y','2026-01-01','9999-12-31','ACTIVE','SAP-WS-PROD-S2','Jadwal produksi shift 2.', 'IGPRD','IGPRD',NOW()
  FROM erp_shift s LEFT JOIN erp_factory_calendar_header fc ON fc.calendar_code='FC-BASE-2026' LEFT JOIN erp_work_location wl ON wl.location_code='WL-PL01-MFG' WHERE s.kode_shift='SHIFT-2' LIMIT 1;

INSERT INTO erp_work_schedule (schedule_code,schedule_name,schedule_type,schedule_category,calendar_id,calendar_code,default_shift_id,default_shift_code,work_location_id,department_code,employee_group,monday,tuesday,wednesday,thursday,friday,saturday,sunday,planned_start,planned_end,break_minutes,working_hours_per_day,working_hours_per_week,grace_in_minutes,grace_out_minutes,overtime_eligible,attendance_required,valid_from,valid_to,schedule_status,sap_reference,remarks,created_by,updated_by,updated_at)
SELECT 'WS-PROD-S3','Production Shift 3','SHIFT','PRODUCTION',fc.id,fc.calendar_code,s.id,s.kode_shift,wl.id,'DEP-PRD','OPERATOR','Y','Y','Y','Y','Y','Y','N',s.jam_mulai,s.jam_selesai,60,8,48,10,10,'Y','Y','2026-01-01','9999-12-31','ACTIVE','SAP-WS-PROD-S3','Jadwal produksi shift 3 lintas hari.', 'IGPRD','IGPRD',NOW()
  FROM erp_shift s LEFT JOIN erp_factory_calendar_header fc ON fc.calendar_code='FC-BASE-2026' LEFT JOIN erp_work_location wl ON wl.location_code='WL-PL01-MFG' WHERE s.kode_shift='SHIFT-3' LIMIT 1;

INSERT INTO erp_work_schedule (schedule_code,schedule_name,schedule_type,schedule_category,calendar_id,calendar_code,default_shift_id,default_shift_code,work_location_id,department_code,employee_group,monday,tuesday,wednesday,thursday,friday,saturday,sunday,planned_start,planned_end,break_minutes,working_hours_per_day,working_hours_per_week,grace_in_minutes,grace_out_minutes,overtime_eligible,attendance_required,valid_from,valid_to,schedule_status,sap_reference,remarks,created_by,updated_by,updated_at)
SELECT 'WS-WH-RM','Raw Material Warehouse Schedule','FIXED','WAREHOUSE',fc.id,fc.calendar_code,s.id,s.kode_shift,wl.id,'DEP-WH','STAFF','Y','Y','Y','Y','Y','Y','N','07:30:00','16:30:00',60,8,48,10,10,'Y','Y','2026-01-01','9999-12-31','ACTIVE','SAP-WS-WH-RM','Jadwal gudang raw material.', 'IGWH_IN','IGWH_IN',NOW()
  FROM erp_shift s LEFT JOIN erp_factory_calendar_header fc ON fc.calendar_code='FC-BASE-2026' LEFT JOIN erp_work_location wl ON wl.location_code='WL-WH-RM' WHERE s.kode_shift='SHIFT-1' LIMIT 1;

INSERT INTO erp_work_schedule (schedule_code,schedule_name,schedule_type,schedule_category,calendar_id,calendar_code,default_shift_id,default_shift_code,work_location_id,department_code,employee_group,monday,tuesday,wednesday,thursday,friday,saturday,sunday,planned_start,planned_end,break_minutes,working_hours_per_day,working_hours_per_week,grace_in_minutes,grace_out_minutes,overtime_eligible,attendance_required,valid_from,valid_to,schedule_status,sap_reference,remarks,created_by,updated_by,updated_at)
SELECT 'WS-WH-FG','Finished Goods Warehouse Schedule','FIXED','WAREHOUSE',fc.id,fc.calendar_code,s.id,s.kode_shift,wl.id,'DEP-WH','STAFF','Y','Y','Y','Y','Y','Y','N','08:00:00','17:00:00',60,8,48,10,10,'Y','Y','2026-01-01','9999-12-31','ACTIVE','SAP-WS-WH-FG','Jadwal gudang finished goods.', 'IGWH_OUT','IGWH_OUT',NOW()
  FROM erp_shift s LEFT JOIN erp_factory_calendar_header fc ON fc.calendar_code='FC-BASE-2026' LEFT JOIN erp_work_location wl ON wl.location_code='WL-WH-FG' WHERE s.kode_shift='SHIFT-1' LIMIT 1;

INSERT INTO erp_work_schedule (schedule_code,schedule_name,schedule_type,schedule_category,calendar_id,calendar_code,default_shift_id,default_shift_code,work_location_id,department_code,employee_group,monday,tuesday,wednesday,thursday,friday,saturday,sunday,planned_start,planned_end,break_minutes,working_hours_per_day,working_hours_per_week,grace_in_minutes,grace_out_minutes,overtime_eligible,attendance_required,valid_from,valid_to,schedule_status,sap_reference,remarks,created_by,updated_by,updated_at)
SELECT 'WS-SALES-001','Sales Office Flexible Schedule','FLEXIBLE','SALES',fc.id,fc.calendar_code,s.id,s.kode_shift,wl.id,'DEP-SLS','STAFF','Y','Y','Y','Y','Y','N','N','09:00:00','18:00:00',60,8,40,30,15,'Y','Y','2026-01-01','9999-12-31','ACTIVE','SAP-WS-SALES-001','Jadwal sales office dengan toleransi masuk lebih besar.', 'Nadia','Nadia',NOW()
  FROM erp_shift s LEFT JOIN erp_factory_calendar_header fc ON fc.calendar_code='FC-BASE-2026' LEFT JOIN erp_work_location wl ON wl.location_code='WL-SO-JKT' WHERE s.kode_shift='SHIFT-1' LIMIT 1;

INSERT INTO erp_work_schedule (schedule_code,schedule_name,schedule_type,schedule_category,calendar_id,calendar_code,default_shift_id,default_shift_code,work_location_id,department_code,employee_group,monday,tuesday,wednesday,thursday,friday,saturday,sunday,planned_start,planned_end,break_minutes,working_hours_per_day,working_hours_per_week,grace_in_minutes,grace_out_minutes,overtime_eligible,attendance_required,valid_from,valid_to,schedule_status,sap_reference,remarks,created_by,updated_by,updated_at)
SELECT 'WS-REMOTE-001','Remote Support Schedule','REMOTE','REMOTE',fc.id,fc.calendar_code,s.id,s.kode_shift,wl.id,'DEP-IT','STAFF','Y','Y','Y','Y','Y','N','N','08:30:00','17:30:00',60,8,40,30,30,'N','N','2026-01-01','9999-12-31','ACTIVE','SAP-WS-REMOTE-001','Jadwal remote support, attendance tidak wajib geofence.', 'Tinna','Tinna',NOW()
  FROM erp_shift s LEFT JOIN erp_factory_calendar_header fc ON fc.calendar_code='FC-BASE-2026' LEFT JOIN erp_work_location wl ON wl.location_code='WL-REMOTE' WHERE s.kode_shift='SHIFT-1' LIMIT 1;

COMMIT;
