<?php
if (!function_exists('prod_t')) {
  function prod_t($key, $fallback = '') { return lang_text($key, $fallback); }
}
if (!function_exists('prod_h')) {
  function prod_h($key, $fallback = '') { return htmlspecialchars((string) prod_t($key, $fallback), ENT_QUOTES, 'UTF-8'); }
}
if (!function_exists('prod_js')) {
  function prod_js($key, $fallback = '') { return json_encode(prod_t($key, $fallback), JSON_HEX_TAG | JSON_HEX_APOS | JSON_HEX_AMP | JSON_HEX_QUOT); }
}
$defaultFrom=date('Y-m-01');$defaultTo=date('Y-m-t');
$plants=$db->query("SELECT id,plant_code,plant_name FROM erp_plant WHERE status='Aktif' ORDER BY plant_code");
?>
<style>
.fc-hero{background:linear-gradient(135deg,#0f766e,#2563eb);color:#fff;border-radius:14px;padding:20px;margin-bottom:18px;box-shadow:0 10px 24px rgba(15,23,42,.16)}
.fc-hero h1{margin:0 0 6px;font-weight:700;font-size:26px}.fc-hero p{margin:0;opacity:.92}.fc-card{border-radius:12px;background:#fff;border:1px solid #e5edf5;box-shadow:0 5px 16px rgba(15,23,42,.05);margin-bottom:14px}.fc-card .box-header{border-bottom:1px solid #edf2f7}.fc-items th,.fc-items td,#dtb_forecast th,#dtb_forecast td{font-size:12px;vertical-align:middle}.select2-container{width:100%!important}.required-label:after{content:' *';color:#dd4b39}.fc-action{white-space:nowrap}
</style>
<section class="content-header"><h1><?=prod_h('production_forecast', 'Forecast');?> <small>SAP Demand Planning</small></h1><ol class="breadcrumb"><li><a href="<?=base_index();?>"><i class="fa fa-dashboard"></i> <?=prod_h('common_home', 'Home');?></a></li><li class="active"><?=prod_h('production_forecast', 'Forecast');?></li></ol></section>
<section class="content">
  <div class="fc-hero"><div class="row"><div class="col-md-8"><h1>Forecast Workbench</h1><p>Kelola demand forecast/PIR sebagai dasar MRP, production planning, dan purchase planning.</p></div><div class="col-md-4 text-right"><button id="btn_open_fc" class="btn btn-warning"><i class="fa fa-plus"></i> Create Forecast</button></div></div></div>
  <div class="box fc-card"><div class="box-header"><h3 class="box-title"><i class="fa fa-filter"></i> Filter Forecast</h3></div><div class="box-body"><form class="form-horizontal" onsubmit="return false;">
    <div class="form-group"><label class="control-label col-lg-2"><?=prod_h('production_period', 'Period');?></label><div class="col-lg-2"><div class="input-group date fc-date"><input id="filter_tgl_awal" class="form-control" value="<?=$defaultFrom;?>"><span class="input-group-addon"><span class="glyphicon glyphicon-calendar"></span></span></div></div><div class="col-lg-2"><div class="input-group date fc-date"><input id="filter_tgl_akhir" class="form-control" value="<?=$defaultTo;?>"><span class="input-group-addon"><span class="glyphicon glyphicon-calendar"></span></span></div></div><label class="control-label col-lg-1"><?=prod_h('production_plant', 'Plant');?></label><div class="col-lg-2"><select id="filter_plant" class="form-control"><option value=""><?=prod_h('common_all', 'All');?></option><?php foreach($plants as $p){ ?><option value="<?=htmlspecialchars($p->plant_code,ENT_QUOTES,'UTF-8');?>"><?=htmlspecialchars($p->plant_code.' - '.$p->plant_name,ENT_QUOTES,'UTF-8');?></option><?php } ?></select></div><label class="control-label col-lg-1"><?=prod_h('common_status', 'Status');?></label><div class="col-lg-2"><select id="filter_status" class="form-control"><option value=""><?=prod_h('common_all', 'All');?></option><option>DRAFT</option><option>RELEASED</option><option>CLOSED</option><option>CANCELLED</option></select></div></div>
    <div class="form-group"><label class="control-label col-lg-2"><?=prod_h('common_search', 'Search');?></label><div class="col-lg-5"><input id="filter_keyword" class="form-control" placeholder="<?=prod_h('production_search_forecast', 'Forecast no / material / customer');?>"></div><div class="col-lg-5"><button id="btn_filter_fc" class="btn btn-primary"><i class="fa fa-filter"></i> <?=prod_h('common_filter', 'Filter');?></button> <button id="btn_reset_fc" class="btn btn-default"><i class="fa fa-refresh"></i> <?=prod_h('common_reset', 'Reset');?></button> <button id="btn_export_fc" class="btn btn-success"><i class="fa fa-file-excel-o"></i> <?=prod_h('common_export_excel', 'Export Excel');?></button></div></div>
  </form></div></div>
  <div class="box fc-card"><div class="box-body"><div class="alert alert-warning error_data_delete" style="display:none"><button type="button" class="close hide_alert_notif">&times;</button><span class="isi_warning_delete"></span></div><div class="table-responsive"><table id="dtb_forecast" class="table table-bordered table-striped" style="width:100%"><thead><tr><th><?=prod_h('common_no', 'No');?></th><th><?=prod_h('common_action', 'Action');?></th><th><?=prod_h('production_forecast', 'Forecast');?></th><th><?=prod_h('production_period', 'Period');?></th><th><?=prod_h('production_plant', 'Plant');?></th><th><?=prod_h('production_customer', 'Customer');?></th><th><?=prod_h('production_items', 'Items');?></th><th><?=prod_h('production_total_qty', 'Total Qty');?></th><th><?=prod_h('common_status', 'Status');?></th><th><?=prod_h('common_created_by', 'Created By');?></th></tr></thead><tbody></tbody></table></div></div></div>
  <div id="modal_fc" class="modal fade"><div class="modal-dialog modal-lg" style="width:94%"><div class="modal-content"><form id="form_fc"><div class="modal-header"><button class="close" data-dismiss="modal">&times;</button><h4 class="modal-title">Create Forecast</h4></div><div class="modal-body">
    <div class="alert alert-info">Forecast bisa dibuat untuk semua customer atau customer tertentu. Setelah <strong>Release</strong>, data ini siap dipakai MRP sebagai demand planning.</div>
    <div class="row"><div class="col-md-2 form-group"><label><?=prod_h('production_type', 'Type');?></label><select name="forecast_type" class="form-control"><option value="SALES">Sales Forecast</option><option value="PRODUCTION">Production Forecast</option><option value="CUSTOMER">Customer Forecast</option><option value="SAFETY_STOCK">Safety Stock</option></select></div><div class="col-md-2 form-group"><label><?=prod_h('production_version_label', 'Version');?></label><input name="forecast_version" class="form-control" value="BASE"></div><div class="col-md-2 form-group"><label class="required-label">From</label><input name="period_from" class="form-control date-field" value="<?=$defaultFrom;?>" required></div><div class="col-md-2 form-group"><label class="required-label">To</label><input name="period_to" class="form-control date-field" value="<?=$defaultTo;?>" required></div><div class="col-md-2 form-group"><label><?=prod_h('production_plant', 'Plant');?></label><select id="plant_id" name="plant_id" class="form-control"><option value="">All Plant</option><?php foreach($db->query("SELECT id,plant_code,plant_name FROM erp_plant WHERE status='Aktif' ORDER BY plant_code") as $p){ ?><option value="<?=intval($p->id);?>" data-code="<?=htmlspecialchars($p->plant_code,ENT_QUOTES,'UTF-8');?>"><?=htmlspecialchars($p->plant_code.' - '.$p->plant_name,ENT_QUOTES,'UTF-8');?></option><?php } ?></select><input type="hidden" name="plant_code" id="plant_code"></div><div class="col-md-2 form-group"><label><?=prod_h('production_customer', 'Customer');?></label><select id="customer_code" name="customer_code" class="form-control"></select><input type="hidden" name="customer_name" id="customer_name"></div></div>
    <div class="form-group"><label><?=prod_h('common_remarks', 'Remarks');?></label><input name="remarks" class="form-control" placeholder="<?=prod_h('production_forecast_remark_placeholder', 'Forecast scenario / demand assumption notes');?>"></div>
    <h4>Forecast Items</h4><div class="table-responsive"><table class="table table-bordered table-condensed fc-items"><thead><tr><th style="width:48px"><button type="button" id="btn_add_line" class="btn btn-xs btn-primary"><i class="fa fa-plus"></i></button></th><th style="width:260px"><?=prod_h('production_material', 'Material');?></th><th style="width:120px">Period Month</th><th style="width:140px">Forecast Qty</th><th style="width:90px"><?=prod_h('production_uom', 'UOM');?></th><th style="width:150px"><?=prod_h('production_source', 'Source');?></th><th style="width:120px"><?=prod_h('production_confidence_percent', 'Confidence %');?></th><th><?=prod_h('common_remarks', 'Remarks');?></th></tr></thead><tbody id="fc_lines"></tbody></table></div>
  </div><div class="modal-footer"><button type="button" class="btn btn-default" data-dismiss="modal"><?=prod_h('common_cancel', 'Cancel');?></button><button type="submit" class="btn btn-primary"><i class="fa fa-save"></i> <?=prod_h('production_save_forecast', 'Save Forecast');?></button></div></form></div></div></div>
  <div id="modal_fc_detail" class="modal fade"><div class="modal-dialog modal-lg" style="width:94%"><div class="modal-content"><div class="modal-header"><button class="close" data-dismiss="modal">&times;</button><h4 class="modal-title">Forecast Detail</h4></div><div class="modal-body" id="fc_detail_body"></div><div class="modal-footer"><button class="btn btn-default" data-dismiss="modal"><?=prod_h('common_close', 'Close');?></button></div></div></div></div>
</section>
<script src="<?=base_admin();?>assets/plugins/select2/select2.min.js"></script><script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
<script>
function fcError(m){$('.isi_warning_delete').text(m||<?=prod_js('production_forecast_process_failed', 'Forecast failed to process.');?>);$('.error_data_delete').fadeIn();}
var lineNo=0;function addLine(){lineNo++;var rowId='fc_line_'+lineNo;var r='<tr id="'+rowId+'"><td class="text-center"><button type="button" class="btn btn-xs btn-danger btn-fc-remove-line"><i class="fa fa-trash"></i></button></td><td><select name="material_code[]" class="form-control material-select" required></select><input type="hidden" name="material_name[]"><input type="hidden" name="material_type[]"></td><td><input name="period_month[]" class="form-control date-field month-field" value="<?=date('Y-m-01');?>" required></td><td><input type="number" step="0.00001" min="0.00001" name="forecast_qty[]" class="form-control text-right" required></td><td><input name="uom[]" class="form-control" readonly></td><td><select name="source_type[]" class="form-control"><option>MANUAL</option><option>SALES_HISTORY</option><option>CUSTOMER_COMMITMENT</option><option>FORECAST_UPLOAD</option></select></td><td><input type="number" step="0.01" min="0" max="100" name="confidence_percent[]" class="form-control text-right" value="100"></td><td><input name="line_remarks[]" class="form-control"></td></tr>';$('#fc_lines').append(r);initMaterialSelect($('#'+rowId+' .material-select'));if($.fn.datepicker)$('#'+rowId+' .date-field').datepicker({format:'yyyy-mm-dd',autoclose:true,todayHighlight:true});}
function initMaterialSelect(el){if(!$.fn.select2){return;}el.select2({width:'100%',dropdownParent:$('#modal_fc'),placeholder:<?=prod_js('production_search_fg_sfg', 'Search FG/SFG material...');?>,minimumInputLength:1,ajax:{url:'<?=base_admin();?>modul/forecast/forecast_action.php?act=material_search',type:'POST',dataType:'json',delay:250,data:function(p){return{term:p.term||''};},processResults:function(d){return{results:d.results||[]};}}}).on('select2:select',function(e){var d=e.params.data,tr=$(this).closest('tr');tr.find('input[name="material_name[]"]').val(d.material_name||'');tr.find('input[name="material_type[]"]').val(d.material_type||'');tr.find('input[name="uom[]"]').val(d.uom||'');});}
function filters(){return{tgl_awal:$('#filter_tgl_awal').val(),tgl_akhir:$('#filter_tgl_akhir').val(),status:$('#filter_status').val(),plant:$('#filter_plant').val(),keyword:$('#filter_keyword').val()};}
$(function(){if($.fn.datepicker){$('.fc-date,.date-field').datepicker({format:'yyyy-mm-dd',autoclose:true,todayHighlight:true});}if($.fn.select2){$('#filter_plant,#filter_status,#plant_id').select2({width:'100%'});$('#customer_code').select2({width:'100%',dropdownParent:$('#modal_fc'),placeholder:<?=prod_js('production_all_customer', 'All Customer');?>,allowClear:true,ajax:{url:'<?=base_admin();?>modul/forecast/forecast_action.php?act=customer_search',type:'POST',dataType:'json',delay:250,data:function(p){return{term:p.term||''};},processResults:function(d){return{results:d.results||[]};}}}).on('select2:select',function(e){$('#customer_name').val(e.params.data.customer_name||'');}).on('select2:clear',function(){$('#customer_name').val('');});}
var dt=null;function reloadForecastTable(resetPaging){if(dt&&dt.draw){dt.draw(resetPaging===false?false:undefined);}}
try{if($.fn.DataTable){dt=$('#dtb_forecast').DataTable({bProcessing:true,bServerSide:true,pageLength:25,dom:"<'row'<'col-sm-12'B>>"+"<'row'<'col-sm-6'l><'col-sm-6'f>>"+"<'row'<'col-sm-12'tr>>"+"<'row'<'col-sm-5'i><'col-sm-7'p>>",buttons:[{extend:'collection',text:<?=prod_js('common_export_data', 'Export Data');?>,buttons:['copyHtml5','excelHtml5','csvHtml5','pdfHtml5']}],columnDefs:[{targets:[0,1],orderable:false,searchable:false},{targets:[7],className:'text-right'},{width:'42px',targets:0},{width:'105px',targets:1}],ajax:{url:'<?=base_admin();?>modul/forecast/forecast_data.php',type:'post',data:function(d){$.extend(d,filters());},error:function(xhr){console.log(xhr.responseText);fcError(<?=prod_js('production_forecast_load_failed', 'Forecast data failed to load.');?>);}}});}}catch(e){console.error(e);fcError(<?=prod_js('production_forecast_load_failed_create_available', 'Forecast data failed to load. Create button remains available.');?>);}
$('#btn_open_fc').click(function(){lineNo=0;$('#form_fc')[0].reset();$('#fc_lines').html('');$('#customer_code').val(null).trigger('change');$('#plant_id').val('').trigger('change');addLine();$('#modal_fc').modal({backdrop:'static',keyboard:false});});$('#plant_id').change(function(){$('#plant_code').val($('#plant_id option:selected').data('code')||'');});$('#btn_add_line').click(addLine);$('#btn_filter_fc').click(function(){reloadForecastTable();});$('#filter_keyword').keyup(function(e){if(e.keyCode===13)reloadForecastTable();});$('#btn_reset_fc').click(function(){$('#filter_tgl_awal').val('<?=$defaultFrom;?>');$('#filter_tgl_akhir').val('<?=$defaultTo;?>');$('#filter_status,#filter_plant').val('').trigger('change');$('#filter_keyword').val('');reloadForecastTable();});$('#btn_export_fc').click(function(){window.location='<?=base_admin();?>modul/forecast/forecast_action.php?act=excel&'+$.param(filters());});
$(document).on('click','.btn-fc-remove-line',function(){$(this).closest('tr').remove();});
$('#form_fc').submit(function(e){e.preventDefault();var btn=$(this).find('button[type=submit]');btn.prop('disabled',true).html('<i class="fa fa-spinner fa-spin"></i> <?=prod_h('common_saving', 'Saving...');?>');$.post('<?=base_admin();?>modul/forecast/forecast_action.php?act=save',$(this).serialize(),function(r){if(r.status==='good'){$('#modal_fc').modal('hide');reloadForecastTable(false);}else fcError(r.error_message);btn.prop('disabled',false).html('<i class="fa fa-save"></i> <?=prod_h('production_save_forecast', 'Save Forecast');?>');},'json').fail(function(xhr){fcError(xhr.responseText);btn.prop('disabled',false).html('<i class="fa fa-save"></i> <?=prod_h('production_save_forecast', 'Save Forecast');?>');});});
$(document).on('click','.btn-fc-detail',function(){$.post('<?=base_admin();?>modul/forecast/forecast_action.php?act=detail',{id:$(this).data('id')},function(html){$('#fc_detail_body').html(html);$('#modal_fc_detail').modal('show');});});$(document).on('click','.btn-fc-release',function(){var id=$(this).data('id'),no=$(this).data('no');Swal.fire({title:<?=prod_js('production_release_forecast_confirm', 'Release Forecast?');?>,text:no+' akan tersedia untuk MRP.',icon:'question',showCancelButton:true,confirmButtonText:<?=prod_js('production_release', 'Release');?>}).then(function(x){if(!x.isConfirmed)return;$.post('<?=base_admin();?>modul/forecast/forecast_action.php?act=release',{id:id},function(r){if(r.status==='good')reloadForecastTable(false);else fcError(r.error_message);},'json');});});$(document).on('click','.btn-fc-cancel',function(){var id=$(this).data('id'),no=$(this).data('no');Swal.fire({title:<?=prod_js('production_cancel_forecast_confirm', 'Cancel Forecast?');?>,input:'text',inputLabel:'Reason '+no,showCancelButton:true,confirmButtonText:'Cancel',inputValidator:function(v){return !v?<?=prod_js('production_reason_required', 'Reason is required');?>:undefined;}}).then(function(x){if(!x.isConfirmed)return;$.post('<?=base_admin();?>modul/forecast/forecast_action.php?act=cancel',{id:id,reason:x.value},function(r){if(r.status==='good')reloadForecastTable(false);else fcError(r.error_message);},'json');});});$('.hide_alert_notif').click(function(){$('.error_data_delete').hide();});
});
</script>
