<?php
if (!function_exists('sd_t')) {
  function sd_t($key, $fallback = '') { return lang_text($key, $fallback); }
}
if (!function_exists('sd_h')) {
  function sd_h($key, $fallback = '') { return htmlspecialchars((string) sd_t($key, $fallback), ENT_QUOTES, 'UTF-8'); }
}
if (!function_exists('sd_js')) {
  function sd_js($key, $fallback = '') { return json_encode(sd_t($key, $fallback), JSON_HEX_TAG | JSON_HEX_APOS | JSON_HEX_AMP | JSON_HEX_QUOT); }
}
include_once "outbound_delivery_lib.php";
$defaultFrom=date('Y-01-01');$defaultTo=date('Y-m-d');
$customers=$db->query("SELECT kode_penerima,nama FROM penerima ORDER BY nama");
$shippingPoints=$db->query("SELECT shipping_code,shipping_name FROM erp_shipping_point WHERE status='Aktif' ORDER BY shipping_code");
$summary=obd_summary($db,array('tgl_awal'=>$defaultFrom,'tgl_akhir'=>$defaultTo,'customer'=>'all','status'=>'all'));
?>
<style>
.obd-hero{background:linear-gradient(135deg,#0f766e,#1d4ed8);color:#fff;border-radius:14px;padding:20px 22px;margin-bottom:18px;box-shadow:0 10px 24px rgba(15,23,42,.18)}
.obd-hero h1{margin:0 0 6px;font-size:26px;font-weight:700}.obd-hero p{margin:0;opacity:.92}
.obd-kpi{border-radius:12px;background:#fff;border:1px solid #e5edf5;padding:15px;margin-bottom:14px;box-shadow:0 4px 14px rgba(15,23,42,.05)}
.obd-kpi span{display:block;color:#64748b;font-size:12px;text-transform:uppercase;letter-spacing:.04em}.obd-kpi strong{display:block;font-size:23px;margin-top:6px;color:#111827}
.obd-kpi i{float:right;font-size:26px;color:#0f766e;opacity:.55}.obd-filter .form-group{margin-bottom:12px}
#dtb_outbound_delivery th,#dtb_outbound_delivery td{font-size:12px;vertical-align:middle}.select2-container{width:100%!important}.progress-xs{height:6px}.obd-item-table th,.obd-item-table td{font-size:12px;vertical-align:middle}.obd-item-table .form-control{font-size:12px;height:31px;padding:4px 7px}
</style>
<section class="content-header"><h1><?=sd_h('sales_outbound_delivery', 'Outbound Delivery');?> <small>SAP SD Delivery</small></h1><ol class="breadcrumb"><li><a href="<?=base_index();?>"><i class="fa fa-dashboard"></i> <?=sd_h('common_home', 'Home');?></a></li><li><a href="#">Sales & Distribution</a></li><li class="active"><?=sd_h('sales_outbound_delivery', 'Outbound Delivery');?></li></ol></section>
<section class="content">
  <div class="obd-hero"><div class="row"><div class="col-md-8"><h1><?=sd_h('sales_outbound_delivery', 'Outbound Delivery');?></h1><p>Membuat dan memonitor dokumen delivery dari Sales Order approved sebagai dasar picking, packing, surat jalan, dan posting goods issue.</p></div><div class="col-md-4 text-right"><button id="btn_add_obd" class="btn btn-success"><i class="fa fa-plus"></i> Create Delivery</button></div></div></div>
  <div class="row">
    <div class="col-sm-3"><div class="obd-kpi"><i class="fa fa-truck"></i><span>Total Delivery</span><strong><?=number_format((float)$summary->total_docs,0,',','.');?></strong></div></div>
    <div class="col-sm-3"><div class="obd-kpi"><i class="fa fa-file-text-o"></i><span>Created</span><strong><?=number_format((float)$summary->created_docs,0,',','.');?></strong></div></div>
    <div class="col-sm-3"><div class="obd-kpi"><i class="fa fa-check-circle"></i><span>PGI/Completed</span><strong><?=number_format((float)$summary->pgi_docs,0,',','.');?></strong></div></div>
    <div class="col-sm-3"><div class="obd-kpi"><i class="fa fa-money"></i><span>Delivery Value</span><strong><?=number_format((float)$summary->total_amount,0,',','.');?></strong></div></div>
  </div>
  <div class="box"><div class="box-header with-border"><h3 class="box-title"><i class="fa fa-filter"></i> Filter Outbound Delivery</h3></div><div class="box-body">
    <form class="form-horizontal obd-filter" onsubmit="return false;">
      <div class="form-group"><label class="control-label col-lg-2"><?=sd_h('sales_delivery_date', 'Delivery Date');?></label><div class="col-lg-2"><div class="input-group date obd-date"><input id="filter_tgl_awal" class="form-control" value="<?=$defaultFrom;?>"><span class="input-group-addon"><span class="glyphicon glyphicon-calendar"></span></span></div></div><div class="col-lg-2"><div class="input-group date obd-date"><input id="filter_tgl_akhir" class="form-control" value="<?=$defaultTo;?>"><span class="input-group-addon"><span class="glyphicon glyphicon-calendar"></span></span></div></div><label class="control-label col-lg-1"><?=sd_h('sales_customer', 'Customer');?></label><div class="col-lg-5"><select id="filter_customer" class="form-control"><option value="all"><?=sd_h('sales_all_customer', 'All Customer');?></option><?php foreach($customers as $c){ ?><option value="<?=obd_h($c->kode_penerima);?>"><?=obd_h($c->kode_penerima.' - '.$c->nama);?></option><?php } ?></select></div></div>
      <div class="form-group"><label class="control-label col-lg-2"><?=sd_h('common_status', 'Status');?></label><div class="col-lg-2"><select id="filter_status" class="form-control"><option value="all"><?=sd_h('common_all', 'All');?></option><option>CREATED</option><option>PICKING</option><option>PICKED</option><option>PACKED</option><option>PGI</option><option>COMPLETED</option><option>CANCELLED</option></select></div><label class="control-label col-lg-2"><?=sd_h('sales_shipping_point', 'Shipping Point');?></label><div class="col-lg-2"><select id="filter_shipping_point" class="form-control"><option value=""><?=sd_h('common_all', 'All');?></option><?php foreach($shippingPoints as $sp){ ?><option value="<?=obd_h($sp->shipping_code);?>"><?=obd_h($sp->shipping_code.' - '.$sp->shipping_name);?></option><?php } ?></select></div><label class="control-label col-lg-1"><?=sd_h('common_search', 'Search');?></label><div class="col-lg-3"><input id="filter_keyword" class="form-control" placeholder="Delivery/SO/customer/vehicle/SJ/GI"></div></div>
      <div class="form-group"><div class="col-lg-offset-2 col-lg-10"><button id="btn_filter_obd" class="btn btn-primary"><i class="fa fa-filter"></i> <?=sd_h('common_filter', 'Filter');?></button> <button id="btn_reset_obd" class="btn btn-default"><i class="fa fa-refresh"></i> <?=sd_h('common_reset', 'Reset');?></button> <button id="btn_excel_obd" class="btn btn-success"><i class="fa fa-file-excel-o"></i> <?=sd_h('common_export_excel', 'Export Excel');?></button></div></div>
    </form>
  </div></div>
  <div class="box"><div class="box-body"><div class="alert alert-warning error_data_delete" style="display:none"><button type="button" class="close hide_alert_notif">&times;</button><i class="icon fa fa-warning"></i> <span class="isi_warning_delete"></span></div><div class="table-responsive"><table id="dtb_outbound_delivery" class="table table-bordered table-striped table-condensed" style="width:100%"><thead><tr><th><?=sd_h('common_no', 'No');?></th><th><?=sd_h('common_action', 'Action');?></th><th>Delivery</th><th><?=sd_h('sales_date', 'Date');?></th><th><?=sd_h('sales_customer', 'Customer');?></th><th><?=sd_h('common_status', 'Status');?></th><th>Process</th><th><?=sd_h('sales_items', 'Items');?></th><th>Delivery Qty</th><th>GI Qty</th><th>Value</th><th>Ship Point</th><th>Vehicle/Driver</th></tr></thead><tbody></tbody></table></div></div></div>
</section>
<div id="modal_obd" class="modal fade"><div class="modal-dialog modal-lg" style="width:96%"><div class="modal-content"><form id="form_obd"><div class="modal-header"><button class="close" data-dismiss="modal">&times;</button><h4 class="modal-title">Create Outbound Delivery</h4></div><div class="modal-body">
  <div class="row"><div class="col-sm-4"><div class="form-group"><label><?=sd_h('sales_order', 'Sales Order');?></label><select id="so_select" name="id_sales_order" class="form-control" required></select></div></div><div class="col-sm-2"><div class="form-group"><label><?=sd_h('sales_delivery_date', 'Delivery Date');?></label><input name="delivery_date" class="form-control obd-date-input" value="<?=date('Y-m-d');?>"></div></div><div class="col-sm-2"><div class="form-group"><label>Planned GI</label><input name="planned_gi_date" class="form-control obd-date-input" value="<?=date('Y-m-d');?>"></div></div><div class="col-sm-4"><div class="form-group"><label><?=sd_h('sales_shipping_point', 'Shipping Point');?></label><select name="shipping_point" class="form-control obd-select"><option value="">-</option><?php foreach($shippingPoints as $sp){ ?><option value="<?=obd_h($sp->shipping_code);?>"><?=obd_h($sp->shipping_code.' - '.$sp->shipping_name);?></option><?php } ?></select></div></div></div>
  <div class="row"><div class="col-sm-3"><div class="form-group"><label>Route</label><input name="route" class="form-control"></div></div><div class="col-sm-3"><div class="form-group"><label>Carrier</label><input name="carrier" class="form-control"></div></div><div class="col-sm-3"><div class="form-group"><label>Vehicle No</label><input name="vehicle_no" class="form-control"></div></div><div class="col-sm-3"><div class="form-group"><label><?=sd_h('sales_driver', 'Driver');?></label><input name="driver_name" class="form-control"></div></div></div>
  <div class="form-group"><label>Ship To Address</label><textarea name="ship_to_address" id="ship_to_address" class="form-control" rows="2"></textarea></div>
  <div class="table-responsive"><table class="table table-bordered table-condensed obd-item-table" id="table_obd_items"><thead><tr><th><?=sd_h('common_no', 'No');?></th><th><?=sd_h('sales_material', 'Material');?></th><th>Store</th><th>Order Qty</th><th>Delivery Qty</th><th><?=sd_h('sales_uom', 'UOM');?></th><th><?=sd_h('sales_price', 'Price');?></th><th><?=sd_h('sales_amount', 'Amount');?></th><th>Remark</th></tr></thead><tbody><tr><td colspan="9" class="text-center text-muted">Pilih Sales Order untuk load item.</td></tr></tbody></table></div>
  <div class="form-group"><label><?=sd_h('common_remarks', 'Remarks');?></label><textarea name="remarks" class="form-control" rows="2"></textarea></div>
</div><div class="modal-footer"><button type="button" class="btn btn-default" data-dismiss="modal"><?=sd_h('common_close', 'Close');?></button><button type="submit" class="btn btn-primary"><i class="fa fa-save"></i> Save Delivery</button></div></form></div></div></div>
<div id="modal_obd_detail" class="modal fade"><div class="modal-dialog modal-lg" style="width:96%"><div class="modal-content"><div class="modal-header"><button class="close" data-dismiss="modal">&times;</button><h4 class="modal-title">Outbound Delivery Detail</h4></div><div class="modal-body" id="obd_detail_body"></div></div></div></div>
<script src="<?=base_admin();?>assets/plugins/select2/select2.min.js"></script>
<script>
function obdFilters(){return{tgl_awal:$('#filter_tgl_awal').val(),tgl_akhir:$('#filter_tgl_akhir').val(),customer:$('#filter_customer').val(),status:$('#filter_status').val(),shipping_point:$('#filter_shipping_point').val(),keyword:$('#filter_keyword').val()};}
function obdError(m){$('.isi_warning_delete').text(m||<?=sd_js('sales_outbound_delivery_process_failed', 'Outbound Delivery data failed to process.');?>);$('.error_data_delete').fadeIn();}
$(function(){
 if($.fn.datepicker){$('.obd-date,.obd-date-input').datepicker({format:'yyyy-mm-dd',autoclose:true,todayHighlight:true});}
 if($.fn.select2){$('#filter_customer,#filter_status,#filter_shipping_point,.obd-select').select2({width:'100%'});$('#so_select').select2({width:'100%',placeholder:'Cari Sales Order approved...',minimumInputLength:1,ajax:{url:'<?=base_admin();?>modul/outbound_delivery/outbound_delivery_action.php?act=so_search',type:'POST',dataType:'json',delay:250,data:function(p){return{term:p.term||''};},processResults:function(d){return{results:d.results||[]};}}}).on('select2:select',function(e){$('#ship_to_address').val(e.params.data.address||'');loadSoItems(e.params.data.id);});}
 var dt=$('#dtb_outbound_delivery').DataTable({bProcessing:true,bServerSide:true,pageLength:25,ordering:false,dom:"<'row'<'col-sm-12'B>>"+"<'row'<'col-sm-6'l><'col-sm-6'f>>"+"<'row'<'col-sm-12'tr>>"+"<'row'<'col-sm-5'i><'col-sm-7'p>>",buttons:[{extend:'collection',text:<?=sd_js('common_export_data', 'Export Data');?>,buttons:['copyHtml5','excelHtml5','csvHtml5','pdfHtml5']}],columnDefs:[{targets:[0,1],orderable:false,searchable:false},{targets:[7,8,9,10],className:'text-right'},{width:'42px',targets:0},{width:'60px',targets:1}],ajax:{url:'<?=base_admin();?>modul/outbound_delivery/outbound_delivery_data.php',type:'post',data:function(d){$.extend(d,obdFilters());},error:function(xhr){console.log(xhr);obdError(<?=sd_js('sales_outbound_delivery_load_failed', 'Outbound Delivery data failed to load.');?>);}}});
 function loadSoItems(id){$.post('<?=base_admin();?>modul/outbound_delivery/outbound_delivery_action.php?act=so_items',{id_sales_order:id},function(html){$('#table_obd_items tbody').html(html);},'html').fail(function(){obdError(<?=sd_js('sales_so_item_load_failed', 'SO item failed to load.');?>);});}
 $('#btn_add_obd').on('click',function(){$('#form_obd')[0].reset();$('#so_select').val(null).trigger('change');$('#table_obd_items tbody').html('<tr><td colspan="9" class="text-center text-muted">Pilih Sales Order untuk load item.</td></tr>');$('#modal_obd').modal('show');});
 $('#btn_filter_obd').on('click',function(){dt.draw();});$('#filter_keyword').on('keyup',function(e){if(e.keyCode===13)dt.draw();});
 $('#btn_reset_obd').on('click',function(){$('#filter_tgl_awal').val('<?=$defaultFrom;?>');$('#filter_tgl_akhir').val('<?=$defaultTo;?>');$('#filter_keyword').val('');$('#filter_customer,#filter_status').val('all').trigger('change');$('#filter_shipping_point').val('').trigger('change');dt.draw();});
 $('#btn_excel_obd').on('click',function(){window.location='<?=base_admin();?>modul/outbound_delivery/outbound_delivery_action.php?act=excel&'+$.param(obdFilters());});
 $('#form_obd').on('submit',function(e){e.preventDefault();$.post('<?=base_admin();?>modul/outbound_delivery/outbound_delivery_action.php?act=save',$(this).serialize(),function(r){if(r.status==='good'){$('#modal_obd').modal('hide');dt.draw(false);}else{obdError(r.error_message||<?=sd_js('sales_delivery_save_failed', 'Delivery failed to save.');?>);}},'json').fail(function(xhr){console.log(xhr.responseText);obdError(<?=sd_js('sales_delivery_save_failed', 'Delivery failed to save.');?>);});});
 $(document).on('keyup change','.delivery-qty,.item-price',function(){var tr=$(this).closest('tr'),q=parseFloat(String(tr.find('.delivery-qty').val()||'0').replace(',','.'))||0,p=parseFloat(String(tr.find('.item-price').val()||'0').replace(',','.'))||0;tr.find('.item-amount').val((q*p).toFixed(2));});
 $(document).on('click','.btn-obd-detail',function(){$.post('<?=base_admin();?>modul/outbound_delivery/outbound_delivery_action.php?act=detail',{id:$(this).data('id')},function(html){$('#obd_detail_body').html(html);$('#modal_obd_detail').modal('show');}).fail(function(){obdError('Detail gagal dibuka.');});});
 $(document).on('click','.hide_alert_notif',function(){$('.error_data_delete').hide();});
});
</script>
