<?php
if (!function_exists('hr_t')) {
  function hr_t($key, $fallback = '') { return lang_text($key, $fallback); }
}
if (!function_exists('hr_h')) {
  function hr_h($key, $fallback = '') { return htmlspecialchars((string) hr_t($key, $fallback), ENT_QUOTES, 'UTF-8'); }
}
if (!function_exists('hr_js')) {
  function hr_js($key, $fallback = '') { return json_encode(hr_t($key, $fallback), JSON_HEX_TAG | JSON_HEX_APOS | JSON_HEX_AMP | JSON_HEX_QUOT); }
}
$defaultFrom=date('Y-m-01');$defaultTo=date('Y-m-t');$canInsert=isset($role_act['insert_act'])&&$role_act['insert_act']==='Y'; ?>
<style>
.pp-hero{background:linear-gradient(135deg,#1e3a8a,#06b6d4);color:#fff;border-radius:14px;padding:20px;margin-bottom:18px;box-shadow:0 10px 24px rgba(15,23,42,.16)}.pp-hero h1{margin:0 0 6px;font-size:26px;font-weight:700}.pp-card{border-radius:12px;background:#fff;border:1px solid #e5edf5;box-shadow:0 5px 16px rgba(15,23,42,.05);margin-bottom:14px}.pp-kpi{padding:14px;border-radius:12px;background:#eff6ff;border:1px solid #bfdbfe}.pp-kpi b{font-size:22px;display:block}#dtb_payroll_process th,#dtb_payroll_process td{font-size:12px;vertical-align:middle}.select2-container{width:100%!important}.required-label:after{content:' *';color:#dd4b39}.pp-action{white-space:nowrap}#modal_payroll_process .modal-body{max-height:calc(100vh - 185px);overflow-y:auto}.pp-section-title{font-weight:700;color:#334155;margin:8px 0 12px;border-bottom:1px solid #e5e7eb;padding-bottom:7px}.pp-hint{background:#ecfeff;border:1px solid #a5f3fc;border-radius:10px;padding:10px;margin-bottom:10px}.pp-emp-table th,.pp-emp-table td{font-size:12px;vertical-align:middle}.pp-emp-table .form-control{height:30px;padding:4px 6px;font-size:12px}.pp-summary{background:#f8fafc;border:1px dashed #cbd5e1;border-radius:10px;padding:10px;margin-bottom:10px}
</style>
<section class="content-header"><h1><?=hr_h('hr_payroll_process', 'Payroll Process');?> <small>SAP HR Payroll Run</small></h1><ol class="breadcrumb"><li><a href="<?=base_index();?>"><i class="fa fa-dashboard"></i> <?=hr_h('common_home', 'Home');?></a></li><li>Human Resource</li><li>Payroll</li><li class="active"><?=hr_h('hr_payroll_process', 'Payroll Process');?></li></ol></section>
<section class="content">
<div class="pp-hero"><div class="row"><div class="col-md-8"><h1>Payroll Processing</h1><p>Jalankan payroll per periode: pilih employee, salary structure, hitung earnings, deductions, tax, net pay, approval, dan posting readiness.</p></div><div class="col-md-4 text-right"><?php if($canInsert){ ?><button id="btn_open_pp" class="btn btn-warning"><i class="fa fa-plus"></i> Create Payroll Run</button><?php } ?> <button id="btn_export_pp" class="btn btn-success"><i class="fa fa-file-excel-o"></i> <?=hr_h('common_export_excel', 'Export Excel');?></button></div></div></div>
<div class="row"><div class="col-sm-2"><div class="pp-kpi"><span>Total Run</span><b id="kpi_total">0</b></div></div><div class="col-sm-2"><div class="pp-kpi"><span>Calculated</span><b id="kpi_calculated">0</b></div></div><div class="col-sm-2"><div class="pp-kpi"><span><?=hr_h('hr_approved', 'Approved');?></span><b id="kpi_approved">0</b></div></div><div class="col-sm-2"><div class="pp-kpi"><span><?=hr_h('hr_posted', 'Posted');?></span><b id="kpi_posted">0</b></div></div><div class="col-sm-2"><div class="pp-kpi"><span>Employees</span><b id="kpi_employees">0</b></div></div><div class="col-sm-2"><div class="pp-kpi"><span><?=hr_h('hr_net_pay', 'Net Pay');?></span><b id="kpi_net">0</b></div></div></div>
<div class="box pp-card"><div class="box-header"><h3 class="box-title"><i class="fa fa-filter"></i> Filter Payroll Process</h3></div><div class="box-body"><form class="form-horizontal" onsubmit="return false;"><div class="form-group"><label class="control-label col-lg-2"><?=hr_h('hr_period', 'Period');?></label><div class="col-lg-2"><div class="input-group date pp-date"><input id="filter_tgl_awal" class="form-control" value="<?=$defaultFrom;?>"><span class="input-group-addon"><span class="glyphicon glyphicon-calendar"></span></span></div></div><div class="col-lg-2"><div class="input-group date pp-date"><input id="filter_tgl_akhir" class="form-control" value="<?=$defaultTo;?>"><span class="input-group-addon"><span class="glyphicon glyphicon-calendar"></span></span></div></div><label class="control-label col-lg-1">Area</label><div class="col-lg-2"><select id="filter_payroll_area" class="form-control"><option value="">All</option><option>MONTHLY</option><option>DAILY</option><option>WEEKLY</option><option>CONTRACT</option><option>MANAGEMENT</option><option>ALL</option></select></div><label class="control-label col-lg-1"><?=hr_h('common_status', 'Status');?></label><div class="col-lg-2"><select id="filter_process_status" class="form-control"><option value="">All</option><option>DRAFT</option><option>CALCULATED</option><option>APPROVED</option><option>POSTED</option><option>CANCELLED</option></select></div></div><div class="form-group"><label class="control-label col-lg-2">Type</label><div class="col-lg-2"><select id="filter_process_type" class="form-control"><option value="">All</option><option>REGULAR</option><option>OFFCYCLE</option><option>THR</option><option>BONUS</option><option>FINAL_SETTLEMENT</option><option>CORRECTION</option></select></div><label class="control-label col-lg-1">Mode</label><div class="col-lg-2"><select id="filter_run_mode" class="form-control"><option value="">All</option><option>SIMULATION</option><option>LIVE</option></select></div><label class="control-label col-lg-1">Keyword</label><div class="col-lg-2"><input id="filter_keyword" class="form-control" placeholder="Run no, posting ref"></div><div class="col-lg-2"><button id="btn_filter_pp" class="btn btn-primary"><i class="fa fa-filter"></i> <?=hr_h('common_filter', 'Filter');?></button> <button id="btn_reset_pp" class="btn btn-default"><i class="fa fa-refresh"></i></button></div></div></form></div></div>
<div class="box pp-card"><div class="box-body"><div class="alert alert-warning error_data_delete" style="display:none"><button type="button" class="close hide_alert_notif">&times;</button><span class="isi_warning_delete"></span></div><div class="table-responsive"><table id="dtb_payroll_process" class="table table-bordered table-striped" style="width:100%"><thead><tr><th><?=hr_h('common_no', 'No');?></th><th><?=hr_h('common_action', 'Action');?></th><th>Run</th><th><?=hr_h('hr_period', 'Period');?></th><th>Area</th><th>Type</th><th><?=hr_h('hr_employee', 'Employee');?></th><th>Amount</th><th><?=hr_h('common_status', 'Status');?></th><th>Updated</th></tr></thead><tbody></tbody></table></div></div></div>
<div id="modal_payroll_process" class="modal fade"><div class="modal-dialog modal-lg" style="width:96%"><div class="modal-content"><form id="form_payroll_process"><input type="hidden" name="id" id="pp_id"><input type="hidden" name="employee_json" id="employee_json"><div class="modal-header"><button type="button" class="close" data-dismiss="modal">&times;</button><h4 class="modal-title">Create Payroll Run</h4></div><div class="modal-body"><div class="pp-hint"><strong>SAP hint:</strong> Control Record mengunci periode payroll. Gunakan SIMULATION untuk test run, LIVE untuk run yang siap approval/posting.</div>
<div class="pp-section-title">Payroll Run Header</div><div class="row"><div class="col-md-2 form-group"><label class="required-label">Run No</label><input name="payroll_run_no" id="payroll_run_no" class="form-control text-uppercase" required maxlength="30" placeholder="PRUN-..."></div><div class="col-md-1 form-group"><label>Year</label><input name="period_year" id="period_year" type="number" class="form-control" value="<?=date('Y');?>"></div><div class="col-md-1 form-group"><label>Month</label><input name="period_month" id="period_month" type="number" min="1" max="12" class="form-control" value="<?=date('n');?>"></div><div class="col-md-2 form-group"><label>Period From</label><input name="period_from" id="period_from" class="form-control date-field" value="<?=$defaultFrom;?>"></div><div class="col-md-2 form-group"><label>Period To</label><input name="period_to" id="period_to" class="form-control date-field" value="<?=$defaultTo;?>"></div><div class="col-md-2 form-group"><label>Pay Date</label><input name="pay_date" id="pay_date" class="form-control date-field" value="<?=$defaultTo;?>"></div><div class="col-md-2 form-group"><label>Currency</label><select name="currency" id="currency" class="form-control"><option>IDR</option><option>USD</option></select></div></div>
<div class="row"><div class="col-md-2 form-group"><label>Payroll Area</label><select name="payroll_area" id="payroll_area" class="form-control"><option>MONTHLY</option><option>DAILY</option><option>WEEKLY</option><option>CONTRACT</option><option>MANAGEMENT</option><option>ALL</option></select></div><div class="col-md-2 form-group"><label>Process Type</label><select name="process_type" id="process_type" class="form-control"><option>REGULAR</option><option>OFFCYCLE</option><option>THR</option><option>BONUS</option><option>FINAL_SETTLEMENT</option><option>CORRECTION</option></select></div><div class="col-md-2 form-group"><label>Run Mode</label><select name="run_mode" id="run_mode" class="form-control"><option>SIMULATION</option><option>LIVE</option></select></div><div class="col-md-2 form-group"><label>Control Record</label><select name="control_record_status" id="control_record_status" class="form-control"><option>OPEN</option><option>RELEASED</option><option>LOCKED</option><option>EXITED</option></select></div><div class="col-md-2 form-group"><label><?=hr_h('common_status', 'Status');?></label><select name="process_status" id="process_status" class="form-control"><option>DRAFT</option><option>CALCULATED</option><option>APPROVED</option><option>POSTED</option><option>CANCELLED</option></select></div><div class="col-md-2 form-group"><label>Posting Ref</label><input name="posting_reference" id="posting_reference" class="form-control"></div></div>
<div class="row"><div class="col-md-3 form-group"><label>SAP Reference</label><input name="sap_reference" id="sap_reference" class="form-control"></div><div class="col-md-9 form-group"><label><?=hr_h('common_remarks', 'Remarks');?></label><input name="remarks" id="remarks" class="form-control"></div></div>
<div class="pp-section-title">Payroll Employee</div><div class="pp-summary"><div class="row"><div class="col-sm-4"><b>Total Employee:</b> <span id="pp_emp_count">0</span></div><div class="col-sm-4"><b>Total Paid Days:</b> <span id="pp_paid_days">0</span></div><div class="col-sm-4 text-right"><button type="button" id="btn_add_employee" class="btn btn-sm btn-info"><i class="fa fa-plus"></i> Add Employee</button></div></div></div><div class="table-responsive"><table class="table table-bordered table-condensed pp-emp-table"><thead><tr><th style="width:260px"><?=hr_h('hr_employee', 'Employee');?></th><th style="width:260px"><?=hr_h('hr_salary_structure', 'Salary Structure');?></th><th style="width:90px">Work Days</th><th style="width:90px">Paid Days</th><th style="width:90px">Absence</th><th style="width:90px">OT Hours</th><th style="width:45px"></th></tr></thead><tbody id="pp_employee_body"></tbody></table></div>
</div><div class="modal-footer"><button type="button" class="btn btn-default" data-dismiss="modal"><?=hr_h('common_cancel', 'Cancel');?></button><button type="submit" class="btn btn-primary"><i class="fa fa-calculator"></i> Save & Calculate</button></div></form></div></div></div>
<div id="modal_pp_detail" class="modal fade"><div class="modal-dialog modal-lg" style="width:94%"><div class="modal-content"><div class="modal-header"><button class="close" data-dismiss="modal">&times;</button><h4 class="modal-title">Payroll Process Detail</h4></div><div class="modal-body" id="pp_detail_body"></div><div class="modal-footer"><button class="btn btn-default" data-dismiss="modal"><?=hr_h('common_close', 'Close');?></button></div></div></div></div>
</section>
<script src="<?=base_admin();?>assets/plugins/select2/select2.min.js"></script><script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
<script>
function ppError(m){$('.isi_warning_delete').text(m||'Payroll Process gagal diproses.');$('.error_data_delete').fadeIn();}
function ppFilters(){return{tgl_awal:$('#filter_tgl_awal').val(),tgl_akhir:$('#filter_tgl_akhir').val(),payroll_area:$('#filter_payroll_area').val(),process_type:$('#filter_process_type').val(),process_status:$('#filter_process_status').val(),run_mode:$('#filter_run_mode').val(),keyword:$('#filter_keyword').val()};}
function ppSet(s,v,t){var e=$(s);if(!v){e.val(null).trigger('change');return;}if(!e.find('option[value="'+v+'"]').length)e.append(new Option(t||v,v,true,true));e.val(v).trigger('change');}
function ppAjax(s,act,p,parent){$(s).select2({width:'100%',allowClear:true,placeholder:p,dropdownParent:parent||$(document.body),ajax:{url:'<?=base_admin();?>modul/payroll_process/payroll_process_action.php?act='+act,type:'POST',dataType:'json',delay:250,data:function(q){return{term:q.term||''};},processResults:function(d){return{results:d.results||[]};}}});}
function ppRow(item){item=item||{};var tr=$('<tr>');tr.append('<td><select class="form-control pp-emp"></select></td>');tr.append('<td><select class="form-control pp-struct"></select></td>');tr.append('<td><input type="number" class="form-control pp-work" value="'+(item.working_days||22)+'"></td>');tr.append('<td><input type="number" class="form-control pp-paid" value="'+(item.paid_days||22)+'"></td>');tr.append('<td><input type="number" class="form-control pp-abs" value="'+(item.absence_days||0)+'"></td>');tr.append('<td><input type="number" class="form-control pp-ot" value="'+(item.overtime_hours||0)+'"></td>');tr.append('<td><button type="button" class="btn btn-danger btn-xs btn-remove-employee"><i class="fa fa-trash"></i></button></td>');$('#pp_employee_body').append(tr);ppAjax(tr.find('.pp-emp'),'employee_search','Pilih Employee',$('#modal_payroll_process'));ppAjax(tr.find('.pp-struct'),'structure_search','Pilih Salary Structure',$('#modal_payroll_process'));if(item.employee_id)ppSet(tr.find('.pp-emp'),item.employee_id,item.employee_text);if(item.salary_structure_id)ppSet(tr.find('.pp-struct'),item.salary_structure_id,item.structure_text);ppSummary();}
function ppCollect(){var arr=[];$('#pp_employee_body tr').each(function(){arr.push({employee_id:$(this).find('.pp-emp').val()||'',salary_structure_id:$(this).find('.pp-struct').val()||'',working_days:$(this).find('.pp-work').val()||0,paid_days:$(this).find('.pp-paid').val()||0,absence_days:$(this).find('.pp-abs').val()||0,overtime_hours:$(this).find('.pp-ot').val()||0});});return arr;}
function ppSummary(){var arr=ppCollect(),days=0;arr.forEach(function(x){days+=parseFloat(x.paid_days||0)||0;});$('#pp_emp_count').text(arr.length);$('#pp_paid_days').text(days);}
function ppReset(title){$('#form_payroll_process')[0].reset();$('#pp_id,#employee_json').val('');$('#pp_employee_body').empty();$('#period_year').val('<?=date('Y');?>');$('#period_month').val('<?=date('n');?>');$('#period_from').val('<?=$defaultFrom;?>');$('#period_to,#pay_date').val('<?=$defaultTo;?>');$('#payroll_area').val('MONTHLY').trigger('change');$('#process_type').val('REGULAR').trigger('change');$('#run_mode').val('SIMULATION').trigger('change');$('#control_record_status').val('OPEN').trigger('change');$('#process_status').val('DRAFT').trigger('change');$('#currency').val('IDR').trigger('change');$('#modal_payroll_process .modal-title').text(title||'Create Payroll Run');ppRow();}
$(function(){if($.fn.datepicker){$('.pp-date,.date-field').datepicker({format:'yyyy-mm-dd',autoclose:true,todayHighlight:true});}if($.fn.select2){$('#filter_payroll_area,#filter_process_type,#filter_process_status,#filter_run_mode,#payroll_area,#process_type,#run_mode,#control_record_status,#process_status,#currency').select2({width:'100%',allowClear:true});}
var dt=$('#dtb_payroll_process').DataTable({bProcessing:true,bServerSide:true,pageLength:25,dom:"<'row'<'col-sm-12'B>>"+"<'row'<'col-sm-6'l><'col-sm-6'f>>"+"<'row'<'col-sm-12'tr>>"+"<'row'<'col-sm-5'i><'col-sm-7'p>>",buttons:[{extend:'collection',text:<?=hr_js('common_export_data', 'Export Data');?>,buttons:['copyHtml5','excelHtml5','csvHtml5','pdfHtml5']}],columnDefs:[{targets:[0,1],orderable:false,searchable:false},{width:'42px',targets:0},{width:'150px',targets:1}],ajax:{url:'<?=base_admin();?>modul/payroll_process/payroll_process_data.php',type:'post',data:function(d){$.extend(d,ppFilters());},dataSrc:function(j){var k=j.kpi||{};$('#kpi_total').text(k.total||0);$('#kpi_calculated').text(k.calculated||0);$('#kpi_approved').text(k.approved||0);$('#kpi_posted').text(k.posted||0);$('#kpi_employees').text(k.employees||0);$('#kpi_net').text((k.net||0).toLocaleString('id-ID'));return j.data||[];},error:function(x){console.log(x.responseText);ppError('Data Payroll Process gagal dimuat.');}}});
$('#btn_open_pp').click(function(){ppReset('Create Payroll Run');$('#modal_payroll_process').modal({backdrop:'static',keyboard:false});});$('#btn_filter_pp').click(function(){dt.draw();});$('#filter_keyword').keyup(function(e){if(e.keyCode===13)dt.draw();});$('#btn_reset_pp').click(function(){$('#filter_tgl_awal').val('<?=$defaultFrom;?>');$('#filter_tgl_akhir').val('<?=$defaultTo;?>');$('#filter_payroll_area,#filter_process_type,#filter_process_status,#filter_run_mode').val(null).trigger('change');$('#filter_keyword').val('');dt.draw();});$('#btn_export_pp').click(function(){window.location='<?=base_admin();?>modul/payroll_process/payroll_process_action.php?act=export&'+$.param(ppFilters());});$('.hide_alert_notif').click(function(){$('.error_data_delete').hide();});$('#payroll_run_no').on('keyup change',function(){this.value=this.value.toUpperCase();});$('#btn_add_employee').click(function(){ppRow();});$(document).on('keyup change','.pp-work,.pp-paid,.pp-abs,.pp-ot,.pp-emp,.pp-struct',ppSummary);$(document).on('click','.btn-remove-employee',function(){$(this).closest('tr').remove();ppSummary();});
$(document).on('change','.pp-emp',function(){var tr=$(this).closest('tr'),id=$(this).val();if(!id)return;$.post('<?=base_admin();?>modul/payroll_process/payroll_process_action.php?act=employee_info',{employee_id:id},function(r){if(r.status==='good'&&r.salary_structure_id)ppSet(tr.find('.pp-struct'),r.salary_structure_id,r.salary_structure_text);},'json');});
$('#form_payroll_process').submit(function(e){e.preventDefault();$('#employee_json').val(JSON.stringify(ppCollect()));var b=$(this).find('button[type=submit]');b.prop('disabled',true).html('<i class="fa fa-spinner fa-spin"></i> Calculating...');$.post('<?=base_admin();?>modul/payroll_process/payroll_process_action.php?act=save',$(this).serialize(),function(r){b.prop('disabled',false).html('<i class="fa fa-calculator"></i> Save & Calculate');if(r.status==='good'){$('#modal_payroll_process').modal('hide');dt.draw(false);Swal.fire('Calculated','Payroll Process berhasil dihitung.','success');}else ppError(r.error_message);},'json').fail(function(x){b.prop('disabled',false).html('<i class="fa fa-calculator"></i> Save & Calculate');ppError(x.responseText);});});
$(document).on('click','.btn-pp-detail',function(){$.post('<?=base_admin();?>modul/payroll_process/payroll_process_action.php?act=detail',{id:$(this).data('id')},function(h){$('#pp_detail_body').html(h);$('#modal_pp_detail').modal('show');});});
$(document).on('click','.btn-pp-edit',function(){var id=$(this).data('id');$.post('<?=base_admin();?>modul/payroll_process/payroll_process_action.php?act=get',{id:id},function(r){if(r.status!=='good'){ppError(r.error_message);return;}ppReset('Edit Payroll Run');var h=r.data||{};Object.keys(h).forEach(function(k){var el=$('#'+k);if(el.length)el.val(h[k]);});$('#pp_id').val(h.id);$('#payroll_area,#process_type,#run_mode,#control_record_status,#process_status,#currency').trigger('change');$('#pp_employee_body').empty();(h.employees||[]).forEach(function(x){ppRow(x);});if(!h.employees||!h.employees.length)ppRow();$('#modal_payroll_process').modal({backdrop:'static',keyboard:false});},'json');});
$(document).on('click','.btn-pp-status',function(){var id=$(this).data('id'),status=$(this).data('status');$.post('<?=base_admin();?>modul/payroll_process/payroll_process_action.php?act=status',{id:id,status:status},function(r){if(r.status==='good'){dt.draw(false);Swal.fire('Updated','Status berhasil diubah.','success');}else ppError(r.error_message);},'json');});
$(document).on('click','.btn-pp-delete',function(){if($(this).is(':disabled'))return;var id=$(this).data('id'),no=$(this).data('no');Swal.fire({title:erpLang('confirm_delete_title','Delete Confirmation'),text:no,icon:'warning',showCancelButton:true,confirmButtonText:erpLang('common_delete','Delete'),cancelButtonText:erpLang('common_cancel','Cancel')}).then(function(x){if(!x.isConfirmed)return;$.post('<?=base_admin();?>modul/payroll_process/payroll_process_action.php?act=delete',{id:id},function(r){if(r.status==='good'){dt.draw(false);Swal.fire(erpLang('common_deleted','Deleted'),erpLang('common_deleted_message','Data deleted successfully.'),'success');}else ppError(r.error_message);},'json').fail(function(x){ppError(x.responseText);});});});
});
</script>
