<?php
if (!function_exists('hr_t')) {
  function hr_t($key, $fallback = '') { return lang_text($key, $fallback); }
}
if (!function_exists('hr_h')) {
  function hr_h($key, $fallback = '') { return htmlspecialchars((string) hr_t($key, $fallback), ENT_QUOTES, 'UTF-8'); }
}
if (!function_exists('hr_js')) {
  function hr_js($key, $fallback = '') { return json_encode(hr_t($key, $fallback), JSON_HEX_TAG | JSON_HEX_APOS | JSON_HEX_AMP | JSON_HEX_QUOT); }
}
if (session_status() === PHP_SESSION_NONE) session_start();
include "../../inc/config.php";
session_check_json();
function pp_json($s,$m='',$x=array()){header('Content-Type: application/json; charset=utf-8');$p=array('status'=>$s);if($m!=='')$p[$s==='good'?'message':'error_message']=$m;foreach($x as $k=>$v)$p[$k]=$v;echo json_encode($p);exit;}
function pp_h($v){return htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');}
function pp_p($k,$d=''){return isset($_POST[$k])?$_POST[$k]:$d;}
function pp_g($k,$d=''){return isset($_GET[$k])?$_GET[$k]:$d;}
function pp_c($v){return strtoupper(trim((string)$v));}
function pp_user(){return isset($_SESSION['username'])&&$_SESSION['username']!==''?$_SESSION['username']:'system';}
function pp_num($v){return is_numeric($v)?(float)$v:0;}
function pp_select2($rows,$id,$cb){$out=array();foreach($rows as $r)$out[]=array('id'=>$r->$id,'text'=>$cb($r));header('Content-Type: application/json; charset=utf-8');echo json_encode(array('results'=>$out));exit;}
function pp_row($id){global $db;return $db->fetch("SELECT * FROM erp_payroll_process WHERE id=? LIMIT 1",array((int)$id));}
function pp_rows($from,$to,$area,$type,$status,$mode,$kw){global $db;$w=" WHERE p.period_from<=? AND p.period_to>=? ";$p=array($to,$from);if($area!==''){$w.=" AND p.payroll_area=? ";$p[]=$area;}if($type!==''){$w.=" AND p.process_type=? ";$p[]=$type;}if($status!==''){$w.=" AND p.process_status=? ";$p[]=$status;}if($mode!==''){$w.=" AND p.run_mode=? ";$p[]=$mode;}if($kw!==''){$like='%'.$kw.'%';$w.=" AND (p.payroll_run_no LIKE ? OR p.posting_reference LIKE ? OR p.sap_reference LIKE ? OR p.remarks LIKE ?) ";array_push($p,$like,$like,$like,$like);}return $db->query("SELECT p.* FROM erp_payroll_process p $w ORDER BY p.period_year DESC,p.period_month DESC,p.payroll_run_no",$p);}
function pp_recalc($processId){global $db;$rows=$db->query("SELECT pe.*,s.base_salary_mid FROM erp_payroll_process_employee pe LEFT JOIN erp_salary_structure s ON s.id=pe.salary_structure_id WHERE pe.payroll_process_id=?",array($processId));foreach($rows as $pe){$db->delete('erp_payroll_process_result','payroll_employee_id',$pe->id);$items=$db->query("SELECT d.*,pc.component_name,pc.wage_type_code,pc.component_type FROM erp_salary_structure_detail d JOIN erp_payroll_component pc ON pc.component_code=d.component_code WHERE d.structure_id=? ORDER BY d.sequence_no,d.id",array((int)$pe->salary_structure_id));$earning=0;$deduct=0;$tax=0;$base=(float)$pe->base_salary_mid;foreach($items as $it){$amount=(float)$it->amount;$qty=1;if($it->calculation_method==='ATTENDANCE_BASED'){$qty=(float)$pe->paid_days;$amount=(float)$it->amount*$qty;}elseif($it->calculation_method==='OVERTIME_BASED'){$qty=(float)$pe->overtime_hours;$amount=($base/173)*$qty*1.5;}elseif($it->calculation_method==='PERCENTAGE'){$amount=$base*((float)$it->percentage_rate)/100;}elseif($it->calculation_method==='FORMULA' && $it->component_code==='PC-TAX-PPH21'){$amount=max(0,($base-4500000)*0.05);}if($it->component_type==='DEDUCTION')$deduct+=abs($amount);elseif($it->component_type==='TAX')$tax+=abs($amount);elseif(in_array($it->component_type,array('EARNING','BENEFIT'),true))$earning+=$amount;$db->insert('erp_payroll_process_result',array('payroll_process_id'=>$processId,'payroll_employee_id'=>$pe->id,'employee_id'=>$pe->employee_id,'component_code'=>$it->component_code,'component_name'=>$it->component_name,'wage_type_code'=>$it->wage_type_code,'component_type'=>$it->component_type,'calculation_method'=>$it->calculation_method,'base_amount'=>$base,'rate'=>$it->percentage_rate,'quantity'=>$qty,'amount'=>abs($amount),'currency'=>'IDR','taxable'=>$it->taxable,'payslip_display'=>$it->payslip_display,'sequence_no'=>$it->sequence_no,'formula_text'=>$it->formula_text));}$db->update('erp_payroll_process_employee',array('gross_pay'=>$earning,'total_earning'=>$earning,'total_deduction'=>$deduct,'tax_amount'=>$tax,'net_pay'=>$earning-$deduct-$tax,'process_status'=>'CALCULATED','error_message'=>null),'id',$pe->id);} $sum=$db->fetch("SELECT COUNT(*) total_employee,SUM(gross_pay) gross,SUM(total_deduction) deduction,SUM(tax_amount) tax,SUM(net_pay) net FROM erp_payroll_process_employee WHERE payroll_process_id=?",array($processId));$db->update('erp_payroll_process',array('total_employee'=>(int)$sum->total_employee,'total_gross'=>(float)$sum->gross,'total_deduction'=>(float)$sum->deduction,'total_tax'=>(float)$sum->tax,'total_net'=>(float)$sum->net,'process_status'=>'CALCULATED','updated_at'=>date('Y-m-d H:i:s')),'id',$processId);}
$act=isset($_GET['act'])?$_GET['act']:'';$username=pp_user();$areas=array('MONTHLY','DAILY','WEEKLY','CONTRACT','MANAGEMENT','ALL');$types=array('REGULAR','OFFCYCLE','THR','BONUS','FINAL_SETTLEMENT','CORRECTION');$modes=array('SIMULATION','LIVE');$controls=array('OPEN','RELEASED','LOCKED','EXITED');$stats=array('DRAFT','CALCULATED','APPROVED','POSTED','CANCELLED');
switch($act){
case 'employee_search':$t=trim(pp_p('term'));$like='%'.$t.'%';$rows=$db->query("SELECT id,employee_no,full_name,employee_group,payroll_area,pay_grade FROM erp_employee_master WHERE employment_status IN ('ACTIVE','PROBATION','CONTRACT') AND (?='' OR employee_no LIKE ? OR full_name LIKE ? OR pay_grade LIKE ?) ORDER BY employee_no LIMIT 40",array($t,$like,$like,$like));pp_select2($rows,'id',function($r){return $r->employee_no.' - '.$r->full_name.' ['.$r->employee_group.' / '.$r->payroll_area.' / '.$r->pay_grade.']';});
case 'structure_search':$t=trim(pp_p('term'));$like='%'.$t.'%';$rows=$db->query("SELECT id,structure_code,structure_name,pay_grade,employee_group,payroll_area FROM erp_salary_structure WHERE structure_status='ACTIVE' AND (?='' OR structure_code LIKE ? OR structure_name LIKE ? OR pay_grade LIKE ? OR employee_group LIKE ?) ORDER BY pay_grade,structure_code LIMIT 40",array($t,$like,$like,$like,$like));pp_select2($rows,'id',function($r){return $r->structure_code.' - '.$r->structure_name.' ['.$r->pay_grade.' / '.$r->employee_group.' / '.$r->payroll_area.']';});
case 'employee_info':$e=$db->fetch("SELECT * FROM erp_employee_master WHERE id=? LIMIT 1",array((int)pp_p('employee_id')));if(!$e)pp_json('error','Employee tidak ditemukan.');$s=$db->fetch("SELECT * FROM erp_salary_structure WHERE structure_status='ACTIVE' AND (pay_grade=? OR employee_group=? OR payroll_area=?) ORDER BY IF(pay_grade=?,0,1),IF(employee_group=?,0,1),id LIMIT 1",array($e->pay_grade,$e->employee_group,$e->payroll_area,$e->pay_grade,$e->employee_group));pp_json('good','',array('employee_no'=>$e->employee_no,'full_name'=>$e->full_name,'department_code'=>$e->department_code,'employee_group'=>$e->employee_group,'payroll_area'=>$e->payroll_area,'cost_center_code'=>$e->cost_center_code,'profit_center_code'=>$e->profit_center_code,'salary_structure_id'=>$s?$s->id:'','salary_structure_text'=>$s?($s->structure_code.' - '.$s->structure_name):''));
case 'get':$r=pp_row((int)pp_p('id'));if(!$r)pp_json('error','Payroll Process tidak ditemukan.');$d=(array)$r;$emps=$db->query("SELECT pe.*,s.structure_name FROM erp_payroll_process_employee pe LEFT JOIN erp_salary_structure s ON s.id=pe.salary_structure_id WHERE pe.payroll_process_id=? ORDER BY pe.employee_no",array((int)$r->id));$d['employees']=array();foreach($emps as $e)$d['employees'][]=(array)$e+array('employee_text'=>$e->employee_no.' - '.$e->full_name,'structure_text'=>$e->salary_structure_code.' - '.$e->structure_name);pp_json('good','',array('data'=>$d));
case 'save':$id=(int)pp_p('id');$no=pp_c(pp_p('payroll_run_no'));$year=(int)pp_p('period_year');$month=(int)pp_p('period_month');$area=pp_c(pp_p('payroll_area','MONTHLY'));$type=pp_c(pp_p('process_type','REGULAR'));$mode=pp_c(pp_p('run_mode','SIMULATION'));$control=pp_c(pp_p('control_record_status','OPEN'));$status=pp_c(pp_p('process_status','DRAFT'));if($no===''||!preg_match('/^[A-Z0-9_-]{4,30}$/',$no))pp_json('error','Payroll Run No wajib valid.');if($year<2000||$month<1||$month>12)pp_json('error','Period tidak valid.');if(!in_array($area,$areas,true)||!in_array($type,$types,true)||!in_array($mode,$modes,true)||!in_array($control,$controls,true)||!in_array($status,$stats,true))pp_json('error','Master process tidak valid.');$from=trim(pp_p('period_from'));$to=trim(pp_p('period_to'));$pay=trim(pp_p('pay_date'));if($from===''||$to===''||$pay===''||strtotime($to)<strtotime($from))pp_json('error','Tanggal periode/pay date tidak valid.');if($db->fetch("SELECT id FROM erp_payroll_process WHERE payroll_run_no=? AND id<>? LIMIT 1",array($no,$id)))pp_json('error','Payroll Run No sudah digunakan.');$emp=json_decode(pp_p('employee_json','[]'),true);if(!is_array($emp)||count($emp)<1)pp_json('error','Employee payroll wajib minimal 1.');
  $data=array('payroll_run_no'=>$no,'period_year'=>$year,'period_month'=>$month,'period_from'=>$from,'period_to'=>$to,'pay_date'=>$pay,'payroll_area'=>$area,'process_type'=>$type,'run_mode'=>$mode,'control_record_status'=>$control,'process_status'=>$status,'currency'=>pp_c(pp_p('currency','IDR')),'posting_reference'=>trim(pp_p('posting_reference')),'sap_reference'=>trim(pp_p('sap_reference')),'remarks'=>trim(pp_p('remarks')),'updated_by'=>$username,'updated_at'=>date('Y-m-d H:i:s'));
  if($id>0){if(!$db->fetch("SELECT id FROM erp_payroll_process WHERE id=? LIMIT 1",array($id)))pp_json('error','Payroll Process tidak ditemukan.');$ok=$db->update('erp_payroll_process',$data,'id',$id);}else{$data['created_by']=$username;$ok=$db->insert('erp_payroll_process',$data);$id=$db->last_insert_id();}if(!$ok)pp_json('error',$db->getErrorMessage()?:'Payroll Process gagal disimpan.');$db->delete('erp_payroll_process_employee','payroll_process_id',$id);
  foreach($emp as $x){$eid=(int)(isset($x['employee_id'])?$x['employee_id']:0);$sid=(int)(isset($x['salary_structure_id'])?$x['salary_structure_id']:0);$e=$db->fetch("SELECT * FROM erp_employee_master WHERE id=? LIMIT 1",array($eid));$s=$db->fetch("SELECT * FROM erp_salary_structure WHERE id=? AND structure_status='ACTIVE' LIMIT 1",array($sid));if(!$e||!$s)pp_json('error','Employee atau Salary Structure detail tidak valid.');$db->insert('erp_payroll_process_employee',array('payroll_process_id'=>$id,'employee_id'=>$e->id,'employee_no'=>$e->employee_no,'full_name'=>$e->full_name,'department_code'=>$e->department_code,'employee_group'=>$e->employee_group,'payroll_area'=>$e->payroll_area,'salary_structure_id'=>$s->id,'salary_structure_code'=>$s->structure_code,'cost_center_code'=>$e->cost_center_code,'profit_center_code'=>$e->profit_center_code,'working_days'=>pp_num(isset($x['working_days'])?$x['working_days']:22),'paid_days'=>pp_num(isset($x['paid_days'])?$x['paid_days']:22),'absence_days'=>pp_num(isset($x['absence_days'])?$x['absence_days']:0),'overtime_hours'=>pp_num(isset($x['overtime_hours'])?$x['overtime_hours']:0),'process_status'=>'DRAFT'));}pp_recalc($id);if(function_exists('simpan_log'))simpan_log('User '.$username.' menjalankan Payroll Process '.$no.' periode '.$year.'-'.$month.' pada '.date('Y-m-d H:i:s'),$username);pp_json('good','Payroll Process berhasil disimpan dan dihitung.',array('id'=>$id));
case 'status':$id=(int)pp_p('id');$status=pp_c(pp_p('status'));if(!in_array($status,$stats,true))pp_json('error','Status tidak valid.');$r=pp_row($id);if(!$r)pp_json('error','Payroll Process tidak ditemukan.');$data=array('process_status'=>$status,'updated_by'=>$username,'updated_at'=>date('Y-m-d H:i:s'));if($status==='APPROVED'){$data['approved_by']=$username;$data['approved_at']=date('Y-m-d H:i:s');}if($status==='POSTED'){$data['posted_by']=$username;$data['posted_at']=date('Y-m-d H:i:s');}$db->update('erp_payroll_process',$data,'id',$id);pp_json('good','Status berhasil diubah.');
case 'delete':$id=(int)pp_p('id');$r=pp_row($id);if(!$r)pp_json('error','Payroll Process tidak ditemukan.');if(in_array($r->process_status,array('APPROVED','POSTED'),true))pp_json('error','Payroll Process APPROVED/POSTED tidak bisa dihapus.');$db->delete('erp_payroll_process','id',$id);if($db->getErrorMessage())pp_json('error',$db->getErrorMessage());pp_json('good','Payroll Process berhasil dihapus.');
case 'detail':$r=pp_row((int)pp_p('id'));if(!$r){echo '<div class="alert alert-warning">Payroll Process tidak ditemukan.</div>';break;}$emps=$db->query("SELECT * FROM erp_payroll_process_employee WHERE payroll_process_id=? ORDER BY employee_no",array((int)$r->id));echo '<h3 style="margin-top:0">'.pp_h($r->payroll_run_no).' <small>'.pp_h($r->process_type.' / '.$r->run_mode).'</small></h3><span class="label label-primary">'.pp_h($r->payroll_area).'</span> <span class="label label-info">'.pp_h($r->control_record_status).'</span> <span class="label label-success">'.pp_h($r->process_status).'</span><hr><div class="row"><div class="col-sm-3"><b>'.hr_h('hr_period', 'Period').'</b><br>'.pp_h($r->period_from.' s/d '.$r->period_to).'</div><div class="col-sm-3"><b>Pay Date</b><br>'.pp_h($r->pay_date).'</div><div class="col-sm-3"><b>'.hr_h('hr_employee', 'Employee').'</b><br>'.(int)$r->total_employee.'</div><div class="col-sm-3"><b>'.hr_h('hr_net_pay', 'Net Pay').'</b><br>'.number_format((float)$r->total_net,2).'</div></div><hr><div class="table-responsive"><table class="table table-bordered table-condensed"><thead><tr><th>'.hr_h('hr_employee', 'Employee').'</th><th>Structure</th><th class="text-right">Gross</th><th class="text-right">'.hr_h('hr_deduction', 'Deduction').'</th><th class="text-right">Tax</th><th class="text-right">Net</th><th>'.hr_h('common_status', 'Status').'</th></tr></thead><tbody>';foreach($emps as $e){echo '<tr><td><b>'.pp_h($e->employee_no).'</b><br><small>'.pp_h($e->full_name).'</small></td><td>'.pp_h($e->salary_structure_code).'</td><td class="text-right">'.number_format((float)$e->gross_pay,2).'</td><td class="text-right">'.number_format((float)$e->total_deduction,2).'</td><td class="text-right">'.number_format((float)$e->tax_amount,2).'</td><td class="text-right"><b>'.number_format((float)$e->net_pay,2).'</b></td><td>'.pp_h($e->process_status).'</td></tr>';}$res=$db->query("SELECT employee_no,full_name,component_code,component_name,component_type,amount FROM erp_payroll_process_employee pe JOIN erp_payroll_process_result r ON r.payroll_employee_id=pe.id WHERE pe.payroll_process_id=? ORDER BY pe.employee_no,r.sequence_no",array((int)$r->id));echo '</tbody></table></div><h4>Payroll Result Component</h4><div class="table-responsive"><table class="table table-bordered table-condensed"><thead><tr><th>'.hr_h('hr_employee', 'Employee').'</th><th>Component</th><th>Type</th><th class="text-right">Amount</th></tr></thead><tbody>';foreach($res as $x){echo '<tr><td>'.pp_h($x->employee_no.' - '.$x->full_name).'</td><td>'.pp_h($x->component_code.' - '.$x->component_name).'</td><td>'.pp_h($x->component_type).'</td><td class="text-right">'.number_format((float)$x->amount,2).'</td></tr>';}echo '</tbody></table></div>';break;
case 'export':$initial=ob_get_level();ob_start();error_reporting(E_ALL & ~E_NOTICE & ~E_WARNING & ~E_DEPRECATED & ~E_USER_DEPRECATED);require_once "../../inc/lib/PHPExcel.php";require_once "../../inc/excel_style_helper.php";PHPExcel_Shared_File::setUseUploadTempDirectory(true);$from=pp_g('tgl_awal',date('Y-01-01'));$to=pp_g('tgl_akhir',date('Y-m-t'));$rows=pp_rows($from,$to,pp_g('payroll_area',''),pp_g('process_type',''),pp_g('process_status',''),pp_g('run_mode',''),pp_g('keyword',''));$excel=new PHPExcel();$sheet=$excel->setActiveSheetIndex(0);$sheet->setTitle(erp_export_sheet_title('Payroll Process'));$heads=array(erp_export_label("No"),erp_export_label("Run No"),erp_export_label("Period"),erp_export_label("Pay Date"),erp_export_label("Area"),erp_export_label("Type"),erp_export_label("Mode"),erp_export_label("Control"),erp_export_label("Status"),erp_export_label("Employee"),erp_export_label("Gross"),erp_export_label("Deduction"),erp_export_label("Tax"),erp_export_label("Net"),erp_export_label("Posting Ref"),erp_export_label("SAP Ref"),erp_export_label("Updated By"));foreach($heads as $i=>$h)$sheet->setCellValue(PHPExcel_Cell::stringFromColumnIndex($i).'4',$h);$rnum=5;$n=1;foreach($rows as $r){$vals=array($n++,$r->payroll_run_no,$r->period_from.' s/d '.$r->period_to,$r->pay_date,$r->payroll_area,$r->process_type,$r->run_mode,$r->control_record_status,$r->process_status,$r->total_employee,$r->total_gross,$r->total_deduction,$r->total_tax,$r->total_net,$r->posting_reference,$r->sap_reference,$r->updated_by?:$r->created_by);foreach($vals as $i=>$v)$sheet->setCellValue(PHPExcel_Cell::stringFromColumnIndex($i).$rnum,$v);$rnum++;}erpkb_excel_apply_standard_style($excel,array('sheet'=>$sheet,'title'=>erp_export_title('PAYROLL PROCESS REPORT'),'header_row'=>4,'first_data_row'=>5,'last_data_row'=>max(5,$rnum-1),'column_count'=>count($heads),'decimal_columns'=>array('K','L','M','N'),'numeric_columns'=>array('J'),'filters'=>array('Period'=>$from.' s/d '.$to,'Area'=>pp_g('payroll_area',erp_export_all_text()),'Status'=>pp_g('process_status',erp_export_all_text()))));$tmp=erpkb_excel_temp_file('payroll_process_');PHPExcel_IOFactory::createWriter($excel,'Excel2007')->save($tmp);$size=@filesize($tmp);$sig=@file_get_contents($tmp,false,null,0,2);if(!$size||$sig!=='PK'){@unlink($tmp);while(ob_get_level()>$initial)ob_end_clean();echo erp_t('export_excel_invalid_file','File Excel gagal dibuat dengan benar.');exit;}while(ob_get_level()>$initial)ob_end_clean();header('Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');header('Content-Disposition: attachment; filename="payroll_process_'.date('Ymd_His').'.xlsx"');header('Content-Length: '.$size);header('Cache-Control: max-age=0');header('Pragma: public');readfile($tmp);@unlink($tmp);exit;
default:pp_json('error','Action tidak dikenal.');
}
?>
