<?php
$workspaceUrl = uri_segment(1);
$workspaces = array(
  'order-master' => array('title'=>'Order Master','code'=>'SAP Project / Order Master','icon'=>'fa-folder-open','color'=>'blue','description'=>'Master order internal sebagai objek pengendalian biaya dan aktivitas.','tables'=>array('project'=>'Order / Project','sales_order'=>'Sales Order'),'links'=>array('sales-order'=>'Sales Order','production-order'=>'Production Order'),'capabilities'=>array('Internal order reference','Assignment to sales and production','Status and responsibility tracking')),
  'laporan-ng' => array('title'=>'Non-Good Report','code'=>'SAP QM Defect Analysis','icon'=>'fa-exclamation-circle','color'=>'red','description'=>'Analisis barang tidak sesuai dan tren defect produksi.','tables'=>array('data_ng'=>'Non-Good Data','ng'=>'NG Reference'),'links'=>array('quality-notification'=>'Quality Notification','capa'=>'CAPA'),'capabilities'=>array('Defect classification','Quantity and production reference','Trend and corrective action monitoring')),
  'sales-quotation' => array('title'=>'Sales Quotation','code'=>'SAP SD Quotation','icon'=>'fa-file-text-o','color'=>'aqua','description'=>'Penawaran penjualan sebelum Sales Order.','tables'=>array('sales_quotation'=>'Quotation','sales_quotation_detail'=>'Item Quotation'),'links'=>array('sales-order'=>'Sales Order','master-customer'=>'Customer Master'),'capabilities'=>array('Quotation header dan item','Masa berlaku penawaran','Harga, kurs, pajak, dan payment term')),
  'down-payment-invoice' => array('title'=>'Down Payment Invoice','code'=>'SAP SD / FI-AR Down Payment','icon'=>'fa-credit-card','color'=>'green','description'=>'Invoice uang muka pelanggan yang dibuat dari Sales Order sebelum pengiriman barang.','tables'=>array('sales_order'=>'Sales Order','sales_invoice'=>'Billing Document','jurnal_header'=>'Journal Header'),'links'=>array('sales-order'=>'Sales Order','sales-invoice'=>'Sales Invoice','billing-history'=>'Billing History'),'capabilities'=>array('Referensi Sales Order tanpa Surat Jalan','Posting uang muka/piutang sesuai kontrol akuntansi','Monitoring saldo uang muka sampai final invoice')),
  'credit-debit-memo' => array('title'=>'Credit / Debit Memo','code'=>'SAP SD Billing Adjustment','icon'=>'fa-adjust','color'=>'yellow','description'=>'Dokumen koreksi nilai billing untuk penambahan tagihan atau pengurangan tagihan pelanggan.','tables'=>array('sales_invoice'=>'Sales Invoice','sales_invoice_detail'=>'Invoice Item','jurnal_header'=>'Journal Header'),'links'=>array('sales-invoice'=>'Sales Invoice','billing-history'=>'Billing History','sales-return'=>'Sales Return'),'capabilities'=>array('Referensi invoice asal atau approved adjustment','Credit memo untuk pengurang piutang','Debit memo untuk tambahan tagihan dan pajak')),
  'proforma-invoice' => array('title'=>'Proforma Invoice','code'=>'SAP SD Proforma Billing','icon'=>'fa-file-text-o','color'=>'aqua','description'=>'Dokumen invoice sementara/non-accounting untuk kebutuhan penawaran, ekspor, atau administrasi sebelum billing final.','tables'=>array('sales_order'=>'Sales Order','sales_quotation'=>'Sales Quotation','sales_invoice'=>'Billing Document'),'links'=>array('sales-order'=>'Sales Order','sales-quotation'=>'Sales Quotation','sales-invoice'=>'Sales Invoice'),'capabilities'=>array('Tidak posting jurnal dan piutang','Bisa dibuat dari Sales Order atau Quotation','Referensi sebelum delivery dan invoice final')),
  'sales-return' => array('title'=>'Sales Return','code'=>'SAP SD Returns','icon'=>'fa-reply','color'=>'red','description'=>'Pengelolaan retur pelanggan dan dampaknya ke stok serta keuangan.','tables'=>array('sales_invoice'=>'Sales Invoice','v_stock_outgoing'=>'Stock Outgoing'),'links'=>array('sales-invoice'=>'Sales Invoice','stock-outgoing'=>'Stock Outgoing'),'capabilities'=>array('Referensi invoice asal','Penerimaan barang retur','Credit memo dan reversal stok')),
  'rfq' => array('title'=>'Request for Quotation','code'=>'SAP MM RFQ','icon'=>'fa-envelope-o','color'=>'yellow','description'=>'Permintaan penawaran kepada pemasok sebelum Purchase Order.','tables'=>array('roin'=>'Purchase Request','pemasok'=>'Vendor'),'links'=>array('pr'=>'Purchase Request','purchase-order'=>'Purchase Order'),'capabilities'=>array('Undangan beberapa vendor','Perbandingan harga dan lead time','Penetapan vendor terpilih')),
  'vendor-evaluation' => array('title'=>'Vendor Evaluation','code'=>'SAP MM Vendor Evaluation','icon'=>'fa-star','color'=>'yellow','description'=>'Penilaian vendor berdasarkan harga, mutu, pengiriman, dan layanan.','tables'=>array('pemasok'=>'Vendor','po'=>'Purchase Order'),'links'=>array('pemasok'=>'Vendor Master','purchase-order'=>'Purchase Order'),'capabilities'=>array('Scorecard vendor','Riwayat ketepatan pengiriman','Evaluasi kualitas pemasok')),
  'picking-pengeluaran' => array('title'=>'Outbound Picking','code'=>'SAP WM Picking','icon'=>'fa-list-alt','color'=>'aqua','description'=>'Persiapan dan pengambilan barang untuk pengeluaran atau pengiriman.','tables'=>array('pengeluaran_temp'=>'Picking Draft','pengeluaran'=>'Goods Issue','packing_list'=>'Packing List'),'links'=>array('pengeluaran-hamparan'=>'Goods Issue','packing-list'=>'Packing List'),'capabilities'=>array('Picking list per dokumen','Konfirmasi kuantitas dan lokasi','Serah terima ke packing dan goods issue')),
  'cash-bank' => array('title'=>'Cash and Bank Management','code'=>'SAP FI-BL','icon'=>'fa-bank','color'=>'green','description'=>'Cockpit kas, bank, penerimaan, pembayaran, dan rekonsiliasi.','tables'=>array('ref_bank'=>'Bank Master','jurnal_header'=>'Journal'),'links'=>array('master-bank'=>'Bank Master','jurnal-umum'=>'Jurnal Umum'),'capabilities'=>array('Kas masuk dan keluar','Mutasi rekening bank','Rekonsiliasi bank')),
  'accounts-payable' => array('title'=>'Accounts Payable','code'=>'SAP FI-AP','icon'=>'fa-money','color'=>'green','description'=>'Utang usaha pemasok dari invoice sampai pembayaran.','tables'=>array('pemasok'=>'Vendor','po'=>'Purchase Order','jurnal_header'=>'Journal'),'links'=>array('purchase-order'=>'Purchase Order','jurnal-umum'=>'Jurnal Umum'),'capabilities'=>array('Vendor invoice','Aging utang','Payment proposal dan pelunasan')),
  'accounts-receivable' => array('title'=>'Accounts Receivable','code'=>'SAP FI-AR','icon'=>'fa-credit-card','color'=>'green','description'=>'Piutang pelanggan dari invoice sampai penerimaan pembayaran.','tables'=>array('customer'=>'Customer','sales_invoice'=>'Sales Invoice','jurnal_header'=>'Journal'),'links'=>array('sales-invoice'=>'Sales Invoice','master-customer'=>'Customer Master'),'capabilities'=>array('Customer invoice','Aging piutang','Penerimaan dan alokasi pembayaran')),
  'tax-management' => array('title'=>'Tax Management','code'=>'SAP FI Tax','icon'=>'fa-percent','color'=>'green','description'=>'Pengelolaan pajak masukan, keluaran, dan pelaporan.','tables'=>array('pajak'=>'Tax','ceisapajakbb'=>'Pajak Bahan Baku','ceisapajakbj'=>'Pajak Barang Jadi'),'links'=>array('jurnal-umum'=>'Jurnal Umum','dokumen-pabean'=>'Dokumen Pabean'),'capabilities'=>array('Kode pajak','Rekonsiliasi pajak masukan/keluaran','Pelaporan pajak periodik')),
  'production-order' => array('title'=>'Production Order','code'=>'SAP PP Production Order','icon'=>'fa-industry','color'=>'purple','description'=>'Perintah produksi dari perencanaan sampai konfirmasi hasil.','tables'=>array('produksi'=>'Production','produksi_detail'=>'Production Item','bom'=>'BOM'),'links'=>array('mrp'=>'MRP','lp-barang-jadi'=>'Laporan Produksi'),'capabilities'=>array('Release production order','Material issue dan confirmation','Yield, scrap, dan variance')),
  'routing' => array('title'=>'Routing','code'=>'SAP PP Routing','icon'=>'fa-random','color'=>'purple','description'=>'Urutan operasi, work center, dan waktu standar produksi.','tables'=>array('manufactur'=>'Work Center','bom'=>'BOM'),'links'=>array('work-center'=>'Work Center','bom'=>'BOM'),'capabilities'=>array('Operation sequence','Setup dan machine time','Work center assignment')),
  'production-forecast' => array('title'=>'Demand Forecast','code'=>'SAP PP Demand Management','icon'=>'fa-line-chart','color'=>'purple','description'=>'Forecast kebutuhan untuk perencanaan produksi dan material.','tables'=>array('sales_order'=>'Sales Order','mrp'=>'MRP'),'links'=>array('sales-order'=>'Sales Order','mrp'=>'MRP'),'capabilities'=>array('Forecast per material/periode','Sales and operation planning','Transfer demand ke MRP')),
  'forecast' => array('title'=>'Forecast','code'=>'SAP PP Demand Management','icon'=>'fa-line-chart','color'=>'purple','description'=>'Perencanaan demand sebagai dasar MRP dan production planning.','tables'=>array('sales_order'=>'Sales Order','mrp'=>'MRP'),'links'=>array('sales-order'=>'Sales Order','mrp'=>'MRP','production-order'=>'Production Order'),'capabilities'=>array('Forecast per material dan periode','Demand aggregation dari sales/order plan','Input utama untuk MRP dan schedule')),
  'demand-management' => array('title'=>'Demand Management','code'=>'SAP PP Demand Management','icon'=>'fa-area-chart','color'=>'purple','description'=>'Pengelolaan kebutuhan independen dari forecast, sales order, dan rencana penjualan sebagai input MRP.','tables'=>array('sales_order'=>'Sales Order','mrp'=>'MRP'),'links'=>array('forecast'=>'Forecast','mrp'=>'MRP','production-order'=>'Production Order'),'capabilities'=>array('Demand consolidation','Independent requirement per material/periode','Basis perencanaan MRP dan production schedule')),
  'capacity-planning' => array('title'=>'Capacity Planning','code'=>'SAP PP-CRP','icon'=>'fa-tasks','color'=>'purple','description'=>'Analisis beban dan kapasitas work center.','tables'=>array('manufactur'=>'Work Center','produksi'=>'Production'),'links'=>array('work-center'=>'Work Center','production-order'=>'Production Order'),'capabilities'=>array('Available capacity','Load profile','Overload alert dan leveling')),
  'material-requirement' => array('title'=>'Material Requirement','code'=>'SAP PP Material Requirement','icon'=>'fa-clipboard','color'=>'purple','description'=>'Kebutuhan material hasil BOM, MRP, atau request produksi untuk memastikan bahan siap sebelum order dijalankan.','tables'=>array('ro'=>'Material Request','mrp'=>'MRP','bom'=>'BOM'),'links'=>array('mrp'=>'MRP','bom'=>'BOM','production-order'=>'Production Order'),'capabilities'=>array('Requirement by material/order','Kebutuhan versus stock tersedia','Dasar material staging request')),
  'production-version' => array('title'=>'Production Version','code'=>'SAP PP Production Version','icon'=>'fa-code-fork','color'=>'purple','description'=>'Kombinasi material, BOM, routing, dan validity untuk menentukan versi proses produksi yang dipakai.','tables'=>array('barang'=>'Material','bom'=>'BOM','manufactur'=>'Routing / Work Center'),'links'=>array('bom'=>'BOM','routing'=>'Routing','production-order'=>'Production Order'),'capabilities'=>array('BOM and routing assignment','Validity date and lot size','Kontrol alternatif proses produksi')),
  'production-order-release' => array('title'=>'Production Order Release','code'=>'SAP PP Order Release','icon'=>'fa-unlock','color'=>'purple','description'=>'Kontrol release production order sebelum material staging, issue, confirmation, dan GR berjalan.','tables'=>array('production_order'=>'Production Order','production_order_material'=>'Material Requirement'),'links'=>array('production-order'=>'Production Order','production-order-monitoring'=>'Production Order Monitoring'),'capabilities'=>array('Release readiness check','Material availability check','Approval dan audit release order')),
  'material-staging-request' => array('title'=>'Material Staging Request','code'=>'SAP PP / WM Material Staging','icon'=>'fa-truck','color'=>'purple','description'=>'Permintaan penyiapan bahan dari PPIC/produksi ke warehouse sebelum Goods Issue 261.','tables'=>array('production_order'=>'Production Order','production_order_material'=>'Material Requirement','stock_layer'=>'Stock Layer'),'links'=>array('production-order'=>'Production Order','issue-to-production'=>'Issue to Production','stock-pemasukan'=>'Stock Overview'),'capabilities'=>array('Request bahan per order','Cek batch/lot dan dokumen BC','Jembatan sebelum issue to production')),
  'production-schedule' => array('title'=>'Production Schedule','code'=>'SAP PP Scheduling','icon'=>'fa-calendar','color'=>'purple','description'=>'Penjadwalan order produksi berdasarkan tanggal mulai, selesai, prioritas, dan kapasitas work center.','tables'=>array('production_order'=>'Production Order','production_order_operation'=>'Operations'),'links'=>array('production-order'=>'Production Order','routing'=>'Routing'),'capabilities'=>array('Schedule by order and operation','Priority dan due date visibility','Basis dispatching ke shop floor')),
  'production-order-monitoring' => array('title'=>'Production Order Monitoring','code'=>'SAP PP Order Monitoring','icon'=>'fa-dashboard','color'=>'purple','description'=>'Monitoring status production order dari created, released, material issued, confirmed, GR posted, sampai closed.','tables'=>array('production_order'=>'Production Order','production_order_material'=>'Material Requirement','production_order_goods_movement'=>'Goods Movement'),'links'=>array('production-order'=>'Production Order','issue-to-production'=>'Issue to Production','incoming-terima'=>'GR from Production Order'),'capabilities'=>array('Progress order end-to-end','Exception material, confirmation, dan GR','Status received quantity dan remaining order')),
  'production-monitoring' => array('title'=>'Production Monitoring','code'=>'SAP PP Shop Floor Control','icon'=>'fa-dashboard','color'=>'purple','description'=>'Monitoring progres Production Order dari release, material issue, confirmation, sampai closing.','tables'=>array('production_order'=>'Production Order','production_order_material'=>'Material Requirement','production_order_goods_movement'=>'Goods Movement'),'links'=>array('production-order'=>'Production Order','issue-to-production'=>'Issue to Production','material-documents'=>'Material Documents'),'capabilities'=>array('Progress order dan status exception','Pemakaian material versus requirement','Trace goods movement produksi')),
  'material-availability' => array('title'=>'Material Availability','code'=>'SAP PP Availability Check','icon'=>'fa-check-circle','color'=>'purple','description'=>'Monitoring ketersediaan bahan terhadap kebutuhan production order, termasuk stock layer, batch/lot, dan dokumen BC.','tables'=>array('production_order_material'=>'Material Requirement','stock_layer'=>'Stock Layer','barang'=>'Material'),'links'=>array('material-requirement'=>'Material Requirement','stock-pemasukan'=>'Stock Overview','material-staging-request'=>'Material Staging Request'),'capabilities'=>array('Requirement versus available stock','Shortage dan exception list','Cek lokasi, stock type, lot, dan dokumen pabean')),
  'wip-monitoring' => array('title'=>'WIP Monitoring','code'=>'SAP PP WIP Monitoring','icon'=>'fa-hourglass-half','color'=>'purple','description'=>'Monitoring order yang masih dalam proses, material sudah issue, confirmation parsial, dan hasil produksi belum lengkap diterima.','tables'=>array('production_order'=>'Production Order','production_order_confirmation'=>'Confirmation','production_order_goods_movement'=>'Goods Movement'),'links'=>array('production-order-monitoring'=>'Production Order Monitoring','production-confirmation'=>'Production Confirmation','incoming-terima'=>'GR from Production Order'),'capabilities'=>array('WIP by production order','Issued material versus received output','Outstanding confirmation dan GR')),
  'production-traceability' => array('title'=>'Production Traceability','code'=>'SAP Batch / Genealogy Trace','icon'=>'fa-random','color'=>'purple','description'=>'Lacak barang jadi atau setengah jadi sampai bahan baku asal, lot/batch, BPB, aju, dan dokumen pabean.','tables'=>array('erp_gr_production_trace'=>'Production Trace','erp_issue_production_trace'=>'Issue Trace','stock_layer'=>'Stock Layer'),'links'=>array('stock-barang-jadi-produksi'=>'Stock Barang Jadi Produksi','stock-barang-setengah-jadi-produksi'=>'Stock Barang Setengah Jadi Produksi','material-documents'=>'Material Documents'),'capabilities'=>array('Multi-level production genealogy','Trace raw material dan dokumen BC','Audit trail BJ/BSJ sampai bahan asal')),
  'production-reports' => array('title'=>'Production Reports','code'=>'SAP PP Reports','icon'=>'fa-file-text-o','color'=>'purple','description'=>'Kumpulan laporan produksi: order history, material consumption, output, WIP, dan variance.','tables'=>array('production_order'=>'Production Order','production_order_goods_movement'=>'Goods Movement','erp_gr_production_trace'=>'Trace'),'links'=>array('production-order-monitoring'=>'Production Order Monitoring','wip-monitoring'=>'WIP Monitoring','production-traceability'=>'Production Traceability'),'capabilities'=>array('Production order history','Material consumption and output report','WIP, traceability, dan variance report')),
  'production-confirmation' => array('title'=>'Production Confirmation','code'=>'SAP PP Confirmation','icon'=>'fa-check-square-o','color'=>'purple','description'=>'Konfirmasi pelaksanaan produksi setelah material di-issue ke production order.','tables'=>array('production_order'=>'Production Order','production_order_confirmation'=>'Confirmation','production_order_operation'=>'Operations'),'links'=>array('production-order'=>'Production Order','issue-to-production'=>'Issue to Production','incoming-terima'=>'GR from Production Order'),'capabilities'=>array('Konfirmasi yield, scrap, dan rework','Catat operation, work center, dan waktu kerja','Basis penerimaan hasil produksi ke gudang')),
  'work-center-dashboard' => array('title'=>'Work Center Dashboard','code'=>'SAP PP Shop Floor Dashboard','icon'=>'fa-desktop','color'=>'purple','description'=>'Dashboard shop floor untuk melihat order dan operasi yang sedang berjalan per work center.','tables'=>array('production_order'=>'Production Order','production_order_operation'=>'Operations','production_order_confirmation'=>'Confirmation'),'links'=>array('production-confirmation'=>'Production Confirmation','operation-queue'=>'Operation Queue','output-monitoring'=>'Output Monitoring'),'capabilities'=>array('Order aktif per work center','Status operasi dan shift','Basis eksekusi operator produksi')),
  'input-downtime' => array('title'=>'Input Downtime','code'=>'SAP PP Downtime Recording','icon'=>'fa-clock-o','color'=>'purple','description'=>'Pencatatan downtime mesin atau work center untuk analisa performance produksi.','tables'=>array('production_order'=>'Production Order','production_order_operation'=>'Operations','production_order_confirmation'=>'Confirmation'),'links'=>array('production-confirmation'=>'Production Confirmation','work-center-dashboard'=>'Work Center Dashboard'),'capabilities'=>array('Catat downtime per order/work center','Reason downtime dan durasi','Basis analisa OEE dan loss time')),
  'production-activity-log' => array('title'=>'Production Activity Log','code'=>'SAP PP Activity Log','icon'=>'fa-list-alt','color'=>'purple','description'=>'Log aktivitas produksi harian untuk operator, shift, operasi, dan catatan kejadian shop floor.','tables'=>array('production_order'=>'Production Order','production_order_confirmation'=>'Confirmation','log_aktifitas'=>'Activity Log'),'links'=>array('production-confirmation'=>'Production Confirmation','my-production-orders'=>'My Production Orders'),'capabilities'=>array('Catatan aktivitas per shift','Audit trail proses produksi','Referensi kejadian produksi')),
  'my-production-orders' => array('title'=>'My Production Orders','code'=>'SAP PP Operator Order List','icon'=>'fa-tasks','color'=>'purple','description'=>'Daftar production order yang relevan untuk tim produksi/operator berdasarkan status release dan execution readiness.','tables'=>array('production_order'=>'Production Order','production_order_material'=>'Material Requirement','production_order_confirmation'=>'Confirmation'),'links'=>array('production-confirmation'=>'Production Confirmation','operation-queue'=>'Operation Queue','production-order-monitoring'=>'Production Order Monitoring'),'capabilities'=>array('Order siap proses','Status material issue dan confirmation','Akses cepat ke confirmation')),
  'operation-queue' => array('title'=>'Operation Queue','code'=>'SAP PP Operation Queue','icon'=>'fa-list-ol','color'=>'purple','description'=>'Antrian operasi produksi per work center, prioritas, tanggal mulai, dan status eksekusi.','tables'=>array('production_order'=>'Production Order','production_order_operation'=>'Operations','production_order_confirmation'=>'Confirmation'),'links'=>array('work-center-dashboard'=>'Work Center Dashboard','production-confirmation'=>'Production Confirmation'),'capabilities'=>array('Queue operasi per work center','Prioritas dan due date','Status belum mulai, proses, selesai')),
  'output-monitoring' => array('title'=>'Output Monitoring','code'=>'SAP PP Output Monitoring','icon'=>'fa-line-chart','color'=>'purple','description'=>'Monitoring hasil produksi dari confirmation sampai GR hasil produksi ke warehouse.','tables'=>array('production_order'=>'Production Order','production_order_confirmation'=>'Confirmation','erp_gr_production'=>'GR Production'),'links'=>array('production-confirmation'=>'Production Confirmation','incoming-terima'=>'GR from Production Order','stock-barang-jadi-produksi'=>'Stock Barang Jadi Produksi'),'capabilities'=>array('Yield, scrap, dan rework','Confirmed versus received quantity','Status output yang belum GR')),
  'ppic-production-confirmation' => array('title'=>'Production Confirmation','code'=>'SAP PP Confirmation','icon'=>'fa-check-square-o','color'=>'purple','description'=>'Shortcut PPIC untuk memonitor dan menyiapkan proses confirmation production order.','tables'=>array('production_order'=>'Production Order','production_order_confirmation'=>'Confirmation','production_order_goods_movement'=>'Goods Movement'),'links'=>array('production-order'=>'Production Order','production-monitoring'=>'Production Monitoring','production-confirmation'=>'Production Confirmation'),'capabilities'=>array('Monitoring order yang siap dikonfirmasi','Validasi material issue sebelum confirmation','Kontrol yield, scrap, dan remaining quantity')),
  'incoming-inspection' => array('title'=>'Incoming Inspection','code'=>'SAP QM Inspection Lot 01','icon'=>'fa-search','color'=>'red','description'=>'Pemeriksaan mutu bahan yang diterima dari pemasok.','tables'=>array('incoming_terima'=>'Goods Receipt','pemasok'=>'Vendor','data_ng'=>'Nonconformity'),'links'=>array('incoming-terima'=>'Goods Receipt','vendor-evaluation'=>'Vendor Evaluation'),'capabilities'=>array('Inspection lot','Sampling dan result recording','Usage decision')),
  'gr-without-po' => array('title'=>'GR Without Purchase Order','code'=>'SAP MM Goods Receipt without PO','icon'=>'fa-download','color'=>'yellow','description'=>'Penerimaan barang tanpa referensi Purchase Order dengan reason code dan persetujuan yang terkontrol.','tables'=>array('pemasukan'=>'Goods Receipt','pemasok'=>'Vendor','detail_transaksi'=>'Material Movement'),'links'=>array('pemasukan-hamparan'=>'GR for Purchase Order','approval-center'=>'Approval Center'),'capabilities'=>array('Reason code penerimaan non-PO','Persetujuan sebelum posting','Plant, storage location, stock type, dan dokumen pabean')),
  'gr-blocked-stock' => array('title'=>'GR Blocked Stock','code'=>'SAP MM Movement 103','icon'=>'fa-lock','color'=>'red','description'=>'Penerimaan awal ke GR blocked stock sebelum barang dilepas menjadi persediaan tersedia.','tables'=>array('pemasukan'=>'Goods Receipt','detail_transaksi'=>'Material Movement','stock_layer'=>'Stock Layer'),'links'=>array('pemasukan-hamparan'=>'GR for Purchase Order','incoming-inspection'=>'Incoming Inspection'),'capabilities'=>array('Movement type 103','Tidak langsung menambah unrestricted stock','Referensi PO, vendor, lot, dan dokumen pabean')),
  'release-gr-blocked-stock' => array('title'=>'Release GR Blocked Stock','code'=>'SAP MM Movement 105','icon'=>'fa-unlock','color'=>'green','description'=>'Pelepasan barang dari GR blocked stock setelah dokumen dan pemeriksaan penerimaan dinyatakan lengkap.','tables'=>array('detail_transaksi'=>'Material Movement','stock_layer'=>'Stock Layer','data_ng'=>'Quality Result'),'links'=>array('gr-blocked-stock'=>'GR Blocked Stock','incoming-inspection'=>'Incoming Inspection'),'capabilities'=>array('Movement type 105','Release penuh atau parsial','Jejak pemeriksa, posting date, dan referensi pabean')),
  'return-to-vendor' => array('title'=>'Return to Vendor','code'=>'SAP MM Return Delivery','icon'=>'fa-reply','color'=>'red','description'=>'Pengembalian barang kepada vendor dengan referensi Goods Receipt dan alasan retur.','tables'=>array('pemasukan'=>'Goods Receipt','pemasok'=>'Vendor','detail_transaksi'=>'Material Movement'),'links'=>array('pemasukan-hamparan'=>'Goods Receipt','quality-notification'=>'Quality Notification / NCR'),'capabilities'=>array('Referensi material document asal','Return quantity dan reason code','Pengurangan stock layer serta dokumen kepabeanan pengeluaran')),
  'material-documents' => array('title'=>'Material Documents','code'=>'SAP MM Material Document','icon'=>'fa-file-text-o','color'=>'aqua','description'=>'Riwayat dokumen material untuk seluruh posting Goods Receipt, reversal, release, dan return.','tables'=>array('detail_transaksi'=>'Material Movement','pemasukan'=>'Goods Receipt','stock_layer'=>'Stock Layer'),'links'=>array('pemasukan-hamparan'=>'GR for Purchase Order','stock-pemasukan'=>'Stock Overview'),'capabilities'=>array('Nomor dan tahun material document','Movement type, document date, dan posting date','Referensi PO, material, plant, lokasi, user, dan reversal')),
  'gr-reversal' => array('title'=>'Goods Receipt Reversal','code'=>'SAP MM Movement 102','icon'=>'fa-undo','color'=>'yellow','description'=>'Pembatalan Goods Receipt berdasarkan material document asal dengan validasi stok yang sudah digunakan.','tables'=>array('pemasukan'=>'Goods Receipt','detail_transaksi'=>'Material Movement','stock_layer'=>'Stock Layer'),'links'=>array('pemasukan-hamparan'=>'Goods Receipt','material-documents'=>'Material Documents'),'capabilities'=>array('Movement type 102','Alasan reversal wajib','Referensi baris asal dan pencegahan reversal jika stok telah dikonsumsi')),
  'customs-receiving-monitor' => array('title'=>'Customs Receiving Monitor','code'=>'Indonesia Customs / CEISA Reconciliation','icon'=>'fa-file-text','color'=>'purple','description'=>'Monitoring keterkaitan Goods Receipt dengan dokumen kepabeanan dan hasil impor CEISA.','tables'=>array('pemasukan'=>'Goods Receipt','pemasukan_detail'=>'GR Item','import_pemasukan_temp'=>'CEISA Import'),'links'=>array('dokumen-pabean'=>'Dokumen Pabean','laporan-pemasukan-per-jenis-dokumen-pabean'=>'Laporan Pemasukan'),'capabilities'=>array('Rekonsiliasi nomor aju dan nomor pendaftaran','Pencocokan item, kuantitas, nilai, berat, dan valuta','Status lengkap, selisih, belum terhubung, dan reversed')),
  'process-inspection' => array('title'=>'In-Process Inspection','code'=>'SAP QM Inspection Lot 03','icon'=>'fa-search-plus','color'=>'red','description'=>'Pemeriksaan kualitas selama proses produksi.','tables'=>array('produksi'=>'Production','data_ng'=>'Nonconformity'),'links'=>array('production-order'=>'Production Order','laporan-ng'=>'Laporan NG'),'capabilities'=>array('Inspection point','Process result recording','Hold dan release process')),
  'final-inspection' => array('title'=>'Final Inspection','code'=>'SAP QM Inspection Lot 04','icon'=>'fa-check-square-o','color'=>'red','description'=>'Pemeriksaan hasil akhir sebelum barang dipindahkan atau dikirim.','tables'=>array('brgjadi'=>'Finished Goods','data_ng'=>'Nonconformity'),'links'=>array('lp-barang-jadi'=>'Laporan Produksi','packing-list'=>'Packing List'),'capabilities'=>array('Final result recording','Release finished goods','Certificate of analysis')),
  'quality-dashboard' => array('title'=>'Quality Dashboard','code'=>'SAP QM Overview','icon'=>'fa-dashboard','color'=>'red','description'=>'Dashboard kualitas untuk memantau inspection, NCR, CAPA, dan tren defect.','tables'=>array('data_ng'=>'Nonconformity','ng'=>'NG Reference','log_aktifitas'=>'Audit Log'),'links'=>array('incoming-inspection'=>'Incoming Inspection','quality-notification'=>'Quality Notification','capa'=>'CAPA'),'capabilities'=>array('KPI kualitas lintas proses','Open NCR dan CAPA overdue','Trend defect by material, vendor, dan order')),
  'inspection-lot' => array('title'=>'Inspection Lot','code'=>'SAP QM Inspection Lot','icon'=>'fa-clipboard','color'=>'red','description'=>'Wadah pemeriksaan mutu untuk penerimaan, proses produksi, dan final inspection.','tables'=>array('incoming_terima'=>'Goods Receipt','produksi'=>'Production','data_ng'=>'Nonconformity'),'links'=>array('incoming-inspection'=>'Incoming Inspection','process-inspection'=>'In-Process Inspection','final-inspection'=>'Final Inspection'),'capabilities'=>array('Generate inspection lot dari GR atau production order','Sampling plan dan result recording','Hubungkan hasil inspeksi ke usage decision')),
  'usage-decision' => array('title'=>'Usage Decision','code'=>'SAP QM UD','icon'=>'fa-gavel','color'=>'red','description'=>'Keputusan akhir hasil inspeksi: accept, reject, rework, return, atau scrap.','tables'=>array('data_ng'=>'Nonconformity','detail_transaksi'=>'Material Movement','stock_layer'=>'Stock Layer'),'links'=>array('inspection-lot'=>'Inspection Lot','return-to-vendor'=>'Return to Vendor','scrap-issue'=>'Scrap Issue'),'capabilities'=>array('Keputusan release atau reject stock','Trigger return, scrap, atau rework','Audit trail keputusan kualitas')),
  'quality-notification' => array('title'=>'Quality Notification / NCR','code'=>'SAP QM Notification','icon'=>'fa-exclamation-triangle','color'=>'red','description'=>'Pencatatan ketidaksesuaian, akar masalah, dan disposisi.','tables'=>array('data_ng'=>'Nonconformity','ng'=>'NG Reference'),'links'=>array('laporan-ng'=>'Laporan NG','laporan-scrap'=>'Laporan Scrap'),'capabilities'=>array('NCR classification','Root cause analysis','Disposition and responsibility')),
  'capa' => array('title'=>'CAPA','code'=>'SAP QM Corrective Action','icon'=>'fa-wrench','color'=>'red','description'=>'Corrective and Preventive Action untuk temuan kualitas.','tables'=>array('data_ng'=>'Nonconformity','log_aktifitas'=>'Audit Log'),'links'=>array('quality-notification'=>'Quality Notification','log-aktifitas'=>'Log Aktivitas'),'capabilities'=>array('Corrective action plan','Owner dan due date','Effectiveness verification')),
  'approval-center' => array('title'=>'Approval Center','code'=>'SAP Business Workflow','icon'=>'fa-check-circle','color'=>'blue','description'=>'Pusat persetujuan transaksi lintas fungsi.','tables'=>array('roin'=>'Purchase Request','po'=>'Purchase Order','sales_order'=>'Sales Order','jurnal_header'=>'Journal'),'links'=>array('pr'=>'Purchase Request','purchase-order'=>'Purchase Order'),'capabilities'=>array('Inbox approval','Approval level dan delegation','History, rejection reason, dan SLA')),
  'management-dashboard' => array('title'=>'Management Dashboard','code'=>'SAP Analytics Overview','icon'=>'fa-dashboard','color'=>'blue','description'=>'Ringkasan KPI lintas fungsi untuk manajemen.','tables'=>array('sales_order'=>'Sales Order','po'=>'Purchase Order','produksi'=>'Production','jurnal_header'=>'Journal'),'links'=>array('laporan-rugi-laba'=>'Laba Rugi','neraca'=>'Neraca'),'capabilities'=>array('Sales, procurement, stock, production KPI','Financial performance','Exception and approval monitoring')),
  'system-configuration' => array('title'=>'System Configuration','code'=>'SAP Basis Customizing','icon'=>'fa-cogs','color'=>'navy','description'=>'Pusat konfigurasi organisasi, referensi, dan parameter ERP.','tables'=>array('settings'=>'Settings','sys_users'=>'Users','sys_group_users'=>'Roles'),'links'=>array('data-user'=>'Data User','group-user'=>'Group User'),'capabilities'=>array('Company and organization settings','Number range and posting control','Integration and environment parameters')),
  'outbound-delivery' => array('title'=>'Outbound Delivery','code'=>'SAP SD Delivery','icon'=>'fa-truck','color'=>'aqua','description'=>'Persiapan pengiriman dari sales order sebelum goods issue dan invoice.','tables'=>array('sales_order'=>'Sales Order','packing_list'=>'Packing List','surat_jalan'=>'Surat Jalan'),'links'=>array('sales-order'=>'Sales Order','packing-list'=>'Packing List','stock-outgoing'=>'Stock Outgoing'),'capabilities'=>array('Delivery reference dari sales order','Picking, packing, dan shipment readiness','Basis goods issue dan billing')),
  'cash-journal' => array('title'=>'Cash Journal','code'=>'SAP FI Cash Journal','icon'=>'fa-book','color'=>'green','description'=>'Pencatatan transaksi kas kecil dan kas operasional.','tables'=>array('jurnal_header'=>'Journal Header','jurnal_detail'=>'Journal Detail'),'links'=>array('jurnal-umum'=>'Jurnal Umum','buku-ledger'=>'Buku Besar'),'capabilities'=>array('Kas masuk dan kas keluar','Posting jurnal otomatis','Kontrol saldo kas per periode')),
  'bank-receipt' => array('title'=>'Bank Receipt','code'=>'SAP FI Incoming Bank','icon'=>'fa-download','color'=>'green','description'=>'Penerimaan dana melalui rekening bank dan alokasi ke piutang atau akun lain.','tables'=>array('jurnal_header'=>'Journal Header','sales_invoice'=>'Sales Invoice','ref_bank'=>'Bank Master'),'links'=>array('incoming-payment'=>'Incoming Payment','master-bank'=>'Bank Master'),'capabilities'=>array('Penerimaan customer dan non-customer','Alokasi invoice atau akun GL','Jejak bukti transfer bank')),
  'bank-payment' => array('title'=>'Bank Payment','code'=>'SAP FI Outgoing Bank','icon'=>'fa-upload','color'=>'green','description'=>'Pembayaran melalui bank untuk vendor, biaya, pajak, dan transaksi lainnya.','tables'=>array('jurnal_header'=>'Journal Header','pemasok'=>'Vendor','ref_bank'=>'Bank Master'),'links'=>array('vendor-payment'=>'Vendor Payment','master-bank'=>'Bank Master'),'capabilities'=>array('Pembayaran vendor dan biaya','Posting bank keluar otomatis','Kontrol referensi payment document')),
  'bank-reconciliation' => array('title'=>'Bank Reconciliation','code'=>'SAP FI Bank Reconciliation','icon'=>'fa-check','color'=>'green','description'=>'Rekonsiliasi mutasi bank dengan jurnal kas bank.','tables'=>array('jurnal_header'=>'Journal Header','jurnal_detail'=>'Journal Detail','ref_bank'=>'Bank Master'),'links'=>array('cash-journal'=>'Cash Journal','bank-receipt'=>'Bank Receipt','bank-payment'=>'Bank Payment'),'capabilities'=>array('Matching mutasi bank dan jurnal','Identifikasi transaksi outstanding','Laporan selisih rekonsiliasi')),
  'vendor-invoice' => array('title'=>'Vendor Invoice','code'=>'SAP FI-AP Invoice','icon'=>'fa-file-text-o','color'=>'green','description'=>'Pencatatan invoice vendor dengan referensi PO, GR, pajak, dan jurnal utang.','tables'=>array('purchase_order'=>'Purchase Order','pemasok'=>'Vendor','jurnal_header'=>'Journal Header'),'links'=>array('purchase-order'=>'Purchase Order','material-documents'=>'Material Documents','jurnal-umum'=>'Jurnal Umum'),'capabilities'=>array('Three-way match PO, GR, invoice','Posting utang vendor dan pajak','Kontrol due date dan payment term')),
  'vendor-payment' => array('title'=>'Vendor Payment','code'=>'SAP FI-AP Payment','icon'=>'fa-money','color'=>'green','description'=>'Pembayaran utang vendor dan pelunasan invoice.','tables'=>array('pemasok'=>'Vendor','jurnal_header'=>'Journal Header','ref_bank'=>'Bank Master'),'links'=>array('vendor-invoice'=>'Vendor Invoice','bank-payment'=>'Bank Payment'),'capabilities'=>array('Payment proposal dan pembayaran manual','Pelunasan invoice vendor','Jurnal bank keluar otomatis')),
  'ap-aging' => array('title'=>'AP Aging','code'=>'SAP FI-AP Aging','icon'=>'fa-clock-o','color'=>'green','description'=>'Analisis umur utang vendor berdasarkan due date dan status pembayaran.','tables'=>array('pemasok'=>'Vendor','jurnal_header'=>'Journal Header','jurnal_detail'=>'Journal Detail'),'links'=>array('vendor-invoice'=>'Vendor Invoice','vendor-payment'=>'Vendor Payment'),'capabilities'=>array('Bucket aging utang','Saldo vendor outstanding','Prioritas pembayaran jatuh tempo')),
  'customer-invoice' => array('title'=>'Customer Invoice','code'=>'SAP FI-AR Billing','icon'=>'fa-file-text','color'=>'green','description'=>'Invoice pelanggan dan posting piutang dari transaksi penjualan.','tables'=>array('sales_invoice'=>'Sales Invoice','sales_order'=>'Sales Order','jurnal_header'=>'Journal Header'),'links'=>array('sales-invoice'=>'Sales Invoice','sales-order'=>'Sales Order','jurnal-umum'=>'Jurnal Umum'),'capabilities'=>array('Billing customer dari sales order/delivery','Posting piutang dan pendapatan','Kontrol pajak keluaran')),
  'incoming-payment' => array('title'=>'Incoming Payment','code'=>'SAP FI-AR Incoming Payment','icon'=>'fa-download','color'=>'green','description'=>'Penerimaan pembayaran pelanggan dan alokasi ke invoice terbuka.','tables'=>array('sales_invoice'=>'Sales Invoice','jurnal_header'=>'Journal Header','ref_bank'=>'Bank Master'),'links'=>array('customer-invoice'=>'Customer Invoice','bank-receipt'=>'Bank Receipt'),'capabilities'=>array('Pelunasan invoice customer','Partial payment dan overpayment','Jurnal bank masuk otomatis')),
  'ar-aging' => array('title'=>'AR Aging','code'=>'SAP FI-AR Aging','icon'=>'fa-clock-o','color'=>'green','description'=>'Analisis umur piutang customer berdasarkan jatuh tempo.','tables'=>array('sales_invoice'=>'Sales Invoice','customer'=>'Customer','jurnal_header'=>'Journal Header'),'links'=>array('customer-invoice'=>'Customer Invoice','incoming-payment'=>'Incoming Payment'),'capabilities'=>array('Bucket aging piutang','Saldo customer outstanding','Monitoring overdue invoice')),
  'tax-invoice-in' => array('title'=>'Tax Invoice In','code'=>'SAP Tax Input VAT','icon'=>'fa-sign-in','color'=>'green','description'=>'Pengelolaan faktur pajak masukan dari pembelian dan impor.','tables'=>array('pajak'=>'Tax','ceisapajakbb'=>'Pajak Bahan Baku','pemasukan'=>'Goods Receipt'),'links'=>array('vendor-invoice'=>'Vendor Invoice','dokumen-pabean'=>'Dokumen Pabean'),'capabilities'=>array('Pajak masukan per vendor/dokumen','Rekonsiliasi dengan GR dan invoice','Status validasi dan masa pajak')),
  'tax-invoice-out' => array('title'=>'Tax Invoice Out','code'=>'SAP Tax Output VAT','icon'=>'fa-sign-out','color'=>'green','description'=>'Pengelolaan faktur pajak keluaran dari penjualan.','tables'=>array('pajak'=>'Tax','ceisapajakbj'=>'Pajak Barang Jadi','sales_invoice'=>'Sales Invoice'),'links'=>array('customer-invoice'=>'Customer Invoice','sales-invoice'=>'Sales Invoice'),'capabilities'=>array('Pajak keluaran per customer/invoice','Rekonsiliasi dengan billing','Status nomor faktur dan masa pajak')),
  'vat-report' => array('title'=>'VAT Report','code'=>'SAP Tax Reporting','icon'=>'fa-file-excel-o','color'=>'green','description'=>'Laporan PPN masukan, keluaran, selisih, dan rekap masa pajak.','tables'=>array('pajak'=>'Tax','ceisapajakbb'=>'Pajak Masukan','ceisapajakbj'=>'Pajak Keluaran'),'links'=>array('tax-invoice-in'=>'Tax Invoice In','tax-invoice-out'=>'Tax Invoice Out'),'capabilities'=>array('Rekap pajak per periode','Selisih pajak masukan dan keluaran','Basis export laporan pajak')),
);
$workspace = isset($workspaces[$workspaceUrl]) ? $workspaces[$workspaceUrl] : null;
if (!$workspace) { echo '<section class="content"><div class="alert alert-danger">Workspace ERP tidak ditemukan.</div></section>'; return; }
?>
<style>
.erpws-card{border-radius:12px;border:1px solid #e5edf5;box-shadow:0 5px 16px rgba(15,23,42,.05)}
.erpws-filter label{font-size:12px;color:#475569;text-transform:uppercase;letter-spacing:.03em}
#dtb_erp_workspace th,#dtb_erp_workspace td{font-size:12px;vertical-align:middle}.select2-container{width:100%!important}
</style>
<section class="content-header"><h1><?=htmlspecialchars($workspace['title'], ENT_QUOTES, 'UTF-8');?> <small><?=htmlspecialchars($workspace['code'], ENT_QUOTES, 'UTF-8');?></small></h1><ol class="breadcrumb"><li><a href="<?=base_index();?>"><i class="fa fa-dashboard"></i> Home</a></li><li class="active"><?=htmlspecialchars($workspace['title'], ENT_QUOTES, 'UTF-8');?></li></ol></section>
<section class="content">
  <div class="callout callout-info"><h4><i class="fa <?=$workspace['icon'];?>"></i> <?=htmlspecialchars($workspace['description'], ENT_QUOTES, 'UTF-8');?></h4><p>Workspace ini menyatukan data yang sudah tersedia dan menjadi titik pengembangan transaksi ERP berikutnya.</p></div>
  <div class="box erpws-card erpws-filter">
    <div class="box-header with-border"><h3 class="box-title"><i class="fa fa-filter"></i> Workspace Filter</h3></div>
    <div class="box-body">
      <form class="form-horizontal" onsubmit="return false;">
        <div class="form-group">
          <label class="control-label col-md-2">Area</label>
          <div class="col-md-3"><select id="erpws_area" class="form-control select2"><option value="">All Scope</option><option value="Table">Data Object</option><option value="Capability">Capability</option><option value="Link">Related Transaction</option></select></div>
          <label class="control-label col-md-2">Keyword</label>
          <div class="col-md-3"><input id="erpws_keyword" class="form-control" placeholder="Cari scope / tabel / transaksi"></div>
          <div class="col-md-2"><button id="erpws_reset" class="btn btn-default"><i class="fa fa-refresh"></i> Reset</button></div>
        </div>
      </form>
    </div>
  </div>
  <div class="row">
    <?php foreach ($workspace['tables'] as $table => $label) { $countResult=$db->query('select count(*) total from '.$table); $total=$countResult ? intval($countResult->fetch()->total) : 0; ?>
      <div class="col-lg-3 col-xs-6"><div class="small-box bg-<?=$workspace['color'];?>"><div class="inner"><h3><?=number_format($total,0,',','.');?></h3><p><?=htmlspecialchars($label, ENT_QUOTES, 'UTF-8');?></p></div><div class="icon"><i class="fa <?=$workspace['icon'];?>"></i></div></div></div>
    <?php } ?>
  </div>
  <div class="row"><div class="col-md-7"><div class="box box-primary"><div class="box-header with-border"><h3 class="box-title">Cakupan Proses</h3></div><div class="box-body"><ul class="list-group"><?php foreach($workspace['capabilities'] as $capability){ ?><li class="list-group-item"><i class="fa fa-check text-green"></i> <?=htmlspecialchars($capability, ENT_QUOTES, 'UTF-8');?></li><?php } ?></ul></div></div></div>
  <div class="col-md-5"><div class="box box-default"><div class="box-header with-border"><h3 class="box-title">Transaksi Terkait</h3></div><div class="box-body"><?php foreach($workspace['links'] as $url=>$label){ ?><a class="btn btn-app" href="<?=base_index().$url;?>"><i class="fa fa-external-link"></i><?=htmlspecialchars($label, ENT_QUOTES, 'UTF-8');?></a><?php } ?></div></div></div></div>
  <div class="box erpws-card">
    <div class="box-header with-border"><h3 class="box-title"><i class="fa fa-table"></i> Workspace Readiness Matrix</h3></div>
    <div class="box-body table-responsive">
      <table id="dtb_erp_workspace" class="table table-bordered table-striped" style="width:100%">
        <thead><tr><th>Area</th><th>Object</th><th>Description</th><th>Action</th></tr></thead>
        <tbody>
          <?php foreach ($workspace['tables'] as $table => $label) { ?>
            <tr><td>Table</td><td><?=htmlspecialchars($table, ENT_QUOTES, 'UTF-8');?></td><td><?=htmlspecialchars($label, ENT_QUOTES, 'UTF-8');?> sebagai sumber data utama workspace.</td><td><button class="btn btn-info btn-xs btn-erpws-detail" data-area="Table" data-object="<?=htmlspecialchars($table, ENT_QUOTES, 'UTF-8');?>" data-description="<?=htmlspecialchars($label, ENT_QUOTES, 'UTF-8');?>"><i class="fa fa-eye"></i></button></td></tr>
          <?php } ?>
          <?php foreach ($workspace['capabilities'] as $capability) { ?>
            <tr><td>Capability</td><td><?=htmlspecialchars($workspace['title'], ENT_QUOTES, 'UTF-8');?></td><td><?=htmlspecialchars($capability, ENT_QUOTES, 'UTF-8');?></td><td><button class="btn btn-info btn-xs btn-erpws-detail" data-area="Capability" data-object="<?=htmlspecialchars($workspace['title'], ENT_QUOTES, 'UTF-8');?>" data-description="<?=htmlspecialchars($capability, ENT_QUOTES, 'UTF-8');?>"><i class="fa fa-eye"></i></button></td></tr>
          <?php } ?>
          <?php foreach ($workspace['links'] as $url => $label) { ?>
            <tr><td>Link</td><td><?=htmlspecialchars($label, ENT_QUOTES, 'UTF-8');?></td><td>Transaksi terkait: <?=htmlspecialchars(base_index().$url, ENT_QUOTES, 'UTF-8');?></td><td><a class="btn btn-primary btn-xs" href="<?=base_index().$url;?>"><i class="fa fa-external-link"></i></a> <button class="btn btn-info btn-xs btn-erpws-detail" data-area="Link" data-object="<?=htmlspecialchars($label, ENT_QUOTES, 'UTF-8');?>" data-description="<?=htmlspecialchars(base_index().$url, ENT_QUOTES, 'UTF-8');?>"><i class="fa fa-eye"></i></button></td></tr>
          <?php } ?>
        </tbody>
      </table>
    </div>
  </div>
</section>
<div class="modal fade" id="modal_erp_workspace_detail">
  <div class="modal-dialog modal-lg"><div class="modal-content"><div class="modal-header"><button class="close" data-dismiss="modal">&times;</button><h4 class="modal-title"><i class="fa fa-eye"></i> Workspace Detail</h4></div><div class="modal-body" id="erp_workspace_detail_body"></div></div></div>
</div>
<script src="<?=base_admin();?>assets/plugins/select2/select2.min.js"></script>
<script>
$(function(){
  if($.fn.select2){$('.select2').select2({width:'100%',allowClear:true});}
  var dt=$.fn.DataTable ? $('#dtb_erp_workspace').DataTable({pageLength:10,dom:"<'row'<'col-sm-12'B>>"+"<'row'<'col-sm-6'l><'col-sm-6'f>>tr<'row'<'col-sm-5'i><'col-sm-7'p>>",buttons:[{extend:'collection',text:'Export Data',buttons:['copyHtml5','excelHtml5','print']}],columnDefs:[{targets:[3],orderable:false,searchable:false}]}) : null;
  $('#erpws_area').on('change',function(){if(dt)dt.column(0).search($(this).val()).draw();});
  $('#erpws_keyword').on('keyup',function(){if(dt)dt.search($(this).val()).draw();});
  $('#erpws_reset').on('click',function(){$('#erpws_area').val('').trigger('change');$('#erpws_keyword').val('');if(dt)dt.search('').columns().search('').draw();});
  $(document).on('click','.btn-erpws-detail',function(){var b=$(this);$('#erp_workspace_detail_body').html('<div class="table-responsive"><table class="table table-bordered table-striped"><tr><th style="width:160px">Workspace</th><td><?=htmlspecialchars($workspace['title'], ENT_QUOTES, 'UTF-8');?></td></tr><tr><th>Area</th><td>'+b.data('area')+'</td></tr><tr><th>Object</th><td>'+b.data('object')+'</td></tr><tr><th>Description</th><td>'+b.data('description')+'</td></tr><tr><th>Status</th><td><span class="label label-info">Configured</span></td></tr></table></div>');$('#modal_erp_workspace_detail').modal('show');});
});
</script>
