<?php
if (!function_exists('prod_t')) {
  function prod_t($key, $fallback = '') { return lang_text($key, $fallback); }
}
if (!function_exists('prod_h')) {
  function prod_h($key, $fallback = '') { return htmlspecialchars((string) prod_t($key, $fallback), ENT_QUOTES, 'UTF-8'); }
}
if (!function_exists('prod_js')) {
  function prod_js($key, $fallback = '') { return json_encode(prod_t($key, $fallback), JSON_HEX_TAG | JSON_HEX_APOS | JSON_HEX_AMP | JSON_HEX_QUOT); }
}
$defaultFrom=date('Y-m-01');$defaultTo=date('Y-m-d');
$plants=$db->query("SELECT DISTINCT plant AS plant_code FROM production_order WHERE plant IS NOT NULL AND plant<>'' ORDER BY plant");
$erpPlants=$db->query("SELECT id,plant_code,plant_name FROM erp_plant WHERE status='Aktif' ORDER BY plant_code");
$storageLocations=$db->query("SELECT s.id,s.plant_id,s.storage_code,s.storage_name,p.plant_code FROM erp_storage_location s LEFT JOIN erp_plant p ON p.id=s.plant_id WHERE s.status='Aktif' ORDER BY p.plant_code,s.storage_code");
$storageBins=$db->query("SELECT b.id,b.storage_location_id,b.bin_code,b.bin_name,s.storage_code FROM erp_storage_bin b LEFT JOIN erp_storage_location s ON s.id=b.storage_location_id WHERE b.status='Aktif' ORDER BY s.storage_code,b.bin_code");
$kpi=$db->fetch("SELECT COUNT(*) component_lines,COALESCE(SUM(m.required_qty),0) required_qty,COALESCE(SUM(m.issued_qty),0) issued_qty FROM production_order_material m JOIN production_order p ON p.id_production_order=m.id_production_order WHERE p.status IN ('CREATED','RELEASED','IN_PROCESS') AND p.start_date BETWEEN ? AND ?",array($defaultFrom,$defaultTo));
$stockKpi=$db->fetch("SELECT COUNT(DISTINCT kode) material_stock,COALESCE(SUM(qty_sisa),0) available_qty FROM stock_layer WHERE qty_sisa>0 AND lokasi='GUDANG' AND COALESCE(stock_type,'UNRESTRICTED')='UNRESTRICTED'");
?>
<style>
.mav-hero{background:linear-gradient(135deg,#0f766e,#15803d);color:#fff;border-radius:14px;padding:20px 22px;margin-bottom:18px;box-shadow:0 10px 24px rgba(15,23,42,.18)}.mav-hero h1{margin:0 0 6px;font-size:26px;font-weight:700}.mav-hero p{margin:0;opacity:.92}.mav-card{border-radius:12px;background:#fff;border:1px solid #e5edf5;box-shadow:0 5px 16px rgba(15,23,42,.05);margin-bottom:14px}.mav-kpi{border-radius:12px;background:#fff;border:1px solid #edf2f7;padding:15px;margin-bottom:14px}.mav-kpi span{display:block;color:#64748b;font-size:12px;text-transform:uppercase}.mav-kpi strong{display:block;font-size:24px;margin-top:6px}.mav-kpi i{float:right;font-size:26px;color:#0f766e;opacity:.55}#dtb_material_availability th,#dtb_material_availability td{font-size:12px;vertical-align:middle}.select2-container{width:100%!important}.mav-filter .form-group{margin-bottom:12px}
</style>
<section class="content-header"><h1><?=prod_h('production_material_availability', 'Material Availability');?> <small>SAP PP ATP/Availability Check</small></h1><ol class="breadcrumb"><li><a href="<?=base_index();?>"><i class="fa fa-dashboard"></i> <?=prod_h('common_home', 'Home');?></a></li><li class="active"><?=prod_h('production_material_availability', 'Material Availability');?></li></ol></section>
<section class="content">
  <div class="mav-hero"><div class="row"><div class="col-md-8"><h1>Material Availability Workbench</h1><p>Cek kebutuhan komponen Production Order terhadap stock layer aktual, plant/storage/bin, stock type, lot/batch, dan dokumen pabean.</p></div><div class="col-md-4 text-right"><button id="btn_excel_mav_top" class="btn btn-success"><i class="fa fa-file-excel-o"></i> Export Availability</button></div></div></div>
  <div class="row"><div class="col-sm-3"><div class="mav-kpi"><i class="fa fa-list"></i><span>Requirement Lines</span><strong><?=number_format((float)$kpi->component_lines,0,',','.');?></strong></div></div><div class="col-sm-3"><div class="mav-kpi"><i class="fa fa-cube"></i><span>Required Qty</span><strong><?=number_format((float)$kpi->required_qty,2,',','.');?></strong></div></div><div class="col-sm-3"><div class="mav-kpi"><i class="fa fa-share"></i><span>Issued Qty</span><strong><?=number_format((float)$kpi->issued_qty,2,',','.');?></strong></div></div><div class="col-sm-3"><div class="mav-kpi"><i class="fa fa-archive"></i><span>Available Stock</span><strong><?=number_format((float)$stockKpi->available_qty,2,',','.');?></strong></div></div></div>
  <div class="box mav-card"><div class="box-header"><h3 class="box-title"><i class="fa fa-filter"></i> Filter Availability</h3></div><div class="box-body"><form class="form-horizontal mav-filter" onsubmit="return false;"><div class="form-group"><label class="control-label col-lg-2">PO Start Date</label><div class="col-lg-2"><div class="input-group date mav-date"><input id="filter_tgl_awal" class="form-control" value="<?=$defaultFrom;?>"><span class="input-group-addon"><span class="glyphicon glyphicon-calendar"></span></span></div></div><div class="col-lg-2"><div class="input-group date mav-date"><input id="filter_tgl_akhir" class="form-control" value="<?=$defaultTo;?>"><span class="input-group-addon"><span class="glyphicon glyphicon-calendar"></span></span></div></div><label class="control-label col-lg-1">PO Status</label><div class="col-lg-2"><select id="filter_po_status" class="form-control"><option value=""><?=prod_h('common_all', 'All');?></option><option>CREATED</option><option>RELEASED</option><option>IN_PROCESS</option></select></div><label class="control-label col-lg-1">Plant PO</label><div class="col-lg-2"><select id="filter_plant" class="form-control"><option value=""><?=prod_h('common_all', 'All');?></option><?php foreach($plants as $p){ ?><option value="<?=htmlspecialchars($p->plant_code,ENT_QUOTES,'UTF-8');?>"><?=htmlspecialchars($p->plant_code,ENT_QUOTES,'UTF-8');?></option><?php } ?></select></div></div>
  <div class="form-group"><label class="control-label col-lg-2">Stock Plant</label><div class="col-lg-2"><select id="filter_stock_plant" class="form-control"><option value=""><?=prod_h('common_all', 'All');?></option><?php foreach($erpPlants as $p){ ?><option value="<?=intval($p->id);?>"><?=htmlspecialchars($p->plant_code.' - '.$p->plant_name,ENT_QUOTES,'UTF-8');?></option><?php } ?></select></div><label class="control-label col-lg-2">Storage Location</label><div class="col-lg-2"><select id="filter_storage_location" class="form-control"><option value=""><?=prod_h('common_all', 'All');?></option><?php foreach($storageLocations as $s){ ?><option value="<?=intval($s->id);?>" data-plant-id="<?=intval($s->plant_id);?>"><?=htmlspecialchars($s->plant_code.' / '.$s->storage_code.' - '.$s->storage_name,ENT_QUOTES,'UTF-8');?></option><?php } ?></select></div><label class="control-label col-lg-1">Storage Bin</label><div class="col-lg-3"><select id="filter_storage_bin" class="form-control"><option value=""><?=prod_h('common_all', 'All');?></option><?php foreach($storageBins as $b){ ?><option value="<?=intval($b->id);?>" data-storage-location-id="<?=intval($b->storage_location_id);?>"><?=htmlspecialchars($b->storage_code.' / '.$b->bin_code.' - '.$b->bin_name,ENT_QUOTES,'UTF-8');?></option><?php } ?></select></div></div>
  <div class="form-group"><label class="control-label col-lg-2">Stock Type</label><div class="col-lg-2"><select id="filter_stock_type" class="form-control"><option value="UNRESTRICTED">Unrestricted</option><option value="QUALITY">Quality</option><option value="BLOCKED">Blocked</option><option value=""><?=prod_h('common_all', 'All');?></option></select></div><label class="control-label col-lg-2">Availability</label><div class="col-lg-2"><select id="filter_availability_status" class="form-control"><option value=""><?=prod_h('common_all', 'All');?></option><option value="SHORTAGE">Shortage</option><option value="AVAILABLE">Available</option></select></div><label class="control-label col-lg-1"><?=prod_h('production_material', 'Material');?></label><div class="col-lg-3"><select id="filter_material" class="form-control"></select></div></div>
  <div class="form-group"><label class="control-label col-lg-2"><?=prod_h('common_search', 'Search');?></label><div class="col-lg-5"><input id="filter_keyword" class="form-control" placeholder="PO, FG, component material"></div><div class="col-lg-5"><button id="btn_filter_mav" class="btn btn-primary"><i class="fa fa-filter"></i> <?=prod_h('common_filter', 'Filter');?></button> <button id="btn_reset_mav" class="btn btn-default"><i class="fa fa-refresh"></i> <?=prod_h('common_reset', 'Reset');?></button> <button id="btn_excel_mav" class="btn btn-success"><i class="fa fa-file-excel-o"></i> <?=prod_h('common_export_excel', 'Export Excel');?></button></div></div></form></div></div>
  <div class="box mav-card"><div class="box-body"><div class="alert alert-warning error_data_delete" style="display:none"><button type="button" class="close hide_alert_notif">&times;</button><span class="isi_warning_delete"></span></div><div class="table-responsive"><table id="dtb_material_availability" class="table table-bordered table-striped table-condensed" style="width:100%"><thead><tr><th><?=prod_h('common_no', 'No');?></th><th><?=prod_h('common_action', 'Action');?></th><th><?=prod_h('production_order', 'Production Order');?></th><th>FG Material</th><th>Component</th><th>Requirement</th><th>Available</th><th>Shortage</th><th><?=prod_h('production_uom', 'UOM');?></th><th>PO Location</th><th>Customs Preview</th><th><?=prod_h('common_status', 'Status');?></th></tr></thead><tbody></tbody></table></div></div></div>
  <div id="modal_layer_mav" class="modal fade"><div class="modal-dialog modal-lg" style="width:96%"><div class="modal-content"><div class="modal-header"><button class="close" data-dismiss="modal">&times;</button><h4 class="modal-title">Stock Layer Detail</h4></div><div class="modal-body" id="mav_layer_body"></div><div class="modal-footer"><button class="btn btn-default" data-dismiss="modal"><?=prod_h('common_close', 'Close');?></button></div></div></div></div>
</section>
<script src="<?=base_admin();?>assets/plugins/select2/select2.min.js"></script>
<script>
function mavError(m){$('.isi_warning_delete').text(m||<?=prod_js('production_material_availability_process_failed', 'Material Availability failed to process.');?>);$('.error_data_delete').fadeIn();}
function mavFilters(){return{tgl_awal:$('#filter_tgl_awal').val(),tgl_akhir:$('#filter_tgl_akhir').val(),po_status:$('#filter_po_status').val(),plant:$('#filter_plant').val(),plant_id:$('#filter_stock_plant').val(),storage_location_id:$('#filter_storage_location').val(),storage_bin_id:$('#filter_storage_bin').val(),stock_type:$('#filter_stock_type').val(),availability_status:$('#filter_availability_status').val(),material_code:$('#filter_material').val(),keyword:$('#filter_keyword').val()};}
function mavQuery(){return $.param(mavFilters());}
$(function(){if($.fn.datepicker){$('.mav-date').datepicker({format:'yyyy-mm-dd',autoclose:true,todayHighlight:true});}if($.fn.select2){$('#filter_po_status,#filter_plant,#filter_stock_plant,#filter_storage_location,#filter_storage_bin,#filter_stock_type,#filter_availability_status').select2({width:'100%',allowClear:true});$('#filter_material').select2({width:'100%',allowClear:true,placeholder:'Cari component...',minimumInputLength:1,ajax:{url:'<?=base_admin();?>modul/material_availability/material_availability_action.php?act=material_search',type:'POST',dataType:'json',delay:250,data:function(p){return{term:p.term||''};},processResults:function(d){return{results:d.results||[]};}}});}
$('#filter_stock_plant').on('change',function(){var plant=$(this).val();$('#filter_storage_location option').each(function(){var op=$(this),p=op.data('plant-id');op.toggle(!p||!plant||String(p)===String(plant));});});
$('#filter_storage_location').on('change',function(){var loc=$(this).val();$('#filter_storage_bin option').each(function(){var op=$(this),l=op.data('storage-location-id');op.toggle(!l||!loc||String(l)===String(loc));});});
var dt=$('#dtb_material_availability').DataTable({bProcessing:true,bServerSide:true,pageLength:25,ordering:false,dom:"<'row'<'col-sm-12'B>>"+"<'row'<'col-sm-6'l><'col-sm-6'f>>"+"<'row'<'col-sm-12'tr>>"+"<'row'<'col-sm-5'i><'col-sm-7'p>>",buttons:[{extend:'collection',text:<?=prod_js('common_export_data', 'Export Data');?>,buttons:['copyHtml5','excelHtml5','csvHtml5','pdfHtml5']}],columnDefs:[{targets:[0,1],orderable:false,searchable:false},{targets:[6,7],className:'text-right'},{width:'38px',targets:0},{width:'58px',targets:1}],ajax:{url:'<?=base_admin();?>modul/material_availability/material_availability_data.php',type:'post',data:function(d){$.extend(d,mavFilters());},error:function(xhr){console.log(xhr.responseText);mavError(<?=prod_js('production_material_availability_load_failed', 'Material Availability data failed to load.');?>);}}});
$('#btn_filter_mav').click(function(){dt.draw();});$('#filter_keyword').keyup(function(e){if(e.keyCode===13)dt.draw();});$('#btn_reset_mav').click(function(){$('#filter_tgl_awal').val('<?=$defaultFrom;?>');$('#filter_tgl_akhir').val('<?=$defaultTo;?>');$('#filter_keyword').val('');$('#filter_po_status,#filter_plant,#filter_stock_plant,#filter_storage_location,#filter_storage_bin,#filter_availability_status').val('').trigger('change');$('#filter_stock_type').val('UNRESTRICTED').trigger('change');$('#filter_material').val(null).trigger('change');dt.draw();});$('#btn_excel_mav,#btn_excel_mav_top').click(function(){window.location='<?=base_admin();?>modul/material_availability/material_availability_action.php?act=excel&'+mavQuery();});
$(document).on('click','.btn-mav-detail',function(){var el=$(this);var data=mavFilters();data.material_code=el.data('material');data.po_id=el.data('po');$.post('<?=base_admin();?>modul/material_availability/material_availability_action.php?act=layer_detail',data,function(html){$('#mav_layer_body').html(html);$('#modal_layer_mav').modal('show');}).fail(function(){mavError('Detail stock layer gagal dibuka.');});});$('.hide_alert_notif').click(function(){$('.error_data_delete').hide();});
});
</script>
