<?php
if (!function_exists('fin_t')) {
  function fin_t($key, $fallback = '') { return lang_text($key, $fallback); }
}
if (!function_exists('fin_h')) {
  function fin_h($key, $fallback = '') { return htmlspecialchars((string) fin_t($key, $fallback), ENT_QUOTES, 'UTF-8'); }
}
if (!function_exists('fin_js')) {
  function fin_js($key, $fallback = '') { return json_encode(fin_t($key, $fallback), JSON_HEX_TAG | JSON_HEX_APOS | JSON_HEX_AMP | JSON_HEX_QUOT); }
}
$initialOutputBufferLevel=ob_get_level();ob_start();session_start();include "../../inc/config.php";require_once "../../inc/lib/PHPExcel.php";require_once "../../inc/excel_style_helper.php";session_check_json();
function vat_h($v){return htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');}function vat_n($v){return number_format((float)$v,2,'.',',');}function vat_json($s,$m='',$e=array()){header('Content-Type: application/json');echo json_encode(array_merge(array('status'=>$s,'message'=>$m),$e));exit;}
function vat_rows($db,$period){return $db->query("SELECT tax_direction,COUNT(*) doc_count,COALESCE(SUM(dpp_amount),0) dpp,COALESCE(SUM(vat_amount),0) vat FROM erp_tax_invoice WHERE tax_period=? AND status='POSTED' GROUP BY tax_direction",array($period));}
try{$act=$_GET['act']??'';$period=$_REQUEST['tax_period']??date('Y-m');
if($act==='filter'){if(!preg_match('/^\d{4}-(0[1-9]|1[0-2])$/',$period))throw new Exception('Period tidak valid.');$in=array('dpp'=>0,'vat'=>0,'doc'=>0);$out=$in;foreach(vat_rows($db,$period) as $r){if($r->tax_direction==='IN')$in=array('dpp'=>(float)$r->dpp,'vat'=>(float)$r->vat,'doc'=>(int)$r->doc_count);else$out=array('dpp'=>(float)$r->dpp,'vat'=>(float)$r->vat,'doc'=>(int)$r->doc_count);} $net=$out['vat']-$in['vat'];$btnIn='<button type="button" class="btn btn-info btn-xs btn-vat-detail" data-type="PPN Masukan" data-docs="'.vat_h(vat_n($in['doc'])).'" data-dpp="'.vat_h(vat_n($in['dpp'])).'" data-vat="'.vat_h(vat_n($in['vat'])).'"><i class="fa fa-eye"></i></button>';$btnOut='<button type="button" class="btn btn-info btn-xs btn-vat-detail" data-type="PPN Keluaran" data-docs="'.vat_h(vat_n($out['doc'])).'" data-dpp="'.vat_h(vat_n($out['dpp'])).'" data-vat="'.vat_h(vat_n($out['vat'])).'"><i class="fa fa-eye"></i></button>';$btnNet='<button type="button" class="btn btn-info btn-xs btn-vat-detail" data-type="Net VAT" data-docs="'.vat_h(vat_n($in['doc']+$out['doc'])).'" data-dpp="-" data-vat="'.vat_h(vat_n($net)).'"><i class="fa fa-eye"></i></button>';$html='<tr><td>PPN Masukan</td><td class="text-right">'.vat_n($in['doc']).'</td><td class="text-right">'.vat_n($in['dpp']).'</td><td class="text-right">'.vat_n($in['vat']).'</td><td>'.$btnIn.'</td></tr><tr><td>PPN Keluaran</td><td class="text-right">'.vat_n($out['doc']).'</td><td class="text-right">'.vat_n($out['dpp']).'</td><td class="text-right">'.vat_n($out['vat']).'</td><td>'.$btnOut.'</td></tr><tr class="info"><th>Net VAT Payable / (Overpaid)</th><th></th><th></th><th class="text-right">'.vat_n($net).'</th><th>'.$btnNet.'</th></tr>';vat_json('success','OK',array('html'=>$html,'input_vat'=>vat_n($in['vat']),'output_vat'=>vat_n($out['vat']),'net_vat'=>vat_n($net),'docs'=>$in['doc']+$out['doc']));}
if($act==='excel'){if(!preg_match('/^\d{4}-(0[1-9]|1[0-2])$/',$period))throw new Exception('Period tidak valid.');$excel=new PHPExcel();$sh=$excel->setActiveSheetIndex(0);$sh->setTitle(erp_export_sheet_title('VAT Report'));$headers=array(erp_export_label("No"),erp_export_label("Direction"),erp_export_label("Tax Invoice"),erp_export_label("Date"),erp_export_label("Partner"),erp_export_label("DPP"),erp_export_label("VAT"),erp_export_label("Status"));foreach($headers as $i=>$h)$sh->setCellValueByColumnAndRow($i,4,$h);$rows=$db->query("SELECT * FROM erp_tax_invoice WHERE tax_period=? AND status='POSTED' ORDER BY tax_direction,tax_invoice_date",array($period));$rn=5;$no=1;foreach($rows as $r){$vals=array($no++,$r->tax_direction,$r->tax_invoice_no,$r->tax_invoice_date,trim($r->partner_code.' - '.$r->partner_name,' -'),$r->dpp_amount,$r->vat_amount,$r->status);foreach($vals as $i=>$v)$sh->setCellValueByColumnAndRow($i,$rn,$v);$rn++;}erpkb_excel_apply_standard_style($excel,array('sheet'=>$sh,'title'=>erp_export_title('VAT REPORT'),'header_row'=>4,'first_data_row'=>5,'last_data_row'=>max(5,$rn-1),'column_count'=>count($headers),'money_columns'=>array('F','G'),'filters'=>array('Period'=>$period)));while(ob_get_level()>$initialOutputBufferLevel)ob_end_clean();header('Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');header('Content-Disposition: attachment;filename="vat_report_'.date('YmdHis').'.xlsx"');header('Cache-Control: max-age=0');PHPExcel_IOFactory::createWriter($excel,'Excel2007')->save('php://output');exit;}
vat_json('error','Action tidak dikenal.');
}catch(Exception $e){vat_json('error',$e->getMessage());}
