<?php
include_once "incoming_inspection_lib.php";
$defaultFrom = date('Y-m-01');
$defaultTo = date('Y-m-d');
$plants = ilot_plants($db);
$storageLocations = ilot_storage_locations($db);
$storageBins = ilot_storage_bins($db);
$kpi = iinq_kpi($db);
?>
<style>
.iinq-hero{background:linear-gradient(135deg,#0f172a,#0f766e);color:#fff;border-radius:14px;padding:21px 22px;margin-bottom:18px;box-shadow:0 10px 24px rgba(15,23,42,.18)}
.iinq-hero h1{margin:0 0 6px;font-size:26px;font-weight:700}.iinq-hero p{margin:0;opacity:.92}
.iinq-kpi{border-radius:12px;background:#fff;border:1px solid #e5edf5;padding:15px;margin-bottom:14px;box-shadow:0 4px 14px rgba(15,23,42,.05)}
.iinq-kpi span{display:block;color:#64748b;font-size:12px;text-transform:uppercase;letter-spacing:.04em}.iinq-kpi strong{display:block;font-size:23px;margin-top:6px;color:#111827}.iinq-kpi i{float:right;font-size:26px;color:#0f766e;opacity:.55}
.iinq-card{border-radius:12px;border:1px solid #e5edf5;box-shadow:0 5px 16px rgba(15,23,42,.05)}.iinq-filter .form-group{margin-bottom:12px}
#dtb_incoming_inspection th,#dtb_incoming_inspection td{font-size:12px;vertical-align:middle}.select2-container{width:100%!important}.iinq-modal .modal-body{max-height:72vh;overflow:auto}
#tbl_ilot_result th,#tbl_ilot_result td{font-size:12px;vertical-align:middle}
</style>
<section class="content-header">
  <h1>Incoming Inspection <small>SAP QM Goods Receipt Inspection</small></h1>
  <ol class="breadcrumb"><li><a href="<?=base_index();?>"><i class="fa fa-dashboard"></i> Home</a></li><li><a href="<?=base_index();?>quality-dashboard">Quality Management</a></li><li class="active">Incoming Inspection</li></ol>
</section>
<section class="content">
  <div class="iinq-hero"><div class="row"><div class="col-md-8"><h1>Incoming Inspection Workbench</h1><p>Monitor kandidat inspeksi dari barang masuk, buat inspection lot, record result, dan post usage decision dengan trace BPB, stock layer, dan dokumen BC.</p></div><div class="col-md-4 text-right"><button id="btn_excel_iinq_top" class="btn btn-success"><i class="fa fa-file-excel-o"></i> Export Excel</button></div></div></div>
  <div class="row">
    <div class="col-sm-3"><div class="iinq-kpi"><i class="fa fa-cubes"></i><span>Incoming Candidates</span><strong><?=number_format((float)$kpi->candidate_count,0,',','.');?></strong></div></div>
    <div class="col-sm-3"><div class="iinq-kpi"><i class="fa fa-plus"></i><span>Pending Lot</span><strong><?=number_format((float)$kpi->pending_lot,0,',','.');?></strong></div></div>
    <div class="col-sm-3"><div class="iinq-kpi"><i class="fa fa-hourglass-half"></i><span>Open Inspection</span><strong><?=number_format((float)$kpi->open_lot,0,',','.');?></strong></div></div>
    <div class="col-sm-3"><div class="iinq-kpi"><i class="fa fa-warning"></i><span>Exception / Partial</span><strong><?=number_format((float)$kpi->exception_lot,0,',','.');?></strong></div></div>
  </div>
  <div class="box iinq-card"><div class="box-header with-border"><h3 class="box-title"><i class="fa fa-filter"></i> Filter Incoming Inspection</h3></div><div class="box-body">
    <form class="form-horizontal iinq-filter" onsubmit="return false;">
      <div class="form-group"><label class="control-label col-lg-2">Receipt Date</label><div class="col-lg-2"><div class="input-group date iinq-date"><input id="filter_tgl_awal" class="form-control" value="<?=$defaultFrom;?>" autocomplete="off"><span class="input-group-addon"><span class="glyphicon glyphicon-calendar"></span></span></div></div><div class="col-lg-2"><div class="input-group date iinq-date"><input id="filter_tgl_akhir" class="form-control" value="<?=$defaultTo;?>" autocomplete="off"><span class="input-group-addon"><span class="glyphicon glyphicon-calendar"></span></span></div></div><label class="control-label col-lg-1">Material</label><div class="col-lg-5"><select id="filter_material" class="form-control"></select></div></div>
      <div class="form-group"><label class="control-label col-lg-2">Plant</label><div class="col-lg-2"><select id="filter_plant" class="form-control"><option value="">Semua Plant</option><?php foreach($plants as $p){ ?><option value="<?=intval($p->id);?>"><?=ilot_h($p->plant_code.' - '.$p->plant_name);?></option><?php } ?></select></div><label class="control-label col-lg-2">Storage Location</label><div class="col-lg-2"><select id="filter_storage_location" class="form-control"><option value="">Semua SLoc</option><?php foreach($storageLocations as $s){ ?><option value="<?=intval($s->id);?>" data-plant-id="<?=intval($s->plant_id);?>"><?=ilot_h($s->plant_code.' / '.$s->storage_code.' - '.$s->storage_name);?></option><?php } ?></select></div><label class="control-label col-lg-1">Bin</label><div class="col-lg-3"><select id="filter_storage_bin" class="form-control"><option value="">Semua Bin</option><?php foreach($storageBins as $b){ ?><option value="<?=intval($b->id);?>" data-storage-location-id="<?=intval($b->storage_location_id);?>"><?=ilot_h($b->storage_code.' / '.$b->bin_code.' - '.$b->bin_name);?></option><?php } ?></select></div></div>
      <div class="form-group"><label class="control-label col-lg-2">Inspection Status</label><div class="col-lg-2"><select id="filter_inspection_status" class="form-control"><option value="">Semua Status</option><option value="PENDING_LOT">Pending Lot</option><option>CREATED</option><option>IN_INSPECTION</option><option>RESULT_RECORDED</option><option>UD_ACCEPTED</option><option>UD_REJECTED</option><option>UD_PARTIAL</option><option>CANCELLED</option></select></div><label class="control-label col-lg-2">Stock Type</label><div class="col-lg-2"><select id="filter_stock_type" class="form-control"><option value="">Semua</option><option value="QUALITY">QUALITY</option><option value="BLOCKED">BLOCKED</option><option value="UNRESTRICTED">UNRESTRICTED</option></select></div><label class="control-label col-lg-1">Search</label><div class="col-lg-3"><input id="filter_keyword" class="form-control" placeholder="BPB, lot, material, No Aju, BC"></div></div>
      <div class="form-group"><div class="col-lg-offset-2 col-lg-10"><button id="btn_filter_iinq" class="btn btn-primary"><i class="fa fa-filter"></i> Filter</button> <button id="btn_reset_iinq" class="btn btn-default"><i class="fa fa-refresh"></i> Reset</button> <button id="btn_excel_iinq" class="btn btn-success"><i class="fa fa-file-excel-o"></i> Export Excel</button></div></div>
    </form>
  </div></div>
  <div class="box iinq-card"><div class="box-body"><div class="alert alert-warning error_data_delete" style="display:none"><button type="button" class="close hide_alert_notif">&times;</button><i class="icon fa fa-warning"></i> <span class="isi_warning_delete"></span></div><div class="table-responsive"><table id="dtb_incoming_inspection" class="table table-bordered table-striped table-condensed" style="width:100%"><thead><tr><th>No</th><th>Action</th><th>BPB / Source</th><th>Receipt</th><th>Material</th><th>Open Qty</th><th>Location</th><th>Inspection Lot</th><th>Result / UD</th><th>Customs Doc</th></tr></thead><tbody></tbody></table></div></div></div>
  <div id="modal_iinq_detail" class="modal fade iinq-modal"><div class="modal-dialog modal-lg" style="width:96%"><div class="modal-content"><div class="modal-header"><button class="close" data-dismiss="modal">&times;</button><h4 class="modal-title">Incoming Source Detail</h4></div><div class="modal-body" id="iinq_detail_body"></div><div class="modal-footer"><button class="btn btn-default" data-dismiss="modal">Close</button></div></div></div></div>
  <div id="modal_iinq_lot_detail" class="modal fade iinq-modal"><div class="modal-dialog modal-lg" style="width:96%"><div class="modal-content"><div class="modal-header"><button class="close" data-dismiss="modal">&times;</button><h4 class="modal-title">Inspection Lot Detail</h4></div><div class="modal-body" id="iinq_lot_detail_body"></div><div class="modal-footer"><button class="btn btn-default" data-dismiss="modal">Close</button></div></div></div></div>
  <div id="modal_iinq_result" class="modal fade iinq-modal"><div class="modal-dialog modal-lg" style="width:96%"><div class="modal-content"><div class="modal-header"><button class="close" data-dismiss="modal">&times;</button><h4 class="modal-title">Record Incoming Inspection Result</h4></div><div class="modal-body" id="iinq_result_body"></div><div class="modal-footer"><button class="btn btn-default" data-dismiss="modal">Close</button><button id="btn_save_iinq_result" class="btn btn-success"><i class="fa fa-check-square-o"></i> Save Result</button></div></div></div></div>
  <div id="modal_iinq_ud" class="modal fade iinq-modal"><div class="modal-dialog modal-lg"><div class="modal-content"><div class="modal-header"><button class="close" data-dismiss="modal">&times;</button><h4 class="modal-title">Usage Decision</h4></div><div class="modal-body" id="iinq_ud_body"></div><div class="modal-footer"><button class="btn btn-default" data-dismiss="modal">Close</button><button id="btn_save_iinq_ud" class="btn btn-warning"><i class="fa fa-gavel"></i> Post Usage Decision</button></div></div></div></div>
</section>
<script src="<?=base_admin();?>assets/plugins/select2/select2.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
<script>
function iinqError(m){$('.isi_warning_delete').text(m||'Incoming Inspection gagal diproses.');$('.error_data_delete').fadeIn();}
function iinqFilters(){return{tgl_awal:$('#filter_tgl_awal').val(),tgl_akhir:$('#filter_tgl_akhir').val(),material_code:$('#filter_material').val(),plant_id:$('#filter_plant').val(),storage_location_id:$('#filter_storage_location').val(),storage_bin_id:$('#filter_storage_bin').val(),stock_type:$('#filter_stock_type').val(),inspection_status:$('#filter_inspection_status').val(),keyword:$('#filter_keyword').val()};}
function iinqExcelUrl(){return '<?=base_admin();?>modul/incoming_inspection/incoming_inspection_action.php?act=excel&'+$.param(iinqFilters());}
function iinqInitSelect(){if(!$.fn.select2)return;$('#filter_plant,#filter_storage_location,#filter_storage_bin,#filter_stock_type,#filter_inspection_status,#ud_code').select2({width:'100%',allowClear:true});$('#filter_material').select2({width:'100%',allowClear:true,placeholder:'Cari material...',minimumInputLength:1,ajax:{url:'<?=base_admin();?>modul/incoming_inspection/incoming_inspection_action.php?act=material_search',type:'POST',dataType:'json',delay:250,data:function(p){return{term:p.term||''};},processResults:function(d){return{results:d.results||[]};}}});}
function resultRow(){return '<tr><td><input name="characteristic_no[]" class="form-control input-sm"></td><td><input name="characteristic_name[]" class="form-control input-sm"></td><td><input name="specification[]" class="form-control input-sm"></td><td><input name="sample_qty_result[]" class="form-control input-sm text-right" value="0"></td><td><input name="result_value[]" class="form-control input-sm"></td><td><select name="result_status[]" class="form-control input-sm"><option value="PASS">PASS</option><option value="FAIL">FAIL</option><option value="INFO">INFO</option></select></td><td><input name="defect_code[]" class="form-control input-sm"></td><td><input name="defect_qty[]" class="form-control input-sm text-right" value="0"></td><td><input name="remarks_result[]" class="form-control input-sm"></td><td><button type="button" class="btn btn-danger btn-xs btn-remove-result"><i class="fa fa-trash"></i></button></td></tr>';}
$(function(){
  if($.fn.datepicker){$('.iinq-date').datepicker({format:'yyyy-mm-dd',autoclose:true,todayHighlight:true});}
  iinqInitSelect();
  var dt=$('#dtb_incoming_inspection').DataTable({bProcessing:true,bServerSide:true,pageLength:25,ordering:false,dom:"<'row'<'col-sm-12'B>>"+"<'row'<'col-sm-6'l><'col-sm-6'f>>"+"<'row'<'col-sm-12'tr>>"+"<'row'<'col-sm-5'i><'col-sm-7'p>>",buttons:[{extend:'collection',text:'Export Data',buttons:['copyHtml5','excelHtml5','csvHtml5','pdfHtml5']}],columnDefs:[{targets:[0,1],orderable:false,searchable:false},{targets:[5],className:'text-right'},{width:'42px',targets:0},{width:'145px',targets:1}],ajax:{url:'<?=base_admin();?>modul/incoming_inspection/incoming_inspection_data.php',type:'post',data:function(d){$.extend(d,iinqFilters());},error:function(xhr){console.log(xhr.responseText);iinqError('Data Incoming Inspection gagal dimuat.');}}});
  $('#btn_filter_iinq').click(function(){dt.draw();});$('#filter_keyword').keyup(function(e){if(e.keyCode===13)dt.draw();});$('#btn_excel_iinq,#btn_excel_iinq_top').click(function(){window.location=iinqExcelUrl();});
  $('#btn_reset_iinq').click(function(){$('#filter_tgl_awal').val('<?=$defaultFrom;?>');$('#filter_tgl_akhir').val('<?=$defaultTo;?>');$('#filter_keyword').val('');$('#filter_material').val(null).trigger('change');$('#filter_plant,#filter_storage_location,#filter_storage_bin,#filter_stock_type,#filter_inspection_status').val('').trigger('change');dt.draw();});
  $(document).on('click','.btn-iinq-source-detail',function(){$.post('<?=base_admin();?>modul/incoming_inspection/incoming_inspection_action.php?act=source_detail',{stock_layer_id:$(this).data('layer-id')},function(html){$('#iinq_detail_body').html(html);$('#modal_iinq_detail').modal('show');}).fail(function(){iinqError('Detail source gagal dibuka.');});});
  $(document).on('click','.btn-iinq-create-lot',function(){var layer=$(this).data('layer-id');Swal.fire({title:'Create inspection lot?',text:'Inspection lot akan dibuat dari stock layer incoming ini.',icon:'question',showCancelButton:true,confirmButtonText:'Create Lot'}).then(function(r){if(!r.isConfirmed)return;$.post('<?=base_admin();?>modul/incoming_inspection/incoming_inspection_action.php?act=create_lot',{stock_layer_id:layer},function(res){if(res.status==='good'){dt.draw(false);Swal.fire('Success','Inspection lot '+res.lot_no+' siap diproses.','success');}else iinqError(res.error_message);},'json').fail(function(xhr){iinqError(xhr.responseText);});});});
  $(document).on('click','.btn-iinq-lot-detail',function(){$.post('<?=base_admin();?>modul/inspection_lot/inspection_lot_action.php?act=detail',{id:$(this).data('id')},function(html){$('#iinq_lot_detail_body').html(html);$('#modal_iinq_lot_detail').modal('show');}).fail(function(){iinqError('Detail lot gagal dibuka.');});});
  $(document).on('click','.btn-iinq-result',function(){$.post('<?=base_admin();?>modul/inspection_lot/inspection_lot_action.php?act=result_form',{id:$(this).data('id')},function(html){$('#iinq_result_body').html(html);$('#modal_iinq_result').modal('show');}).fail(function(){iinqError('Form result gagal dibuka.');});});
  $(document).on('click','#btn_add_result_row',function(){$('#tbl_ilot_result tbody').append(resultRow());});$(document).on('click','.btn-remove-result',function(){$(this).closest('tr').remove();});
  $('#btn_save_iinq_result').click(function(){var btn=$(this);btn.prop('disabled',true).html('<i class="fa fa-spinner fa-spin"></i> Saving...');$.ajax({url:'<?=base_admin();?>modul/inspection_lot/inspection_lot_action.php?act=record_result',type:'POST',data:$('#form_ilot_result').serialize(),dataType:'json',success:function(res){btn.prop('disabled',false).html('<i class="fa fa-check-square-o"></i> Save Result');if(res.status==='good'){$('#modal_iinq_result').modal('hide');dt.draw(false);Swal.fire('Success','Incoming inspection result tersimpan.','success');}else iinqError(res.error_message);},error:function(xhr){btn.prop('disabled',false).html('<i class="fa fa-check-square-o"></i> Save Result');iinqError(xhr.responseText);}});});
  $(document).on('click','.btn-iinq-ud',function(){$.post('<?=base_admin();?>modul/inspection_lot/inspection_lot_action.php?act=ud_form',{id:$(this).data('id')},function(html){$('#iinq_ud_body').html(html);iinqInitSelect();$('#modal_iinq_ud').modal('show');}).fail(function(){iinqError('Form UD gagal dibuka.');});});
  $('#btn_save_iinq_ud').click(function(){Swal.fire({title:'Post usage decision?',text:'UD akan memfinalisasi incoming inspection lot.',icon:'question',showCancelButton:true,confirmButtonText:'Post UD'}).then(function(r){if(!r.isConfirmed)return;$.ajax({url:'<?=base_admin();?>modul/inspection_lot/inspection_lot_action.php?act=usage_decision',type:'POST',data:$('#form_ilot_ud').serialize(),dataType:'json',success:function(res){if(res.status==='good'){$('#modal_iinq_ud').modal('hide');dt.draw(false);Swal.fire('Success','Usage decision berhasil diposting.','success');}else iinqError(res.error_message);},error:function(xhr){iinqError(xhr.responseText);}});});});
  $('.hide_alert_notif').click(function(){$('.error_data_delete').hide();});
});
</script>
