<?php
if (!function_exists('hr_t')) {
  function hr_t($key, $fallback = '') { return lang_text($key, $fallback); }
}
if (!function_exists('hr_h')) {
  function hr_h($key, $fallback = '') { return htmlspecialchars((string) hr_t($key, $fallback), ENT_QUOTES, 'UTF-8'); }
}
if (!function_exists('hr_js')) {
  function hr_js($key, $fallback = '') { return json_encode(hr_t($key, $fallback), JSON_HEX_TAG | JSON_HEX_APOS | JSON_HEX_AMP | JSON_HEX_QUOT); }
}
$defaultFrom=date('Y-01-01');$defaultTo='9999-12-31';$canInsert=isset($role_act['insert_act'])&&$role_act['insert_act']==='Y'; ?>
<style>
.ef-hero{background:linear-gradient(135deg,#0f766e,#7c3aed);color:#fff;border-radius:14px;padding:20px;margin-bottom:18px;box-shadow:0 10px 24px rgba(15,23,42,.16)}.ef-hero h1{margin:0 0 6px;font-size:26px;font-weight:700}.ef-hero p{margin:0;opacity:.93}.ef-card{border-radius:12px;background:#fff;border:1px solid #e5edf5;box-shadow:0 5px 16px rgba(15,23,42,.05);margin-bottom:14px}.ef-kpi{padding:14px;border-radius:12px;background:#f8fafc;border:1px solid #e5edf5}.ef-kpi b{font-size:22px;display:block}#dtb_employee_family_data th,#dtb_employee_family_data td{font-size:12px;vertical-align:middle}.select2-container{width:100%!important}.required-label:after{content:' *';color:#dd4b39}.ef-action{white-space:nowrap}#modal_employee_family_data .modal-body{max-height:calc(100vh - 185px);overflow-y:auto}
</style>
<section class="content-header"><h1><?=hr_h('hr_employee_family_data', 'Employee Family Data');?> <small>SAP HR Family / Dependent Data</small></h1><ol class="breadcrumb"><li><a href="<?=base_index();?>"><i class="fa fa-dashboard"></i> <?=hr_h('common_home', 'Home');?></a></li><li>Human Resource</li><li>Personnel Administration</li><li class="active"><?=hr_h('hr_employee_family_data', 'Employee Family Data');?></li></ol></section>
<section class="content">
<div class="ef-hero"><div class="row"><div class="col-md-8"><h1>Family Data Workbench</h1><p>Kelola pasangan, anak, orang tua, tanggungan pajak/BPJS, emergency contact, dan dokumen keluarga karyawan.</p></div><div class="col-md-4 text-right"><?php if($canInsert){ ?><button id="btn_open_ef" class="btn btn-warning"><i class="fa fa-plus"></i> Create Family Data</button><?php } ?> <button id="btn_export_ef" class="btn btn-success"><i class="fa fa-file-excel-o"></i> <?=hr_h('common_export_excel', 'Export Excel');?></button></div></div></div>
<div class="row"><div class="col-sm-2"><div class="ef-kpi"><span>Total</span><b id="kpi_total">0</b></div></div><div class="col-sm-2"><div class="ef-kpi"><span><?=hr_h('hr_active', 'Active');?></span><b id="kpi_active">0</b></div></div><div class="col-sm-2"><div class="ef-kpi"><span>Dependent</span><b id="kpi_dependent">0</b></div></div><div class="col-sm-2"><div class="ef-kpi"><span>Emergency</span><b id="kpi_emergency">0</b></div></div><div class="col-sm-2"><div class="ef-kpi"><span>Benefit</span><b id="kpi_benefit">0</b></div></div><div class="col-sm-2"><div class="ef-kpi"><span>Today</span><b><?=date('d M');?></b></div></div></div>
<div class="box ef-card"><div class="box-header"><h3 class="box-title"><i class="fa fa-filter"></i> Filter Family Data</h3></div><div class="box-body"><form class="form-horizontal" onsubmit="return false;"><div class="form-group"><label class="control-label col-lg-2">Effective</label><div class="col-lg-2"><div class="input-group date ef-date"><input id="filter_tgl_awal" class="form-control" value="<?=$defaultFrom;?>"><span class="input-group-addon"><span class="glyphicon glyphicon-calendar"></span></span></div></div><div class="col-lg-2"><div class="input-group date ef-date"><input id="filter_tgl_akhir" class="form-control" value="<?=$defaultTo;?>"><span class="input-group-addon"><span class="glyphicon glyphicon-calendar"></span></span></div></div><label class="control-label col-lg-1">Relation</label><div class="col-lg-2"><select id="filter_relationship_type" class="form-control"><option value=""><?=hr_h('common_all', 'All');?></option><option>SPOUSE</option><option>CHILD</option><option>FATHER</option><option>MOTHER</option><option>SIBLING</option><option>GUARDIAN</option><option>OTHER</option></select></div><label class="control-label col-lg-1"><?=hr_h('common_status', 'Status');?></label><div class="col-lg-2"><select id="filter_status" class="form-control"><option value=""><?=hr_h('common_all', 'All');?></option><option>ACTIVE</option><option>INACTIVE</option></select></div></div><div class="form-group"><label class="control-label col-lg-2">Dependent</label><div class="col-lg-2"><select id="filter_is_dependent" class="form-control"><option value=""><?=hr_h('common_all', 'All');?></option><option>Y</option><option>N</option></select></div><label class="control-label col-lg-1">Emergency</label><div class="col-lg-2"><select id="filter_emergency_contact" class="form-control"><option value=""><?=hr_h('common_all', 'All');?></option><option>Y</option><option>N</option></select></div><label class="control-label col-lg-1"><?=hr_h('common_search', 'Search');?></label><div class="col-lg-4"><input id="filter_keyword" class="form-control" placeholder="Family no, employee, family name, identity no"></div></div><div class="form-group"><div class="col-lg-offset-2 col-lg-10"><button id="btn_filter_ef" class="btn btn-primary"><i class="fa fa-filter"></i> <?=hr_h('common_filter', 'Filter');?></button> <button id="btn_reset_ef" class="btn btn-default"><i class="fa fa-refresh"></i> <?=hr_h('common_reset', 'Reset');?></button></div></div></form></div></div>
<div class="box ef-card"><div class="box-body"><div class="alert alert-warning error_data_delete" style="display:none"><button type="button" class="close hide_alert_notif">&times;</button><span class="isi_warning_delete"></span></div><div class="table-responsive"><table id="dtb_employee_family_data" class="table table-bordered table-striped" style="width:100%"><thead><tr><th><?=hr_h('common_no', 'No');?></th><th><?=hr_h('common_action', 'Action');?></th><th>Family No</th><th><?=hr_h('hr_employee', 'Employee');?></th><th>Relation</th><th>Family Name</th><th>Birth / Identity</th><th>Dependent Flags</th><th>Emergency / Benefit</th><th><?=hr_h('common_status', 'Status');?></th><th>Updated</th></tr></thead><tbody></tbody></table></div></div></div>
<div id="modal_employee_family_data" class="modal fade"><div class="modal-dialog modal-lg" style="width:94%"><div class="modal-content"><form id="form_employee_family_data"><input type="hidden" name="id" id="ef_id"><div class="modal-header"><button type="button" class="close" data-dismiss="modal">&times;</button><h4 class="modal-title">Create Family Data</h4></div><div class="modal-body"><div class="alert alert-info"><strong>SAP hint:</strong> Family data dipakai untuk benefit, pajak, BPJS, administrasi HR, dan emergency contact.</div>
<div class="row"><div class="col-md-2 form-group"><label class="required-label">Family No</label><input name="family_no" id="family_no" class="form-control text-uppercase" required maxlength="30"></div><div class="col-md-4 form-group"><label class="required-label"><?=hr_h('hr_employee', 'Employee');?></label><select name="employee_id" id="employee_id" class="form-control" required></select></div><div class="col-md-2 form-group"><label>Relationship</label><select name="relationship_type" id="relationship_type" class="form-control"><option>SPOUSE</option><option>CHILD</option><option>FATHER</option><option>MOTHER</option><option>SIBLING</option><option>GUARDIAN</option><option>OTHER</option></select></div><div class="col-md-4 form-group"><label class="required-label">Family Name</label><input name="family_name" id="family_name" class="form-control" required maxlength="160"></div></div>
<div class="row"><div class="col-md-2 form-group"><label>Gender</label><select name="gender" id="gender" class="form-control"><option>MALE</option><option>FEMALE</option><option>OTHER</option></select></div><div class="col-md-2 form-group"><label>Birth Place</label><input name="birth_place" id="birth_place" class="form-control"></div><div class="col-md-2 form-group"><label>Birth Date</label><input name="birth_date" id="birth_date" class="form-control date-field"></div><div class="col-md-2 form-group"><label>Marital</label><select name="marital_status" id="marital_status" class="form-control"><option>SINGLE</option><option>MARRIED</option><option>DIVORCED</option><option>WIDOWED</option></select></div><div class="col-md-1 form-group"><label>Nation</label><input name="nationality" id="nationality" class="form-control text-uppercase" value="ID"></div><div class="col-md-3 form-group"><label>Occupation</label><input name="occupation" id="occupation" class="form-control"></div></div>
<div class="row"><div class="col-md-2 form-group"><label>Identity Type</label><select name="identity_type" id="identity_type" class="form-control"><option>KTP</option><option>PASSPORT</option><option>KITAS</option><option>BIRTH_CERTIFICATE</option><option>FAMILY_CARD</option><option>OTHER</option></select></div><div class="col-md-3 form-group"><label>Identity No</label><input name="identity_no" id="identity_no" class="form-control"></div><div class="col-md-3 form-group"><label>Phone</label><input name="phone" id="phone" class="form-control"></div><div class="col-md-4 form-group"><label>Email</label><input name="email" id="email" class="form-control"></div></div>
<div class="row"><div class="col-md-2 form-group"><label>Dependent</label><select name="is_dependent" id="is_dependent" class="form-control"><option>N</option><option>Y</option></select></div><div class="col-md-2 form-group"><label>Tax Dependent</label><select name="tax_dependent" id="tax_dependent" class="form-control"><option>N</option><option>Y</option></select></div><div class="col-md-2 form-group"><label>BPJS</label><select name="bpjs_dependent" id="bpjs_dependent" class="form-control"><option>N</option><option>Y</option></select></div><div class="col-md-2 form-group"><label>Emergency</label><select name="emergency_contact" id="emergency_contact" class="form-control"><option>N</option><option>Y</option></select></div><div class="col-md-2 form-group"><label>Benefit</label><select name="benefit_eligible" id="benefit_eligible" class="form-control"><option>N</option><option>Y</option></select></div><div class="col-md-2 form-group"><label><?=hr_h('common_status', 'Status');?></label><select name="status" id="status" class="form-control"><option>ACTIVE</option><option>INACTIVE</option></select></div></div>
<div class="row"><div class="col-md-2 form-group"><label>Effective From</label><input name="effective_from" id="effective_from" class="form-control date-field" value="<?=$defaultFrom;?>"></div><div class="col-md-2 form-group"><label>Effective To</label><input name="effective_to" id="effective_to" class="form-control date-field" value="<?=$defaultTo;?>"></div><div class="col-md-4 form-group"><label>Document Ref</label><input name="document_ref" id="document_ref" class="form-control"></div><div class="col-md-4 form-group"><label>SAP Reference</label><input name="sap_reference" id="sap_reference" class="form-control"></div></div>
<div class="form-group"><label>Address</label><input name="address" id="address" class="form-control"></div><div class="form-group"><label><?=hr_h('common_remarks', 'Remarks');?></label><textarea name="remarks" id="remarks" class="form-control" rows="3"></textarea></div>
</div><div class="modal-footer"><button type="button" class="btn btn-default" data-dismiss="modal"><?=hr_h('common_cancel', 'Cancel');?></button><button type="submit" class="btn btn-primary"><i class="fa fa-save"></i> Save Family Data</button></div></form></div></div></div>
<div id="modal_ef_detail" class="modal fade"><div class="modal-dialog modal-lg" style="width:92%"><div class="modal-content"><div class="modal-header"><button class="close" data-dismiss="modal">&times;</button><h4 class="modal-title">Family Data Detail</h4></div><div class="modal-body" id="ef_detail_body"></div><div class="modal-footer"><button class="btn btn-default" data-dismiss="modal"><?=hr_h('common_close', 'Close');?></button></div></div></div></div>
</section>
<script src="<?=base_admin();?>assets/plugins/select2/select2.min.js"></script><script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
<script>
function efError(m){$('.isi_warning_delete').text(m||'Employee Family Data gagal diproses.');$('.error_data_delete').fadeIn();}
function efFilters(){return{tgl_awal:$('#filter_tgl_awal').val(),tgl_akhir:$('#filter_tgl_akhir').val(),relationship_type:$('#filter_relationship_type').val(),is_dependent:$('#filter_is_dependent').val(),emergency_contact:$('#filter_emergency_contact').val(),status:$('#filter_status').val(),keyword:$('#filter_keyword').val()};}
function efSet(s,v,t){var e=$(s);if(!v){e.val(null).trigger('change');return;}if(!e.find('option[value="'+v+'"]').length)e.append(new Option(t||v,v,true,true));e.val(v).trigger('change');}
function efReset(title){$('#form_employee_family_data')[0].reset();$('#ef_id').val('');$('#employee_id').val(null).trigger('change');$('#relationship_type,#gender,#marital_status,#identity_type,#is_dependent,#tax_dependent,#bpjs_dependent,#emergency_contact,#benefit_eligible,#status').trigger('change');$('#nationality').val('ID');$('#effective_from').val('<?=$defaultFrom;?>');$('#effective_to').val('<?=$defaultTo;?>');$('#status').val('ACTIVE').trigger('change');$('#modal_employee_family_data .modal-title').text(title||'Create Family Data');}
$(function(){if($.fn.datepicker){$('.ef-date,.date-field').datepicker({format:'yyyy-mm-dd',autoclose:true,todayHighlight:true});}if($.fn.select2){$('#filter_relationship_type,#filter_is_dependent,#filter_emergency_contact,#filter_status,#relationship_type,#gender,#marital_status,#identity_type,#is_dependent,#tax_dependent,#bpjs_dependent,#emergency_contact,#benefit_eligible,#status').select2({width:'100%',allowClear:true});$('#employee_id').select2({width:'100%',allowClear:true,placeholder:'Pilih Employee...',dropdownParent:$('#modal_employee_family_data'),ajax:{url:'<?=base_admin();?>modul/employee_family_data/employee_family_data_action.php?act=employee_search',type:'POST',dataType:'json',delay:250,data:function(p){return{term:p.term||''};},processResults:function(d){return{results:d.results||[]};}}});}
var dt=$('#dtb_employee_family_data').DataTable({bProcessing:true,bServerSide:true,pageLength:25,dom:"<'row'<'col-sm-12'B>>"+"<'row'<'col-sm-6'l><'col-sm-6'f>>"+"<'row'<'col-sm-12'tr>>"+"<'row'<'col-sm-5'i><'col-sm-7'p>>",buttons:[{extend:'collection',text:<?=hr_js('common_export_data', 'Export Data');?>,buttons:['copyHtml5','excelHtml5','csvHtml5','pdfHtml5']}],columnDefs:[{targets:[0,1],orderable:false,searchable:false},{width:'42px',targets:0},{width:'150px',targets:1}],ajax:{url:'<?=base_admin();?>modul/employee_family_data/employee_family_data_data.php',type:'post',data:function(d){$.extend(d,efFilters());},dataSrc:function(j){var k=j.kpi||{};$('#kpi_total').text(k.total||0);$('#kpi_active').text(k.active||0);$('#kpi_dependent').text(k.dependent||0);$('#kpi_emergency').text(k.emergency||0);$('#kpi_benefit').text(k.benefit||0);return j.data||[];},error:function(x){console.log(x.responseText);efError('Data Employee Family gagal dimuat.');}}});
$('#btn_open_ef').click(function(){efReset('Create Family Data');$('#modal_employee_family_data').modal({backdrop:'static',keyboard:false});});$('#btn_filter_ef').click(function(){dt.draw();});$('#filter_keyword').keyup(function(e){if(e.keyCode===13)dt.draw();});$('#btn_reset_ef').click(function(){$('#filter_tgl_awal').val('<?=$defaultFrom;?>');$('#filter_tgl_akhir').val('<?=$defaultTo;?>');$('#filter_relationship_type,#filter_is_dependent,#filter_emergency_contact,#filter_status').val(null).trigger('change');$('#filter_keyword').val('');dt.draw();});$('#btn_export_ef').click(function(){window.location='<?=base_admin();?>modul/employee_family_data/employee_family_data_action.php?act=export&'+$.param(efFilters());});$('.hide_alert_notif').click(function(){$('.error_data_delete').hide();});$('#family_no,#nationality').on('keyup change',function(){this.value=this.value.toUpperCase();});
$('#form_employee_family_data').submit(function(e){e.preventDefault();var b=$(this).find('button[type=submit]');b.prop('disabled',true).html('<i class="fa fa-spinner fa-spin"></i> <?=hr_h('common_saving', 'Saving...');?>');$.post('<?=base_admin();?>modul/employee_family_data/employee_family_data_action.php?act=save',$(this).serialize(),function(r){b.prop('disabled',false).html('<i class="fa fa-save"></i> Save Family Data');if(r.status==='good'){$('#modal_employee_family_data').modal('hide');dt.draw(false);Swal.fire('Saved','Employee Family Data berhasil disimpan.','success');}else efError(r.error_message);},'json').fail(function(x){b.prop('disabled',false).html('<i class="fa fa-save"></i> Save Family Data');efError(x.responseText);});});
$(document).on('click','.btn-ef-detail',function(){$.post('<?=base_admin();?>modul/employee_family_data/employee_family_data_action.php?act=detail',{id:$(this).data('id')},function(h){$('#ef_detail_body').html(h);$('#modal_ef_detail').modal('show');});});
$(document).on('click','.btn-ef-edit',function(){var id=$(this).data('id');$.post('<?=base_admin();?>modul/employee_family_data/employee_family_data_action.php?act=get',{id:id},function(r){if(r.status!=='good'){efError(r.error_message);return;}efReset('Edit Family Data');var h=r.data||{};Object.keys(h).forEach(function(k){var el=$('#'+k);if(el.length&&k!=='employee_id')el.val(h[k]);});$('#ef_id').val(h.id);efSet('#employee_id',h.employee_id,h.employee_text);$('#relationship_type,#gender,#marital_status,#identity_type,#is_dependent,#tax_dependent,#bpjs_dependent,#emergency_contact,#benefit_eligible,#status').trigger('change');$('#modal_employee_family_data').modal({backdrop:'static',keyboard:false});},'json');});
$(document).on('click','.btn-ef-status',function(){var id=$(this).data('id'),status=$(this).data('status');$.post('<?=base_admin();?>modul/employee_family_data/employee_family_data_action.php?act=status',{id:id,status:status},function(r){if(r.status==='good'){dt.draw(false);Swal.fire('Updated','Status berhasil diubah.','success');}else efError(r.error_message);},'json');});
$(document).on('click','.btn-ef-delete',function(){var id=$(this).data('id'),no=$(this).data('no');Swal.fire({title:erpLang('confirm_delete_title','Delete Confirmation'),text:no,icon:'warning',showCancelButton:true,confirmButtonText:erpLang('common_delete','Delete'),cancelButtonText:erpLang('common_cancel','Cancel')}).then(function(x){if(!x.isConfirmed)return;$.post('<?=base_admin();?>modul/employee_family_data/employee_family_data_action.php?act=delete',{id:id},function(r){if(r.status==='good'){dt.draw(false);Swal.fire(erpLang('common_deleted','Deleted'),erpLang('common_deleted_message','Data deleted successfully.'),'success');}else efError(r.error_message);},'json').fail(function(x){efError(x.responseText);});});});
});
</script>
