<?php
if (!function_exists('hr_t')) {
  function hr_t($key, $fallback = '') { return lang_text($key, $fallback); }
}
if (!function_exists('hr_h')) {
  function hr_h($key, $fallback = '') { return htmlspecialchars((string) hr_t($key, $fallback), ENT_QUOTES, 'UTF-8'); }
}
if (!function_exists('hr_js')) {
  function hr_js($key, $fallback = '') { return json_encode(hr_t($key, $fallback), JSON_HEX_TAG | JSON_HEX_APOS | JSON_HEX_AMP | JSON_HEX_QUOT); }
}
if (session_status() === PHP_SESSION_NONE) session_start();
include "../../inc/config.php";
session_check_json();
function ef_json($s,$m='',$x=array()){header('Content-Type: application/json; charset=utf-8');$p=array('status'=>$s);if($m!=='')$p[$s==='good'?'message':'error_message']=$m;foreach($x as $k=>$v)$p[$k]=$v;echo json_encode($p);exit;}
function ef_h($v){return htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');}
function ef_p($k,$d=''){return isset($_POST[$k])?$_POST[$k]:$d;}
function ef_g($k,$d=''){return isset($_GET[$k])?$_GET[$k]:$d;}
function ef_c($v){return strtoupper(trim((string)$v));}
function ef_user(){return isset($_SESSION['username'])&&$_SESSION['username']!==''?$_SESSION['username']:'system';}
function ef_select2($rows,$id,$cb){$out=array();foreach($rows as $r)$out[]=array('id'=>$r->$id,'text'=>$cb($r));header('Content-Type: application/json; charset=utf-8');echo json_encode(array('results'=>$out));exit;}
function ef_row($id){global $db;return $db->fetch("SELECT f.*,e.employee_no,e.full_name,e.department_code,d.nm_dept,j.job_title_code,j.job_title_name FROM erp_employee_family_data f JOIN erp_employee_master e ON e.id=f.employee_id LEFT JOIN dept d ON d.kd_dept=e.department_code LEFT JOIN erp_job_title j ON j.id=e.job_title_id WHERE f.id=? LIMIT 1",array((int)$id));}
function ef_payload($r){$d=(array)$r;$d['employee_text']=$r->employee_id?($r->employee_no.' - '.$r->full_name):'';return $d;}
function ef_rows($from,$to,$rel,$dep,$emergency,$status,$kw){global $db;$w=" WHERE f.effective_from<=? AND f.effective_to>=? ";$p=array($to,$from);if($rel!==''){$w.=" AND f.relationship_type=? ";$p[]=$rel;}if($dep!==''){$w.=" AND f.is_dependent=? ";$p[]=$dep;}if($emergency!==''){$w.=" AND f.emergency_contact=? ";$p[]=$emergency;}if($status!==''){$w.=" AND f.status=? ";$p[]=$status;}if($kw!==''){$like='%'.$kw.'%';$w.=" AND (f.family_no LIKE ? OR f.family_name LIKE ? OR e.employee_no LIKE ? OR e.full_name LIKE ? OR f.identity_no LIKE ?) ";array_push($p,$like,$like,$like,$like,$like);}return $db->query("SELECT f.*,e.employee_no,e.full_name,e.department_code,d.nm_dept,j.job_title_code,j.job_title_name FROM erp_employee_family_data f JOIN erp_employee_master e ON e.id=f.employee_id LEFT JOIN dept d ON d.kd_dept=e.department_code LEFT JOIN erp_job_title j ON j.id=e.job_title_id $w ORDER BY e.employee_no,f.relationship_type,f.family_name",$p);}
$act=isset($_GET['act'])?$_GET['act']:'';$username=ef_user();
$rels=array('SPOUSE','CHILD','FATHER','MOTHER','SIBLING','GUARDIAN','OTHER');$genders=array('MALE','FEMALE','OTHER');$maritals=array('SINGLE','MARRIED','DIVORCED','WIDOWED');$ids=array('KTP','PASSPORT','KITAS','BIRTH_CERTIFICATE','FAMILY_CARD','OTHER');
switch($act){
case 'employee_search':$t=trim(ef_p('term'));$like='%'.$t.'%';$rows=$db->query("SELECT id,employee_no,full_name,employment_status FROM erp_employee_master WHERE employment_status IN ('ACTIVE','PROBATION','CONTRACT') AND (?='' OR employee_no LIKE ? OR full_name LIKE ?) ORDER BY employee_no LIMIT 30",array($t,$like,$like));ef_select2($rows,'id',function($r){return $r->employee_no.' - '.$r->full_name.' ['.$r->employment_status.']';});break;
case 'get':$r=ef_row((int)ef_p('id'));if(!$r)ef_json('error','Employee Family Data tidak ditemukan.');ef_json('good','',array('data'=>ef_payload($r)));break;
case 'save':
  $id=(int)ef_p('id');$no=ef_c(ef_p('family_no'));$emp=(int)ef_p('employee_id');$rel=ef_c(ef_p('relationship_type'));$name=trim(ef_p('family_name'));$gender=ef_c(ef_p('gender','MALE'));$marital=ef_c(ef_p('marital_status','SINGLE'));$identity=ef_c(ef_p('identity_type','KTP'));$from=trim(ef_p('effective_from'));$to=trim(ef_p('effective_to','9999-12-31'));$status=ef_c(ef_p('status','ACTIVE'));
  if($no==='')ef_json('error','Family No wajib diisi.');if(!preg_match('/^[A-Z0-9_-]{3,30}$/',$no))ef_json('error','Family No hanya boleh huruf besar, angka, underscore, atau dash.');if(!$emp)ef_json('error','Employee wajib dipilih.');if($name==='')ef_json('error','Family Name wajib diisi.');if(!in_array($rel,$rels,true))ef_json('error','Relationship Type tidak valid.');if(!in_array($gender,$genders,true))ef_json('error','Gender tidak valid.');if(!in_array($marital,$maritals,true))ef_json('error','Marital Status tidak valid.');if(!in_array($identity,$ids,true))ef_json('error','Identity Type tidak valid.');if($from===''||$to==='')ef_json('error','Effective From/To wajib diisi.');if(strtotime($to)<strtotime($from))ef_json('error','Effective To tidak boleh sebelum Effective From.');if(!in_array($status,array('ACTIVE','INACTIVE'),true))ef_json('error','Status tidak valid.');
  if(!$db->fetch("SELECT id FROM erp_employee_master WHERE id=? LIMIT 1",array($emp)))ef_json('error','Employee tidak valid.');if($db->fetch("SELECT id FROM erp_employee_family_data WHERE family_no=? AND id<>? LIMIT 1",array($no,$id)))ef_json('error','Family No sudah digunakan.');
  $yn=array('Y','N');$dep=ef_c(ef_p('is_dependent','N'));$tax=ef_c(ef_p('tax_dependent','N'));$bpjs=ef_c(ef_p('bpjs_dependent','N'));$emer=ef_c(ef_p('emergency_contact','N'));$benefit=ef_c(ef_p('benefit_eligible','N'));foreach(array($dep,$tax,$bpjs,$emer,$benefit) as $v){if(!in_array($v,$yn,true))ef_json('error','Flag Y/N tidak valid.');}
  $data=array('family_no'=>$no,'employee_id'=>$emp,'relationship_type'=>$rel,'family_name'=>$name,'gender'=>$gender,'birth_place'=>trim(ef_p('birth_place')),'birth_date'=>trim(ef_p('birth_date'))?:null,'marital_status'=>$marital,'nationality'=>ef_c(ef_p('nationality','ID')),'identity_type'=>$identity,'identity_no'=>trim(ef_p('identity_no')),'occupation'=>trim(ef_p('occupation')),'phone'=>trim(ef_p('phone')),'email'=>trim(ef_p('email')),'address'=>trim(ef_p('address')),'is_dependent'=>$dep,'tax_dependent'=>$tax,'bpjs_dependent'=>$bpjs,'emergency_contact'=>$emer,'benefit_eligible'=>$benefit,'effective_from'=>$from,'effective_to'=>$to,'document_ref'=>trim(ef_p('document_ref')),'status'=>$status,'sap_reference'=>trim(ef_p('sap_reference')),'remarks'=>trim(ef_p('remarks')),'updated_by'=>$username,'updated_at'=>date('Y-m-d H:i:s'));
  if($id>0){if(!$db->fetch("SELECT id FROM erp_employee_family_data WHERE id=? LIMIT 1",array($id)))ef_json('error','Employee Family Data tidak ditemukan.');$ok=$db->update('erp_employee_family_data',$data,'id',$id);}else{$data['created_by']=$username;$ok=$db->insert('erp_employee_family_data',$data);$id=$db->last_insert_id();}
  if(!$ok)ef_json('error',$db->getErrorMessage()?:'Employee Family Data gagal disimpan.');if(function_exists('simpan_log'))simpan_log('User '.$username.' menyimpan Employee Family Data '.$no.' untuk '.$name.' pada '.date('Y-m-d H:i:s'),$username);ef_json('good','Employee Family Data berhasil disimpan.',array('id'=>$id));
case 'delete':$id=(int)ef_p('id');$r=$db->fetch("SELECT * FROM erp_employee_family_data WHERE id=? LIMIT 1",array($id));if(!$r)ef_json('error','Employee Family Data tidak ditemukan.');$db->delete('erp_employee_family_data','id',$id);if($db->getErrorMessage())ef_json('error',$db->getErrorMessage());if(function_exists('simpan_log'))simpan_log('User '.$username.' menghapus Employee Family Data '.$r->family_no,$username);ef_json('good','Employee Family Data berhasil dihapus.');
case 'status':$id=(int)ef_p('id');$status=ef_c(ef_p('status'));if(!in_array($status,array('ACTIVE','INACTIVE'),true))ef_json('error','Status tidak valid.');$r=$db->fetch("SELECT * FROM erp_employee_family_data WHERE id=? LIMIT 1",array($id));if(!$r)ef_json('error','Employee Family Data tidak ditemukan.');$ok=$db->update('erp_employee_family_data',array('status'=>$status,'updated_by'=>$username,'updated_at'=>date('Y-m-d H:i:s')),'id',$id);if(!$ok)ef_json('error',$db->getErrorMessage()?:'Status gagal diubah.');ef_json('good','Status berhasil diubah.');
case 'detail':$r=ef_row((int)ef_p('id'));if(!$r){echo '<div class="alert alert-warning">Employee Family Data tidak ditemukan.</div>';break;}echo '<h3 style="margin-top:0">'.ef_h($r->family_no).' <small>'.ef_h($r->family_name).'</small></h3><span class="label label-success">'.ef_h($r->status).'</span> <span class="label label-info">'.ef_h($r->relationship_type).'</span><hr>';echo '<div class="row"><div class="col-sm-3"><b>'.hr_h('hr_employee', 'Employee').'</b><br>'.ef_h($r->employee_no.' - '.$r->full_name).'</div><div class="col-sm-3"><b>Birth</b><br>'.ef_h(($r->birth_place?:'-').', '.($r->birth_date?:'-')).'</div><div class="col-sm-3"><b>Identity</b><br>'.ef_h($r->identity_type.' '.$r->identity_no).'</div><div class="col-sm-3"><b>Effective</b><br>'.ef_h($r->effective_from.' s/d '.$r->effective_to).'</div></div><hr>';echo '<div class="row"><div class="col-sm-2"><b>Dependent</b><br>'.ef_h($r->is_dependent).'</div><div class="col-sm-2"><b>Tax</b><br>'.ef_h($r->tax_dependent).'</div><div class="col-sm-2"><b>BPJS</b><br>'.ef_h($r->bpjs_dependent).'</div><div class="col-sm-2"><b>Emergency</b><br>'.ef_h($r->emergency_contact).'</div><div class="col-sm-2"><b>Benefit</b><br>'.ef_h($r->benefit_eligible).'</div><div class="col-sm-2"><b>Phone</b><br>'.ef_h($r->phone?:'-').'</div></div><hr><b>Address</b><p>'.ef_h($r->address?:'-').'</p><b>'.hr_h('common_remarks', 'Remarks').'</b><p>'.nl2br(ef_h($r->remarks?:'-')).'</p>';break;
case 'export':
  $initial=ob_get_level();ob_start();error_reporting(E_ALL & ~E_NOTICE & ~E_WARNING & ~E_DEPRECATED & ~E_USER_DEPRECATED);require_once "../../inc/lib/PHPExcel.php";require_once "../../inc/excel_style_helper.php";PHPExcel_Shared_File::setUseUploadTempDirectory(true);$from=ef_g('tgl_awal',date('Y-01-01'));$to=ef_g('tgl_akhir','9999-12-31');$rows=ef_rows($from,$to,ef_g('relationship_type',''),ef_g('is_dependent',''),ef_g('emergency_contact',''),ef_g('status',''),ef_g('keyword',''));$excel=new PHPExcel();$sheet=$excel->setActiveSheetIndex(0);$sheet->setTitle(erp_export_sheet_title('Family Data'));$heads=array(erp_export_label("No"),erp_export_label("Family No"),erp_export_label("Employee"),erp_export_label("Relationship"),erp_export_label("Family Name"),erp_export_label("Gender"),erp_export_label("Birth"),erp_export_label("Identity"),erp_export_label("Occupation"),erp_export_label("Phone"),erp_export_label("Dependent"),erp_export_label("Tax"),erp_export_label("BPJS"),erp_export_label("Emergency"),erp_export_label("Benefit"),erp_export_label("Effective"),erp_export_label("Status"),erp_export_label("Document"),erp_export_label("SAP Ref"),erp_export_label("Updated By"));foreach($heads as $i=>$h)$sheet->setCellValue(PHPExcel_Cell::stringFromColumnIndex($i).'4',$h);$rnum=5;$n=1;foreach($rows as $r){$vals=array($n++,$r->family_no,$r->employee_no.' - '.$r->full_name,$r->relationship_type,$r->family_name,$r->gender,($r->birth_place?:'-').', '.($r->birth_date?:'-'),$r->identity_type.' '.$r->identity_no,$r->occupation,$r->phone,$r->is_dependent,$r->tax_dependent,$r->bpjs_dependent,$r->emergency_contact,$r->benefit_eligible,$r->effective_from.' s/d '.$r->effective_to,$r->status,$r->document_ref,$r->sap_reference,$r->updated_by?:$r->created_by);foreach($vals as $i=>$v)$sheet->setCellValue(PHPExcel_Cell::stringFromColumnIndex($i).$rnum,$v);$rnum++;}erpkb_excel_apply_standard_style($excel,array('sheet'=>$sheet,'title'=>erp_export_title('EMPLOYEE FAMILY DATA REPORT'),'header_row'=>4,'first_data_row'=>5,'last_data_row'=>max(5,$rnum-1),'column_count'=>count($heads),'filters'=>array('Effective'=>$from.' s/d '.$to)));$tmp=erpkb_excel_temp_file('employee_family_data_');PHPExcel_IOFactory::createWriter($excel,'Excel2007')->save($tmp);$size=@filesize($tmp);$sig=@file_get_contents($tmp,false,null,0,2);if(!$size||$sig!=='PK'){@unlink($tmp);while(ob_get_level()>$initial)ob_end_clean();echo erp_t('export_excel_invalid_file','File Excel gagal dibuat dengan benar.');exit;}while(ob_get_level()>$initial)ob_end_clean();header('Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');header('Content-Disposition: attachment; filename="employee_family_data_'.date('Ymd_His').'.xlsx"');header('Content-Length: '.$size);header('Cache-Control: max-age=0');header('Pragma: public');readfile($tmp);@unlink($tmp);exit;
default:ef_json('error','Action tidak dikenal.');
}
?>
