<?php
if (!function_exists('hr_t')) {
  function hr_t($key, $fallback = '') { return lang_text($key, $fallback); }
}
if (!function_exists('hr_h')) {
  function hr_h($key, $fallback = '') { return htmlspecialchars((string) hr_t($key, $fallback), ENT_QUOTES, 'UTF-8'); }
}
if (!function_exists('hr_js')) {
  function hr_js($key, $fallback = '') { return json_encode(hr_t($key, $fallback), JSON_HEX_TAG | JSON_HEX_APOS | JSON_HEX_AMP | JSON_HEX_QUOT); }
}
$defaultFrom=date('Y-01-01');$defaultTo=date('Y-12-31');$canInsert=isset($insert_act)&&$insert_act==='Y'; ?>
<style>
.ap-hero{background:linear-gradient(135deg,#0f766e,#7c3aed);color:#fff;border-radius:14px;padding:22px;margin-bottom:14px;box-shadow:0 8px 24px rgba(15,118,110,.18)}.ap-hero h1{margin:0 0 6px;font-weight:700}.ap-hero p{margin:0;color:#ecfeff}.ap-card{border-radius:12px;border:1px solid #e5edf5;box-shadow:0 4px 14px rgba(15,23,42,.05)}.ap-kpi{background:#fff;border:1px solid #e5edf5;border-radius:12px;padding:13px;margin-bottom:14px}.ap-kpi span{font-size:12px;color:#64748b}.ap-kpi b{display:block;font-size:21px;color:#0f172a}#dtb_applicant_data th,#dtb_applicant_data td{font-size:12px;vertical-align:middle}.ap-action{white-space:nowrap}.select2-container{width:100%!important}.required-label:after{content:' *';color:#dd4b39}#modal_ap .modal-body{max-height:calc(100vh - 180px);overflow-y:auto}.ap-section{font-weight:700;color:#334155;border-bottom:1px solid #e5e7eb;padding-bottom:7px;margin:8px 0 12px}
</style>
<section class="content-header"><h1><?=hr_h('hr_applicant_data', 'Applicant Data');?> <small>SAP HCM Recruitment</small></h1><ol class="breadcrumb"><li><a href="<?=base_index();?>"><i class="fa fa-dashboard"></i> <?=hr_h('common_home', 'Home');?></a></li><li>Human Resource</li><li>Recruitment</li><li class="active"><?=hr_h('hr_applicant_data', 'Applicant Data');?></li></ol></section>
<section class="content">
<div class="ap-hero"><div class="row"><div class="col-md-8"><h1>Applicant Data Cockpit</h1><p>Kelola data kandidat, CV, sumber pelamar, scoring, screening, interview, offer, dan status hiring dalam satu tampilan recruitment pipeline.</p></div><div class="col-md-4 text-right"><?php if($canInsert){ ?><button id="btn_open_ap" class="btn btn-warning"><i class="fa fa-plus"></i> Create Applicant</button><?php } ?> <button id="btn_export_ap" class="btn btn-success"><i class="fa fa-file-excel-o"></i> <?=hr_h('common_export_excel', 'Export Excel');?></button></div></div></div>
<div class="row"><div class="col-sm-2"><div class="ap-kpi"><span>Total</span><b id="kpi_total">0</b></div></div><div class="col-sm-2"><div class="ap-kpi"><span>New</span><b id="kpi_new">0</b></div></div><div class="col-sm-2"><div class="ap-kpi"><span>In Process</span><b id="kpi_process">0</b></div></div><div class="col-sm-2"><div class="ap-kpi"><span>Offer</span><b id="kpi_offer">0</b></div></div><div class="col-sm-2"><div class="ap-kpi"><span>Hired</span><b id="kpi_hired">0</b></div></div><div class="col-sm-2"><div class="ap-kpi"><span>Avg Score</span><b id="kpi_avg_score">0</b></div></div></div>
<div class="box ap-card"><div class="box-header"><h3 class="box-title"><i class="fa fa-filter"></i> Filter Applicant</h3></div><div class="box-body"><form class="form-horizontal" onsubmit="return false;"><div class="form-group"><label class="control-label col-lg-2">Application Date</label><div class="col-lg-2"><div class="input-group date ap-date"><input id="filter_tgl_awal" class="form-control" value="<?=$defaultFrom;?>"><span class="input-group-addon"><span class="glyphicon glyphicon-calendar"></span></span></div></div><div class="col-lg-2"><div class="input-group date ap-date"><input id="filter_tgl_akhir" class="form-control" value="<?=$defaultTo;?>"><span class="input-group-addon"><span class="glyphicon glyphicon-calendar"></span></span></div></div><label class="control-label col-lg-1"><?=hr_h('common_status', 'Status');?></label><div class="col-lg-2"><select id="filter_applicant_status" class="form-control"><option value=""><?=hr_h('common_all', 'All');?></option><option>NEW</option><option>SCREENING</option><option>SHORTLISTED</option><option>INTERVIEW</option><option>OFFER</option><option>HIRED</option><option>REJECTED</option><option>WITHDRAWN</option><option>BLACKLISTED</option></select></div><label class="control-label col-lg-1">Source</label><div class="col-lg-2"><select id="filter_source_channel" class="form-control"></select></div></div><div class="form-group"><label class="control-label col-lg-2">Vacancy</label><div class="col-lg-3"><select id="filter_vacancy_id" class="form-control"></select></div><div class="col-lg-5"><input id="filter_keyword" class="form-control" placeholder="Applicant no, name, email, phone, vacancy"></div><div class="col-lg-2"><button id="btn_filter_ap" class="btn btn-primary"><i class="fa fa-filter"></i> <?=hr_h('common_filter', 'Filter');?></button> <button id="btn_reset_ap" class="btn btn-default"><i class="fa fa-refresh"></i></button></div></div></form></div></div>
<div class="box ap-card"><div class="box-body"><div class="alert alert-warning error_data_delete" style="display:none"><button type="button" class="close hide_alert_notif">&times;</button><span class="isi_warning_delete"></span></div><div class="table-responsive"><table id="dtb_applicant_data" class="table table-bordered table-striped" style="width:100%"><thead><tr><th><?=hr_h('common_no', 'No');?></th><th><?=hr_h('common_action', 'Action');?></th><th>Applicant No</th><th><?=hr_h('hr_applicant', 'Applicant');?></th><th>Vacancy</th><th>Education</th><th>Experience</th><th><?=hr_h('hr_score', 'Score');?></th><th>Application</th><th><?=hr_h('common_status', 'Status');?></th><th>Updated</th></tr></thead><tbody></tbody></table></div></div></div>
<div id="modal_ap" class="modal fade"><div class="modal-dialog modal-lg" style="width:96%"><div class="modal-content"><form id="form_ap"><input type="hidden" name="id" id="ap_id"><div class="modal-header"><button type="button" class="close" data-dismiss="modal">&times;</button><h4 class="modal-title">Create Applicant</h4></div><div class="modal-body">
<div class="alert alert-info"><strong>SAP hint:</strong> Applicant Data adalah kandidat per vacancy. Status applicant akan otomatis memperbarui pipeline count pada Job Vacancy.</div>
<div class="ap-section">Application Assignment</div><div class="row"><div class="col-md-2 form-group"><label class="required-label">Applicant No</label><div class="input-group"><input name="applicant_no" id="applicant_no" class="form-control" readonly><span class="input-group-btn"><button type="button" id="btn_next_ap" class="btn btn-default"><i class="fa fa-refresh"></i></button></span></div></div><div class="col-md-4 form-group"><label class="required-label">Applicant Name</label><input name="applicant_name" id="applicant_name" class="form-control" required maxlength="160"></div><div class="col-md-3 form-group"><label>Vacancy</label><select name="vacancy_id" id="vacancy_id" class="form-control"></select></div><div class="col-md-3 form-group"><label><?=hr_h('common_status', 'Status');?></label><select name="applicant_status" id="applicant_status" class="form-control"><option>NEW</option><option>SCREENING</option><option>SHORTLISTED</option><option>INTERVIEW</option><option>OFFER</option><option>HIRED</option><option>REJECTED</option><option>WITHDRAWN</option><option>BLACKLISTED</option></select></div></div>
<div class="row"><div class="col-md-2 form-group"><label class="required-label">Application Date</label><input name="application_date" id="application_date" class="form-control date-field" value="<?=date('Y-m-d');?>"></div><div class="col-md-2 form-group"><label>Available Start</label><input name="available_start_date" id="available_start_date" class="form-control date-field"></div><div class="col-md-2 form-group"><label>Source Channel</label><input name="source_channel" id="source_channel" class="form-control"></div><div class="col-md-3 form-group"><label>Recruiter</label><select name="recruiter_employee_id" id="recruiter_employee_id" class="form-control"></select></div><div class="col-md-3 form-group"><label>Referred By</label><select name="referred_by_employee_id" id="referred_by_employee_id" class="form-control"></select></div></div>
<div class="ap-section">Personal Data</div><div class="row"><div class="col-md-2 form-group"><label>Gender</label><select name="gender" id="gender" class="form-control"><option>OTHER</option><option>MALE</option><option>FEMALE</option></select></div><div class="col-md-2 form-group"><label>Birth Place</label><input name="birth_place" id="birth_place" class="form-control"></div><div class="col-md-2 form-group"><label>Birth Date</label><input name="birth_date" id="birth_date" class="form-control date-field"></div><div class="col-md-1 form-group"><label>Nation</label><input name="nationality" id="nationality" class="form-control" value="ID"></div><div class="col-md-2 form-group"><label>ID Type</label><select name="identity_type" id="identity_type" class="form-control"><option>KTP</option><option>PASSPORT</option><option>KITAS</option><option>OTHER</option></select></div><div class="col-md-3 form-group"><label>ID No</label><input name="identity_no" id="identity_no" class="form-control"></div></div>
<div class="row"><div class="col-md-3 form-group"><label>Email</label><input name="email" id="email" type="email" class="form-control"></div><div class="col-md-2 form-group"><label>Phone</label><input name="phone" id="phone" class="form-control"></div><div class="col-md-4 form-group"><label>Address</label><input name="address" id="address" class="form-control"></div><div class="col-md-2 form-group"><label>City</label><input name="city" id="city" class="form-control"></div><div class="col-md-1 form-group"><label>Postal</label><input name="postal_code" id="postal_code" class="form-control"></div></div>
<div class="ap-section">Education & Experience</div><div class="row"><div class="col-md-2 form-group"><label>Education</label><select name="education_level" id="education_level" class="form-control"><option>S1</option><option>SMA_SMK</option><option>DIPLOMA</option><option>S2</option><option>S3</option><option>OTHER</option></select></div><div class="col-md-3 form-group"><label>Major</label><input name="major" id="major" class="form-control"></div><div class="col-md-3 form-group"><label>University / School</label><input name="university" id="university" class="form-control"></div><div class="col-md-2 form-group"><label>Grad Year</label><input name="graduation_year" id="graduation_year" type="number" class="form-control"></div><div class="col-md-2 form-group"><label>GPA</label><input name="gpa" id="gpa" type="number" step="0.01" min="0" max="4" class="form-control"></div></div>
<div class="row"><div class="col-md-3 form-group"><label>Current Company</label><input name="current_company" id="current_company" class="form-control"></div><div class="col-md-3 form-group"><label>Current Position</label><input name="current_position" id="current_position" class="form-control"></div><div class="col-md-2 form-group"><label>Experience Years</label><input name="years_experience" id="years_experience" type="number" step="0.01" min="0" class="form-control" value="0"></div><div class="col-md-2 form-group"><label>Expected Salary</label><input name="expected_salary" id="expected_salary" type="number" step="0.01" min="0" class="form-control" value="0"></div><div class="col-md-2 form-group"><label>Currency</label><select name="currency" id="currency" class="form-control"><option>IDR</option><option>USD</option><option>EUR</option></select></div></div>
<div class="ap-section">Assessment</div><div class="row"><div class="col-md-2 form-group"><label>Screen Score</label><input name="screening_score" id="screening_score" type="number" step="0.01" min="0" max="100" class="form-control" value="0"></div><div class="col-md-2 form-group"><label>Interview Score</label><input name="interview_score" id="interview_score" type="number" step="0.01" min="0" max="100" class="form-control" value="0"></div><div class="col-md-2 form-group"><label>Final Score</label><input name="final_score" id="final_score" type="number" step="0.01" min="0" max="100" class="form-control" value="0"></div><div class="col-md-3 form-group"><label>Hired Employee</label><select name="hired_employee_id" id="hired_employee_id" class="form-control"></select></div><div class="col-md-3 form-group"><label>Rejection Reason</label><input name="rejection_reason" id="rejection_reason" class="form-control"></div></div>
<div class="row"><div class="col-md-3 form-group"><label>CV Reference</label><input name="cv_reference" id="cv_reference" class="form-control" placeholder="Path/link CV"></div><div class="col-md-3 form-group"><label>Portfolio URL</label><input name="portfolio_url" id="portfolio_url" class="form-control"></div><div class="col-md-3 form-group"><label>LinkedIn URL</label><input name="linkedin_url" id="linkedin_url" class="form-control"></div><div class="col-md-3 form-group"><label>SAP Reference</label><input name="sap_reference" id="sap_reference" class="form-control"></div></div>
<div class="row"><div class="col-md-4 form-group"><label>Skills</label><textarea name="skills" id="skills" rows="3" class="form-control"></textarea></div><div class="col-md-4 form-group"><label>Screening Notes</label><textarea name="screening_notes" id="screening_notes" rows="3" class="form-control"></textarea></div><div class="col-md-4 form-group"><label>Interview Notes</label><textarea name="interview_notes" id="interview_notes" rows="3" class="form-control"></textarea></div></div><div class="form-group"><label><?=hr_h('common_remarks', 'Remarks');?></label><textarea name="remarks" id="remarks" rows="2" class="form-control"></textarea></div>
</div><div class="modal-footer"><button type="button" class="btn btn-default" data-dismiss="modal"><?=hr_h('common_cancel', 'Cancel');?></button><button type="submit" class="btn btn-primary"><i class="fa fa-save"></i> Save Applicant</button></div></form></div></div></div>
<div id="modal_ap_detail" class="modal fade"><div class="modal-dialog modal-lg" style="width:94%"><div class="modal-content"><div class="modal-header"><button class="close" data-dismiss="modal">&times;</button><h4 class="modal-title">Applicant Detail</h4></div><div class="modal-body" id="ap_detail_body"></div><div class="modal-footer"><button class="btn btn-default" data-dismiss="modal"><?=hr_h('common_close', 'Close');?></button></div></div></div></div>
</section>
<script src="<?=base_admin();?>assets/plugins/select2/select2.min.js"></script><script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
<script>
function apError(m){$('.isi_warning_delete').text(m||'Applicant gagal diproses.');$('.error_data_delete').fadeIn();}
function apFilters(){return{tgl_awal:$('#filter_tgl_awal').val(),tgl_akhir:$('#filter_tgl_akhir').val(),applicant_status:$('#filter_applicant_status').val(),vacancy_id:$('#filter_vacancy_id').val(),source_channel:$('#filter_source_channel').val(),keyword:$('#filter_keyword').val()};}
function apSet(s,v,t){var e=$(s);if(!v){e.val(null).trigger('change');return;}if(!e.find('option[value="'+v+'"]').length)e.append(new Option(t||v,v,true,true));e.val(v).trigger('change');}
function apAjaxSelect(selector,act,placeholder,parent){$(selector).select2({width:'100%',allowClear:true,placeholder:placeholder,dropdownParent:parent||$(document.body),ajax:{url:'<?=base_admin();?>modul/applicant_data/applicant_data_action.php?act='+act,type:'POST',dataType:'json',delay:250,data:function(q){return{term:q.term||''};},processResults:function(d){return{results:d.results||[]};}}});}
function loadNextAp(){ $.post('<?=base_admin();?>modul/applicant_data/applicant_data_action.php?act=next_no',{year:($('#application_date').val()||'<?=date('Y');?>').substr(0,4)},function(r){ if(r.status==='good')$('#applicant_no').val(r.applicant_no); },'json'); }
function resetAp(title){$('#form_ap')[0].reset();$('#ap_id').val('');$('#application_date').val('<?=date('Y-m-d');?>');$('#nationality').val('ID');$('#applicant_status').val('NEW').trigger('change');$('#gender').val('OTHER').trigger('change');$('#identity_type').val('KTP').trigger('change');$('#education_level').val('S1').trigger('change');$('#currency').val('IDR').trigger('change');$('#vacancy_id,#recruiter_employee_id,#referred_by_employee_id,#hired_employee_id').val(null).trigger('change');$('#years_experience,#expected_salary,#screening_score,#interview_score,#final_score').val(0);$('#modal_ap .modal-title').text(title||'Create Applicant');loadNextAp();}
$(function(){if($.fn.datepicker){$('.ap-date,.date-field').datepicker({format:'yyyy-mm-dd',autoclose:true,todayHighlight:true});}if($.fn.select2){$('#filter_applicant_status,#applicant_status,#gender,#identity_type,#education_level,#currency').select2({width:'100%',allowClear:true});apAjaxSelect('#filter_vacancy_id','vacancy_search','Semua Vacancy');apAjaxSelect('#filter_source_channel','source_search','Semua Source');apAjaxSelect('#vacancy_id','vacancy_search','Pilih Vacancy',$('#modal_ap'));apAjaxSelect('#recruiter_employee_id','employee_search','Pilih Recruiter',$('#modal_ap'));apAjaxSelect('#referred_by_employee_id','employee_search','Pilih Referred By',$('#modal_ap'));apAjaxSelect('#hired_employee_id','employee_search','Pilih Hired Employee',$('#modal_ap'));}
var dt=$('#dtb_applicant_data').DataTable({bProcessing:true,bServerSide:true,pageLength:25,dom:"<'row'<'col-sm-12'B>>"+"<'row'<'col-sm-6'l><'col-sm-6'f>>"+"<'row'<'col-sm-12'tr>>"+"<'row'<'col-sm-5'i><'col-sm-7'p>>",buttons:[{extend:'collection',text:<?=hr_js('common_export_data', 'Export Data');?>,buttons:['copyHtml5','excelHtml5','csvHtml5','pdfHtml5']}],columnDefs:[{targets:[0,1],orderable:false,searchable:false},{targets:[6,7],className:'text-right'},{width:'42px',targets:0},{width:'150px',targets:1}],ajax:{url:'<?=base_admin();?>modul/applicant_data/applicant_data_data.php',type:'post',data:function(d){$.extend(d,apFilters());},dataSrc:function(j){var k=j.kpi||{};$('#kpi_total').text(k.total||0);$('#kpi_new').text(k.new||0);$('#kpi_process').text(k.process||0);$('#kpi_offer').text(k.offer||0);$('#kpi_hired').text(k.hired||0);$('#kpi_avg_score').text(k.avg_score||0);return j.data||[];},error:function(xhr){console.log(xhr.responseText);apError('Data Applicant gagal dimuat.');}}});
$('#btn_open_ap').click(function(){resetAp('Create Applicant');$('#modal_ap').modal({backdrop:'static',keyboard:false});});$('#btn_next_ap,#application_date').on('click change',loadNextAp);$('#btn_filter_ap').click(function(){dt.draw();});$('#filter_keyword').keyup(function(e){if(e.keyCode===13)dt.draw();});$('#btn_reset_ap').click(function(){$('#filter_tgl_awal').val('<?=$defaultFrom;?>');$('#filter_tgl_akhir').val('<?=$defaultTo;?>');$('#filter_applicant_status,#filter_vacancy_id,#filter_source_channel').val(null).trigger('change');$('#filter_keyword').val('');dt.draw();});$('#btn_export_ap').click(function(){window.location='<?=base_admin();?>modul/applicant_data/applicant_data_action.php?act=export&'+$.param(apFilters());});$('.hide_alert_notif').click(function(){$('.error_data_delete').hide();});
$('#screening_score,#interview_score').on('keyup change',function(){var s=parseFloat($('#screening_score').val())||0,i=parseFloat($('#interview_score').val())||0;if(!$('#final_score').is(':focus'))$('#final_score').val(((s+i)/((s>0&&i>0)?2:1)).toFixed(2));});
$('#form_ap').submit(function(e){e.preventDefault();var b=$(this).find('button[type=submit]');b.prop('disabled',true).html('<i class="fa fa-spinner fa-spin"></i> <?=hr_h('common_saving', 'Saving...');?>');$.post('<?=base_admin();?>modul/applicant_data/applicant_data_action.php?act=save',$(this).serialize(),function(r){b.prop('disabled',false).html('<i class="fa fa-save"></i> Save Applicant');if(r.status==='good'){$('#modal_ap').modal('hide');dt.draw(false);Swal.fire('Saved','Applicant berhasil disimpan.','success');}else apError(r.error_message);},'json').fail(function(xhr){b.prop('disabled',false).html('<i class="fa fa-save"></i> Save Applicant');apError(xhr.responseText);});});
$(document).on('click','.btn-ap-detail',function(){$.post('<?=base_admin();?>modul/applicant_data/applicant_data_action.php?act=detail',{id:$(this).data('id')},function(h){$('#ap_detail_body').html(h);$('#modal_ap_detail').modal('show');});});
$(document).on('click','.btn-ap-edit',function(){var id=$(this).data('id');$.post('<?=base_admin();?>modul/applicant_data/applicant_data_action.php?act=get',{id:id},function(r){if(r.status!=='good'){apError(r.error_message);return;}resetAp('Edit Applicant');var h=r.data||{};Object.keys(h).forEach(function(k){var el=$('#'+k);if(el.length&&!['vacancy_id','recruiter_employee_id','referred_by_employee_id','hired_employee_id'].includes(k))el.val(h[k]);});$('#ap_id').val(h.id);apSet('#vacancy_id',h.vacancy_id,h.vacancy_text);apSet('#recruiter_employee_id',h.recruiter_employee_id,h.recruiter_text);apSet('#referred_by_employee_id',h.referred_by_employee_id,h.referred_by_text);apSet('#hired_employee_id',h.hired_employee_id,h.hired_employee_text);$('#applicant_status,#gender,#identity_type,#education_level,#currency').trigger('change');$('#modal_ap').modal({backdrop:'static',keyboard:false});},'json');});
$(document).on('click','.btn-ap-status',function(){var id=$(this).data('id'),status=$(this).data('status');$.post('<?=base_admin();?>modul/applicant_data/applicant_data_action.php?act=status',{id:id,status:status},function(r){if(r.status==='good'){dt.draw(false);Swal.fire('Updated','Status berhasil diubah.','success');}else apError(r.error_message);},'json');});
$(document).on('click','.btn-ap-delete',function(){var id=$(this).data('id'),no=$(this).data('no');Swal.fire({title:erpLang('confirm_delete_title','Delete Confirmation'),text:no,icon:'warning',showCancelButton:true,confirmButtonText:erpLang('common_delete','Delete'),cancelButtonText:erpLang('common_cancel','Cancel')}).then(function(x){if(!x.isConfirmed)return;$.post('<?=base_admin();?>modul/applicant_data/applicant_data_action.php?act=delete',{id:id},function(r){if(r.status==='good'){dt.draw(false);Swal.fire(erpLang('common_deleted','Deleted'),erpLang('common_deleted_message','Data deleted successfully.'),'success');}else apError(r.error_message);},'json').fail(function(xhr){apError(xhr.responseText);});});});
});
</script>
