<?php
if (!function_exists('hr_t')) {
  function hr_t($key, $fallback = '') { return lang_text($key, $fallback); }
}
if (!function_exists('hr_h')) {
  function hr_h($key, $fallback = '') { return htmlspecialchars((string) hr_t($key, $fallback), ENT_QUOTES, 'UTF-8'); }
}
if (!function_exists('hr_js')) {
  function hr_js($key, $fallback = '') { return json_encode(hr_t($key, $fallback), JSON_HEX_TAG | JSON_HEX_APOS | JSON_HEX_AMP | JSON_HEX_QUOT); }
}
$defaultFrom=date('Y-m-01');$defaultTo=date('Y-m-t');$yearNow=(int)date('Y'); ?>
<style>
.pr-hero{background:linear-gradient(135deg,#312e81,#0f766e);color:#fff;border-radius:14px;padding:22px;margin-bottom:16px;box-shadow:0 10px 24px rgba(49,46,129,.18)}.pr-hero h1{margin:0 0 6px;font-size:27px;font-weight:700}.pr-hero p{margin:0;color:#e0f2fe}.pr-card{border-radius:12px;background:#fff;border:1px solid #e5edf5;box-shadow:0 5px 16px rgba(15,23,42,.05);margin-bottom:14px}.pr-kpi{padding:14px;border-radius:12px;background:#f8fafc;border:1px solid #dbeafe;min-height:78px}.pr-kpi span{display:block;color:#64748b;font-size:12px}.pr-kpi b{font-size:21px;color:#0f172a}.pr-kpi.good{background:#ecfdf5;border-color:#bbf7d0}.pr-kpi.warn{background:#fff7ed;border-color:#fed7aa}.pr-kpi.info{background:#eff6ff;border-color:#bfdbfe}#dtb_payroll_report th,#dtb_payroll_report td{font-size:12px;vertical-align:middle}.select2-container{width:100%!important}.pr-action{white-space:nowrap}.pr-detail{background:#fff;border:1px solid #e5e7eb;border-radius:12px;padding:18px}#modal_pr_detail .modal-body{max-height:calc(100vh - 180px);overflow-y:auto}.pr-filter .form-group{margin-bottom:12px}.pr-money{text-align:right}
</style>
<section class="content-header"><h1><?=hr_h('hr_payroll_report', 'Payroll Report');?> <small>SAP-style Payroll Analytics</small></h1><ol class="breadcrumb"><li><a href="<?=base_index();?>"><i class="fa fa-dashboard"></i> <?=hr_h('common_home', 'Home');?></a></li><li>Human Resource</li><li>HR Reports</li><li class="active"><?=hr_h('hr_payroll_report', 'Payroll Report');?></li></ol></section>
<section class="content">
<div class="pr-hero"><div class="row"><div class="col-md-8"><h1>Payroll Report Cockpit</h1><p>Ringkasan payroll per employee dan periode: gross, deduction, pajak, net pay, status payslip, posting jurnal, serta detail wage type untuk audit payroll.</p></div><div class="col-md-4 text-right"><button id="btn_export_pr" class="btn btn-success"><i class="fa fa-file-excel-o"></i> <?=hr_h('common_export_excel', 'Export Excel');?></button></div></div></div>
<div class="row"><div class="col-sm-2"><div class="pr-kpi info"><span>Payroll Rows</span><b id="kpi_pr_total">0</b></div></div><div class="col-sm-2"><div class="pr-kpi"><span>Employees</span><b id="kpi_pr_employees">0</b></div></div><div class="col-sm-2"><div class="pr-kpi"><span><?=hr_h('hr_gross_pay', 'Gross Pay');?></span><b id="kpi_pr_gross">0</b></div></div><div class="col-sm-2"><div class="pr-kpi warn"><span>Deduction + Tax</span><b id="kpi_pr_deduction">0</b></div></div><div class="col-sm-2"><div class="pr-kpi good"><span><?=hr_h('hr_net_pay', 'Net Pay');?></span><b id="kpi_pr_net">0</b></div></div><div class="col-sm-2"><div class="pr-kpi"><span>Posted / Pending</span><b id="kpi_pr_posting">0 / 0</b></div></div></div>
<div class="box pr-card pr-filter"><div class="box-header"><h3 class="box-title"><i class="fa fa-filter"></i> Filter Payroll Report</h3></div><div class="box-body"><form class="form-horizontal" onsubmit="return false;">
  <div class="form-group"><label class="control-label col-lg-2">Period Date</label><div class="col-lg-2"><div class="input-group date pr-date"><input id="filter_tgl_awal" class="form-control" value="<?=$defaultFrom;?>"><span class="input-group-addon"><span class="glyphicon glyphicon-calendar"></span></span></div></div><div class="col-lg-2"><div class="input-group date pr-date"><input id="filter_tgl_akhir" class="form-control" value="<?=$defaultTo;?>"><span class="input-group-addon"><span class="glyphicon glyphicon-calendar"></span></span></div></div><label class="control-label col-lg-1">Year</label><div class="col-lg-2"><select id="filter_period_year" class="form-control"><option value="">All</option><?php for($y=$yearNow-2;$y<=$yearNow+1;$y++){ ?><option value="<?=$y;?>" <?=$y===$yearNow?'selected':'';?>><?=$y;?></option><?php } ?></select></div><label class="control-label col-lg-1">Month</label><div class="col-lg-2"><select id="filter_period_month" class="form-control"><option value="">All</option><?php for($m=1;$m<=12;$m++){ ?><option value="<?=$m;?>" <?=$m==(int)date('n')?'selected':'';?>><?=str_pad($m,2,'0',STR_PAD_LEFT);?></option><?php } ?></select></div></div>
  <div class="form-group"><label class="control-label col-lg-2"><?=hr_h('hr_employee', 'Employee');?></label><div class="col-lg-3"><select id="filter_employee_id" class="form-control"></select></div><label class="control-label col-lg-1"><?=hr_h('hr_department', 'Department');?></label><div class="col-lg-3"><select id="filter_department_code" class="form-control"></select></div><label class="control-label col-lg-1">Area</label><div class="col-lg-2"><select id="filter_payroll_area" class="form-control"><option value="">All</option><option>MONTHLY</option><option>DAILY</option><option>WEEKLY</option><option>CONTRACT</option><option>MANAGEMENT</option><option>ALL</option></select></div></div>
  <div class="form-group"><label class="control-label col-lg-2">Process</label><div class="col-lg-2"><select id="filter_payroll_process_status" class="form-control"><option value="">All</option><option>DRAFT</option><option>CALCULATED</option><option>APPROVED</option><option>POSTED</option><option>CANCELLED</option></select></div><label class="control-label col-lg-1"><?=hr_h('hr_payslip', 'Payslip');?></label><div class="col-lg-2"><select id="filter_payslip_status" class="form-control"><option value="">All</option><option>DRAFT</option><option>GENERATED</option><option>RELEASED</option><option>VOID</option><option>NOT_GENERATED</option></select></div><label class="control-label col-lg-1">Posting</label><div class="col-lg-2"><select id="filter_posting_status" class="form-control"><option value="">All</option><option>DRAFT</option><option>READY</option><option>POSTED</option><option>REVERSED</option><option>CANCELLED</option><option>NOT_CREATED</option></select></div><div class="col-lg-2"><select id="filter_history_status" class="form-control"><option value="">History: All</option><option>ACTIVE</option><option>ARCHIVED</option><option>LOCKED</option><option>VOID</option></select></div></div>
  <div class="form-group"><label class="control-label col-lg-2">Impact</label><div class="col-lg-3"><select id="filter_impact_type" class="form-control"><option value="">All Payroll Impact</option><option value="NET_PAY">Net Pay > 0</option><option value="PAYSLIP_NOT_RELEASED">Payslip Belum Released</option><option value="POSTING_PENDING">Posting Pending</option><option value="POSTED">Sudah Posted</option><option value="EXCEPTION">Exception / Cancelled / Reversed</option></select></div><label class="control-label col-lg-1">Keyword</label><div class="col-lg-4"><input id="filter_keyword" class="form-control" placeholder="Payroll run, employee, payslip, posting, SAP ref"></div><div class="col-lg-2"><button id="btn_filter_pr" class="btn btn-primary"><i class="fa fa-filter"></i> <?=hr_h('common_filter', 'Filter');?></button> <button id="btn_reset_pr" class="btn btn-default"><i class="fa fa-refresh"></i></button></div></div>
</form></div></div>
<div class="box pr-card"><div class="box-body"><div class="alert alert-warning error_data_delete" style="display:none"><button type="button" class="close hide_alert_notif">&times;</button><span class="isi_warning_delete"></span></div><div class="table-responsive"><table id="dtb_payroll_report" class="table table-bordered table-striped" style="width:100%"><thead><tr><th><?=hr_h('common_no', 'No');?></th><th><?=hr_h('common_action', 'Action');?></th><th>Payroll Run</th><th><?=hr_h('hr_period', 'Period');?></th><th><?=hr_h('hr_employee', 'Employee');?></th><th><?=hr_h('hr_department', 'Department');?></th><th>Area</th><th><?=hr_h('hr_attendance', 'Attendance');?></th><th>Gross</th><th><?=hr_h('hr_deduction', 'Deduction');?></th><th>Tax</th><th><?=hr_h('hr_net_pay', 'Net Pay');?></th><th><?=hr_h('hr_payslip', 'Payslip');?></th><th>Posting</th><th><?=hr_h('common_status', 'Status');?></th></tr></thead><tbody></tbody></table></div></div></div>
<div id="modal_pr_detail" class="modal fade"><div class="modal-dialog modal-lg" style="width:94%"><div class="modal-content"><div class="modal-header"><button class="close" data-dismiss="modal">&times;</button><h4 class="modal-title">Payroll Report Detail</h4></div><div class="modal-body" id="pr_detail_body"></div><div class="modal-footer"><button class="btn btn-default" data-dismiss="modal"><?=hr_h('common_close', 'Close');?></button></div></div></div></div>
</section>
<script src="<?=base_admin();?>assets/plugins/select2/select2.min.js"></script>
<script>
function prError(m){$('.isi_warning_delete').text(m||'Payroll Report gagal diproses.');$('.error_data_delete').fadeIn();}
function prMoney(v){return (parseFloat(v||0)||0).toLocaleString('id-ID');}
function prFilters(){return{tgl_awal:$('#filter_tgl_awal').val(),tgl_akhir:$('#filter_tgl_akhir').val(),period_year:$('#filter_period_year').val(),period_month:$('#filter_period_month').val(),employee_id:$('#filter_employee_id').val(),department_code:$('#filter_department_code').val(),payroll_area:$('#filter_payroll_area').val(),payroll_process_status:$('#filter_payroll_process_status').val(),payslip_status:$('#filter_payslip_status').val(),posting_status:$('#filter_posting_status').val(),history_status:$('#filter_history_status').val(),impact_type:$('#filter_impact_type').val(),keyword:$('#filter_keyword').val()};}
function prAjax(s,act,p){$(s).select2({width:'100%',allowClear:true,placeholder:p,ajax:{url:'<?=base_admin();?>modul/payroll_report/payroll_report_action.php?act='+act,type:'POST',dataType:'json',delay:250,data:function(q){return{term:q.term||''};},processResults:function(d){return{results:d.results||[]};}}});}
$(function(){if($.fn.datepicker){$('.pr-date').datepicker({format:'yyyy-mm-dd',autoclose:true,todayHighlight:true});}if($.fn.select2){$('#filter_period_year,#filter_period_month,#filter_payroll_area,#filter_payroll_process_status,#filter_payslip_status,#filter_posting_status,#filter_history_status,#filter_impact_type').select2({width:'100%',allowClear:true});prAjax('#filter_employee_id','employee_search','Semua Employee');prAjax('#filter_department_code','department_search','Semua Department');}
var dt=$('#dtb_payroll_report').DataTable({bProcessing:true,bServerSide:true,pageLength:25,dom:"<'row'<'col-sm-12'B>>"+"<'row'<'col-sm-6'l><'col-sm-6'f>>"+"<'row'<'col-sm-12'tr>>"+"<'row'<'col-sm-5'i><'col-sm-7'p>>",buttons:[{extend:'collection',text:<?=hr_js('common_export_data', 'Export Data');?>,buttons:['copyHtml5','excelHtml5','csvHtml5','pdfHtml5']}],columnDefs:[{targets:[0,1],orderable:false,searchable:false},{width:'42px',targets:0},{width:'70px',targets:1},{className:'pr-money',targets:[8,9,10,11]}],ajax:{url:'<?=base_admin();?>modul/payroll_report/payroll_report_data.php',type:'post',data:function(d){$.extend(d,prFilters());},dataSrc:function(j){var k=j.kpi||{};$('#kpi_pr_total').text(k.total||0);$('#kpi_pr_employees').text(k.employees||0);$('#kpi_pr_gross').text(prMoney(k.gross));$('#kpi_pr_deduction').text(prMoney((parseFloat(k.deduction||0)+parseFloat(k.tax||0))));$('#kpi_pr_net').text(prMoney(k.net));$('#kpi_pr_posting').text((k.posted||0)+' / '+(k.posting_pending||0));return j.data||[];},error:function(x){console.log(x.responseText);prError('Data Payroll Report gagal dimuat.');}}});
$('#btn_filter_pr').click(function(){dt.draw();});$('#filter_keyword').keyup(function(e){if(e.keyCode===13)dt.draw();});$('#btn_reset_pr').click(function(){$('#filter_tgl_awal').val('<?=$defaultFrom;?>');$('#filter_tgl_akhir').val('<?=$defaultTo;?>');$('#filter_period_year').val('<?=$yearNow;?>').trigger('change');$('#filter_period_month').val('<?=date('n');?>').trigger('change');$('#filter_employee_id,#filter_department_code,#filter_payroll_area,#filter_payroll_process_status,#filter_payslip_status,#filter_posting_status,#filter_history_status,#filter_impact_type').val(null).trigger('change');$('#filter_keyword').val('');dt.draw();});$('#btn_export_pr').click(function(){window.location='<?=base_admin();?>modul/payroll_report/payroll_report_action.php?act=export&'+$.param(prFilters());});$('.hide_alert_notif').click(function(){$('.error_data_delete').hide();});
$(document).on('click','.btn-pr-detail',function(){$.post('<?=base_admin();?>modul/payroll_report/payroll_report_action.php?act=detail',{id:$(this).data('id')},function(h){$('#pr_detail_body').html(h);$('#modal_pr_detail').modal('show');});});
});
</script>
