<?php
if (!function_exists('prod_t')) {
  function prod_t($key, $fallback = '') { return lang_text($key, $fallback); }
}
if (!function_exists('prod_h')) {
  function prod_h($key, $fallback = '') { return htmlspecialchars((string) prod_t($key, $fallback), ENT_QUOTES, 'UTF-8'); }
}
if (!function_exists('prod_js')) {
  function prod_js($key, $fallback = '') { return json_encode(prod_t($key, $fallback), JSON_HEX_TAG | JSON_HEX_APOS | JSON_HEX_AMP | JSON_HEX_QUOT); }
}
$defaultFrom=date('Y-m-d',strtotime('-7 days'));$defaultTo=date('Y-m-d',strtotime('+14 days'));
$plants=$db->query("SELECT DISTINCT plant FROM production_order WHERE plant IS NOT NULL AND plant<>'' ORDER BY plant");
$workCenters=$db->query("SELECT DISTINCT work_center FROM production_order_operation WHERE work_center IS NOT NULL AND work_center<>'' ORDER BY work_center");
$kpi=$db->fetch("SELECT COUNT(*) total_doc,SUM(status='RELEASED') released_doc,SUM(status='IN_PROCESS') inprocess_doc,SUM(status='CONFIRMED') confirmed_doc FROM production_order WHERE status IN ('RELEASED','IN_PROCESS','CONFIRMED') AND start_date BETWEEN ? AND ?",array($defaultFrom,$defaultTo));
?>
<style>
.mpo-hero{background:linear-gradient(135deg,#581c87,#0369a1);color:#fff;border-radius:14px;padding:20px 22px;margin-bottom:18px;box-shadow:0 10px 24px rgba(15,23,42,.18)}.mpo-hero h1{margin:0 0 6px;font-size:26px;font-weight:700}.mpo-card{border-radius:12px;background:#fff;border:1px solid #e5edf5;box-shadow:0 5px 16px rgba(15,23,42,.05);margin-bottom:14px}.mpo-kpi{border-radius:12px;background:#fff;border:1px solid #edf2f7;padding:15px;margin-bottom:14px}.mpo-kpi span{display:block;color:#64748b;font-size:12px;text-transform:uppercase}.mpo-kpi strong{display:block;font-size:24px;margin-top:6px}.mpo-kpi i{float:right;font-size:26px;color:#581c87;opacity:.55}#dtb_my_production_orders th,#dtb_my_production_orders td{font-size:12px;vertical-align:middle}.select2-container{width:100%!important}.progress-xs{height:7px}.mpo-progress{min-width:150px}.mpo-help{background:#f8fafc;border:1px dashed #cbd5e1;border-radius:10px;padding:12px;margin-bottom:14px;color:#475569}.mpo-actions{white-space:nowrap}
</style>
<section class="content-header"><h1><?=prod_h('production_my_orders', 'My Production Orders');?> <small>SAP PP Operator Order List</small></h1><ol class="breadcrumb"><li><a href="<?=base_index();?>"><i class="fa fa-dashboard"></i> <?=prod_h('common_home', 'Home');?></a></li><li class="active"><?=prod_h('production_my_orders', 'My Production Orders');?></li></ol></section>
<section class="content">
  <div class="mpo-hero"><div class="row"><div class="col-md-8"><h1>Operator Production Order Cockpit</h1><p>Daftar order produksi aktif untuk eksekusi shop floor: cek material readiness, operasi, progress confirmation, GR, dan downtime dari satu layar.</p></div><div class="col-md-4 text-right"><a class="btn btn-success btn-lg" href="<?=base_index();?>production-confirmation"><i class="fa fa-check-square-o"></i> <?=prod_h('production_confirmation', 'Production Confirmation');?></a></div></div></div>
  <div class="row"><div class="col-sm-3"><div class="mpo-kpi"><i class="fa fa-tasks"></i><span>Total Active Orders</span><strong><?=number_format((float)$kpi->total_doc,0,',','.');?></strong></div></div><div class="col-sm-3"><div class="mpo-kpi"><i class="fa fa-play"></i><span><?=prod_h('production_released', 'Released');?></span><strong><?=number_format((float)$kpi->released_doc,0,',','.');?></strong></div></div><div class="col-sm-3"><div class="mpo-kpi"><i class="fa fa-cogs"></i><span><?=prod_h('production_in_process', 'In Process');?></span><strong><?=number_format((float)$kpi->inprocess_doc,0,',','.');?></strong></div></div><div class="col-sm-3"><div class="mpo-kpi"><i class="fa fa-check"></i><span>Confirmed</span><strong><?=number_format((float)$kpi->confirmed_doc,0,',','.');?></strong></div></div></div>
  <div class="mpo-help"><strong>Standar pemakaian:</strong> operator memilih order yang statusnya `RELEASED` atau `IN_PROCESS`, pastikan material `READY`, jalankan operasi sesuai work center, lalu catat confirmation/downtime dari tombol cepat.</div>
  <div class="box mpo-card"><div class="box-header"><h3 class="box-title"><i class="fa fa-filter"></i> Filter My Orders</h3></div><div class="box-body"><form class="form-horizontal" onsubmit="return false;"><div class="form-group"><label class="control-label col-lg-2"><?=prod_h('production_start_date', 'Start Date');?></label><div class="col-lg-2"><div class="input-group date mpo-date"><input id="filter_tgl_awal" class="form-control" value="<?=$defaultFrom;?>"><span class="input-group-addon"><span class="glyphicon glyphicon-calendar"></span></span></div></div><div class="col-lg-2"><div class="input-group date mpo-date"><input id="filter_tgl_akhir" class="form-control" value="<?=$defaultTo;?>"><span class="input-group-addon"><span class="glyphicon glyphicon-calendar"></span></span></div></div><label class="control-label col-lg-1"><?=prod_h('production_plant', 'Plant');?></label><div class="col-lg-2"><select id="filter_plant" class="form-control"><option value=""><?=prod_h('common_all', 'All');?></option><?php foreach($plants as $p){ ?><option value="<?=htmlspecialchars($p->plant,ENT_QUOTES,'UTF-8');?>"><?=htmlspecialchars($p->plant,ENT_QUOTES,'UTF-8');?></option><?php } ?></select></div><label class="control-label col-lg-1"><?=prod_h('common_status', 'Status');?></label><div class="col-lg-2"><select id="filter_status" class="form-control"><option value=""><?=prod_h('common_all', 'All');?></option><option>RELEASED</option><option>IN_PROCESS</option><option>CONFIRMED</option></select></div></div><div class="form-group"><label class="control-label col-lg-2"><?=prod_h('production_work_center', 'Work Center');?></label><div class="col-lg-2"><select id="filter_work_center" class="form-control"><option value=""><?=prod_h('common_all', 'All');?></option><?php foreach($workCenters as $w){ ?><option value="<?=htmlspecialchars($w->work_center,ENT_QUOTES,'UTF-8');?>"><?=htmlspecialchars($w->work_center,ENT_QUOTES,'UTF-8');?></option><?php } ?></select></div><label class="control-label col-lg-1">Readiness</label><div class="col-lg-2"><select id="filter_readiness" class="form-control"><option value=""><?=prod_h('common_all', 'All');?></option><option value="READY">Material Ready</option><option value="SHORTAGE">Material Shortage</option><option value="TO_CONFIRM">Need Confirmation</option><option value="TO_GR">Need GR</option></select></div><label class="control-label col-lg-1"><?=prod_h('common_search', 'Search');?></label><div class="col-lg-2"><input id="filter_keyword" class="form-control" placeholder="PO, material, SO"></div><div class="col-lg-2"><button id="btn_filter_mpo" class="btn btn-primary"><i class="fa fa-filter"></i></button> <button id="btn_reset_mpo" class="btn btn-default"><i class="fa fa-refresh"></i></button> <button id="btn_excel_mpo" class="btn btn-success"><i class="fa fa-file-excel-o"></i></button></div></div></form></div></div>
  <div class="box mpo-card"><div class="box-body"><div class="alert alert-warning error_data_delete" style="display:none"><button type="button" class="close hide_alert_notif">&times;</button><span class="isi_warning_delete"></span></div><div class="table-responsive"><table id="dtb_my_production_orders" class="table table-bordered table-striped table-condensed" style="width:100%"><thead><tr><th><?=prod_h('common_no', 'No');?></th><th><?=prod_h('common_action', 'Action');?></th><th><?=prod_h('production_order', 'Production Order');?></th><th><?=prod_h('production_material', 'Material');?></th><th><?=prod_h('production_qty', 'Qty');?></th><th>Plant/SLoc</th><th>Operations</th><th>Readiness</th><th>Schedule</th><th>Progress</th><th>Downtime</th><th><?=prod_h('common_status', 'Status');?></th></tr></thead><tbody></tbody></table></div></div></div>
  <div id="modal_detail_mpo" class="modal fade"><div class="modal-dialog modal-lg" style="width:94%"><div class="modal-content"><div class="modal-header"><button class="close" data-dismiss="modal">&times;</button><h4 class="modal-title">My Production Order Detail</h4></div><div class="modal-body" id="mpo_detail_body"></div><div class="modal-footer"><a class="btn btn-success" href="<?=base_index();?>production-confirmation"><i class="fa fa-check-square-o"></i> <?=prod_h('production_confirmation_short', 'Confirmation');?></a><a class="btn btn-warning" href="<?=base_index();?>input-downtime"><i class="fa fa-clock-o"></i> Downtime</a><button class="btn btn-default" data-dismiss="modal"><?=prod_h('common_close', 'Close');?></button></div></div></div></div>
</section>
<script src="<?=base_admin();?>assets/plugins/select2/select2.min.js"></script>
<script>
function mpoError(m){$('.isi_warning_delete').text(m||<?=prod_js('production_my_orders_process_failed', 'My Production Orders failed to process.');?>);$('.error_data_delete').fadeIn();}
function mpoFilters(){return{tgl_awal:$('#filter_tgl_awal').val(),tgl_akhir:$('#filter_tgl_akhir').val(),plant:$('#filter_plant').val(),status:$('#filter_status').val(),work_center:$('#filter_work_center').val(),readiness:$('#filter_readiness').val(),keyword:$('#filter_keyword').val()};}
function mpoQuery(){return $.param(mpoFilters());}
$(function(){if($.fn.datepicker){$('.mpo-date').datepicker({format:'yyyy-mm-dd',autoclose:true,todayHighlight:true});}if($.fn.select2){$('#filter_plant,#filter_status,#filter_work_center,#filter_readiness').select2({width:'100%',allowClear:true});}
var dt=$('#dtb_my_production_orders').DataTable({bProcessing:true,bServerSide:true,pageLength:25,ordering:false,dom:"<'row'<'col-sm-12'B>>"+"<'row'<'col-sm-6'l><'col-sm-6'f>>"+"<'row'<'col-sm-12'tr>>"+"<'row'<'col-sm-5'i><'col-sm-7'p>>",buttons:[{extend:'collection',text:<?=prod_js('common_export_data', 'Export Data');?>,buttons:['copyHtml5','excelHtml5','csvHtml5','pdfHtml5']}],columnDefs:[{targets:[0,1],orderable:false,searchable:false},{width:'38px',targets:0},{width:'100px',targets:1},{className:'mpo-progress',targets:9}],ajax:{url:'<?=base_admin();?>modul/my_production_orders/my_production_orders_data.php',type:'post',data:function(d){$.extend(d,mpoFilters());},error:function(xhr){console.log(xhr.responseText);mpoError(<?=prod_js('production_my_orders_load_failed', 'My Production Orders data failed to load.');?>);}}});
$('#btn_filter_mpo').click(function(){dt.draw();});$('#filter_keyword').keyup(function(e){if(e.keyCode===13)dt.draw();});$('#btn_reset_mpo').click(function(){$('#filter_tgl_awal').val('<?=$defaultFrom;?>');$('#filter_tgl_akhir').val('<?=$defaultTo;?>');$('#filter_plant,#filter_status,#filter_work_center,#filter_readiness').val('').trigger('change');$('#filter_keyword').val('');dt.draw();});$('#btn_excel_mpo').click(function(){window.location='<?=base_admin();?>modul/my_production_orders/my_production_orders_action.php?act=excel&'+mpoQuery();});
$(document).on('click','.btn-mpo-detail',function(){$.post('<?=base_admin();?>modul/my_production_orders/my_production_orders_action.php?act=detail',{id:$(this).data('id')},function(html){$('#mpo_detail_body').html(html);$('#modal_detail_mpo').modal('show');}).fail(function(){mpoError('Detail gagal dibuka.');});});$('.hide_alert_notif').click(function(){$('.error_data_delete').hide();});
});
</script>
