<?php
if (!function_exists('sd_t')) {
  function sd_t($key, $fallback = '') { return lang_text($key, $fallback); }
}
if (!function_exists('sd_h')) {
  function sd_h($key, $fallback = '') { return htmlspecialchars((string) sd_t($key, $fallback), ENT_QUOTES, 'UTF-8'); }
}
if (!function_exists('sd_js')) {
  function sd_js($key, $fallback = '') { return json_encode(sd_t($key, $fallback), JSON_HEX_TAG | JSON_HEX_APOS | JSON_HEX_AMP | JSON_HEX_QUOT); }
}
if(session_status()===PHP_SESSION_NONE)session_start();
include "../../inc/config.php";
session_check_json();
error_reporting(E_ALL & ~E_NOTICE & ~E_WARNING & ~E_DEPRECATED & ~E_USER_DEPRECATED);
function sqra_h($v){return htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');}
function sqra_num($v,$d=2){return number_format((float)$v,$d,',','.');}
$act=isset($_GET['act'])?$_GET['act']:'';
switch($act){
  case 'detail':
    $id=isset($_POST['id'])?(int)$_POST['id']:0;
    $h=$db->fetch("SELECT sq.*,COALESCE(NULLIF(sq.customer_name,''),c.nama) customer_display,c.alamat customer_address FROM sales_quotation sq LEFT JOIN customer c ON c.id_customer=sq.customer_id OR c.kode_pemasok=sq.kode_penerima WHERE sq.id_quotation=? LIMIT 1",array($id));
    if(!$h){echo '<div class="alert alert-warning">Quotation tidak ditemukan.</div>';break;}
    $items=$db->query("SELECT d.*,b.nm_barang,b.satuan FROM sales_quotation_detail d LEFT JOIN barang b ON b.kd_barang=d.kd_barang WHERE d.id_quotation=? ORDER BY d.line_no,d.id_detail",array($id));
    $orders=$db->query("SELECT no_sales_order,so_date,status,approval_status,currency,no_po FROM sales_order WHERE id_quotation=? ORDER BY so_date,id_sales_order",array($id));
    $followups=$db->query("SELECT * FROM sales_quotation_followup WHERE quotation_id=? ORDER BY followup_date DESC,id DESC",array($id));
    $subtotal=0;$qty=0;foreach($items as $it){$subtotal+=(float)$it->nilai;$qty+=(float)$it->qty;}$tax=0;
    echo '<h3 style="margin-top:0">'.sqra_h($h->no_sales_quotation).' <small>'.sqra_h($h->status.' / '.$h->currency).'</small></h3><div class="row"><div class="col-sm-3"><strong>'.sd_h('sales_customer', 'Customer').'</strong><br>'.sqra_h($h->customer_display?:$h->kode_penerima).'<br><small>'.sqra_h($h->customer_address).'</small></div><div class="col-sm-3"><strong>Subject</strong><br>'.sqra_h($h->subject?:'-').'<br><small>'.sqra_h($h->contact_person?:'-').'</small></div><div class="col-sm-3"><strong>Validity</strong><br>'.sqra_h($h->tgl).' s/d '.sqra_h($h->valid_date).'<br><small>Req Deliv '.sqra_h($h->requested_delivery_date?:'-').'</small></div><div class="col-sm-3"><strong>Sales</strong><br>'.sqra_h($h->sales_id?:'-').'<br><small>'.sqra_h($h->payment_term?:$h->term).'</small></div></div><hr>';
    echo '<div class="row"><div class="col-sm-3"><div class="well well-sm"><strong>Total Qty</strong><br>'.sqra_num($qty,4).'</div></div><div class="col-sm-3"><div class="well well-sm"><strong>Quotation Amount</strong><br>'.sqra_num($subtotal).'</div></div><div class="col-sm-3"><div class="well well-sm"><strong>Tax Flag</strong><br>'.sqra_h($h->tax?:'-').'</div></div><div class="col-sm-3"><div class="well well-sm"><strong>Incoterm</strong><br>'.sqra_h($h->incoterm?:'-').'</div></div></div>';
    echo '<h4>Quotation Items</h4><table class="table table-bordered table-condensed"><thead><tr class="bg-gray"><th>Line</th><th>'.sd_h('sales_material', 'Material').'</th><th class="text-right">'.sd_h('sales_qty', 'Qty').'</th><th>'.sd_h('sales_uom', 'UOM').'</th><th class="text-right">'.sd_h('sales_price', 'Price').'</th><th class="text-right">Disc %</th><th class="text-right">Tax %</th><th class="text-right">'.sd_h('sales_amount', 'Amount').'</th><th>Req Deliv</th></tr></thead><tbody>';
    foreach($items as $it)echo '<tr><td>'.(int)$it->line_no.'</td><td><strong>'.sqra_h($it->kd_barang).'</strong><br><small>'.sqra_h($it->nm_barang?:$it->ket).'</small></td><td class="text-right">'.sqra_num($it->qty,4).'</td><td>'.sqra_h($it->uom?:$it->satuan).'</td><td class="text-right">'.sqra_num($it->price).'</td><td class="text-right">'.sqra_num($it->discount_percent).'</td><td class="text-right">'.sqra_num($it->tax_percent).'</td><td class="text-right">'.sqra_num($it->nilai).'</td><td>'.sqra_h($it->requested_delivery_date?:'-').'</td></tr>';
    echo '</tbody></table><div class="row"><div class="col-md-6"><h4>Converted Sales Orders</h4><table class="table table-bordered table-condensed"><thead><tr class="bg-gray"><th>'.sd_h('sales_order', 'Sales Order').'</th><th>'.sd_h('sales_date', 'Date').'</th><th>'.sd_h('sales_customer_po', 'Customer PO').'</th><th>'.sd_h('common_status', 'Status').'</th></tr></thead><tbody>';
    foreach($orders as $o)echo '<tr><td>'.sqra_h($o->no_sales_order).'</td><td>'.sqra_h($o->so_date).'</td><td>'.sqra_h($o->no_po).'</td><td>'.sqra_h($o->status.' / '.$o->approval_status).'</td></tr>';
    echo '</tbody></table></div><div class="col-md-6"><h4>Follow Up History</h4><table class="table table-bordered table-condensed"><thead><tr class="bg-gray"><th>'.sd_h('sales_date', 'Date').'</th><th>Method</th><th>Result</th><th>Next Action</th></tr></thead><tbody>';
    foreach($followups as $f)echo '<tr><td>'.sqra_h($f->followup_date).'</td><td>'.sqra_h($f->contact_method.' / '.$f->activity_type).'</td><td>'.sqra_h($f->result_status.' '.$f->probability_percent.'%').'</td><td>'.sqra_h($f->next_action).'<br><small>'.sqra_h($f->next_followup_date).'</small></td></tr>';
    echo '</tbody></table></div></div>';break;
  case 'excel':
    $initial=ob_get_level();ob_start();require_once "../../inc/lib/PHPExcel.php";require_once "../../inc/excel_style_helper.php";PHPExcel_Shared_File::setUseUploadTempDirectory(true);
    $from=isset($_GET['tgl_awal'])?$_GET['tgl_awal']:date('Y-m-01');$to=isset($_GET['tgl_akhir'])?$_GET['tgl_akhir']:date('Y-m-d');$p=array($from,$to);$w=" WHERE sq.tgl BETWEEN ? AND ? ";
    if(!empty($_GET['status'])){$w.=" AND sq.status=? ";$p[]=$_GET['status'];}if(!empty($_GET['sales_person'])){$w.=" AND sq.sales_id=? ";$p[]=$_GET['sales_person'];}if(!empty($_GET['currency'])){$w.=" AND sq.currency=? ";$p[]=$_GET['currency'];}
    $rows=$db->query("SELECT sq.no_sales_quotation,sq.tgl,sq.valid_date,sq.requested_delivery_date,sq.status,sq.currency,sq.sales_id,COALESCE(NULLIF(sq.customer_name,''),c.nama) customer_display,sq.subject,d.line_no,d.kd_barang,b.nm_barang,d.qty,d.uom,d.price,d.discount_percent,d.tax_percent,d.nilai,COALESCE(so.so_count,0) so_count,so.so_numbers FROM sales_quotation sq LEFT JOIN customer c ON c.id_customer=sq.customer_id OR c.kode_pemasok=sq.kode_penerima LEFT JOIN sales_quotation_detail d ON d.id_quotation=sq.id_quotation LEFT JOIN barang b ON b.kd_barang=d.kd_barang LEFT JOIN(SELECT id_quotation,COUNT(*) so_count,GROUP_CONCAT(no_sales_order ORDER BY so_date SEPARATOR ', ') so_numbers FROM sales_order WHERE COALESCE(id_quotation,0)>0 GROUP BY id_quotation) so ON so.id_quotation=sq.id_quotation $w ORDER BY sq.tgl DESC,sq.id_quotation DESC,d.line_no",$p);
    $excel=new PHPExcel();$sh=$excel->setActiveSheetIndex(0);$sh->setTitle(erp_export_sheet_title('Quotation Report'));$heads=array(erp_export_label("No"),erp_export_label("Quotation No"),erp_export_label("Date"),erp_export_label("Valid Until"),erp_export_label("Req Delivery"),erp_export_label("Status"),erp_export_label("Customer"),erp_export_label("Subject"),erp_export_label("Currency"),erp_export_label("Sales"),erp_export_label("Line"),erp_export_label("Material"),erp_export_label("Material Name"),erp_export_label("Qty"),erp_export_label("UOM"),erp_export_label("Price"),erp_export_label("Disc %"),erp_export_label("Tax %"),erp_export_label("Amount"),erp_export_label("SO Count"),erp_export_label("Sales Orders"));foreach($heads as $i=>$v)$sh->setCellValue(PHPExcel_Cell::stringFromColumnIndex($i).'4',$v);$r=5;$n=1;foreach($rows as $row){$vals=array($n++,$row->no_sales_quotation,$row->tgl,$row->valid_date,$row->requested_delivery_date,$row->status,$row->customer_display,$row->subject,$row->currency,$row->sales_id,(int)$row->line_no,$row->kd_barang,$row->nm_barang,(float)$row->qty,$row->uom,(float)$row->price,(float)$row->discount_percent,(float)$row->tax_percent,(float)$row->nilai,(int)$row->so_count,$row->so_numbers);foreach($vals as $i=>$v)$sh->setCellValue(PHPExcel_Cell::stringFromColumnIndex($i).$r,$v);$r++;}
    erpkb_excel_apply_standard_style($excel,array('sheet'=>$sh,'title'=>erp_export_title('SALES QUOTATION REPORT'),'header_row'=>4,'first_data_row'=>5,'last_data_row'=>max(5,$r-1),'column_count'=>21,'numeric_columns'=>array('K','N','P','Q','R','S','T'),'filters'=>array('Quotation Date'=>$from.' s/d '.$to,'Status'=>isset($_GET['status'])?$_GET['status']:erp_export_all_text(),'Sales'=>isset($_GET['sales_person'])?$_GET['sales_person']:erp_export_all_text())));$tmp=erpkb_excel_temp_file('sales_quotation_report_');PHPExcel_IOFactory::createWriter($excel,'Excel2007')->save($tmp);$size=@filesize($tmp);$sig=@file_get_contents($tmp,false,null,0,2);if(!$size||$sig!=='PK'){@unlink($tmp);while(ob_get_level()>$initial)ob_end_clean();header('Content-Type:text/plain; charset=utf-8');echo erp_t('export_excel_invalid_file','File Excel gagal dibuat dengan benar.');exit;}while(ob_get_level()>$initial)ob_end_clean();header('Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');header('Content-Disposition: attachment; filename="sales_quotation_report_'.date('Ymd_His').'.xlsx"');header('Content-Length: '.$size);header('Cache-Control: max-age=0');header('Pragma: public');readfile($tmp);@unlink($tmp);exit;
  default:header('Content-Type: application/json');echo json_encode(array('status'=>'error','error_message'=>'Action tidak dikenal.'));
}
?>
