<?php
if (!function_exists('hr_t')) {
  function hr_t($key, $fallback = '') { return lang_text($key, $fallback); }
}
if (!function_exists('hr_h')) {
  function hr_h($key, $fallback = '') { return htmlspecialchars((string) hr_t($key, $fallback), ENT_QUOTES, 'UTF-8'); }
}
if (!function_exists('hr_js')) {
  function hr_js($key, $fallback = '') { return json_encode(hr_t($key, $fallback), JSON_HEX_TAG | JSON_HEX_APOS | JSON_HEX_AMP | JSON_HEX_QUOT); }
}
if (session_status() === PHP_SESSION_NONE) session_start();
include "../../inc/config.php";
session_check_json();
function ssd_h($v){return htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');}
function ssd_label($s){$map=array('DRAFT'=>'warning','PLANNED'=>'info','RELEASED'=>'success','CANCELLED'=>'danger');$c=isset($map[$s])?$map[$s]:'default';return '<span class="label label-'.$c.'">'.ssd_h($s).'</span>';}
$draw=isset($_POST['draw'])?(int)$_POST['draw']:1;$start=isset($_POST['start'])?max(0,(int)$_POST['start']):0;$length=isset($_POST['length'])?(int)$_POST['length']:25;if($length<=0||$length>500)$length=25;
$from=isset($_POST['tgl_awal'])&&$_POST['tgl_awal']!==''?$_POST['tgl_awal']:date('Y-m-01');$to=isset($_POST['tgl_akhir'])&&$_POST['tgl_akhir']!==''?$_POST['tgl_akhir']:date('Y-m-t');$emp=isset($_POST['employee_id'])?trim($_POST['employee_id']):'';$dept=isset($_POST['department_code'])?trim($_POST['department_code']):'';$shift=isset($_POST['shift_id'])?trim($_POST['shift_id']):'';$status=isset($_POST['assignment_status'])?trim($_POST['assignment_status']):'';$roster=isset($_POST['roster_type'])?trim($_POST['roster_type']):'';$kw=isset($_POST['keyword'])?trim($_POST['keyword']):'';
$w=" WHERE ss.schedule_from<=? AND ss.schedule_to>=? ";$p=array($to,$from);if($emp!==''){$w.=" AND ss.employee_id=? ";$p[]=(int)$emp;}if($dept!==''){$w.=" AND ss.department_code=? ";$p[]=$dept;}if($shift!==''){$w.=" AND ss.shift_id=? ";$p[]=(int)$shift;}if($status!==''){$w.=" AND ss.assignment_status=? ";$p[]=$status;}if($roster!==''){$w.=" AND ss.roster_type=? ";$p[]=$roster;}if($kw!==''){$like='%'.$kw.'%';$w.=" AND (ss.assignment_no LIKE ? OR ss.employee_no LIKE ? OR e.full_name LIKE ? OR ss.rotation_group LIKE ? OR ss.sap_reference LIKE ? OR ss.remarks LIKE ?) ";array_push($p,$like,$like,$like,$like,$like,$like);}
$kpi=$db->fetch("SELECT COUNT(*) total,SUM(assignment_status='RELEASED') released,SUM(assignment_status='PLANNED') planned,SUM(roster_type='ROTATION') rotation,SUM(roster_type='OVERTIME') overtime FROM erp_shift_schedule");
$cnt=$db->fetch("SELECT COUNT(*) jml FROM erp_shift_schedule ss JOIN erp_employee_master e ON e.id=ss.employee_id $w",$p);$total=$cnt?(int)$cnt->jml:0;
$orderMap=array(2=>'ss.assignment_no',3=>'e.employee_no',4=>'ss.department_code',5=>'ss.shift_code',6=>'ss.schedule_from',7=>'ss.roster_type',8=>'ss.assignment_status',9=>'ss.updated_at');$orderBy='ss.schedule_from DESC,ss.assignment_no';if(isset($_POST['order'][0]['column'])){$col=(int)$_POST['order'][0]['column'];$dir=(isset($_POST['order'][0]['dir'])&&strtolower($_POST['order'][0]['dir'])==='desc')?'DESC':'ASC';if(isset($orderMap[$col]))$orderBy=$orderMap[$col].' '.$dir;}
$rows=$db->query("SELECT ss.*,e.full_name,e.employee_group,e.employment_status,d.nm_dept,ws.schedule_name,wl.location_code,wl.location_name,s.nama_shift,s.jam_mulai,s.jam_selesai FROM erp_shift_schedule ss JOIN erp_employee_master e ON e.id=ss.employee_id LEFT JOIN dept d ON d.kd_dept=ss.department_code LEFT JOIN erp_work_schedule ws ON ws.id=ss.work_schedule_id LEFT JOIN erp_work_location wl ON wl.id=ss.work_location_id LEFT JOIN erp_shift s ON s.id=ss.shift_id $w ORDER BY $orderBy LIMIT $start,$length",$p);
$data=array();$no=$start+1;foreach($rows as $r){$canDel=$r->assignment_status==='RELEASED'?' disabled':'';$act='<div class="ss-action"><button class="btn btn-info btn-xs btn-ss-detail" data-id="'.(int)$r->id.'" title="'.hr_h('common_detail', 'Detail').'"><i class="fa fa-eye"></i></button> <button class="btn btn-primary btn-xs btn-ss-edit" data-id="'.(int)$r->id.'" title="'.hr_h('common_edit', 'Edit').'"><i class="fa fa-pencil"></i></button> <button class="btn btn-success btn-xs btn-ss-status" data-id="'.(int)$r->id.'" data-status="RELEASED" title="Release"><i class="fa fa-check"></i></button> <button class="btn btn-warning btn-xs btn-ss-status" data-id="'.(int)$r->id.'" data-status="CANCELLED" title="'.hr_h('common_cancel', 'Cancel').'"><i class="fa fa-ban"></i></button> <button class="btn btn-danger btn-xs btn-ss-delete" data-id="'.(int)$r->id.'" data-no="'.ssd_h($r->assignment_no).'" title="'.hr_h('common_delete', 'Delete').'"'.$canDel.'><i class="fa fa-trash"></i></button></div>';$days='<span class="label label-'.($r->monday==='Y'?'success':'default').'">M</span> <span class="label label-'.($r->tuesday==='Y'?'success':'default').'">T</span> <span class="label label-'.($r->wednesday==='Y'?'success':'default').'">W</span> <span class="label label-'.($r->thursday==='Y'?'success':'default').'">T</span> <span class="label label-'.($r->friday==='Y'?'success':'default').'">F</span> <span class="label label-'.($r->saturday==='Y'?'success':'default').'">S</span> <span class="label label-'.($r->sunday==='Y'?'success':'default').'">S</span>';
  $data[]=array($no++,$act,'<strong>'.ssd_h($r->assignment_no).'</strong><br><small>'.ssd_h($r->schedule_from.' s/d '.$r->schedule_to).'</small>','<strong>'.ssd_h($r->employee_no).'</strong><br><small>'.ssd_h($r->full_name).'</small><br><small>'.ssd_h($r->employee_group.' / '.$r->employment_status).'</small>','<strong>'.ssd_h($r->department_code?:'-').'</strong><br><small>'.ssd_h($r->nm_dept?:'-').'</small>','<strong>'.ssd_h(($r->shift_code?:'-').' '.$r->nama_shift).'</strong><br><small>'.ssd_h(($r->planned_start?substr($r->planned_start,0,5):'-').' - '.($r->planned_end?substr($r->planned_end,0,5):'-')).'</small><br><small>'.ssd_h($r->planned_hours_per_day).' h/day</small>',$days,'<strong>'.ssd_h($r->roster_type).'</strong><br><small>'.ssd_h($r->source_type.' / '.$r->rotation_group).'</small>',ssd_label($r->assignment_status).'<br><small>OT '.ssd_h($r->overtime_eligible).' | Att '.ssd_h($r->attendance_required).'</small>',ssd_h($r->updated_by?:$r->created_by?:'-').'<br><small>'.ssd_h($r->updated_at?:$r->created_at).'</small>');}
header('Content-Type: application/json; charset=utf-8');echo json_encode(array('draw'=>$draw,'recordsTotal'=>$total,'recordsFiltered'=>$total,'data'=>$data,'kpi'=>array('total'=>$kpi?(int)$kpi->total:0,'released'=>$kpi?(int)$kpi->released:0,'planned'=>$kpi?(int)$kpi->planned:0,'rotation'=>$kpi?(int)$kpi->rotation:0,'overtime'=>$kpi?(int)$kpi->overtime:0)));
?>
