<?php
if (!function_exists('hr_t')) {
  function hr_t($key, $fallback = '') { return lang_text($key, $fallback); }
}
if (!function_exists('hr_h')) {
  function hr_h($key, $fallback = '') { return htmlspecialchars((string) hr_t($key, $fallback), ENT_QUOTES, 'UTF-8'); }
}
if (!function_exists('hr_js')) {
  function hr_js($key, $fallback = '') { return json_encode(hr_t($key, $fallback), JSON_HEX_TAG | JSON_HEX_APOS | JSON_HEX_AMP | JSON_HEX_QUOT); }
}
$defaultFrom=date('Y-m-01');$defaultTo=date('Y-m-t');$canInsert=isset($role_act['insert_act'])&&$role_act['insert_act']==='Y'; ?>
<style>
.ss-hero{background:linear-gradient(135deg,#1e3a8a,#0f766e);color:#fff;border-radius:14px;padding:20px;margin-bottom:18px;box-shadow:0 10px 24px rgba(15,23,42,.16)}.ss-hero h1{margin:0 0 6px;font-size:26px;font-weight:700}.ss-hero p{margin:0;opacity:.94}.ss-card{border-radius:12px;background:#fff;border:1px solid #e5edf5;box-shadow:0 5px 16px rgba(15,23,42,.05);margin-bottom:14px}.ss-kpi{padding:14px;border-radius:12px;background:#f8fafc;border:1px solid #e5edf5}.ss-kpi b{font-size:22px;display:block}#dtb_shift_schedule th,#dtb_shift_schedule td{font-size:12px;vertical-align:middle}.select2-container{width:100%!important}.required-label:after{content:' *';color:#dd4b39}.ss-action{white-space:nowrap}#modal_shift_schedule .modal-body{max-height:calc(100vh - 185px);overflow-y:auto}.ss-section-title{font-weight:700;color:#334155;margin:8px 0 12px;border-bottom:1px solid #e5e7eb;padding-bottom:7px}.ss-day-box{background:#f8fafc;border:1px solid #e2e8f0;border-radius:10px;padding:10px;margin-bottom:10px}
</style>
<section class="content-header"><h1><?=hr_h('hr_shift_schedule', 'Shift Schedule');?> <small>SAP HR Shift Planning</small></h1><ol class="breadcrumb"><li><a href="<?=base_index();?>"><i class="fa fa-dashboard"></i> <?=hr_h('common_home', 'Home');?></a></li><li>Human Resource</li><li>Time Management</li><li class="active"><?=hr_h('hr_shift_schedule', 'Shift Schedule');?></li></ol></section>
<section class="content">
<div class="ss-hero"><div class="row"><div class="col-md-8"><h1>Shift Schedule Workbench</h1><p>Kelola roster karyawan per periode: employee, shift, work schedule, lokasi, hari kerja, planned hours, release/cancel, dan export monitoring.</p></div><div class="col-md-4 text-right"><?php if($canInsert){ ?><button id="btn_open_ss" class="btn btn-warning"><i class="fa fa-plus"></i> Create Shift Schedule</button><?php } ?> <button id="btn_export_ss" class="btn btn-success"><i class="fa fa-file-excel-o"></i> <?=hr_h('common_export_excel', 'Export Excel');?></button></div></div></div>
<div class="row"><div class="col-sm-2"><div class="ss-kpi"><span>Total</span><b id="kpi_total">0</b></div></div><div class="col-sm-2"><div class="ss-kpi"><span>Released</span><b id="kpi_released">0</b></div></div><div class="col-sm-2"><div class="ss-kpi"><span>Planned</span><b id="kpi_planned">0</b></div></div><div class="col-sm-2"><div class="ss-kpi"><span>Rotation</span><b id="kpi_rotation">0</b></div></div><div class="col-sm-2"><div class="ss-kpi"><span><?=hr_h('hr_overtime', 'Overtime');?></span><b id="kpi_overtime">0</b></div></div><div class="col-sm-2"><div class="ss-kpi"><span><?=hr_h('hr_period', 'Period');?></span><b><?=date('M Y');?></b></div></div></div>
<div class="box ss-card"><div class="box-header"><h3 class="box-title"><i class="fa fa-filter"></i> Filter Shift Schedule</h3></div><div class="box-body"><form class="form-horizontal" onsubmit="return false;"><div class="form-group"><label class="control-label col-lg-2"><?=hr_h('hr_period', 'Period');?></label><div class="col-lg-2"><div class="input-group date ss-date"><input id="filter_tgl_awal" class="form-control" value="<?=$defaultFrom;?>"><span class="input-group-addon"><span class="glyphicon glyphicon-calendar"></span></span></div></div><div class="col-lg-2"><div class="input-group date ss-date"><input id="filter_tgl_akhir" class="form-control" value="<?=$defaultTo;?>"><span class="input-group-addon"><span class="glyphicon glyphicon-calendar"></span></span></div></div><label class="control-label col-lg-1"><?=hr_h('hr_employee', 'Employee');?></label><div class="col-lg-3"><select id="filter_employee_id" class="form-control"></select></div><label class="control-label col-lg-1"><?=hr_h('common_status', 'Status');?></label><div class="col-lg-1"><select id="filter_assignment_status" class="form-control"><option value="">All</option><option>DRAFT</option><option>PLANNED</option><option>RELEASED</option><option>CANCELLED</option></select></div></div><div class="form-group"><label class="control-label col-lg-2"><?=hr_h('hr_department', 'Department');?></label><div class="col-lg-2"><select id="filter_department_code" class="form-control"></select></div><label class="control-label col-lg-1"><?=hr_h('hr_shift', 'Shift');?></label><div class="col-lg-2"><select id="filter_shift_id" class="form-control"></select></div><label class="control-label col-lg-1">Roster</label><div class="col-lg-2"><select id="filter_roster_type" class="form-control"><option value="">All</option><option>REGULAR</option><option>ROTATION</option><option>OVERTIME</option><option>REPLACEMENT</option><option>TEMPORARY</option></select></div><div class="col-lg-2"><input id="filter_keyword" class="form-control" placeholder="Assignment no, employee, group"></div></div><div class="form-group"><div class="col-lg-offset-2 col-lg-10"><button id="btn_filter_ss" class="btn btn-primary"><i class="fa fa-filter"></i> <?=hr_h('common_filter', 'Filter');?></button> <button id="btn_reset_ss" class="btn btn-default"><i class="fa fa-refresh"></i> <?=hr_h('common_reset', 'Reset');?></button></div></div></form></div></div>
<div class="box ss-card"><div class="box-body"><div class="alert alert-warning error_data_delete" style="display:none"><button type="button" class="close hide_alert_notif">&times;</button><span class="isi_warning_delete"></span></div><div class="table-responsive"><table id="dtb_shift_schedule" class="table table-bordered table-striped" style="width:100%"><thead><tr><th><?=hr_h('common_no', 'No');?></th><th><?=hr_h('common_action', 'Action');?></th><th>Assignment</th><th><?=hr_h('hr_employee', 'Employee');?></th><th><?=hr_h('hr_department', 'Department');?></th><th>Shift / Hours</th><th>Days</th><th>Roster</th><th><?=hr_h('common_status', 'Status');?></th><th>Updated</th></tr></thead><tbody></tbody></table></div></div></div>
<div id="modal_shift_schedule" class="modal fade"><div class="modal-dialog modal-lg" style="width:94%"><div class="modal-content"><form id="form_shift_schedule"><input type="hidden" name="id" id="ss_id"><div class="modal-header"><button type="button" class="close" data-dismiss="modal">&times;</button><h4 class="modal-title">Create Shift Schedule</h4></div><div class="modal-body"><div class="alert alert-info"><strong>SAP hint:</strong> Shift Schedule adalah assignment roster employee untuk periode tertentu. Release jadwal jika sudah siap dipakai attendance.</div>
<div class="ss-section-title">Assignment Data</div><div class="row"><div class="col-md-2 form-group"><label class="required-label">Assignment No</label><input name="assignment_no" id="assignment_no" class="form-control text-uppercase" required maxlength="30" placeholder="SS-..."></div><div class="col-md-4 form-group"><label class="required-label"><?=hr_h('hr_employee', 'Employee');?></label><select name="employee_id" id="employee_id" class="form-control" required></select></div><div class="col-md-3 form-group"><label><?=hr_h('hr_department', 'Department');?></label><select name="department_code" id="department_code" class="form-control"></select></div><div class="col-md-3 form-group"><label><?=hr_h('hr_work_schedule', 'Work Schedule');?></label><select name="work_schedule_id" id="work_schedule_id" class="form-control"></select></div></div>
<div class="row"><div class="col-md-3 form-group"><label class="required-label"><?=hr_h('hr_shift', 'Shift');?></label><select name="shift_id" id="shift_id" class="form-control" required></select></div><div class="col-md-3 form-group"><label><?=hr_h('hr_work_location', 'Work Location');?></label><select name="work_location_id" id="work_location_id" class="form-control"></select></div><div class="col-md-2 form-group"><label>Schedule From</label><input name="schedule_from" id="schedule_from" class="form-control date-field" value="<?=$defaultFrom;?>"></div><div class="col-md-2 form-group"><label>Schedule To</label><input name="schedule_to" id="schedule_to" class="form-control date-field" value="<?=$defaultTo;?>"></div><div class="col-md-2 form-group"><label><?=hr_h('common_status', 'Status');?></label><select name="assignment_status" id="assignment_status" class="form-control"><option>DRAFT</option><option>PLANNED</option><option>RELEASED</option><option>CANCELLED</option></select></div></div>
<div class="ss-section-title">Roster Pattern</div><div class="ss-day-box"><div class="row"><div class="col-md-1 form-group"><label>Mon</label><select name="monday" id="monday" class="form-control"><option>Y</option><option>N</option></select></div><div class="col-md-1 form-group"><label>Tue</label><select name="tuesday" id="tuesday" class="form-control"><option>Y</option><option>N</option></select></div><div class="col-md-1 form-group"><label>Wed</label><select name="wednesday" id="wednesday" class="form-control"><option>Y</option><option>N</option></select></div><div class="col-md-1 form-group"><label>Thu</label><select name="thursday" id="thursday" class="form-control"><option>Y</option><option>N</option></select></div><div class="col-md-1 form-group"><label>Fri</label><select name="friday" id="friday" class="form-control"><option>Y</option><option>N</option></select></div><div class="col-md-1 form-group"><label>Sat</label><select name="saturday" id="saturday" class="form-control"><option>N</option><option>Y</option></select></div><div class="col-md-1 form-group"><label>Sun</label><select name="sunday" id="sunday" class="form-control"><option>N</option><option>Y</option></select></div><div class="col-md-2 form-group"><label>Planned Start</label><input name="planned_start" id="planned_start" class="form-control" placeholder="08:00"></div><div class="col-md-2 form-group"><label>Planned End</label><input name="planned_end" id="planned_end" class="form-control" placeholder="17:00"></div><div class="col-md-1 form-group"><label>Break</label><input name="break_minutes" id="break_minutes" type="number" min="0" class="form-control" value="60"></div></div></div>
<div class="row"><div class="col-md-2 form-group"><label>Hours / Day</label><input name="planned_hours_per_day" id="planned_hours_per_day" type="number" step="0.01" min="0.01" class="form-control" value="8"></div><div class="col-md-2 form-group"><label>Roster Type</label><select name="roster_type" id="roster_type" class="form-control"><option>REGULAR</option><option>ROTATION</option><option>OVERTIME</option><option>REPLACEMENT</option><option>TEMPORARY</option></select></div><div class="col-md-2 form-group"><label>Source Type</label><select name="source_type" id="source_type" class="form-control"><option>MANUAL</option><option>WORK_SCHEDULE</option><option>ROTATION_PLAN</option><option>IMPORT</option></select></div><div class="col-md-2 form-group"><label>Rotation Group</label><input name="rotation_group" id="rotation_group" class="form-control text-uppercase"></div><div class="col-md-2 form-group"><label><?=hr_h('hr_overtime', 'Overtime');?></label><select name="overtime_eligible" id="overtime_eligible" class="form-control"><option>Y</option><option>N</option></select></div><div class="col-md-2 form-group"><label><?=hr_h('hr_attendance', 'Attendance');?></label><select name="attendance_required" id="attendance_required" class="form-control"><option>Y</option><option>N</option></select></div></div>
<div class="row"><div class="col-md-4 form-group"><label>SAP Reference</label><input name="sap_reference" id="sap_reference" class="form-control"></div><div class="col-md-8 form-group"><label><?=hr_h('common_remarks', 'Remarks');?></label><textarea name="remarks" id="remarks" class="form-control" rows="2"></textarea></div></div>
</div><div class="modal-footer"><button type="button" class="btn btn-default" data-dismiss="modal"><?=hr_h('common_cancel', 'Cancel');?></button><button type="submit" class="btn btn-primary"><i class="fa fa-save"></i> Save Shift Schedule</button></div></form></div></div></div>
<div id="modal_ss_detail" class="modal fade"><div class="modal-dialog modal-lg" style="width:92%"><div class="modal-content"><div class="modal-header"><button class="close" data-dismiss="modal">&times;</button><h4 class="modal-title">Shift Schedule Detail</h4></div><div class="modal-body" id="ss_detail_body"></div><div class="modal-footer"><button class="btn btn-default" data-dismiss="modal"><?=hr_h('common_close', 'Close');?></button></div></div></div></div>
</section>
<script src="<?=base_admin();?>assets/plugins/select2/select2.min.js"></script><script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
<script>
function ssError(m){$('.isi_warning_delete').text(m||<?=hr_js('hr_shift_schedule_process_failed', 'Shift Schedule failed to process.');?>);$('.error_data_delete').fadeIn();}
function ssFilters(){return{tgl_awal:$('#filter_tgl_awal').val(),tgl_akhir:$('#filter_tgl_akhir').val(),employee_id:$('#filter_employee_id').val(),department_code:$('#filter_department_code').val(),shift_id:$('#filter_shift_id').val(),assignment_status:$('#filter_assignment_status').val(),roster_type:$('#filter_roster_type').val(),keyword:$('#filter_keyword').val()};}
function ssSet(s,v,t){var e=$(s);if(!v){e.val(null).trigger('change');return;}if(!e.find('option[value="'+v+'"]').length)e.append(new Option(t||v,v,true,true));e.val(v).trigger('change');}
function ssAjax(selector,act,placeholder,parent){$(selector).select2({width:'100%',allowClear:true,placeholder:placeholder,dropdownParent:parent||$(document.body),ajax:{url:'<?=base_admin();?>modul/shift_schedule/shift_schedule_action.php?act='+act,type:'POST',dataType:'json',delay:250,data:function(q){return{term:q.term||''};},processResults:function(d){return{results:d.results||[]};}}});}
function ssReset(title){$('#form_shift_schedule')[0].reset();$('#ss_id').val('');$('#employee_id,#department_code,#work_schedule_id,#shift_id,#work_location_id').val(null).trigger('change');$('#assignment_status').val('DRAFT').trigger('change');$('#roster_type').val('REGULAR').trigger('change');$('#source_type').val('MANUAL').trigger('change');$('#monday,#tuesday,#wednesday,#thursday,#friday').val('Y').trigger('change');$('#saturday,#sunday').val('N').trigger('change');$('#overtime_eligible,#attendance_required').val('Y').trigger('change');$('#schedule_from').val('<?=$defaultFrom;?>');$('#schedule_to').val('<?=$defaultTo;?>');$('#break_minutes').val(60);$('#planned_hours_per_day').val(8);$('#modal_shift_schedule .modal-title').text(title||'Create Shift Schedule');}
$(function(){if($.fn.datepicker){$('.ss-date,.date-field').datepicker({format:'yyyy-mm-dd',autoclose:true,todayHighlight:true});}if($.fn.select2){$('#filter_assignment_status,#filter_roster_type,#assignment_status,#roster_type,#source_type,#monday,#tuesday,#wednesday,#thursday,#friday,#saturday,#sunday,#overtime_eligible,#attendance_required').select2({width:'100%',allowClear:true});ssAjax('#filter_employee_id','employee_search','Semua Employee');ssAjax('#filter_department_code','department_search','Semua Department');ssAjax('#filter_shift_id','shift_search','Semua Shift');ssAjax('#employee_id','employee_search','Pilih Employee',$('#modal_shift_schedule'));ssAjax('#department_code','department_search','Pilih Department',$('#modal_shift_schedule'));ssAjax('#work_schedule_id','work_schedule_search','Pilih Work Schedule',$('#modal_shift_schedule'));ssAjax('#shift_id','shift_search','Pilih Shift',$('#modal_shift_schedule'));ssAjax('#work_location_id','work_location_search','Pilih Work Location',$('#modal_shift_schedule'));}
var dt=$('#dtb_shift_schedule').DataTable({bProcessing:true,bServerSide:true,pageLength:25,dom:"<'row'<'col-sm-12'B>>"+"<'row'<'col-sm-6'l><'col-sm-6'f>>"+"<'row'<'col-sm-12'tr>>"+"<'row'<'col-sm-5'i><'col-sm-7'p>>",buttons:[{extend:'collection',text:<?=hr_js('common_export_data', 'Export Data');?>,buttons:['copyHtml5','excelHtml5','csvHtml5','pdfHtml5']}],columnDefs:[{targets:[0,1],orderable:false,searchable:false},{width:'42px',targets:0},{width:'180px',targets:1}],ajax:{url:'<?=base_admin();?>modul/shift_schedule/shift_schedule_data.php',type:'post',data:function(d){$.extend(d,ssFilters());},dataSrc:function(j){var k=j.kpi||{};$('#kpi_total').text(k.total||0);$('#kpi_released').text(k.released||0);$('#kpi_planned').text(k.planned||0);$('#kpi_rotation').text(k.rotation||0);$('#kpi_overtime').text(k.overtime||0);return j.data||[];},error:function(x){console.log(x.responseText);ssError(<?=hr_js('hr_shift_schedule_load_failed', 'Shift Schedule data failed to load.');?>);}}});
$('#btn_open_ss').click(function(){ssReset('Create Shift Schedule');$('#modal_shift_schedule').modal({backdrop:'static',keyboard:false});});$('#btn_filter_ss').click(function(){dt.draw();});$('#filter_keyword').keyup(function(e){if(e.keyCode===13)dt.draw();});$('#btn_reset_ss').click(function(){$('#filter_tgl_awal').val('<?=$defaultFrom;?>');$('#filter_tgl_akhir').val('<?=$defaultTo;?>');$('#filter_employee_id,#filter_department_code,#filter_shift_id,#filter_assignment_status,#filter_roster_type').val(null).trigger('change');$('#filter_keyword').val('');dt.draw();});$('#btn_export_ss').click(function(){window.location='<?=base_admin();?>modul/shift_schedule/shift_schedule_action.php?act=export&'+$.param(ssFilters());});$('.hide_alert_notif').click(function(){$('.error_data_delete').hide();});$('#assignment_no,#rotation_group').on('keyup change',function(){this.value=this.value.toUpperCase();});
$('#employee_id').on('select2:select',function(e){$.post('<?=base_admin();?>modul/shift_schedule/shift_schedule_action.php?act=employee_info',{employee_id:e.params.data.id},function(r){if(r.status==='good')ssSet('#department_code',r.department_code,r.department_text);},'json');});
$('#shift_id').on('select2:select',function(e){var txt=e.params.data.text||'',m=txt.match(/\((\d{2}:\d{2})-(\d{2}:\d{2})\)/);if(m){$('#planned_start').val(m[1]);$('#planned_end').val(m[2]);}else{$.post('<?=base_admin();?>modul/shift_schedule/shift_schedule_action.php?act=shift_info',{shift_id:e.params.data.id},function(r){if(r.status==='good'){$('#planned_start').val(r.planned_start);$('#planned_end').val(r.planned_end);}},'json');}});
$('#form_shift_schedule').submit(function(e){e.preventDefault();var b=$(this).find('button[type=submit]');b.prop('disabled',true).html('<i class="fa fa-spinner fa-spin"></i> <?=hr_h('common_saving', 'Saving...');?>');$.post('<?=base_admin();?>modul/shift_schedule/shift_schedule_action.php?act=save',$(this).serialize(),function(r){b.prop('disabled',false).html('<i class="fa fa-save"></i> Save Shift Schedule');if(r.status==='good'){$('#modal_shift_schedule').modal('hide');dt.draw(false);Swal.fire('Saved','Shift Schedule berhasil disimpan.','success');}else ssError(r.error_message);},'json').fail(function(x){b.prop('disabled',false).html('<i class="fa fa-save"></i> Save Shift Schedule');ssError(x.responseText);});});
$(document).on('click','.btn-ss-detail',function(){$.post('<?=base_admin();?>modul/shift_schedule/shift_schedule_action.php?act=detail',{id:$(this).data('id')},function(h){$('#ss_detail_body').html(h);$('#modal_ss_detail').modal('show');});});
$(document).on('click','.btn-ss-edit',function(){var id=$(this).data('id');$.post('<?=base_admin();?>modul/shift_schedule/shift_schedule_action.php?act=get',{id:id},function(r){if(r.status!=='good'){ssError(r.error_message);return;}ssReset('Edit Shift Schedule');var h=r.data||{};Object.keys(h).forEach(function(k){var el=$('#'+k);if(el.length&&!['employee_id','department_code','work_schedule_id','shift_id','work_location_id'].includes(k))el.val(h[k]);});$('#ss_id').val(h.id);ssSet('#employee_id',h.employee_id,h.employee_text);ssSet('#department_code',h.department_code,h.department_text);ssSet('#work_schedule_id',h.work_schedule_id,h.work_schedule_text);ssSet('#shift_id',h.shift_id,h.shift_text);ssSet('#work_location_id',h.work_location_id,h.work_location_text);$('#assignment_status,#roster_type,#source_type,#monday,#tuesday,#wednesday,#thursday,#friday,#saturday,#sunday,#overtime_eligible,#attendance_required').trigger('change');$('#modal_shift_schedule').modal({backdrop:'static',keyboard:false});},'json');});
$(document).on('click','.btn-ss-status',function(){var id=$(this).data('id'),status=$(this).data('status');$.post('<?=base_admin();?>modul/shift_schedule/shift_schedule_action.php?act=status',{id:id,status:status},function(r){if(r.status==='good'){dt.draw(false);Swal.fire('Updated','Status berhasil diubah.','success');}else ssError(r.error_message);},'json');});
$(document).on('click','.btn-ss-delete',function(){if($(this).is(':disabled'))return;var id=$(this).data('id'),no=$(this).data('no');Swal.fire({title:erpLang('confirm_delete_title','Delete Confirmation'),text:no,icon:'warning',showCancelButton:true,confirmButtonText:erpLang('common_delete','Delete'),cancelButtonText:erpLang('common_cancel','Cancel')}).then(function(x){if(!x.isConfirmed)return;$.post('<?=base_admin();?>modul/shift_schedule/shift_schedule_action.php?act=delete',{id:id},function(r){if(r.status==='good'){dt.draw(false);Swal.fire(erpLang('common_deleted','Deleted'),erpLang('common_deleted_message','Data deleted successfully.'),'success');}else ssError(r.error_message);},'json').fail(function(x){ssError(x.responseText);});});});
});
</script>
