<?php
if (!function_exists('prod_t')) {
  function prod_t($key, $fallback = '') { return lang_text($key, $fallback); }
}
if (!function_exists('prod_h')) {
  function prod_h($key, $fallback = '') { return htmlspecialchars((string) prod_t($key, $fallback), ENT_QUOTES, 'UTF-8'); }
}
if (!function_exists('prod_js')) {
  function prod_js($key, $fallback = '') { return json_encode(prod_t($key, $fallback), JSON_HEX_TAG | JSON_HEX_APOS | JSON_HEX_AMP | JSON_HEX_QUOT); }
}
if(session_status()===PHP_SESSION_NONE)session_start();
include "../../inc/config.php";
session_check_json();
error_reporting(E_ALL & ~E_NOTICE & ~E_WARNING & ~E_DEPRECATED & ~E_USER_DEPRECATED);
function poma_h($v){return htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');}
function poma_num($v,$d=5){return number_format((float)$v,$d,',','.');}
function poma_pct($a,$b){$b=(float)$b;return $b>0?max(0,min(100,round(((float)$a/$b)*100,1))):0;}
$act=isset($_GET['act'])?$_GET['act']:'';
switch($act){
  case 'detail':
    $id=isset($_POST['id'])?(int)$_POST['id']:0;
    $po=$db->fetch("SELECT * FROM production_order WHERE id_production_order=? LIMIT 1",array($id));
    if(!$po){echo '<div class="alert alert-warning">Production Order tidak ditemukan.</div>';break;}
    $mats=$db->query("SELECT * FROM production_order_material WHERE id_production_order=? ORDER BY id_material",array($id));
    $ops=$db->query("SELECT * FROM production_order_operation WHERE id_production_order=? ORDER BY CAST(operation_no AS UNSIGNED),operation_no,id_operation",array($id));
    $schedules=$db->query("SELECT * FROM erp_production_schedule WHERE id_production_order=? ORDER BY planned_start,id",array($id));
    $gis=$db->query("SELECT h.*,COUNT(d.id) item_count,SUM(d.issued_qty) total_qty FROM erp_issue_production h LEFT JOIN erp_issue_production_detail d ON d.issue_id=h.id WHERE h.production_id=? GROUP BY h.id ORDER BY h.posting_date,h.id",array($id));
    $confs=$db->query("SELECT * FROM production_order_confirmation WHERE id_production_order=? ORDER BY posting_date,id_confirmation",array($id));
    $grs=$db->query("SELECT h.*,SUM(d.qty) total_qty FROM erp_gr_production h LEFT JOIN erp_gr_production_detail d ON d.gr_id=h.id WHERE h.id_production_order=? GROUP BY h.id ORDER BY h.posting_date,h.id",array($id));
    echo '<h3 style="margin-top:0">'.poma_h($po->no_production_order).' <small>'.poma_h($po->status).'</small></h3><div class="row"><div class="col-sm-4"><strong>Material</strong><br>'.poma_h($po->material_code.' - '.$po->material_name).'</div><div class="col-sm-2"><strong>Qty</strong><br>'.poma_num($po->order_qty).' '.poma_h($po->uom).'</div><div class="col-sm-2"><strong>Completed/Scrap</strong><br>'.poma_num($po->completed_qty).' / '.poma_num($po->scrap_qty).'</div><div class="col-sm-2"><strong>Plant</strong><br>'.poma_h($po->plant.' / '.$po->storage_location).'</div><div class="col-sm-2"><strong>Schedule</strong><br>'.poma_h($po->start_date.' s/d '.$po->finish_date).'</div></div><hr>';
    echo '<h4>Material Requirement vs Issue</h4><div class="table-responsive"><table class="table table-bordered table-condensed"><thead><tr class="bg-gray"><th>Material</th><th class="text-right">Required</th><th class="text-right">Issued</th><th class="text-right">Remaining</th><th>UOM</th><th>Status</th></tr></thead><tbody>';
    foreach($mats as $m){$pct=poma_pct($m->issued_qty,$m->required_qty);$cls=$pct>=100?'success':'danger';echo '<tr><td><strong>'.poma_h($m->material_code).'</strong><br><small>'.poma_h($m->material_name).'</small></td><td class="text-right">'.poma_num($m->required_qty).'</td><td class="text-right">'.poma_num($m->issued_qty).'</td><td class="text-right">'.poma_num($m->remaining_qty).'</td><td>'.poma_h($m->uom).'</td><td><span class="label label-'.$cls.'">'.$pct.'%</span></td></tr>';}
    echo '</tbody></table></div><h4>Operations</h4><table class="table table-bordered table-condensed"><thead><tr class="bg-gray"><th>Op</th><th>Work Center</th><th>Name</th><th class="text-right">Setup</th><th class="text-right">Machine</th><th class="text-right">Labor</th><th>Status</th></tr></thead><tbody>';
    foreach($ops as $o)echo '<tr><td>'.poma_h($o->operation_no).'</td><td>'.poma_h($o->work_center).'</td><td>'.poma_h($o->operation_name).'</td><td class="text-right">'.poma_num($o->setup_time,2).'</td><td class="text-right">'.poma_num($o->machine_time,2).'</td><td class="text-right">'.poma_num($o->labor_time,2).'</td><td>'.poma_h($o->status).'</td></tr>';
    echo '</tbody></table><div class="row"><div class="col-md-6"><h4>Production Schedule</h4><table class="table table-bordered table-condensed"><thead><tr class="bg-gray"><th>Schedule</th><th>Plan</th><th>Status</th></tr></thead><tbody>';
    foreach($schedules as $s)echo '<tr><td>'.poma_h($s->schedule_no).'</td><td>'.poma_h($s->planned_start.' s/d '.$s->planned_finish).'</td><td>'.poma_h($s->dispatch_status).'</td></tr>';
    echo '</tbody></table></div><div class="col-md-6"><h4>Goods Issue 261</h4><table class="table table-bordered table-condensed"><thead><tr class="bg-gray"><th>GI</th><th>Date</th><th class="text-right">Qty</th><th>Status</th></tr></thead><tbody>';
    foreach($gis as $g)echo '<tr><td>'.poma_h($g->issue_no).'</td><td>'.poma_h($g->posting_date).'</td><td class="text-right">'.poma_num($g->total_qty).'</td><td>'.poma_h($g->status).'</td></tr>';
    echo '</tbody></table></div></div><div class="row"><div class="col-md-6"><h4>Confirmations</h4><table class="table table-bordered table-condensed"><thead><tr class="bg-gray"><th>Confirmation</th><th>Operation</th><th class="text-right">Yield</th><th class="text-right">Scrap</th><th>Status</th></tr></thead><tbody>';
    foreach($confs as $c)echo '<tr><td>'.poma_h($c->confirmation_no).'<br><small>'.poma_h($c->posting_date).'</small></td><td>'.poma_h($c->operation_no.' / '.$c->work_center).'</td><td class="text-right">'.poma_num($c->yield_qty).'</td><td class="text-right">'.poma_num($c->scrap_qty).'</td><td>'.poma_h($c->status).'</td></tr>';
    echo '</tbody></table></div><div class="col-md-6"><h4>GR from Production 101</h4><table class="table table-bordered table-condensed"><thead><tr class="bg-gray"><th>GR</th><th>Date</th><th class="text-right">Qty</th><th>Status</th></tr></thead><tbody>';
    foreach($grs as $g)echo '<tr><td>'.poma_h($g->gr_no).'<br><small>'.poma_h($g->confirmation_no).'</small></td><td>'.poma_h($g->posting_date).'</td><td class="text-right">'.poma_num($g->total_qty).'</td><td>'.poma_h($g->status).'</td></tr>';
    echo '</tbody></table></div></div>';break;
  case 'excel':
    $initial=ob_get_level();ob_start();require_once "../../inc/lib/PHPExcel.php";require_once "../../inc/excel_style_helper.php";PHPExcel_Shared_File::setUseUploadTempDirectory(true);$from=isset($_GET['tgl_awal'])?$_GET['tgl_awal']:date('Y-m-01');$to=isset($_GET['tgl_akhir'])?$_GET['tgl_akhir']:date('Y-m-d');$status=isset($_GET['status'])?trim($_GET['status']):'';$plant=isset($_GET['plant'])?trim($_GET['plant']):'';$p=array($from,$to);$w=" WHERE p.start_date BETWEEN ? AND ? ";if($status!==''){$w.=" AND p.status=? ";$p[]=$status;}if($plant!==''){$w.=" AND p.plant=? ";$p[]=$plant;}
    $rows=$db->query("SELECT p.*,COALESCE(mat.required_qty,0) required_qty,COALESCE(mat.issued_qty,0) issued_qty,COALESCE(conf.yield_qty,0) yield_qty,COALESCE(conf.scrap_qty,0) conf_scrap_qty,COALESCE(gr.gr_qty,0) gr_qty FROM production_order p LEFT JOIN(SELECT id_production_order,SUM(required_qty) required_qty,SUM(issued_qty) issued_qty FROM production_order_material GROUP BY id_production_order) mat ON mat.id_production_order=p.id_production_order LEFT JOIN(SELECT id_production_order,SUM(CASE WHEN status='POSTED' THEN yield_qty ELSE 0 END) yield_qty,SUM(CASE WHEN status='POSTED' THEN scrap_qty ELSE 0 END) scrap_qty FROM production_order_confirmation GROUP BY id_production_order) conf ON conf.id_production_order=p.id_production_order LEFT JOIN(SELECT h.id_production_order,SUM(CASE WHEN h.status='POSTED' THEN d.qty ELSE 0 END) gr_qty FROM erp_gr_production h JOIN erp_gr_production_detail d ON d.gr_id=h.id GROUP BY h.id_production_order) gr ON gr.id_production_order=p.id_production_order $w ORDER BY p.start_date,p.id_production_order",$p);
    $excel=new PHPExcel();$sh=$excel->setActiveSheetIndex(0);$sh->setTitle(erp_export_sheet_title('PO Monitoring'));$heads=array(erp_export_label("No"),erp_export_label("Production Order"),erp_export_label("Status"),erp_export_label("Plant"),erp_export_label("Material"),erp_export_label("Order Qty"),erp_export_label("UOM"),erp_export_label("Start"),erp_export_label("Finish"),erp_export_label("Required Mat"),erp_export_label("Issued Mat"),erp_export_label("Material %"),erp_export_label("Yield"),erp_export_label("Confirm %"),erp_export_label("GR Qty"),erp_export_label("GR %"),erp_export_label("Scrap"));foreach($heads as $i=>$v)$sh->setCellValue(PHPExcel_Cell::stringFromColumnIndex($i).'4',$v);$r=5;$n=1;foreach($rows as $row){$vals=array($n++,$row->no_production_order,$row->status,$row->plant,$row->material_code.' - '.$row->material_name,(float)$row->order_qty,$row->uom,$row->start_date,$row->finish_date,(float)$row->required_qty,(float)$row->issued_qty,poma_pct($row->issued_qty,$row->required_qty),(float)$row->yield_qty,poma_pct($row->yield_qty,$row->order_qty),(float)$row->gr_qty,poma_pct($row->gr_qty,$row->order_qty),(float)$row->conf_scrap_qty);foreach($vals as $i=>$v)$sh->setCellValue(PHPExcel_Cell::stringFromColumnIndex($i).$r,$v);$r++;}
    erpkb_excel_apply_standard_style($excel,array('sheet'=>$sh,'title'=>erp_export_title('PRODUCTION ORDER MONITORING'),'header_row'=>4,'first_data_row'=>5,'last_data_row'=>max(5,$r-1),'column_count'=>17,'numeric_columns'=>array('F','J','K','M','O','Q'),'decimal_columns'=>array('L','N','P'),'filters'=>array('Start Date'=>$from.' s/d '.$to,'Status'=>$status?:erp_export_all_text(),'Plant'=>$plant?:erp_export_all_text())));$tmp=erpkb_excel_temp_file('production_order_monitoring_');PHPExcel_IOFactory::createWriter($excel,'Excel2007')->save($tmp);$size=@filesize($tmp);$sig=@file_get_contents($tmp,false,null,0,2);if(!$size||$sig!=='PK'){@unlink($tmp);while(ob_get_level()>$initial)ob_end_clean();header('Content-Type:text/plain; charset=utf-8');echo erp_t('export_excel_invalid_file','File Excel gagal dibuat dengan benar.');exit;}while(ob_get_level()>$initial)ob_end_clean();header('Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');header('Content-Disposition: attachment; filename="production_order_monitoring_'.date('Ymd_His').'.xlsx"');header('Content-Length: '.$size);header('Cache-Control: max-age=0');header('Pragma: public');readfile($tmp);@unlink($tmp);exit;
  default:header('Content-Type: application/json');echo json_encode(array('status'=>'error','error_message'=>'Action tidak dikenal.'));
}
?>
