<?php
if (!function_exists('prod_t')) {
  function prod_t($key, $fallback = '') { return lang_text($key, $fallback); }
}
if (!function_exists('prod_h')) {
  function prod_h($key, $fallback = '') { return htmlspecialchars((string) prod_t($key, $fallback), ENT_QUOTES, 'UTF-8'); }
}
if (!function_exists('prod_js')) {
  function prod_js($key, $fallback = '') { return json_encode(prod_t($key, $fallback), JSON_HEX_TAG | JSON_HEX_APOS | JSON_HEX_AMP | JSON_HEX_QUOT); }
}
$defaultFrom=date('Y-m-01');$defaultTo=date('Y-m-d');
$plants=$db->query("SELECT DISTINCT plant AS plant_code FROM production_order WHERE plant IS NOT NULL AND plant<>'' ORDER BY plant");
$kpi=$db->fetch("SELECT COUNT(*) total_order,SUM(status='RELEASED') released_order,SUM(status='IN_PROCESS') in_process_order,SUM(status IN ('CONFIRMED','TECO','CLOSED')) completed_flow FROM production_order WHERE start_date BETWEEN ? AND ?",array($defaultFrom,$defaultTo));
?>
<style>
.pom-hero{background:linear-gradient(135deg,#1d4ed8,#7c3aed);color:#fff;border-radius:14px;padding:20px 22px;margin-bottom:18px;box-shadow:0 10px 24px rgba(15,23,42,.18)}.pom-hero h1{margin:0 0 6px;font-size:26px;font-weight:700}.pom-hero p{margin:0;opacity:.92}.pom-card{border-radius:12px;background:#fff;border:1px solid #e5edf5;box-shadow:0 5px 16px rgba(15,23,42,.05);margin-bottom:14px}.pom-kpi{border-radius:12px;background:#fff;border:1px solid #edf2f7;padding:15px;margin-bottom:14px}.pom-kpi span{display:block;color:#64748b;font-size:12px;text-transform:uppercase}.pom-kpi strong{display:block;font-size:24px;margin-top:6px}.pom-kpi i{float:right;font-size:26px;color:#1d4ed8;opacity:.55}#dtb_production_order_monitoring th,#dtb_production_order_monitoring td{font-size:12px;vertical-align:middle}.select2-container{width:100%!important}.progress-xs{height:7px}.pom-progress{min-width:150px}.pom-actions{white-space:nowrap}
</style>
<section class="content-header"><h1>Production Order Monitoring <small>SAP PP Order Cockpit</small></h1><ol class="breadcrumb"><li><a href="<?=base_index();?>"><i class="fa fa-dashboard"></i> <?=prod_h('common_home', 'Home');?></a></li><li class="active">Production Order Monitoring</li></ol></section>
<section class="content">
  <div class="pom-hero"><div class="row"><div class="col-md-8"><h1>Production Order Monitoring Cockpit</h1><p>Monitor end-to-end order produksi: schedule, material issue 261, confirmation, GR 101, progress, dan exception.</p></div><div class="col-md-4 text-right"><button id="btn_excel_pom_top" class="btn btn-success"><i class="fa fa-file-excel-o"></i> Export Monitoring</button></div></div></div>
  <div class="row"><div class="col-sm-3"><div class="pom-kpi"><i class="fa fa-file-text-o"></i><span><?=prod_h('production_total_order', 'Total Order');?></span><strong><?=number_format((float)$kpi->total_order,0,',','.');?></strong></div></div><div class="col-sm-3"><div class="pom-kpi"><i class="fa fa-unlock"></i><span><?=prod_h('production_released', 'Released');?></span><strong><?=number_format((float)$kpi->released_order,0,',','.');?></strong></div></div><div class="col-sm-3"><div class="pom-kpi"><i class="fa fa-cogs"></i><span><?=prod_h('production_in_process', 'In Process');?></span><strong><?=number_format((float)$kpi->in_process_order,0,',','.');?></strong></div></div><div class="col-sm-3"><div class="pom-kpi"><i class="fa fa-check"></i><span>Confirmed/Closed</span><strong><?=number_format((float)$kpi->completed_flow,0,',','.');?></strong></div></div></div>
  <div class="box pom-card"><div class="box-header"><h3 class="box-title"><i class="fa fa-filter"></i> Filter Monitoring</h3></div><div class="box-body"><form class="form-horizontal" onsubmit="return false;"><div class="form-group"><label class="control-label col-lg-2"><?=prod_h('production_start_date', 'Start Date');?></label><div class="col-lg-2"><div class="input-group date pom-date"><input id="filter_tgl_awal" class="form-control" value="<?=$defaultFrom;?>"><span class="input-group-addon"><span class="glyphicon glyphicon-calendar"></span></span></div></div><div class="col-lg-2"><div class="input-group date pom-date"><input id="filter_tgl_akhir" class="form-control" value="<?=$defaultTo;?>"><span class="input-group-addon"><span class="glyphicon glyphicon-calendar"></span></span></div></div><label class="control-label col-lg-1"><?=prod_h('common_status', 'Status');?></label><div class="col-lg-2"><select id="filter_status" class="form-control"><option value=""><?=prod_h('common_all', 'All');?></option><option>CREATED</option><option>RELEASED</option><option>IN_PROCESS</option><option>CONFIRMED</option><option>TECO</option><option>CLOSED</option><option>CANCELLED</option></select></div><label class="control-label col-lg-1"><?=prod_h('production_plant', 'Plant');?></label><div class="col-lg-2"><select id="filter_plant" class="form-control"><option value=""><?=prod_h('common_all', 'All');?></option><?php foreach($plants as $p){ ?><option value="<?=htmlspecialchars($p->plant_code,ENT_QUOTES,'UTF-8');?>"><?=htmlspecialchars($p->plant_code,ENT_QUOTES,'UTF-8');?></option><?php } ?></select></div></div><div class="form-group"><label class="control-label col-lg-2">Exception</label><div class="col-lg-2"><select id="filter_exception" class="form-control"><option value=""><?=prod_h('common_all', 'All');?></option><option value="SHORTAGE">Material belum full issue</option><option value="NO_CONFIRMATION">Belum confirmation</option><option value="NO_GR">Belum GR produksi</option></select></div><label class="control-label col-lg-1"><?=prod_h('common_search', 'Search');?></label><div class="col-lg-4"><input id="filter_keyword" class="form-control" placeholder="PO, SO, material, BOM, routing"></div><div class="col-lg-3"><button id="btn_filter_pom" class="btn btn-primary"><i class="fa fa-filter"></i> <?=prod_h('common_filter', 'Filter');?></button> <button id="btn_reset_pom" class="btn btn-default"><i class="fa fa-refresh"></i> <?=prod_h('common_reset', 'Reset');?></button> <button id="btn_excel_pom" class="btn btn-success"><i class="fa fa-file-excel-o"></i> <?=prod_h('common_export_excel', 'Export Excel');?></button></div></div></form></div></div>
  <div class="box pom-card"><div class="box-body"><div class="alert alert-warning error_data_delete" style="display:none"><button type="button" class="close hide_alert_notif">&times;</button><span class="isi_warning_delete"></span></div><div class="table-responsive"><table id="dtb_production_order_monitoring" class="table table-bordered table-striped table-condensed" style="width:100%"><thead><tr><th><?=prod_h('common_no', 'No');?></th><th><?=prod_h('common_action', 'Action');?></th><th><?=prod_h('production_order', 'Production Order');?></th><th><?=prod_h('production_material', 'Material');?></th><th><?=prod_h('production_qty', 'Qty');?></th><th>Plant/SLoc</th><th>Basic Dates</th><th>Schedule</th><th>Progress</th><th>Documents</th><th>Exception</th><th><?=prod_h('common_status', 'Status');?></th></tr></thead><tbody></tbody></table></div></div></div>
  <div id="modal_detail_pom" class="modal fade"><div class="modal-dialog modal-lg" style="width:96%"><div class="modal-content"><div class="modal-header"><button class="close" data-dismiss="modal">&times;</button><h4 class="modal-title">Production Order Detail Monitoring</h4></div><div class="modal-body" id="pom_detail_body"></div><div class="modal-footer"><button class="btn btn-default" data-dismiss="modal"><?=prod_h('common_close', 'Close');?></button></div></div></div></div>
</section>
<script src="<?=base_admin();?>assets/plugins/select2/select2.min.js"></script>
<script>
function pomError(m){$('.isi_warning_delete').text(m||<?=prod_js('production_order_monitoring_process_failed', 'Production Order Monitoring failed to process.');?>);$('.error_data_delete').fadeIn();}
function pomFilters(){return{tgl_awal:$('#filter_tgl_awal').val(),tgl_akhir:$('#filter_tgl_akhir').val(),status:$('#filter_status').val(),plant:$('#filter_plant').val(),exception:$('#filter_exception').val(),keyword:$('#filter_keyword').val()};}
function pomQuery(){return $.param(pomFilters());}
$(function(){if($.fn.datepicker){$('.pom-date').datepicker({format:'yyyy-mm-dd',autoclose:true,todayHighlight:true});}if($.fn.select2){$('#filter_status,#filter_plant,#filter_exception').select2({width:'100%',allowClear:true});}
var dt=$('#dtb_production_order_monitoring').DataTable({bProcessing:true,bServerSide:true,pageLength:25,ordering:false,dom:"<'row'<'col-sm-12'B>>"+"<'row'<'col-sm-6'l><'col-sm-6'f>>"+"<'row'<'col-sm-12'tr>>"+"<'row'<'col-sm-5'i><'col-sm-7'p>>",buttons:[{extend:'collection',text:<?=prod_js('common_export_data', 'Export Data');?>,buttons:['copyHtml5','excelHtml5','csvHtml5','pdfHtml5']}],columnDefs:[{targets:[0,1],orderable:false,searchable:false},{width:'38px',targets:0},{width:'58px',targets:1},{className:'pom-progress',targets:8}],ajax:{url:'<?=base_admin();?>modul/production_order_monitoring/production_order_monitoring_data.php',type:'post',data:function(d){$.extend(d,pomFilters());},error:function(xhr){console.log(xhr.responseText);pomError(<?=prod_js('production_monitoring_load_failed', 'Monitoring data failed to load.');?>);}}});
$('#btn_filter_pom').click(function(){dt.draw();});$('#filter_keyword').keyup(function(e){if(e.keyCode===13)dt.draw();});$('#btn_reset_pom').click(function(){$('#filter_tgl_awal').val('<?=$defaultFrom;?>');$('#filter_tgl_akhir').val('<?=$defaultTo;?>');$('#filter_status,#filter_plant,#filter_exception').val('').trigger('change');$('#filter_keyword').val('');dt.draw();});$('#btn_excel_pom,#btn_excel_pom_top').click(function(){window.location='<?=base_admin();?>modul/production_order_monitoring/production_order_monitoring_action.php?act=excel&'+pomQuery();});
$(document).on('click','.btn-pom-detail',function(){$.post('<?=base_admin();?>modul/production_order_monitoring/production_order_monitoring_action.php?act=detail',{id:$(this).data('id')},function(html){$('#pom_detail_body').html(html);$('#modal_detail_pom').modal('show');}).fail(function(){pomError('Detail monitoring gagal dibuka.');});});$('.hide_alert_notif').click(function(){$('.error_data_delete').hide();});
});
</script>
