<?php
if (!function_exists('hr_t')) {
  function hr_t($key, $fallback = '') { return lang_text($key, $fallback); }
}
if (!function_exists('hr_h')) {
  function hr_h($key, $fallback = '') { return htmlspecialchars((string) hr_t($key, $fallback), ENT_QUOTES, 'UTF-8'); }
}
if (!function_exists('hr_js')) {
  function hr_js($key, $fallback = '') { return json_encode(hr_t($key, $fallback), JSON_HEX_TAG | JSON_HEX_APOS | JSON_HEX_AMP | JSON_HEX_QUOT); }
}
if (session_status() === PHP_SESSION_NONE) session_start();
include "../../inc/config.php";
session_check_json();
function phd_h($v){return htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');}
function phd_label($s,$type='history'){$map=array('ACTIVE'=>'success','ARCHIVED'=>'default','LOCKED'=>'primary','VOID'=>'danger','RELEASED'=>'success','GENERATED'=>'info','DRAFT'=>'default','READY'=>'warning','POSTED'=>'success','NOT_GENERATED'=>'default','NOT_CREATED'=>'default','CALCULATED'=>'info');$c=isset($map[$s])?$map[$s]:'default';return '<span class="label label-'.$c.'">'.phd_h($s).'</span>';}
$draw=isset($_POST['draw'])?(int)$_POST['draw']:1;$start=isset($_POST['start'])?max(0,(int)$_POST['start']):0;$length=isset($_POST['length'])?(int)$_POST['length']:25;if($length<=0||$length>500)$length=25;
$from=isset($_POST['tgl_awal'])&&$_POST['tgl_awal']!==''?$_POST['tgl_awal']:date('Y-m-01');$to=isset($_POST['tgl_akhir'])&&$_POST['tgl_akhir']!==''?$_POST['tgl_akhir']:date('Y-m-t');
$area=isset($_POST['payroll_area'])?trim($_POST['payroll_area']):'';$historyStatus=isset($_POST['history_status'])?trim($_POST['history_status']):'';$payslipStatus=isset($_POST['payslip_status'])?trim($_POST['payslip_status']):'';$postingStatus=isset($_POST['posting_status'])?trim($_POST['posting_status']):'';$emp=isset($_POST['employee_id'])?trim($_POST['employee_id']):'';$kw=isset($_POST['keyword'])?trim($_POST['keyword']):'';
$w=" WHERE ph.period_from<=? AND ph.period_to>=? ";$p=array($to,$from);if($area!==''){$w.=" AND ph.payroll_area=? ";$p[]=$area;}if($historyStatus!==''){$w.=" AND ph.history_status=? ";$p[]=$historyStatus;}if($payslipStatus!==''){$w.=" AND ph.payslip_status=? ";$p[]=$payslipStatus;}if($postingStatus!==''){$w.=" AND ph.posting_status=? ";$p[]=$postingStatus;}if($emp!==''){$w.=" AND ph.employee_id=? ";$p[]=(int)$emp;}if($kw!==''){$like='%'.$kw.'%';$w.=" AND (ph.history_no LIKE ? OR ph.payroll_run_no LIKE ? OR ph.payslip_no LIKE ? OR ph.posting_no LIKE ? OR ph.employee_no LIKE ? OR ph.full_name LIKE ? OR ph.sap_reference LIKE ?) ";array_push($p,$like,$like,$like,$like,$like,$like,$like);}
$kpi=$db->fetch("SELECT COUNT(*) total,SUM(history_status='ACTIVE') active_count,SUM(history_status='LOCKED') locked_count,SUM(payslip_status='RELEASED') released_count,SUM(posting_status IN ('READY','POSTED')) posting_ready,SUM(net_pay) net,SUM(gross_pay) gross FROM erp_payroll_history ph $w",$p);
$cnt=$db->fetch("SELECT COUNT(*) jml FROM erp_payroll_history ph $w",$p);$total=$cnt?(int)$cnt->jml:0;
$orderMap=array(2=>'ph.history_no',3=>'ph.payroll_run_no',4=>'ph.employee_no',5=>'ph.payroll_area',6=>'ph.net_pay',7=>'ph.history_status',8=>'ph.payslip_status',9=>'ph.posting_status',10=>'ph.updated_at');$orderBy='ph.period_year DESC,ph.period_month DESC,ph.employee_no';if(isset($_POST['order'][0]['column'])){$col=(int)$_POST['order'][0]['column'];$dir=(isset($_POST['order'][0]['dir'])&&strtolower($_POST['order'][0]['dir'])==='desc')?'DESC':'ASC';if(isset($orderMap[$col]))$orderBy=$orderMap[$col].' '.$dir;}
$rows=$db->query("SELECT ph.*,d.nm_dept FROM erp_payroll_history ph LEFT JOIN dept d ON d.kd_dept=ph.department_code $w ORDER BY $orderBy LIMIT $start,$length",$p);
$data=array();$no=$start+1;foreach($rows as $r){$locked=$r->history_status==='LOCKED';$act='<div class="ph-action"><button class="btn btn-info btn-xs btn-ph-detail" data-id="'.(int)$r->id.'" title="'.hr_h('common_detail', 'Detail').'"><i class="fa fa-eye"></i></button> <button class="btn btn-primary btn-xs btn-ph-edit" data-id="'.(int)$r->id.'" title="'.hr_h('common_edit', 'Edit').'"'.($locked?' disabled':'').'><i class="fa fa-pencil"></i></button> <button class="btn btn-warning btn-xs btn-ph-lock" data-id="'.(int)$r->id.'" title="Lock"><i class="fa fa-lock"></i></button> <button class="btn btn-default btn-xs btn-ph-archive" data-id="'.(int)$r->id.'" title="Archive"'.($locked?' disabled':'').'><i class="fa fa-archive"></i></button> <button class="btn btn-danger btn-xs btn-ph-delete" data-id="'.(int)$r->id.'" data-no="'.phd_h($r->history_no).'" title="'.hr_h('common_delete', 'Delete').'"'.($locked?' disabled':'').'><i class="fa fa-trash"></i></button></div>';
  $data[]=array($no++,$act,'<strong>'.phd_h($r->history_no).'</strong><br><small>'.phd_h($r->sap_reference).'</small>','<strong>'.phd_h($r->payroll_run_no).'</strong><br><small>'.phd_h($r->period_from.' s/d '.$r->period_to).'</small>','<strong>'.phd_h($r->employee_no).'</strong><br><small>'.phd_h($r->full_name).'</small>','<strong>'.phd_h($r->payroll_area).'</strong><br><small>'.phd_h($r->department_code.' - '.$r->nm_dept).'</small>','Gross '.number_format((float)$r->gross_pay,0).'<br><small>Net <b>'.number_format((float)$r->net_pay,0).'</b></small>',phd_label($r->history_status),phd_label($r->payslip_status),phd_label($r->posting_status).'<br><small>'.phd_h($r->posting_no?:'-').'</small>',phd_h($r->updated_by?:$r->created_by?:'-').'<br><small>'.phd_h($r->updated_at?:$r->created_at).'</small>');}
header('Content-Type: application/json; charset=utf-8');echo json_encode(array('draw'=>$draw,'recordsTotal'=>$total,'recordsFiltered'=>$total,'data'=>$data,'kpi'=>array('total'=>$kpi?(int)$kpi->total:0,'active'=>$kpi?(int)$kpi->active_count:0,'locked'=>$kpi?(int)$kpi->locked_count:0,'released'=>$kpi?(int)$kpi->released_count:0,'posting_ready'=>$kpi?(int)$kpi->posting_ready:0,'net'=>$kpi?(float)$kpi->net:0,'gross'=>$kpi?(float)$kpi->gross:0)));
?>
