<?php
if (!function_exists('hr_t')) {
  function hr_t($key, $fallback = '') { return lang_text($key, $fallback); }
}
if (!function_exists('hr_h')) {
  function hr_h($key, $fallback = '') { return htmlspecialchars((string) hr_t($key, $fallback), ENT_QUOTES, 'UTF-8'); }
}
if (!function_exists('hr_js')) {
  function hr_js($key, $fallback = '') { return json_encode(hr_t($key, $fallback), JSON_HEX_TAG | JSON_HEX_APOS | JSON_HEX_AMP | JSON_HEX_QUOT); }
}
$defaultFrom=date('Y-m-01');$defaultTo=date('Y-m-t');$canInsert=isset($role_act['insert_act'])&&$role_act['insert_act']==='Y'; ?>
<style>
.ph-hero{background:linear-gradient(135deg,#0f766e,#1d4ed8);color:#fff;border-radius:14px;padding:20px;margin-bottom:18px;box-shadow:0 10px 24px rgba(15,23,42,.16)}.ph-hero h1{margin:0 0 6px;font-size:26px;font-weight:700}.ph-card{border-radius:12px;background:#fff;border:1px solid #e5edf5;box-shadow:0 5px 16px rgba(15,23,42,.05);margin-bottom:14px}.ph-kpi{padding:14px;border-radius:12px;background:#eef6ff;border:1px solid #bfdbfe}.ph-kpi b{font-size:22px;display:block}#dtb_payroll_history th,#dtb_payroll_history td{font-size:12px;vertical-align:middle}.select2-container{width:100%!important}.required-label:after{content:' *';color:#dd4b39}.ph-action{white-space:nowrap}#modal_payroll_history .modal-body,#modal_ph_detail .modal-body{max-height:calc(100vh - 185px);overflow-y:auto}.ph-hint{background:#ecfeff;border:1px solid #67e8f9;border-radius:10px;padding:10px;margin-bottom:10px}.ph-section-title{font-weight:700;color:#334155;margin:8px 0 12px;border-bottom:1px solid #e5e7eb;padding-bottom:7px}.ph-detail{background:#fff;border:1px solid #e5e7eb;border-radius:12px;padding:18px}.ph-toolbar .btn{margin-left:4px}
</style>
<section class="content-header"><h1><?=hr_h('hr_payroll_history', 'Payroll History');?> <small>SAP HR Payroll Archive</small></h1><ol class="breadcrumb"><li><a href="<?=base_index();?>"><i class="fa fa-dashboard"></i> <?=hr_h('common_home', 'Home');?></a></li><li>Human Resource</li><li>Payroll</li><li class="active"><?=hr_h('hr_payroll_history', 'Payroll History');?></li></ol></section>
<section class="content">
<div class="ph-hero"><div class="row"><div class="col-md-8"><h1>Payroll History & Audit Cockpit</h1><p>Arsip payroll per periode dan employee, mengikat payroll result, payslip, posting, journal reference, dan wage type snapshot untuk kebutuhan audit SAP-style.</p></div><div class="col-md-4 text-right ph-toolbar"><?php if($canInsert){ ?><button id="btn_open_ph" class="btn btn-warning"><i class="fa fa-plus"></i> Create Snapshot</button><?php } ?><button id="btn_export_ph" class="btn btn-success"><i class="fa fa-file-excel-o"></i> <?=hr_h('common_export_excel', 'Export Excel');?></button></div></div></div>
<div class="row"><div class="col-sm-2"><div class="ph-kpi"><span>Total</span><b id="kpi_total">0</b></div></div><div class="col-sm-2"><div class="ph-kpi"><span><?=hr_h('hr_active', 'Active');?></span><b id="kpi_active">0</b></div></div><div class="col-sm-2"><div class="ph-kpi"><span>Locked</span><b id="kpi_locked">0</b></div></div><div class="col-sm-2"><div class="ph-kpi"><span>Released Slip</span><b id="kpi_released">0</b></div></div><div class="col-sm-2"><div class="ph-kpi"><span>Posting Ready</span><b id="kpi_posting">0</b></div></div><div class="col-sm-2"><div class="ph-kpi"><span><?=hr_h('hr_net_pay', 'Net Pay');?></span><b id="kpi_net">0</b></div></div></div>
<div class="box ph-card"><div class="box-header"><h3 class="box-title"><i class="fa fa-filter"></i> Filter Payroll History</h3></div><div class="box-body"><form class="form-horizontal" onsubmit="return false;"><div class="form-group"><label class="control-label col-lg-2"><?=hr_h('hr_period', 'Period');?></label><div class="col-lg-2"><div class="input-group date ph-date"><input id="filter_tgl_awal" class="form-control" value="<?=$defaultFrom;?>"><span class="input-group-addon"><span class="glyphicon glyphicon-calendar"></span></span></div></div><div class="col-lg-2"><div class="input-group date ph-date"><input id="filter_tgl_akhir" class="form-control" value="<?=$defaultTo;?>"><span class="input-group-addon"><span class="glyphicon glyphicon-calendar"></span></span></div></div><label class="control-label col-lg-1">Area</label><div class="col-lg-2"><select id="filter_payroll_area" class="form-control"><option value="">All</option><option>MONTHLY</option><option>DAILY</option><option>WEEKLY</option><option>CONTRACT</option><option>MANAGEMENT</option><option>ALL</option></select></div><label class="control-label col-lg-1">History</label><div class="col-lg-2"><select id="filter_history_status" class="form-control"><option value="">All</option><option>ACTIVE</option><option>ARCHIVED</option><option>LOCKED</option><option>VOID</option></select></div></div><div class="form-group"><label class="control-label col-lg-2"><?=hr_h('hr_payslip', 'Payslip');?></label><div class="col-lg-2"><select id="filter_payslip_status" class="form-control"><option value="">All</option><option>DRAFT</option><option>GENERATED</option><option>RELEASED</option><option>VOID</option><option>NOT_GENERATED</option></select></div><label class="control-label col-lg-1">Posting</label><div class="col-lg-2"><select id="filter_posting_status" class="form-control"><option value="">All</option><option>DRAFT</option><option>READY</option><option>POSTED</option><option>REVERSED</option><option>CANCELLED</option><option>NOT_CREATED</option></select></div><label class="control-label col-lg-1"><?=hr_h('hr_employee', 'Employee');?></label><div class="col-lg-2"><select id="filter_employee_id" class="form-control"></select></div><div class="col-lg-2"><input id="filter_keyword" class="form-control" placeholder="History, run, employee"></div></div><div class="form-group"><div class="col-lg-10 col-lg-offset-2"><button id="btn_filter_ph" class="btn btn-primary"><i class="fa fa-filter"></i> <?=hr_h('common_filter', 'Filter');?></button> <button id="btn_reset_ph" class="btn btn-default"><i class="fa fa-refresh"></i> <?=hr_h('common_reset', 'Reset');?></button></div></div></form></div></div>
<div class="box ph-card"><div class="box-body"><div class="alert alert-warning error_data_delete" style="display:none"><button type="button" class="close hide_alert_notif">&times;</button><span class="isi_warning_delete"></span></div><div class="table-responsive"><table id="dtb_payroll_history" class="table table-bordered table-striped" style="width:100%"><thead><tr><th><?=hr_h('common_no', 'No');?></th><th><?=hr_h('common_action', 'Action');?></th><th>History</th><th>Payroll Run</th><th><?=hr_h('hr_employee', 'Employee');?></th><th>Area</th><th>Amount</th><th>History</th><th><?=hr_h('hr_payslip', 'Payslip');?></th><th>Posting</th><th>Updated</th></tr></thead><tbody></tbody></table></div></div></div>
<div id="modal_payroll_history" class="modal fade"><div class="modal-dialog modal-lg" style="width:88%"><div class="modal-content"><form id="form_payroll_history"><input type="hidden" name="id" id="ph_id"><div class="modal-header"><button type="button" class="close" data-dismiss="modal">&times;</button><h4 class="modal-title" id="ph_modal_title">Create Payroll History Snapshot</h4></div><div class="modal-body"><div class="ph-hint"><strong>SAP hint:</strong> Payroll History sebaiknya menjadi arsip audit. Angka payroll diambil dari payroll result/payslip/posting, sedangkan edit hanya untuk status arsip, source, dan remarks.</div><div class="ph-section-title">Snapshot Source</div><div class="row"><div class="col-md-6 form-group"><label class="required-label">Payroll Result Employee</label><select name="payroll_employee_id" id="payroll_employee_id" class="form-control"></select></div><div class="col-md-2 form-group"><label><?=hr_h('common_status', 'Status');?></label><select name="history_status" id="history_status" class="form-control"><option>ACTIVE</option><option>ARCHIVED</option><option>LOCKED</option><option>VOID</option></select></div><div class="col-md-3 form-group"><label>Audit Source</label><select name="audit_source" id="audit_source" class="form-control"><option>AUTO_SNAPSHOT</option><option>MANUAL_ADJUSTMENT</option><option>IMPORT</option></select></div></div><div class="row"><div class="col-md-12 form-group"><label><?=hr_h('common_remarks', 'Remarks');?></label><textarea name="remarks" id="remarks" class="form-control" rows="3" placeholder="Catatan audit payroll history"></textarea></div></div></div><div class="modal-footer"><button type="button" class="btn btn-default" data-dismiss="modal"><?=hr_h('common_cancel', 'Cancel');?></button><button type="submit" class="btn btn-primary"><i class="fa fa-save"></i> Save Snapshot</button></div></form></div></div></div>
<div id="modal_ph_detail" class="modal fade"><div class="modal-dialog modal-lg" style="width:94%"><div class="modal-content"><div class="modal-header"><button class="close" data-dismiss="modal">&times;</button><h4 class="modal-title">Payroll History Detail</h4></div><div class="modal-body" id="ph_detail_body"></div><div class="modal-footer"><button class="btn btn-default" data-dismiss="modal"><?=hr_h('common_close', 'Close');?></button></div></div></div></div>
</section>
<script src="<?=base_admin();?>assets/plugins/select2/select2.min.js"></script><script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
<script>
function phError(m){$('.isi_warning_delete').text(m||'Payroll History gagal diproses.');$('.error_data_delete').fadeIn();}
function phMoney(v){return (parseFloat(v||0)||0).toLocaleString('id-ID');}
function phFilters(){return{tgl_awal:$('#filter_tgl_awal').val(),tgl_akhir:$('#filter_tgl_akhir').val(),payroll_area:$('#filter_payroll_area').val(),history_status:$('#filter_history_status').val(),payslip_status:$('#filter_payslip_status').val(),posting_status:$('#filter_posting_status').val(),employee_id:$('#filter_employee_id').val(),keyword:$('#filter_keyword').val()};}
function phAjax(s,act,p,parent){$(s).select2({width:'100%',allowClear:true,placeholder:p,dropdownParent:parent||$(document.body),ajax:{url:'<?=base_admin();?>modul/payroll_history/payroll_history_action.php?act='+act,type:'POST',dataType:'json',delay:250,data:function(q){return{term:q.term||''};},processResults:function(d){return{results:d.results||[]};}}});}
function phReset(){$('#form_payroll_history')[0].reset();$('#ph_id').val('');$('#payroll_employee_id').prop('disabled',false).val(null).trigger('change');$('#history_status').val('ACTIVE').trigger('change');$('#audit_source').val('AUTO_SNAPSHOT').trigger('change');$('#ph_modal_title').text('Create Payroll History Snapshot');}
$(function(){if($.fn.datepicker){$('.ph-date').datepicker({format:'yyyy-mm-dd',autoclose:true,todayHighlight:true});}if($.fn.select2){$('#filter_payroll_area,#filter_history_status,#filter_payslip_status,#filter_posting_status,#history_status,#audit_source').select2({width:'100%',allowClear:true});phAjax('#filter_employee_id','employee_search','Pilih Employee');phAjax('#payroll_employee_id','payroll_employee_search','Pilih Payroll Result',$('#modal_payroll_history'));}
var dt=$('#dtb_payroll_history').DataTable({bProcessing:true,bServerSide:true,pageLength:25,dom:"<'row'<'col-sm-12'B>>"+"<'row'<'col-sm-6'l><'col-sm-6'f>>"+"<'row'<'col-sm-12'tr>>"+"<'row'<'col-sm-5'i><'col-sm-7'p>>",buttons:[{extend:'collection',text:<?=hr_js('common_export_data', 'Export Data');?>,buttons:['copyHtml5','excelHtml5','csvHtml5','pdfHtml5']}],columnDefs:[{targets:[0,1],orderable:false,searchable:false},{width:'42px',targets:0},{width:'180px',targets:1}],ajax:{url:'<?=base_admin();?>modul/payroll_history/payroll_history_data.php',type:'post',data:function(d){$.extend(d,phFilters());},dataSrc:function(j){var k=j.kpi||{};$('#kpi_total').text(k.total||0);$('#kpi_active').text(k.active||0);$('#kpi_locked').text(k.locked||0);$('#kpi_released').text(k.released||0);$('#kpi_posting').text(k.posting_ready||0);$('#kpi_net').text(phMoney(k.net));return j.data||[];},error:function(x){console.log(x.responseText);phError('Data Payroll History gagal dimuat.');}}});
$('#btn_open_ph').click(function(){phReset();$('#modal_payroll_history').modal({backdrop:'static',keyboard:false});});$('#btn_filter_ph').click(function(){dt.draw();});$('#filter_keyword').keyup(function(e){if(e.keyCode===13)dt.draw();});$('#btn_reset_ph').click(function(){$('#filter_tgl_awal').val('<?=$defaultFrom;?>');$('#filter_tgl_akhir').val('<?=$defaultTo;?>');$('#filter_payroll_area,#filter_history_status,#filter_payslip_status,#filter_posting_status,#filter_employee_id').val(null).trigger('change');$('#filter_keyword').val('');dt.draw();});$('#btn_export_ph').click(function(){window.location='<?=base_admin();?>modul/payroll_history/payroll_history_action.php?act=export&'+$.param(phFilters());});$('.hide_alert_notif').click(function(){$('.error_data_delete').hide();});
$('#form_payroll_history').submit(function(e){e.preventDefault();var edit=$('#ph_id').val()!=='';if(!edit&&!$('#payroll_employee_id').val()){phError('Payroll Result Employee wajib dipilih.');return;}var b=$(this).find('button[type=submit]');b.prop('disabled',true).html('<i class="fa fa-spinner fa-spin"></i> <?=hr_h('common_saving', 'Saving...');?>');$.post('<?=base_admin();?>modul/payroll_history/payroll_history_action.php?act='+(edit?'update':'save'),$(this).serialize(),function(r){b.prop('disabled',false).html('<i class="fa fa-save"></i> Save Snapshot');if(r.status==='good'){$('#modal_payroll_history').modal('hide');dt.draw(false);Swal.fire('Saved','Payroll History berhasil disimpan.','success');}else phError(r.error_message);},'json').fail(function(x){b.prop('disabled',false).html('<i class="fa fa-save"></i> Save Snapshot');phError(x.responseText);});});
$(document).on('click','.btn-ph-detail',function(){$.post('<?=base_admin();?>modul/payroll_history/payroll_history_action.php?act=detail',{id:$(this).data('id')},function(h){$('#ph_detail_body').html(h);$('#modal_ph_detail').modal('show');});});
$(document).on('click','.btn-ph-edit',function(){if($(this).is(':disabled'))return;phReset();$.post('<?=base_admin();?>modul/payroll_history/payroll_history_action.php?act=get',{id:$(this).data('id')},function(r){if(r.status!=='good'){phError(r.error_message);return;}var d=r.data;$('#ph_id').val(d.id);$('#payroll_employee_id').prop('disabled',true).append(new Option(d.payroll_run_no+' - '+d.employee_no+' '+d.full_name,d.payroll_employee_id,true,true)).trigger('change');$('#history_status').val(d.history_status).trigger('change');$('#audit_source').val(d.audit_source).trigger('change');$('#remarks').val(d.remarks);$('#ph_modal_title').text('Edit Payroll History');$('#modal_payroll_history').modal({backdrop:'static',keyboard:false});},'json');});
function phSetStatus(id,status,label){$.post('<?=base_admin();?>modul/payroll_history/payroll_history_action.php?act=status',{id:id,status:status},function(r){if(r.status==='good'){dt.draw(false);Swal.fire(label,'Payroll History berhasil diubah.','success');}else phError(r.error_message);},'json');}
$(document).on('click','.btn-ph-lock',function(){phSetStatus($(this).data('id'),'LOCKED','Locked');});
$(document).on('click','.btn-ph-archive',function(){if($(this).is(':disabled'))return;phSetStatus($(this).data('id'),'ARCHIVED','Archived');});
$(document).on('click','.btn-ph-delete',function(){if($(this).is(':disabled'))return;var id=$(this).data('id'),no=$(this).data('no');Swal.fire({title:erpLang('confirm_delete_title','Delete Confirmation'),text:no,icon:'warning',showCancelButton:true,confirmButtonText:erpLang('common_delete','Delete'),cancelButtonText:erpLang('common_cancel','Cancel')}).then(function(x){if(!x.isConfirmed)return;$.post('<?=base_admin();?>modul/payroll_history/payroll_history_action.php?act=delete',{id:id},function(r){if(r.status==='good'){dt.draw(false);Swal.fire(erpLang('common_deleted','Deleted'),erpLang('common_deleted_message','Data deleted successfully.'),'success');}else phError(r.error_message);},'json');});});
});
</script>
