<?php
if (!function_exists('hr_t')) {
  function hr_t($key, $fallback = '') { return lang_text($key, $fallback); }
}
if (!function_exists('hr_h')) {
  function hr_h($key, $fallback = '') { return htmlspecialchars((string) hr_t($key, $fallback), ENT_QUOTES, 'UTF-8'); }
}
if (!function_exists('hr_js')) {
  function hr_js($key, $fallback = '') { return json_encode(hr_t($key, $fallback), JSON_HEX_TAG | JSON_HEX_APOS | JSON_HEX_AMP | JSON_HEX_QUOT); }
}
if (session_status() === PHP_SESSION_NONE) session_start();
include "../../inc/config.php";
session_check_json();
function atd_h($v){return htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');}
function atd_label($s){$map=array('DRAFT'=>'warning','RECORDED'=>'info','APPROVED'=>'success','POSTED'=>'primary','REJECTED'=>'danger','CANCELLED'=>'default');$c=isset($map[$s])?$map[$s]:'default';return '<span class="label label-'.$c.'">'.atd_h($s).'</span>';}
$draw=isset($_POST['draw'])?(int)$_POST['draw']:1;$start=isset($_POST['start'])?max(0,(int)$_POST['start']):0;$length=isset($_POST['length'])?(int)$_POST['length']:25;if($length<=0||$length>500)$length=25;
$from=isset($_POST['tgl_awal'])&&$_POST['tgl_awal']!==''?$_POST['tgl_awal']:date('Y-m-01');$to=isset($_POST['tgl_akhir'])&&$_POST['tgl_akhir']!==''?$_POST['tgl_akhir']:date('Y-m-t');$emp=isset($_POST['employee_id'])?trim($_POST['employee_id']):'';$dept=isset($_POST['department_code'])?trim($_POST['department_code']):'';$type=isset($_POST['attendance_type'])?trim($_POST['attendance_type']):'';$status=isset($_POST['attendance_status'])?trim($_POST['attendance_status']):'';$source=isset($_POST['attendance_source'])?trim($_POST['attendance_source']):'';$kw=isset($_POST['keyword'])?trim($_POST['keyword']):'';
$w=" WHERE a.attendance_date BETWEEN ? AND ? ";$p=array($from,$to);if($emp!==''){$w.=" AND a.employee_id=? ";$p[]=(int)$emp;}if($dept!==''){$w.=" AND a.department_code=? ";$p[]=$dept;}if($type!==''){$w.=" AND a.attendance_type=? ";$p[]=$type;}if($status!==''){$w.=" AND a.attendance_status=? ";$p[]=$status;}if($source!==''){$w.=" AND a.attendance_source=? ";$p[]=$source;}if($kw!==''){$like='%'.$kw.'%';$w.=" AND (a.attendance_no LIKE ? OR a.employee_no LIKE ? OR e.full_name LIKE ? OR a.sap_reference LIKE ? OR a.remarks LIKE ?) ";array_push($p,$like,$like,$like,$like,$like);}
$kpi=$db->fetch("SELECT COUNT(*) total,SUM(attendance_status='POSTED') posted,SUM(late_minutes>0) late_count,SUM(early_leave_minutes>0) early_count,SUM(attendance_type IN ('ABSENT','SICK','LEAVE')) absence_count,ROUND(SUM(overtime_hours),2) overtime_hours FROM erp_attendance");
$cnt=$db->fetch("SELECT COUNT(*) jml FROM erp_attendance a JOIN erp_employee_master e ON e.id=a.employee_id $w",$p);$total=$cnt?(int)$cnt->jml:0;
$orderMap=array(2=>'a.attendance_no',3=>'a.attendance_date',4=>'e.employee_no',5=>'a.department_code',6=>'a.shift_code',7=>'a.actual_clock_in',8=>'a.attendance_type',9=>'a.attendance_status',10=>'a.updated_at');$orderBy='a.attendance_date DESC,a.attendance_no';if(isset($_POST['order'][0]['column'])){$col=(int)$_POST['order'][0]['column'];$dir=(isset($_POST['order'][0]['dir'])&&strtolower($_POST['order'][0]['dir'])==='desc')?'DESC':'ASC';if(isset($orderMap[$col]))$orderBy=$orderMap[$col].' '.$dir;}
$rows=$db->query("SELECT a.*,e.full_name,e.employee_group,d.nm_dept,wl.location_code,wl.location_name,s.nama_shift FROM erp_attendance a JOIN erp_employee_master e ON e.id=a.employee_id LEFT JOIN dept d ON d.kd_dept=a.department_code LEFT JOIN erp_work_location wl ON wl.id=a.work_location_id LEFT JOIN erp_shift s ON s.id=a.shift_id $w ORDER BY $orderBy LIMIT $start,$length",$p);
$data=array();$no=$start+1;foreach($rows as $r){$canDel=$r->attendance_status==='POSTED'?' disabled':'';$act='<div class="at-action"><button class="btn btn-info btn-xs btn-at-detail" data-id="'.(int)$r->id.'" title="'.hr_h('common_detail', 'Detail').'"><i class="fa fa-eye"></i></button> <button class="btn btn-primary btn-xs btn-at-edit" data-id="'.(int)$r->id.'" title="'.hr_h('common_edit', 'Edit').'"><i class="fa fa-pencil"></i></button> <button class="btn btn-success btn-xs btn-at-status" data-id="'.(int)$r->id.'" data-status="APPROVED" title="'.hr_h('common_approve', 'Approve').'"><i class="fa fa-check"></i></button> <button class="btn btn-primary btn-xs btn-at-status" data-id="'.(int)$r->id.'" data-status="POSTED" title="Post"><i class="fa fa-upload"></i></button> <button class="btn btn-warning btn-xs btn-at-status" data-id="'.(int)$r->id.'" data-status="CANCELLED" title="'.hr_h('common_cancel', 'Cancel').'"><i class="fa fa-ban"></i></button> <button class="btn btn-danger btn-xs btn-at-delete" data-id="'.(int)$r->id.'" data-no="'.atd_h($r->attendance_no).'" title="'.hr_h('common_delete', 'Delete').'"'.$canDel.'><i class="fa fa-trash"></i></button></div>';
  $data[]=array($no++,$act,'<strong>'.atd_h($r->attendance_no).'</strong><br><small>'.atd_h($r->attendance_date).'</small>','<strong>'.atd_h($r->employee_no).'</strong><br><small>'.atd_h($r->full_name).'</small><br><small>'.atd_h($r->employee_group).'</small>','<strong>'.atd_h($r->department_code?:'-').'</strong><br><small>'.atd_h($r->nm_dept?:'-').'</small>','<strong>'.atd_h(($r->shift_code?:'-').' '.$r->nama_shift).'</strong><br><small>'.atd_h($r->assignment_no?:'-').'</small>','Plan: '.atd_h($r->planned_start?substr($r->planned_start,11,5):'-').' - '.atd_h($r->planned_end?substr($r->planned_end,11,5):'-').'<br><small>Actual: '.atd_h($r->actual_clock_in?substr($r->actual_clock_in,11,5):'-').' - '.atd_h($r->actual_clock_out?substr($r->actual_clock_out,11,5):'-').'</small>','<strong>'.atd_h($r->actual_hours).'</strong> h<br><small>Late '.atd_h($r->late_minutes).'m | Early '.atd_h($r->early_leave_minutes).'m | OT '.atd_h($r->overtime_hours).'h</small>','<strong>'.atd_h($r->attendance_type).'</strong><br><small>'.atd_h($r->attendance_source).'</small>',atd_label($r->attendance_status),atd_h($r->updated_by?:$r->created_by?:'-').'<br><small>'.atd_h($r->updated_at?:$r->created_at).'</small>');}
header('Content-Type: application/json; charset=utf-8');echo json_encode(array('draw'=>$draw,'recordsTotal'=>$total,'recordsFiltered'=>$total,'data'=>$data,'kpi'=>array('total'=>$kpi?(int)$kpi->total:0,'posted'=>$kpi?(int)$kpi->posted:0,'late_count'=>$kpi?(int)$kpi->late_count:0,'early_count'=>$kpi?(int)$kpi->early_count:0,'absence_count'=>$kpi?(int)$kpi->absence_count:0,'overtime_hours'=>$kpi?$kpi->overtime_hours:0)));
?>
