<?php
if (!function_exists('hr_t')) {
  function hr_t($key, $fallback = '') { return lang_text($key, $fallback); }
}
if (!function_exists('hr_h')) {
  function hr_h($key, $fallback = '') { return htmlspecialchars((string) hr_t($key, $fallback), ENT_QUOTES, 'UTF-8'); }
}
if (!function_exists('hr_js')) {
  function hr_js($key, $fallback = '') { return json_encode(hr_t($key, $fallback), JSON_HEX_TAG | JSON_HEX_APOS | JSON_HEX_AMP | JSON_HEX_QUOT); }
}
if (session_status() === PHP_SESSION_NONE) session_start();
include "../../inc/config.php";
session_check_json();
function lrep_h($v){return htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');}
function lrep_label($s){$m=array('DRAFT'=>'warning','SUBMITTED'=>'info','MANAGER_APPROVED'=>'primary','HR_APPROVED'=>'primary','APPROVED'=>'success','REJECTED'=>'danger','RETURNED'=>'warning','CANCELLED'=>'default');$c=isset($m[$s])?$m[$s]:'default';return '<span class="label label-'.$c.'">'.lrep_h($s).'</span>';}
function lrep_filters(){return array('from'=>isset($_POST['tgl_awal'])&&$_POST['tgl_awal']!==''?$_POST['tgl_awal']:date('Y-m-01'),'to'=>isset($_POST['tgl_akhir'])&&$_POST['tgl_akhir']!==''?$_POST['tgl_akhir']:date('Y-m-t'),'employee_id'=>isset($_POST['employee_id'])?trim($_POST['employee_id']):'','department_code'=>isset($_POST['department_code'])?trim($_POST['department_code']):'','job_title_id'=>isset($_POST['job_title_id'])?trim($_POST['job_title_id']):'','leave_type'=>isset($_POST['leave_type'])?trim($_POST['leave_type']):'','workflow_status'=>isset($_POST['workflow_status'])?trim($_POST['workflow_status']):'','decision'=>isset($_POST['decision'])?trim($_POST['decision']):'','approval_level'=>isset($_POST['approval_level'])?trim($_POST['approval_level']):'','impact_type'=>isset($_POST['impact_type'])?trim($_POST['impact_type']):'','keyword'=>isset($_POST['keyword'])?trim($_POST['keyword']):'');}
function lrep_where($f,&$p){$w=" WHERE l.start_date<=? AND l.end_date>=? ";array_push($p,$f['to'],$f['from']);if($f['employee_id']!==''){$w.=" AND l.employee_id=? ";$p[]=(int)$f['employee_id'];}if($f['job_title_id']!==''){$w.=" AND l.job_title_id=? ";$p[]=(int)$f['job_title_id'];}foreach(array('department_code','leave_type','workflow_status','decision','approval_level') as $k){if($f[$k]!==''){$w.=" AND l.$k=? ";$p[]=$f[$k];}}if($f['impact_type']==='QUOTA_DEDUCT')$w.=" AND l.leave_quota_before>l.leave_quota_after ";elseif($f['impact_type']==='PENDING_APPROVAL')$w.=" AND l.workflow_status IN ('SUBMITTED','MANAGER_APPROVED','HR_APPROVED') ";elseif($f['impact_type']==='APPROVED_USAGE')$w.=" AND l.workflow_status='APPROVED' ";elseif($f['impact_type']==='EXCEPTION')$w.=" AND l.workflow_status IN ('REJECTED','RETURNED','CANCELLED') ";elseif($f['impact_type']==='ATTACHMENT')$w.=" AND l.attachment_ref IS NOT NULL AND l.attachment_ref<>'' ";if($f['keyword']!==''){$kw='%'.$f['keyword'].'%';$w.=" AND (l.leave_no LIKE ? OR e.employee_no LIKE ? OR e.full_name LIKE ? OR l.reason LIKE ? OR l.sap_reference LIKE ? OR d.nm_dept LIKE ?) ";for($i=0;$i<6;$i++)$p[]=$kw;}return $w;}
$draw=isset($_POST['draw'])?(int)$_POST['draw']:1;$start=isset($_POST['start'])?max(0,(int)$_POST['start']):0;$length=isset($_POST['length'])?(int)$_POST['length']:25;if($length<=0||$length>500)$length=25;
$f=lrep_filters();$p=array();$w=lrep_where($f,$p);
$base=" FROM erp_leave_request l JOIN erp_employee_master e ON e.id=l.employee_id LEFT JOIN dept d ON d.kd_dept=l.department_code LEFT JOIN erp_job_title j ON j.id=l.job_title_id LEFT JOIN erp_employee_master app ON app.id=l.approver_employee_id LEFT JOIN erp_employee_master hr ON hr.id=l.hr_reviewer_employee_id LEFT JOIN erp_employee_master hand ON hand.id=l.handover_to_employee_id ";
$kpi=$db->fetch("SELECT COUNT(*) total,SUM(l.workflow_status IN ('SUBMITTED','MANAGER_APPROVED','HR_APPROVED')) pending_count,SUM(l.workflow_status='APPROVED') approved_count,SUM(l.workflow_status IN ('REJECTED','RETURNED','CANCELLED')) exception_count,ROUND(SUM(l.total_days),2) requested_days,ROUND(SUM(CASE WHEN l.workflow_status='APPROVED' THEN l.total_days ELSE 0 END),2) approved_days,ROUND(SUM(l.leave_quota_before-l.leave_quota_after),2) quota_deducted $base $w",$p);
$cnt=$db->fetch("SELECT COUNT(*) jml $base $w",$p);$total=$cnt?(int)$cnt->jml:0;
$orderMap=array(2=>'l.leave_no',3=>'l.request_date',4=>'e.employee_no',5=>'d.kd_dept',6=>'l.leave_type',7=>'l.start_date',8=>'l.total_days',9=>'l.leave_quota_after',10=>'l.workflow_status',11=>'l.updated_at');$orderBy='l.start_date DESC,l.leave_no DESC';
if(isset($_POST['order'][0]['column'])){$col=(int)$_POST['order'][0]['column'];$dir=(isset($_POST['order'][0]['dir'])&&strtolower($_POST['order'][0]['dir'])==='desc')?'DESC':'ASC';if(isset($orderMap[$col]))$orderBy=$orderMap[$col].' '.$dir;}
$rows=$db->query("SELECT l.*,e.employee_no,e.full_name,e.employee_group,d.nm_dept,j.job_title_code,j.job_title_name,app.employee_no approver_no,app.full_name approver_name,hr.employee_no hr_no,hr.full_name hr_name,hand.employee_no handover_no,hand.full_name handover_name,(SELECT COUNT(*) FROM erp_leave_approval la WHERE la.leave_request_id=l.id) approval_count $base $w ORDER BY $orderBy LIMIT $start,$length",$p);
$data=array();$no=$start+1;foreach($rows as $r){$quotaUsed=(float)$r->leave_quota_before-(float)$r->leave_quota_after;$data[]=array($no++,'<button class="btn btn-info btn-xs btn-lrep-detail" data-id="'.(int)$r->id.'"><i class="fa fa-eye"></i></button>','<strong>'.lrep_h($r->leave_no).'</strong><br><small>'.lrep_h($r->sap_reference?:'-').'</small>',lrep_h($r->request_date),'<strong>'.lrep_h($r->employee_no).'</strong><br><small>'.lrep_h($r->full_name).' / '.lrep_h($r->employee_group).'</small>','<strong>'.lrep_h($r->department_code?:'-').'</strong><br><small>'.lrep_h($r->nm_dept?:'-').'</small>','<strong>'.lrep_h($r->leave_type).'</strong><br><small>'.lrep_h($r->job_title_code?:'-').'</small>',lrep_h($r->start_date.' s/d '.$r->end_date).'<br><small>'.lrep_h($r->start_half_day.' / '.$r->end_half_day).'</small>','<strong>'.number_format((float)$r->total_days,2).'</strong><br><small>Quota use '.number_format($quotaUsed,2).'</small>','Before '.number_format((float)$r->leave_quota_before,2).'<br><small>After '.number_format((float)$r->leave_quota_after,2).'</small>',lrep_label($r->workflow_status).'<br><small>'.lrep_h($r->approval_level.' / '.$r->decision).'</small>',lrep_h($r->approver_no?($r->approver_no.' - '.$r->approver_name):'-').'<br><small>HR '.lrep_h($r->hr_no?($r->hr_no.' - '.$r->hr_name):'-').'</small>',lrep_h($r->updated_by?:$r->created_by?:'-').'<br><small>'.lrep_h($r->updated_at?:$r->created_at).'</small>');}
header('Content-Type: application/json; charset=utf-8');echo json_encode(array('draw'=>$draw,'recordsTotal'=>$total,'recordsFiltered'=>$total,'data'=>$data,'kpi'=>array('total'=>$kpi?(int)$kpi->total:0,'pending'=>$kpi?(int)$kpi->pending_count:0,'approved'=>$kpi?(int)$kpi->approved_count:0,'exception'=>$kpi?(int)$kpi->exception_count:0,'requested_days'=>$kpi?$kpi->requested_days:0,'approved_days'=>$kpi?$kpi->approved_days:0,'quota_deducted'=>$kpi?$kpi->quota_deducted:0)));
?>
