<?php
if (!function_exists('hr_t')) {
  function hr_t($key, $fallback = '') { return lang_text($key, $fallback); }
}
if (!function_exists('hr_h')) {
  function hr_h($key, $fallback = '') { return htmlspecialchars((string) hr_t($key, $fallback), ENT_QUOTES, 'UTF-8'); }
}
if (!function_exists('hr_js')) {
  function hr_js($key, $fallback = '') { return json_encode(hr_t($key, $fallback), JSON_HEX_TAG | JSON_HEX_APOS | JSON_HEX_AMP | JSON_HEX_QUOT); }
}
$defaultFrom=date('Y-m-01');$defaultTo=date('Y-m-t');$today=date('Y-m-d');$canInsert=isset($role_act['insert_act'])&&$role_act['insert_act']==='Y'; ?>
<style>
.ot-hero{background:linear-gradient(135deg,#7c2d12,#2563eb);color:#fff;border-radius:14px;padding:20px;margin-bottom:18px;box-shadow:0 10px 24px rgba(15,23,42,.16)}.ot-hero h1{margin:0 0 6px;font-size:26px;font-weight:700}.ot-hero p{margin:0;opacity:.94}.ot-card{border-radius:12px;background:#fff;border:1px solid #e5edf5;box-shadow:0 5px 16px rgba(15,23,42,.05);margin-bottom:14px}.ot-kpi{padding:14px;border-radius:12px;background:#f8fafc;border:1px solid #e5edf5}.ot-kpi b{font-size:22px;display:block}#dtb_overtime th,#dtb_overtime td{font-size:12px;vertical-align:middle}.select2-container{width:100%!important}.required-label:after{content:' *';color:#dd4b39}.ot-action{white-space:nowrap}#modal_overtime .modal-body{max-height:calc(100vh - 185px);overflow-y:auto}.ot-section-title{font-weight:700;color:#334155;margin:8px 0 12px;border-bottom:1px solid #e5e7eb;padding-bottom:7px}.ot-hint{background:#fff7ed;border:1px solid #fed7aa;border-radius:10px;padding:10px;margin-bottom:10px}
</style>
<section class="content-header"><h1><?=hr_h('hr_overtime', 'Overtime');?> <small>SAP HR Overtime Management</small></h1><ol class="breadcrumb"><li><a href="<?=base_index();?>"><i class="fa fa-dashboard"></i> <?=hr_h('common_home', 'Home');?></a></li><li>Human Resource</li><li>Time Management</li><li class="active"><?=hr_h('hr_overtime', 'Overtime');?></li></ol></section>
<section class="content">
<div class="ot-hero"><div class="row"><div class="col-md-8"><h1>Overtime Workbench</h1><p>Kelola request lembur berbasis attendance atau manual: alasan, cost center, jam request/approve/payable, multiplier, estimasi amount, approval, dan posting payroll.</p></div><div class="col-md-4 text-right"><?php if($canInsert){ ?><button id="btn_open_ot" class="btn btn-warning"><i class="fa fa-plus"></i> Create Overtime</button><?php } ?> <button id="btn_export_ot" class="btn btn-success"><i class="fa fa-file-excel-o"></i> <?=hr_h('common_export_excel', 'Export Excel');?></button></div></div></div>
<div class="row"><div class="col-sm-2"><div class="ot-kpi"><span>Total</span><b id="kpi_total">0</b></div></div><div class="col-sm-2"><div class="ot-kpi"><span><?=hr_h('hr_approved', 'Approved');?></span><b id="kpi_approved">0</b></div></div><div class="col-sm-2"><div class="ot-kpi"><span><?=hr_h('hr_posted', 'Posted');?></span><b id="kpi_posted">0</b></div></div><div class="col-sm-2"><div class="ot-kpi"><span>Requested</span><b id="kpi_requested">0</b></div></div><div class="col-sm-2"><div class="ot-kpi"><span>Payable Hours</span><b id="kpi_payable_hours">0</b></div></div><div class="col-sm-2"><div class="ot-kpi"><span>Amount</span><b id="kpi_amount">0</b></div></div></div>
<div class="box ot-card"><div class="box-header"><h3 class="box-title"><i class="fa fa-filter"></i> Filter Overtime</h3></div><div class="box-body"><form class="form-horizontal" onsubmit="return false;"><div class="form-group"><label class="control-label col-lg-2"><?=hr_h('hr_date', 'Date');?></label><div class="col-lg-2"><div class="input-group date ot-date"><input id="filter_tgl_awal" class="form-control" value="<?=$defaultFrom;?>"><span class="input-group-addon"><span class="glyphicon glyphicon-calendar"></span></span></div></div><div class="col-lg-2"><div class="input-group date ot-date"><input id="filter_tgl_akhir" class="form-control" value="<?=$defaultTo;?>"><span class="input-group-addon"><span class="glyphicon glyphicon-calendar"></span></span></div></div><label class="control-label col-lg-1"><?=hr_h('hr_employee', 'Employee');?></label><div class="col-lg-3"><select id="filter_employee_id" class="form-control"></select></div><label class="control-label col-lg-1"><?=hr_h('common_status', 'Status');?></label><div class="col-lg-1"><select id="filter_overtime_status" class="form-control"><option value="">All</option><option>DRAFT</option><option>REQUESTED</option><option>APPROVED</option><option>REJECTED</option><option>POSTED</option><option>CANCELLED</option></select></div></div><div class="form-group"><label class="control-label col-lg-2"><?=hr_h('hr_department', 'Department');?></label><div class="col-lg-2"><select id="filter_department_code" class="form-control"></select></div><label class="control-label col-lg-1">Type</label><div class="col-lg-2"><select id="filter_overtime_type" class="form-control"><option value="">All</option><option>REGULAR_OT</option><option>HOLIDAY_OT</option><option>WEEKEND_OT</option><option>CALL_OUT</option><option>PROJECT_OT</option><option>EMERGENCY_OT</option></select></div><label class="control-label col-lg-1">Source</label><div class="col-lg-2"><select id="filter_request_source" class="form-control"><option value="">All</option><option>ATTENDANCE</option><option>MANUAL</option><option>IMPORT</option><option>MOBILE</option><option>WEB</option></select></div><div class="col-lg-2"><input id="filter_keyword" class="form-control" placeholder="OT no, employee, reason"></div></div><div class="form-group"><div class="col-lg-offset-2 col-lg-10"><button id="btn_filter_ot" class="btn btn-primary"><i class="fa fa-filter"></i> <?=hr_h('common_filter', 'Filter');?></button> <button id="btn_reset_ot" class="btn btn-default"><i class="fa fa-refresh"></i> <?=hr_h('common_reset', 'Reset');?></button></div></div></form></div></div>
<div class="box ot-card"><div class="box-body"><div class="alert alert-warning error_data_delete" style="display:none"><button type="button" class="close hide_alert_notif">&times;</button><span class="isi_warning_delete"></span></div><div class="table-responsive"><table id="dtb_overtime" class="table table-bordered table-striped" style="width:100%"><thead><tr><th><?=hr_h('common_no', 'No');?></th><th><?=hr_h('common_action', 'Action');?></th><th><?=hr_h('hr_overtime', 'Overtime');?></th><th><?=hr_h('hr_employee', 'Employee');?></th><th><?=hr_h('hr_department', 'Department');?></th><th>Type</th><th>Time</th><th>Hours</th><th>Amount</th><th><?=hr_h('common_status', 'Status');?></th><th>Updated</th></tr></thead><tbody></tbody></table></div></div></div>
<div id="modal_overtime" class="modal fade"><div class="modal-dialog modal-lg" style="width:94%"><div class="modal-content"><form id="form_overtime"><input type="hidden" name="id" id="ot_id"><input type="hidden" name="shift_schedule_id" id="shift_schedule_id"><input type="hidden" name="assignment_no" id="assignment_no"><div class="modal-header"><button type="button" class="close" data-dismiss="modal">&times;</button><h4 class="modal-title">Create Overtime</h4></div><div class="modal-body"><div class="ot-hint"><strong>SAP hint:</strong> Pilih Attendance yang punya OT Hours untuk auto-fill employee, date, planned/actual time, dan requested hours. Manual tetap bisa untuk planned overtime sebelum attendance final.</div>
<div class="ot-section-title">Request Header</div><div class="row"><div class="col-md-2 form-group"><label class="required-label">Overtime No</label><input name="overtime_no" id="overtime_no" class="form-control text-uppercase" required maxlength="30" placeholder="OT-..."></div><div class="col-md-2 form-group"><label class="required-label"><?=hr_h('hr_date', 'Date');?></label><input name="overtime_date" id="overtime_date" class="form-control date-field" value="<?=$today;?>"></div><div class="col-md-4 form-group"><label>Attendance Ref</label><select name="attendance_id" id="attendance_id" class="form-control"></select></div><div class="col-md-4 form-group"><label class="required-label"><?=hr_h('hr_employee', 'Employee');?></label><select name="employee_id" id="employee_id" class="form-control" required></select></div></div>
<div class="row"><div class="col-md-3 form-group"><label><?=hr_h('hr_department', 'Department');?></label><select name="department_code" id="department_code" class="form-control"></select></div><div class="col-md-3 form-group"><label>Cost Center</label><select name="cost_center_code" id="cost_center_code" class="form-control"></select></div><div class="col-md-3 form-group"><label>Type</label><select name="overtime_type" id="overtime_type" class="form-control"><option>REGULAR_OT</option><option>HOLIDAY_OT</option><option>WEEKEND_OT</option><option>CALL_OUT</option><option>PROJECT_OT</option><option>EMERGENCY_OT</option></select></div><div class="col-md-3 form-group"><label><?=hr_h('common_status', 'Status');?></label><select name="overtime_status" id="overtime_status" class="form-control"><option>DRAFT</option><option>REQUESTED</option><option>APPROVED</option><option>REJECTED</option><option>POSTED</option><option>CANCELLED</option></select></div></div>
<div class="ot-section-title">Time & Payroll Estimate</div><div class="row"><div class="col-md-3 form-group"><label>Planned Start</label><input name="planned_start" id="planned_start" type="datetime-local" class="form-control"></div><div class="col-md-3 form-group"><label>Planned End</label><input name="planned_end" id="planned_end" type="datetime-local" class="form-control"></div><div class="col-md-3 form-group"><label>Actual Start</label><input name="actual_start" id="actual_start" type="datetime-local" class="form-control"></div><div class="col-md-3 form-group"><label>Actual End</label><input name="actual_end" id="actual_end" type="datetime-local" class="form-control"></div></div>
<div class="row"><div class="col-md-2 form-group"><label>Requested Hours</label><input name="requested_hours" id="requested_hours" type="number" step="0.01" min="0" class="form-control" value="0"></div><div class="col-md-2 form-group"><label>Approved Hours</label><input name="approved_hours" id="approved_hours" type="number" step="0.01" min="0" class="form-control" value="0"></div><div class="col-md-2 form-group"><label>Payable Hours</label><input name="payable_hours" id="payable_hours" type="number" step="0.01" min="0" class="form-control" value="0"></div><div class="col-md-2 form-group"><label>Multiplier</label><input name="rate_multiplier" id="rate_multiplier" type="number" step="0.01" min="0" class="form-control" value="1.50"></div><div class="col-md-2 form-group"><label>Hourly Rate</label><input name="hourly_rate" id="hourly_rate" type="number" step="0.01" min="0" class="form-control" value="0"></div><div class="col-md-2 form-group"><label>Source</label><select name="request_source" id="request_source" class="form-control"><option>MANUAL</option><option>ATTENDANCE</option><option>IMPORT</option><option>MOBILE</option><option>WEB</option></select></div></div>
<div class="row"><div class="col-md-6 form-group"><label class="required-label">Overtime Reason</label><input name="overtime_reason" id="overtime_reason" class="form-control" required></div><div class="col-md-3 form-group"><label>Reject Reason</label><input name="reject_reason" id="reject_reason" class="form-control"></div><div class="col-md-3 form-group"><label>SAP Reference</label><input name="sap_reference" id="sap_reference" class="form-control"></div></div><div class="form-group"><label><?=hr_h('common_remarks', 'Remarks');?></label><textarea name="remarks" id="remarks" class="form-control" rows="2"></textarea></div>
</div><div class="modal-footer"><button type="button" class="btn btn-default" data-dismiss="modal"><?=hr_h('common_cancel', 'Cancel');?></button><button type="submit" class="btn btn-primary"><i class="fa fa-save"></i> Save Overtime</button></div></form></div></div></div>
<div id="modal_ot_detail" class="modal fade"><div class="modal-dialog modal-lg" style="width:92%"><div class="modal-content"><div class="modal-header"><button class="close" data-dismiss="modal">&times;</button><h4 class="modal-title">Overtime Detail</h4></div><div class="modal-body" id="ot_detail_body"></div><div class="modal-footer"><button class="btn btn-default" data-dismiss="modal"><?=hr_h('common_close', 'Close');?></button></div></div></div></div>
</section>
<script src="<?=base_admin();?>assets/plugins/select2/select2.min.js"></script><script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
<script>
function otError(m){$('.isi_warning_delete').text(m||<?=hr_js('hr_overtime_process_failed', 'Overtime failed to process.');?>);$('.error_data_delete').fadeIn();}
function otFilters(){return{tgl_awal:$('#filter_tgl_awal').val(),tgl_akhir:$('#filter_tgl_akhir').val(),employee_id:$('#filter_employee_id').val(),department_code:$('#filter_department_code').val(),overtime_type:$('#filter_overtime_type').val(),overtime_status:$('#filter_overtime_status').val(),request_source:$('#filter_request_source').val(),keyword:$('#filter_keyword').val()};}
function otSet(s,v,t){var e=$(s);if(!v){e.val(null).trigger('change');return;}if(!e.find('option[value="'+v+'"]').length)e.append(new Option(t||v,v,true,true));e.val(v).trigger('change');}
function otAjax(selector,act,placeholder,parent){$(selector).select2({width:'100%',allowClear:true,placeholder:placeholder,dropdownParent:parent||$(document.body),ajax:{url:'<?=base_admin();?>modul/overtime/overtime_action.php?act='+act,type:'POST',dataType:'json',delay:250,data:function(q){return{term:q.term||''};},processResults:function(d){return{results:d.results||[]};}}});}
function otReset(title){$('#form_overtime')[0].reset();$('#ot_id,#shift_schedule_id,#assignment_no').val('');$('#attendance_id,#employee_id,#department_code,#cost_center_code').val(null).trigger('change');$('#overtime_date').val('<?=$today;?>');$('#overtime_type').val('REGULAR_OT').trigger('change');$('#request_source').val('MANUAL').trigger('change');$('#overtime_status').val('DRAFT').trigger('change');$('#requested_hours,#approved_hours,#payable_hours,#hourly_rate').val(0);$('#rate_multiplier').val('1.50');$('#modal_overtime .modal-title').text(title||'Create Overtime');}
$(function(){if($.fn.datepicker){$('.ot-date,.date-field').datepicker({format:'yyyy-mm-dd',autoclose:true,todayHighlight:true});}if($.fn.select2){$('#filter_overtime_type,#filter_overtime_status,#filter_request_source,#overtime_type,#request_source,#overtime_status').select2({width:'100%',allowClear:true});otAjax('#filter_employee_id','employee_search','Semua Employee');otAjax('#filter_department_code','department_search','Semua Department');otAjax('#attendance_id','attendance_search','Pilih Attendance OT',$('#modal_overtime'));otAjax('#employee_id','employee_search','Pilih Employee',$('#modal_overtime'));otAjax('#department_code','department_search','Pilih Department',$('#modal_overtime'));otAjax('#cost_center_code','cost_center_search','Pilih Cost Center',$('#modal_overtime'));}
var dt=$('#dtb_overtime').DataTable({bProcessing:true,bServerSide:true,pageLength:25,dom:"<'row'<'col-sm-12'B>>"+"<'row'<'col-sm-6'l><'col-sm-6'f>>"+"<'row'<'col-sm-12'tr>>"+"<'row'<'col-sm-5'i><'col-sm-7'p>>",buttons:[{extend:'collection',text:<?=hr_js('common_export_data', 'Export Data');?>,buttons:['copyHtml5','excelHtml5','csvHtml5','pdfHtml5']}],columnDefs:[{targets:[0,1],orderable:false,searchable:false},{width:'42px',targets:0},{width:'210px',targets:1}],ajax:{url:'<?=base_admin();?>modul/overtime/overtime_data.php',type:'post',data:function(d){$.extend(d,otFilters());},dataSrc:function(j){var k=j.kpi||{};$('#kpi_total').text(k.total||0);$('#kpi_approved').text(k.approved||0);$('#kpi_posted').text(k.posted||0);$('#kpi_requested').text(k.requested||0);$('#kpi_payable_hours').text(k.payable_hours||0);$('#kpi_amount').text(k.amount||0);return j.data||[];},error:function(x){console.log(x.responseText);otError('Data Overtime gagal dimuat.');}}});
$('#btn_open_ot').click(function(){otReset('Create Overtime');$('#modal_overtime').modal({backdrop:'static',keyboard:false});});$('#btn_filter_ot').click(function(){dt.draw();});$('#filter_keyword').keyup(function(e){if(e.keyCode===13)dt.draw();});$('#btn_reset_ot').click(function(){$('#filter_tgl_awal').val('<?=$defaultFrom;?>');$('#filter_tgl_akhir').val('<?=$defaultTo;?>');$('#filter_employee_id,#filter_department_code,#filter_overtime_type,#filter_overtime_status,#filter_request_source').val(null).trigger('change');$('#filter_keyword').val('');dt.draw();});$('#btn_export_ot').click(function(){window.location='<?=base_admin();?>modul/overtime/overtime_action.php?act=export&'+$.param(otFilters());});$('.hide_alert_notif').click(function(){$('.error_data_delete').hide();});$('#overtime_no').on('keyup change',function(){this.value=this.value.toUpperCase();});
$('#attendance_id').on('select2:select',function(e){$.post('<?=base_admin();?>modul/overtime/overtime_action.php?act=attendance_info',{attendance_id:e.params.data.id},function(r){if(r.status==='good'){otSet('#employee_id',r.employee_id,r.employee_text);otSet('#department_code',r.department_code,r.department_text);$('#shift_schedule_id').val(r.shift_schedule_id);$('#assignment_no').val(r.assignment_no);$('#overtime_date').val(r.overtime_date);$('#planned_start').val(r.planned_start);$('#planned_end').val(r.planned_end);$('#actual_start').val(r.actual_start);$('#actual_end').val(r.actual_end);$('#requested_hours,#approved_hours,#payable_hours').val(r.requested_hours);$('#request_source').val('ATTENDANCE').trigger('change');}},'json');});
$('#form_overtime').submit(function(e){e.preventDefault();var b=$(this).find('button[type=submit]');b.prop('disabled',true).html('<i class="fa fa-spinner fa-spin"></i> <?=hr_h('common_saving', 'Saving...');?>');$.post('<?=base_admin();?>modul/overtime/overtime_action.php?act=save',$(this).serialize(),function(r){b.prop('disabled',false).html('<i class="fa fa-save"></i> Save Overtime');if(r.status==='good'){$('#modal_overtime').modal('hide');dt.draw(false);Swal.fire('Saved','Overtime berhasil disimpan.','success');}else otError(r.error_message);},'json').fail(function(x){b.prop('disabled',false).html('<i class="fa fa-save"></i> Save Overtime');otError(x.responseText);});});
$(document).on('click','.btn-ot-detail',function(){$.post('<?=base_admin();?>modul/overtime/overtime_action.php?act=detail',{id:$(this).data('id')},function(h){$('#ot_detail_body').html(h);$('#modal_ot_detail').modal('show');});});
$(document).on('click','.btn-ot-edit',function(){var id=$(this).data('id');$.post('<?=base_admin();?>modul/overtime/overtime_action.php?act=get',{id:id},function(r){if(r.status!=='good'){otError(r.error_message);return;}otReset('Edit Overtime');var h=r.data||{};Object.keys(h).forEach(function(k){var el=$('#'+k);if(el.length&&!['employee_id','department_code','cost_center_code','attendance_id'].includes(k))el.val(h[k]);});$('#ot_id').val(h.id);otSet('#employee_id',h.employee_id,h.employee_text);otSet('#department_code',h.department_code,h.department_text);otSet('#cost_center_code',h.cost_center_code,h.cost_center_text);otSet('#attendance_id',h.attendance_id,h.attendance_text);$('#overtime_type,#request_source,#overtime_status').trigger('change');$('#modal_overtime').modal({backdrop:'static',keyboard:false});},'json');});
$(document).on('click','.btn-ot-status',function(){var id=$(this).data('id'),status=$(this).data('status');$.post('<?=base_admin();?>modul/overtime/overtime_action.php?act=status',{id:id,status:status},function(r){if(r.status==='good'){dt.draw(false);Swal.fire('Updated','Status berhasil diubah.','success');}else otError(r.error_message);},'json');});
$(document).on('click','.btn-ot-delete',function(){if($(this).is(':disabled'))return;var id=$(this).data('id'),no=$(this).data('no');Swal.fire({title:erpLang('confirm_delete_title','Delete Confirmation'),text:no,icon:'warning',showCancelButton:true,confirmButtonText:erpLang('common_delete','Delete'),cancelButtonText:erpLang('common_cancel','Cancel')}).then(function(x){if(!x.isConfirmed)return;$.post('<?=base_admin();?>modul/overtime/overtime_action.php?act=delete',{id:id},function(r){if(r.status==='good'){dt.draw(false);Swal.fire(erpLang('common_deleted','Deleted'),erpLang('common_deleted_message','Data deleted successfully.'),'success');}else otError(r.error_message);},'json').fail(function(x){otError(x.responseText);});});});
});
</script>
