<?php
if (!function_exists('hr_t')) {
  function hr_t($key, $fallback = '') { return lang_text($key, $fallback); }
}
if (!function_exists('hr_h')) {
  function hr_h($key, $fallback = '') { return htmlspecialchars((string) hr_t($key, $fallback), ENT_QUOTES, 'UTF-8'); }
}
if (!function_exists('hr_js')) {
  function hr_js($key, $fallback = '') { return json_encode(hr_t($key, $fallback), JSON_HEX_TAG | JSON_HEX_APOS | JSON_HEX_AMP | JSON_HEX_QUOT); }
}
if (session_status() === PHP_SESSION_NONE) session_start();
include "../../inc/config.php";
session_check_json();
function otd_h($v){return htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');}
function otd_label($s){$map=array('DRAFT'=>'warning','REQUESTED'=>'info','APPROVED'=>'success','REJECTED'=>'danger','POSTED'=>'primary','CANCELLED'=>'default');$c=isset($map[$s])?$map[$s]:'default';return '<span class="label label-'.$c.'">'.otd_h($s).'</span>';}
$draw=isset($_POST['draw'])?(int)$_POST['draw']:1;$start=isset($_POST['start'])?max(0,(int)$_POST['start']):0;$length=isset($_POST['length'])?(int)$_POST['length']:25;if($length<=0||$length>500)$length=25;
$from=isset($_POST['tgl_awal'])&&$_POST['tgl_awal']!==''?$_POST['tgl_awal']:date('Y-m-01');$to=isset($_POST['tgl_akhir'])&&$_POST['tgl_akhir']!==''?$_POST['tgl_akhir']:date('Y-m-t');$emp=isset($_POST['employee_id'])?trim($_POST['employee_id']):'';$dept=isset($_POST['department_code'])?trim($_POST['department_code']):'';$type=isset($_POST['overtime_type'])?trim($_POST['overtime_type']):'';$status=isset($_POST['overtime_status'])?trim($_POST['overtime_status']):'';$source=isset($_POST['request_source'])?trim($_POST['request_source']):'';$kw=isset($_POST['keyword'])?trim($_POST['keyword']):'';
$w=" WHERE ot.overtime_date BETWEEN ? AND ? ";$p=array($from,$to);if($emp!==''){$w.=" AND ot.employee_id=? ";$p[]=(int)$emp;}if($dept!==''){$w.=" AND ot.department_code=? ";$p[]=$dept;}if($type!==''){$w.=" AND ot.overtime_type=? ";$p[]=$type;}if($status!==''){$w.=" AND ot.overtime_status=? ";$p[]=$status;}if($source!==''){$w.=" AND ot.request_source=? ";$p[]=$source;}if($kw!==''){$like='%'.$kw.'%';$w.=" AND (ot.overtime_no LIKE ? OR ot.employee_no LIKE ? OR e.full_name LIKE ? OR ot.overtime_reason LIKE ? OR ot.sap_reference LIKE ?) ";array_push($p,$like,$like,$like,$like,$like);}
$kpi=$db->fetch("SELECT COUNT(*) total,SUM(overtime_status='APPROVED') approved,SUM(overtime_status='POSTED') posted,SUM(overtime_status='REQUESTED') requested,ROUND(SUM(payable_hours),2) payable_hours,ROUND(SUM(estimated_amount),2) amount FROM erp_overtime");
$cnt=$db->fetch("SELECT COUNT(*) jml FROM erp_overtime ot JOIN erp_employee_master e ON e.id=ot.employee_id $w",$p);$total=$cnt?(int)$cnt->jml:0;
$orderMap=array(2=>'ot.overtime_no',3=>'ot.overtime_date',4=>'e.employee_no',5=>'ot.department_code',6=>'ot.overtime_type',7=>'ot.payable_hours',8=>'ot.estimated_amount',9=>'ot.overtime_status',10=>'ot.updated_at');$orderBy='ot.overtime_date DESC,ot.overtime_no';if(isset($_POST['order'][0]['column'])){$col=(int)$_POST['order'][0]['column'];$dir=(isset($_POST['order'][0]['dir'])&&strtolower($_POST['order'][0]['dir'])==='desc')?'DESC':'ASC';if(isset($orderMap[$col]))$orderBy=$orderMap[$col].' '.$dir;}
$rows=$db->query("SELECT ot.*,e.full_name,e.employee_group,d.nm_dept,cc.cost_center_name FROM erp_overtime ot JOIN erp_employee_master e ON e.id=ot.employee_id LEFT JOIN dept d ON d.kd_dept=ot.department_code LEFT JOIN erp_cost_center cc ON cc.cost_center_code=ot.cost_center_code $w ORDER BY $orderBy LIMIT $start,$length",$p);
$data=array();$no=$start+1;foreach($rows as $r){$canDel=$r->overtime_status==='POSTED'?' disabled':'';$act='<div class="ot-action"><button class="btn btn-info btn-xs btn-ot-detail" data-id="'.(int)$r->id.'" title="'.hr_h('common_detail', 'Detail').'"><i class="fa fa-eye"></i></button> <button class="btn btn-primary btn-xs btn-ot-edit" data-id="'.(int)$r->id.'" title="'.hr_h('common_edit', 'Edit').'"><i class="fa fa-pencil"></i></button> <button class="btn btn-success btn-xs btn-ot-status" data-id="'.(int)$r->id.'" data-status="APPROVED" title="'.hr_h('common_approve', 'Approve').'"><i class="fa fa-check"></i></button> <button class="btn btn-primary btn-xs btn-ot-status" data-id="'.(int)$r->id.'" data-status="POSTED" title="Post"><i class="fa fa-upload"></i></button> <button class="btn btn-warning btn-xs btn-ot-status" data-id="'.(int)$r->id.'" data-status="CANCELLED" title="'.hr_h('common_cancel', 'Cancel').'"><i class="fa fa-ban"></i></button> <button class="btn btn-danger btn-xs btn-ot-delete" data-id="'.(int)$r->id.'" data-no="'.otd_h($r->overtime_no).'" title="'.hr_h('common_delete', 'Delete').'"'.$canDel.'><i class="fa fa-trash"></i></button></div>';
  $data[]=array($no++,$act,'<strong>'.otd_h($r->overtime_no).'</strong><br><small>'.otd_h($r->overtime_date).'</small>','<strong>'.otd_h($r->employee_no).'</strong><br><small>'.otd_h($r->full_name).'</small><br><small>'.otd_h($r->employee_group).'</small>','<strong>'.otd_h($r->department_code?:'-').'</strong><br><small>'.otd_h($r->nm_dept?:'-').'</small>','<strong>'.otd_h($r->overtime_type).'</strong><br><small>'.otd_h($r->request_source.' / '.($r->attendance_no?:'-')).'</small>',otd_h($r->planned_start?substr($r->planned_start,11,5):'-').' - '.otd_h($r->planned_end?substr($r->planned_end,11,5):'-').'<br><small>Actual: '.otd_h($r->actual_start?substr($r->actual_start,11,5):'-').' - '.otd_h($r->actual_end?substr($r->actual_end,11,5):'-').'</small>','Req '.otd_h($r->requested_hours).' | App '.otd_h($r->approved_hours).'<br><small>Pay '.otd_h($r->payable_hours).' x '.otd_h($r->rate_multiplier).'</small>','<strong>'.number_format((float)$r->estimated_amount,2).'</strong><br><small>'.otd_h($r->cost_center_code?:'-').'</small>',otd_label($r->overtime_status),otd_h($r->updated_by?:$r->created_by?:'-').'<br><small>'.otd_h($r->updated_at?:$r->created_at).'</small>');}
header('Content-Type: application/json; charset=utf-8');echo json_encode(array('draw'=>$draw,'recordsTotal'=>$total,'recordsFiltered'=>$total,'data'=>$data,'kpi'=>array('total'=>$kpi?(int)$kpi->total:0,'approved'=>$kpi?(int)$kpi->approved:0,'posted'=>$kpi?(int)$kpi->posted:0,'requested'=>$kpi?(int)$kpi->requested:0,'payable_hours'=>$kpi?$kpi->payable_hours:0,'amount'=>$kpi?$kpi->amount:0)));
?>
