<?php
if (!function_exists('prod_t')) {
  function prod_t($key, $fallback = '') { return lang_text($key, $fallback); }
}
if (!function_exists('prod_h')) {
  function prod_h($key, $fallback = '') { return htmlspecialchars((string) prod_t($key, $fallback), ENT_QUOTES, 'UTF-8'); }
}
if (!function_exists('prod_js')) {
  function prod_js($key, $fallback = '') { return json_encode(prod_t($key, $fallback), JSON_HEX_TAG | JSON_HEX_APOS | JSON_HEX_AMP | JSON_HEX_QUOT); }
}
$defaultFrom=date('Y-m-01');$defaultTo=date('Y-m-d');
$plants=$db->query("SELECT DISTINCT plant AS plant_code FROM production_order WHERE plant IS NOT NULL AND plant<>'' ORDER BY plant");
$kpi=$db->fetch("SELECT COUNT(*) total_doc,SUM(dispatch_status='SCHEDULED') scheduled_doc,SUM(dispatch_status='DISPATCHED') dispatched_doc,SUM(dispatch_status='DRAFT') draft_doc FROM erp_production_schedule WHERE schedule_date BETWEEN ? AND ?",array($defaultFrom,$defaultTo));
?>
<style>
.ps-hero{background:linear-gradient(135deg,#7c3aed,#0f766e);color:#fff;border-radius:14px;padding:20px 22px;margin-bottom:18px;box-shadow:0 10px 24px rgba(15,23,42,.18)}.ps-hero h1{margin:0 0 6px;font-size:26px;font-weight:700}.ps-hero p{margin:0;opacity:.92}.ps-card{border-radius:12px;background:#fff;border:1px solid #e5edf5;box-shadow:0 5px 16px rgba(15,23,42,.05);margin-bottom:14px}.ps-kpi{border-radius:12px;background:#fff;border:1px solid #edf2f7;padding:15px;margin-bottom:14px}.ps-kpi span{display:block;color:#64748b;font-size:12px;text-transform:uppercase}.ps-kpi strong{display:block;font-size:24px;margin-top:6px}.ps-kpi i{float:right;font-size:26px;color:#7c3aed;opacity:.55}#dtb_production_schedule th,#dtb_production_schedule td,.ps-op-table th,.ps-op-table td{font-size:12px;vertical-align:middle}.ps-action{white-space:nowrap;min-width:110px}.select2-container{width:100%!important}.ps-form .form-group{margin-bottom:12px}.ps-op-wrap{max-height:420px;overflow:auto;border:1px solid #e5e7eb;border-radius:8px}.ps-op-table{margin-bottom:0}.ps-op-table thead th{position:sticky;top:0;background:#f8fafc;z-index:2}.ps-help{font-size:12px;color:#64748b;margin-top:5px}.required-label:after{content:' *';color:#dd4b39}
</style>
<section class="content-header"><h1><?=prod_h('production_schedule', 'Production Schedule');?> <small>SAP PP Dispatch Planning</small></h1><ol class="breadcrumb"><li><a href="<?=base_index();?>"><i class="fa fa-dashboard"></i> <?=prod_h('common_home', 'Home');?></a></li><li class="active"><?=prod_h('production_schedule', 'Production Schedule');?></li></ol></section>
<section class="content">
  <div class="ps-hero"><div class="row"><div class="col-md-8"><h1>Production Schedule Workbench</h1><p>Susun jadwal produksi per Production Order dan operation: work center, shift, waktu mulai/selesai, kapasitas, dan dispatch ke shop floor.</p></div><div class="col-md-4 text-right"><button id="btn_add_ps" class="btn btn-warning btn-lg"><i class="fa fa-plus"></i> Create Schedule</button></div></div></div>
  <div class="row"><div class="col-sm-3"><div class="ps-kpi"><i class="fa fa-calendar"></i><span>Total This Period</span><strong><?=number_format((float)$kpi->total_doc,0,',','.');?></strong></div></div><div class="col-sm-3"><div class="ps-kpi"><i class="fa fa-list"></i><span>Draft</span><strong><?=number_format((float)$kpi->draft_doc,0,',','.');?></strong></div></div><div class="col-sm-3"><div class="ps-kpi"><i class="fa fa-calendar-check-o"></i><span>Scheduled</span><strong><?=number_format((float)$kpi->scheduled_doc,0,',','.');?></strong></div></div><div class="col-sm-3"><div class="ps-kpi"><i class="fa fa-send"></i><span>Dispatched</span><strong><?=number_format((float)$kpi->dispatched_doc,0,',','.');?></strong></div></div></div>
  <div class="box ps-card"><div class="box-header"><h3 class="box-title"><i class="fa fa-filter"></i> Filter Schedule</h3></div><div class="box-body"><form class="form-horizontal" onsubmit="return false;"><div class="form-group"><label class="control-label col-lg-2">Schedule Date</label><div class="col-lg-2"><div class="input-group date ps-date"><input id="filter_tgl_awal" class="form-control" value="<?=$defaultFrom;?>"><span class="input-group-addon"><span class="glyphicon glyphicon-calendar"></span></span></div></div><div class="col-lg-2"><div class="input-group date ps-date"><input id="filter_tgl_akhir" class="form-control" value="<?=$defaultTo;?>"><span class="input-group-addon"><span class="glyphicon glyphicon-calendar"></span></span></div></div><label class="control-label col-lg-1"><?=prod_h('common_status', 'Status');?></label><div class="col-lg-2"><select id="filter_status" class="form-control"><option value=""><?=prod_h('common_all', 'All');?></option><option>DRAFT</option><option>SCHEDULED</option><option>DISPATCHED</option><option>IN_PROCESS</option><option>COMPLETED</option><option>CANCELLED</option></select></div><label class="control-label col-lg-1"><?=prod_h('production_plant', 'Plant');?></label><div class="col-lg-2"><select id="filter_plant" class="form-control"><option value=""><?=prod_h('common_all', 'All');?></option><?php foreach($plants as $p){ ?><option value="<?=htmlspecialchars($p->plant_code,ENT_QUOTES,'UTF-8');?>"><?=htmlspecialchars($p->plant_code,ENT_QUOTES,'UTF-8');?></option><?php } ?></select></div></div><div class="form-group"><label class="control-label col-lg-2"><?=prod_h('production_work_center', 'Work Center');?></label><div class="col-lg-2"><input id="filter_work_center" class="form-control" placeholder="WC code/name"></div><label class="control-label col-lg-1"><?=prod_h('common_search', 'Search');?></label><div class="col-lg-4"><input id="filter_keyword" class="form-control" placeholder="Schedule, PO, material, scheduler"></div><div class="col-lg-3"><button id="btn_filter_ps" class="btn btn-primary"><i class="fa fa-filter"></i> <?=prod_h('common_filter', 'Filter');?></button> <button id="btn_reset_ps" class="btn btn-default"><i class="fa fa-refresh"></i> <?=prod_h('common_reset', 'Reset');?></button> <button id="btn_excel_ps" class="btn btn-success"><i class="fa fa-file-excel-o"></i> <?=prod_h('common_export_excel', 'Export Excel');?></button></div></div></form></div></div>
  <div class="box ps-card"><div class="box-body"><div class="alert alert-warning error_data_delete" style="display:none"><button type="button" class="close hide_alert_notif">&times;</button><span class="isi_warning_delete"></span></div><div class="table-responsive"><table id="dtb_production_schedule" class="table table-bordered table-striped table-condensed" style="width:100%"><thead><tr><th><?=prod_h('common_no', 'No');?></th><th><?=prod_h('common_action', 'Action');?></th><th>Schedule</th><th><?=prod_h('production_order', 'Production Order');?></th><th><?=prod_h('production_material', 'Material');?></th><th><?=prod_h('production_qty', 'Qty');?></th><th><?=prod_h('production_plant', 'Plant');?></th><th>Plan Date/Time</th><th>Operations</th><th><?=prod_h('common_status', 'Status');?></th><th><?=prod_h('common_created_by', 'Created By');?></th></tr></thead><tbody></tbody></table></div></div></div>
  <div id="modal_ps" class="modal fade"><div class="modal-dialog modal-lg" style="width:96%"><form id="form_ps" class="modal-content ps-form"><input type="hidden" name="submit" id="ps_submit" value="N"><div class="modal-header"><button class="close" data-dismiss="modal">&times;</button><h4 class="modal-title">Create Production Schedule</h4></div><div class="modal-body"><div class="row"><div class="col-md-7 form-group"><label class="required-label"><?=prod_h('production_order', 'Production Order');?></label><select id="ps_production_id" name="production_id" class="form-control" required></select><div class="ps-help">Hanya Production Order RELEASED/IN_PROCESS yang bisa dijadwalkan.</div></div><div class="col-md-2 form-group"><label class="required-label">Schedule Date</label><input name="schedule_date" id="ps_schedule_date" class="form-control ps-date-input" value="<?=date('Y-m-d');?>"></div><div class="col-md-3 form-group"><label>Scheduler</label><input name="scheduler" class="form-control" value="<?=htmlspecialchars(isset($_SESSION['username'])?$_SESSION['username']:'',ENT_QUOTES,'UTF-8');?>"></div></div><div class="row"><div class="col-md-3 form-group"><label>Planned Start</label><input type="datetime-local" name="planned_start" id="ps_planned_start" class="form-control" value="<?=date('Y-m-d');?>T08:00"></div><div class="col-md-3 form-group"><label>Planned Finish</label><input type="datetime-local" name="planned_finish" id="ps_planned_finish" class="form-control" value="<?=date('Y-m-d');?>T17:00"></div><div class="col-md-6 form-group"><label><?=prod_h('common_remarks', 'Remarks');?></label><input name="remarks" class="form-control" placeholder="Catatan dispatch, kapasitas, constraint mesin, dll"></div></div><div class="clearfix"><h4 class="pull-left">Operation Schedule</h4><button type="button" id="btn_reload_ops_ps" class="btn btn-default btn-sm pull-right"><i class="fa fa-refresh"></i> Reload Operations</button></div><div id="ps_ops_area" class="ps-op-wrap"><div class="alert alert-info" style="margin:12px">Pilih Production Order untuk menampilkan operation.</div></div></div><div class="modal-footer"><button type="button" class="btn btn-default" data-dismiss="modal"><?=prod_h('common_close', 'Close');?></button><button type="button" id="btn_save_draft_ps" class="btn btn-default"><i class="fa fa-save"></i> Save Draft</button><button type="button" id="btn_submit_ps" class="btn btn-primary"><i class="fa fa-calendar-check-o"></i> Save & Schedule</button></div></form></div></div>
  <div id="modal_detail_ps" class="modal fade"><div class="modal-dialog modal-lg" style="width:96%"><div class="modal-content"><div class="modal-header"><button class="close" data-dismiss="modal">&times;</button><h4 class="modal-title">Production Schedule Detail</h4></div><div class="modal-body" id="ps_detail_body"></div><div class="modal-footer"><button class="btn btn-default" data-dismiss="modal"><?=prod_h('common_close', 'Close');?></button></div></div></div></div>
</section>
<script src="<?=base_admin();?>assets/plugins/select2/select2.min.js"></script><script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
<script>
function psError(m){$('.isi_warning_delete').text(m||<?=prod_js('production_schedule_process_failed', 'Production Schedule failed to process.');?>);$('.error_data_delete').fadeIn();}
function psFilters(){return{tgl_awal:$('#filter_tgl_awal').val(),tgl_akhir:$('#filter_tgl_akhir').val(),status:$('#filter_status').val(),plant:$('#filter_plant').val(),work_center:$('#filter_work_center').val(),keyword:$('#filter_keyword').val()};}
function psLoadOps(){var po=$('#ps_production_id').val();if(!po){$('#ps_ops_area').html('<div class="alert alert-info" style="margin:12px">Pilih Production Order untuk menampilkan operation.</div>');return;}$('#ps_ops_area').html('<div class="alert alert-info" style="margin:12px"><i class="fa fa-spinner fa-spin"></i> Memuat operation...</div>');$.post('<?=base_admin();?>modul/production_schedule/production_schedule_action.php?act=operations',{production_id:po,planned_start:$('#ps_planned_start').val()},function(html){$('#ps_ops_area').html(html);if($.fn.select2){$('.ps-shift').select2({width:'100%',allowClear:true});}}).fail(function(){psError(<?=prod_js('production_operation_load_failed', 'Operation failed to load.');?>);});}
function psSave(flag){$('#ps_submit').val(flag);if(!$('#ps_production_id').val()){psError('Production Order wajib dipilih.');return;}if($('#form_ps input[name="op_id[]"]').length<1){psError('Minimal satu operation wajib dijadwalkan.');return;}$.ajax({url:'<?=base_admin();?>modul/production_schedule/production_schedule_action.php?act=save',type:'POST',data:$('#form_ps').serialize(),dataType:'json',success:function(r){if(r.status==='good'){$('#modal_ps').modal('hide');dt_ps.draw(false);Swal.fire(<?=prod_js('common_success', 'Success');?>,'Production Schedule '+(r.schedule_no||'')+' tersimpan.','success');}else psError(r.error_message);},error:function(xhr){console.log(xhr.responseText);psError('Production Schedule gagal disimpan.');}});}
var dt_ps;
$(function(){if($.fn.datepicker){$('.ps-date').datepicker({format:'yyyy-mm-dd',autoclose:true,todayHighlight:true});$('.ps-date-input').datepicker({format:'yyyy-mm-dd',autoclose:true,todayHighlight:true});}if($.fn.select2){$('#filter_status,#filter_plant').select2({width:'100%',allowClear:true});$('#ps_production_id').select2({width:'100%',placeholder:<?=prod_js('production_search_production_order', 'Search Production Order...');?>,minimumInputLength:1,ajax:{url:'<?=base_admin();?>modul/production_schedule/production_schedule_action.php?act=production_search',type:'POST',dataType:'json',delay:250,data:function(p){return{term:p.term||''};},processResults:function(d){return{results:d.results||[]};}}});}
dt_ps=$('#dtb_production_schedule').DataTable({bProcessing:true,bServerSide:true,pageLength:25,ordering:false,dom:"<'row'<'col-sm-12'B>>"+"<'row'<'col-sm-6'l><'col-sm-6'f>>"+"<'row'<'col-sm-12'tr>>"+"<'row'<'col-sm-5'i><'col-sm-7'p>>",buttons:[{extend:'collection',text:<?=prod_js('common_export_data', 'Export Data');?>,buttons:['copyHtml5','excelHtml5','csvHtml5','pdfHtml5']}],columnDefs:[{targets:[0,1],orderable:false,searchable:false},{width:'38px',targets:0},{width:'125px',targets:1}],ajax:{url:'<?=base_admin();?>modul/production_schedule/production_schedule_data.php',type:'post',data:function(d){$.extend(d,psFilters());},error:function(xhr){console.log(xhr.responseText);psError(<?=prod_js('production_schedule_load_failed', 'Production Schedule data failed to load.');?>);}}});
$('#btn_filter_ps').click(function(){dt_ps.draw();});$('#filter_keyword,#filter_work_center').keyup(function(e){if(e.keyCode===13)dt_ps.draw();});$('#btn_reset_ps').click(function(){$('#filter_tgl_awal').val('<?=$defaultFrom;?>');$('#filter_tgl_akhir').val('<?=$defaultTo;?>');$('#filter_status,#filter_plant').val('').trigger('change');$('#filter_work_center,#filter_keyword').val('');dt_ps.draw();});$('#btn_excel_ps').click(function(){window.location='<?=base_admin();?>modul/production_schedule/production_schedule_action.php?act=excel&'+$.param(psFilters());});
$('#btn_add_ps').click(function(){document.getElementById('form_ps').reset();$('#ps_production_id').val(null).trigger('change');$('#ps_schedule_date').val('<?=date('Y-m-d');?>');$('#ps_planned_start').val('<?=date('Y-m-d');?>T08:00');$('#ps_planned_finish').val('<?=date('Y-m-d');?>T17:00');$('#ps_ops_area').html('<div class="alert alert-info" style="margin:12px">Pilih Production Order untuk menampilkan operation.</div>');$('#modal_ps').modal({backdrop:'static',keyboard:false});});$('#ps_production_id,#ps_planned_start,#btn_reload_ops_ps').on('change click',psLoadOps);$('#btn_save_draft_ps').click(function(){psSave('N');});$('#btn_submit_ps').click(function(){psSave('Y');});
$(document).on('click','.btn-ps-detail',function(){$.post('<?=base_admin();?>modul/production_schedule/production_schedule_action.php?act=detail',{id:$(this).data('id')},function(html){$('#ps_detail_body').html(html);$('#modal_detail_ps').modal('show');}).fail(function(){psError('Detail gagal dibuka.');});});
$(document).on('click','.btn-ps-status',function(){var id=$(this).data('id'),act=$(this).data('act');Swal.fire({title:'Konfirmasi',text:'Lanjutkan aksi '+act+'?',icon:'question',showCancelButton:true,confirmButtonText:'Ya'}).then(function(x){if(!x.isConfirmed)return;$.post('<?=base_admin();?>modul/production_schedule/production_schedule_action.php?act='+act,{id:id},function(r){if(r.status==='good'){dt_ps.draw(false);Swal.fire(<?=prod_js('common_success', 'Success');?>,'Status diperbarui.','success');}else psError(r.error_message);},'json').fail(function(){psError('Status gagal diperbarui.');});});});
$(document).on('click','.btn-ps-cancel',function(){var id=$(this).data('id');Swal.fire({title:'Cancel Production Schedule',input:'text',inputLabel:'Alasan cancel',showCancelButton:true,confirmButtonText:'Cancel Schedule'}).then(function(x){if(!x.isConfirmed)return;$.post('<?=base_admin();?>modul/production_schedule/production_schedule_action.php?act=cancel',{id:id,reason:x.value||''},function(r){if(r.status==='good'){dt_ps.draw(false);Swal.fire(<?=prod_js('common_success', 'Success');?>,'Schedule dibatalkan.','success');}else psError(r.error_message);},'json').fail(function(){psError(<?=prod_js('production_cancel_process_failed', 'Cancel failed to process.');?>);});});});$('.hide_alert_notif').click(function(){$('.error_data_delete').hide();});
});
</script>
