<?php
if (!function_exists('prod_t')) {
  function prod_t($key, $fallback = '') { return lang_text($key, $fallback); }
}
if (!function_exists('prod_h')) {
  function prod_h($key, $fallback = '') { return htmlspecialchars((string) prod_t($key, $fallback), ENT_QUOTES, 'UTF-8'); }
}
if (!function_exists('prod_js')) {
  function prod_js($key, $fallback = '') { return json_encode(prod_t($key, $fallback), JSON_HEX_TAG | JSON_HEX_APOS | JSON_HEX_AMP | JSON_HEX_QUOT); }
}
if(session_status()===PHP_SESSION_NONE)session_start();
include "../../inc/config.php";
session_check_json();
error_reporting(E_ALL & ~E_NOTICE & ~E_WARNING & ~E_DEPRECATED & ~E_USER_DEPRECATED);
function ps_json($s,$m='',$x=array()){header('Content-Type: application/json');$p=array('status'=>$s);if($m!=='')$p['error_message']=$m;foreach($x as $k=>$v)$p[$k]=$v;echo json_encode($p);exit;}
function ps_h($v){return htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');}
function ps_num($v,$d=5){return number_format((float)$v,$d,',','.');}
function ps_dt($v){$v=trim((string)$v);if($v==='')return null;return str_replace('T',' ',$v).(strlen($v)===16?':00':'');}
function ps_next_no($date){global $db;$prefix='PSC'.date('Ym',strtotime($date));$r=$db->fetch("SELECT schedule_no FROM erp_production_schedule WHERE schedule_no LIKE ? ORDER BY schedule_no DESC LIMIT 1",array($prefix.'%'));$n=1;if($r&&preg_match('/(\d{5})$/',$r->schedule_no,$m))$n=(int)$m[1]+1;return $prefix.sprintf('%05d',$n);}
function ps_hist($id,$old,$new,$rem,$user){global $db;$db->insert('erp_production_schedule_history',array('schedule_id'=>$id,'status_lama'=>$old,'status_baru'=>$new,'remarks'=>$rem,'changed_by'=>$user));}
$act=isset($_GET['act'])?$_GET['act']:'';$username=isset($_SESSION['username'])?$_SESSION['username']:'system';
switch($act){
  case 'production_search':
    $term=isset($_POST['term'])?trim($_POST['term']):'';$like='%'.$term.'%';
    $rows=$db->query("SELECT p.id_production_order,p.no_production_order,p.material_code,p.material_name,p.order_qty,p.uom,p.plant,p.start_date,p.finish_date,p.priority,p.status,COUNT(o.id_operation) op_count
      FROM production_order p LEFT JOIN production_order_operation o ON o.id_production_order=p.id_production_order
      WHERE p.status IN ('RELEASED','IN_PROCESS') AND (?='' OR p.no_production_order LIKE ? OR p.material_code LIKE ? OR p.material_name LIKE ?)
      GROUP BY p.id_production_order ORDER BY p.start_date,p.id_production_order DESC LIMIT 30",array($term,$like,$like,$like));
    $res=array();foreach($rows as $r)$res[]=array('id'=>$r->id_production_order,'text'=>$r->no_production_order.' | '.$r->material_code.' - '.$r->material_name.' | Qty '.ps_num($r->order_qty).' '.$r->uom.' | '.$r->op_count.' op','start_date'=>$r->start_date,'finish_date'=>$r->finish_date,'plant'=>$r->plant,'priority'=>$r->priority);
    echo json_encode(array('results'=>$res));break;
  case 'operations':
    $pid=isset($_POST['production_id'])?(int)$_POST['production_id']:0;$start=ps_dt(isset($_POST['planned_start'])?$_POST['planned_start']:'');$po=$db->fetch("SELECT * FROM production_order WHERE id_production_order=? LIMIT 1",array($pid));
    if(!$po){echo '<div class="alert alert-warning">Production Order tidak ditemukan.</div>';break;}
    $ops=$db->query("SELECT * FROM production_order_operation WHERE id_production_order=? ORDER BY CAST(operation_no AS UNSIGNED),operation_no,id_operation",array($pid));
    $cursor=$start?strtotime($start):strtotime(($po->start_date?:date('Y-m-d')).' 08:00:00');
    echo '<div class="alert alert-info"><strong>'.ps_h($po->no_production_order).'</strong> | '.ps_h($po->material_code.' - '.$po->material_name).' | Qty '.ps_num($po->order_qty).' '.ps_h($po->uom).'<br><small>Status '.ps_h($po->status).' | Plant '.ps_h($po->plant).' | Schedule '.ps_h($po->start_date.' s/d '.$po->finish_date).'</small></div>';
    echo '<div class="table-responsive ps-op-wrap"><table class="table table-bordered table-condensed ps-op-table"><thead><tr><th>#</th><th>Operation</th><th>Work Center</th><th>Shift</th><th>Start</th><th>Finish</th><th class="text-right">Duration Min</th><th class="text-right">Qty</th><th>Remark</th></tr></thead><tbody>';
    $shifts=$db->query("SELECT id,kode_shift,nama_shift FROM erp_shift WHERE status='Aktif' ORDER BY kode_shift");$shiftOptions='<option value="">-</option>';foreach($shifts as $s)$shiftOptions.='<option value="'.(int)$s->id.'" data-code="'.ps_h($s->kode_shift).'">'.ps_h($s->kode_shift.' - '.$s->nama_shift).'</option>';
    $seq=1;foreach($ops as $o){$dur=max(30,(float)$o->setup_time+(float)$o->machine_time+(float)$o->labor_time);$s=date('Y-m-d\TH:i',$cursor);$cursor+=((int)$dur)*60;$f=date('Y-m-d\TH:i',$cursor);echo '<tr><td>'.(int)$seq.'<input type="hidden" name="op_id[]" value="'.(int)$o->id_operation.'"><input type="hidden" name="sequence_no['.(int)$o->id_operation.']" value="'.(int)$seq.'"></td><td><strong>'.ps_h($o->operation_no).'</strong><br><small>'.ps_h($o->operation_name).'</small></td><td><input name="work_center['.(int)$o->id_operation.']" class="form-control" value="'.ps_h($o->work_center).'"><small>'.ps_h($o->work_center?:'-').'</small></td><td><select name="shift_id['.(int)$o->id_operation.']" class="form-control ps-shift">'.$shiftOptions.'</select></td><td><input type="datetime-local" name="op_start['.(int)$o->id_operation.']" class="form-control ps-op-start" value="'.$s.'"></td><td><input type="datetime-local" name="op_finish['.(int)$o->id_operation.']" class="form-control ps-op-finish" value="'.$f.'"></td><td><input type="number" step="1" name="duration['.(int)$o->id_operation.']" class="form-control text-right" value="'.ps_h($dur).'"></td><td><input type="number" step="0.00001" name="scheduled_qty['.(int)$o->id_operation.']" class="form-control text-right" value="'.ps_h($po->order_qty).'"></td><td><input name="op_remarks['.(int)$o->id_operation.']" class="form-control"></td></tr>';$seq++;}
    if($seq===1)echo '<tr><td colspan="9" class="text-center text-danger">Production Order belum memiliki operation. Lengkapi routing/operation dulu.</td></tr>';
    echo '</tbody></table></div>';break;
  case 'save':
    $pid=isset($_POST['production_id'])?(int)$_POST['production_id']:0;$date=isset($_POST['schedule_date'])?trim($_POST['schedule_date']):'';$start=ps_dt(isset($_POST['planned_start'])?$_POST['planned_start']:'');$finish=ps_dt(isset($_POST['planned_finish'])?$_POST['planned_finish']:'');
    if($pid<=0)ps_json('error','Production Order wajib dipilih.');if($date==='')ps_json('error','Schedule Date wajib diisi.');if(empty($_POST['op_id'])||!is_array($_POST['op_id']))ps_json('error','Minimal satu operation wajib dijadwalkan.');
    $po=$db->fetch("SELECT * FROM production_order WHERE id_production_order=? LIMIT 1",array($pid));if(!$po)ps_json('error','Production Order tidak ditemukan.');if(!in_array($po->status,array('RELEASED','IN_PROCESS'),true))ps_json('error','Production Order harus RELEASED atau IN_PROCESS.');
    $db->query('START TRANSACTION');$no=ps_next_no($date);$status=(isset($_POST['submit'])&&$_POST['submit']==='Y')?'SCHEDULED':'DRAFT';
    $h=array('schedule_no'=>$no,'id_production_order'=>$po->id_production_order,'no_production_order'=>$po->no_production_order,'schedule_date'=>$date,'plant_code'=>$po->plant,'material_code'=>$po->material_code,'material_name'=>$po->material_name,'order_qty'=>$po->order_qty,'uom'=>$po->uom,'planned_start'=>$start,'planned_finish'=>$finish,'dispatch_status'=>$status,'priority'=>$po->priority,'scheduler'=>isset($_POST['scheduler'])?trim($_POST['scheduler']):$username,'remarks'=>isset($_POST['remarks'])?trim($_POST['remarks']):'','created_by'=>$username,'updated_by'=>$username);
    if($status==='SCHEDULED'){$h['released_by']=$username;$h['released_at']=date('Y-m-d H:i:s');}
    if(!$db->insert('erp_production_schedule',$h)){$e=$db->getErrorMessage();$db->query('ROLLBACK');ps_json('error',$e?:'Header Production Schedule gagal disimpan.');}
    $sid=$db->last_insert_id();
    foreach($_POST['op_id'] as $opid){$opid=(int)$opid;$op=$db->fetch("SELECT * FROM production_order_operation WHERE id_operation=? AND id_production_order=? LIMIT 1",array($opid,$pid));if(!$op){$db->query('ROLLBACK');ps_json('error','Operation tidak valid.');}
      $shiftId=isset($_POST['shift_id'][$opid])?(int)$_POST['shift_id'][$opid]:0;$shift=$shiftId?$db->fetch("SELECT kode_shift FROM erp_shift WHERE id=? LIMIT 1",array($shiftId)):null;$wc=isset($_POST['work_center'][$opid])?trim($_POST['work_center'][$opid]):$op->work_center;
      $d=array('schedule_id'=>$sid,'id_operation'=>$opid,'operation_no'=>$op->operation_no,'operation_name'=>$op->operation_name,'work_center'=>$wc,'work_center_name'=>$op->work_center,'shift_id'=>$shiftId?:null,'shift_code'=>$shift?$shift->kode_shift:null,'planned_start'=>ps_dt($_POST['op_start'][$opid]),'planned_finish'=>ps_dt($_POST['op_finish'][$opid]),'duration_minutes'=>isset($_POST['duration'][$opid])?(float)$_POST['duration'][$opid]:0,'capacity_qty'=>isset($_POST['scheduled_qty'][$opid])?(float)$_POST['scheduled_qty'][$opid]:0,'scheduled_qty'=>isset($_POST['scheduled_qty'][$opid])?(float)$_POST['scheduled_qty'][$opid]:0,'sequence_no'=>isset($_POST['sequence_no'][$opid])?(int)$_POST['sequence_no'][$opid]:0,'operation_status'=>$status==='SCHEDULED'?'READY':'OPEN','remarks'=>isset($_POST['op_remarks'][$opid])?trim($_POST['op_remarks'][$opid]):'');
      if(!$db->insert('erp_production_schedule_detail',$d)){$e=$db->getErrorMessage();$db->query('ROLLBACK');ps_json('error',$e?:'Detail Production Schedule gagal disimpan.');}
    }
    ps_hist($sid,null,$status,$status==='SCHEDULED'?'Save and schedule':'Save draft',$username);simpan_log('User '.$username.' membuat Production Schedule '.$no.' untuk Production Order '.$po->no_production_order.' pada '.date('Y-m-d H:i:s'),$username);$db->query('COMMIT');ps_json('good','',array('schedule_no'=>$no));break;
  case 'schedule': case 'dispatch':
    $id=isset($_POST['id'])?(int)$_POST['id']:0;$h=$db->fetch("SELECT * FROM erp_production_schedule WHERE id=? LIMIT 1",array($id));if(!$h)ps_json('error','Production Schedule tidak ditemukan.');$old=$h->dispatch_status;$new=$old;
    if($act==='schedule'){if($old!=='DRAFT')ps_json('error','Hanya DRAFT yang bisa dijadwalkan.');$new='SCHEDULED';$db->query("UPDATE erp_production_schedule_detail SET operation_status='READY' WHERE schedule_id=?",array($id));}
    if($act==='dispatch'){if($old!=='SCHEDULED')ps_json('error','Hanya SCHEDULED yang bisa dispatch.');$new='DISPATCHED';$db->query("UPDATE erp_production_schedule_detail SET operation_status='DISPATCHED' WHERE schedule_id=?",array($id));}
    $db->update('erp_production_schedule',array('dispatch_status'=>$new,'released_by'=>$username,'released_at'=>date('Y-m-d H:i:s'),'updated_by'=>$username),'id',$id);ps_hist($id,$old,$new,$act,$username);simpan_log('User '.$username.' mengubah Production Schedule '.$h->schedule_no.' dari '.$old.' menjadi '.$new.' pada '.date('Y-m-d H:i:s'),$username);ps_json('good');break;
  case 'cancel':
    $id=isset($_POST['id'])?(int)$_POST['id']:0;$reason=isset($_POST['reason'])?trim($_POST['reason']):'';$h=$db->fetch("SELECT * FROM erp_production_schedule WHERE id=? LIMIT 1",array($id));if(!$h)ps_json('error','Production Schedule tidak ditemukan.');if(!in_array($h->dispatch_status,array('DRAFT','SCHEDULED'),true))ps_json('error','Schedule ini tidak bisa dibatalkan.');
    $db->update('erp_production_schedule',array('dispatch_status'=>'CANCELLED','cancelled_by'=>$username,'cancelled_at'=>date('Y-m-d H:i:s'),'cancel_reason'=>$reason,'updated_by'=>$username),'id',$id);$db->query("UPDATE erp_production_schedule_detail SET operation_status='CANCELLED' WHERE schedule_id=?",array($id));ps_hist($id,$h->dispatch_status,'CANCELLED',$reason,$username);simpan_log('User '.$username.' membatalkan Production Schedule '.$h->schedule_no.' pada '.date('Y-m-d H:i:s'),$username);ps_json('good');break;
  case 'detail':
    $id=isset($_POST['id'])?(int)$_POST['id']:0;$h=$db->fetch("SELECT * FROM erp_production_schedule WHERE id=? LIMIT 1",array($id));if(!$h){echo '<div class="alert alert-warning">Data tidak ditemukan.</div>';break;}$ds=$db->query("SELECT * FROM erp_production_schedule_detail WHERE schedule_id=? ORDER BY sequence_no,id",array($id));$hs=$db->query("SELECT * FROM erp_production_schedule_history WHERE schedule_id=? ORDER BY changed_at,id",array($id));
    echo '<h3 style="margin-top:0">'.ps_h($h->schedule_no).' <small>'.ps_h($h->dispatch_status).'</small></h3><div class="row"><div class="col-sm-3"><strong>Production Order</strong><br>'.ps_h($h->no_production_order).'</div><div class="col-sm-4"><strong>Material</strong><br>'.ps_h($h->material_code.' - '.$h->material_name).'</div><div class="col-sm-2"><strong>Qty</strong><br>'.ps_num($h->order_qty).' '.ps_h($h->uom).'</div><div class="col-sm-3"><strong>Plan</strong><br>'.ps_h($h->planned_start.' s/d '.$h->planned_finish).'</div></div><hr><h4>Operation Dispatch</h4><table class="table table-bordered table-condensed"><thead><tr class="bg-gray"><th>Seq</th><th>Operation</th><th>Work Center</th><th>Shift</th><th>Start</th><th>Finish</th><th class="text-right">Min</th><th class="text-right">Qty</th><th>Status</th></tr></thead><tbody>';
    foreach($ds as $d)echo '<tr><td>'.(int)$d->sequence_no.'</td><td><strong>'.ps_h($d->operation_no).'</strong><br><small>'.ps_h($d->operation_name).'</small></td><td>'.ps_h($d->work_center).'</td><td>'.ps_h($d->shift_code?:'-').'</td><td>'.ps_h($d->planned_start).'</td><td>'.ps_h($d->planned_finish).'</td><td class="text-right">'.ps_num($d->duration_minutes,0).'</td><td class="text-right">'.ps_num($d->scheduled_qty).'</td><td>'.ps_h($d->operation_status).'</td></tr>';
    echo '</tbody></table><h4>History</h4><table class="table table-bordered table-condensed"><thead><tr class="bg-gray"><th>Time</th><th>From</th><th>To</th><th>User</th><th>Remarks</th></tr></thead><tbody>';foreach($hs as $x)echo '<tr><td>'.ps_h($x->changed_at).'</td><td>'.ps_h($x->status_lama?:'-').'</td><td>'.ps_h($x->status_baru).'</td><td>'.ps_h($x->changed_by).'</td><td>'.ps_h($x->remarks).'</td></tr>';echo '</tbody></table>';break;
  case 'excel':
    $initial=ob_get_level();ob_start();require_once "../../inc/lib/PHPExcel.php";require_once "../../inc/excel_style_helper.php";PHPExcel_Shared_File::setUseUploadTempDirectory(true);$from=isset($_GET['tgl_awal'])?$_GET['tgl_awal']:date('Y-m-01');$to=isset($_GET['tgl_akhir'])?$_GET['tgl_akhir']:date('Y-m-d');$status=isset($_GET['status'])?trim($_GET['status']):'';$p=array($from,$to);$w=" WHERE h.schedule_date BETWEEN ? AND ? ";if($status!==''){$w.=" AND h.dispatch_status=? ";$p[]=$status;}
    $rows=$db->query("SELECT h.*,COUNT(d.id) op_count,SUM(d.duration_minutes) total_min FROM erp_production_schedule h LEFT JOIN erp_production_schedule_detail d ON d.schedule_id=h.id $w GROUP BY h.id ORDER BY h.schedule_date,h.id",$p);$excel=new PHPExcel();$sh=$excel->setActiveSheetIndex(0);$sh->setTitle(erp_export_sheet_title('Prod Schedule'));$heads=array(erp_export_label("No"),erp_export_label("Schedule No"),erp_export_label("Production Order"),erp_export_label("Date"),erp_export_label("Plant"),erp_export_label("Material"),erp_export_label("Qty"),erp_export_label("UOM"),erp_export_label("Start"),erp_export_label("Finish"),erp_export_label("Operations"),erp_export_label("Duration Min"),erp_export_label("Priority"),erp_export_label("Status"),erp_export_label("Scheduler"));foreach($heads as $i=>$v)$sh->setCellValue(PHPExcel_Cell::stringFromColumnIndex($i).'4',$v);$r=5;$n=1;foreach($rows as $row){$vals=array($n++,$row->schedule_no,$row->no_production_order,$row->schedule_date,$row->plant_code,$row->material_code.' - '.$row->material_name,(float)$row->order_qty,$row->uom,$row->planned_start,$row->planned_finish,(int)$row->op_count,(float)$row->total_min,$row->priority,$row->dispatch_status,$row->scheduler);foreach($vals as $i=>$v)$sh->setCellValue(PHPExcel_Cell::stringFromColumnIndex($i).$r,$v);$r++;}
    erpkb_excel_apply_standard_style($excel,array('sheet'=>$sh,'title'=>erp_export_title('PRODUCTION SCHEDULE'),'header_row'=>4,'first_data_row'=>5,'last_data_row'=>max(5,$r-1),'column_count'=>15,'numeric_columns'=>array('G'),'decimal_columns'=>array('L'),'filters'=>array('Schedule Date'=>$from.' s/d '.$to,'Status'=>$status?:erp_export_all_text())));$tmp=erpkb_excel_temp_file('production_schedule_');PHPExcel_IOFactory::createWriter($excel,'Excel2007')->save($tmp);$size=@filesize($tmp);$sig=@file_get_contents($tmp,false,null,0,2);if(!$size||$sig!=='PK'){@unlink($tmp);while(ob_get_level()>$initial)ob_end_clean();header('Content-Type:text/plain; charset=utf-8');echo erp_t('export_excel_invalid_file','File Excel gagal dibuat dengan benar.');exit;}while(ob_get_level()>$initial)ob_end_clean();header('Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');header('Content-Disposition: attachment; filename="production_schedule_'.date('Ymd_His').'.xlsx"');header('Content-Length: '.$size);header('Cache-Control: max-age=0');header('Pragma: public');readfile($tmp);@unlink($tmp);exit;
  default:ps_json('error','Action tidak dikenal.');
}
?>
