<?php
if (!function_exists('hr_t')) {
  function hr_t($key, $fallback = '') { return lang_text($key, $fallback); }
}
if (!function_exists('hr_h')) {
  function hr_h($key, $fallback = '') { return htmlspecialchars((string) hr_t($key, $fallback), ENT_QUOTES, 'UTF-8'); }
}
if (!function_exists('hr_js')) {
  function hr_js($key, $fallback = '') { return json_encode(hr_t($key, $fallback), JSON_HEX_TAG | JSON_HEX_APOS | JSON_HEX_AMP | JSON_HEX_QUOT); }
}
if (session_status() === PHP_SESSION_NONE) session_start();
include "../../inc/config.php";
session_check_json();
function cfd_h($v){return htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');}
function cfd_label($s){$map=array('DRAFT'=>'default','ACTIVE'=>'success','EXPIRING'=>'warning','EXPIRED'=>'danger','SUSPENDED'=>'warning','REVOKED'=>'danger','RENEWED'=>'primary','COMPLIANT'=>'success','WARNING'=>'warning','NON_COMPLIANT'=>'danger','NOT_REQUIRED'=>'default');$c=isset($map[$s])?$map[$s]:'default';return '<span class="label label-'.$c.'">'.cfd_h($s).'</span>';}
function cfd_filters(){return array('from'=>isset($_POST['tgl_awal'])&&$_POST['tgl_awal']!==''?$_POST['tgl_awal']:date('Y-01-01'),'to'=>isset($_POST['tgl_akhir'])&&$_POST['tgl_akhir']!==''?$_POST['tgl_akhir']:date('Y-12-31'),'certification_type'=>isset($_POST['certification_type'])?trim($_POST['certification_type']):'','certification_status'=>isset($_POST['certification_status'])?trim($_POST['certification_status']):'','compliance_status'=>isset($_POST['compliance_status'])?trim($_POST['compliance_status']):'','department_code'=>isset($_POST['department_code'])?trim($_POST['department_code']):'','expiring_days'=>isset($_POST['expiring_days'])?trim($_POST['expiring_days']):'','keyword'=>isset($_POST['keyword'])?trim($_POST['keyword']):'');}
function cfd_where($f,&$p){$w=" WHERE cf.issue_date BETWEEN ? AND ? ";$p[]=$f['from'];$p[]=$f['to'];foreach(array('certification_type','certification_status','compliance_status') as $k){if($f[$k]!==''){$w.=" AND cf.$k=? ";$p[]=$f[$k];}}if($f['department_code']!==''){$w.=" AND e.department_code=? ";$p[]=$f['department_code'];}if($f['expiring_days']!==''){$w.=" AND cf.valid_until IS NOT NULL AND cf.valid_until BETWEEN CURDATE() AND DATE_ADD(CURDATE(), INTERVAL ? DAY) ";$p[]=(int)$f['expiring_days'];}if($f['keyword']!==''){$kw='%'.$f['keyword'].'%';$w.=" AND (cf.certification_no LIKE ? OR cf.certificate_no LIKE ? OR cf.certification_name LIKE ? OR cf.issuing_body LIKE ? OR e.employee_no LIKE ? OR e.full_name LIKE ? OR tc.training_code LIKE ? OR tc.training_name LIKE ?) ";for($i=0;$i<8;$i++)$p[]=$kw;}return $w;}
$draw=isset($_POST['draw'])?(int)$_POST['draw']:1;$start=isset($_POST['start'])?max(0,(int)$_POST['start']):0;$length=isset($_POST['length'])?(int)$_POST['length']:25;if($length<=0||$length>500)$length=25;
$f=cfd_filters();$p=array();$w=cfd_where($f,$p);
$join=" FROM erp_certification cf JOIN erp_training_result trr ON trr.id=cf.training_result_id JOIN erp_training_registration reg ON reg.id=trr.training_registration_id JOIN erp_training_plan tp ON tp.id=reg.training_plan_id JOIN erp_training_catalog tc ON tc.id=tp.training_catalog_id JOIN erp_employee_master e ON e.id=cf.employee_id LEFT JOIN dept d ON d.kd_dept=e.department_code LEFT JOIN erp_job_title jt ON jt.id=e.job_title_id ";
$kpi=$db->fetch("SELECT COUNT(*) total,SUM(CASE WHEN cf.certification_status='ACTIVE' THEN 1 ELSE 0 END) active,SUM(CASE WHEN cf.valid_until BETWEEN CURDATE() AND DATE_ADD(CURDATE(), INTERVAL 30 DAY) THEN 1 ELSE 0 END) expiring,SUM(CASE WHEN cf.certification_status='EXPIRED' OR (cf.valid_until IS NOT NULL AND cf.valid_until<CURDATE()) THEN 1 ELSE 0 END) expired,SUM(CASE WHEN cf.compliance_status='COMPLIANT' THEN 1 ELSE 0 END) compliant,SUM(CASE WHEN cf.renewal_required='Y' THEN 1 ELSE 0 END) renewal $join");
$cnt=$db->fetch("SELECT COUNT(*) jml $join $w",$p);$total=$cnt?(int)$cnt->jml:0;
$orderMap=array(2=>'cf.certification_no',3=>'e.employee_no',4=>'tc.training_name',5=>'cf.certification_type',6=>'cf.issue_date',7=>'cf.valid_until',8=>'cf.certification_status',9=>'cf.compliance_status',10=>'cf.updated_at');$orderBy="cf.valid_until IS NULL, cf.valid_until ASC, cf.certification_no DESC";
if(isset($_POST['order'][0]['column'])){$col=(int)$_POST['order'][0]['column'];$dir=(isset($_POST['order'][0]['dir'])&&strtolower($_POST['order'][0]['dir'])==='desc')?'DESC':'ASC';if(isset($orderMap[$col]))$orderBy=$orderMap[$col].' '.$dir;}
$rows=$db->query("SELECT cf.*,trr.result_no,tc.training_code,tc.training_name,e.employee_no,e.full_name,e.department_code,d.nm_dept,jt.job_title_code,jt.job_title_name $join $w ORDER BY $orderBy LIMIT $start,$length",$p);
$data=array();$no=$start+1;foreach($rows as $r){$act='<div class="cf-action"><button class="btn btn-info btn-xs btn-cf-detail" data-id="'.(int)$r->id.'"><i class="fa fa-eye"></i></button> <button class="btn btn-primary btn-xs btn-cf-edit" data-id="'.(int)$r->id.'"><i class="fa fa-pencil"></i></button> <button class="btn btn-warning btn-xs btn-cf-renew" data-id="'.(int)$r->id.'"><i class="fa fa-refresh"></i></button> <button class="btn btn-danger btn-xs btn-cf-delete" data-id="'.(int)$r->id.'" data-no="'.cfd_h($r->certification_no).'"><i class="fa fa-trash"></i></button></div>';$emp='<strong>'.cfd_h($r->employee_no).'</strong><br><small>'.cfd_h($r->full_name).'</small>';$dept='<strong>'.cfd_h($r->department_code).'</strong> - '.cfd_h($r->nm_dept).'<br><small>'.cfd_h($r->job_title_code.' - '.$r->job_title_name).'</small>';$valid=cfd_h($r->valid_from.' s/d '.($r->valid_until?:'No Expiry'));$data[]=array($no++,$act,'<strong>'.cfd_h($r->certification_no).'</strong><br><small>Cert: '.cfd_h($r->certificate_no?:'-').'</small>',$emp,$dept,'<strong>'.cfd_h($r->training_code).'</strong><br><small>'.cfd_h($r->certification_name).'</small>','<span class="cf-pill">'.cfd_h($r->certification_type).'</span><br><small>'.cfd_h($r->issuing_body?:'-').'</small>',cfd_h($r->issue_date).'<br><small>'.$valid.'</small>',cfd_label($r->certification_status).'<br><small>Renewal: '.cfd_h($r->renewal_required).'</small>',cfd_label($r->compliance_status),cfd_h(($r->updated_by?:$r->created_by?:'-')).'<br><small>'.cfd_h($r->updated_at?:$r->created_at).'</small>');}
header('Content-Type: application/json; charset=utf-8');echo json_encode(array('draw'=>$draw,'recordsTotal'=>$total,'recordsFiltered'=>$total,'data'=>$data,'kpi'=>array('total'=>$kpi?(int)$kpi->total:0,'active'=>$kpi?(int)$kpi->active:0,'expiring'=>$kpi?(int)$kpi->expiring:0,'expired'=>$kpi?(int)$kpi->expired:0,'compliant'=>$kpi?(int)$kpi->compliant:0,'renewal'=>$kpi?(int)$kpi->renewal:0)));
?>
