<?php
if (!function_exists('hr_t')) {
  function hr_t($key, $fallback = '') { return lang_text($key, $fallback); }
}
if (!function_exists('hr_h')) {
  function hr_h($key, $fallback = '') { return htmlspecialchars((string) hr_t($key, $fallback), ENT_QUOTES, 'UTF-8'); }
}
if (!function_exists('hr_js')) {
  function hr_js($key, $fallback = '') { return json_encode(hr_t($key, $fallback), JSON_HEX_TAG | JSON_HEX_APOS | JSON_HEX_AMP | JSON_HEX_QUOT); }
}
if (session_status() === PHP_SESSION_NONE) session_start();
include "../../inc/config.php";
session_check_json();
function cf_json($s,$m='',$x=array()){header('Content-Type: application/json; charset=utf-8');$p=array('status'=>$s);if($m!=='')$p[$s==='good'?'message':'error_message']=$m;foreach($x as $k=>$v)$p[$k]=$v;echo json_encode($p);exit;}
function cf_h($v){return htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');}
function cf_p($k,$d=''){return isset($_POST[$k])?$_POST[$k]:$d;} function cf_g($k,$d=''){return isset($_GET[$k])?$_GET[$k]:$d;}
function cf_code($v){return strtoupper(trim((string)$v));}
function cf_in($v,$a){return in_array($v,$a,true);}
function cf_select2($rows,$id,$cb){$out=array();foreach($rows as $r)$out[]=array('id'=>$r->$id,'text'=>$cb($r));header('Content-Type: application/json; charset=utf-8');echo json_encode(array('results'=>$out));exit;}
function cf_next_no(){global $db;$prefix='CRT-'.date('Y').'-';$r=$db->fetch("SELECT certification_no FROM erp_certification WHERE certification_no LIKE ? ORDER BY certification_no DESC LIMIT 1",array($prefix.'%'));$n=1;if($r&&preg_match('/(\d+)$/',$r->certification_no,$m))$n=(int)$m[1]+1;return $prefix.str_pad($n,4,'0',STR_PAD_LEFT);}
function cf_row($id){global $db;return $db->fetch("SELECT cf.*,trr.result_no,tc.training_code,tc.training_name,e.employee_no,e.full_name,e.department_code,d.nm_dept,jt.job_title_code,jt.job_title_name FROM erp_certification cf JOIN erp_training_result trr ON trr.id=cf.training_result_id JOIN erp_training_registration reg ON reg.id=trr.training_registration_id JOIN erp_training_plan tp ON tp.id=reg.training_plan_id JOIN erp_training_catalog tc ON tc.id=tp.training_catalog_id JOIN erp_employee_master e ON e.id=cf.employee_id LEFT JOIN dept d ON d.kd_dept=e.department_code LEFT JOIN erp_job_title jt ON jt.id=e.job_title_id WHERE cf.id=? LIMIT 1",array((int)$id));}
function cf_payload($r){$d=(array)$r;$d['result_text']=$r->result_no.' - '.$r->employee_no.' '.$r->full_name.' ['.$r->training_code.' - '.$r->training_name.']';return $d;}
function cf_filters_where($src,&$p){$from=isset($src['tgl_awal'])&&$src['tgl_awal']!==''?$src['tgl_awal']:date('Y-01-01');$to=isset($src['tgl_akhir'])&&$src['tgl_akhir']!==''?$src['tgl_akhir']:date('Y-12-31');$w=" WHERE cf.issue_date BETWEEN ? AND ? ";$p[]=$from;$p[]=$to;foreach(array('certification_type','certification_status','compliance_status') as $k){if(isset($src[$k])&&$src[$k]!==''){$w.=" AND cf.$k=? ";$p[]=trim($src[$k]);}}if(isset($src['department_code'])&&$src['department_code']!==''){$w.=" AND e.department_code=? ";$p[]=trim($src['department_code']);}if(isset($src['expiring_days'])&&$src['expiring_days']!==''){$w.=" AND cf.valid_until IS NOT NULL AND cf.valid_until BETWEEN CURDATE() AND DATE_ADD(CURDATE(), INTERVAL ? DAY) ";$p[]=(int)$src['expiring_days'];}if(isset($src['keyword'])&&$src['keyword']!==''){$kw='%'.trim($src['keyword']).'%';$w.=" AND (cf.certification_no LIKE ? OR cf.certificate_no LIKE ? OR cf.certification_name LIKE ? OR cf.issuing_body LIKE ? OR e.employee_no LIKE ? OR e.full_name LIKE ? OR tc.training_code LIKE ? OR tc.training_name LIKE ?) ";for($i=0;$i<8;$i++)$p[]=$kw;}return $w;}
$act=isset($_GET['act'])?$_GET['act']:'';$username=isset($_SESSION['username'])?$_SESSION['username']:'system';
$types=array('INTERNAL','EXTERNAL','REGULATORY','PROFESSIONAL','SAFETY','QUALITY','CUSTOMS','OTHER');$statuses=array('DRAFT','ACTIVE','EXPIRING','EXPIRED','SUSPENDED','REVOKED','RENEWED');$compliances=array('COMPLIANT','WARNING','NON_COMPLIANT','NOT_REQUIRED');$yn=array('Y','N');
switch($act){
case 'next_no':cf_json('good','',array('code'=>cf_next_no()));break;
case 'result_search':$t=trim(cf_p('term'));$like='%'.$t.'%';$rows=$db->query("SELECT trr.id,trr.result_no,tc.training_code,tc.training_name,e.employee_no,e.full_name FROM erp_training_result trr JOIN erp_training_registration reg ON reg.id=trr.training_registration_id JOIN erp_training_plan tp ON tp.id=reg.training_plan_id JOIN erp_training_catalog tc ON tc.id=tp.training_catalog_id JOIN erp_employee_master e ON e.id=reg.employee_id WHERE trr.result_status='PASSED' AND trr.completion_status='COMPLETED' AND NOT EXISTS (SELECT 1 FROM erp_certification c WHERE c.training_result_id=trr.id) AND (?='' OR trr.result_no LIKE ? OR tc.training_name LIKE ? OR e.employee_no LIKE ? OR e.full_name LIKE ?) ORDER BY trr.result_date DESC LIMIT 80",array($t,$like,$like,$like,$like));cf_select2($rows,'id',function($r){return $r->result_no.' - '.$r->employee_no.' '.$r->full_name.' ['.$r->training_code.' - '.$r->training_name.']';});break;
case 'department_search':$t=trim(cf_p('term'));$like='%'.$t.'%';$rows=$db->query("SELECT kd_dept,nm_dept,dept_type FROM dept WHERE status='ACTIVE' AND (?='' OR kd_dept LIKE ? OR nm_dept LIKE ? OR dept_type LIKE ?) ORDER BY kd_dept LIMIT 50",array($t,$like,$like,$like));cf_select2($rows,'kd_dept',function($r){return $r->kd_dept.' - '.$r->nm_dept.' ['.$r->dept_type.']';});break;
case 'get':$r=cf_row((int)cf_p('id'));if(!$r)cf_json('error','Certification tidak ditemukan.');cf_json('good','',array('data'=>cf_payload($r)));break;
case 'save':
  $id=(int)cf_p('id');$no=cf_code(cf_p('certification_no'));if($no==='')$no=cf_next_no();$resultId=(int)cf_p('training_result_id');$type=cf_code(cf_p('certification_type','INTERNAL'));$name=trim(cf_p('certification_name'));$issue=trim(cf_p('issue_date'));$from=trim(cf_p('valid_from'));$until=trim(cf_p('valid_until'));$renew=cf_code(cf_p('renewal_required','N'));$status=cf_code(cf_p('certification_status','DRAFT'));$comp=cf_code(cf_p('compliance_status','COMPLIANT'));
  if(!preg_match('/^[A-Z0-9_-]{3,30}$/',$no))cf_json('error','Certification No tidak valid.');
  $res=$db->fetch("SELECT trr.*,reg.employee_id,tc.training_name FROM erp_training_result trr JOIN erp_training_registration reg ON reg.id=trr.training_registration_id JOIN erp_training_plan tp ON tp.id=reg.training_plan_id JOIN erp_training_catalog tc ON tc.id=tp.training_catalog_id WHERE trr.id=? AND trr.result_status='PASSED' AND trr.completion_status='COMPLETED' LIMIT 1",array($resultId));if(!$res)cf_json('error','Training Result wajib PASSED dan COMPLETED.');
  if($name==='')$name=$res->training_name;if($issue===''||$from==='')cf_json('error','Issue Date dan Valid From wajib diisi.');
  if($until!=='' && strtotime($until)<strtotime($from))cf_json('error','Valid Until tidak boleh sebelum Valid From.');
  if(!cf_in($type,$types)||!cf_in($renew,$yn)||!cf_in($status,$statuses)||!cf_in($comp,$compliances))cf_json('error','Status/type tidak valid.');
  $dup=$db->fetch("SELECT id FROM erp_certification WHERE certification_no=? AND id<>? LIMIT 1",array($no,$id));if($dup)cf_json('error','Certification No sudah digunakan.');
  $dupRes=$db->fetch("SELECT id FROM erp_certification WHERE training_result_id=? AND id<>? LIMIT 1",array($resultId,$id));if($dupRes)cf_json('error','Training Result ini sudah memiliki certification.');
  $data=array('certification_no'=>$no,'training_result_id'=>$resultId,'employee_id'=>$res->employee_id,'certification_type'=>$type,'certification_name'=>$name,'issuing_body'=>trim(cf_p('issuing_body')),'issue_date'=>$issue,'valid_from'=>$from,'valid_until'=>$until?:null,'renewal_required'=>$renew,'renewal_alert_days'=>max(0,(int)cf_p('renewal_alert_days',30)),'certification_status'=>$status,'compliance_status'=>$comp,'certificate_no'=>trim(cf_p('certificate_no')),'certificate_file_ref'=>trim(cf_p('certificate_file_ref')),'score'=>cf_p('score')!==''?(float)cf_p('score'):$res->final_score,'remarks'=>trim(cf_p('remarks')),'updated_by'=>$username,'updated_at'=>date('Y-m-d H:i:s'));
  if($id>0){$ok=$db->update('erp_certification',$data,'id',$id);}else{$data['created_by']=$username;$ok=$db->insert('erp_certification',$data);$id=$db->last_insert_id();}
  if(!$ok)cf_json('error',$db->getErrorMessage()?:'Certification gagal disimpan.');
  $db->update('erp_training_result',array('certificate_issued'=>'Y','certificate_no'=>$data['certificate_no'],'certificate_date'=>$issue,'certificate_valid_until'=>$until?:null,'updated_by'=>$username,'updated_at'=>date('Y-m-d H:i:s')),'id',$resultId);
  if(function_exists('simpan_log'))simpan_log('User '.$username.' menyimpan Certification '.$no.' pada '.date('Y-m-d H:i:s'),$username);
  cf_json('good','Certification berhasil disimpan.',array('id'=>$id));break;
case 'renew':$id=(int)cf_p('id');$r=$db->fetch("SELECT * FROM erp_certification WHERE id=? LIMIT 1",array($id));if(!$r)cf_json('error','Certification tidak ditemukan.');$newUntil=$r->valid_until?date('Y-m-d',strtotime($r->valid_until.' +1 year')):date('Y-m-d',strtotime('+1 year'));$ok=$db->update('erp_certification',array('certification_status'=>'RENEWED','compliance_status'=>'COMPLIANT','valid_until'=>$newUntil,'updated_by'=>$username,'updated_at'=>date('Y-m-d H:i:s')),'id',$id);if(!$ok)cf_json('error',$db->getErrorMessage()?:'Renew gagal.');cf_json('good','Certification berhasil direnew.');break;
case 'delete':$id=(int)cf_p('id');$r=$db->fetch("SELECT * FROM erp_certification WHERE id=? LIMIT 1",array($id));if(!$r)cf_json('error','Certification tidak ditemukan.');if($r->certification_status==='ACTIVE')cf_json('error','Certification ACTIVE tidak boleh dihapus. Ubah status dahulu.');$db->delete('erp_certification','id',$id);if($db->getErrorMessage())cf_json('error',$db->getErrorMessage());cf_json('good','Certification berhasil dihapus.');break;
case 'detail':$r=cf_row((int)cf_p('id'));if(!$r){echo '<div class="alert alert-warning">Certification tidak ditemukan.</div>';break;}echo '<h3 style="margin-top:0">'.cf_h($r->certification_no).' <small>'.cf_h($r->employee_no.' - '.$r->full_name).'</small></h3><span class="label label-success">'.cf_h($r->certification_status).'</span> <span class="label label-info">'.cf_h($r->compliance_status).'</span><hr><div class="row"><div class="col-sm-3"><b>'.hr_h('hr_certification', 'Certification').'</b><br>'.cf_h($r->certification_name).'</div><div class="col-sm-3"><b>'.hr_h('hr_training_result', 'Training Result').'</b><br>'.cf_h($r->result_no).'</div><div class="col-sm-3"><b>Issuing Body</b><br>'.cf_h($r->issuing_body?:'-').'</div><div class="col-sm-3"><b>Validity</b><br>'.cf_h($r->valid_from.' s/d '.($r->valid_until?:'No Expiry')).'</div></div><hr><b>'.hr_h('common_remarks', 'Remarks').'</b><p>'.nl2br(cf_h($r->remarks?:'-')).'</p>';break;
case 'export':
  $initial=ob_get_level();ob_start();error_reporting(E_ALL & ~E_NOTICE & ~E_WARNING & ~E_DEPRECATED & ~E_USER_DEPRECATED);require_once "../../inc/lib/PHPExcel.php";require_once "../../inc/excel_style_helper.php";PHPExcel_Shared_File::setUseUploadTempDirectory(true);$p=array();$w=cf_filters_where($_GET,$p);$join=" FROM erp_certification cf JOIN erp_training_result trr ON trr.id=cf.training_result_id JOIN erp_training_registration reg ON reg.id=trr.training_registration_id JOIN erp_training_plan tp ON tp.id=reg.training_plan_id JOIN erp_training_catalog tc ON tc.id=tp.training_catalog_id JOIN erp_employee_master e ON e.id=cf.employee_id LEFT JOIN dept d ON d.kd_dept=e.department_code LEFT JOIN erp_job_title jt ON jt.id=e.job_title_id ";$rows=$db->query("SELECT cf.*,trr.result_no,tc.training_code,tc.training_name,e.employee_no,e.full_name,e.department_code,d.nm_dept,jt.job_title_code,jt.job_title_name $join $w ORDER BY cf.valid_until,cf.certification_no",$p);
  $excel=new PHPExcel();$sheet=$excel->setActiveSheetIndex(0);$sheet->setTitle(erp_export_sheet_title('Certification'));$heads=array(erp_export_label("No"),erp_export_label("Certification No"),erp_export_label("Certificate No"),erp_export_label("Employee No"),erp_export_label("Employee Name"),erp_export_label("Department"),erp_export_label("Job Title"),erp_export_label("Training Code"),erp_export_label("Certification Name"),erp_export_label("Type"),erp_export_label("Issuing Body"),erp_export_label("Issue Date"),erp_export_label("Valid From"),erp_export_label("Valid Until"),erp_export_label("Renewal Required"),erp_export_label("Alert Days"),erp_export_label("Certification Status"),erp_export_label("Compliance"),erp_export_label("Score"),erp_export_label("File Ref"),erp_export_label("Remarks"),erp_export_label("Updated By"));foreach($heads as $i=>$h)$sheet->setCellValue(PHPExcel_Cell::stringFromColumnIndex($i).'4',$h);$rn=5;$n=1;foreach($rows as $r){$vals=array($n++,$r->certification_no,$r->certificate_no,$r->employee_no,$r->full_name,$r->department_code.' - '.$r->nm_dept,$r->job_title_code.' - '.$r->job_title_name,$r->training_code,$r->certification_name,$r->certification_type,$r->issuing_body,$r->issue_date,$r->valid_from,$r->valid_until,$r->renewal_required,$r->renewal_alert_days,$r->certification_status,$r->compliance_status,$r->score,$r->certificate_file_ref,$r->remarks,$r->updated_by?:$r->created_by);foreach($vals as $i=>$v)$sheet->setCellValue(PHPExcel_Cell::stringFromColumnIndex($i).$rn,$v);$rn++;}
  erpkb_excel_apply_standard_style($excel,array('sheet'=>$sheet,'title'=>erp_export_title('CERTIFICATION REGISTER'),'header_row'=>4,'first_data_row'=>5,'last_data_row'=>max(5,$rn-1),'column_count'=>count($heads),'filters'=>array('Issue Period'=>array(cf_g('tgl_awal',date('Y-01-01')),cf_g('tgl_akhir',date('Y-12-31'))),'Status'=>cf_g('certification_status',''),'Compliance'=>cf_g('compliance_status','')),'decimal_columns'=>array('S'),'widths'=>array('B'=>20,'C'=>20,'E'=>28,'F'=>28,'G'=>28,'I'=>34,'K'=>28,'U'=>34)));
  $tmp=erpkb_excel_temp_file('certification_');PHPExcel_IOFactory::createWriter($excel,'Excel2007')->save($tmp);$size=@filesize($tmp);$sig=@file_get_contents($tmp,false,null,0,2);if(!$size||$sig!=='PK'){@unlink($tmp);while(ob_get_level()>$initial)ob_end_clean();echo erp_t('export_excel_invalid_file','File Excel gagal dibuat dengan benar.');exit;}while(ob_get_level()>$initial)ob_end_clean();header('Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');header('Content-Disposition: attachment; filename="certification_'.date('Ymd_His').'.xlsx"');header('Content-Length: '.$size);header('Cache-Control: max-age=0');header('Pragma: public');readfile($tmp);@unlink($tmp);exit;
default:cf_json('error','Action tidak dikenal.');
}
?>
