<?php
if (!function_exists('hr_t')) {
  function hr_t($key, $fallback = '') { return lang_text($key, $fallback); }
}
if (!function_exists('hr_h')) {
  function hr_h($key, $fallback = '') { return htmlspecialchars((string) hr_t($key, $fallback), ENT_QUOTES, 'UTF-8'); }
}
if (!function_exists('hr_js')) {
  function hr_js($key, $fallback = '') { return json_encode(hr_t($key, $fallback), JSON_HEX_TAG | JSON_HEX_APOS | JSON_HEX_AMP | JSON_HEX_QUOT); }
}
$defaultFrom=date('Y-01-01');$defaultTo=date('Y-m-d');$canInsert=isset($role_act['insert_act'])&&$role_act['insert_act']==='Y'; ?>
<style>
.aa-hero{background:linear-gradient(135deg,#4f46e5,#0f766e);color:#fff;border-radius:14px;padding:20px;margin-bottom:18px;box-shadow:0 10px 24px rgba(15,23,42,.16)}.aa-hero h1{margin:0 0 6px;font-size:26px;font-weight:700}.aa-card{border-radius:12px;background:#fff;border:1px solid #e5edf5;box-shadow:0 5px 16px rgba(15,23,42,.05);margin-bottom:14px}.aa-kpi{padding:14px;border-radius:12px;background:#f8fafc;border:1px solid #e5edf5}.aa-kpi b{font-size:22px;display:block}#dtb_appraisal_approval th,#dtb_appraisal_approval td{font-size:12px;vertical-align:middle}.select2-container{width:100%!important}.required-label:after{content:' *';color:#dd4b39}.aa-action{white-space:nowrap;min-width:150px}.aa-score b{font-size:17px;color:#0f766e}.aa-rating{display:inline-block;border-radius:50%;width:34px;height:34px;line-height:34px;text-align:center;color:#fff;font-weight:700}.aa-rating-A{background:#16a34a}.aa-rating-B{background:#2563eb}.aa-rating-C{background:#f59e0b}.aa-rating-D{background:#ea580c}.aa-rating-E{background:#dc2626}#modal_appraisal .modal-body{max-height:calc(100vh - 185px);overflow-y:auto}.aa-section-title{font-weight:700;color:#0f172a;margin:12px 0 8px;border-bottom:1px solid #e5edf5;padding-bottom:6px}.aa-readonly{background:#f8fafc}
</style>
<section class="content-header"><h1><?=hr_h('hr_appraisal_approval', 'Appraisal Approval');?> <small>SAP HCM Performance Management</small></h1><ol class="breadcrumb"><li><a href="<?=base_index();?>"><i class="fa fa-dashboard"></i> <?=hr_h('common_home', 'Home');?></a></li><li>Human Resource</li><li>Performance Management</li><li class="active"><?=hr_h('hr_appraisal_approval', 'Appraisal Approval');?></li></ol></section>
<section class="content">
  <div class="aa-hero"><div class="row"><div class="col-md-8"><h1>Appraisal Approval Workbench</h1><p>Review, approve, return, dan monitor hasil appraisal karyawan berdasarkan cycle, skor, rating, dan department.</p></div><div class="col-md-4 text-right"><?php if($canInsert){ ?><button id="btn_open_aa" class="btn btn-warning"><i class="fa fa-plus"></i> Create Appraisal</button><?php } ?></div></div></div>
  <div class="row"><div class="col-sm-3"><div class="aa-kpi"><span>Total Appraisal</span><b id="kpi_total">0</b></div></div><div class="col-sm-3"><div class="aa-kpi"><span>Submitted</span><b id="kpi_submitted">0</b></div></div><div class="col-sm-3"><div class="aa-kpi"><span>HR Review</span><b id="kpi_hr_review">0</b></div></div><div class="col-sm-3"><div class="aa-kpi"><span>Average Score</span><b id="kpi_avg_score">0</b></div></div></div>
  <div class="box aa-card"><div class="box-header"><h3 class="box-title"><i class="fa fa-filter"></i> Filter Appraisal Approval</h3></div><div class="box-body"><form class="form-horizontal" onsubmit="return false;"><div class="form-group"><label class="control-label col-lg-2">Tanggal</label><div class="col-lg-2"><div class="input-group date aa-date"><input id="filter_tgl_awal" class="form-control" value="<?=$defaultFrom;?>"><span class="input-group-addon"><span class="glyphicon glyphicon-calendar"></span></span></div></div><div class="col-lg-2"><div class="input-group date aa-date"><input id="filter_tgl_akhir" class="form-control" value="<?=$defaultTo;?>"><span class="input-group-addon"><span class="glyphicon glyphicon-calendar"></span></span></div></div><label class="control-label col-lg-1">Year</label><div class="col-lg-1"><input id="filter_cycle_year" class="form-control" value="<?=date('Y');?>"></div><label class="control-label col-lg-1"><?=hr_h('common_status', 'Status');?></label><div class="col-lg-3"><select id="filter_status" class="form-control"><option value=""><?=hr_h('common_all', 'All');?></option><option>DRAFT</option><option>SUBMITTED</option><option>MANAGER_APPROVED</option><option>HR_REVIEW</option><option>APPROVED</option><option>REJECTED</option><option>RETURNED</option><option>CANCELLED</option></select></div></div><div class="form-group"><label class="control-label col-lg-2"><?=hr_h('hr_department', 'Department');?></label><div class="col-lg-3"><select id="filter_department_code" class="form-control"></select></div><label class="control-label col-lg-1"><?=hr_h('hr_rating', 'Rating');?></label><div class="col-lg-2"><select id="filter_rating" class="form-control"><option value=""><?=hr_h('common_all', 'All');?></option><option>A</option><option>B</option><option>C</option><option>D</option><option>E</option></select></div><label class="control-label col-lg-1"><?=hr_h('common_search', 'Search');?></label><div class="col-lg-2"><input id="filter_keyword" class="form-control" placeholder="No, employee, appraiser"></div><div class="col-lg-1"><button id="btn_filter_aa" class="btn btn-primary"><i class="fa fa-filter"></i></button> <button id="btn_reset_aa" class="btn btn-default"><i class="fa fa-refresh"></i></button></div></div><div class="form-group"><div class="col-lg-10 col-lg-offset-2"><button id="btn_export_aa" class="btn btn-success"><i class="fa fa-file-excel-o"></i> <?=hr_h('common_download_excel', 'Download Excel');?></button></div></div></form></div></div>
  <div class="box aa-card"><div class="box-body"><div class="alert alert-warning error_data_delete" style="display:none"><button type="button" class="close hide_alert_notif">&times;</button><span class="isi_warning_delete"></span></div><div class="table-responsive"><table id="dtb_appraisal_approval" class="table table-bordered table-striped" style="width:100%"><thead><tr><th><?=hr_h('common_no', 'No');?></th><th><?=hr_h('common_action', 'Action');?></th><th>Appraisal</th><th>Cycle</th><th><?=hr_h('hr_employee', 'Employee');?></th><th>Organization</th><th>Reviewer</th><th><?=hr_h('hr_score', 'Score');?></th><th><?=hr_h('hr_rating', 'Rating');?></th><th><?=hr_h('common_status', 'Status');?></th><th>Updated</th></tr></thead><tbody></tbody></table></div></div></div>
  <div id="modal_appraisal" class="modal fade"><div class="modal-dialog modal-lg" style="width:94%"><div class="modal-content"><form id="form_appraisal"><input type="hidden" name="id" id="aa_id"><div class="modal-header"><button type="button" class="close" data-dismiss="modal">&times;</button><h4 class="modal-title">Create Appraisal Approval</h4></div><div class="modal-body">
    <div class="alert alert-info"><strong>SAP hint:</strong> Flow appraisal idealnya dari employee appraisal submit, manager review, HR calibration, lalu final approve. Modul ini menangkap approval dan rating final.</div>
    <div class="aa-section-title">Appraisal Header</div><div class="row"><div class="col-md-2 form-group"><label>Appraisal No</label><input name="appraisal_no" id="appraisal_no" class="form-control aa-readonly" readonly placeholder="Auto"></div><div class="col-md-2 form-group"><label class="required-label">Cycle Year</label><input name="cycle_year" id="cycle_year" class="form-control" value="<?=date('Y');?>" required></div><div class="col-md-2 form-group"><label><?=hr_h('hr_period', 'Period');?></label><select name="appraisal_period" id="appraisal_period" class="form-control"><option>ANNUAL</option><option>H1</option><option>H2</option><option>Q1</option><option>Q2</option><option>Q3</option><option>Q4</option><option>PROBATION</option><option>SPECIAL</option></select></div><div class="col-md-3 form-group"><label>Type</label><select name="appraisal_type" id="appraisal_type" class="form-control"><option>ANNUAL</option><option>MID_YEAR</option><option>PROBATION</option><option>PROJECT</option><option>SPECIAL</option></select></div><div class="col-md-3 form-group"><label class="required-label">Appraisal Date</label><input name="appraisal_date" id="appraisal_date" class="form-control date-field" value="<?=date('Y-m-d');?>" required></div></div>
    <div class="aa-section-title">Employee & Reviewer</div><div class="row"><div class="col-md-4 form-group"><label class="required-label"><?=hr_h('hr_employee', 'Employee');?></label><select name="employee_id" id="employee_id" class="form-control" required></select></div><div class="col-md-4 form-group"><label class="required-label">Appraiser / Manager</label><select name="appraiser_employee_id" id="appraiser_employee_id" class="form-control" required></select></div><div class="col-md-4 form-group"><label>Second Appraiser</label><select name="second_appraiser_employee_id" id="second_appraiser_employee_id" class="form-control"></select></div></div>
    <div class="row"><div class="col-md-4 form-group"><label>HR Reviewer</label><select name="hr_reviewer_employee_id" id="hr_reviewer_employee_id" class="form-control"></select></div><div class="col-md-4 form-group"><label><?=hr_h('hr_department', 'Department');?></label><select name="department_code" id="department_code" class="form-control"></select></div><div class="col-md-4 form-group"><label><?=hr_h('hr_job_title', 'Job Title');?></label><select name="job_title_id" id="job_title_id" class="form-control"></select></div></div>
    <div class="aa-section-title">Score & Approval</div><div class="row"><div class="col-md-2 form-group"><label>KPI Score</label><input type="number" step="0.01" min="0" max="100" name="kpi_score" id="kpi_score" class="form-control aa-score-input" value="0"></div><div class="col-md-2 form-group"><label>Competency</label><input type="number" step="0.01" min="0" max="100" name="competency_score" id="competency_score" class="form-control aa-score-input" value="0"></div><div class="col-md-2 form-group"><label>Behavior</label><input type="number" step="0.01" min="0" max="100" name="behavior_score" id="behavior_score" class="form-control aa-score-input" value="0"></div><div class="col-md-2 form-group"><label>Final Score</label><input id="final_score_preview" class="form-control aa-readonly" readonly></div><div class="col-md-2 form-group"><label><?=hr_h('hr_rating', 'Rating');?></label><input id="final_rating_preview" class="form-control aa-readonly" readonly></div><div class="col-md-2 form-group"><label>Improvement</label><select name="improvement_required" id="improvement_required" class="form-control"><option>N</option><option>Y</option></select></div></div>
    <div class="row"><div class="col-md-3 form-group"><label><?=hr_h('common_status', 'Status');?></label><select name="calibration_status" id="calibration_status" class="form-control"><option>DRAFT</option><option>SUBMITTED</option><option>MANAGER_APPROVED</option><option>HR_REVIEW</option><option>APPROVED</option><option>REJECTED</option><option>RETURNED</option><option>CANCELLED</option></select></div><div class="col-md-3 form-group"><label>Approval Level</label><select name="approval_level" id="approval_level" class="form-control"><option>MANAGER</option><option>SECOND_MANAGER</option><option>HR</option><option>FINAL</option></select></div><div class="col-md-6 form-group"><label>Reward Recommendation</label><input name="reward_recommendation" id="reward_recommendation" class="form-control" placeholder="Merit increase, promotion candidate, bonus, atau none"></div></div>
    <div class="aa-section-title">Comments & Development Plan</div><div class="row"><div class="col-md-4 form-group"><label>Employee Comment</label><textarea name="employee_comment" id="employee_comment" class="form-control" rows="3"></textarea></div><div class="col-md-4 form-group"><label>Manager Comment</label><textarea name="manager_comment" id="manager_comment" class="form-control" rows="3"></textarea></div><div class="col-md-4 form-group"><label>HR Comment</label><textarea name="hr_comment" id="hr_comment" class="form-control" rows="3"></textarea></div></div>
    <div class="row"><div class="col-md-8 form-group"><label>Development Plan</label><textarea name="development_plan" id="development_plan" class="form-control" rows="3" placeholder="Training, coaching, rotation, target perbaikan"></textarea></div><div class="col-md-4 form-group"><label><?=hr_h('common_remarks', 'Remarks');?></label><textarea name="remarks" id="remarks" class="form-control" rows="3"></textarea></div></div>
  </div><div class="modal-footer"><button type="button" class="btn btn-default" data-dismiss="modal"><?=hr_h('common_cancel', 'Cancel');?></button><button type="submit" class="btn btn-primary"><i class="fa fa-save"></i> Save Appraisal</button></div></form></div></div></div>
  <div id="modal_aa_detail" class="modal fade"><div class="modal-dialog modal-lg" style="width:92%"><div class="modal-content"><div class="modal-header"><button class="close" data-dismiss="modal">&times;</button><h4 class="modal-title">Appraisal Detail</h4></div><div class="modal-body" id="aa_detail_body"></div><div class="modal-footer"><button class="btn btn-default" data-dismiss="modal"><?=hr_h('common_close', 'Close');?></button></div></div></div></div>
</section>
<script src="<?=base_admin();?>assets/plugins/select2/select2.min.js"></script><script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
<script>
function aaError(m){$('.isi_warning_delete').text(m||'Appraisal approval gagal diproses.');$('.error_data_delete').fadeIn();}
function aaFilters(){return{tgl_awal:$('#filter_tgl_awal').val(),tgl_akhir:$('#filter_tgl_akhir').val(),cycle_year:$('#filter_cycle_year').val(),status:$('#filter_status').val(),rating:$('#filter_rating').val(),department_code:$('#filter_department_code').val(),keyword:$('#filter_keyword').val()};}
function aaSet(selector,value,text){var el=$(selector);if(!value){el.val(null).trigger('change');return;}if(!el.find('option[value="'+value+'"]').length)el.append(new Option(text||value,value,true,true));el.val(value).trigger('change');}
function aaRating(score){score=parseFloat(score||0);if(score>=90)return'A';if(score>=80)return'B';if(score>=70)return'C';if(score>=60)return'D';return'E';}
function aaCalc(){var k=parseFloat($('#kpi_score').val()||0),c=parseFloat($('#competency_score').val()||0),b=parseFloat($('#behavior_score').val()||0);var f=((k*.5)+(c*.3)+(b*.2));$('#final_score_preview').val(f.toFixed(2));$('#final_rating_preview').val(aaRating(f));}
function aaReset(title){$('#form_appraisal')[0].reset();$('#aa_id').val('');$('#appraisal_no').val('');$('#cycle_year').val('<?=date('Y');?>');$('#appraisal_date').val('<?=date('Y-m-d');?>');$('#employee_id,#appraiser_employee_id,#second_appraiser_employee_id,#hr_reviewer_employee_id,#department_code,#job_title_id').val(null).trigger('change');$('#appraisal_period,#appraisal_type,#calibration_status,#approval_level,#improvement_required').val('').trigger('change');$('#appraisal_period').val('ANNUAL').trigger('change');$('#appraisal_type').val('ANNUAL').trigger('change');$('#calibration_status').val('DRAFT').trigger('change');$('#approval_level').val('MANAGER').trigger('change');$('#improvement_required').val('N').trigger('change');aaCalc();$('#modal_appraisal .modal-title').text(title||'Create Appraisal Approval');}
function aaAjax(selector,act,placeholder){$(selector).select2({width:'100%',allowClear:true,placeholder:placeholder,dropdownParent:$('#modal_appraisal'),ajax:{url:'<?=base_admin();?>modul/appraisal_approval/appraisal_approval_action.php?act='+act,type:'POST',dataType:'json',delay:250,data:function(p){return{term:p.term||'',exclude:$('#employee_id').val()||0,department_code:$('#department_code').val()||''};},processResults:function(d){return{results:d.results||[]};}}});}
$(function(){
  if($.fn.datepicker){$('.aa-date,.date-field').datepicker({format:'yyyy-mm-dd',autoclose:true,todayHighlight:true});}
  if($.fn.select2){$('#filter_status,#filter_rating,#appraisal_period,#appraisal_type,#calibration_status,#approval_level,#improvement_required').select2({width:'100%',allowClear:true});$('#filter_department_code').select2({width:'100%',allowClear:true,placeholder:'Semua Department',ajax:{url:'<?=base_admin();?>modul/appraisal_approval/appraisal_approval_action.php?act=department_search',type:'POST',dataType:'json',delay:250,data:function(p){return{term:p.term||''};},processResults:function(d){return{results:d.results||[]};}}});aaAjax('#employee_id','employee_search','Pilih employee...');aaAjax('#appraiser_employee_id','employee_search','Pilih appraiser...');aaAjax('#second_appraiser_employee_id','employee_search','Pilih second appraiser...');aaAjax('#hr_reviewer_employee_id','employee_search','Pilih HR reviewer...');aaAjax('#department_code','department_search','Pilih department...');aaAjax('#job_title_id','job_title_search','Pilih job title...');}
  var dt=$('#dtb_appraisal_approval').DataTable({bProcessing:true,bServerSide:true,pageLength:25,dom:"<'row'<'col-sm-12'B>>"+"<'row'<'col-sm-6'l><'col-sm-6'f>>"+"<'row'<'col-sm-12'tr>>"+"<'row'<'col-sm-5'i><'col-sm-7'p>>",buttons:[{extend:'collection',text:<?=hr_js('common_export_data', 'Export Data');?>,buttons:['copyHtml5','excelHtml5','csvHtml5']}],columnDefs:[{targets:[0,1],orderable:false,searchable:false},{width:'42px',targets:0},{width:'160px',targets:1}],ajax:{url:'<?=base_admin();?>modul/appraisal_approval/appraisal_approval_data.php',type:'post',data:function(d){$.extend(d,aaFilters());},dataSrc:function(json){var k=json.kpi||{};$('#kpi_total').text(k.total||0);$('#kpi_submitted').text(k.submitted||0);$('#kpi_hr_review').text(k.hr_review||0);$('#kpi_avg_score').text(k.avg_score||0);return json.data||[];},error:function(xhr){console.log(xhr.responseText);aaError('Data Appraisal Approval gagal dimuat.');}}});
  $('#btn_open_aa').click(function(){aaReset('Create Appraisal Approval');$('#modal_appraisal').modal({backdrop:'static',keyboard:false});});
  $('#btn_filter_aa').click(function(){dt.draw();});$('#filter_keyword').keyup(function(e){if(e.keyCode===13)dt.draw();});
  $('#btn_reset_aa').click(function(){$('#filter_tgl_awal').val('<?=$defaultFrom;?>');$('#filter_tgl_akhir').val('<?=$defaultTo;?>');$('#filter_cycle_year').val('<?=date('Y');?>');$('#filter_status,#filter_rating,#filter_department_code').val(null).trigger('change');$('#filter_keyword').val('');dt.draw();});
  $('#btn_export_aa').click(function(){var q=$.param(aaFilters());window.location='<?=base_admin();?>modul/appraisal_approval/appraisal_approval_action.php?act=export&'+q;});
  $('.hide_alert_notif').click(function(){$('.error_data_delete').hide();});$('.aa-score-input').on('keyup change',aaCalc);
  $('#employee_id').on('change',function(){var id=$(this).val();if(!id)return;$.post('<?=base_admin();?>modul/appraisal_approval/appraisal_approval_action.php?act=employee_snapshot',{employee_id:id},function(r){if(r.status!=='good')return;var h=r.data;aaSet('#department_code',h.department_code,h.department_code+' - '+(h.nm_dept||''));aaSet('#job_title_id',h.job_title_id,(h.job_title_code||'')+' - '+(h.job_title_name||''));aaSet('#appraiser_employee_id',h.manager_employee_id,h.manager_no? h.manager_no+' - '+h.manager_name : 'Manager ID '+h.manager_employee_id);},'json');});
  $('#form_appraisal').submit(function(e){e.preventDefault();var btn=$(this).find('button[type=submit]');btn.prop('disabled',true).html('<i class="fa fa-spinner fa-spin"></i> <?=hr_h('common_saving', 'Saving...');?>');$.post('<?=base_admin();?>modul/appraisal_approval/appraisal_approval_action.php?act=save',$(this).serialize(),function(r){btn.prop('disabled',false).html('<i class="fa fa-save"></i> Save Appraisal');if(r.status==='good'){$('#modal_appraisal').modal('hide');dt.draw(false);Swal.fire('Saved','Appraisal approval tersimpan. Final score '+r.final_score+' rating '+r.final_rating,'success');}else aaError(r.error_message);},'json').fail(function(xhr){btn.prop('disabled',false).html('<i class="fa fa-save"></i> Save Appraisal');aaError(xhr.responseText);});});
  $(document).on('click','.btn-aa-detail',function(){$.post('<?=base_admin();?>modul/appraisal_approval/appraisal_approval_action.php?act=detail',{id:$(this).data('id')},function(html){$('#aa_detail_body').html(html);$('#modal_aa_detail').modal('show');});});
  $(document).on('click','.btn-aa-edit',function(){var id=$(this).data('id');$.post('<?=base_admin();?>modul/appraisal_approval/appraisal_approval_action.php?act=get',{id:id},function(r){if(r.status!=='good'){aaError(r.error_message);return;}aaReset('Edit Appraisal Approval');var h=r.data||{};Object.keys(h).forEach(function(k){var el=$('#'+k);if(el.length&&!['employee_id','appraiser_employee_id','second_appraiser_employee_id','hr_reviewer_employee_id','department_code','job_title_id'].includes(k))el.val(h[k]);});$('#aa_id').val(h.id);aaSet('#employee_id',h.employee_id,h.employee_text);aaSet('#appraiser_employee_id',h.appraiser_employee_id,h.appraiser_text);aaSet('#second_appraiser_employee_id',h.second_appraiser_employee_id,h.second_text);aaSet('#hr_reviewer_employee_id',h.hr_reviewer_employee_id,h.hr_text);aaSet('#department_code',h.department_code,h.department_text);aaSet('#job_title_id',h.job_title_id,h.job_title_text);$('#appraisal_period,#appraisal_type,#calibration_status,#approval_level,#improvement_required').trigger('change');aaCalc();$('#modal_appraisal').modal({backdrop:'static',keyboard:false});},'json');});
  $(document).on('click','.btn-aa-decision',function(){var id=$(this).data('id'),no=$(this).data('no'),decision=$(this).data('decision');Swal.fire({title:decision+' appraisal?',text:no,input:'textarea',inputPlaceholder:'Catatan approval/reject/return',showCancelButton:true,confirmButtonText:decision}).then(function(x){if(!x.isConfirmed)return;$.post('<?=base_admin();?>modul/appraisal_approval/appraisal_approval_action.php?act=decision',{id:id,decision:decision,comment:x.value||''},function(r){if(r.status==='good'){dt.draw(false);Swal.fire('Saved','Decision berhasil disimpan.','success');}else aaError(r.error_message);},'json');});});
  $(document).on('click','.btn-aa-delete',function(){var id=$(this).data('id'),no=$(this).data('no');Swal.fire({title:erpLang('confirm_delete_title','Delete Confirmation'),text:no,icon:'warning',showCancelButton:true,confirmButtonText:erpLang('common_delete','Delete'),cancelButtonText:erpLang('common_cancel','Cancel')}).then(function(x){if(!x.isConfirmed)return;$.post('<?=base_admin();?>modul/appraisal_approval/appraisal_approval_action.php?act=delete',{id:id},function(r){if(r.status==='good'){dt.draw(false);Swal.fire(erpLang('common_deleted','Deleted'),erpLang('common_deleted_message','Data deleted successfully.'),'success');}else aaError(r.error_message);},'json');});});
});
</script>
