<?php
if (!function_exists('hr_t')) {
  function hr_t($key, $fallback = '') { return lang_text($key, $fallback); }
}
if (!function_exists('hr_h')) {
  function hr_h($key, $fallback = '') { return htmlspecialchars((string) hr_t($key, $fallback), ENT_QUOTES, 'UTF-8'); }
}
if (!function_exists('hr_js')) {
  function hr_js($key, $fallback = '') { return json_encode(hr_t($key, $fallback), JSON_HEX_TAG | JSON_HEX_APOS | JSON_HEX_AMP | JSON_HEX_QUOT); }
}
$defaultFrom=date('Y-01-01');$defaultTo=date('Y-12-31');$today=date('Y-m-d');$canInsert=isset($role_act['insert_act'])&&$role_act['insert_act']==='Y'; ?>
<style>
.hc-hero{background:linear-gradient(135deg,#991b1b,#2563eb);color:#fff;border-radius:14px;padding:20px;margin-bottom:18px;box-shadow:0 10px 24px rgba(15,23,42,.16)}.hc-hero h1{margin:0 0 6px;font-size:26px;font-weight:700}.hc-hero p{margin:0;opacity:.94}.hc-card{border-radius:12px;background:#fff;border:1px solid #e5edf5;box-shadow:0 5px 16px rgba(15,23,42,.05);margin-bottom:14px}.hc-kpi{padding:14px;border-radius:12px;background:#f8fafc;border:1px solid #e5edf5}.hc-kpi b{font-size:22px;display:block}#dtb_holiday_calendar th,#dtb_holiday_calendar td{font-size:12px;vertical-align:middle}.select2-container{width:100%!important}.required-label:after{content:' *';color:#dd4b39}.hc-action{white-space:nowrap}#modal_holiday_calendar .modal-body{max-height:calc(100vh - 185px);overflow-y:auto}.hc-section-title{font-weight:700;color:#334155;margin:8px 0 12px;border-bottom:1px solid #e5e7eb;padding-bottom:7px}.hc-hint{background:#fef2f2;border:1px solid #fecaca;border-radius:10px;padding:10px;margin-bottom:10px}
</style>
<section class="content-header"><h1><?=hr_h('hr_holiday_calendar', 'Holiday Calendar');?> <small>SAP HR Public Holiday Calendar</small></h1><ol class="breadcrumb"><li><a href="<?=base_index();?>"><i class="fa fa-dashboard"></i> <?=hr_h('common_home', 'Home');?></a></li><li>Human Resource</li><li>Time Management</li><li class="active"><?=hr_h('hr_holiday_calendar', 'Holiday Calendar');?></li></ol></section>
<section class="content">
<div class="hc-hero"><div class="row"><div class="col-md-8"><h1>Holiday Calendar Workbench</h1><p>Kelola libur nasional, cuti bersama, libur regional, shutdown plant, dan half day sebagai exception kalender kerja perusahaan.</p></div><div class="col-md-4 text-right"><?php if($canInsert){ ?><button id="btn_open_hc" class="btn btn-warning"><i class="fa fa-plus"></i> Create Holiday</button><?php } ?> <button id="btn_export_hc" class="btn btn-success"><i class="fa fa-file-excel-o"></i> <?=hr_h('common_export_excel', 'Export Excel');?></button></div></div></div>
<div class="row"><div class="col-sm-2"><div class="hc-kpi"><span>Total</span><b id="kpi_total">0</b></div></div><div class="col-sm-2"><div class="hc-kpi"><span><?=hr_h('hr_active', 'Active');?></span><b id="kpi_active">0</b></div></div><div class="col-sm-2"><div class="hc-kpi"><span>Public</span><b id="kpi_public_holiday">0</b></div></div><div class="col-sm-2"><div class="hc-kpi"><span>Collective</span><b id="kpi_collective_leave">0</b></div></div><div class="col-sm-2"><div class="hc-kpi"><span>Half Day</span><b id="kpi_half_day">0</b></div></div><div class="col-sm-2"><div class="hc-kpi"><span>Year</span><b><?=date('Y');?></b></div></div></div>
<div class="box hc-card"><div class="box-header"><h3 class="box-title"><i class="fa fa-filter"></i> Filter Holiday</h3></div><div class="box-body"><form class="form-horizontal" onsubmit="return false;"><div class="form-group"><label class="control-label col-lg-2"><?=hr_h('hr_date', 'Date');?></label><div class="col-lg-2"><div class="input-group date hc-date"><input id="filter_tgl_awal" class="form-control" value="<?=$defaultFrom;?>"><span class="input-group-addon"><span class="glyphicon glyphicon-calendar"></span></span></div></div><div class="col-lg-2"><div class="input-group date hc-date"><input id="filter_tgl_akhir" class="form-control" value="<?=$defaultTo;?>"><span class="input-group-addon"><span class="glyphicon glyphicon-calendar"></span></span></div></div><label class="control-label col-lg-1">Type</label><div class="col-lg-2"><select id="filter_holiday_type" class="form-control"><option value="">All</option><option>PUBLIC_HOLIDAY</option><option>COMPANY_HOLIDAY</option><option>COLLECTIVE_LEAVE</option><option>REGIONAL_HOLIDAY</option><option>RELIGIOUS_HOLIDAY</option><option>SPECIAL_NON_WORKING</option><option>HALF_DAY</option></select></div><label class="control-label col-lg-1"><?=hr_h('common_status', 'Status');?></label><div class="col-lg-2"><select id="filter_holiday_status" class="form-control"><option value="">All</option><option>DRAFT</option><option>ACTIVE</option><option>INACTIVE</option></select></div></div><div class="form-group"><label class="control-label col-lg-2">Scope</label><div class="col-lg-2"><select id="filter_holiday_scope" class="form-control"><option value="">All</option><option>NATIONAL</option><option>REGIONAL</option><option>PLANT</option><option>COMPANY</option><option>LOCATION</option></select></div><label class="control-label col-lg-1">Calendar</label><div class="col-lg-3"><select id="filter_calendar_id" class="form-control"></select></div><div class="col-lg-4"><input id="filter_keyword" class="form-control" placeholder="Holiday code, name, region, source"></div></div><div class="form-group"><div class="col-lg-offset-2 col-lg-10"><button id="btn_filter_hc" class="btn btn-primary"><i class="fa fa-filter"></i> <?=hr_h('common_filter', 'Filter');?></button> <button id="btn_reset_hc" class="btn btn-default"><i class="fa fa-refresh"></i> <?=hr_h('common_reset', 'Reset');?></button></div></div></form></div></div>
<div class="box hc-card"><div class="box-body"><div class="alert alert-warning error_data_delete" style="display:none"><button type="button" class="close hide_alert_notif">&times;</button><span class="isi_warning_delete"></span></div><div class="table-responsive"><table id="dtb_holiday_calendar" class="table table-bordered table-striped" style="width:100%"><thead><tr><th><?=hr_h('common_no', 'No');?></th><th><?=hr_h('common_action', 'Action');?></th><th>Holiday</th><th><?=hr_h('hr_date', 'Date');?></th><th>Type</th><th>Scope</th><th>Calendar</th><th>Rules</th><th><?=hr_h('common_status', 'Status');?></th><th>Updated</th></tr></thead><tbody></tbody></table></div></div></div>
<div id="modal_holiday_calendar" class="modal fade"><div class="modal-dialog modal-lg" style="width:94%"><div class="modal-content"><form id="form_holiday_calendar"><input type="hidden" name="id" id="hc_id"><div class="modal-header"><button type="button" class="close" data-dismiss="modal">&times;</button><h4 class="modal-title">Create Holiday Calendar</h4></div><div class="modal-body"><div class="hc-hint"><strong>SAP hint:</strong> Jika `Apply to Factory Calendar` dipilih, tanggal holiday ACTIVE akan ditulis sebagai exception di kalender kerja.</div>
<div class="hc-section-title">Holiday Definition</div><div class="row"><div class="col-md-2 form-group"><label class="required-label">Holiday Code</label><input name="holiday_code" id="holiday_code" class="form-control text-uppercase" required maxlength="30" placeholder="HC-..."></div><div class="col-md-4 form-group"><label class="required-label">Holiday Name</label><input name="holiday_name" id="holiday_name" class="form-control" required maxlength="150"></div><div class="col-md-2 form-group"><label>Date From</label><input name="holiday_date" id="holiday_date" class="form-control date-field" value="<?=$today;?>"></div><div class="col-md-2 form-group"><label>Date To</label><input name="holiday_end_date" id="holiday_end_date" class="form-control date-field" value="<?=$today;?>"></div><div class="col-md-2 form-group"><label><?=hr_h('common_status', 'Status');?></label><select name="holiday_status" id="holiday_status" class="form-control"><option>DRAFT</option><option>ACTIVE</option><option>INACTIVE</option></select></div></div>
<div class="row"><div class="col-md-3 form-group"><label>Holiday Type</label><select name="holiday_type" id="holiday_type" class="form-control"><option>PUBLIC_HOLIDAY</option><option>COMPANY_HOLIDAY</option><option>COLLECTIVE_LEAVE</option><option>REGIONAL_HOLIDAY</option><option>RELIGIOUS_HOLIDAY</option><option>SPECIAL_NON_WORKING</option><option>HALF_DAY</option></select></div><div class="col-md-3 form-group"><label>Scope</label><select name="holiday_scope" id="holiday_scope" class="form-control"><option>NATIONAL</option><option>REGIONAL</option><option>PLANT</option><option>COMPANY</option><option>LOCATION</option></select></div><div class="col-md-3 form-group"><label>Factory Calendar</label><select name="calendar_id" id="calendar_id" class="form-control"></select></div><div class="col-md-3 form-group"><label><?=hr_h('hr_work_location', 'Work Location');?></label><select name="work_location_id" id="work_location_id" class="form-control"></select></div></div>
<div class="row"><div class="col-md-2 form-group"><label>Region Code</label><input name="region_code" id="region_code" class="form-control text-uppercase" placeholder="ID-JB"></div><div class="col-md-2 form-group"><label>Country</label><input name="country" id="country" class="form-control text-uppercase" value="ID" maxlength="3"></div><div class="col-md-2 form-group"><label>Working Hours</label><input name="working_hours" id="working_hours" type="number" step="0.01" min="0" class="form-control" value="0"></div><div class="col-md-2 form-group"><label>Paid Holiday</label><select name="paid_holiday" id="paid_holiday" class="form-control"><option>Y</option><option>N</option></select></div><div class="col-md-2 form-group"><label>Recurring</label><select name="recurring_annual" id="recurring_annual" class="form-control"><option>N</option><option>Y</option></select></div><div class="col-md-2 form-group"><label>Apply Calendar</label><select name="apply_calendar" id="apply_calendar" class="form-control"><option>N</option><option>Y</option></select></div></div>
<div class="row"><div class="col-md-4 form-group"><label>Source Reference</label><input name="source_reference" id="source_reference" class="form-control" placeholder="SKB / Policy / Memo"></div><div class="col-md-4 form-group"><label>SAP Reference</label><input name="sap_reference" id="sap_reference" class="form-control"></div><div class="col-md-4 form-group"><label><?=hr_h('common_remarks', 'Remarks');?></label><input name="remarks" id="remarks" class="form-control"></div></div>
</div><div class="modal-footer"><button type="button" class="btn btn-default" data-dismiss="modal"><?=hr_h('common_cancel', 'Cancel');?></button><button type="submit" class="btn btn-primary"><i class="fa fa-save"></i> Save Holiday</button></div></form></div></div></div>
<div id="modal_hc_detail" class="modal fade"><div class="modal-dialog modal-lg" style="width:92%"><div class="modal-content"><div class="modal-header"><button class="close" data-dismiss="modal">&times;</button><h4 class="modal-title">Holiday Calendar Detail</h4></div><div class="modal-body" id="hc_detail_body"></div><div class="modal-footer"><button class="btn btn-default" data-dismiss="modal"><?=hr_h('common_close', 'Close');?></button></div></div></div></div>
</section>
<script src="<?=base_admin();?>assets/plugins/select2/select2.min.js"></script><script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
<script>
function hcError(m){$('.isi_warning_delete').text(m||'Holiday Calendar gagal diproses.');$('.error_data_delete').fadeIn();}
function hcFilters(){return{tgl_awal:$('#filter_tgl_awal').val(),tgl_akhir:$('#filter_tgl_akhir').val(),holiday_type:$('#filter_holiday_type').val(),holiday_scope:$('#filter_holiday_scope').val(),holiday_status:$('#filter_holiday_status').val(),calendar_id:$('#filter_calendar_id').val(),keyword:$('#filter_keyword').val()};}
function hcSet(s,v,t){var e=$(s);if(!v){e.val(null).trigger('change');return;}if(!e.find('option[value="'+v+'"]').length)e.append(new Option(t||v,v,true,true));e.val(v).trigger('change');}
function hcAjax(s,act,p,parent){$(s).select2({width:'100%',allowClear:true,placeholder:p,dropdownParent:parent||$(document.body),ajax:{url:'<?=base_admin();?>modul/holiday_calendar/holiday_calendar_action.php?act='+act,type:'POST',dataType:'json',delay:250,data:function(q){return{term:q.term||''};},processResults:function(d){return{results:d.results||[]};}}});}
function hcReset(title){$('#form_holiday_calendar')[0].reset();$('#hc_id').val('');$('#calendar_id,#work_location_id').val(null).trigger('change');$('#holiday_date,#holiday_end_date').val('<?=$today;?>');$('#holiday_type').val('PUBLIC_HOLIDAY').trigger('change');$('#holiday_scope').val('NATIONAL').trigger('change');$('#holiday_status').val('DRAFT').trigger('change');$('#paid_holiday').val('Y').trigger('change');$('#recurring_annual,#apply_calendar').val('N').trigger('change');$('#country').val('ID');$('#working_hours').val(0);$('#modal_holiday_calendar .modal-title').text(title||'Create Holiday Calendar');}
$(function(){if($.fn.datepicker){$('.hc-date,.date-field').datepicker({format:'yyyy-mm-dd',autoclose:true,todayHighlight:true});}if($.fn.select2){$('#filter_holiday_type,#filter_holiday_scope,#filter_holiday_status,#holiday_type,#holiday_scope,#holiday_status,#paid_holiday,#recurring_annual,#apply_calendar').select2({width:'100%',allowClear:true});hcAjax('#filter_calendar_id','calendar_search','Semua Calendar');hcAjax('#calendar_id','calendar_search','Pilih Factory Calendar',$('#modal_holiday_calendar'));hcAjax('#work_location_id','work_location_search','Pilih Work Location',$('#modal_holiday_calendar'));}
var dt=$('#dtb_holiday_calendar').DataTable({bProcessing:true,bServerSide:true,pageLength:25,dom:"<'row'<'col-sm-12'B>>"+"<'row'<'col-sm-6'l><'col-sm-6'f>>"+"<'row'<'col-sm-12'tr>>"+"<'row'<'col-sm-5'i><'col-sm-7'p>>",buttons:[{extend:'collection',text:<?=hr_js('common_export_data', 'Export Data');?>,buttons:['copyHtml5','excelHtml5','csvHtml5','pdfHtml5']}],columnDefs:[{targets:[0,1],orderable:false,searchable:false},{width:'42px',targets:0},{width:'180px',targets:1}],ajax:{url:'<?=base_admin();?>modul/holiday_calendar/holiday_calendar_data.php',type:'post',data:function(d){$.extend(d,hcFilters());},dataSrc:function(j){var k=j.kpi||{};$('#kpi_total').text(k.total||0);$('#kpi_active').text(k.active||0);$('#kpi_public_holiday').text(k.public_holiday||0);$('#kpi_collective_leave').text(k.collective_leave||0);$('#kpi_half_day').text(k.half_day||0);return j.data||[];},error:function(x){console.log(x.responseText);hcError('Data Holiday Calendar gagal dimuat.');}}});
$('#btn_open_hc').click(function(){hcReset('Create Holiday Calendar');$('#modal_holiday_calendar').modal({backdrop:'static',keyboard:false});});$('#btn_filter_hc').click(function(){dt.draw();});$('#filter_keyword').keyup(function(e){if(e.keyCode===13)dt.draw();});$('#btn_reset_hc').click(function(){$('#filter_tgl_awal').val('<?=$defaultFrom;?>');$('#filter_tgl_akhir').val('<?=$defaultTo;?>');$('#filter_holiday_type,#filter_holiday_scope,#filter_holiday_status,#filter_calendar_id').val(null).trigger('change');$('#filter_keyword').val('');dt.draw();});$('#btn_export_hc').click(function(){window.location='<?=base_admin();?>modul/holiday_calendar/holiday_calendar_action.php?act=export&'+$.param(hcFilters());});$('.hide_alert_notif').click(function(){$('.error_data_delete').hide();});$('#holiday_code,#region_code,#country').on('keyup change',function(){this.value=this.value.toUpperCase();});
$('#form_holiday_calendar').submit(function(e){e.preventDefault();var b=$(this).find('button[type=submit]');b.prop('disabled',true).html('<i class="fa fa-spinner fa-spin"></i> <?=hr_h('common_saving', 'Saving...');?>');$.post('<?=base_admin();?>modul/holiday_calendar/holiday_calendar_action.php?act=save',$(this).serialize(),function(r){b.prop('disabled',false).html('<i class="fa fa-save"></i> Save Holiday');if(r.status==='good'){$('#modal_holiday_calendar').modal('hide');dt.draw(false);Swal.fire('Saved','Holiday Calendar berhasil disimpan. Applied: '+(r.applied||0),'success');}else hcError(r.error_message);},'json').fail(function(x){b.prop('disabled',false).html('<i class="fa fa-save"></i> Save Holiday');hcError(x.responseText);});});
$(document).on('click','.btn-hc-detail',function(){$.post('<?=base_admin();?>modul/holiday_calendar/holiday_calendar_action.php?act=detail',{id:$(this).data('id')},function(h){$('#hc_detail_body').html(h);$('#modal_hc_detail').modal('show');});});
$(document).on('click','.btn-hc-edit',function(){var id=$(this).data('id');$.post('<?=base_admin();?>modul/holiday_calendar/holiday_calendar_action.php?act=get',{id:id},function(r){if(r.status!=='good'){hcError(r.error_message);return;}hcReset('Edit Holiday Calendar');var h=r.data||{};Object.keys(h).forEach(function(k){var el=$('#'+k);if(el.length&&!['calendar_id','work_location_id'].includes(k))el.val(h[k]);});$('#hc_id').val(h.id);hcSet('#calendar_id',h.calendar_id,h.calendar_text);hcSet('#work_location_id',h.work_location_id,h.work_location_text);$('#holiday_type,#holiday_scope,#holiday_status,#paid_holiday,#recurring_annual').trigger('change');$('#modal_holiday_calendar').modal({backdrop:'static',keyboard:false});},'json');});
$(document).on('click','.btn-hc-apply',function(){var id=$(this).data('id');$.post('<?=base_admin();?>modul/holiday_calendar/holiday_calendar_action.php?act=apply',{id:id},function(r){if(r.status==='good'){dt.draw(false);Swal.fire('Applied','Holiday diterapkan ke '+(r.applied||0)+' hari calendar.','success');}else hcError(r.error_message);},'json');});
$(document).on('click','.btn-hc-status',function(){var id=$(this).data('id'),status=$(this).data('status');$.post('<?=base_admin();?>modul/holiday_calendar/holiday_calendar_action.php?act=status',{id:id,status:status},function(r){if(r.status==='good'){dt.draw(false);Swal.fire('Updated','Status berhasil diubah.','success');}else hcError(r.error_message);},'json');});
$(document).on('click','.btn-hc-delete',function(){if($(this).is(':disabled'))return;var id=$(this).data('id'),no=$(this).data('no');Swal.fire({title:erpLang('confirm_delete_title','Delete Confirmation'),text:no,icon:'warning',showCancelButton:true,confirmButtonText:erpLang('common_delete','Delete'),cancelButtonText:erpLang('common_cancel','Cancel')}).then(function(x){if(!x.isConfirmed)return;$.post('<?=base_admin();?>modul/holiday_calendar/holiday_calendar_action.php?act=delete',{id:id},function(r){if(r.status==='good'){dt.draw(false);Swal.fire(erpLang('common_deleted','Deleted'),erpLang('common_deleted_message','Data deleted successfully.'),'success');}else hcError(r.error_message);},'json').fail(function(x){hcError(x.responseText);});});});
});
</script>
