<?php
if (!function_exists('hr_t')) {
  function hr_t($key, $fallback = '') { return lang_text($key, $fallback); }
}
if (!function_exists('hr_h')) {
  function hr_h($key, $fallback = '') { return htmlspecialchars((string) hr_t($key, $fallback), ENT_QUOTES, 'UTF-8'); }
}
if (!function_exists('hr_js')) {
  function hr_js($key, $fallback = '') { return json_encode(hr_t($key, $fallback), JSON_HEX_TAG | JSON_HEX_APOS | JSON_HEX_AMP | JSON_HEX_QUOT); }
}
if (session_status() === PHP_SESSION_NONE) session_start();
include "../../inc/config.php";
session_check_json();
function hc_json($s,$m='',$x=array()){header('Content-Type: application/json; charset=utf-8');$p=array('status'=>$s);if($m!=='')$p[$s==='good'?'message':'error_message']=$m;foreach($x as $k=>$v)$p[$k]=$v;echo json_encode($p);exit;}
function hc_h($v){return htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');}
function hc_p($k,$d=''){return isset($_POST[$k])?$_POST[$k]:$d;}
function hc_g($k,$d=''){return isset($_GET[$k])?$_GET[$k]:$d;}
function hc_c($v){return strtoupper(trim((string)$v));}
function hc_user(){return isset($_SESSION['username'])&&$_SESSION['username']!==''?$_SESSION['username']:'system';}
function hc_date_ok($v){return (bool)preg_match('/^\d{4}-\d{2}-\d{2}$/',(string)$v);}
function hc_num($v){return is_numeric($v)?(float)$v:0;}
function hc_select2($rows,$id,$cb){$out=array();foreach($rows as $r)$out[]=array('id'=>$r->$id,'text'=>$cb($r));header('Content-Type: application/json; charset=utf-8');echo json_encode(array('results'=>$out));exit;}
function hc_day_name($date){$n=array('Minggu','Senin','Selasa','Rabu','Kamis','Jumat','Sabtu');return $n[(int)date('w',strtotime($date))];}
function hc_weekday_no($date){return (int)date('w',strtotime($date))+1;}
function hc_row($id){global $db;return $db->fetch("SELECT hc.*,fc.calendar_name,wl.location_code,wl.location_name FROM erp_holiday_calendar hc LEFT JOIN erp_factory_calendar_header fc ON fc.id=hc.calendar_id LEFT JOIN erp_work_location wl ON wl.id=hc.work_location_id WHERE hc.id=? LIMIT 1",array((int)$id));}
function hc_payload($r){$d=(array)$r;$d['calendar_text']=$r->calendar_id?($r->calendar_code.' - '.$r->calendar_name.' ['.$r->plant_code.']'):'';$d['work_location_text']=$r->work_location_id?($r->location_code.' - '.$r->location_name):'';return $d;}
function hc_apply($h){
  global $db,$username;
  if(!$h->calendar_id)return 0;
  $start=strtotime($h->holiday_date);$end=strtotime($h->holiday_end_date?:$h->holiday_date);$count=0;
  for($t=$start;$t<=$end;$t=strtotime('+1 day',$t)){
    $date=date('Y-m-d',$t);$tipe=((float)$h->working_hours)>0?'Khusus':'Libur';$ket=$h->holiday_code.' - '.$h->holiday_name;
    $exist=$db->fetch("SELECT id FROM erp_factory_calendar WHERE calendar_id=? AND tanggal=? LIMIT 1",array($h->calendar_id,$date));
    $data=array('calendar_code'=>$h->calendar_code,'plant_code'=>$h->plant_code,'tanggal'=>$date,'nama_hari'=>hc_day_name($date),'weekday_no'=>hc_weekday_no($date),'tipe_hari'=>$tipe,'shift_id'=>null,'shift_code'=>null,'working_hours'=>(float)$h->working_hours,'exception_type'=>$h->holiday_type,'source_type'=>'HOLIDAY_CALENDAR','keterangan'=>$ket,'updated_by'=>$username,'updated_at'=>date('Y-m-d H:i:s'));
    if($exist)$db->update('erp_factory_calendar',$data,'id',$exist->id);
    else{$data['calendar_id']=$h->calendar_id;$db->insert('erp_factory_calendar',$data);}
    $count++;
  }
  return $count;
}
function hc_rows($from,$to,$type,$scope,$status,$calendar,$kw){global $db;$w=" WHERE hc.holiday_date<=? AND COALESCE(hc.holiday_end_date,hc.holiday_date)>=? ";$p=array($to,$from);if($type!==''){$w.=" AND hc.holiday_type=? ";$p[]=$type;}if($scope!==''){$w.=" AND hc.holiday_scope=? ";$p[]=$scope;}if($status!==''){$w.=" AND hc.holiday_status=? ";$p[]=$status;}if($calendar!==''){$w.=" AND hc.calendar_id=? ";$p[]=(int)$calendar;}if($kw!==''){$like='%'.$kw.'%';$w.=" AND (hc.holiday_code LIKE ? OR hc.holiday_name LIKE ? OR hc.region_code LIKE ? OR hc.source_reference LIKE ? OR hc.sap_reference LIKE ?) ";array_push($p,$like,$like,$like,$like,$like);}return $db->query("SELECT hc.*,fc.calendar_name,wl.location_code,wl.location_name FROM erp_holiday_calendar hc LEFT JOIN erp_factory_calendar_header fc ON fc.id=hc.calendar_id LEFT JOIN erp_work_location wl ON wl.id=hc.work_location_id $w ORDER BY hc.holiday_date,hc.holiday_code",$p);}
$act=isset($_GET['act'])?$_GET['act']:'';$username=hc_user();$types=array('PUBLIC_HOLIDAY','COMPANY_HOLIDAY','COLLECTIVE_LEAVE','REGIONAL_HOLIDAY','RELIGIOUS_HOLIDAY','SPECIAL_NON_WORKING','HALF_DAY');$scopes=array('NATIONAL','REGIONAL','PLANT','COMPANY','LOCATION');$stats=array('DRAFT','ACTIVE','INACTIVE');$yn=array('Y','N');
switch($act){
case 'calendar_search':$t=trim(hc_p('term'));$like='%'.$t.'%';$rows=$db->query("SELECT id,calendar_code,calendar_name,plant_code,calendar_status FROM erp_factory_calendar_header WHERE (?='' OR calendar_code LIKE ? OR calendar_name LIKE ? OR plant_code LIKE ?) ORDER BY FIELD(calendar_status,'RELEASED','ACTIVE','DRAFT','INACTIVE'),calendar_code LIMIT 30",array($t,$like,$like,$like));hc_select2($rows,'id',function($r){return $r->calendar_code.' - '.$r->calendar_name.' ['.$r->plant_code.' / '.$r->calendar_status.']';});
case 'work_location_search':$t=trim(hc_p('term'));$like='%'.$t.'%';$rows=$db->query("SELECT id,location_code,location_name,location_type,city FROM erp_work_location WHERE status='ACTIVE' AND (?='' OR location_code LIKE ? OR location_name LIKE ? OR city LIKE ?) ORDER BY location_code LIMIT 30",array($t,$like,$like,$like));hc_select2($rows,'id',function($r){return $r->location_code.' - '.$r->location_name.' ['.$r->location_type.($r->city?' / '.$r->city:'').']';});
case 'get':$r=hc_row((int)hc_p('id'));if(!$r)hc_json('error','Holiday Calendar tidak ditemukan.');hc_json('good','',array('data'=>hc_payload($r)));
case 'save':
  $id=(int)hc_p('id');$code=hc_c(hc_p('holiday_code'));$name=trim(hc_p('holiday_name'));$from=trim(hc_p('holiday_date'));$to=trim(hc_p('holiday_end_date'));$type=hc_c(hc_p('holiday_type','PUBLIC_HOLIDAY'));$scope=hc_c(hc_p('holiday_scope','NATIONAL'));$status=hc_c(hc_p('holiday_status','DRAFT'));
  if($code===''||!preg_match('/^[A-Z0-9_-]{3,30}$/',$code))hc_json('error','Holiday Code wajib diisi dan hanya boleh huruf besar/angka/underscore/dash.');if($name==='')hc_json('error','Holiday Name wajib diisi.');if(!hc_date_ok($from))hc_json('error','Holiday Date wajib format YYYY-MM-DD.');if($to==='' )$to=$from;if(!hc_date_ok($to)||strtotime($to)<strtotime($from))hc_json('error','Holiday End Date tidak valid.');if(!in_array($type,$types,true)||!in_array($scope,$scopes,true)||!in_array($status,$stats,true))hc_json('error','Type/scope/status tidak valid.');
  $calId=hc_p('calendar_id')!==''?(int)hc_p('calendar_id'):null;$calCode=null;$plantCode=null;if($calId){$cal=$db->fetch("SELECT * FROM erp_factory_calendar_header WHERE id=? LIMIT 1",array($calId));if(!$cal)hc_json('error','Factory Calendar tidak valid.');$calCode=$cal->calendar_code;$plantCode=$cal->plant_code;}
  $locId=hc_p('work_location_id')!==''?(int)hc_p('work_location_id'):null;if($locId&&!$db->fetch("SELECT id FROM erp_work_location WHERE id=? LIMIT 1",array($locId)))hc_json('error','Work Location tidak valid.');
  if($db->fetch("SELECT id FROM erp_holiday_calendar WHERE holiday_code=? AND id<>? LIMIT 1",array($code,$id)))hc_json('error','Holiday Code sudah digunakan.');
  $hours=hc_num(hc_p('working_hours',0));if($type!=='HALF_DAY'&&$hours>0)$type='HALF_DAY';if($hours<0)hc_json('error','Working Hours tidak boleh negatif.');
  $paid=hc_c(hc_p('paid_holiday','Y'));$rec=hc_c(hc_p('recurring_annual','N'));if(!in_array($paid,$yn,true)||!in_array($rec,$yn,true))hc_json('error','Paid/Recurring flag tidak valid.');
  $data=array('holiday_code'=>$code,'holiday_name'=>$name,'holiday_date'=>$from,'holiday_end_date'=>$to,'holiday_type'=>$type,'holiday_scope'=>$scope,'calendar_id'=>$calId,'calendar_code'=>$calCode,'plant_code'=>$plantCode,'region_code'=>trim(hc_p('region_code')),'country'=>hc_c(hc_p('country','ID')),'work_location_id'=>$locId,'working_hours'=>$hours,'paid_holiday'=>$paid,'recurring_annual'=>$rec,'source_reference'=>trim(hc_p('source_reference')),'holiday_status'=>$status,'sap_reference'=>trim(hc_p('sap_reference')),'remarks'=>trim(hc_p('remarks')),'updated_by'=>$username,'updated_at'=>date('Y-m-d H:i:s'));
  if($id>0){if(!$db->fetch("SELECT id FROM erp_holiday_calendar WHERE id=? LIMIT 1",array($id)))hc_json('error','Holiday Calendar tidak ditemukan.');$ok=$db->update('erp_holiday_calendar',$data,'id',$id);}else{$data['created_by']=$username;$ok=$db->insert('erp_holiday_calendar',$data);$id=$db->last_insert_id();}
  if(!$ok)hc_json('error',$db->getErrorMessage()?:'Holiday Calendar gagal disimpan.');$applied=0;$row=hc_row($id);if($status==='ACTIVE'&&hc_p('apply_calendar','N')==='Y')$applied=hc_apply($row);if(function_exists('simpan_log'))simpan_log('User '.$username.' menyimpan Holiday Calendar '.$code.' pada '.date('Y-m-d H:i:s'),$username);hc_json('good','Holiday Calendar berhasil disimpan.',array('id'=>$id,'applied'=>$applied));
case 'apply':$id=(int)hc_p('id');$r=hc_row($id);if(!$r)hc_json('error','Holiday Calendar tidak ditemukan.');if($r->holiday_status!=='ACTIVE')hc_json('error','Hanya holiday ACTIVE yang bisa apply ke calendar.');$cnt=hc_apply($r);if(function_exists('simpan_log'))simpan_log('User '.$username.' apply Holiday Calendar '.$r->holiday_code.' ke Factory Calendar '.$r->calendar_code,$username);hc_json('good','Holiday berhasil diterapkan.',array('applied'=>$cnt));
case 'status':$id=(int)hc_p('id');$status=hc_c(hc_p('status'));if(!in_array($status,$stats,true))hc_json('error','Status tidak valid.');$r=$db->fetch("SELECT * FROM erp_holiday_calendar WHERE id=? LIMIT 1",array($id));if(!$r)hc_json('error','Holiday Calendar tidak ditemukan.');$db->update('erp_holiday_calendar',array('holiday_status'=>$status,'updated_by'=>$username,'updated_at'=>date('Y-m-d H:i:s')),'id',$id);hc_json('good','Status berhasil diubah.');
case 'delete':$id=(int)hc_p('id');$r=$db->fetch("SELECT * FROM erp_holiday_calendar WHERE id=? LIMIT 1",array($id));if(!$r)hc_json('error','Holiday Calendar tidak ditemukan.');if($r->holiday_status==='ACTIVE')hc_json('error','Holiday ACTIVE tidak bisa dihapus. Ubah ke INACTIVE dulu.');$db->delete('erp_holiday_calendar','id',$id);if($db->getErrorMessage())hc_json('error',$db->getErrorMessage());hc_json('good','Holiday Calendar berhasil dihapus.');
case 'detail':$r=hc_row((int)hc_p('id'));if(!$r){echo '<div class="alert alert-warning">Holiday Calendar tidak ditemukan.</div>';break;}echo '<h3 style="margin-top:0">'.hc_h($r->holiday_code).' <small>'.hc_h($r->holiday_name).'</small></h3><span class="label label-primary">'.hc_h($r->holiday_type).'</span> <span class="label label-info">'.hc_h($r->holiday_scope).'</span> <span class="label label-success">'.hc_h($r->holiday_status).'</span><hr>';echo '<div class="row"><div class="col-sm-3"><b>'.hr_h('hr_date', 'Date').'</b><br>'.hc_h($r->holiday_date.' s/d '.$r->holiday_end_date).'</div><div class="col-sm-3"><b>Calendar</b><br>'.hc_h(($r->calendar_code?:'-').' '.$r->calendar_name).'</div><div class="col-sm-3"><b>Plant / Region</b><br>'.hc_h(($r->plant_code?:'-').' / '.($r->region_code?:'-')).'</div><div class="col-sm-3"><b>Rules</b><br>Hours '.hc_h($r->working_hours).' | Paid '.hc_h($r->paid_holiday).'<br><small>Recurring '.hc_h($r->recurring_annual).'</small></div></div><hr><b>Source</b><p>'.hc_h($r->source_reference?:'-').'</p><b>'.hr_h('common_remarks', 'Remarks').'</b><p>'.nl2br(hc_h($r->remarks?:'-')).'</p>';break;
case 'export':
  $initial=ob_get_level();ob_start();error_reporting(E_ALL & ~E_NOTICE & ~E_WARNING & ~E_DEPRECATED & ~E_USER_DEPRECATED);require_once "../../inc/lib/PHPExcel.php";require_once "../../inc/excel_style_helper.php";PHPExcel_Shared_File::setUseUploadTempDirectory(true);$from=hc_g('tgl_awal',date('Y-01-01'));$to=hc_g('tgl_akhir',date('Y-12-31'));$rows=hc_rows($from,$to,hc_g('holiday_type',''),hc_g('holiday_scope',''),hc_g('holiday_status',''),hc_g('calendar_id',''),hc_g('keyword',''));$excel=new PHPExcel();$sheet=$excel->setActiveSheetIndex(0);$sheet->setTitle(erp_export_sheet_title('Holiday Calendar'));$heads=array(erp_export_label("No"),erp_export_label("Holiday Code"),erp_export_label("Holiday Name"),erp_export_label("Date From"),erp_export_label("Date To"),erp_export_label("Type"),erp_export_label("Scope"),erp_export_label("Calendar"),erp_export_label("Plant"),erp_export_label("Region"),erp_export_label("Country"),erp_export_label("Location"),erp_export_label("Working Hours"),erp_export_label("Paid"),erp_export_label("Recurring"),erp_export_label("Source Ref"),erp_export_label("Status"),erp_export_label("SAP Ref"),erp_export_label("Remarks"),erp_export_label("Updated By"));foreach($heads as $i=>$h)$sheet->setCellValue(PHPExcel_Cell::stringFromColumnIndex($i).'4',$h);$rnum=5;$n=1;foreach($rows as $r){$vals=array($n++,$r->holiday_code,$r->holiday_name,$r->holiday_date,$r->holiday_end_date,$r->holiday_type,$r->holiday_scope,($r->calendar_code?:'').' - '.($r->calendar_name?:''),$r->plant_code,$r->region_code,$r->country,($r->location_code?:'').' - '.($r->location_name?:''),$r->working_hours,$r->paid_holiday,$r->recurring_annual,$r->source_reference,$r->holiday_status,$r->sap_reference,$r->remarks,$r->updated_by?:$r->created_by);foreach($vals as $i=>$v)$sheet->setCellValue(PHPExcel_Cell::stringFromColumnIndex($i).$rnum,$v);$rnum++;}erpkb_excel_apply_standard_style($excel,array('sheet'=>$sheet,'title'=>erp_export_title('HOLIDAY CALENDAR REPORT'),'header_row'=>4,'first_data_row'=>5,'last_data_row'=>max(5,$rnum-1),'column_count'=>count($heads),'decimal_columns'=>array('M'),'filters'=>array('Date'=>$from.' s/d '.$to,'Type'=>hc_g('holiday_type',erp_export_all_text()),'Status'=>hc_g('holiday_status',erp_export_all_text()))));$tmp=erpkb_excel_temp_file('holiday_calendar_');PHPExcel_IOFactory::createWriter($excel,'Excel2007')->save($tmp);$size=@filesize($tmp);$sig=@file_get_contents($tmp,false,null,0,2);if(!$size||$sig!=='PK'){@unlink($tmp);while(ob_get_level()>$initial)ob_end_clean();echo erp_t('export_excel_invalid_file','File Excel gagal dibuat dengan benar.');exit;}while(ob_get_level()>$initial)ob_end_clean();header('Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');header('Content-Disposition: attachment; filename="holiday_calendar_'.date('Ymd_His').'.xlsx"');header('Content-Length: '.$size);header('Cache-Control: max-age=0');header('Pragma: public');readfile($tmp);@unlink($tmp);exit;
default:hc_json('error','Action tidak dikenal.');
}
?>
