<?php
if (!function_exists('sd_t')) {
  function sd_t($key, $fallback = '') { return lang_text($key, $fallback); }
}
if (!function_exists('sd_h')) {
  function sd_h($key, $fallback = '') { return htmlspecialchars((string) sd_t($key, $fallback), ENT_QUOTES, 'UTF-8'); }
}
if (!function_exists('sd_js')) {
  function sd_js($key, $fallback = '') { return json_encode(sd_t($key, $fallback), JSON_HEX_TAG | JSON_HEX_APOS | JSON_HEX_AMP | JSON_HEX_QUOT); }
}
if(session_status()===PHP_SESSION_NONE)session_start();
include "../../inc/config.php";
session_check_json();
error_reporting(E_ALL & ~E_NOTICE & ~E_WARNING & ~E_DEPRECATED & ~E_USER_DEPRECATED);
function pf_json($s,$m='',$e=array()){echo json_encode(array(array_merge(array('status'=>$s,'error_message'=>$m),$e)));exit;}
function pf_h($v){return htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');}
function pf_num($v,$d=2){return number_format((float)$v,$d,',','.');}
function pf_user(){return isset($_SESSION['username'])?$_SESSION['username']:'system';}
function pf_no(){global $db;$p='PF/'.date('Y').'/'.date('m').'/';$r=$db->fetch("SELECT MAX(no_sales_invoice) max_no FROM sales_invoice WHERE no_sales_invoice LIKE ?",array($p.'%'));$n=1;if($r&&$r->max_no){$x=explode('/',$r->max_no);$n=((int)end($x))+1;}return $p.str_pad($n,4,'0',STR_PAD_LEFT);}
function pf_source($type,$id){global $db;if($type==='QUOTATION'){return $db->fetch("SELECT 'QUOTATION' ref_type,sq.id_quotation id,sq.no_sales_quotation ref_no,'' no_sales_order,'' nopo,sq.kode_penerima bill_to,sq.kode_penerima ship_to,sq.tgl doc_date,sq.currency valuta,sq.tax,sq.term,sq.catatan,COALESCE(p.nama,sq.customer_name) customer_name,COALESCE(SUM(d.nilai),0) net_amount FROM sales_quotation sq LEFT JOIN sales_quotation_detail d ON d.id_quotation=sq.id_quotation LEFT JOIN penerima p ON p.kode_penerima=sq.kode_penerima WHERE sq.id_quotation=? GROUP BY sq.id_quotation",array($id));}return $db->fetch("SELECT 'SO' ref_type,so.id_sales_order id,so.no_sales_order ref_no,so.no_sales_order,so.no_po nopo,so.kode_penerima bill_to,so.kode_penerima ship_to,so.so_date doc_date,so.currency valuta,so.tax,so.term,so.catatan,p.nama customer_name,COALESCE(SUM(d.nilai),0) net_amount FROM sales_order so LEFT JOIN sales_order_detail d ON d.id_sales_order=so.id_sales_order LEFT JOIN penerima p ON p.kode_penerima=so.kode_penerima WHERE so.id_sales_order=? GROUP BY so.id_sales_order",array($id));}
function pf_tax_rate($tax){$t=strtolower((string)$tax);return ($t==='include'||$t==='exclude'||$t==='1')?11:0;}
function pf_items($type,$id){global $db;if($type==='QUOTATION')return $db->query("SELECT d.id_detail,d.kd_barang,d.qty,d.uom unit,d.price,d.nilai,b.nm_barang FROM sales_quotation_detail d LEFT JOIN barang b ON b.kd_barang=d.kd_barang WHERE d.id_quotation=? ORDER BY d.line_no,d.id_detail",array($id));return $db->query("SELECT d.id_detail,d.kd_barang,d.qty,'' unit,d.price,d.nilai,b.nm_barang FROM sales_order_detail d LEFT JOIN barang b ON b.kd_barang=d.kd_barang WHERE d.id_sales_order=? ORDER BY d.id_detail",array($id));}
$act=isset($_GET['act'])?$_GET['act']:'';
switch($act){
case 'get_no':header('Content-Type: application/json');echo json_encode(array('no'=>pf_no()));break;
case 'get_source':header('Content-Type: application/json');$type=$_GET['type']==='QUOTATION'?'QUOTATION':'SO';$src=pf_source($type,(int)$_GET['id']);if(!$src){echo json_encode(array('status'=>'error','error_message'=>'Source document tidak ditemukan.'));break;}$taxRate=pf_tax_rate($src->tax);$tax=round((float)$src->net_amount*$taxRate/100,2);$gross=(float)$src->net_amount+$tax;$rows=pf_items($type,(int)$_GET['id']);$html='<div class="row"><div class="col-sm-3"><strong>Source</strong><br>'.pf_h($src->ref_type.' '.$src->ref_no).'</div><div class="col-sm-3"><strong>'.sd_h('sales_customer', 'Customer').'</strong><br>'.pf_h($src->customer_name?:$src->bill_to).'</div><div class="col-sm-3"><strong>'.sd_h('sales_date', 'Date').'</strong><br>'.pf_h($src->doc_date).'</div><div class="col-sm-3"><strong>'.sd_h('sales_total', 'Total').'</strong><br>'.pf_h($src->valuta).' '.pf_num($gross).'</div></div><hr><div class="table-responsive"><table class="table table-bordered table-condensed"><thead><tr class="bg-gray"><th>'.sd_h('sales_material', 'Material').'</th><th class="text-right">'.sd_h('sales_qty', 'Qty').'</th><th class="text-right">'.sd_h('sales_price', 'Price').'</th><th class="text-right">'.sd_h('sales_amount', 'Amount').'</th></tr></thead><tbody>';foreach($rows as $r)$html.='<tr><td><strong>'.pf_h($r->kd_barang).'</strong><br><small>'.pf_h($r->nm_barang).'</small></td><td class="text-right">'.pf_num($r->qty,4).'</td><td class="text-right">'.pf_num($r->price).'</td><td class="text-right">'.pf_num($r->nilai).'</td></tr>';$html.='</tbody></table></div>';echo json_encode(array('status'=>'good','bill_to'=>$src->bill_to,'ship_to'=>$src->ship_to,'reference_no'=>$src->ref_no,'no_sales_order'=>$src->no_sales_order,'nopo'=>$src->nopo,'valuta'=>$src->valuta?:'IDR','tax'=>$taxRate>0?'1':'0','net_amount'=>(float)$src->net_amount,'tax_amount'=>$tax,'gross_amount'=>$gross,'html'=>$html));break;
case 'in':$type=$_POST['reference_type']==='QUOTATION'?'QUOTATION':'SO';$srcId=$type==='QUOTATION'?(int)$_POST['quotation_id']:(int)$_POST['sales_order_id'];$src=pf_source($type,$srcId);if(!$src)pf_json('error','Source document tidak ditemukan.');$no=trim($_POST['no_sales_invoice']);if($no==='')$no=pf_no();if($db->fetch("SELECT id_sales FROM sales_invoice WHERE no_sales_invoice=? LIMIT 1",array($no)))pf_json('error','Nomor Proforma sudah dipakai.');$taxRate=pf_tax_rate($src->tax);$net=(float)$_POST['net_amount'];$tax=(float)$_POST['tax_amount'];$gross=(float)$_POST['gross_amount'];$date=$_POST['invoice_date']?:date('Y-m-d');$data=array('billing_type'=>'PF','reference_type'=>$type,'reference_no'=>$src->ref_no,'bill_to'=>$src->bill_to,'ship_to'=>$src->ship_to,'invoice_date'=>$date,'posting_date'=>null,'invoice_no'=>'','no_sales_order'=>$src->no_sales_order,'no_sales_invoice'=>$no,'nopo'=>$src->nopo,'ttd'=>$_POST['ttd'],'term'=>$src->term,'due_date'=>null,'valuta'=>$src->valuta?:'IDR','ship_date'=>null,'catatan'=>$_POST['catatan'],'no_do'=>null,'bank_detail'=>function_exists('infokb')?infokb()->bank:'','tax'=>$taxRate>0?'1':'0','tax_code'=>$taxRate>0?'PPN11':'NON_TAX','tax_rate'=>$taxRate,'net_amount'=>$net,'tax_amount'=>$tax,'gross_amount'=>$gross,'billing_status'=>'POSTED','proforma_valid_until'=>$_POST['proforma_valid_until'],'created_by'=>pf_user(),'posted_by'=>pf_user(),'posted_at'=>date('Y-m-d H:i:s'));if(!$db->insert('sales_invoice',$data))pf_json('error',$db->getErrorMessage()?:sd_t('sales_proforma_save_failed', 'Proforma failed to save.'));$id=$db->last_insert_id();$line=10;foreach(pf_items($type,$srcId) as $it){$lineTax=round((float)$it->nilai*$taxRate/100,2);$db->insert('sales_invoice_detail',array('id_sales'=>$id,'line_no'=>$line,'billing_item_type'=>'PROFORMA','kd_barang'=>$it->kd_barang,'nm_barang'=>$it->nm_barang,'qty'=>$it->qty,'harga'=>$it->price,'unit'=>$it->unit?:'PCS','nilai'=>$it->nilai,'tax_code'=>$taxRate>0?'PPN11':'NON_TAX','tax_rate'=>$taxRate,'tax_amount'=>$lineTax,'gross_amount'=>(float)$it->nilai+$lineTax));$line+=10;}if(function_exists('simpan_log'))simpan_log('User '.pf_user().' issue Proforma Invoice '.$no.' dari '.$type.' '.$src->ref_no.' pada '.date('Y-m-d H:i:s'),pf_user());pf_json('good','',array('id'=>$id,'proforma_no'=>$no));break;
case 'cancel':$id=(int)$_POST['id'];$reason=trim($_POST['reason']);$h=$db->fetch("SELECT * FROM sales_invoice WHERE id_sales=? AND billing_type='PF' LIMIT 1",array($id));if(!$h)pf_json('error','Proforma tidak ditemukan.');if($h->billing_status!=='POSTED')pf_json('error','Hanya proforma ISSUED yang bisa dicancel.');if($reason==='')pf_json('error','Alasan cancel wajib diisi.');$db->update('sales_invoice',array('billing_status'=>'CANCELLED','cancelled_by'=>pf_user(),'cancelled_at'=>date('Y-m-d H:i:s'),'cancel_reason'=>$reason),'id_sales',$id);if(function_exists('simpan_log'))simpan_log('User '.pf_user().' cancel Proforma Invoice '.$h->no_sales_invoice.' alasan '.$reason.' pada '.date('Y-m-d H:i:s'),pf_user());pf_json('good','');break;
case 'detail':$id=(int)$_POST['id'];$h=$db->fetch("SELECT si.*,p.nama customer_name FROM sales_invoice si LEFT JOIN penerima p ON p.kode_penerima=si.bill_to WHERE si.id_sales=? AND si.billing_type='PF' LIMIT 1",array($id));if(!$h){echo '<div class="alert alert-warning">Proforma tidak ditemukan.</div>';break;}echo '<h3 style="margin-top:0">'.pf_h($h->no_sales_invoice).' <small>'.pf_h($h->billing_status==='POSTED'?'ISSUED':$h->billing_status).'</small></h3><div class="row"><div class="col-sm-3"><strong>'.sd_h('sales_customer', 'Customer').'</strong><br>'.pf_h($h->customer_name?:$h->bill_to).'</div><div class="col-sm-3"><strong>'.sd_h('sales_reference', 'Reference').'</strong><br>'.pf_h($h->reference_type.' '.$h->reference_no).'</div><div class="col-sm-3"><strong>Valid Until</strong><br>'.pf_h($h->proforma_valid_until?:'-').'</div><div class="col-sm-3"><strong>'.sd_h('sales_total', 'Total').'</strong><br>'.pf_h($h->valuta).' '.pf_num($h->gross_amount).'</div></div><hr>';echo '<table class="table table-bordered table-condensed"><thead><tr class="bg-gray"><th>'.sd_h('sales_material', 'Material').'</th><th class="text-right">'.sd_h('sales_qty', 'Qty').'</th><th>'.sd_h('sales_uom', 'UOM').'</th><th class="text-right">'.sd_h('sales_price', 'Price').'</th><th class="text-right">'.sd_h('sales_amount', 'Amount').'</th></tr></thead><tbody>';foreach($db->query("SELECT * FROM sales_invoice_detail WHERE id_sales=? ORDER BY line_no,id_sales_detail",array($id)) as $r)echo '<tr><td><strong>'.pf_h($r->kd_barang).'</strong><br><small>'.pf_h($r->nm_barang).'</small></td><td class="text-right">'.pf_num($r->qty,4).'</td><td>'.pf_h($r->unit).'</td><td class="text-right">'.pf_num($r->harga).'</td><td class="text-right">'.pf_num($r->nilai).'</td></tr>';echo '</tbody></table>';if($h->cancel_reason)echo '<div class="alert alert-warning"><strong>Cancel Reason:</strong> '.pf_h($h->cancel_reason).'</div>';break;
case 'excel':$initial=ob_get_level();ob_start();require_once "../../inc/lib/PHPExcel.php";require_once "../../inc/excel_style_helper.php";PHPExcel_Shared_File::setUseUploadTempDirectory(true);$from=!empty($_GET['tgl_awal'])?$_GET['tgl_awal']:date('Y-m-01');$to=!empty($_GET['tgl_akhir'])?$_GET['tgl_akhir']:date('Y-m-d');$p=array($from,$to);$w=" WHERE si.billing_type='PF' AND si.invoice_date BETWEEN ? AND ? ";if(!empty($_GET['customer'])){$w.=" AND si.bill_to=? ";$p[]=$_GET['customer'];}if(!empty($_GET['ref_type'])){$w.=" AND si.reference_type=? ";$p[]=$_GET['ref_type'];}if(!empty($_GET['status'])){$w.=" AND si.billing_status=? ";$p[]=$_GET['status'];}$rows=$db->query("SELECT si.*,p.nama customer_name FROM sales_invoice si LEFT JOIN penerima p ON p.kode_penerima=si.bill_to $w ORDER BY si.invoice_date DESC,si.id_sales DESC",$p);$excel=new PHPExcel();$sh=$excel->setActiveSheetIndex(0);$sh->setTitle(erp_export_sheet_title('Proforma Invoice'));$heads=array(erp_export_label("No"),erp_export_label("Proforma No"),erp_export_label("Date"),erp_export_label("Customer"),erp_export_label("Source"),erp_export_label("Reference"),erp_export_label("Currency"),erp_export_label("Valid Until"),erp_export_label("DPP"),erp_export_label("PPN"),erp_export_label("Gross"),erp_export_label("Status"),erp_export_label("Created By"),erp_export_label("Notes"));foreach($heads as $i=>$v)$sh->setCellValue(PHPExcel_Cell::stringFromColumnIndex($i).'4',$v);$r=5;$n=1;foreach($rows as $row){$vals=array($n++,$row->no_sales_invoice,$row->invoice_date,$row->customer_name?:$row->bill_to,$row->reference_type,$row->reference_no,$row->valuta,$row->proforma_valid_until,(float)$row->net_amount,(float)$row->tax_amount,(float)$row->gross_amount,$row->billing_status,$row->created_by,$row->catatan);foreach($vals as $i=>$v)$sh->setCellValue(PHPExcel_Cell::stringFromColumnIndex($i).$r,$v);$r++;}erpkb_excel_apply_standard_style($excel,array('sheet'=>$sh,'title'=>erp_export_title('PROFORMA INVOICE'),'header_row'=>4,'first_data_row'=>5,'last_data_row'=>max(5,$r-1),'column_count'=>14,'numeric_columns'=>array('I','J','K'),'filters'=>array('Date'=>$from.' s/d '.$to)));$tmp=erpkb_excel_temp_file('proforma_invoice_');PHPExcel_IOFactory::createWriter($excel,'Excel2007')->save($tmp);$size=@filesize($tmp);$sig=@file_get_contents($tmp,false,null,0,2);if(!$size||$sig!=='PK'){@unlink($tmp);while(ob_get_level()>$initial)ob_end_clean();header('Content-Type:text/plain; charset=utf-8');echo erp_t('export_excel_invalid_file','File Excel gagal dibuat dengan benar.');exit;}while(ob_get_level()>$initial)ob_end_clean();header('Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');header('Content-Disposition: attachment; filename="proforma_invoice_'.date('Ymd_His').'.xlsx"');header('Content-Length: '.$size);header('Cache-Control: max-age=0');header('Pragma: public');readfile($tmp);@unlink($tmp);exit;
default:header('Content-Type: application/json');echo json_encode(array('status'=>'error','error_message'=>'Action tidak dikenal.'));
}
?>
