<?php
if (!function_exists('hr_t')) {
  function hr_t($key, $fallback = '') { return lang_text($key, $fallback); }
}
if (!function_exists('hr_h')) {
  function hr_h($key, $fallback = '') { return htmlspecialchars((string) hr_t($key, $fallback), ENT_QUOTES, 'UTF-8'); }
}
if (!function_exists('hr_js')) {
  function hr_js($key, $fallback = '') { return json_encode(hr_t($key, $fallback), JSON_HEX_TAG | JSON_HEX_APOS | JSON_HEX_AMP | JSON_HEX_QUOT); }
}
if (session_status() === PHP_SESSION_NONE) session_start();
include "../../inc/config.php";
session_check_json();
function eed_h($v){return htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');}
function eed_label($s,$kind='status'){$map=$kind==='verified'?array('PENDING'=>'warning','VERIFIED'=>'success','REJECTED'=>'danger'):array('ACTIVE'=>'success','INACTIVE'=>'warning');$c=isset($map[$s])?$map[$s]:'default';return '<span class="label label-'.$c.'">'.eed_h($s).'</span>';}
$draw=isset($_POST['draw'])?(int)$_POST['draw']:1;$start=isset($_POST['start'])?max(0,(int)$_POST['start']):0;$length=isset($_POST['length'])?(int)$_POST['length']:25;if($length<=0||$length>500)$length=25;
$from=isset($_POST['tgl_awal'])&&$_POST['tgl_awal']!==''?$_POST['tgl_awal']:date('Y-01-01');$to=isset($_POST['tgl_akhir'])&&$_POST['tgl_akhir']!==''?$_POST['tgl_akhir']:'9999-12-31';$level=isset($_POST['education_level'])?trim($_POST['education_level']):'';$type=isset($_POST['education_type'])?trim($_POST['education_type']):'';$verified=isset($_POST['verified_status'])?trim($_POST['verified_status']):'';$highest=isset($_POST['highest_education'])?trim($_POST['highest_education']):'';$status=isset($_POST['status'])?trim($_POST['status']):'';$kw=isset($_POST['keyword'])?trim($_POST['keyword']):'';
$w=" WHERE ed.effective_from<=? AND ed.effective_to>=? ";$p=array($to,$from);if($level!==''){$w.=" AND ed.education_level=? ";$p[]=$level;}if($type!==''){$w.=" AND ed.education_type=? ";$p[]=$type;}if($verified!==''){$w.=" AND ed.verified_status=? ";$p[]=$verified;}if($highest!==''){$w.=" AND ed.highest_education=? ";$p[]=$highest;}if($status!==''){$w.=" AND ed.status=? ";$p[]=$status;}if($kw!==''){$like='%'.$kw.'%';$w.=" AND (ed.education_no LIKE ? OR ed.institution_name LIKE ? OR ed.major LIKE ? OR e.employee_no LIKE ? OR e.full_name LIKE ? OR ed.certificate_no LIKE ?) ";array_push($p,$like,$like,$like,$like,$like,$like);}
$kpi=$db->fetch("SELECT COUNT(*) total,SUM(status='ACTIVE') active,SUM(highest_education='Y') highest,SUM(verified_status='VERIFIED') verified,SUM(verified_status='PENDING') pending FROM erp_employee_education");
$cnt=$db->fetch("SELECT COUNT(*) jml FROM erp_employee_education ed JOIN erp_employee_master e ON e.id=ed.employee_id $w",$p);$total=$cnt?(int)$cnt->jml:0;
$orderMap=array(2=>'ed.education_no',3=>'e.employee_no',4=>'ed.education_level',5=>'ed.education_type',6=>'ed.institution_name',7=>'ed.graduation_year',8=>'ed.verified_status',9=>'ed.status',10=>'ed.updated_at');$orderBy='e.employee_no,ed.highest_education DESC,ed.graduation_year DESC';if(isset($_POST['order'][0]['column'])){$col=(int)$_POST['order'][0]['column'];$dir=(isset($_POST['order'][0]['dir'])&&strtolower($_POST['order'][0]['dir'])==='desc')?'DESC':'ASC';if(isset($orderMap[$col]))$orderBy=$orderMap[$col].' '.$dir;}
$rows=$db->query("SELECT ed.*,e.employee_no,e.full_name,e.department_code,d.nm_dept,j.job_title_code,j.job_title_name,v.employee_no verifier_no,v.full_name verifier_name FROM erp_employee_education ed JOIN erp_employee_master e ON e.id=ed.employee_id LEFT JOIN dept d ON d.kd_dept=e.department_code LEFT JOIN erp_job_title j ON j.id=e.job_title_id LEFT JOIN erp_employee_master v ON v.id=ed.verified_by_employee_id $w ORDER BY $orderBy LIMIT $start,$length",$p);
$data=array();$no=$start+1;foreach($rows as $r){$next=$r->status==='ACTIVE'?'INACTIVE':'ACTIVE';$btn=$r->status==='ACTIVE'?'warning':'success';$icon=$r->status==='ACTIVE'?'fa-ban':'fa-check';$act='<div class="ee-action"><button class="btn btn-info btn-xs btn-ee-detail" data-id="'.(int)$r->id.'" title="'.hr_h('common_detail', 'Detail').'"><i class="fa fa-eye"></i></button> <button class="btn btn-primary btn-xs btn-ee-edit" data-id="'.(int)$r->id.'" title="'.hr_h('common_edit', 'Edit').'"><i class="fa fa-pencil"></i></button> <button class="btn btn-'.$btn.' btn-xs btn-ee-status" data-id="'.(int)$r->id.'" data-status="'.$next.'" title="'.$next.'"><i class="fa '.$icon.'"></i></button> <button class="btn btn-danger btn-xs btn-ee-delete" data-id="'.(int)$r->id.'" data-no="'.eed_h($r->education_no).'" title="'.hr_h('common_delete', 'Delete').'"><i class="fa fa-trash"></i></button></div>';
  $data[]=array($no++,$act,'<strong>'.eed_h($r->education_no).'</strong><br><small>SAP: '.eed_h($r->sap_reference?:'-').'</small>','<strong>'.eed_h($r->employee_no).'</strong><br><small>'.eed_h($r->full_name).'</small><br><small>'.eed_h($r->department_code?:'-').' '.eed_h($r->nm_dept?:'').'</small>','<strong>'.eed_h($r->education_level).'</strong><br><small>'.eed_h($r->education_type).'</small>','<strong>'.eed_h($r->institution_name).'</strong><br><small>'.eed_h($r->city?:'-').' '.$r->country.'</small>',eed_h(($r->major?:'-').' / '.($r->faculty?:'-')).'<br><small>Cert: '.eed_h($r->certificate_no?:'-').'</small>',eed_h(($r->start_year?:'-').' - '.($r->graduation_year?:'-')).'<br><small>GPA/Score: '.eed_h(($r->gpa?:'-').'/'.($r->score?:'-')).'</small>',eed_label($r->verified_status,'verified').'<br><small>Highest: '.eed_h($r->highest_education).' | Relevant: '.eed_h($r->relevant_to_position).'</small>',eed_label($r->status),eed_h($r->updated_by?:$r->created_by?:'-').'<br><small>'.eed_h($r->updated_at?:$r->created_at).'</small>');}
header('Content-Type: application/json; charset=utf-8');echo json_encode(array('draw'=>$draw,'recordsTotal'=>$total,'recordsFiltered'=>$total,'data'=>$data,'kpi'=>array('total'=>$kpi?(int)$kpi->total:0,'active'=>$kpi?(int)$kpi->active:0,'highest'=>$kpi?(int)$kpi->highest:0,'verified'=>$kpi?(int)$kpi->verified:0,'pending'=>$kpi?(int)$kpi->pending:0)));
?>
