<?php
if (!function_exists('hr_t')) {
  function hr_t($key, $fallback = '') { return lang_text($key, $fallback); }
}
if (!function_exists('hr_h')) {
  function hr_h($key, $fallback = '') { return htmlspecialchars((string) hr_t($key, $fallback), ENT_QUOTES, 'UTF-8'); }
}
if (!function_exists('hr_js')) {
  function hr_js($key, $fallback = '') { return json_encode(hr_t($key, $fallback), JSON_HEX_TAG | JSON_HEX_APOS | JSON_HEX_AMP | JSON_HEX_QUOT); }
}
if (session_status() === PHP_SESSION_NONE) session_start();
include "../../inc/config.php";
session_check_json();
function ee_json($s,$m='',$x=array()){header('Content-Type: application/json; charset=utf-8');$p=array('status'=>$s);if($m!=='')$p[$s==='good'?'message':'error_message']=$m;foreach($x as $k=>$v)$p[$k]=$v;echo json_encode($p);exit;}
function ee_h($v){return htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');}
function ee_p($k,$d=''){return isset($_POST[$k])?$_POST[$k]:$d;}
function ee_g($k,$d=''){return isset($_GET[$k])?$_GET[$k]:$d;}
function ee_c($v){return strtoupper(trim((string)$v));}
function ee_user(){return isset($_SESSION['username'])&&$_SESSION['username']!==''?$_SESSION['username']:'system';}
function ee_select2($rows,$id,$cb){$out=array();foreach($rows as $r)$out[]=array('id'=>$r->$id,'text'=>$cb($r));header('Content-Type: application/json; charset=utf-8');echo json_encode(array('results'=>$out));exit;}
function ee_row($id){global $db;return $db->fetch("SELECT ed.*,e.employee_no,e.full_name,e.department_code,d.nm_dept,j.job_title_code,j.job_title_name,v.employee_no verifier_no,v.full_name verifier_name FROM erp_employee_education ed JOIN erp_employee_master e ON e.id=ed.employee_id LEFT JOIN dept d ON d.kd_dept=e.department_code LEFT JOIN erp_job_title j ON j.id=e.job_title_id LEFT JOIN erp_employee_master v ON v.id=ed.verified_by_employee_id WHERE ed.id=? LIMIT 1",array((int)$id));}
function ee_payload($r){$d=(array)$r;$d['employee_text']=$r->employee_id?($r->employee_no.' - '.$r->full_name):'';$d['verified_by_text']=$r->verified_by_employee_id?($r->verifier_no.' - '.$r->verifier_name):'';return $d;}
function ee_rows($from,$to,$level,$type,$verified,$highest,$status,$kw){global $db;$w=" WHERE ed.effective_from<=? AND ed.effective_to>=? ";$p=array($to,$from);if($level!==''){$w.=" AND ed.education_level=? ";$p[]=$level;}if($type!==''){$w.=" AND ed.education_type=? ";$p[]=$type;}if($verified!==''){$w.=" AND ed.verified_status=? ";$p[]=$verified;}if($highest!==''){$w.=" AND ed.highest_education=? ";$p[]=$highest;}if($status!==''){$w.=" AND ed.status=? ";$p[]=$status;}if($kw!==''){$like='%'.$kw.'%';$w.=" AND (ed.education_no LIKE ? OR ed.institution_name LIKE ? OR ed.major LIKE ? OR e.employee_no LIKE ? OR e.full_name LIKE ? OR ed.certificate_no LIKE ?) ";array_push($p,$like,$like,$like,$like,$like,$like);}return $db->query("SELECT ed.*,e.employee_no,e.full_name,e.department_code,d.nm_dept,j.job_title_code,j.job_title_name,v.employee_no verifier_no,v.full_name verifier_name FROM erp_employee_education ed JOIN erp_employee_master e ON e.id=ed.employee_id LEFT JOIN dept d ON d.kd_dept=e.department_code LEFT JOIN erp_job_title j ON j.id=e.job_title_id LEFT JOIN erp_employee_master v ON v.id=ed.verified_by_employee_id $w ORDER BY e.employee_no,ed.highest_education DESC,ed.graduation_year DESC",$p);}
$act=isset($_GET['act'])?$_GET['act']:'';$username=ee_user();
$levels=array('SD','SMP','SMA_SMK','D1','D2','D3','D4','S1','S2','S3','PROFESSIONAL','CERTIFICATION','OTHER');$types=array('FORMAL','NON_FORMAL','CERTIFICATION','TRAINING','LICENSE');$verified=array('PENDING','VERIFIED','REJECTED');
switch($act){
case 'employee_search':$t=trim(ee_p('term'));$like='%'.$t.'%';$rows=$db->query("SELECT id,employee_no,full_name,employment_status FROM erp_employee_master WHERE employment_status IN ('ACTIVE','PROBATION','CONTRACT') AND (?='' OR employee_no LIKE ? OR full_name LIKE ?) ORDER BY employee_no LIMIT 30",array($t,$like,$like));ee_select2($rows,'id',function($r){return $r->employee_no.' - '.$r->full_name.' ['.$r->employment_status.']';});break;
case 'get':$r=ee_row((int)ee_p('id'));if(!$r)ee_json('error','Employee Education tidak ditemukan.');ee_json('good','',array('data'=>ee_payload($r)));break;
case 'save':
  $id=(int)ee_p('id');$no=ee_c(ee_p('education_no'));$emp=(int)ee_p('employee_id');$level=ee_c(ee_p('education_level'));$type=ee_c(ee_p('education_type'));$inst=trim(ee_p('institution_name'));$ver=ee_c(ee_p('verified_status','PENDING'));$highest=ee_c(ee_p('highest_education','N'));$relevant=ee_c(ee_p('relevant_to_position','N'));$from=trim(ee_p('effective_from'));$to=trim(ee_p('effective_to','9999-12-31'));$status=ee_c(ee_p('status','ACTIVE'));
  if($no==='')ee_json('error','Education No wajib diisi.');if(!preg_match('/^[A-Z0-9_-]{3,30}$/',$no))ee_json('error','Education No hanya boleh huruf besar, angka, underscore, atau dash.');if(!$emp)ee_json('error','Employee wajib dipilih.');if($inst==='')ee_json('error','Institution Name wajib diisi.');if(!in_array($level,$levels,true))ee_json('error','Education Level tidak valid.');if(!in_array($type,$types,true))ee_json('error','Education Type tidak valid.');if(!in_array($ver,$verified,true))ee_json('error','Verified Status tidak valid.');foreach(array($highest,$relevant) as $v){if(!in_array($v,array('Y','N'),true))ee_json('error','Flag Y/N tidak valid.');}if($from===''||$to==='')ee_json('error','Effective From/To wajib diisi.');if(strtotime($to)<strtotime($from))ee_json('error','Effective To tidak boleh sebelum Effective From.');if(!in_array($status,array('ACTIVE','INACTIVE'),true))ee_json('error','Status tidak valid.');if(!$db->fetch("SELECT id FROM erp_employee_master WHERE id=? LIMIT 1",array($emp)))ee_json('error','Employee tidak valid.');if($db->fetch("SELECT id FROM erp_employee_education WHERE education_no=? AND id<>? LIMIT 1",array($no,$id)))ee_json('error','Education No sudah digunakan.');
  if($highest==='Y')$db->query("UPDATE erp_employee_education SET highest_education='N',updated_by=?,updated_at=NOW() WHERE employee_id=? AND id<>?",array($username,$emp,$id));
  $data=array('education_no'=>$no,'employee_id'=>$emp,'education_level'=>$level,'education_type'=>$type,'institution_name'=>$inst,'major'=>trim(ee_p('major')),'faculty'=>trim(ee_p('faculty')),'city'=>trim(ee_p('city')),'country'=>ee_c(ee_p('country','ID')),'start_year'=>trim(ee_p('start_year'))?:null,'graduation_year'=>trim(ee_p('graduation_year'))?:null,'certificate_no'=>trim(ee_p('certificate_no')),'gpa'=>trim(ee_p('gpa')),'score'=>trim(ee_p('score')),'highest_education'=>$highest,'relevant_to_position'=>$relevant,'verified_status'=>$ver,'verified_by_employee_id'=>ee_p('verified_by_employee_id')!==''?(int)ee_p('verified_by_employee_id'):null,'verified_at'=>trim(ee_p('verified_at'))?:null,'document_ref'=>trim(ee_p('document_ref')),'effective_from'=>$from,'effective_to'=>$to,'status'=>$status,'sap_reference'=>trim(ee_p('sap_reference')),'remarks'=>trim(ee_p('remarks')),'updated_by'=>$username,'updated_at'=>date('Y-m-d H:i:s'));
  if($id>0){if(!$db->fetch("SELECT id FROM erp_employee_education WHERE id=? LIMIT 1",array($id)))ee_json('error','Employee Education tidak ditemukan.');$ok=$db->update('erp_employee_education',$data,'id',$id);}else{$data['created_by']=$username;$ok=$db->insert('erp_employee_education',$data);$id=$db->last_insert_id();}
  if(!$ok)ee_json('error',$db->getErrorMessage()?:'Employee Education gagal disimpan.');if(function_exists('simpan_log'))simpan_log('User '.$username.' menyimpan Employee Education '.$no.' pada '.date('Y-m-d H:i:s'),$username);ee_json('good','Employee Education berhasil disimpan.',array('id'=>$id));
case 'delete':$id=(int)ee_p('id');$r=$db->fetch("SELECT * FROM erp_employee_education WHERE id=? LIMIT 1",array($id));if(!$r)ee_json('error','Employee Education tidak ditemukan.');$db->delete('erp_employee_education','id',$id);if($db->getErrorMessage())ee_json('error',$db->getErrorMessage());if(function_exists('simpan_log'))simpan_log('User '.$username.' menghapus Employee Education '.$r->education_no,$username);ee_json('good','Employee Education berhasil dihapus.');
case 'status':$id=(int)ee_p('id');$status=ee_c(ee_p('status'));if(!in_array($status,array('ACTIVE','INACTIVE'),true))ee_json('error','Status tidak valid.');$r=$db->fetch("SELECT * FROM erp_employee_education WHERE id=? LIMIT 1",array($id));if(!$r)ee_json('error','Employee Education tidak ditemukan.');$ok=$db->update('erp_employee_education',array('status'=>$status,'updated_by'=>$username,'updated_at'=>date('Y-m-d H:i:s')),'id',$id);if(!$ok)ee_json('error',$db->getErrorMessage()?:'Status gagal diubah.');ee_json('good','Status berhasil diubah.');
case 'detail':$r=ee_row((int)ee_p('id'));if(!$r){echo '<div class="alert alert-warning">Employee Education tidak ditemukan.</div>';break;}echo '<h3 style="margin-top:0">'.ee_h($r->education_no).' <small>'.ee_h($r->institution_name).'</small></h3><span class="label label-success">'.ee_h($r->status).'</span> <span class="label label-info">'.ee_h($r->education_level.' / '.$r->education_type).'</span> <span class="label label-primary">'.ee_h($r->verified_status).'</span><hr>';echo '<div class="row"><div class="col-sm-3"><b>'.hr_h('hr_employee', 'Employee').'</b><br>'.ee_h($r->employee_no.' - '.$r->full_name).'</div><div class="col-sm-3"><b>Major / Faculty</b><br>'.ee_h(($r->major?:'-').' / '.($r->faculty?:'-')).'</div><div class="col-sm-3"><b>'.hr_h('hr_period', 'Period').'</b><br>'.ee_h(($r->start_year?:'-').' - '.($r->graduation_year?:'-')).'</div><div class="col-sm-3"><b>Certificate</b><br>'.ee_h($r->certificate_no?:'-').'</div></div><hr>';echo '<div class="row"><div class="col-sm-3"><b>GPA / Score</b><br>'.ee_h(($r->gpa?:'-').' / '.($r->score?:'-')).'</div><div class="col-sm-3"><b>Highest</b><br>'.ee_h($r->highest_education).'</div><div class="col-sm-3"><b>Relevant</b><br>'.ee_h($r->relevant_to_position).'</div><div class="col-sm-3"><b>Verified By</b><br>'.ee_h($r->verifier_no?($r->verifier_no.' - '.$r->verifier_name):'-').'</div></div><hr><b>'.hr_h('hr_document', 'Document').'</b><p>'.ee_h($r->document_ref?:'-').'</p><b>'.hr_h('common_remarks', 'Remarks').'</b><p>'.nl2br(ee_h($r->remarks?:'-')).'</p>';break;
case 'export':
  $initial=ob_get_level();ob_start();error_reporting(E_ALL & ~E_NOTICE & ~E_WARNING & ~E_DEPRECATED & ~E_USER_DEPRECATED);require_once "../../inc/lib/PHPExcel.php";require_once "../../inc/excel_style_helper.php";PHPExcel_Shared_File::setUseUploadTempDirectory(true);$from=ee_g('tgl_awal',date('Y-01-01'));$to=ee_g('tgl_akhir','9999-12-31');$rows=ee_rows($from,$to,ee_g('education_level',''),ee_g('education_type',''),ee_g('verified_status',''),ee_g('highest_education',''),ee_g('status',''),ee_g('keyword',''));$excel=new PHPExcel();$sheet=$excel->setActiveSheetIndex(0);$sheet->setTitle(erp_export_sheet_title('Education'));$heads=array(erp_export_label("No"),erp_export_label("Education No"),erp_export_label("Employee"),erp_export_label("Level"),erp_export_label("Type"),erp_export_label("Institution"),erp_export_label("Major"),erp_export_label("Faculty"),erp_export_label("City"),erp_export_label("Country"),erp_export_label("Start"),erp_export_label("Graduation"),erp_export_label("Certificate"),erp_export_label("GPA"),erp_export_label("Score"),erp_export_label("Highest"),erp_export_label("Relevant"),erp_export_label("Verified"),erp_export_label("Verifier"),erp_export_label("Effective"),erp_export_label("Status"),erp_export_label("Document"),erp_export_label("SAP Ref"),erp_export_label("Updated By"));foreach($heads as $i=>$h)$sheet->setCellValue(PHPExcel_Cell::stringFromColumnIndex($i).'4',$h);$rnum=5;$n=1;foreach($rows as $r){$vals=array($n++,$r->education_no,$r->employee_no.' - '.$r->full_name,$r->education_level,$r->education_type,$r->institution_name,$r->major,$r->faculty,$r->city,$r->country,$r->start_year,$r->graduation_year,$r->certificate_no,$r->gpa,$r->score,$r->highest_education,$r->relevant_to_position,$r->verified_status,$r->verifier_no.' - '.$r->verifier_name,$r->effective_from.' s/d '.$r->effective_to,$r->status,$r->document_ref,$r->sap_reference,$r->updated_by?:$r->created_by);foreach($vals as $i=>$v)$sheet->setCellValue(PHPExcel_Cell::stringFromColumnIndex($i).$rnum,$v);$rnum++;}erpkb_excel_apply_standard_style($excel,array('sheet'=>$sheet,'title'=>erp_export_title('EMPLOYEE EDUCATION REPORT'),'header_row'=>4,'first_data_row'=>5,'last_data_row'=>max(5,$rnum-1),'column_count'=>count($heads),'filters'=>array('Effective'=>$from.' s/d '.$to)));$tmp=erpkb_excel_temp_file('employee_education_');PHPExcel_IOFactory::createWriter($excel,'Excel2007')->save($tmp);$size=@filesize($tmp);$sig=@file_get_contents($tmp,false,null,0,2);if(!$size||$sig!=='PK'){@unlink($tmp);while(ob_get_level()>$initial)ob_end_clean();echo erp_t('export_excel_invalid_file','File Excel gagal dibuat dengan benar.');exit;}while(ob_get_level()>$initial)ob_end_clean();header('Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');header('Content-Disposition: attachment; filename="employee_education_'.date('Ymd_His').'.xlsx"');header('Content-Length: '.$size);header('Cache-Control: max-age=0');header('Pragma: public');readfile($tmp);@unlink($tmp);exit;
default:ee_json('error','Action tidak dikenal.');
}
?>
