<?php
if (!function_exists('prod_t')) {
  function prod_t($key, $fallback = '') { return lang_text($key, $fallback); }
}
if (!function_exists('prod_h')) {
  function prod_h($key, $fallback = '') { return htmlspecialchars((string) prod_t($key, $fallback), ENT_QUOTES, 'UTF-8'); }
}
if (!function_exists('prod_js')) {
  function prod_js($key, $fallback = '') { return json_encode(prod_t($key, $fallback), JSON_HEX_TAG | JSON_HEX_APOS | JSON_HEX_AMP | JSON_HEX_QUOT); }
}
$today=date('Y-m-d');$defaultFrom=date('Y-m-01');$defaultTo=date('Y-m-t');
$plants=$db->query("SELECT id,plant_code,plant_name FROM erp_plant WHERE status='Aktif' ORDER BY plant_code")->fetchAll(PDO::FETCH_OBJ);
$storages=$db->query("SELECT l.storage_code,l.storage_name,p.plant_code FROM erp_storage_location l LEFT JOIN erp_plant p ON p.id=l.plant_id WHERE l.status='Aktif' ORDER BY p.plant_code,l.storage_code")->fetchAll(PDO::FETCH_OBJ);
?>
<style>
.pv-hero{background:linear-gradient(135deg,#6d28d9,#1d4ed8);color:#fff;border-radius:14px;padding:20px;margin-bottom:18px;box-shadow:0 10px 24px rgba(15,23,42,.16)}.pv-hero h1{margin:0 0 6px;font-size:26px;font-weight:700}.pv-hero p{margin:0;opacity:.92}.pv-card{border-radius:12px;background:#fff;border:1px solid #e5edf5;box-shadow:0 5px 16px rgba(15,23,42,.05);margin-bottom:14px}#dtb_production_version th,#dtb_production_version td{font-size:12px;vertical-align:middle}.select2-container{width:100%!important}.required-label:after{content:' *';color:#dd4b39}.pv-action{white-space:nowrap}.pv-pill{display:inline-block;border-radius:999px;background:#ede9fe;color:#5b21b6;padding:3px 9px;font-size:12px;margin-left:6px}#modal_pv .modal-body{max-height:calc(100vh - 185px);overflow-y:auto}.pv-source-box{background:#f8fafc;border:1px solid #e2e8f0;border-radius:10px;padding:10px;margin-bottom:10px}
</style>
<section class="content-header"><h1><?=prod_h('production_version', 'Production Version');?> <small>SAP PP Master Data</small></h1><ol class="breadcrumb"><li><a href="<?=base_index();?>"><i class="fa fa-dashboard"></i> <?=prod_h('common_home', 'Home');?></a></li><li class="active"><?=prod_h('production_version', 'Production Version');?></li></ol></section>
<section class="content">
  <div class="pv-hero"><div class="row"><div class="col-md-8"><h1>Production Version Workbench</h1><p>Satukan material, plant, BOM, routing, validity, lot size, dan default version agar MRP dan Production Order memilih proses produksi yang benar.</p></div><div class="col-md-4 text-right"><button id="btn_open_pv" class="btn btn-warning"><i class="fa fa-plus"></i> Create Production Version</button></div></div></div>
  <div class="box pv-card"><div class="box-header"><h3 class="box-title"><i class="fa fa-filter"></i> Filter Production Version</h3></div><div class="box-body"><form class="form-horizontal" onsubmit="return false;"><div class="form-group"><label class="control-label col-lg-2">Valid From</label><div class="col-lg-2"><div class="input-group date pv-date"><input id="filter_tgl_awal" class="form-control" value="<?=$defaultFrom;?>"><span class="input-group-addon"><span class="glyphicon glyphicon-calendar"></span></span></div></div><div class="col-lg-2"><div class="input-group date pv-date"><input id="filter_tgl_akhir" class="form-control" value="<?=$defaultTo;?>"><span class="input-group-addon"><span class="glyphicon glyphicon-calendar"></span></span></div></div><label class="control-label col-lg-1"><?=prod_h('production_plant', 'Plant');?></label><div class="col-lg-2"><select id="filter_plant" class="form-control"><option value=""><?=prod_h('common_all', 'All');?></option><?php foreach($plants as $p){ ?><option value="<?=htmlspecialchars($p->plant_code,ENT_QUOTES,'UTF-8');?>"><?=htmlspecialchars($p->plant_code.' - '.$p->plant_name,ENT_QUOTES,'UTF-8');?></option><?php } ?></select></div><label class="control-label col-lg-1"><?=prod_h('common_status', 'Status');?></label><div class="col-lg-2"><select id="filter_status" class="form-control"><option value=""><?=prod_h('common_all', 'All');?></option><option>DRAFT</option><option>RELEASED</option><option>INACTIVE</option><option>LOCKED</option></select></div></div><div class="form-group"><label class="control-label col-lg-2"><?=prod_h('common_search', 'Search');?></label><div class="col-lg-7"><input id="filter_keyword" class="form-control" placeholder="PV No / material / BOM / routing / description"></div><div class="col-lg-3"><button id="btn_filter_pv" class="btn btn-primary"><i class="fa fa-filter"></i> <?=prod_h('common_filter', 'Filter');?></button> <button id="btn_reset_pv" class="btn btn-default"><i class="fa fa-refresh"></i> <?=prod_h('common_reset', 'Reset');?></button> <button id="btn_export_pv" class="btn btn-success"><i class="fa fa-file-excel-o"></i> <?=prod_h('common_export_excel', 'Export Excel');?></button></div></div></form></div></div>
  <div class="box pv-card"><div class="box-body"><div class="alert alert-warning error_data_delete" style="display:none"><button type="button" class="close hide_alert_notif">&times;</button><span class="isi_warning_delete"></span></div><div class="table-responsive"><table id="dtb_production_version" class="table table-bordered table-striped" style="width:100%"><thead><tr><th><?=prod_h('common_no', 'No');?></th><th><?=prod_h('common_action', 'Action');?></th><th><?=prod_h('production_version_label', 'Version');?></th><th><?=prod_h('production_material', 'Material');?></th><th><?=prod_h('production_plant', 'Plant');?></th><th><?=prod_h('production_bom', 'BOM');?></th><th><?=prod_h('production_routing', 'Routing');?></th><th>Validity</th><th>Lot Size</th><th><?=prod_h('common_status', 'Status');?></th><th>Updated By</th></tr></thead><tbody></tbody></table></div></div></div>
  <div id="modal_pv" class="modal fade"><div class="modal-dialog modal-lg" style="width:94%"><div class="modal-content"><form id="form_pv"><input type="hidden" name="id" id="pv_id"><div class="modal-header"><button class="close" data-dismiss="modal">&times;</button><h4 class="modal-title">Create Production Version</h4></div><div class="modal-body">
    <div class="alert alert-info">Pilih material dan plant terlebih dahulu, lalu pilih BOM dan Routing yang sudah <strong>RELEASED</strong>. Production Version yang RELEASED akan menjadi referensi utama Production Order.</div>
    <div class="row"><div class="col-md-2 form-group"><label>PV No</label><input id="production_version_no" class="form-control" readonly placeholder="Loading..."></div><div class="col-md-4 form-group"><label class="required-label">Material FG/SFG</label><select name="material_code" id="material_code" class="form-control" required></select><input type="hidden" name="material_name" id="material_name"></div><div class="col-md-2 form-group"><label class="required-label"><?=prod_h('production_plant', 'Plant');?></label><select name="plant_id" id="plant_id" class="form-control" required><option value=""><?=prod_h('production_select_plant', 'Select Plant');?></option><?php foreach($plants as $p){ ?><option value="<?=intval($p->id);?>" data-code="<?=htmlspecialchars($p->plant_code,ENT_QUOTES,'UTF-8');?>"><?=htmlspecialchars($p->plant_code.' - '.$p->plant_name,ENT_QUOTES,'UTF-8');?></option><?php } ?></select><input type="hidden" name="plant_code" id="plant_code"></div><div class="col-md-1 form-group"><label class="required-label"><?=prod_h('production_version_label', 'Version');?></label><input name="version_code" id="version_code" class="form-control" value="01" required></div><div class="col-md-3 form-group"><label>Description</label><input name="version_description" id="version_description" class="form-control" placeholder="Main / alternative process"></div></div>
    <div class="row"><div class="col-md-4 form-group"><label class="required-label">Released BOM</label><select name="bom_id" id="bom_id" class="form-control" required></select><input type="hidden" name="bom_no" id="bom_no"></div><div class="col-md-4 form-group"><label class="required-label">Released Routing</label><select name="routing_id" id="routing_id" class="form-control" required></select><input type="hidden" name="routing_no" id="routing_no"></div><div class="col-md-2 form-group"><label>Default</label><select name="is_default" id="is_default" class="form-control"><option value="Y">Yes</option><option value="N"><?=prod_h('common_no', 'No');?></option></select></div><div class="col-md-2 form-group"><label>Locked</label><select name="locked" id="locked" class="form-control"><option value="N"><?=prod_h('common_no', 'No');?></option><option value="Y">Yes</option></select></div></div>
    <div class="row"><div class="col-md-2 form-group"><label class="required-label">Valid From</label><input name="valid_from" id="valid_from" class="form-control date-field" value="<?=$today;?>" required></div><div class="col-md-2 form-group"><label>Valid To</label><input name="valid_to" id="valid_to" class="form-control date-field" placeholder="Open ended"></div><div class="col-md-2 form-group"><label>Lot From</label><input type="number" step="0.00001" name="lot_size_from" id="lot_size_from" class="form-control text-right"></div><div class="col-md-2 form-group"><label>Lot To</label><input type="number" step="0.00001" name="lot_size_to" id="lot_size_to" class="form-control text-right"></div><div class="col-md-2 form-group"><label>Production Line</label><input name="production_line" id="production_line" class="form-control"></div><div class="col-md-2 form-group"><label>Procurement</label><select name="procurement_type" id="procurement_type" class="form-control"><option value="IN_HOUSE">In-house</option><option value="EXTERNAL">External</option><option value="BOTH">Both</option></select></div></div>
    <div class="pv-source-box"><span class="pv-pill">Storage default membantu GI/GR produksi, tapi tidak wajib</span></div>
    <div class="row"><div class="col-md-3 form-group"><label>Issue Storage Location</label><select name="issue_storage_location" id="issue_storage_location" class="form-control"><option value="">-</option><?php foreach($storages as $s){ ?><option value="<?=htmlspecialchars($s->storage_code,ENT_QUOTES,'UTF-8');?>"><?=htmlspecialchars(($s->plant_code?$s->plant_code.' / ':'').$s->storage_code.' - '.$s->storage_name,ENT_QUOTES,'UTF-8');?></option><?php } ?></select></div><div class="col-md-3 form-group"><label>Receipt Storage Location</label><select name="receipt_storage_location" id="receipt_storage_location" class="form-control"><option value="">-</option><?php foreach($storages as $s){ ?><option value="<?=htmlspecialchars($s->storage_code,ENT_QUOTES,'UTF-8');?>"><?=htmlspecialchars(($s->plant_code?$s->plant_code.' / ':'').$s->storage_code.' - '.$s->storage_name,ENT_QUOTES,'UTF-8');?></option><?php } ?></select></div><div class="col-md-6 form-group"><label><?=prod_h('common_remarks', 'Remarks');?></label><input name="remarks" id="remarks" class="form-control" placeholder="Catatan planning / engineering"></div></div>
  </div><div class="modal-footer"><button type="button" class="btn btn-default" data-dismiss="modal"><?=prod_h('common_cancel', 'Cancel');?></button><button type="submit" class="btn btn-primary"><i class="fa fa-save"></i> <?=prod_h('production_save_draft', 'Save Draft');?></button></div></form></div></div></div>
  <div id="modal_pv_detail" class="modal fade"><div class="modal-dialog modal-lg" style="width:96%"><div class="modal-content"><div class="modal-header"><button class="close" data-dismiss="modal">&times;</button><h4 class="modal-title">Production Version Detail</h4></div><div class="modal-body" id="pv_detail_body"></div><div class="modal-footer"><button class="btn btn-default" data-dismiss="modal"><?=prod_h('common_close', 'Close');?></button></div></div></div></div>
</section>
<script src="<?=base_admin();?>assets/plugins/select2/select2.min.js"></script><script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
<script>
function pvError(m){$('.isi_warning_delete').text(m||<?=prod_js('production_version_process_failed', 'Production Version failed to process.');?>);$('.error_data_delete').fadeIn();}
function esc(s){return String(s||'').replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c];});}
function filters(){return{tgl_awal:$('#filter_tgl_awal').val(),tgl_akhir:$('#filter_tgl_akhir').val(),status:$('#filter_status').val(),plant:$('#filter_plant').val(),keyword:$('#filter_keyword').val()};}
function resetBomRouting(){ $('#bom_id,#routing_id').html('').val('').trigger('change'); $('#bom_no,#routing_no').val(''); }
function loadNextPvNo(){ $('#production_version_no').val('Loading...'); $.post('<?=base_admin();?>modul/production_version/production_version_action.php?act=next_no',{},function(r){$('#production_version_no').val(r.status==='good'?(r.production_version_no||'Auto'):'Auto');},'json').fail(function(){$('#production_version_no').val('Auto');});}
function openForm(title,isEdit){$('#form_pv')[0].reset();$('#pv_id,#material_name,#plant_code,#bom_no,#routing_no').val('');$('#material_code,#bom_id,#routing_id').html('').trigger('change');$('#modal_pv .modal-title').text(title||'Create Production Version');$('#version_code').val('01');$('#valid_from').val('<?=$today;?>');$('#is_default').val('Y').trigger('change');$('#locked').val('N').trigger('change');$('#procurement_type').val('IN_HOUSE').trigger('change');$('#modal_pv').modal({backdrop:'static',keyboard:false});if(!isEdit)loadNextPvNo();}
$(function(){if($.fn.datepicker){$('.pv-date,.date-field').datepicker({format:'yyyy-mm-dd',autoclose:true,todayHighlight:true});}if($.fn.select2){$('#filter_plant,#filter_status,#plant_id,#is_default,#locked,#procurement_type,#issue_storage_location,#receipt_storage_location').select2({width:'100%'});$('#material_code').select2({width:'100%',dropdownParent:$('#modal_pv'),placeholder:<?=prod_js('production_search_fg_sfg', 'Search FG/SFG material...');?>,minimumInputLength:1,ajax:{url:'<?=base_admin();?>modul/production_version/production_version_action.php?act=material_search',type:'POST',dataType:'json',delay:250,data:function(p){return{term:p.term||''};},processResults:function(d){return{results:d.results||[]};}}}).on('select2:select',function(e){var d=e.params.data;$('#material_name').val(d.material_name||'');resetBomRouting();});
$('#bom_id').select2({width:'100%',dropdownParent:$('#modal_pv'),placeholder:'Pilih released BOM...',allowClear:true,ajax:{url:'<?=base_admin();?>modul/production_version/production_version_action.php?act=bom_search',type:'POST',dataType:'json',delay:250,data:function(p){return{term:p.term||'',material_code:$('#material_code').val()||'',plant_code:$('#plant_code').val()||''};},processResults:function(d){return{results:d.results||[]};}}}).on('select2:select',function(e){$('#bom_no').val(e.params.data.bom_no||'');});
$('#routing_id').select2({width:'100%',dropdownParent:$('#modal_pv'),placeholder:'Pilih released routing...',allowClear:true,ajax:{url:'<?=base_admin();?>modul/production_version/production_version_action.php?act=routing_search',type:'POST',dataType:'json',delay:250,data:function(p){return{term:p.term||'',material_code:$('#material_code').val()||'',plant_code:$('#plant_code').val()||''};},processResults:function(d){return{results:d.results||[]};}}}).on('select2:select',function(e){$('#routing_no').val(e.params.data.routing_no||'');});}
var dt=null;function reloadTable(resetPaging){if(dt&&dt.draw)dt.draw(resetPaging===false?false:undefined);}try{if($.fn.DataTable){dt=$('#dtb_production_version').DataTable({bProcessing:true,bServerSide:true,pageLength:25,dom:"<'row'<'col-sm-12'B>>"+"<'row'<'col-sm-6'l><'col-sm-6'f>>"+"<'row'<'col-sm-12'tr>>"+"<'row'<'col-sm-5'i><'col-sm-7'p>>",buttons:[{extend:'collection',text:<?=prod_js('common_export_data', 'Export Data');?>,buttons:['copyHtml5','excelHtml5','csvHtml5','pdfHtml5']}],columnDefs:[{targets:[0,1],orderable:false,searchable:false},{width:'42px',targets:0},{width:'180px',targets:1}],ajax:{url:'<?=base_admin();?>modul/production_version/production_version_data.php',type:'post',data:function(d){$.extend(d,filters());},error:function(xhr){console.log(xhr.responseText);pvError(<?=prod_js('production_version_load_failed', 'Production Version data failed to load.');?>);}}});}}catch(e){console.error(e);pvError(<?=prod_js('production_version_load_failed_create_available', 'Production Version data failed to load. Create button remains available.');?>);}
$('#btn_open_pv').click(function(){openForm('Create Production Version',false);});$('#plant_id').change(function(){$('#plant_code').val($('#plant_id option:selected').data('code')||'');resetBomRouting();});$('#btn_filter_pv').click(function(){reloadTable();});$('#filter_keyword').keyup(function(e){if(e.keyCode===13)reloadTable();});$('#btn_reset_pv').click(function(){$('#filter_tgl_awal').val('<?=$defaultFrom;?>');$('#filter_tgl_akhir').val('<?=$defaultTo;?>');$('#filter_status,#filter_plant').val('').trigger('change');$('#filter_keyword').val('');reloadTable();});$('#btn_export_pv').click(function(){window.location='<?=base_admin();?>modul/production_version/production_version_action.php?act=excel&'+$.param(filters());});$('.hide_alert_notif').click(function(){$('.error_data_delete').hide();});
$('#form_pv').submit(function(e){e.preventDefault();var btn=$(this).find('button[type=submit]');btn.prop('disabled',true).html('<i class="fa fa-spinner fa-spin"></i> <?=prod_h('common_saving', 'Saving...');?>');$.post('<?=base_admin();?>modul/production_version/production_version_action.php?act=save',$(this).serialize(),function(r){if(r.status==='good'){$('#modal_pv').modal('hide');reloadTable(false);}else pvError(r.error_message);btn.prop('disabled',false).html('<i class="fa fa-save"></i> <?=prod_h('production_save_draft', 'Save Draft');?>');},'json').fail(function(xhr){pvError(xhr.responseText);btn.prop('disabled',false).html('<i class="fa fa-save"></i> <?=prod_h('production_save_draft', 'Save Draft');?>');});});
$(document).on('click','.btn-pv-detail',function(){$.post('<?=base_admin();?>modul/production_version/production_version_action.php?act=detail',{id:$(this).data('id')},function(html){$('#pv_detail_body').html(html);$('#modal_pv_detail').modal('show');});});
$(document).on('click','.btn-pv-edit',function(){var id=$(this).data('id');$.post('<?=base_admin();?>modul/production_version/production_version_action.php?act=get',{id:id},function(r){if(r.status!=='good'){pvError(r.error_message);return;}openForm('Edit Production Version',true);var h=r.header||{};$('#pv_id').val(h.id);$('#production_version_no').val(h.production_version_no);$('#material_code').html('<option value="'+esc(h.material_code)+'" selected>'+esc(h.material_code+' - '+h.material_name)+'</option>').trigger('change');$('#material_name').val(h.material_name);$('#plant_id').val(h.plant_id||'').trigger('change');$('#plant_code').val(h.plant_code||'');$('#version_code').val(h.version_code);$('#version_description').val(h.version_description);$('#bom_id').html('<option value="'+esc(h.bom_id)+'" selected>'+esc(h.bom_no)+'</option>').trigger('change');$('#bom_no').val(h.bom_no);$('#routing_id').html('<option value="'+esc(h.routing_id)+'" selected>'+esc(h.routing_no)+'</option>').trigger('change');$('#routing_no').val(h.routing_no);$('#valid_from').val(h.valid_from);$('#valid_to').val(h.valid_to);$('#lot_size_from').val(h.lot_size_from);$('#lot_size_to').val(h.lot_size_to);$('#production_line').val(h.production_line);$('#procurement_type').val(h.procurement_type||'IN_HOUSE').trigger('change');$('#issue_storage_location').val(h.issue_storage_location).trigger('change');$('#receipt_storage_location').val(h.receipt_storage_location).trigger('change');$('#is_default').val(h.is_default||'N').trigger('change');$('#locked').val(h.locked||'N').trigger('change');$('#remarks').val(h.remarks);},'json');});
function statusAction(act,id,no,title,input){var cfg={title:title,text:no,icon:'question',showCancelButton:true,confirmButtonText:title};if(input){cfg.input='text';cfg.inputLabel='Reason '+no;cfg.inputValidator=function(v){return !v?<?=prod_js('production_reason_required', 'Reason is required');?>:undefined;};}Swal.fire(cfg).then(function(x){if(!x.isConfirmed)return;var data={id:id};if(input)data.reason=x.value;$.post('<?=base_admin();?>modul/production_version/production_version_action.php?act='+act,data,function(r){if(r.status==='good')reloadTable(false);else pvError(r.error_message);},'json').fail(function(xhr){pvError(xhr.responseText);});});}
$(document).on('click','.btn-pv-release',function(){statusAction('release',$(this).data('id'),$(this).data('no'),'Release Production Version');});$(document).on('click','.btn-pv-inactive',function(){statusAction('inactive',$(this).data('id'),$(this).data('no'),'Set Inactive',true);});$(document).on('click','.btn-pv-delete',function(){statusAction('delete',$(this).data('id'),$(this).data('no'),'Delete Draft');});
});
</script>
