<?php
if (!function_exists('prod_t')) {
  function prod_t($key, $fallback = '') { return lang_text($key, $fallback); }
}
if (!function_exists('prod_h')) {
  function prod_h($key, $fallback = '') { return htmlspecialchars((string) prod_t($key, $fallback), ENT_QUOTES, 'UTF-8'); }
}
if (!function_exists('prod_js')) {
  function prod_js($key, $fallback = '') { return json_encode(prod_t($key, $fallback), JSON_HEX_TAG | JSON_HEX_APOS | JSON_HEX_AMP | JSON_HEX_QUOT); }
}
if(session_status()===PHP_SESSION_NONE)session_start();
include "../../inc/config.php";
session_check_json();
function pvj($s,$m='',$x=array()){header('Content-Type: application/json');$p=array('status'=>$s);if($m!=='')$p['error_message']=$m;foreach($x as $k=>$v)$p[$k]=$v;echo json_encode($p);exit;}
function pvh($v){return htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');}
function pvq($v){return (float)str_replace(',','.',trim((string)$v));}
function pv_next_no(){global $db;$prefix='PV'.date('Ym');$r=$db->fetch("SELECT production_version_no FROM erp_production_version WHERE production_version_no LIKE ? ORDER BY production_version_no DESC LIMIT 1",array($prefix.'%'));$n=1;if($r&&preg_match('/(\d{5})$/',$r->production_version_no,$m))$n=(int)$m[1]+1;return $prefix.sprintf('%05d',$n);}
function pv_get($key,$default=''){return isset($_POST[$key])?$_POST[$key]:$default;}
function pv_empty_null($v){$v=trim((string)$v);return $v===''?null:$v;}
function pv_filters_get(){return array('from'=>isset($_GET['tgl_awal'])&&$_GET['tgl_awal']!==''?$_GET['tgl_awal']:date('Y-m-01'),'to'=>isset($_GET['tgl_akhir'])&&$_GET['tgl_akhir']!==''?$_GET['tgl_akhir']:date('Y-m-t'),'status'=>isset($_GET['status'])?trim($_GET['status']):'','plant'=>isset($_GET['plant'])?trim($_GET['plant']):'','keyword'=>isset($_GET['keyword'])?trim($_GET['keyword']):'');}
function pv_where($f,&$p){$w=" WHERE pv.valid_from BETWEEN ? AND ? ";$p[]=$f['from'];$p[]=$f['to'];if($f['status']!==''){$w.=" AND pv.version_status=? ";$p[]=$f['status'];}if($f['plant']!==''){$w.=" AND pv.plant_code=? ";$p[]=$f['plant'];}if($f['keyword']!==''){$kw='%'.$f['keyword'].'%';$w.=" AND (pv.production_version_no LIKE ? OR pv.material_code LIKE ? OR pv.material_name LIKE ? OR pv.bom_no LIKE ? OR pv.routing_no LIKE ? OR pv.version_description LIKE ?) ";for($i=0;$i<6;$i++)$p[]=$kw;}return $w;}
$act=isset($_GET['act'])?$_GET['act']:'';$username=isset($_SESSION['username'])?$_SESSION['username']:'system';
switch($act){
  case 'next_no':pvj('good','',array('production_version_no'=>pv_next_no()));break;
  case 'material_search':
    $term=isset($_POST['term'])?trim($_POST['term']):'';$kw='%'.$term.'%';$rows=$db->query("SELECT kd_barang,nm_barang,satuan,type FROM barang WHERE COALESCE(status,1)=1 AND (?='' OR kd_barang LIKE ? OR nm_barang LIKE ?) ORDER BY kd_barang LIMIT 30",array($term,$kw,$kw));$res=array();foreach($rows as $r)$res[]=array('id'=>$r->kd_barang,'text'=>$r->kd_barang.' - '.$r->nm_barang,'material_name'=>$r->nm_barang,'uom'=>$r->satuan,'material_type'=>$r->type);echo json_encode(array('results'=>$res));break;
  case 'bom_search':
    $term=isset($_POST['term'])?trim($_POST['term']):'';$mat=trim(pv_get('material_code'));$plant=trim(pv_get('plant_code'));$kw='%'.$term.'%';$p=array();$sql="SELECT id,bom_no,kodebj,nm_barang,plant_code,alternative_bom,valid_from,valid_to,base_qty,base_uom FROM bom WHERE COALESCE(bom_status,'DRAFT')='RELEASED' ";if($mat!==''){$sql.=" AND kodebj=? ";$p[]=$mat;}if($plant!==''){$sql.=" AND (plant_code=? OR plant_code IS NULL OR plant_code='') ";$p[]=$plant;}if($term!==''){$sql.=" AND (bom_no LIKE ? OR alternative_bom LIKE ? OR revision LIKE ? OR nm_barang LIKE ?) ";array_push($p,$kw,$kw,$kw,$kw);}$sql.=" ORDER BY CASE WHEN plant_code=? THEN 0 ELSE 1 END, valid_from DESC,id DESC LIMIT 30";$p[]=$plant;$rows=$db->query($sql,$p);$res=array();foreach($rows as $r){$plantLabel=trim((string)$r->plant_code)!==''?$r->plant_code:'All Plant';$res[]=array('id'=>$r->id,'text'=>($r->bom_no?:'BOM'.$r->id).' | '.$plantLabel.' | Alt '.$r->alternative_bom.' | '.$r->valid_from.' - '.($r->valid_to?:'Open'),'bom_no'=>$r->bom_no,'material_code'=>$r->kodebj,'material_name'=>$r->nm_barang,'plant_code'=>$r->plant_code,'base_qty'=>$r->base_qty,'base_uom'=>$r->base_uom);}echo json_encode(array('results'=>$res));break;
  case 'routing_search':
    $term=isset($_POST['term'])?trim($_POST['term']):'';$mat=trim(pv_get('material_code'));$plant=trim(pv_get('plant_code'));$kw='%'.$term.'%';$p=array();$sql="SELECT id,routing_no,material_code,material_name,plant_code,alternative_routing,valid_from,valid_to,base_qty,base_uom FROM erp_routing WHERE routing_status='RELEASED' ";if($mat!==''){$sql.=" AND material_code=? ";$p[]=$mat;}if($plant!==''){$sql.=" AND (plant_code=? OR plant_code IS NULL OR plant_code='') ";$p[]=$plant;}if($term!==''){$sql.=" AND (routing_no LIKE ? OR alternative_routing LIKE ? OR revision LIKE ? OR material_name LIKE ?) ";array_push($p,$kw,$kw,$kw,$kw);}$sql.=" ORDER BY CASE WHEN plant_code=? THEN 0 ELSE 1 END, valid_from DESC,id DESC LIMIT 30";$p[]=$plant;$rows=$db->query($sql,$p);$res=array();foreach($rows as $r){$plantLabel=trim((string)$r->plant_code)!==''?$r->plant_code:'All Plant';$res[]=array('id'=>$r->id,'text'=>$r->routing_no.' | '.$plantLabel.' | Alt '.$r->alternative_routing.' | '.$r->valid_from.' - '.($r->valid_to?:'Open'),'routing_no'=>$r->routing_no,'material_code'=>$r->material_code,'material_name'=>$r->material_name,'plant_code'=>$r->plant_code,'base_qty'=>$r->base_qty,'base_uom'=>$r->base_uom);}echo json_encode(array('results'=>$res));break;
  case 'get':
    $id=(int)pv_get('id');$h=$db->fetch("SELECT * FROM erp_production_version WHERE id=? LIMIT 1",array($id));if(!$h)pvj('error','Production Version tidak ditemukan.');pvj('good','',array('header'=>(array)$h));break;
  case 'save':
    $id=(int)pv_get('id');$mat=trim(pv_get('material_code'));$plantId=pv_get('plant_id')!==''?(int)pv_get('plant_id'):null;$plant=trim(pv_get('plant_code'));$bomId=(int)pv_get('bom_id');$routingId=(int)pv_get('routing_id');$validFrom=trim(pv_get('valid_from'));$versionCode=trim(pv_get('version_code','01'))?:'01';
    if($mat==='')pvj('error','Material wajib diisi.');if($plant==='')pvj('error','Plant wajib dipilih.');if($bomId<=0)pvj('error','BOM RELEASED wajib dipilih.');if($routingId<=0)pvj('error','Routing RELEASED wajib dipilih.');if($validFrom==='')pvj('error','Valid From wajib diisi.');
    $item=$db->fetch("SELECT kd_barang,nm_barang FROM barang WHERE kd_barang=? LIMIT 1",array($mat));if(!$item)pvj('error','Material tidak ditemukan.');
    $bom=$db->fetch("SELECT id,bom_no,kodebj,nm_barang,plant_code,bom_status,valid_from,valid_to FROM bom WHERE id=? LIMIT 1",array($bomId));$bomPlant=$bom?trim((string)$bom->plant_code):'';if(!$bom||$bom->kodebj!==$mat||($bomPlant!==''&&$bomPlant!==$plant)||$bom->bom_status!=='RELEASED')pvj('error','BOM tidak sesuai material/plant atau belum RELEASED.');
    $rt=$db->fetch("SELECT id,routing_no,material_code,plant_code,routing_status,valid_from,valid_to FROM erp_routing WHERE id=? LIMIT 1",array($routingId));$rtPlant=$rt?trim((string)$rt->plant_code):'';if(!$rt||$rt->material_code!==$mat||($rtPlant!==''&&$rtPlant!==$plant)||$rt->routing_status!=='RELEASED')pvj('error','Routing tidak sesuai material/plant atau belum RELEASED.');
    $dupe=$db->fetch("SELECT id FROM erp_production_version WHERE material_code=? AND plant_code=? AND version_code=? AND id<>? LIMIT 1",array($mat,$plant,$versionCode,$id));if($dupe)pvj('error','Version Code sudah dipakai untuk material dan plant ini.');
    $data=array('material_code'=>$mat,'material_name'=>$item->nm_barang,'plant_id'=>$plantId,'plant_code'=>$plant,'version_code'=>$versionCode,'version_description'=>pv_get('version_description'),'bom_id'=>$bomId,'bom_no'=>$bom->bom_no,'routing_id'=>$routingId,'routing_no'=>$rt->routing_no,'valid_from'=>$validFrom,'valid_to'=>pv_empty_null(pv_get('valid_to')),'lot_size_from'=>pv_get('lot_size_from')!==''?pvq(pv_get('lot_size_from')):null,'lot_size_to'=>pv_get('lot_size_to')!==''?pvq(pv_get('lot_size_to')):null,'production_line'=>pv_get('production_line'),'procurement_type'=>pv_get('procurement_type','IN_HOUSE'),'issue_storage_location'=>pv_get('issue_storage_location'),'receipt_storage_location'=>pv_get('receipt_storage_location'),'is_default'=>pv_get('is_default')==='Y'?'Y':'N','locked'=>pv_get('locked')==='Y'?'Y':'N','remarks'=>pv_get('remarks'),'updated_by'=>$username,'updated_at'=>date('Y-m-d H:i:s'));
    $db->query('START TRANSACTION');
    if($data['is_default']==='Y')$db->query("UPDATE erp_production_version SET is_default='N' WHERE material_code=? AND plant_code=? AND id<>?",array($mat,$plant,$id));
    if($id>0){$old=$db->fetch("SELECT * FROM erp_production_version WHERE id=? LIMIT 1",array($id));if(!$old){$db->query('ROLLBACK');pvj('error','Production Version tidak ditemukan.');}if($old->version_status!=='DRAFT'){$db->query('ROLLBACK');pvj('error','Hanya DRAFT yang bisa diedit.');}$pvNo=$old->production_version_no;$ok=$db->update('erp_production_version',$data,'id',$id);}
    else{$pvNo=pv_next_no();$data['production_version_no']=$pvNo;$data['version_status']='DRAFT';$data['created_by']=$username;$ok=$db->insert('erp_production_version',$data);$id=$db->last_insert_id();}
    if(!$ok){$e=$db->getErrorMessage();$db->query('ROLLBACK');pvj('error',$e?:'Production Version gagal disimpan.');}
    if(function_exists('simpan_log'))simpan_log('User '.$username.' menyimpan Production Version '.$pvNo.' material '.$mat.' plant '.$plant.' pada '.date('Y-m-d H:i:s'),$username);$db->query('COMMIT');pvj('good','',array('id'=>$id,'production_version_no'=>$pvNo));break;
  case 'release':
    $id=(int)pv_get('id');$h=$db->fetch("SELECT * FROM erp_production_version WHERE id=? LIMIT 1",array($id));if(!$h)pvj('error','Production Version tidak ditemukan.');if($h->version_status!=='DRAFT')pvj('error','Hanya DRAFT yang bisa release.');if($h->locked==='Y')pvj('error','Production Version terkunci.');$db->query("UPDATE erp_production_version SET version_status='RELEASED',released_by=?,released_at=NOW(),updated_by=?,updated_at=NOW() WHERE id=?",array($username,$username,$id));if(function_exists('simpan_log'))simpan_log('User '.$username.' release Production Version '.$h->production_version_no,$username);pvj('good');break;
  case 'inactive':
    $id=(int)pv_get('id');$reason=trim(pv_get('reason'));if($reason==='')pvj('error','Reason inactive wajib diisi.');$h=$db->fetch("SELECT * FROM erp_production_version WHERE id=? LIMIT 1",array($id));if(!$h)pvj('error','Production Version tidak ditemukan.');if($h->version_status!=='RELEASED')pvj('error','Hanya RELEASED yang bisa inactive.');$db->query("UPDATE erp_production_version SET version_status='INACTIVE',inactive_reason=?,updated_by=?,updated_at=NOW() WHERE id=?",array($reason,$username,$id));if(function_exists('simpan_log'))simpan_log('User '.$username.' inactive Production Version '.$h->production_version_no.' alasan '.$reason,$username);pvj('good');break;
  case 'delete':
    $id=(int)pv_get('id');$h=$db->fetch("SELECT * FROM erp_production_version WHERE id=? LIMIT 1",array($id));if(!$h)pvj('error','Production Version tidak ditemukan.');if($h->version_status!=='DRAFT')pvj('error','Hanya DRAFT yang bisa delete.');$db->delete('erp_production_version','id',$id);if(function_exists('simpan_log'))simpan_log('User '.$username.' delete draft Production Version '.$h->production_version_no,$username);pvj('good');break;
  case 'detail':
    $id=(int)pv_get('id');$h=$db->fetch("SELECT * FROM erp_production_version WHERE id=? LIMIT 1",array($id));if(!$h){echo '<div class="alert alert-warning">Production Version tidak ditemukan.</div>';break;}$ops=$db->query("SELECT * FROM erp_routing_operation WHERE routing_id=? ORDER BY operation_no,id",array($h->routing_id));$bom=$db->query("SELECT * FROM bom_detail WHERE id_bom=? ORDER BY COALESCE(line_no,id),id",array($h->bom_id));echo '<h3 style="margin-top:0">'.pvh($h->production_version_no).' <small>Version '.pvh($h->version_code).' / '.pvh($h->version_status).'</small></h3><div class="row"><div class="col-sm-3"><strong>Material</strong><br>'.pvh($h->material_code.' - '.$h->material_name).'</div><div class="col-sm-2"><strong>Plant</strong><br>'.pvh($h->plant_code).'</div><div class="col-sm-2"><strong>BOM</strong><br>'.pvh($h->bom_no).'</div><div class="col-sm-2"><strong>Routing</strong><br>'.pvh($h->routing_no).'</div><div class="col-sm-3"><strong>Validity</strong><br>'.pvh($h->valid_from.' s/d '.($h->valid_to?:'Open')).'</div></div><hr><h4>BOM Components</h4><div class="table-responsive"><table class="table table-bordered table-condensed"><thead><tr class="bg-gray"><th>Line</th><th>Component</th><th class="text-right">Qty</th><th>UOM</th><th>Operation</th></tr></thead><tbody>';foreach($bom as $b)echo '<tr><td>'.(int)$b->line_no.'</td><td><strong>'.pvh($b->kodebb).'</strong><br><small>'.pvh($b->nm_barang).'</small></td><td class="text-right">'.number_format((float)($b->component_qty?:$b->jumlah),5,',','.').'</td><td>'.pvh($b->component_uom?:$b->satuan).'</td><td>'.pvh($b->operation_no).'</td></tr>';echo '</tbody></table></div><h4>Routing Operations</h4><div class="table-responsive"><table class="table table-bordered table-condensed"><thead><tr class="bg-gray"><th>Op</th><th>Work Center</th><th>Name</th><th class="text-right">Setup</th><th class="text-right">Machine</th><th class="text-right">Labor</th></tr></thead><tbody>';foreach($ops as $o)echo '<tr><td>'.pvh($o->operation_no).'</td><td>'.pvh($o->work_center_code.' - '.$o->work_center_name).'</td><td>'.pvh($o->operation_name).'</td><td class="text-right">'.number_format((float)$o->setup_time,2,',','.').'</td><td class="text-right">'.number_format((float)$o->machine_time,2,',','.').'</td><td class="text-right">'.number_format((float)$o->labor_time,2,',','.').'</td></tr>';echo '</tbody></table></div>';break;
  case 'excel':
    $initial=ob_get_level();ob_start();error_reporting(E_ALL & ~E_NOTICE & ~E_WARNING & ~E_DEPRECATED & ~E_USER_DEPRECATED);require_once "../../inc/lib/PHPExcel.php";require_once "../../inc/excel_style_helper.php";PHPExcel_Shared_File::setUseUploadTempDirectory(true);$f=pv_filters_get();$p=array();$w=pv_where($f,$p);$rows=$db->query("SELECT * FROM erp_production_version pv $w ORDER BY material_code,plant_code,version_code",$p);$excel=new PHPExcel();$sheet=$excel->setActiveSheetIndex(0);$sheet->setTitle(erp_export_sheet_title('Prod Version'));$heads=array(erp_export_label("No"),erp_export_label("PV No"),erp_export_label("Material"),erp_export_label("Material Name"),erp_export_label("Plant"),erp_export_label("Version"),erp_export_label("Description"),erp_export_label("BOM"),erp_export_label("Routing"),erp_export_label("Valid From"),erp_export_label("Valid To"),erp_export_label("Lot From"),erp_export_label("Lot To"),erp_export_label("Line"),erp_export_label("Proc Type"),erp_export_label("Issue SLoc"),erp_export_label("Receipt SLoc"),erp_export_label("Default"),erp_export_label("Locked"),erp_export_label("Status"),erp_export_label("Remarks"));foreach($heads as $i=>$v)$sheet->setCellValue(PHPExcel_Cell::stringFromColumnIndex($i).'4',$v);$r=5;$n=1;foreach($rows as $row){$vals=array($n++,$row->production_version_no,$row->material_code,$row->material_name,$row->plant_code,$row->version_code,$row->version_description,$row->bom_no,$row->routing_no,$row->valid_from,$row->valid_to,(float)$row->lot_size_from,(float)$row->lot_size_to,$row->production_line,$row->procurement_type,$row->issue_storage_location,$row->receipt_storage_location,$row->is_default,$row->locked,$row->version_status,$row->remarks);foreach($vals as $i=>$v)$sheet->setCellValue(PHPExcel_Cell::stringFromColumnIndex($i).$r,$v);$r++;}erpkb_excel_apply_standard_style($excel,array('sheet'=>$sheet,'title'=>erp_export_title('PRODUCTION VERSION REPORT - SAP PP'),'header_row'=>4,'first_data_row'=>5,'last_data_row'=>max(5,$r-1),'column_count'=>21,'numeric_columns'=>array('L','M'),'filters'=>array('Valid From'=>$f['from'].' s/d '.$f['to'],'Status'=>$f['status'],'Plant'=>$f['plant'],'Keyword'=>$f['keyword'])));$tmp=erpkb_excel_temp_file('production_version_');PHPExcel_IOFactory::createWriter($excel,'Excel2007')->save($tmp);$size=@filesize($tmp);$sig=@file_get_contents($tmp,false,null,0,2);if(!$size||$sig!=='PK'){@unlink($tmp);while(ob_get_level()>$initial)ob_end_clean();header('Content-Type:text/plain; charset=utf-8');echo erp_t('export_excel_invalid_file','File Excel gagal dibuat dengan benar.');exit;}while(ob_get_level()>$initial)ob_end_clean();header('Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');header('Content-Disposition: attachment; filename="production_version_'.date('Ymd_His').'.xlsx"');header('Content-Length: '.$size);header('Cache-Control: max-age=0');header('Pragma: public');readfile($tmp);@unlink($tmp);exit;
  default:pvj('error','Action tidak dikenal.');
}
?>
