<?php
if (!function_exists('hr_t')) {
  function hr_t($key, $fallback = '') { return lang_text($key, $fallback); }
}
if (!function_exists('hr_h')) {
  function hr_h($key, $fallback = '') { return htmlspecialchars((string) hr_t($key, $fallback), ENT_QUOTES, 'UTF-8'); }
}
if (!function_exists('hr_js')) {
  function hr_js($key, $fallback = '') { return json_encode(hr_t($key, $fallback), JSON_HEX_TAG | JSON_HEX_APOS | JSON_HEX_AMP | JSON_HEX_QUOT); }
}
if (session_status() === PHP_SESSION_NONE) session_start();
include "../../inc/config.php";
session_check_json();

function jv_json($s,$m='',$x=array()){header('Content-Type: application/json; charset=utf-8');$p=array('status'=>$s);if($m!=='')$p[$s==='good'?'message':'error_message']=$m;foreach($x as $k=>$v)$p[$k]=$v;echo json_encode($p);exit;}
function jv_h($v){return htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');}
function jv_p($k,$d=''){return isset($_POST[$k])?$_POST[$k]:$d;}
function jv_g($k,$d=''){return isset($_GET[$k])?$_GET[$k]:$d;}
function jv_c($v){return strtoupper(trim((string)$v));}
function jv_user(){return isset($_SESSION['username'])&&$_SESSION['username']!==''?$_SESSION['username']:'system';}
function jv_select2($rows,$id,$cb){$out=array();foreach($rows as $r)$out[]=array('id'=>$r->$id,'text'=>$cb($r));header('Content-Type: application/json; charset=utf-8');echo json_encode(array('results'=>$out));exit;}
function jv_next_no($year){global $db;$year=(int)$year>0?(int)$year:(int)date('Y');$r=$db->fetch("SELECT vacancy_no FROM erp_job_vacancy WHERE vacancy_no LIKE ? ORDER BY vacancy_no DESC LIMIT 1",array('JV-'.$year.'-%'));$n=1;if($r&&preg_match('/-(\d+)$/',$r->vacancy_no,$m))$n=(int)$m[1]+1;return 'JV-'.$year.'-'.str_pad($n,3,'0',STR_PAD_LEFT);}
function jv_row($id){
  global $db;
  return $db->fetch("SELECT v.*,mp.plan_no,mp.plan_name,p.position_code,p.position_name,jt.job_title_code,jt.job_title_name,d.nm_dept,cs.structure_code,cs.structure_name,cc.cost_center_name,pc.profit_center_name,wl.location_code,wl.location_name,rec.employee_no recruiter_no,rec.full_name recruiter_name,hm.employee_no manager_no,hm.full_name manager_name
    FROM erp_job_vacancy v
    LEFT JOIN erp_manpower_plan mp ON mp.id=v.manpower_plan_id
    LEFT JOIN erp_position p ON p.id=v.position_id
    LEFT JOIN erp_job_title jt ON jt.id=v.job_title_id
    LEFT JOIN dept d ON d.kd_dept=v.department_code
    LEFT JOIN erp_company_structure cs ON cs.id=v.company_structure_id
    LEFT JOIN erp_cost_center cc ON cc.cost_center_code=v.cost_center_code
    LEFT JOIN erp_profit_center pc ON pc.profit_center_code=v.profit_center_code
    LEFT JOIN erp_work_location wl ON wl.id=v.work_location_id
    LEFT JOIN erp_employee_master rec ON rec.id=v.recruiter_employee_id
    LEFT JOIN erp_employee_master hm ON hm.id=v.hiring_manager_employee_id
    WHERE v.id=? LIMIT 1",array((int)$id));
}
function jv_payload($r){
  $d=(array)$r;
  $d['manpower_plan_text']=$r->manpower_plan_id?($r->plan_no.' - '.$r->plan_name):'';
  $d['position_text']=$r->position_id?($r->position_code.' - '.$r->position_name):'';
  $d['job_title_text']=$r->job_title_id?($r->job_title_code.' - '.$r->job_title_name):'';
  $d['department_text']=$r->department_code?($r->department_code.' - '.$r->nm_dept):'';
  $d['company_structure_text']=$r->company_structure_id?($r->structure_code.' - '.$r->structure_name):'';
  $d['cost_center_text']=$r->cost_center_code?($r->cost_center_code.' - '.$r->cost_center_name):'';
  $d['profit_center_text']=$r->profit_center_code?($r->profit_center_code.' - '.$r->profit_center_name):'';
  $d['work_location_text']=$r->work_location_id?($r->location_code.' - '.$r->location_name):'';
  $d['recruiter_text']=$r->recruiter_employee_id?($r->recruiter_no.' - '.$r->recruiter_name):'';
  $d['hiring_manager_text']=$r->hiring_manager_employee_id?($r->manager_no.' - '.$r->manager_name):'';
  return $d;
}
function jv_export_rows($from,$to,$status,$type,$dept,$kw){
  global $db;$p=array($to,$from);$w=" WHERE COALESCE(v.posting_date,v.created_at)<=? AND COALESCE(v.closing_date,'9999-12-31')>=? ";
  if($status!==''){$w.=" AND v.vacancy_status=? ";$p[]=$status;}if($type!==''){$w.=" AND v.vacancy_type=? ";$p[]=$type;}if($dept!==''){$w.=" AND v.department_code=? ";$p[]=$dept;}if($kw!==''){$like='%'.$kw.'%';$w.=" AND (v.vacancy_no LIKE ? OR v.vacancy_title LIKE ? OR p.position_code LIKE ? OR jt.job_title_name LIKE ? OR v.sap_reference LIKE ?) ";array_push($p,$like,$like,$like,$like,$like);}
  return $db->query("SELECT v.*,mp.plan_no,p.position_code,p.position_name,jt.job_title_code,jt.job_title_name,d.nm_dept,cs.structure_code,cs.structure_name,rec.employee_no recruiter_no,rec.full_name recruiter_name,hm.employee_no manager_no,hm.full_name manager_name
    FROM erp_job_vacancy v
    LEFT JOIN erp_manpower_plan mp ON mp.id=v.manpower_plan_id
    LEFT JOIN erp_position p ON p.id=v.position_id
    LEFT JOIN erp_job_title jt ON jt.id=v.job_title_id
    LEFT JOIN dept d ON d.kd_dept=v.department_code
    LEFT JOIN erp_company_structure cs ON cs.id=v.company_structure_id
    LEFT JOIN erp_employee_master rec ON rec.id=v.recruiter_employee_id
    LEFT JOIN erp_employee_master hm ON hm.id=v.hiring_manager_employee_id
    $w ORDER BY v.created_at DESC,v.vacancy_no DESC",$p);
}

$act=isset($_GET['act'])?$_GET['act']:'';
$username=jv_user();
$types=array('NEW_POSITION','REPLACEMENT','INTERNAL_TRANSFER','TEMPORARY','PROJECT');
$employment=array('PERMANENT','CONTRACT','DAILY_WORKER','INTERNSHIP','OUTSOURCE');
$groups=array('DIRECTOR','MANAGER','STAFF','NON_STAFF','OPERATOR','CONTRACT','DAILY_WORKER','TRAINEE');
$priorities=array('LOW','MEDIUM','HIGH','CRITICAL');
$statuses=array('DRAFT','OPEN','SCREENING','INTERVIEW','OFFER','HIRED','CANCELLED','CLOSED');

switch($act){
case 'next_no':jv_json('good','',array('vacancy_no'=>jv_next_no((int)jv_p('year',date('Y')))));
case 'department_search':$t=trim(jv_p('term'));$like='%'.$t.'%';$rows=$db->query("SELECT kd_dept,nm_dept,dept_type FROM dept WHERE status='ACTIVE' AND (?='' OR kd_dept LIKE ? OR nm_dept LIKE ?) ORDER BY kd_dept LIMIT 40",array($t,$like,$like));jv_select2($rows,'kd_dept',function($r){return $r->kd_dept.' - '.$r->nm_dept.' ['.$r->dept_type.']';});
case 'company_structure_search':$t=trim(jv_p('term'));$like='%'.$t.'%';$rows=$db->query("SELECT id,structure_code,structure_name,structure_type FROM erp_company_structure WHERE status='ACTIVE' AND (?='' OR structure_code LIKE ? OR structure_name LIKE ? OR structure_type LIKE ?) ORDER BY structure_code LIMIT 40",array($t,$like,$like,$like));jv_select2($rows,'id',function($r){return $r->structure_code.' - '.$r->structure_name.' ['.$r->structure_type.']';});
case 'cost_center_search':$t=trim(jv_p('term'));$like='%'.$t.'%';$rows=$db->query("SELECT cost_center_code,cost_center_name FROM erp_cost_center WHERE status='Aktif' AND (?='' OR cost_center_code LIKE ? OR cost_center_name LIKE ?) ORDER BY cost_center_code LIMIT 40",array($t,$like,$like));jv_select2($rows,'cost_center_code',function($r){return $r->cost_center_code.' - '.$r->cost_center_name;});
case 'profit_center_search':$t=trim(jv_p('term'));$like='%'.$t.'%';$rows=$db->query("SELECT profit_center_code,profit_center_name FROM erp_profit_center WHERE status='Aktif' AND (?='' OR profit_center_code LIKE ? OR profit_center_name LIKE ?) ORDER BY profit_center_code LIMIT 40",array($t,$like,$like));jv_select2($rows,'profit_center_code',function($r){return $r->profit_center_code.' - '.$r->profit_center_name;});
case 'employee_search':$t=trim(jv_p('term'));$like='%'.$t.'%';$rows=$db->query("SELECT id,employee_no,full_name,employment_status FROM erp_employee_master WHERE employment_status IN ('ACTIVE','PROBATION','CONTRACT') AND (?='' OR employee_no LIKE ? OR full_name LIKE ?) ORDER BY employee_no LIMIT 40",array($t,$like,$like));jv_select2($rows,'id',function($r){return $r->employee_no.' - '.$r->full_name.' ['.$r->employment_status.']';});
case 'job_title_search':$t=trim(jv_p('term'));$like='%'.$t.'%';$rows=$db->query("SELECT id,job_title_code,job_title_name,job_level FROM erp_job_title WHERE status='ACTIVE' AND (?='' OR job_title_code LIKE ? OR job_title_name LIKE ?) ORDER BY job_title_code LIMIT 40",array($t,$like,$like));jv_select2($rows,'id',function($r){return $r->job_title_code.' - '.$r->job_title_name.' ['.$r->job_level.']';});
case 'position_search':$t=trim(jv_p('term'));$like='%'.$t.'%';$rows=$db->query("SELECT id,position_code,position_name,vacancy_status FROM erp_position WHERE position_status IN ('APPROVED','ACTIVE','PLANNED') AND (?='' OR position_code LIKE ? OR position_name LIKE ?) ORDER BY position_code LIMIT 40",array($t,$like,$like));jv_select2($rows,'id',function($r){return $r->position_code.' - '.$r->position_name.' ['.$r->vacancy_status.']';});
case 'work_location_search':$t=trim(jv_p('term'));$like='%'.$t.'%';$rows=$db->query("SELECT id,location_code,location_name,location_type FROM erp_work_location WHERE status='ACTIVE' AND (?='' OR location_code LIKE ? OR location_name LIKE ?) ORDER BY location_code LIMIT 40",array($t,$like,$like));jv_select2($rows,'id',function($r){return $r->location_code.' - '.$r->location_name.' ['.$r->location_type.']';});
case 'manpower_plan_search':$t=trim(jv_p('term'));$like='%'.$t.'%';$rows=$db->query("SELECT id,plan_no,plan_name,planning_status,total_requested_headcount FROM erp_manpower_plan WHERE planning_status IN ('SUBMITTED','APPROVED') AND (?='' OR plan_no LIKE ? OR plan_name LIKE ?) ORDER BY period_from DESC,plan_no DESC LIMIT 40",array($t,$like,$like));jv_select2($rows,'id',function($r){return $r->plan_no.' - '.$r->plan_name.' ['.$r->planning_status.' / HC '.$r->total_requested_headcount.']';});
case 'position_info':
  $r=$db->fetch("SELECT p.*,d.nm_dept,cs.structure_code,cs.structure_name,jt.job_title_code,jt.job_title_name,cc.cost_center_name,pc.profit_center_name,wl.location_code,wl.location_name FROM erp_position p LEFT JOIN dept d ON d.kd_dept=p.department_code LEFT JOIN erp_company_structure cs ON cs.id=p.company_structure_id LEFT JOIN erp_job_title jt ON jt.id=p.job_title_id LEFT JOIN erp_cost_center cc ON cc.cost_center_code=p.cost_center_code LEFT JOIN erp_profit_center pc ON pc.profit_center_code=p.profit_center_code LEFT JOIN erp_work_location wl ON wl.id=p.work_location_id WHERE p.id=? LIMIT 1",array((int)jv_p('id')));
  if(!$r)jv_json('error','Position tidak ditemukan.');
  jv_json('good','',array('data'=>array('job_title_id'=>$r->job_title_id,'job_title_text'=>$r->job_title_id?($r->job_title_code.' - '.$r->job_title_name):'','department_code'=>$r->department_code,'department_text'=>$r->department_code?($r->department_code.' - '.$r->nm_dept):'','company_structure_id'=>$r->company_structure_id,'company_structure_text'=>$r->company_structure_id?($r->structure_code.' - '.$r->structure_name):'','cost_center_code'=>$r->cost_center_code,'cost_center_text'=>$r->cost_center_code?($r->cost_center_code.' - '.$r->cost_center_name):'','profit_center_code'=>$r->profit_center_code,'profit_center_text'=>$r->profit_center_code?($r->profit_center_code.' - '.$r->profit_center_name):'','work_location_id'=>$r->work_location_id,'work_location_text'=>$r->work_location_id?($r->location_code.' - '.$r->location_name):'','employee_group'=>$r->employee_group,'pay_grade'=>$r->pay_grade,'vacancy_title'=>$r->job_title_name?:$r->position_name,'headcount_requested'=>max(1,(float)$r->headcount_plan-(float)$r->occupied_fte))));
case 'get':$r=jv_row((int)jv_p('id'));if(!$r)jv_json('error','Job Vacancy tidak ditemukan.');jv_json('good','',array('data'=>jv_payload($r)));
case 'save':
  $id=(int)jv_p('id');$no=jv_c(jv_p('vacancy_no'));$title=trim(jv_p('vacancy_title'));$year=(int)date('Y');if(jv_p('posting_date')!=='')$year=(int)substr(jv_p('posting_date'),0,4);if($no===''||$no==='AUTO')$no=jv_next_no($year);
  $type=jv_c(jv_p('vacancy_type','NEW_POSITION'));$emp=jv_c(jv_p('employment_type','PERMANENT'));$grp=jv_c(jv_p('employee_group','STAFF'));$pri=jv_c(jv_p('priority','MEDIUM'));$status=jv_c(jv_p('vacancy_status','DRAFT'));
  if($title==='')jv_json('error','Vacancy Title wajib diisi.');if(!in_array($type,$types,true))jv_json('error','Vacancy Type tidak valid.');if(!in_array($emp,$employment,true))jv_json('error','Employment Type tidak valid.');if(!in_array($grp,$groups,true))jv_json('error','Employee Group tidak valid.');if(!in_array($pri,$priorities,true))jv_json('error','Priority tidak valid.');if(!in_array($status,$statuses,true))jv_json('error','Vacancy Status tidak valid.');if($db->fetch("SELECT id FROM erp_job_vacancy WHERE vacancy_no=? AND id<>? LIMIT 1",array($no,$id)))jv_json('error','Vacancy No sudah digunakan.');
  $posting=trim(jv_p('posting_date'));$closing=trim(jv_p('closing_date'));if($posting!==''&&$closing!==''&&strtotime($closing)<strtotime($posting))jv_json('error','Closing Date tidak boleh sebelum Posting Date.');
  $req=max(0,(float)jv_p('headcount_requested',1));$appr=max(0,(float)jv_p('headcount_approved',0));$filled=max(0,(float)jv_p('headcount_filled',0));if($req<=0)jv_json('error','Headcount Requested wajib lebih dari 0.');if($filled>$req)jv_json('error','Headcount Filled tidak boleh melebihi Requested.');
  $data=array('vacancy_no'=>$no,'vacancy_title'=>$title,'manpower_plan_id'=>jv_p('manpower_plan_id')!==''?(int)jv_p('manpower_plan_id'):null,'manpower_plan_detail_id'=>null,'position_id'=>jv_p('position_id')!==''?(int)jv_p('position_id'):null,'job_title_id'=>jv_p('job_title_id')!==''?(int)jv_p('job_title_id'):null,'company_structure_id'=>jv_p('company_structure_id')!==''?(int)jv_p('company_structure_id'):null,'department_code'=>jv_c(jv_p('department_code'))?:null,'cost_center_code'=>trim(jv_p('cost_center_code')),'profit_center_code'=>trim(jv_p('profit_center_code')),'work_location_id'=>jv_p('work_location_id')!==''?(int)jv_p('work_location_id'):null,'vacancy_type'=>$type,'employment_type'=>$emp,'employee_group'=>$grp,'pay_grade'=>trim(jv_p('pay_grade')),'priority'=>$pri,'vacancy_status'=>$status,'headcount_requested'=>$req,'headcount_approved'=>$appr,'headcount_filled'=>$filled,'salary_min'=>(float)jv_p('salary_min',0),'salary_max'=>(float)jv_p('salary_max',0),'currency'=>jv_c(jv_p('currency','IDR'))?:'IDR','posting_date'=>$posting?:null,'closing_date'=>$closing?:null,'target_join_date'=>trim(jv_p('target_join_date'))?:null,'recruiter_employee_id'=>jv_p('recruiter_employee_id')!==''?(int)jv_p('recruiter_employee_id'):null,'hiring_manager_employee_id'=>jv_p('hiring_manager_employee_id')!==''?(int)jv_p('hiring_manager_employee_id'):null,'publish_internal'=>jv_c(jv_p('publish_internal','Y'))==='N'?'N':'Y','publish_external'=>jv_c(jv_p('publish_external','N'))==='Y'?'Y':'N','source_channel'=>trim(jv_p('source_channel')),'applicant_count'=>max(0,(int)jv_p('applicant_count',0)),'shortlisted_count'=>max(0,(int)jv_p('shortlisted_count',0)),'interview_count'=>max(0,(int)jv_p('interview_count',0)),'offer_count'=>max(0,(int)jv_p('offer_count',0)),'hired_count'=>max(0,(int)jv_p('hired_count',0)),'job_description'=>trim(jv_p('job_description')),'qualification_requirement'=>trim(jv_p('qualification_requirement')),'responsibilities'=>trim(jv_p('responsibilities')),'benefits'=>trim(jv_p('benefits')),'cancellation_reason'=>trim(jv_p('cancellation_reason')),'sap_reference'=>trim(jv_p('sap_reference')),'remarks'=>trim(jv_p('remarks')),'updated_by'=>$username,'updated_at'=>date('Y-m-d H:i:s'));
  if($id>0){if(!jv_row($id))jv_json('error','Job Vacancy tidak ditemukan.');$ok=$db->update('erp_job_vacancy',$data,'id',$id);}else{$data['created_by']=$username;$ok=$db->insert('erp_job_vacancy',$data);$id=(int)$db->last_insert_id();}
  if(!$ok)jv_json('error',$db->getErrorMessage()?:'Job Vacancy gagal disimpan.');if(function_exists('simpan_log'))simpan_log('User '.$username.' menyimpan Job Vacancy '.$no.' - '.$title.' pada '.date('Y-m-d H:i:s'),$username);jv_json('good','Job Vacancy berhasil disimpan.',array('id'=>$id,'vacancy_no'=>$no));
case 'status':$id=(int)jv_p('id');$status=jv_c(jv_p('status'));if(!in_array($status,$statuses,true))jv_json('error','Status tidak valid.');$r=jv_row($id);if(!$r)jv_json('error','Job Vacancy tidak ditemukan.');$ok=$db->update('erp_job_vacancy',array('vacancy_status'=>$status,'updated_by'=>$username,'updated_at'=>date('Y-m-d H:i:s')),'id',$id);if(!$ok)jv_json('error',$db->getErrorMessage()?:'Status gagal diubah.');if(function_exists('simpan_log'))simpan_log('User '.$username.' mengubah status Job Vacancy '.$r->vacancy_no.' menjadi '.$status,$username);jv_json('good','Status berhasil diubah.');
case 'delete':$id=(int)jv_p('id');$r=jv_row($id);if(!$r)jv_json('error','Job Vacancy tidak ditemukan.');if(!in_array($r->vacancy_status,array('DRAFT','CANCELLED'),true))jv_json('error','Hanya DRAFT/CANCELLED yang boleh dihapus.');$db->delete('erp_job_vacancy','id',$id);if($db->getErrorMessage())jv_json('error',$db->getErrorMessage());if(function_exists('simpan_log'))simpan_log('User '.$username.' menghapus Job Vacancy '.$r->vacancy_no,$username);jv_json('good','Job Vacancy berhasil dihapus.');
case 'detail':
  $r=jv_row((int)jv_p('id'));if(!$r){echo '<div class="alert alert-warning">Job Vacancy tidak ditemukan.</div>';break;}
  echo '<div class="jv-detail"><h3 style="margin-top:0">'.jv_h($r->vacancy_no).' <small>'.jv_h($r->vacancy_title).'</small></h3><span class="label label-success">'.jv_h($r->vacancy_status).'</span> <span class="label label-info">'.jv_h($r->vacancy_type).'</span> <span class="label label-default">'.jv_h($r->priority).'</span><hr><div class="row"><div class="col-sm-3"><b>'.hr_h('hr_position', 'Position').'</b><br>'.jv_h($r->position_code?($r->position_code.' - '.$r->position_name):'-').'</div><div class="col-sm-3"><b>'.hr_h('hr_job_title', 'Job Title').'</b><br>'.jv_h($r->job_title_code?($r->job_title_code.' - '.$r->job_title_name):'-').'</div><div class="col-sm-3"><b>'.hr_h('hr_department', 'Department').'</b><br>'.jv_h($r->department_code?($r->department_code.' - '.$r->nm_dept):'-').'</div><div class="col-sm-3"><b>Manpower Plan</b><br>'.jv_h($r->plan_no?($r->plan_no.' - '.$r->plan_name):'-').'</div></div><hr><div class="row"><div class="col-sm-3"><b>Headcount</b><br>'.number_format((float)$r->headcount_filled,2).' filled / '.number_format((float)$r->headcount_requested,2).' requested</div><div class="col-sm-3"><b>Posting</b><br>'.jv_h(($r->posting_date?:'-').' s/d '.($r->closing_date?:'-')).'</div><div class="col-sm-3"><b>Recruiter</b><br>'.jv_h($r->recruiter_no?($r->recruiter_no.' - '.$r->recruiter_name):'-').'</div><div class="col-sm-3"><b>Hiring Manager</b><br>'.jv_h($r->manager_no?($r->manager_no.' - '.$r->manager_name):'-').'</div></div><hr><div class="row"><div class="col-sm-2"><b>Applicants</b><br>'.(int)$r->applicant_count.'</div><div class="col-sm-2"><b>Shortlisted</b><br>'.(int)$r->shortlisted_count.'</div><div class="col-sm-2"><b>'.hr_h('hr_interview', 'Interview').'</b><br>'.(int)$r->interview_count.'</div><div class="col-sm-2"><b>Offer</b><br>'.(int)$r->offer_count.'</div><div class="col-sm-2"><b>Hired</b><br>'.(int)$r->hired_count.'</div><div class="col-sm-2"><b>Publish</b><br>Internal '.jv_h($r->publish_internal).' / External '.jv_h($r->publish_external).'</div></div><hr><div class="row"><div class="col-sm-6"><b>Job Description</b><p>'.nl2br(jv_h($r->job_description?:'-')).'</p><b>Responsibilities</b><p>'.nl2br(jv_h($r->responsibilities?:'-')).'</p></div><div class="col-sm-6"><b>Qualification</b><p>'.nl2br(jv_h($r->qualification_requirement?:'-')).'</p><b>Benefits</b><p>'.nl2br(jv_h($r->benefits?:'-')).'</p></div></div><hr><p><b>SAP Reference:</b> '.jv_h($r->sap_reference?:'-').'<br><b>Remarks:</b> '.nl2br(jv_h($r->remarks?:'-')).'</p></div>';break;
case 'export':
  $initial=ob_get_level();ob_start();error_reporting(E_ALL & ~E_NOTICE & ~E_WARNING & ~E_DEPRECATED & ~E_USER_DEPRECATED);require_once "../../inc/lib/PHPExcel.php";require_once "../../inc/excel_style_helper.php";PHPExcel_Shared_File::setUseUploadTempDirectory(true);
  $from=jv_g('tgl_awal',date('Y-01-01'));$to=jv_g('tgl_akhir',date('Y-12-31'));$status=jv_g('vacancy_status','');$type=jv_g('vacancy_type','');$dept=jv_g('department_code','');$kw=jv_g('keyword','');$rows=jv_export_rows($from,$to,$status,$type,$dept,$kw);
  $excel=new PHPExcel();$sheet=$excel->setActiveSheetIndex(0);$sheet->setTitle(erp_export_sheet_title('Job Vacancy'));$heads=array(erp_export_label("No"),erp_export_label("Vacancy No"),erp_export_label("Title"),erp_export_label("Status"),erp_export_label("Type"),erp_export_label("Employment"),erp_export_label("Priority"),erp_export_label("Position"),erp_export_label("Job Title"),erp_export_label("Department"),erp_export_label("Org Unit"),erp_export_label("Requested HC"),erp_export_label("Approved HC"),erp_export_label("Filled HC"),erp_export_label("Posting"),erp_export_label("Closing"),erp_export_label("Target Join"),erp_export_label("Applicants"),erp_export_label("Shortlisted"),erp_export_label("Interview"),erp_export_label("Offer"),erp_export_label("Hired"),erp_export_label("Recruiter"),erp_export_label("Hiring Manager"),erp_export_label("Salary Min"),erp_export_label("Salary Max"),erp_export_label("Currency"),erp_export_label("Publish Internal"),erp_export_label("Publish External"),erp_export_label("Source"),erp_export_label("SAP Ref"),erp_export_label("Updated By"));
  foreach($heads as $i=>$h)$sheet->setCellValue(PHPExcel_Cell::stringFromColumnIndex($i).'4',$h);$rn=5;$n=1;foreach($rows as $r){$vals=array($n++,$r->vacancy_no,$r->vacancy_title,$r->vacancy_status,$r->vacancy_type,$r->employment_type,$r->priority,$r->position_code.' - '.$r->position_name,$r->job_title_code.' - '.$r->job_title_name,$r->department_code.' - '.$r->nm_dept,$r->structure_code.' - '.$r->structure_name,(float)$r->headcount_requested,(float)$r->headcount_approved,(float)$r->headcount_filled,$r->posting_date,$r->closing_date,$r->target_join_date,(int)$r->applicant_count,(int)$r->shortlisted_count,(int)$r->interview_count,(int)$r->offer_count,(int)$r->hired_count,$r->recruiter_no.' - '.$r->recruiter_name,$r->manager_no.' - '.$r->manager_name,(float)$r->salary_min,(float)$r->salary_max,$r->currency,$r->publish_internal,$r->publish_external,$r->source_channel,$r->sap_reference,$r->updated_by?:$r->created_by);foreach($vals as $i=>$v)$sheet->setCellValue(PHPExcel_Cell::stringFromColumnIndex($i).$rn,$v);$rn++;}
  erpkb_excel_apply_standard_style($excel,array('sheet'=>$sheet,'title'=>erp_export_title('JOB VACANCY REPORT'),'header_row'=>4,'first_data_row'=>5,'last_data_row'=>max(5,$rn-1),'column_count'=>count($heads),'decimal_columns'=>array('L','M','N','Y','Z'),'numeric_columns'=>array('R','S','T','U','V'),'filters'=>array('Period'=>$from.' s/d '.$to,'Status'=>$status?:erp_export_all_text(),'Type'=>$type?:erp_export_all_text(),'Department'=>$dept?:erp_export_all_text()),'widths'=>array('B'=>18,'C'=>34,'H'=>28,'I'=>25,'J'=>24,'K'=>28,'O'=>14,'P'=>14,'Q'=>14,'W'=>28,'X'=>28,'AD'=>22,'AE'=>20)));
  $tmp=erpkb_excel_temp_file('job_vacancy_');PHPExcel_IOFactory::createWriter($excel,'Excel2007')->save($tmp);$size=@filesize($tmp);$sig=@file_get_contents($tmp,false,null,0,2);if(!$size||$sig!=='PK'){@unlink($tmp);while(ob_get_level()>$initial)ob_end_clean();echo erp_t('export_excel_invalid_file','File Excel gagal dibuat dengan benar.');exit;}while(ob_get_level()>$initial)ob_end_clean();header('Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');header('Content-Disposition: attachment; filename="job_vacancy_'.date('Ymd_His').'.xlsx"');header('Content-Length: '.$size);header('Cache-Control: max-age=0');header('Pragma: public');readfile($tmp);@unlink($tmp);exit;
default:jv_json('error','Action tidak dikenal.');
}
?>
