<?php
if (!function_exists('hr_t')) {
  function hr_t($key, $fallback = '') { return lang_text($key, $fallback); }
}
if (!function_exists('hr_h')) {
  function hr_h($key, $fallback = '') { return htmlspecialchars((string) hr_t($key, $fallback), ENT_QUOTES, 'UTF-8'); }
}
if (!function_exists('hr_js')) {
  function hr_js($key, $fallback = '') { return json_encode(hr_t($key, $fallback), JSON_HEX_TAG | JSON_HEX_APOS | JSON_HEX_AMP | JSON_HEX_QUOT); }
}
$defaultFrom=date('Y-01-01');$defaultTo=date('Y-12-31');$canInsert=isset($insert_act)&&$insert_act==='Y'; ?>
<style>
.jv-hero{background:linear-gradient(135deg,#7c3aed,#0ea5e9);color:#fff;border-radius:14px;padding:22px;margin-bottom:14px;box-shadow:0 8px 24px rgba(124,58,237,.18)}.jv-hero h1{margin:0 0 6px;font-weight:700}.jv-hero p{margin:0;color:#eef2ff}.jv-card{border-radius:12px;border:1px solid #e5edf5;box-shadow:0 4px 14px rgba(15,23,42,.05)}.jv-kpi{background:#fff;border:1px solid #e5edf5;border-radius:12px;padding:13px;margin-bottom:14px}.jv-kpi span{font-size:12px;color:#64748b}.jv-kpi b{display:block;font-size:21px;color:#0f172a}#dtb_job_vacancy th,#dtb_job_vacancy td{font-size:12px;vertical-align:middle}.jv-action{white-space:nowrap}.select2-container{width:100%!important}.required-label:after{content:' *';color:#dd4b39}#modal_jv .modal-body{max-height:calc(100vh - 180px);overflow-y:auto}.jv-section{font-weight:700;color:#334155;border-bottom:1px solid #e5e7eb;padding-bottom:7px;margin:8px 0 12px}
</style>
<section class="content-header"><h1><?=hr_h('hr_job_vacancy', 'Job Vacancy');?> <small>SAP HCM Recruitment</small></h1><ol class="breadcrumb"><li><a href="<?=base_index();?>"><i class="fa fa-dashboard"></i> <?=hr_h('common_home', 'Home');?></a></li><li>Human Resource</li><li>Recruitment</li><li class="active"><?=hr_h('hr_job_vacancy', 'Job Vacancy');?></li></ol></section>
<section class="content">
<div class="jv-hero"><div class="row"><div class="col-md-8"><h1>Job Vacancy Cockpit</h1><p>Kelola lowongan dari manpower plan sampai publish, screening, interview, offer, dan hired dengan assignment organisasi ala SAP HCM.</p></div><div class="col-md-4 text-right"><?php if($canInsert){ ?><button id="btn_open_jv" class="btn btn-warning"><i class="fa fa-plus"></i> Create Vacancy</button><?php } ?> <button id="btn_export_jv" class="btn btn-success"><i class="fa fa-file-excel-o"></i> <?=hr_h('common_export_excel', 'Export Excel');?></button></div></div></div>
<div class="row"><div class="col-sm-2"><div class="jv-kpi"><span>Total</span><b id="kpi_total">0</b></div></div><div class="col-sm-2"><div class="jv-kpi"><span>Open</span><b id="kpi_open">0</b></div></div><div class="col-sm-2"><div class="jv-kpi"><span>In Process</span><b id="kpi_process">0</b></div></div><div class="col-sm-2"><div class="jv-kpi"><span>Requested HC</span><b id="kpi_requested">0</b></div></div><div class="col-sm-2"><div class="jv-kpi"><span>Filled HC</span><b id="kpi_filled">0</b></div></div><div class="col-sm-2"><div class="jv-kpi"><span>Applicants</span><b id="kpi_applicants">0</b></div></div></div>
<div class="box jv-card"><div class="box-header"><h3 class="box-title"><i class="fa fa-filter"></i> Filter Job Vacancy</h3></div><div class="box-body"><form class="form-horizontal" onsubmit="return false;"><div class="form-group"><label class="control-label col-lg-2">Posting Period</label><div class="col-lg-2"><div class="input-group date jv-date"><input id="filter_tgl_awal" class="form-control" value="<?=$defaultFrom;?>"><span class="input-group-addon"><span class="glyphicon glyphicon-calendar"></span></span></div></div><div class="col-lg-2"><div class="input-group date jv-date"><input id="filter_tgl_akhir" class="form-control" value="<?=$defaultTo;?>"><span class="input-group-addon"><span class="glyphicon glyphicon-calendar"></span></span></div></div><label class="control-label col-lg-1">Type</label><div class="col-lg-2"><select id="filter_vacancy_type" class="form-control"><option value=""><?=hr_h('common_all', 'All');?></option><option>NEW_POSITION</option><option>REPLACEMENT</option><option>INTERNAL_TRANSFER</option><option>TEMPORARY</option><option>PROJECT</option></select></div><label class="control-label col-lg-1"><?=hr_h('common_status', 'Status');?></label><div class="col-lg-2"><select id="filter_vacancy_status" class="form-control"><option value=""><?=hr_h('common_all', 'All');?></option><option>DRAFT</option><option>OPEN</option><option>SCREENING</option><option>INTERVIEW</option><option>OFFER</option><option>HIRED</option><option>CANCELLED</option><option>CLOSED</option></select></div></div><div class="form-group"><label class="control-label col-lg-2"><?=hr_h('hr_department', 'Department');?></label><div class="col-lg-3"><select id="filter_department_code" class="form-control"></select></div><div class="col-lg-5"><input id="filter_keyword" class="form-control" placeholder="Vacancy no, title, position, job title, SAP ref"></div><div class="col-lg-2"><button id="btn_filter_jv" class="btn btn-primary"><i class="fa fa-filter"></i> <?=hr_h('common_filter', 'Filter');?></button> <button id="btn_reset_jv" class="btn btn-default"><i class="fa fa-refresh"></i></button></div></div></form></div></div>
<div class="box jv-card"><div class="box-body"><div class="alert alert-warning error_data_delete" style="display:none"><button type="button" class="close hide_alert_notif">&times;</button><span class="isi_warning_delete"></span></div><div class="table-responsive"><table id="dtb_job_vacancy" class="table table-bordered table-striped" style="width:100%"><thead><tr><th><?=hr_h('common_no', 'No');?></th><th><?=hr_h('common_action', 'Action');?></th><th>Vacancy No</th><th>Vacancy</th><th>Org / Dept</th><th>Type</th><th>Headcount</th><th>Pipeline</th><th>Posting</th><th><?=hr_h('common_status', 'Status');?></th><th>Updated</th></tr></thead><tbody></tbody></table></div></div></div>
<div id="modal_jv" class="modal fade"><div class="modal-dialog modal-lg" style="width:96%"><div class="modal-content"><form id="form_jv"><input type="hidden" name="id" id="jv_id"><div class="modal-header"><button type="button" class="close" data-dismiss="modal">&times;</button><h4 class="modal-title">Create Job Vacancy</h4></div><div class="modal-body">
<div class="alert alert-info"><strong>SAP hint:</strong> Vacancy bisa dibuat dari manpower plan atau langsung dari position. Jika memilih position, field organisasi akan auto-terisi.</div>
<div class="jv-section">Vacancy Header</div><div class="row"><div class="col-md-2 form-group"><label class="required-label">Vacancy No</label><div class="input-group"><input name="vacancy_no" id="vacancy_no" class="form-control" readonly><span class="input-group-btn"><button type="button" id="btn_next_jv" class="btn btn-default"><i class="fa fa-refresh"></i></button></span></div></div><div class="col-md-4 form-group"><label class="required-label">Vacancy Title</label><input name="vacancy_title" id="vacancy_title" class="form-control" required maxlength="150"></div><div class="col-md-3 form-group"><label>Manpower Plan</label><select name="manpower_plan_id" id="manpower_plan_id" class="form-control"></select></div><div class="col-md-3 form-group"><label><?=hr_h('hr_position', 'Position');?></label><select name="position_id" id="position_id" class="form-control"></select></div></div>
<div class="row"><div class="col-md-3 form-group"><label><?=hr_h('hr_job_title', 'Job Title');?></label><select name="job_title_id" id="job_title_id" class="form-control"></select></div><div class="col-md-3 form-group"><label>Org Unit</label><select name="company_structure_id" id="company_structure_id" class="form-control"></select></div><div class="col-md-3 form-group"><label><?=hr_h('hr_department', 'Department');?></label><select name="department_code" id="department_code" class="form-control"></select></div><div class="col-md-3 form-group"><label><?=hr_h('hr_work_location', 'Work Location');?></label><select name="work_location_id" id="work_location_id" class="form-control"></select></div></div>
<div class="row"><div class="col-md-2 form-group"><label>Vacancy Type</label><select name="vacancy_type" id="vacancy_type" class="form-control"><option>NEW_POSITION</option><option>REPLACEMENT</option><option>INTERNAL_TRANSFER</option><option>TEMPORARY</option><option>PROJECT</option></select></div><div class="col-md-2 form-group"><label>Employment</label><select name="employment_type" id="employment_type" class="form-control"><option>PERMANENT</option><option>CONTRACT</option><option>DAILY_WORKER</option><option>INTERNSHIP</option><option>OUTSOURCE</option></select></div><div class="col-md-2 form-group"><label>Employee Group</label><select name="employee_group" id="employee_group" class="form-control"><option>STAFF</option><option>OPERATOR</option><option>MANAGER</option><option>DIRECTOR</option><option>NON_STAFF</option><option>CONTRACT</option><option>DAILY_WORKER</option><option>TRAINEE</option></select></div><div class="col-md-2 form-group"><label>Pay Grade</label><input name="pay_grade" id="pay_grade" class="form-control"></div><div class="col-md-2 form-group"><label>Priority</label><select name="priority" id="priority" class="form-control"><option>MEDIUM</option><option>LOW</option><option>HIGH</option><option>CRITICAL</option></select></div><div class="col-md-2 form-group"><label><?=hr_h('common_status', 'Status');?></label><select name="vacancy_status" id="vacancy_status" class="form-control"><option>DRAFT</option><option>OPEN</option><option>SCREENING</option><option>INTERVIEW</option><option>OFFER</option><option>HIRED</option><option>CANCELLED</option><option>CLOSED</option></select></div></div>
<div class="jv-section">Planning & Publishing</div><div class="row"><div class="col-md-2 form-group"><label>Requested HC</label><input name="headcount_requested" id="headcount_requested" type="number" step="0.01" min="0.01" class="form-control" value="1"></div><div class="col-md-2 form-group"><label>Approved HC</label><input name="headcount_approved" id="headcount_approved" type="number" step="0.01" min="0" class="form-control" value="0"></div><div class="col-md-2 form-group"><label>Filled HC</label><input name="headcount_filled" id="headcount_filled" type="number" step="0.01" min="0" class="form-control" value="0"></div><div class="col-md-2 form-group"><label>Posting Date</label><input name="posting_date" id="posting_date" class="form-control date-field"></div><div class="col-md-2 form-group"><label>Closing Date</label><input name="closing_date" id="closing_date" class="form-control date-field"></div><div class="col-md-2 form-group"><label>Target Join</label><input name="target_join_date" id="target_join_date" class="form-control date-field"></div></div>
<div class="row"><div class="col-md-3 form-group"><label>Recruiter</label><select name="recruiter_employee_id" id="recruiter_employee_id" class="form-control"></select></div><div class="col-md-3 form-group"><label>Hiring Manager</label><select name="hiring_manager_employee_id" id="hiring_manager_employee_id" class="form-control"></select></div><div class="col-md-2 form-group"><label>Publish Internal</label><select name="publish_internal" id="publish_internal" class="form-control"><option>Y</option><option>N</option></select></div><div class="col-md-2 form-group"><label>Publish External</label><select name="publish_external" id="publish_external" class="form-control"><option>N</option><option>Y</option></select></div><div class="col-md-2 form-group"><label>Source Channel</label><input name="source_channel" id="source_channel" class="form-control"></div></div>
<div class="jv-section">Compensation & Pipeline</div><div class="row"><div class="col-md-2 form-group"><label>Salary Min</label><input name="salary_min" id="salary_min" type="number" step="0.01" min="0" class="form-control" value="0"></div><div class="col-md-2 form-group"><label>Salary Max</label><input name="salary_max" id="salary_max" type="number" step="0.01" min="0" class="form-control" value="0"></div><div class="col-md-1 form-group"><label>Currency</label><select name="currency" id="currency" class="form-control"><option>IDR</option><option>USD</option><option>EUR</option></select></div><div class="col-md-1 form-group"><label><?=hr_h('hr_applicant', 'Applicant');?></label><input name="applicant_count" id="applicant_count" type="number" min="0" class="form-control" value="0"></div><div class="col-md-1 form-group"><label>Shortlist</label><input name="shortlisted_count" id="shortlisted_count" type="number" min="0" class="form-control" value="0"></div><div class="col-md-1 form-group"><label><?=hr_h('hr_interview', 'Interview');?></label><input name="interview_count" id="interview_count" type="number" min="0" class="form-control" value="0"></div><div class="col-md-1 form-group"><label>Offer</label><input name="offer_count" id="offer_count" type="number" min="0" class="form-control" value="0"></div><div class="col-md-1 form-group"><label>Hired</label><input name="hired_count" id="hired_count" type="number" min="0" class="form-control" value="0"></div><div class="col-md-2 form-group"><label>Cost Center</label><select name="cost_center_code" id="cost_center_code" class="form-control"></select></div></div>
<div class="row"><div class="col-md-3 form-group"><label>Profit Center</label><select name="profit_center_code" id="profit_center_code" class="form-control"></select></div><div class="col-md-3 form-group"><label>SAP Reference</label><input name="sap_reference" id="sap_reference" class="form-control"></div><div class="col-md-3 form-group"><label>Cancellation Reason</label><input name="cancellation_reason" id="cancellation_reason" class="form-control"></div><div class="col-md-3 form-group"><label><?=hr_h('common_remarks', 'Remarks');?></label><input name="remarks" id="remarks" class="form-control"></div></div>
<div class="jv-section">Job Profile</div><div class="row"><div class="col-md-6 form-group"><label>Job Description</label><textarea name="job_description" id="job_description" class="form-control" rows="3"></textarea></div><div class="col-md-6 form-group"><label>Qualification Requirement</label><textarea name="qualification_requirement" id="qualification_requirement" class="form-control" rows="3"></textarea></div></div><div class="row"><div class="col-md-6 form-group"><label>Responsibilities</label><textarea name="responsibilities" id="responsibilities" class="form-control" rows="3"></textarea></div><div class="col-md-6 form-group"><label>Benefits</label><textarea name="benefits" id="benefits" class="form-control" rows="3"></textarea></div></div>
</div><div class="modal-footer"><button type="button" class="btn btn-default" data-dismiss="modal"><?=hr_h('common_cancel', 'Cancel');?></button><button type="submit" class="btn btn-primary"><i class="fa fa-save"></i> Save Vacancy</button></div></form></div></div></div>
<div id="modal_jv_detail" class="modal fade"><div class="modal-dialog modal-lg" style="width:94%"><div class="modal-content"><div class="modal-header"><button class="close" data-dismiss="modal">&times;</button><h4 class="modal-title">Job Vacancy Detail</h4></div><div class="modal-body" id="jv_detail_body"></div><div class="modal-footer"><button class="btn btn-default" data-dismiss="modal"><?=hr_h('common_close', 'Close');?></button></div></div></div></div>
</section>
<script src="<?=base_admin();?>assets/plugins/select2/select2.min.js"></script><script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
<script>
function jvError(m){$('.isi_warning_delete').text(m||'Job Vacancy gagal diproses.');$('.error_data_delete').fadeIn();}
function jvFilters(){return{tgl_awal:$('#filter_tgl_awal').val(),tgl_akhir:$('#filter_tgl_akhir').val(),vacancy_type:$('#filter_vacancy_type').val(),vacancy_status:$('#filter_vacancy_status').val(),department_code:$('#filter_department_code').val(),keyword:$('#filter_keyword').val()};}
function jvSet(s,v,t){var e=$(s);if(!v){e.val(null).trigger('change');return;}if(!e.find('option[value="'+v+'"]').length)e.append(new Option(t||v,v,true,true));e.val(v).trigger('change');}
function jvAjaxSelect(selector,act,placeholder,parent){$(selector).select2({width:'100%',allowClear:true,placeholder:placeholder,dropdownParent:parent||$(document.body),ajax:{url:'<?=base_admin();?>modul/job_vacancy/job_vacancy_action.php?act='+act,type:'POST',dataType:'json',delay:250,data:function(q){return{term:q.term||''};},processResults:function(d){return{results:d.results||[]};}}});}
function loadNextJv(){ $.post('<?=base_admin();?>modul/job_vacancy/job_vacancy_action.php?act=next_no',{year:($('#posting_date').val()||'<?=date('Y');?>').substr(0,4)},function(r){ if(r.status==='good')$('#vacancy_no').val(r.vacancy_no); },'json'); }
function resetJv(title){$('#form_jv')[0].reset();$('#jv_id').val('');$('#vacancy_type').val('NEW_POSITION').trigger('change');$('#employment_type').val('PERMANENT').trigger('change');$('#employee_group').val('STAFF').trigger('change');$('#priority').val('MEDIUM').trigger('change');$('#vacancy_status').val('DRAFT').trigger('change');$('#publish_internal').val('Y').trigger('change');$('#publish_external').val('N').trigger('change');$('#currency').val('IDR').trigger('change');$('#manpower_plan_id,#position_id,#job_title_id,#company_structure_id,#department_code,#work_location_id,#recruiter_employee_id,#hiring_manager_employee_id,#cost_center_code,#profit_center_code').val(null).trigger('change');$('#headcount_requested').val(1);$('#headcount_approved,#headcount_filled,#salary_min,#salary_max,#applicant_count,#shortlisted_count,#interview_count,#offer_count,#hired_count').val(0);$('#modal_jv .modal-title').text(title||'Create Job Vacancy');loadNextJv();}
$(function(){if($.fn.datepicker){$('.jv-date,.date-field').datepicker({format:'yyyy-mm-dd',autoclose:true,todayHighlight:true});}if($.fn.select2){$('#filter_vacancy_type,#filter_vacancy_status,#vacancy_type,#employment_type,#employee_group,#priority,#vacancy_status,#publish_internal,#publish_external,#currency').select2({width:'100%',allowClear:true});jvAjaxSelect('#filter_department_code','department_search','Semua Department');jvAjaxSelect('#manpower_plan_id','manpower_plan_search','Pilih Manpower Plan',$('#modal_jv'));jvAjaxSelect('#position_id','position_search','Pilih Position',$('#modal_jv'));jvAjaxSelect('#job_title_id','job_title_search','Pilih Job Title',$('#modal_jv'));jvAjaxSelect('#company_structure_id','company_structure_search','Pilih Org Unit',$('#modal_jv'));jvAjaxSelect('#department_code','department_search','Pilih Department',$('#modal_jv'));jvAjaxSelect('#work_location_id','work_location_search','Pilih Work Location',$('#modal_jv'));jvAjaxSelect('#recruiter_employee_id','employee_search','Pilih Recruiter',$('#modal_jv'));jvAjaxSelect('#hiring_manager_employee_id','employee_search','Pilih Hiring Manager',$('#modal_jv'));jvAjaxSelect('#cost_center_code','cost_center_search','Pilih Cost Center',$('#modal_jv'));jvAjaxSelect('#profit_center_code','profit_center_search','Pilih Profit Center',$('#modal_jv'));}
var dt=$('#dtb_job_vacancy').DataTable({bProcessing:true,bServerSide:true,pageLength:25,dom:"<'row'<'col-sm-12'B>>"+"<'row'<'col-sm-6'l><'col-sm-6'f>>"+"<'row'<'col-sm-12'tr>>"+"<'row'<'col-sm-5'i><'col-sm-7'p>>",buttons:[{extend:'collection',text:<?=hr_js('common_export_data', 'Export Data');?>,buttons:['copyHtml5','excelHtml5','csvHtml5','pdfHtml5']}],columnDefs:[{targets:[0,1],orderable:false,searchable:false},{targets:[6,7],className:'text-right'},{width:'42px',targets:0},{width:'150px',targets:1}],ajax:{url:'<?=base_admin();?>modul/job_vacancy/job_vacancy_data.php',type:'post',data:function(d){$.extend(d,jvFilters());},dataSrc:function(j){var k=j.kpi||{};$('#kpi_total').text(k.total||0);$('#kpi_open').text(k.open||0);$('#kpi_process').text(k.process||0);$('#kpi_requested').text(k.requested_hc||0);$('#kpi_filled').text(k.filled_hc||0);$('#kpi_applicants').text(k.applicants||0);return j.data||[];},error:function(xhr){console.log(xhr.responseText);jvError('Data Job Vacancy gagal dimuat.');}}});
$('#btn_open_jv').click(function(){resetJv('Create Job Vacancy');$('#modal_jv').modal({backdrop:'static',keyboard:false});});$('#btn_next_jv,#posting_date').on('click change',loadNextJv);$('#btn_filter_jv').click(function(){dt.draw();});$('#filter_keyword').keyup(function(e){if(e.keyCode===13)dt.draw();});$('#btn_reset_jv').click(function(){$('#filter_tgl_awal').val('<?=$defaultFrom;?>');$('#filter_tgl_akhir').val('<?=$defaultTo;?>');$('#filter_vacancy_type,#filter_vacancy_status,#filter_department_code').val(null).trigger('change');$('#filter_keyword').val('');dt.draw();});$('#btn_export_jv').click(function(){window.location='<?=base_admin();?>modul/job_vacancy/job_vacancy_action.php?act=export&'+$.param(jvFilters());});$('.hide_alert_notif').click(function(){$('.error_data_delete').hide();});
$('#position_id').on('select2:select',function(e){$.post('<?=base_admin();?>modul/job_vacancy/job_vacancy_action.php?act=position_info',{id:e.params.data.id},function(r){if(r.status!=='good')return;var d=r.data||{};jvSet('#job_title_id',d.job_title_id,d.job_title_text);jvSet('#department_code',d.department_code,d.department_text);jvSet('#company_structure_id',d.company_structure_id,d.company_structure_text);jvSet('#cost_center_code',d.cost_center_code,d.cost_center_text);jvSet('#profit_center_code',d.profit_center_code,d.profit_center_text);jvSet('#work_location_id',d.work_location_id,d.work_location_text);$('#employee_group').val(d.employee_group||'STAFF').trigger('change');$('#pay_grade').val(d.pay_grade||'');$('#vacancy_title').val(d.vacancy_title||$('#vacancy_title').val());$('#headcount_requested').val(d.headcount_requested||1);},'json');});
$('#form_jv').submit(function(e){e.preventDefault();var b=$(this).find('button[type=submit]');b.prop('disabled',true).html('<i class="fa fa-spinner fa-spin"></i> <?=hr_h('common_saving', 'Saving...');?>');$.post('<?=base_admin();?>modul/job_vacancy/job_vacancy_action.php?act=save',$(this).serialize(),function(r){b.prop('disabled',false).html('<i class="fa fa-save"></i> Save Vacancy');if(r.status==='good'){$('#modal_jv').modal('hide');dt.draw(false);Swal.fire('Saved','Job Vacancy berhasil disimpan.','success');}else jvError(r.error_message);},'json').fail(function(xhr){b.prop('disabled',false).html('<i class="fa fa-save"></i> Save Vacancy');jvError(xhr.responseText);});});
$(document).on('click','.btn-jv-detail',function(){$.post('<?=base_admin();?>modul/job_vacancy/job_vacancy_action.php?act=detail',{id:$(this).data('id')},function(h){$('#jv_detail_body').html(h);$('#modal_jv_detail').modal('show');});});
$(document).on('click','.btn-jv-edit',function(){var id=$(this).data('id');$.post('<?=base_admin();?>modul/job_vacancy/job_vacancy_action.php?act=get',{id:id},function(r){if(r.status!=='good'){jvError(r.error_message);return;}resetJv('Edit Job Vacancy');var h=r.data||{};Object.keys(h).forEach(function(k){var el=$('#'+k);if(el.length&&!['manpower_plan_id','position_id','job_title_id','company_structure_id','department_code','work_location_id','recruiter_employee_id','hiring_manager_employee_id','cost_center_code','profit_center_code'].includes(k))el.val(h[k]);});$('#jv_id').val(h.id);jvSet('#manpower_plan_id',h.manpower_plan_id,h.manpower_plan_text);jvSet('#position_id',h.position_id,h.position_text);jvSet('#job_title_id',h.job_title_id,h.job_title_text);jvSet('#company_structure_id',h.company_structure_id,h.company_structure_text);jvSet('#department_code',h.department_code,h.department_text);jvSet('#work_location_id',h.work_location_id,h.work_location_text);jvSet('#recruiter_employee_id',h.recruiter_employee_id,h.recruiter_text);jvSet('#hiring_manager_employee_id',h.hiring_manager_employee_id,h.hiring_manager_text);jvSet('#cost_center_code',h.cost_center_code,h.cost_center_text);jvSet('#profit_center_code',h.profit_center_code,h.profit_center_text);$('#vacancy_type,#employment_type,#employee_group,#priority,#vacancy_status,#publish_internal,#publish_external,#currency').trigger('change');$('#modal_jv').modal({backdrop:'static',keyboard:false});},'json');});
$(document).on('click','.btn-jv-status',function(){var id=$(this).data('id'),status=$(this).data('status');$.post('<?=base_admin();?>modul/job_vacancy/job_vacancy_action.php?act=status',{id:id,status:status},function(r){if(r.status==='good'){dt.draw(false);Swal.fire('Updated','Status berhasil diubah.','success');}else jvError(r.error_message);},'json');});
$(document).on('click','.btn-jv-delete',function(){var id=$(this).data('id'),no=$(this).data('no');Swal.fire({title:erpLang('confirm_delete_title','Delete Confirmation'),text:no,icon:'warning',showCancelButton:true,confirmButtonText:erpLang('common_delete','Delete'),cancelButtonText:erpLang('common_cancel','Cancel')}).then(function(x){if(!x.isConfirmed)return;$.post('<?=base_admin();?>modul/job_vacancy/job_vacancy_action.php?act=delete',{id:id},function(r){if(r.status==='good'){dt.draw(false);Swal.fire(erpLang('common_deleted','Deleted'),erpLang('common_deleted_message','Data deleted successfully.'),'success');}else jvError(r.error_message);},'json').fail(function(xhr){jvError(xhr.responseText);});});});
});
</script>
