<?php
if (!function_exists('prod_t')) {
  function prod_t($key, $fallback = '') { return lang_text($key, $fallback); }
}
if (!function_exists('prod_h')) {
  function prod_h($key, $fallback = '') { return htmlspecialchars((string) prod_t($key, $fallback), ENT_QUOTES, 'UTF-8'); }
}
if (!function_exists('prod_js')) {
  function prod_js($key, $fallback = '') { return json_encode(prod_t($key, $fallback), JSON_HEX_TAG | JSON_HEX_APOS | JSON_HEX_AMP | JSON_HEX_QUOT); }
}
$defaultFrom=date('Y-m-01');$defaultTo=date('Y-m-d');
$plants=$db->query("SELECT DISTINCT plant AS plant_code FROM production_order WHERE plant IS NOT NULL AND plant<>'' ORDER BY plant");
$kpi=$db->fetch("SELECT COUNT(*) total_wip,SUM(status='RELEASED') released_order,SUM(status='IN_PROCESS') in_process_order,SUM(status='CONFIRMED') confirmed_order FROM production_order WHERE status IN ('RELEASED','IN_PROCESS','CONFIRMED','TECO') AND start_date BETWEEN ? AND ?",array($defaultFrom,$defaultTo));
$flow=$db->fetch("SELECT COALESCE(SUM(conf.yield_qty),0) yield_qty,COALESCE(SUM(gr.gr_qty),0) gr_qty FROM production_order p LEFT JOIN (SELECT id_production_order,SUM(CASE WHEN status='POSTED' THEN yield_qty ELSE 0 END) yield_qty FROM production_order_confirmation GROUP BY id_production_order) conf ON conf.id_production_order=p.id_production_order LEFT JOIN (SELECT h.id_production_order,SUM(CASE WHEN h.status='POSTED' THEN d.qty ELSE 0 END) gr_qty FROM erp_gr_production h JOIN erp_gr_production_detail d ON d.gr_id=h.id GROUP BY h.id_production_order) gr ON gr.id_production_order=p.id_production_order WHERE p.status IN ('RELEASED','IN_PROCESS','CONFIRMED','TECO') AND p.start_date BETWEEN ? AND ?",array($defaultFrom,$defaultTo));
?>
<style>
.wip-hero{background:linear-gradient(135deg,#7c2d12,#7c3aed);color:#fff;border-radius:14px;padding:20px 22px;margin-bottom:18px;box-shadow:0 10px 24px rgba(15,23,42,.18)}.wip-hero h1{margin:0 0 6px;font-size:26px;font-weight:700}.wip-hero p{margin:0;opacity:.92}.wip-card{border-radius:12px;background:#fff;border:1px solid #e5edf5;box-shadow:0 5px 16px rgba(15,23,42,.05);margin-bottom:14px}.wip-kpi{border-radius:12px;background:#fff;border:1px solid #edf2f7;padding:15px;margin-bottom:14px}.wip-kpi span{display:block;color:#64748b;font-size:12px;text-transform:uppercase}.wip-kpi strong{display:block;font-size:24px;margin-top:6px}.wip-kpi i{float:right;font-size:26px;color:#7c2d12;opacity:.55}#dtb_wip_monitoring th,#dtb_wip_monitoring td{font-size:12px;vertical-align:middle}.select2-container{width:100%!important}.progress-xs{height:7px}.wip-progress{min-width:150px}
</style>
<section class="content-header"><h1><?=prod_h('production_wip_monitoring', 'WIP Monitoring');?> <small>SAP PP Work In Process</small></h1><ol class="breadcrumb"><li><a href="<?=base_index();?>"><i class="fa fa-dashboard"></i> <?=prod_h('common_home', 'Home');?></a></li><li class="active"><?=prod_h('production_wip_monitoring', 'WIP Monitoring');?></li></ol></section>
<section class="content">
  <div class="wip-hero"><div class="row"><div class="col-md-8"><h1>WIP Monitoring Cockpit</h1><p>Monitor order produksi yang masih dalam proses: material issued, confirmation parsial, outstanding GR, aging, dan dokumen produksi terkait.</p></div><div class="col-md-4 text-right"><button id="btn_excel_wip_top" class="btn btn-success"><i class="fa fa-file-excel-o"></i> Export WIP</button></div></div></div>
  <div class="row"><div class="col-sm-3"><div class="wip-kpi"><i class="fa fa-hourglass-half"></i><span>Total WIP Order</span><strong><?=number_format((float)$kpi->total_wip,0,',','.');?></strong></div></div><div class="col-sm-3"><div class="wip-kpi"><i class="fa fa-unlock"></i><span><?=prod_h('production_released', 'Released');?></span><strong><?=number_format((float)$kpi->released_order,0,',','.');?></strong></div></div><div class="col-sm-3"><div class="wip-kpi"><i class="fa fa-cogs"></i><span><?=prod_h('production_in_process', 'In Process');?></span><strong><?=number_format((float)$kpi->in_process_order,0,',','.');?></strong></div></div><div class="col-sm-3"><div class="wip-kpi"><i class="fa fa-truck"></i><span>Outstanding GR Qty</span><strong><?=number_format(max((float)$flow->yield_qty-(float)$flow->gr_qty,0),2,',','.');?></strong></div></div></div>
  <div class="box wip-card"><div class="box-header"><h3 class="box-title"><i class="fa fa-filter"></i> Filter WIP</h3></div><div class="box-body"><form class="form-horizontal" onsubmit="return false;"><div class="form-group"><label class="control-label col-lg-2"><?=prod_h('production_start_date', 'Start Date');?></label><div class="col-lg-2"><div class="input-group date wip-date"><input id="filter_tgl_awal" class="form-control" value="<?=$defaultFrom;?>"><span class="input-group-addon"><span class="glyphicon glyphicon-calendar"></span></span></div></div><div class="col-lg-2"><div class="input-group date wip-date"><input id="filter_tgl_akhir" class="form-control" value="<?=$defaultTo;?>"><span class="input-group-addon"><span class="glyphicon glyphicon-calendar"></span></span></div></div><label class="control-label col-lg-1"><?=prod_h('common_status', 'Status');?></label><div class="col-lg-2"><select id="filter_status" class="form-control"><option value=""><?=prod_h('common_all', 'All');?></option><option>RELEASED</option><option>IN_PROCESS</option><option>CONFIRMED</option><option>TECO</option></select></div><label class="control-label col-lg-1"><?=prod_h('production_plant', 'Plant');?></label><div class="col-lg-2"><select id="filter_plant" class="form-control"><option value=""><?=prod_h('common_all', 'All');?></option><?php foreach($plants as $p){ ?><option value="<?=htmlspecialchars($p->plant_code,ENT_QUOTES,'UTF-8');?>"><?=htmlspecialchars($p->plant_code,ENT_QUOTES,'UTF-8');?></option><?php } ?></select></div></div><div class="form-group"><label class="control-label col-lg-2">WIP State</label><div class="col-lg-3"><select id="filter_wip_state" class="form-control"><option value="">Semua WIP</option><option value="MATERIAL_ISSUED">Material issued belum confirmation</option><option value="AWAITING_GR">Confirmation belum GR</option><option value="SHORT_CONFIRMATION">Confirmation belum penuh</option></select></div><label class="control-label col-lg-1"><?=prod_h('common_search', 'Search');?></label><div class="col-lg-3"><input id="filter_keyword" class="form-control" placeholder="PO, SO, customer PO, material"></div><div class="col-lg-3"><button id="btn_filter_wip" class="btn btn-primary"><i class="fa fa-filter"></i> <?=prod_h('common_filter', 'Filter');?></button> <button id="btn_reset_wip" class="btn btn-default"><i class="fa fa-refresh"></i> <?=prod_h('common_reset', 'Reset');?></button> <button id="btn_excel_wip" class="btn btn-success"><i class="fa fa-file-excel-o"></i> <?=prod_h('common_export_excel', 'Export Excel');?></button></div></div></form></div></div>
  <div class="box wip-card"><div class="box-body"><div class="alert alert-warning error_data_delete" style="display:none"><button type="button" class="close hide_alert_notif">&times;</button><span class="isi_warning_delete"></span></div><div class="table-responsive"><table id="dtb_wip_monitoring" class="table table-bordered table-striped table-condensed" style="width:100%"><thead><tr><th><?=prod_h('common_no', 'No');?></th><th><?=prod_h('common_action', 'Action');?></th><th><?=prod_h('production_order', 'Production Order');?></th><th><?=prod_h('production_material', 'Material');?></th><th>Qty Flow</th><th>Plant/SLoc</th><th>Dates & Aging</th><th>Progress</th><th>Outstanding</th><th>Documents</th><th>WIP State</th><th>PO Status</th></tr></thead><tbody></tbody></table></div></div></div>
  <div id="modal_detail_wip" class="modal fade"><div class="modal-dialog modal-lg" style="width:96%"><div class="modal-content"><div class="modal-header"><button class="close" data-dismiss="modal">&times;</button><h4 class="modal-title">WIP Detail</h4></div><div class="modal-body" id="wip_detail_body"></div><div class="modal-footer"><button class="btn btn-default" data-dismiss="modal"><?=prod_h('common_close', 'Close');?></button></div></div></div></div>
</section>
<script src="<?=base_admin();?>assets/plugins/select2/select2.min.js"></script>
<script>
function wipError(m){$('.isi_warning_delete').text(m||<?=prod_js('production_wip_monitoring_process_failed', 'WIP Monitoring failed to process.');?>);$('.error_data_delete').fadeIn();}
function wipFilters(){return{tgl_awal:$('#filter_tgl_awal').val(),tgl_akhir:$('#filter_tgl_akhir').val(),status:$('#filter_status').val(),plant:$('#filter_plant').val(),wip_state:$('#filter_wip_state').val(),keyword:$('#filter_keyword').val()};}
function wipQuery(){return $.param(wipFilters());}
$(function(){if($.fn.datepicker){$('.wip-date').datepicker({format:'yyyy-mm-dd',autoclose:true,todayHighlight:true});}if($.fn.select2){$('#filter_status,#filter_plant,#filter_wip_state').select2({width:'100%',allowClear:true});}
var dt=$('#dtb_wip_monitoring').DataTable({bProcessing:true,bServerSide:true,pageLength:25,ordering:false,dom:"<'row'<'col-sm-12'B>>"+"<'row'<'col-sm-6'l><'col-sm-6'f>>"+"<'row'<'col-sm-12'tr>>"+"<'row'<'col-sm-5'i><'col-sm-7'p>>",buttons:[{extend:'collection',text:<?=prod_js('common_export_data', 'Export Data');?>,buttons:['copyHtml5','excelHtml5','csvHtml5','pdfHtml5']}],columnDefs:[{targets:[0,1],orderable:false,searchable:false},{width:'38px',targets:0},{width:'58px',targets:1},{className:'wip-progress',targets:7}],ajax:{url:'<?=base_admin();?>modul/wip_monitoring/wip_monitoring_data.php',type:'post',data:function(d){$.extend(d,wipFilters());},error:function(xhr){console.log(xhr.responseText);wipError(<?=prod_js('production_wip_load_failed', 'WIP data failed to load.');?>);}}});
$('#btn_filter_wip').click(function(){dt.draw();});$('#filter_keyword').keyup(function(e){if(e.keyCode===13)dt.draw();});$('#btn_reset_wip').click(function(){$('#filter_tgl_awal').val('<?=$defaultFrom;?>');$('#filter_tgl_akhir').val('<?=$defaultTo;?>');$('#filter_status,#filter_plant,#filter_wip_state').val('').trigger('change');$('#filter_keyword').val('');dt.draw();});$('#btn_excel_wip,#btn_excel_wip_top').click(function(){window.location='<?=base_admin();?>modul/wip_monitoring/wip_monitoring_action.php?act=excel&'+wipQuery();});
$(document).on('click','.btn-wip-detail',function(){$.post('<?=base_admin();?>modul/wip_monitoring/wip_monitoring_action.php?act=detail',{id:$(this).data('id')},function(html){$('#wip_detail_body').html(html);$('#modal_detail_wip').modal('show');}).fail(function(){wipError('Detail WIP gagal dibuka.');});});$('.hide_alert_notif').click(function(){$('.error_data_delete').hide();});
});
</script>
