<?php
if (!function_exists('hr_t')) {
  function hr_t($key, $fallback = '') { return lang_text($key, $fallback); }
}
if (!function_exists('hr_h')) {
  function hr_h($key, $fallback = '') { return htmlspecialchars((string) hr_t($key, $fallback), ENT_QUOTES, 'UTF-8'); }
}
if (!function_exists('hr_js')) {
  function hr_js($key, $fallback = '') { return json_encode(hr_t($key, $fallback), JSON_HEX_TAG | JSON_HEX_APOS | JSON_HEX_AMP | JSON_HEX_QUOT); }
}
$defaultFrom=date('Y-01-01');$defaultTo=date('Y-m-d');$yearNow=(int)date('Y'); ?>
<style>
.pfr-hero{background:linear-gradient(135deg,#7c2d12,#0f766e);color:#fff;border-radius:14px;padding:22px;margin-bottom:16px;box-shadow:0 10px 24px rgba(124,45,18,.18)}.pfr-hero h1{margin:0 0 6px;font-size:27px;font-weight:700}.pfr-hero p{margin:0;color:#ffedd5}.pfr-card{border-radius:12px;background:#fff;border:1px solid #e5edf5;box-shadow:0 5px 16px rgba(15,23,42,.05);margin-bottom:14px}.pfr-kpi{padding:14px;border-radius:12px;background:#f8fafc;border:1px solid #dbeafe;min-height:78px}.pfr-kpi span{display:block;color:#64748b;font-size:12px}.pfr-kpi b{font-size:21px;color:#0f172a}.pfr-kpi.good{background:#ecfdf5;border-color:#bbf7d0}.pfr-kpi.warn{background:#fff7ed;border-color:#fed7aa}.pfr-kpi.danger{background:#fef2f2;border-color:#fecaca}#dtb_performance_report th,#dtb_performance_report td{font-size:12px;vertical-align:middle}.select2-container{width:100%!important}.pfr-detail{background:#fff;border:1px solid #e5e7eb;border-radius:12px;padding:18px}#modal_pfr_detail .modal-body{max-height:calc(100vh - 180px);overflow-y:auto}.pfr-filter .form-group{margin-bottom:12px}.pfr-score{text-align:right}
</style>
<section class="content-header"><h1><?=hr_h('hr_performance_report', 'Performance Report');?> <small>SAP-style Performance Analytics</small></h1><ol class="breadcrumb"><li><a href="<?=base_index();?>"><i class="fa fa-dashboard"></i> <?=hr_h('common_home', 'Home');?></a></li><li>Human Resource</li><li>HR Reports</li><li class="active"><?=hr_h('hr_performance_report', 'Performance Report');?></li></ol></section>
<section class="content">
<div class="pfr-hero"><div class="row"><div class="col-md-8"><h1>Performance Report Cockpit</h1><p>Monitoring hasil appraisal per cycle: KPI, competency, behavior, rating, calibration status, high performer, PIP, dan rekomendasi development.</p></div><div class="col-md-4 text-right"><button id="btn_export_pfr" class="btn btn-success"><i class="fa fa-file-excel-o"></i> <?=hr_h('common_export_excel', 'Export Excel');?></button></div></div></div>
<div class="row"><div class="col-sm-2"><div class="pfr-kpi"><span>Total Review</span><b id="kpi_pfr_total">0</b></div></div><div class="col-sm-2"><div class="pfr-kpi"><span>Employees</span><b id="kpi_pfr_employees">0</b></div></div><div class="col-sm-2"><div class="pfr-kpi good"><span>Avg Score</span><b id="kpi_pfr_avg">0</b></div></div><div class="col-sm-2"><div class="pfr-kpi good"><span>High Performer</span><b id="kpi_pfr_high">0</b></div></div><div class="col-sm-2"><div class="pfr-kpi danger"><span>Low Performer</span><b id="kpi_pfr_low">0</b></div></div><div class="col-sm-2"><div class="pfr-kpi warn"><span>PIP / Approved</span><b id="kpi_pfr_pip">0 / 0</b></div></div></div>
<div class="box pfr-card pfr-filter"><div class="box-header"><h3 class="box-title"><i class="fa fa-filter"></i> Filter Performance Report</h3></div><div class="box-body"><form class="form-horizontal" onsubmit="return false;">
  <div class="form-group"><label class="control-label col-lg-2">Appraisal Date</label><div class="col-lg-2"><div class="input-group date pfr-date"><input id="filter_tgl_awal" class="form-control" value="<?=$defaultFrom;?>"><span class="input-group-addon"><span class="glyphicon glyphicon-calendar"></span></span></div></div><div class="col-lg-2"><div class="input-group date pfr-date"><input id="filter_tgl_akhir" class="form-control" value="<?=$defaultTo;?>"><span class="input-group-addon"><span class="glyphicon glyphicon-calendar"></span></span></div></div><label class="control-label col-lg-1">Year</label><div class="col-lg-2"><select id="filter_cycle_year" class="form-control"><option value="">All</option><?php for($y=$yearNow-2;$y<=$yearNow+1;$y++){ ?><option value="<?=$y;?>" <?=$y===$yearNow?'selected':'';?>><?=$y;?></option><?php } ?></select></div><label class="control-label col-lg-1"><?=hr_h('hr_period', 'Period');?></label><div class="col-lg-2"><select id="filter_appraisal_period" class="form-control"><option value="">All</option><option>Q1</option><option>Q2</option><option>Q3</option><option>Q4</option><option>H1</option><option>H2</option><option>ANNUAL</option><option>PROBATION</option><option>SPECIAL</option></select></div></div>
  <div class="form-group"><label class="control-label col-lg-2"><?=hr_h('hr_employee', 'Employee');?></label><div class="col-lg-3"><select id="filter_employee_id" class="form-control"></select></div><label class="control-label col-lg-1">Appraiser</label><div class="col-lg-3"><select id="filter_appraiser_employee_id" class="form-control"></select></div><label class="control-label col-lg-1">Type</label><div class="col-lg-2"><select id="filter_appraisal_type" class="form-control"><option value="">All</option><option>ANNUAL</option><option>MID_YEAR</option><option>PROBATION</option><option>PROJECT</option><option>SPECIAL</option></select></div></div>
  <div class="form-group"><label class="control-label col-lg-2"><?=hr_h('hr_department', 'Department');?></label><div class="col-lg-3"><select id="filter_department_code" class="form-control"></select></div><label class="control-label col-lg-1"><?=hr_h('hr_job_title', 'Job Title');?></label><div class="col-lg-3"><select id="filter_job_title_id" class="form-control"></select></div><label class="control-label col-lg-1"><?=hr_h('hr_rating', 'Rating');?></label><div class="col-lg-2"><select id="filter_final_rating" class="form-control"><option value="">All</option><option>A</option><option>B</option><option>C</option><option>D</option><option>E</option></select></div></div>
  <div class="form-group"><label class="control-label col-lg-2"><?=hr_h('common_status', 'Status');?></label><div class="col-lg-2"><select id="filter_calibration_status" class="form-control"><option value="">All</option><option>DRAFT</option><option>SUBMITTED</option><option>MANAGER_APPROVED</option><option>HR_REVIEW</option><option>APPROVED</option><option>REJECTED</option><option>RETURNED</option><option>CANCELLED</option></select></div><label class="control-label col-lg-1">Decision</label><div class="col-lg-2"><select id="filter_decision" class="form-control"><option value="">All</option><option>PENDING</option><option>APPROVED</option><option>REJECTED</option><option>RETURNED</option></select></div><label class="control-label col-lg-1">Impact</label><div class="col-lg-2"><select id="filter_impact_type" class="form-control"><option value="">All</option><option value="HIGH_PERFORMER">High Performer</option><option value="LOW_PERFORMER">Low Performer</option><option value="PIP">PIP Required</option><option value="PENDING_APPROVAL">Pending Approval</option><option value="APPROVED_RESULT">Approved Result</option></select></div><div class="col-lg-2"><select id="filter_improvement_required" class="form-control"><option value="">PIP: All</option><option value="Y">Y</option><option value="N">N</option></select></div></div>
  <div class="form-group"><label class="control-label col-lg-2">Keyword</label><div class="col-lg-6"><input id="filter_keyword" class="form-control" placeholder="Appraisal no, employee, department, appraiser, recommendation"></div><div class="col-lg-4"><button id="btn_filter_pfr" class="btn btn-primary"><i class="fa fa-filter"></i> <?=hr_h('common_filter', 'Filter');?></button> <button id="btn_reset_pfr" class="btn btn-default"><i class="fa fa-refresh"></i> <?=hr_h('common_reset', 'Reset');?></button></div></div>
</form></div></div>
<div class="box pfr-card"><div class="box-body"><div class="alert alert-warning error_data_delete" style="display:none"><button type="button" class="close hide_alert_notif">&times;</button><span class="isi_warning_delete"></span></div><div class="table-responsive"><table id="dtb_performance_report" class="table table-bordered table-striped" style="width:100%"><thead><tr><th><?=hr_h('common_no', 'No');?></th><th><?=hr_h('common_action', 'Action');?></th><th>Appraisal</th><th>Cycle</th><th><?=hr_h('hr_employee', 'Employee');?></th><th>Organization</th><th>Appraiser</th><th>KPI</th><th>Competency</th><th>Behavior</th><th>Final Score</th><th><?=hr_h('hr_rating', 'Rating');?></th><th><?=hr_h('common_status', 'Status');?></th><th>Recommendation</th><th>Updated</th></tr></thead><tbody></tbody></table></div></div></div>
<div id="modal_pfr_detail" class="modal fade"><div class="modal-dialog modal-lg" style="width:94%"><div class="modal-content"><div class="modal-header"><button class="close" data-dismiss="modal">&times;</button><h4 class="modal-title">Performance Report Detail</h4></div><div class="modal-body" id="pfr_detail_body"></div><div class="modal-footer"><button class="btn btn-default" data-dismiss="modal"><?=hr_h('common_close', 'Close');?></button></div></div></div></div>
</section>
<script src="<?=base_admin();?>assets/plugins/select2/select2.min.js"></script>
<script>
function pfrError(m){$('.isi_warning_delete').text(m||'Performance Report gagal diproses.');$('.error_data_delete').fadeIn();}
function pfrFilters(){return{tgl_awal:$('#filter_tgl_awal').val(),tgl_akhir:$('#filter_tgl_akhir').val(),cycle_year:$('#filter_cycle_year').val(),appraisal_period:$('#filter_appraisal_period').val(),appraisal_type:$('#filter_appraisal_type').val(),employee_id:$('#filter_employee_id').val(),appraiser_employee_id:$('#filter_appraiser_employee_id').val(),department_code:$('#filter_department_code').val(),job_title_id:$('#filter_job_title_id').val(),final_rating:$('#filter_final_rating').val(),calibration_status:$('#filter_calibration_status').val(),decision:$('#filter_decision').val(),improvement_required:$('#filter_improvement_required').val(),impact_type:$('#filter_impact_type').val(),keyword:$('#filter_keyword').val()};}
function pfrAjax(s,act,p){$(s).select2({width:'100%',allowClear:true,placeholder:p,ajax:{url:'<?=base_admin();?>modul/performance_report/performance_report_action.php?act='+act,type:'POST',dataType:'json',delay:250,data:function(q){return{term:q.term||''};},processResults:function(d){return{results:d.results||[]};}}});}
$(function(){if($.fn.datepicker){$('.pfr-date').datepicker({format:'yyyy-mm-dd',autoclose:true,todayHighlight:true});}if($.fn.select2){$('#filter_cycle_year,#filter_appraisal_period,#filter_appraisal_type,#filter_final_rating,#filter_calibration_status,#filter_decision,#filter_improvement_required,#filter_impact_type').select2({width:'100%',allowClear:true});pfrAjax('#filter_employee_id','employee_search','Semua Employee');pfrAjax('#filter_appraiser_employee_id','appraiser_search','Semua Appraiser');pfrAjax('#filter_department_code','department_search','Semua Department');pfrAjax('#filter_job_title_id','job_title_search','Semua Job Title');}
var dt=$('#dtb_performance_report').DataTable({bProcessing:true,bServerSide:true,pageLength:25,dom:"<'row'<'col-sm-12'B>>"+"<'row'<'col-sm-6'l><'col-sm-6'f>>"+"<'row'<'col-sm-12'tr>>"+"<'row'<'col-sm-5'i><'col-sm-7'p>>",buttons:[{extend:'collection',text:<?=hr_js('common_export_data', 'Export Data');?>,buttons:['copyHtml5','excelHtml5','csvHtml5','pdfHtml5']}],columnDefs:[{targets:[0,1],orderable:false,searchable:false},{width:'42px',targets:0},{width:'68px',targets:1},{className:'pfr-score',targets:[7,8,9,10]}],ajax:{url:'<?=base_admin();?>modul/performance_report/performance_report_data.php',type:'post',data:function(d){$.extend(d,pfrFilters());},dataSrc:function(j){var k=j.kpi||{};$('#kpi_pfr_total').text(k.total||0);$('#kpi_pfr_employees').text(k.employees||0);$('#kpi_pfr_avg').text(k.avg_score||0);$('#kpi_pfr_high').text(k.high_performer||0);$('#kpi_pfr_low').text(k.low_performer||0);$('#kpi_pfr_pip').text((k.pip||0)+' / '+(k.approved||0));return j.data||[];},error:function(x){console.log(x.responseText);pfrError('Data Performance Report gagal dimuat.');}}});
$('#btn_filter_pfr').click(function(){dt.draw();});$('#filter_keyword').keyup(function(e){if(e.keyCode===13)dt.draw();});$('#btn_reset_pfr').click(function(){$('#filter_tgl_awal').val('<?=$defaultFrom;?>');$('#filter_tgl_akhir').val('<?=$defaultTo;?>');$('#filter_cycle_year').val('<?=$yearNow;?>').trigger('change');$('#filter_appraisal_period,#filter_appraisal_type,#filter_employee_id,#filter_appraiser_employee_id,#filter_department_code,#filter_job_title_id,#filter_final_rating,#filter_calibration_status,#filter_decision,#filter_improvement_required,#filter_impact_type').val(null).trigger('change');$('#filter_keyword').val('');dt.draw();});$('#btn_export_pfr').click(function(){window.location='<?=base_admin();?>modul/performance_report/performance_report_action.php?act=export&'+$.param(pfrFilters());});$('.hide_alert_notif').click(function(){$('.error_data_delete').hide();});
$(document).on('click','.btn-pfr-detail',function(){$.post('<?=base_admin();?>modul/performance_report/performance_report_action.php?act=detail',{id:$(this).data('id')},function(h){$('#pfr_detail_body').html(h);$('#modal_pfr_detail').modal('show');});});
});
</script>
