<?php
if (!function_exists('hr_t')) {
  function hr_t($key, $fallback = '') { return lang_text($key, $fallback); }
}
if (!function_exists('hr_h')) {
  function hr_h($key, $fallback = '') { return htmlspecialchars((string) hr_t($key, $fallback), ENT_QUOTES, 'UTF-8'); }
}
if (!function_exists('hr_js')) {
  function hr_js($key, $fallback = '') { return json_encode(hr_t($key, $fallback), JSON_HEX_TAG | JSON_HEX_APOS | JSON_HEX_AMP | JSON_HEX_QUOT); }
}
if (session_status() === PHP_SESSION_NONE) session_start();
include "../../inc/config.php";
session_check_json();
function hd_h($v){return htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');}
function hd_label($s){$m=array('DRAFT'=>'default','OFFER_PREPARED'=>'info','OFFER_SENT'=>'primary','OFFER_ACCEPTED'=>'success','PRE_EMPLOYMENT_CHECK'=>'warning','READY_TO_HIRE'=>'success','HIRED'=>'success','ONBOARDED'=>'success','CANCELLED'=>'default','DECLINED'=>'danger');$c=isset($m[$s])?$m[$s]:'default';return '<span class="label label-'.$c.'">'.hd_h($s).'</span>';}
function hd_filters(){return array('from'=>isset($_POST['tgl_awal'])&&$_POST['tgl_awal']!==''?$_POST['tgl_awal']:date('Y-m-01'),'to'=>isset($_POST['tgl_akhir'])&&$_POST['tgl_akhir']!==''?$_POST['tgl_akhir']:date('Y-m-t'),'status'=>isset($_POST['hiring_status'])?trim($_POST['hiring_status']):'','offer'=>isset($_POST['offer_status'])?trim($_POST['offer_status']):'','onboarding'=>isset($_POST['onboarding_status'])?trim($_POST['onboarding_status']):'','vacancy_id'=>isset($_POST['vacancy_id'])?trim($_POST['vacancy_id']):'','keyword'=>isset($_POST['keyword'])?trim($_POST['keyword']):'');}
function hd_where($f,&$p){$w=" WHERE h.hiring_date BETWEEN ? AND ? ";array_push($p,$f['from'],$f['to']);if($f['status']!==''){$w.=" AND h.hiring_status=? ";$p[]=$f['status'];}if($f['offer']!==''){$w.=" AND h.offer_status=? ";$p[]=$f['offer'];}if($f['onboarding']!==''){$w.=" AND h.onboarding_status=? ";$p[]=$f['onboarding'];}if($f['vacancy_id']!==''){$w.=" AND h.vacancy_id=? ";$p[]=(int)$f['vacancy_id'];}if($f['keyword']!==''){$kw='%'.$f['keyword'].'%';$w.=" AND (h.hiring_no LIKE ? OR a.applicant_no LIKE ? OR a.applicant_name LIKE ? OR v.vacancy_no LIKE ? OR v.vacancy_title LIKE ?) ";array_push($p,$kw,$kw,$kw,$kw,$kw);}return $w;}
$draw=isset($_POST['draw'])?(int)$_POST['draw']:1;$start=isset($_POST['start'])?max(0,(int)$_POST['start']):0;$length=isset($_POST['length'])?(int)$_POST['length']:25;if($length<=0||$length>500)$length=25;
$f=hd_filters();$p=array();$w=hd_where($f,$p);
$base=" FROM erp_hiring h LEFT JOIN erp_selection_result s ON s.id=h.selection_result_id LEFT JOIN erp_applicant_data a ON a.id=h.applicant_id LEFT JOIN erp_job_vacancy v ON v.id=h.vacancy_id LEFT JOIN erp_employee_master emp ON emp.id=h.hired_employee_id LEFT JOIN erp_employee_master rec ON rec.id=h.recruiter_employee_id LEFT JOIN erp_employee_master hm ON hm.id=h.hiring_manager_employee_id ";
$kpi=$db->fetch("SELECT COUNT(*) total,SUM(h.offer_status='ACCEPTED') accepted_count,SUM(h.hiring_status IN ('HIRED','ONBOARDED')) hired_count,SUM(h.onboarding_status='COMPLETED') onboarded_count,SUM(h.hiring_status IN ('CANCELLED','DECLINED')) failed_count,AVG(NULLIF(h.checklist_done/NULLIF(h.checklist_total,0)*100,0)) progress_avg $base $w",$p);
$cnt=$db->fetch("SELECT COUNT(*) jml $base $w",$p);$total=$cnt?(int)$cnt->jml:0;
$orderMap=array(2=>'h.hiring_no',3=>'a.applicant_name',4=>'v.vacancy_no',5=>'h.hiring_status',6=>'h.offer_status',7=>'h.onboarding_status',8=>'h.planned_join_date',9=>'h.salary_amount',10=>'h.updated_at');$orderBy='h.hiring_date DESC,h.hiring_no DESC';
if(isset($_POST['order'][0]['column'])){$col=(int)$_POST['order'][0]['column'];$dir=(isset($_POST['order'][0]['dir'])&&strtolower($_POST['order'][0]['dir'])==='desc')?'DESC':'ASC';if(isset($orderMap[$col]))$orderBy=$orderMap[$col].' '.$dir;}
$rows=$db->query("SELECT h.*,s.selection_no,a.applicant_no,a.applicant_name,a.applicant_status,v.vacancy_no,v.vacancy_title,emp.employee_no hired_no,emp.full_name hired_name,rec.employee_no recruiter_no,rec.full_name recruiter_name,hm.employee_no manager_no,hm.full_name manager_name $base $w ORDER BY $orderBy LIMIT $start,$length",$p);
$data=array();$no=$start+1;foreach($rows as $r){$canDelete=in_array($r->hiring_status,array('DRAFT','CANCELLED','DECLINED'),true);$progress=(int)$r->checklist_total>0?round(((int)$r->checklist_done/(int)$r->checklist_total)*100):0;$act='<div class="hr-action"><button class="btn btn-info btn-xs btn-hd-detail" data-id="'.(int)$r->id.'"><i class="fa fa-eye"></i></button> <button class="btn btn-primary btn-xs btn-hd-edit" data-id="'.(int)$r->id.'"><i class="fa fa-pencil"></i></button> <button class="btn btn-success btn-xs btn-hd-status" data-id="'.(int)$r->id.'" data-status="HIRED"><i class="fa fa-user"></i></button> <button class="btn btn-warning btn-xs btn-hd-status" data-id="'.(int)$r->id.'" data-status="OFFER_ACCEPTED"><i class="fa fa-check"></i></button> <button class="btn btn-danger btn-xs btn-hd-delete" data-id="'.(int)$r->id.'" data-no="'.hd_h($r->hiring_no).'"'.($canDelete?'':' disabled').'><i class="fa fa-trash"></i></button></div>';
  $data[]=array($no++,$act,'<strong>'.hd_h($r->hiring_no).'</strong><br><small>'.hd_h($r->selection_no?:'-').'</small>','<strong>'.hd_h($r->applicant_no.' - '.$r->applicant_name).'</strong><br><small>'.hd_h($r->applicant_status).'</small>','<strong>'.hd_h($r->vacancy_no?:'-').'</strong><br><small>'.hd_h($r->vacancy_title?:'-').'</small>',hd_label($r->hiring_status).'<br><small>'.hd_h($r->hiring_type).'</small>','<span class="label label-info">'.hd_h($r->offer_status).'</span><br><small>'.hd_h($r->contract_status).'</small>','<div class="progress progress-xs"><div class="progress-bar progress-bar-success" style="width:'.$progress.'%"></div></div><small>'.hd_h($r->onboarding_status).' '.$progress.'%</small>',hd_h(($r->planned_join_date?:'-').' / '.($r->actual_join_date?:'-')).'<br><small>'.hd_h($r->hired_no?($r->hired_no.' - '.$r->hired_name):'-').'</small>','<strong>'.hd_h($r->currency).'</strong> '.number_format((float)$r->salary_amount,2).'<br><small>'.hd_h($r->pay_grade?:'-').'</small>',hd_h($r->updated_by?:$r->created_by?:'-').'<br><small>'.hd_h($r->updated_at?:$r->created_at).'</small>');}
header('Content-Type: application/json; charset=utf-8');echo json_encode(array('draw'=>$draw,'recordsTotal'=>$total,'recordsFiltered'=>$total,'data'=>$data,'kpi'=>array('total'=>$kpi?(int)$kpi->total:0,'accepted'=>$kpi?(int)$kpi->accepted_count:0,'hired'=>$kpi?(int)$kpi->hired_count:0,'onboarded'=>$kpi?(int)$kpi->onboarded_count:0,'failed'=>$kpi?(int)$kpi->failed_count:0,'progress'=>$kpi?number_format((float)$kpi->progress_avg,2):'0.00')));
?>
